Aufwands_Kosten_Kontrolle
ManagingProjectsSuccessfully/ManagingProjectsSuccessfully.github.io pull request #100
Opened 2021-11-22 14:58 UTC by Steffi226

2021-11-27 12:34 UTC, DeniseWt requested changes
| Kriterium | Bewertung|
|-----|---|
| Front-Matter | ja |
| Umfang | ja|
| Belege | ja |
| Links | ja|
| Formatierung | ja|
| Verlinkungen vorhanden | ja |
| Abbildungen | ja |
| Strukturierung des Beitrags | 9 |
| Rechtschreibung | 8 |
| Sprache | 9 |
| Inhalt | 9|
| Einordnung in den Kontext | 8 |
| Ansprechend für Zielgruppe | 10 |

# Zusammenfassung

Der Beitrag beinhaltet das regelmäßige Kontrollieren des Aufwands in Bezug auf die bisher angefallenen Kosten. Dies kann auch analytisch anhand der Earned Value Analyse verdeutlicht werden.

# Positive Aspekte

Positiv angefallen sind vor allem die zahlreichen Verlinkungen zu angrenzenden Beiträgen, sodass man sofort weiß, wo man bei näherem Interessen nachlesen kann. Auch der Inhalt wurde kurz und prägnant gehalten, wobei man sich auf die Kernpunkte fokussiert hat. Somit fühlt man sich am Ende des Beitrages gut informiert.

# Negative Aspekte

Bei der Rechtschreibung müsste das Wort "präziese" in Zeile 28 auf "präzise" geändert werden.  Außerdem sollte in Zeile 41 nach " notwendig ist" noch ein Punkt eingefügt werden.  
Des Weiteren wäre es vielleicht hilfreich in Zeile 28 nach dem Wort Earned Value Analysis die Abkürzung EVA in Klammern zu ergänzen, sodass man im Folgenden sofort den Bezug dazu herstellen kann.

2021-11-27 13:23 UTC, DeniseWt requested changes
| Kriterium | Bewertung|
|-----|---|
| Front-Matter | ja |
| Umfang | ja|
| Belege | ja |
| Links | ja|
| Formatierung | ja|
| Verlinkungen vorhanden | ja |
| Abbildungen | ja |
| Strukturierung des Beitrags | 8 |
| Rechtschreibung | 8 |
| Sprache | 9 |
| Inhalt | 9|
| Einordnung in den Kontext | 8 |
| Ansprechend für Zielgruppe | 10 |

# Zusammenfassung

Der Beitrag beinhaltet das regelmäßige Kontrollieren des Aufwands in Bezug auf die bisher angefallenen Kosten. Dies kann auch analytisch anhand der Earned Value Analyse verdeutlicht werden.

# Positive Aspekte

Positiv angefallen sind vor allem die zahlreichen Verlinkungen zu angrenzenden Beiträgen, sodass man sofort weiß, wo man bei näherem Interessen nachlesen kann. Auch der Inhalt wurde kurz und prägnant gehalten, wobei man sich auf die Kernpunkte fokussiert hat. Somit fühlt man sich am Ende des Beitrages gut informiert.

# Negative Aspekte

Bei der Rechtschreibung müsste das Wort "präziese" in Zeile 28 auf "präzise" geändert werden.  Außerdem sollte in Zeile 41 nach " notwendig ist" noch ein Punkt eingefügt werden.  
Des Weiteren wäre es vielleicht hilfreich in Zeile 28 nach dem Wort Earned Value Analysis die Abkürzung EVA in Klammern zu ergänzen, sodass man im Folgenden sofort den Bezug dazu herstellen kann. 




Scrum Überprüfung:

| Kriterium | Bewertung|
|-----|---|
| Front-Matter | ja |
| Umfang |nein|
| Belege | ja |
| Links | ja |
| Formatierung | ja |
| Verlinkungen vorhanden | ja |
| Abbildungen | ja |
| Strukturierung des Beitrags | 9 |
| Rechtschreibung | 10 |
| Sprache | 10 |
| Inhalt | 8 |
| Einordnung in den Kontext | 10 |
| Ansprechend für Zielgruppe | 9 |

# Zusammenfassung

Der Artikel befasst sich mit dem Ablauf und Durchführung der Scrum Überprüfung, welche ein Teil der drei Säulen darstellt . Es nimmt auf die einzelnen Schritte in einem Sprint Bezug und hinterfragt diese kritisch. 

# Positive Aspekte

Sowohl die Rechtschreibung als auch die Sprache in dem Beitrag sind einwandfrei, sodass in dieser Hinsicht keine weiteren Verbesserungsvorschläge nötig sind. Auch wird dabei Bezug auf weitere Beiträge genommen, indem diese kurz angeschnitten werden und deren Funktionen in der Überprüfung deutlich gemacht werden. Auch zahlreiche Verlinkungen wurden gesetzt. Des Weiteren gibt es dem Leser Auskunft über die wichtigsten Punkte.

# Negative Aspekte

Hierbei ist zu erwähnen, dass der Umfang ein wenig zu gering ist und somit ausbaufähig wäre. Eventuell könnte man dafür noch mehr zu dem Konzept der drei Säulen erklären oder über den genauen Ablauf der Überprüfung? Z.B. wer daran beteiligt ist, wann genau es stattfindet...
Des Weiteren ist mir der extra Absatz zu Sprint Retrospektive nicht ganz klar, da er doch eigentlich noch Inhalt des Absatzes davor ist oder?

2021-12-07 09:19 UTC, Magnus-schn reviewed
Aufwands_Kosten_Kontrolle

| Kriterium | Bewertung|
|-----|---|
| Front-Matter | ja |
| Umfang | ja |
| Belege | ja |
| Links | ja |
| Formatierung | ja |
| Verlinkungen vorhanden | ja |
| Abbildungen | ja |
| Strukturierung des Beitrags | 9 |
| Rechtschreibung | 9 |
| Sprache | 10 |
| Inhalt | 9 |
| Einordnung in den Kontext | 10 |
| Ansprechend für Zielgruppe | 10 |

# Zusammenfassung

Der Artikel befasst sich mit der Kalkulation von Projektkosten und geht dabei besonders auf die Earned-Value-Analyse ein. 

# Positive Aspekte

Die Struktur des Artikels ist sehr gut und übersichtlich. Insbesondere die Abbildung ist passend und ansprechend platziert.

# Negative Aspekte

Mich persönlich stört das Aufzählungszeichen bei nur einem Unterpunkt. Des Weiteren könnte der Artikel sich noch etwas mehr vom Artikel zu Earned-Value-Analyse abheben.

Scrum_Ueberpruefung

| Kriterium | Bewertung|
|-----|---|
| Front-Matter | ja |
| Umfang | ja |
| Belege | ja |
| Links | ja |
| Formatierung | ja |
| Verlinkungen vorhanden | ja|
| Abbildungen | ja |
| Strukturierung des Beitrags | 8 |
| Rechtschreibung | 9 |
| Sprache | 9 |
| Inhalt | 10 |
| Einordnung in den Kontext | 10 | 
| Ansprechend für Zielgruppe | 10 |

# Zusammenfassung

Der Artikel befasst sich mit der Scrum-Theorie und geht dabei insbesondere auf die zweite Säule: Überprüfung ein.

# Positive Aspekte

Sehr interessanter Artikel, der gerade wegen den vielen Beispielen sehr verständlich ist. 

# Negative Aspekte

Man könnte im Text selbst noch verlinkungen einfügen, sodass der Leser Intuitiv zu weiteren Artikeln springen kann. Außerdem ist der Artikel noch etwas kurz.

2021-12-07 20:24 UTC, AbleAn requested changes
| Kriterium | Bewertung|
|-----|---|
| Front-Matter | ja |
| Umfang | Nein|
| Belege | ja |
| Links | ja|
| Formatierung | ja|
| Verlinkungen vorhanden | ja|
| Abbildungen | ja |
| Strukturierung des Beitrags | 10 |
| Rechtschreibung | 10 |
| Sprache |10 |
| Inhalt | 9|
| Einordnung in den Kontext | 9|
| Ansprechend für Zielgruppe | 10|

# Zusammenfassung

Der Artikel befasst sich mit der Aufwands_Kosten_Kontrolle mit besonderem Fokus auf die Earned Value Analyse.

# Positive Aspekte

Der Aufbau ist gut nachvollziehbar. Sprachlich ist der Artikel sehr schön zu lesen. Besonders angenehm gestaltet ist das Kapitel Earned Value Analyse. Außerdem wurde stets mit Belegen gearbeitet.

# Negative Aspekte 

Es könnte noch mehr mit Verlinkungen im Text zu angrenzenden Themen gearbeitet werden. Der Text ist leider etwas kurz geraten und könnte noch durch 1-2 Unterpunkte ergänzt werden.

Rechtschreibung:

Erster Satz im Kapitel Earned Aalue Analyse: präzise
Beim zweiten Stichpunkt: multipliziert
Im vorletzten Satz: Mehrzahl oder Einzahl anpassen

2021-12-09 19:27 UTC, merged