Compliance_im_Projektmanagment
ManagingProjectsSuccessfully/ManagingProjectsSuccessfully.github.io pull request #109
Opened 2021-11-22 17:12 UTC by moritzgrt

2021-12-03 11:50 UTC, Leni2505 requested changes
| Kriterium | Bewertung|
|-----|---|
| Front-Matter | ja |
| Umfang | nein|
| Belege | ja |
| Links | ja |
| Formatierung | ja |
| Verlinkungen vorhanden | ja |
| Abbildungen | nein |
| Strukturierung des Beitrags | 10 |
| Rechtschreibung | 10 |
| Sprache | 10 |
| Inhalt | 10|
| Einordnung in den Kontext | 10|
| Ansprechend für Zielgruppe | 9 |

# Zusammenfassung

Der Beitrag gibt einen sehr guten Überblick zum Thema Compliance im Projektmanagement. 

In diesem Artikel wird sowohl auf die rechtlichen Grundlagen, die Integration von Compliance in Unternehmen, die Risiken und Präventionen als auch auf die Einordnung in den Gesamtkontext eingegangen. 


# Positive Aspekte

Die Meta-Daten sind alle korrekt ausgefüllt. 
Die Textabschnitte wurden mit den entsprechenden Quellen belegt und die Formatierungen sind ebenfalls alle richtig. 

In diesem Beitrag wurde mehrmals zu thematisch angrenzenden Artikeln verlinkt, wodurch er sehr gut in den Gesamtkontext eingeordnet wird. 

Außerdem finde ich, dass der Beitrag Inhaltlich wirklich gelungen ist.
Er ist logisch strukturiert, verständlich geschrieben und vermittelt einen guten ersten Einblick zum Thema Compliance im Projektmanagement.

# Negative Aspekte

Der Artikel ist mit ca. 580 Wörtern leider nicht mehr im Toleranzbereich von +/- 10% von den geforderten 500 Wörtern. Vielleicht könnte ein Abschnitt noch etwas gekürzt oder anhand einer Tabelle darstellt werden? Dann wäre dein Beitrag zusätzlich noch ein bisschen anschaulicher. 

Zum Thema Rechtschreibung ist dir lediglich im Absatz "Integration von Compliance im Unternehmen" im 2. Satz ein kleiner Fehler unterlaufen. Ich denke, du wolltest an Stelle von "Vollstädigkeit" Vollständigkeit schreiben. 

Außerdem fehlt im fünften Satz dieses Abschnitts nach "... analysiert werden" ein Komma. 

Leider konnte ich deine Abbildung zur Compliance Kultur nicht öffnen.

2021-12-06 14:18 UTC, ow79arux requested changes
| Kriterium | Bewertung|
|-----|---|
| Front-Matter | ja|
| Umfang | ja/|
| Belege | ja |
| Links | ja|
| Formatierung | ja|
| Verlinkungen vorhanden | ja |
| Abbildungen | ja |
| Strukturierung des Beitrags | 8 |
| Rechtschreibung | 7|
| Sprache | 8 |
| Inhalt | 9|
| Einordnung in den Kontext | 10|
| Ansprechend für Zielgruppe | 8|

# Zusammenfassung

Der Artikel gibt eine gute Zusammenfassung zum Thema Compliance im Projektmanagement. Es wird auf verschiedene Unterthemen eingegangen und dementsprechend gegliedert..

# Positive Aspekte

- schöne Abbildung
- gute Gliederung
- viele Links und Belege
- angenehm zu lesen


# Negative Aspekte

- einige Tippfehler in der Rechtschreibung 
- ein paar Fehler in der Zeichensetzung, vor allem Kommas
- "Abschließende Bemerkung und Einordnung in den Gesamtkontext" würde ich glaub ich anders benennen. Das ist sehr lang und nicht so ansprechend für das Ende eines Artikels

2021-12-08 14:01 UTC, moritzgrt commented
Danke für das Feedback, ich habe die Rechtschreibfehler überarbeitet und das fehlende Komma hinzugefügt...
Wegen dem Umfang wurde ja alles in MS Teams geklärt. Die Abbildung ist bei mir ganz normal zu sehen und scheint auch bei ow79arux keine Probleme zu verursachen...
Wisst ihr ob es ausreichend ist, den neuen (für euch hoffentlich sichtbaren) Commit einfach zu machen oder muss ich einen komplett neuen Pullrequest stellen?
Danke und LG

2021-12-08 17:08 UTC, eftalyaumat requested changes
| Kriterium | Bewertung|
|-----|---|
| Front-Matter | ja |
| Umfang | ja |
| Belege | ja |
| Links | ja |
| Formatierung | ja |
| Verlinkungen vorhanden | ja |
| Abbildungen | ja |
| Strukturierung des Beitrags | 1-10 |
| Rechtschreibung | 1-10|
| Sprache | 1-10 |
| Inhalt | 1-10|
| Einordnung in den Kontext | 10 |
| Ansprechend für Zielgruppe | 10 |

# Zusammenfassung

Der Beitrag befasst sich mit der Bedeutung des Compliance Managements für das Projektmanagement, dabei wird auf die Punkte rechtliche Grundlagen, Integration von Compliance im Unternehmen und Risiken und Prävention näher eingegangen. 

# Positive Aspekte

Der Artikel überzeugt insbesondere inhaltlich. Es wird anschaulich beschrieben was unter dem Begriff Compliance zu verstehen ist und welche Rolle dieses Thema für Unternehmen spielt. Sehr gut ist dem Autor auch die Einordnung in den Gesamtkonzept und der Bezug zum Projektmanagement gelungen. Die Abbildung wurde passend zum Thema gewählt und unterstützt das Verständnis. Die Links funktionieren und die Mindestanzahl an Wörtern wurde mit knapp 580 Wörtern auch erreicht. Auch sind einige Verlinkungen zu anderen Beiträgen im Kompendium vorhanden. 

# Negative Aspekte

Leider ist die Angabe von Quellen nicht ganz korrekt, da hier statt die hochgestellten Zahlen mit Verlinkung zu verwenden, die Quellen in Klammern hinter dem Satz angegeben wurden. Sprachlich sind auch einige Fehler eingeschlichen, z.B. wird "keineswegs" zusammen und kleingeschrieben. Im Absatz "Integration von Compliance im Unternehmen" fehlt im vorletzten Satz bei ständig das n und auch einige Kommafehler sind mir aufgefallen. Oft fehlt ein Komma vor "wenn", "ob" oder "um". Da wäre es ganz gut, den ganzen Beitrag nochmal gründlich hinsichtlich dieser Punkte zu überprüfen.

2021-12-09 19:28 UTC, merged

2021-12-13 11:56 UTC, moritzgrt commented
Also...Rechtschreibung und Kommafehler sollten nun alle behoben sein, Verlinkungen auf externe Seiten wurden entfernt und die Überschrift wurde angepasst. @eftalyaumat die Quellennachweise sollten so eigentlich in Ordnung sein, da es uns ja frei gestellt wurde wie wir unsere Nachweise gestalten und wir uns lediglich an Wikipedia orientieren sollten... Meines Wissens nach wird "keineswegs" klein und zusammen geschrieben...
LG