Erster Wurf Integrationsmanagement.md
ManagingProjectsSuccessfully/ManagingProjectsSuccessfully.github.io pull request #114
Opened 2021-11-22 18:24 UTC by ow79arux

2021-11-27 21:56 UTC, si18k1 requested changes
| Kriterium | Bewertung|
|-----|---|
| Front-Matter | ja |
| Umfang | ja|
| Belege | ja |
| Links | nein|
| Formatierung | ja|
| Verlinkungen vorhanden | ja|
| Abbildungen | ja|
| Strukturierung des Beitrags | 8 |
| Rechtschreibung | 5|
| Sprache | 7 |
| Inhalt | 8|
| Einordnung in den Kontext | 9|
| Ansprechend für Zielgruppe | 8|

# Zusammenfassung

Der Artikel "Integrationsmanagement" beschreibt, was der Begriff grundlegend bedeutet, wofür das Integrationsmanagement verwendet wird und gibt Aufschluss über die Aufgaben und Soft-Skills eines Projektleiters. Darüber hinaus werden die Kommunikation und Prozesse genauer erläutert. Es besteht ein Bezug zum "Projektmanagement".

# Positive Aspekte

Die Abbildung ist gut gelungen und wird durch anhand des Texts noch einmal sprachlich erläutert. Auch ist eine Tabelle vorhanden.

Inhaltlich ist alles relevante zu dem Thema gegeben.

Durch Abschnitte ist der Text sehr leserlich gestaltet. Die Überschriften passen dazu.

Die Links zu den Quellen funktionieren. Ebenso bei der weiterführenden Literatur.

Es ist ein Bezug zu angrenzenden Themen (Projektmanagement) gegeben.

# Negative Aspekte

Den ersten Abschnitt könnte man in einem Unterpunkt wie z.B. "Definition des Begriffs" wiedergeben.

Es sind einige sprachliche Fehler unterlaufen. Im ersten Abschnitt (siehe Prozesse) fehlt ein "man". Im folgenden Satz müsste es "Abschluss" statt "Abschließung" heißen, auch fehlt das "d" bei "des". 

Die Tabelle könnte meiner Meinung nach Stichpunkte enthalten. Es fehlt die Bezeichnung "Abbildung".

Im ersten Abschnitt von "Kommunikation" fehlt der Quellenbeleg.

Die Links bei "Siehe auch" funktionieren nicht.

Bei den Quellen fehlen die Titel. Es ist lediglich der Link angegeben.

Eventuell könnte man ein paar Stichpunkte (z.B. bei den Aufgaben des Projektleiters) einbauen. Dies erleichtert das Lesen.

2021-12-03 11:39 UTC, Leni2505 requested changes
| Kriterium | Bewertung|
|-----|---|
| Front-Matter | ja |
| Umfang | nein |
| Belege | ja |
| Links | ja |
| Formatierung | ja |
| Verlinkungen vorhanden | ja |
| Abbildungen | ja |
| Strukturierung des Beitrags | 10 |
| Rechtschreibung | 9 |
| Sprache | 9 |
| Inhalt | 9 |
| Einordnung in den Kontext | 10 |
| Ansprechend für Zielgruppe | 10 |

# Zusammenfassung

Dieser Beitrag gibt insgesamt einen guten Überblick zum Thema Integrationsmanagement.
 
Es wird auf unterschiedliche Aspekte eingegangen, zu denen unter anderem der Prozess des Integrationsmanagements, die Aufgaben eines Projektleiters sowie notwendige Soft Skills zählen. 
Das Thema wird dem Leser anschaulich mit Hilfe von Tabellen und Grafiken vermittelt. 


# Positive Aspekte

Die Front-Matter wurden korrekt ausgefüllt. 

Die verwendeten Quellen wurden verlinkt und die Formatierung des Beitrags ist ebenfalls richtig. 

Deine erstellte Grafik finde ich sehr gut und die Tabelle ist dir ebenfalls gelungen.

Zudem folgt dein Beitrag einer klaren Struktur und ist logisch aufgebaut. 

Außerdem schaffst du mit Hilfe der Verlinkungen zu anderen Beiträgen einen Bezug zu angrenzenden Themengebieten.


# Negative Aspekte

Leider bist du mit ca. 570 Wörtern nicht mehr im Toleranzbereich von +/-10% von den geforderten 500 Wörtern. 

Bei der Rechtschreibung und der Kommasetzung sind dir hier und da noch ein paar kleine Fehler unterlaufen.

Zudem denke ich, dass die Überschrift "Kommunikation" etwas weit gefasst ist.
 --> Vielleicht wäre hier eine Überschrift wie z.B.: "Kommunikation innerhalb der Projektplanung" o.ä. ein bisschen treffender?

2021-12-08 15:18 UTC, eftalyaumat requested changes
| Kriterium | Bewertung|
|-----|---|
| Front-Matter | ja |
| Umfang | ja |
| Belege | ja |
| Links | nein |
| Formatierung | ja |
| Verlinkungen vorhanden | ja |
| Abbildungen | ja |
| Strukturierung des Beitrags | 9 |
| Rechtschreibung | 9 |
| Sprache | 8 |
| Inhalt | 10|
| Einordnung in den Kontext | 10|
| Ansprechend für Zielgruppe | 10|

# Zusammenfassung

Der Artikel beschreibt was unter dem Begriff Integrationsmanagement zu verstehen ist und aus welchen Teilschritten dieser besteht. Außerdem werden die Aspekte Kommunikation und die Rolle des Projektleiters näher erläutert.

# Positive Aspekte

Besonders gelungen ist die Eingliederung des Thema in den Gesamtkonzept und der Bezug zum Projektmanagement wird deutlich. Die selbst erstellte Graphik stellt die einzelnen Komponenten des Integrationsmanagements auch nochmal sehr anschaulich dar. Auch der vorgegeben Umfang an Wörtern wurde eingehalten. 


# Negative Aspekte

Bei der eigenen Abbildung fehlt der Quellennamen. Es würde vollständiger aussehen, wenn nach dem "auf Basis von" der Quellenname noch eingefügt werden würde. Bei Prozesse wird im zweiten Absatz im zweiten zweimal "aufgrund von" in einem Satz verwendet. Hier könnte man überlegen, ob man eines nicht durch einen anderen Ausdruck ersetzen könnte. Beim Unterpunkt Aufgaben fehlt vor "Abschlussbericht" der Artikel. Generell könnten die Überschriften etwas aussagekräftiger formuliert werden, wie z.B. "Gute Kommunikation als Schlüsselkompetenz". Leider fehlt auch die Angabe von Quelle Nummer 6.

2021-12-09 19:28 UTC, merged

2021-12-22 13:03 UTC, ow79arux commented
Die Fehler in Sprache und Rechtschreibung wurden behoben. Des Weiteren habe ich die Überschriften angepasst und die Aufgaben des Projektleiters in Stichpunkten dargestellt