Crunch Time + Scrum.org Institution
ManagingProjectsSuccessfully/ManagingProjectsSuccessfully.github.io pull request #142
Opened 2021-11-23 10:19 UTC by SimonM211

2021-11-28 15:28 UTC, nta01 requested changes
**Crunch_Time**

| Kriterium | Bewertung|
|-----|---|
| Front-Matter | ja |
| Umfang | ja|
| Belege | ja |
| Links | ja|
| Formatierung | ja|
| Verlinkungen vorhanden | ja|
| Abbildungen | ja |
| Strukturierung des Beitrags | 10 |
| Rechtschreibung | 10|
| Sprache | 6 |
| Inhalt | 10|
| Einordnung in den Kontext | 10|
| Ansprechend für Zielgruppe | 8|

# Zusammenfassung

Der Artikel behandelt die crunch time, diese steht für Zeitverzug in Projekten.

# Positive Aspekte

* Viele Quellen wurden verwendet
* Der Artikel ist übersichtlich gestaltet
* Es wurde auf die Github Pages anderer Studenten verwiesen

# Negative Aspekte

* Verwendung wertender Adjektive (z.B. einfach, schlecht, natürlich)
* Umgangssprachlich/ Der Text könnte noch etwas wissenschaftlicher formuliert werden
* Gerne Absätze verwenden, um das Lesen zu erleichtern

**SCRUM_org_Institution**

| Kriterium | Bewertung|
|-----|---|
| Front-Matter | ja|
| Umfang | ja|
| Belege | ja|
| Links | ja|
| Formatierung | ja|
| Verlinkungen vorhanden | ja |
| Abbildungen | ja |
| Strukturierung des Beitrags | 10 |
| Rechtschreibung | 10|
| Sprache | 8 |
| Inhalt | 10|
| Einordnung in den Kontext | 10|
| Ansprechend für Zielgruppe | 8|

# Zusammenfassung

Der Artikel behandelt die Organisation Scrum.org, diese dient zur Lösung von komplexen Problemen mit Hilfe von Scrum. 

# Positive Aspekte

* Viele Quellen wurden verwendet
* Der Artikel ist übersichtlich gestaltet
* Es wurde auf die Github Pages anderer Studenten verwiesen

# Negative Aspekte

* Auch hier ist der Sprachgebrauch etwas umgangssprachlich gestaltet, der Text könnte noch etwas wissenschaftlicher formuliert werden
* Ebenfalls gerne Absätze verwenden, um das Lesen zu erleichtern

2021-11-30 09:34 UTC, schooschef requested changes
| Kriterium | Bewertung|
|-----|---|
| Front-Matter | ja|
| Umfang | ja|
| Belege | ja|
| Links | ja |
| Formatierung | ja |
| Verlinkungen vorhanden | ja |
| Abbildungen | ja |
| Strukturierung des Beitrags | 9 |
| Rechtschreibung | 10 |
| Sprache | 8 |
| Inhalt | 10 |
| Einordnung in den Kontext | 10 |
| Ansprechend für Zielgruppe | 10 |

# Zusammenfassung

Der Artikel erklärt Crunch-Time im Kontext des Projekmanagement. Es werden Ursachen, Folgen und Lösungen strukturiert und gut verständlich erklärt.

Der Artikel Scrum_org_Institution erläutert Entstehung, Angebot und Nutzen der Institution Scrum.org in deutlicher und klar gegliederter Form.


# Positive Aspekte

* Gut verständlich
* klare Sprache und Satzbau
* Sinnvolle Reihenfolge
* Praktische Hyperlinks an den richtigen Stellen

# Negative Aspekte

* Nur Fließtext (Crunch-Time) (evtl. auflösen via Umbrüchen/Tabellen)
* Eher Erzähler-Stil als Wikipedia-Stil zu Beginn

2021-12-05 11:53 UTC, starni26 requested changes
| Kriterium | Bewertung|
|-----|---|
| Front-Matter | ja |
| Umfang | ja |
| Belege | ja |
| Links | ja|
| Formatierung | ja/ nein|
| Verlinkungen vorhanden | ja |
| Abbildungen | ja |
| Strukturierung des Beitrags | 7 |
| Rechtschreibung | 8 |
| Sprache | 10 |
| Inhalt | 10 |
| Einordnung in den Kontext | 10 |
| Ansprechend für Zielgruppe | 10 |

# Zusammenfassung

Der Artikel behandelt das Thema 'Crunch Time', den entstehenden Zeitverzug im Projektmanagement. Er ist untergliedert in Ursachen, Folgen und Lösungen. 

# Positive Aspekte

- leicht verständliche Sätze, was den Inhalt leichter greifbar macht
- der Kontext wurde gut rüber gebracht

# Negative Aspekte

- vereinzelt Rechtschreib- bzw. Zeichensetzungsfehler
- auf die Abbildung wurde nicht näher hingewiesen

2021-12-06 14:07 UTC, SimonM211 commented
> Kriterium	Bewertung
> Front-Matter	ja
> Umfang	ja
> Belege	ja
> Links	ja
> Formatierung	ja/ nein
> Verlinkungen vorhanden	ja
> Abbildungen	ja
> Strukturierung des Beitrags	7
> Rechtschreibung	8
> Sprache	10
> Inhalt	10
> Einordnung in den Kontext	10
> Ansprechend für Zielgruppe	10
> # Zusammenfassung
> Der Artikel behandelt das Thema 'Crunch Time', den entstehenden Zeitverzug im Projektmanagement. Er ist untergliedert in Ursachen, Folgen und Lösungen.
> 
> # Positive Aspekte
> * leicht verständliche Sätze, was den Inhalt leichter greifbar macht
> * der Kontext wurde gut rüber gebracht
> 
> # Negative Aspekte
> * vereinzelt Rechtschreib- bzw. Zeichensetzungsfehler
> * auf die Abbildung wurde nicht näher hingewiesen

2021-12-06 14:13 UTC, SimonM211 commented
Hallo zusammen,

Erstmal danke für die Reviews und vor allem für die konstruktiven Verbesserungsvorschläge. 

@starni26 darf ich fragen, warum du bei der Formatierung "ja/nein" geschrieben hast?

2021-12-09 19:28 UTC, merged

2021-12-13 13:31 UTC, starni26 commented
@SimonM211 muss wohl ein Versehen gewesen sein. Da steht ja