Abschlussanalyse
ManagingProjectsSuccessfully/ManagingProjectsSuccessfully.github.io pull request #170
Opened 2021-11-23 12:00 UTC by medjeara

2021-11-30 17:01 UTC, FerdinandMerbecks requested changes
| Kriterium | Bewertung|
|-----|---|
| Front-Matter | ja |
| Umfang | ja |
| Belege | ja |
| Links | ja |
| Formatierung | nein |
| Verlinkungen vorhanden | ja |
| Abbildungen | ja |
| Strukturierung des Beitrags | 6 |
| Rechtschreibung | 8 |
| Sprache | 5 |
| Inhalt | 7 |
| Einordnung in den Kontext | 8 |
| Ansprechend für Zielgruppe | 5 |

# Zusammenfassung

Der Artikel führt zu Beginn passend zum Thema der Abschlussanalyse hin und rückt hierbei den Soll- Ist Vergleich in den Vordergrund. Anschließend erfolgt die Erläuterungen des Prozessablaufes der Abschlussanalyse. Teilweise gut von Beispielen untermauert fällt vor allem die fehlende Formatierung auf. Dies erschwert dann auch das Lesen des Beitrags, welcher durch passende Absätze und gegebenenfalls durch das Einfügen von Stichpunkten verständlicher gestaltet werden kann. Abgerundet wird der Artikel durch ein Fazit, welches 
durch den Plan-/ Istkostenvergleich hervorhebt.

# Positive Aspekte

- gute Einbindung in den Kontext
- durch Bild bessere Veranschaulichung 
- gute Strukturierung, kann aber im Mittelteil nochmal überarbeitet werden

# Negative Aspekte

- häufte Anwendungen von Umgangssprache
- Der Bereich "Prozessablauf Abschlussanalyse" ist inhaltlich ok, jedoch unstrukturiert und unübersichtlich
- Dadurch ist der Artikel nicht mehr so ansprechend für die Zielgruppe

2021-11-30 21:48 UTC, Juliakau commented
| Kriterium | Bewertung|
|-----|---|
| Front-Matter | ja |
| Umfang | ja |
| Belege | ja |
| Links | ja |
| Formatierung | nein|
| Verlinkungen vorhanden | ja |
| Abbildungen | ja |
| Strukturierung des Beitrags | 5 |
| Rechtschreibung | 8 |
| Sprache | 9 |
| Inhalt | 10 |
| Einordnung in den Kontext | 10 |
| Ansprechend für Zielgruppe | 10 |

# Zusammenfassung

Der Artikel ist sehr schön geschrieben und liest sich leicht. Man bekommt einen guten Einblick. Jedoch ist der Ablauf ein großer Absatz, vielleicht noch unterteilen und zB die Vorteile am Ende in einen extra Unterpunkt schreiben. Kleine Absätze lassen sich einfacher verstehen als ein langer. Ab und zu sind sehr lange Sätze, die dadurch zu komplex und unverständlich werden. Ab und zu sind Wortwiederholungen drin, zB 'auch'. Achte zudem auf die Rechtschreibung, ab und zu werden falsche Artikel verwendet (liegt teilweise auch an den zu verschachtelten Sätzen).

# Positive Aspekte

- sehr Verständlich
- meistens fachlich geschrieben
- guter Aufbau zu Beginn (Unterabsätze am Ende einfügen)

# Negative Aspekte

- kürzere Sätze. Lieber mal 2 Sätze daraus machen
- Rechtschreibung nochmal kontrollieren
- Absätze machen

2021-12-05 21:26 UTC, Juliakau reviewed
| Kriterium | Bewertung|
|-----|---|
| Front-Matter | ja |
| Umfang | ja |
| Belege | ja |
| Links | ja |
| Formatierung | nein|
| Verlinkungen vorhanden | ja |
| Abbildungen | ja |
| Strukturierung des Beitrags | 5 |
| Rechtschreibung | 8 |
| Sprache | 9 |
| Inhalt | 10 |
| Einordnung in den Kontext | 10 |
| Ansprechend für Zielgruppe | 10 |

# Zusammenfassung

Der Artikel ist sehr schön geschrieben und liest sich leicht. Man bekommt einen guten Einblick. Jedoch ist der Ablauf ein großer Absatz, vielleicht noch unterteilen und zB die Vorteile am Ende in einen extra Unterpunkt schreiben. Kleine Absätze lassen sich einfacher verstehen als ein langer. Ab und zu sind sehr lange Sätze, die dadurch zu komplex und unverständlich werden. Ab und zu sind Wortwiederholungen drin, zB 'auch'. Achte zudem auf die Rechtschreibung, ab und zu werden falsche Artikel verwendet (liegt teilweise auch an den zu verschachtelten Sätzen).

# Positive Aspekte

- sehr Verständlich
- meistens fachlich geschrieben
- guter Aufbau zu Beginn (Unterabsätze am Ende einfügen)

# Negative Aspekte

- kürzere Sätze. Lieber mal 2 Sätze daraus machen
- Rechtschreibung nochmal kontrollieren
- Absätze machen

2021-12-08 19:57 UTC, ValerieGF requested changes
| Kriterium | Bewertung|
|-----|---|
| Front-Matter | ja |
| Umfang | ja|
| Belege | ja |
| Links | ja|
| Formatierung | nein|
| Verlinkungen vorhanden | ja |
| Abbildungen | ja |
| Strukturierung des Beitrags | 7 |
| Rechtschreibung | 8|
| Sprache | 7 |
| Inhalt | 10|
| Einordnung in den Kontext | 10|
| Ansprechend für Zielgruppe | 10|

# Zusammenfassung

Der Artikel beginnt mit einer Einführung ins Thema der Abschlussanalyse. Danach wird die konkrete Aufgabe der Abschlussanalyse mit dem Soll-Ist-Vergleich erläutert. Daraufhin wird genauer auf den Prozessablauf eingegangen und abschließend wird ein Fazit gezogen, wo nochmals die große Rolle des Plan-/Istkostenvergleich hervorgehoben wird. Der Text ist im Allgemeinen sehr gut geschrieben, allerdings wäre es ratsam den großen Abschnitt in kleinere Absätze zu untergliedern, dann wäre der Artikel leichter zu lesen.

# Positive Aspekte

•	Gute Struktur 
•	Inhalt ist verständlich 
•	Die Beispiele und die Abbildung untermauern gut den Inhalt 

# Negative Aspekte

•	Der Artikel enthält noch ein paar Rechtschreibfehler, am bestem mit einem   Rechtschreibprüfer drüber gehen
•	Den Absatz Prozessablauf in kleine Absätze unterteilen

2021-12-09 19:36 UTC, merged