Berichtswesen
ManagingProjectsSuccessfully/ManagingProjectsSuccessfully.github.io pull request #172
Opened 2021-11-23 13:40 UTC by FerdinandMerbecks

2021-11-27 09:04 UTC, PhilippWolfrum requested changes
| Kriterium | Bewertung|
|-----|---|
| Front-Matter | ja |
| Umfang | ja|
| Belege | ja |
| Links | ja|
| Formatierung | ja|
| Verlinkungen vorhanden | ja |
| Abbildungen | ja |
| Strukturierung des Beitrags | 4 |
| Rechtschreibung | 8|
| Sprache | 7 |
| Inhalt | 9|
| Einordnung in den Kontext | 9|
| Ansprechend für Zielgruppe | 5|

# Zusammenfassung

Der Artikel geht zu Beginn kurz auf das allgemeine Berichtswesen ein, bevor er anschließend auf die konkrete Ausgestaltung im Projektmanagement eingeht. Aufgaben und Ziele sind gut dargestellt, insbesondere auf die Unerlässlichkeit guter Daten wird in dem Artikel hingewiesen.
Es wird auch herausgestellt, dass das Berichtswesen kein notwendiges Übel ist, sondern ein entscheidender Faktor für ein erfolgreiches Projekt sein kann. 

# Positive Aspekte

- Der Artikel wird gut in den Projektkontext eingeordnet
- Leser*innen verstehen die Wichtigkeit von Berichtswesen
- Probleme in der Praxis wie die fehlende Motivation beim Erstellen werden aufgegriffen und adressiert

# Negative Aspekte

- Der Bereich "Erfolgsfaktor Berichtswesen" ist inhaltlich gut, jedoch etwas unstrukturiert und unübersichtlich
- Dadurch ist der Artikel nicht mehr so ansprechend für die Zielgruppe
- "Wie bereits erwähnt" sollte durch eine andere Formulierung ausgetauscht werden, da dies etwas flapsig klingt

2021-11-30 15:35 UTC, Juliakau commented
| Kriterium | Bewertung|
|-----|---|
| Front-Matter | ja |
| Umfang | ja |
| Belege | ja |
| Links | ja |
| Formatierung | ja |
| Verlinkungen vorhanden | ja |
| Abbildungen | ja |
| Strukturierung des Beitrags | 8 |
| Rechtschreibung | 9 |
| Sprache | 6 |
| Inhalt | 7 |
| Einordnung in den Kontext | 10 |
| Ansprechend für Zielgruppe | 10 |

# Zusammenfassung

Der Artikel ist inhaltlich gut zu verstehen, ohne dass man sich näher mit dem Thema auseinander setzen muss und gibt einen guten Einblick in das Arbeiten und die Wichtigkeit des Berichtswesen. Allgemein sollte der Artikel sachlicher gehalten werden (v.a. Einleitung) und der Satzbau überarbeitet werden. Sehr viele Kommas (teilweise falsch gesetzt) machen die Sätze sehr komplex und so das Thema schwerer zu verstehen. Allgemein ist der Artikel aber gut geschrieben, dass man trotz der langen Sätze weiß worum es geht. 

# Positive Aspekte

- gute Einbindung in den Kontext
- Das Thema ist gut erklärt, dadurch einfach zu verstehen
- Alle wichtigen Aspekte herausgefiltert und kompakt dargestellt

# Negative Aspekte

- Kommasetzung teilweise unpassend
- teilweise zu lange Sätze, die dadurch schwer zu verstehen sind
- Ziele sind inkl. Abbildung eine sehr lange Aufzählung

2021-12-05 18:15 UTC, eberto99 requested changes
| Kriterium | Bewertung|
|-----|---|
| Front-Matter | ja |
| Umfang | ja |
| Belege | ja |
| Links | ja |
| Formatierung | ja |
| Verlinkungen vorhanden | ja |
| Abbildungen | ja |
| Strukturierung des Beitrags | 8 |
| Rechtschreibung | 8 |
| Sprache | 7 |
| Inhalt | 9 |
| Einordnung in den Kontext | 10 |
| Ansprechend für Zielgruppe | 8 |

# Zusammenfassung

Der Beitrag beginnt mit einer kurzen Erklärung, was unter dem Berichtswesen zu verstehen ist. Der erste Abschnitt zeigt die Struktur des Beitrags im Folgenden auf.
Danach werden Aufgaben und Ziele gut dargelegt, als auch durch ein Bild visuell hervorgehoben.
Mit dem anschließenden Eingehen auf die Bedeutung des Berichtswesens wurden alle wichtigen Aspekte berücksichtigt. Das Fazit am Ende fasst den Artikel gut zusammen.

# Positive Aspekte
* Die Einordnung in den Kontext ist sehr gelungen, vor allem durch den Verweis auf angrenzende Themen
* Beitrag vermittelt kurz und prägnant das Wesentliche
* Notwendigkeit, als auch Sinn und Zweck der korrekten, ungeschönten Berichterstattung gut herausgearbeitet

# Negative Aspekte

* Umgangssprachliche Redewendungen sollten ausgetauscht werden, wie z.B. :"Wie der Name schon verrät, geht es kurz und knapp gesagt …"
* Ein paar zusätzliche Absätze bzw. Textumbrüche würden mehr Struktur geben und den Beitrag noch ansprechender machen
* Einige Sätze könnten für ein besseres Verständnis gekürzt und auf zwei Sätze aufgeteilt werden

2021-12-05 21:24 UTC, Juliakau reviewed
| Kriterium | Bewertung|
|-----|---|
| Front-Matter | ja |
| Umfang | ja |
| Belege | ja |
| Links | ja |
| Formatierung | ja |
| Verlinkungen vorhanden | ja |
| Abbildungen | ja |
| Strukturierung des Beitrags | 8 |
| Rechtschreibung | 9 |
| Sprache | 6 |
| Inhalt | 7 |
| Einordnung in den Kontext | 10 |
| Ansprechend für Zielgruppe | 10 |

# Zusammenfassung

Der Artikel ist inhaltlich gut zu verstehen, ohne dass man sich näher mit dem Thema auseinander setzen muss und gibt einen guten Einblick in das Arbeiten und die Wichtigkeit des Berichtswesen. Allgemein sollte der Artikel sachlicher gehalten werden (v.a. Einleitung) und der Satzbau überarbeitet werden. Sehr viele Kommas (teilweise falsch gesetzt) machen die Sätze sehr komplex und so das Thema schwerer zu verstehen. Allgemein ist der Artikel aber gut geschrieben, dass man trotz der langen Sätze weiß worum es geht. 

# Positive Aspekte

- gute Einbindung in den Kontext
- Das Thema ist gut erklärt, dadurch einfach zu verstehen
- Alle wichtigen Aspekte herausgefiltert und kompakt dargestellt

# Negative Aspekte

- Kommasetzung teilweise unpassend
- teilweise zu lange Sätze, die dadurch schwer zu verstehen sind
- Ziele sind inkl. Abbildung eine sehr lange Aufzählung

2021-12-09 19:36 UTC, merged