Earned_Value_Analyse und User_Story_INVEST_Methode
ManagingProjectsSuccessfully/ManagingProjectsSuccessfully.github.io pull request #174
Opened 2021-11-23 13:56 UTC by Juliakau

2021-11-28 08:41 UTC, PhilippWolfrum requested changes
| Kriterium | Bewertung|
|-----|---|
| Front-Matter | ja |
| Umfang | nein|
| Belege | ja |
| Links | ja/ nein|
| Formatierung | ja|
| Verlinkungen vorhanden | ja|
| Abbildungen | ja |
| Strukturierung des Beitrags | 7 |
| Rechtschreibung | 9|
| Sprache | 8 |
| Inhalt | 7|
| Einordnung in den Kontext | 7|
| Ansprechend für Zielgruppe | 8|

# Zusammenfassung 

Review zum Artikel EVA:
Der Artikel gibt einen guten Überblick über die EVA und zeigt auf warum es Sinn macht, nicht nur Zeit und Aufwand zu betrachten. Anhand der Durchführungsschritte könnte direkt in die Implementierung einer EVA gestartet werden.

# Positive Aspekte

- Abbildung für die Visualisierung sehr gut geeignet
- Einordnung in Bezug auf das magische Dreieck und Projektcontrolling

# Negative Aspekte

- Der Beitrag ist etwas zu lang und hat dabei für meinen Geschmack zu viele Gliederungsebenen
- Mehr Verlinkungen einfügen, beispielsweise zum Projektcontrolling

2021-11-28 08:54 UTC, PhilippWolfrum requested changes
| Kriterium | Bewertung|
|-----|---|
| Front-Matter | ja |
| Umfang | ja|
| Belege | ja |
| Links | ja|
| Formatierung | ja|
| Verlinkungen vorhanden | ja |
| Abbildungen | ja |
| Strukturierung des Beitrags | 8 |
| Rechtschreibung | 9|
| Sprache | 9 |
| Inhalt | 9|
| Einordnung in den Kontext | 10|
| Ansprechend für Zielgruppe | 8|

# Zusammenfassung

Review zum Artikel User_Story_INVEST_Methode:
In dem Artikel wird sehr gut beschrieben, wofür die INVEST-Methode genutzt wird und wie sie angewendet werden kann. Nach der allgemeinen Beschreibung einer User Story geht der Artikel anschließend auf die einzelnen Aspekt der Methode ein.

# Positive Aspekte

- Kurze Darstellung der INVEST Kriterien mit Übersetzung 
- Gute Einordnung in den Gesamtkontext 

# Negative Aspekte

- Gliederung etwas zu fein 
-

2021-11-30 15:07 UTC, Creed229 requested changes
# Zusammenfassung

Kurze Zusammenfassung beider Artikel:
Beide Artikel sind im Großen und Ganzen gelungen. Sprachlich ist allerdings in beiden Fällen, besonders in den Abschnitten mit Fließtext, noch Luft nach oben. Inhaltlich werden die wichtigsten Aspekte beleuchtet. Schade ist, dass die Kapitel "weiterführende Links" und "Siehe auch" komplett weggelassen wurden.
##
| Kriterium | Bewertung| **User_Story_INVEST_Methode**
|-----|---|
| Front-Matter | ja |
| Umfang | ja |
| Belege | ja|
| Links | ja|
| Formatierung | ja|
| Verlinkungen vorhanden |nein |
| Abbildungen | ja |
| Strukturierung des Beitrags | 8 |
| Rechtschreibung | 8 |
| Sprache | 6 |
| Inhalt | 9 |
| Einordnung in den Kontext | 4 |
| Ansprechend für Zielgruppe | 8 |


# Positive Aspekte
- beide Themen inhaltlich ausreichend beleuchtet 
- gute Struktur 
- Verlinkung von Schlüsselbegriffen 

# Negative Aspekte
- Rechtschreibfehler [eine(r), unterteilet]
- Grammatikfehler (z.B Absatz "Estimable": ...der User Story (ist) wird ...)
- Vor allem bei Erklärung der Keywords der Invest Methode zu unsachlicher Schreibstil 
- keine weiterführenden Links oder Referenzen zu angrenzenden Themengebiete 


---------------------------------------------------------------------------------------
| Kriterium | Bewertung| **Earned_Value_Analyse**
|-----|---|
| Front-Matter | ja |
| Umfang | nein |
| Belege | ja|
| Links | ja|
| Formatierung | ja|
| Verlinkungen vorhanden | nein |
| Abbildungen | ja |
| Strukturierung des Beitrags | 8 |
| Rechtschreibung | 9,5 |
| Sprache | 7  |
| Inhalt | 9 |
| Einordnung in den Kontext | 2 |
| Ansprechend für Zielgruppe | 8,5 |


# Positive Aspekte
- korrekte Grammatik 
- insgesamt guter Satzbau, sachlicher Schreibstil
- inhaltlich gut, sehr übersichtlich 
- gute Struktur


# Negative Aspekte

- Verwendung falscher Zeitformen im Abschnitt "Nutzen"; Bsp:"Das Ergebnis wäre trotz Kostenüberschreitung in diesem Moment positiv, denn die Kosten im Gesamtprojekt blieben gleich, jedoch wurde das Projekt schneller erledigt als geplant. "
- mit c.a 600 Wörtern zu lang 
- keine weiterführenden Links oder Referenzen zu angrenzenden Themengebiete 
- sprachlich Kapitel "Nutzen" und "Kosten- und Terminvarianzindex "nicht gut

2021-12-06 19:22 UTC, eberto99 requested changes
# Review zur Earned Value Analyse

| Kriterium | Bewertung|
|-----|---|
| Front-Matter | ja |
| Umfang | nein|
| Belege | ja |
| Links | ja|
| Formatierung | ja|
| Verlinkungen vorhanden | ja |
| Abbildungen | ja |
| Strukturierung des Beitrags | 8 |
| Rechtschreibung | 8|
| Sprache | 8 |
| Inhalt | 9|
| Einordnung in den Kontext | 8|
| Ansprechend für Zielgruppe | 8|

# Zusammenfassung

Anfangs wird der Begriff Earned Value Analyse erklärt und in den Gesamtkontext des Projektmanagements eingeordnet. Danach wird der Nutzen der EVA in Zusammenhang mit dem magischen Dreiecks anhand eines Beispiels gut aufgezeigt. Die Durchführungsschritte, als auch die Angabe der Kennzahlenberechnung zeigen den Ablauf gut dar.

# Positive Aspekte

* Nutzen wird durch Beispiel für Leser*innen sehr gut nachvollziehbar dargestellt
* Bild visualisiert zusammenfassend die vorherigen Beschreibungen zu den Kennzahlen auf einen Blick
* Umfassendes Thema auf die relevanten Aspekte begrenzt

# Negative Aspekte

* Bei ein paar Sätzen könnte die Satzstellung geändert werden, damit diese verständlicher sind, z.B. "Unterschieden werden kann bei Kostenüberschreitung beispielsweise zwischen Gesamtkosten anpassen und erhöhen oder Maßnahmen zur Kosteneinsparung einzuleiten."
* Für einen tieferen Einblick in die Kennzahlenanalyse wären weiterführende Literaturlinks hilfreich
* Verlinkung zum Thema Projektsteuerung würde die EVA mehr in den Gesamtkontext einbetten und damit den Zweck noch mehr verdeutlichen


# Review zur User Story Invest Methode

| Kriterium | Bewertung|
|-----|---|
| Front-Matter | ja |
| Umfang | ja|
| Belege | ja |
| Links | ja|
| Formatierung | ja|
| Verlinkungen vorhanden | ja |
| Abbildungen | ja |
| Strukturierung des Beitrags | 9 |
| Rechtschreibung | 8|
| Sprache | 8 |
| Inhalt | 9|
| Einordnung in den Kontext | 9|
| Ansprechend für Zielgruppe | 8|

# Zusammenfassung

Zu Beginn wird die User Story an sich in Zusammenhang mit Scrum beschrieben. Danach wird kurz der Ablauf einer User Story beschrieben und hier auch auf den anderen Beitrag zur User Story verlinkt. Den zweiten Teil des Beitrags nimmt die genaue Erklärung der Kriterien der INVEST Methode ein.

# Positive Aspekte

* Einordnung in den Gesamtkontext ist sehr gelungen, vor allem durch die Verweisung auf angrenzende Themen
* Inhaltlich wurde ausführlich auf die INVEST Kriterien eingegangen
* Bild zeigt gut auf einem Blick den Aufbau der User-Story


# Negative Aspekte

* Sprachlich könnten die Sätze sachlicher sein und der Satzbau verbessert werden, z.B. "wichtig ist zu beachten, dass …" --> wichtig zu beachten ist, dass
* Es könnten die doppelten Worterklärungen für die INVEST Kriterien gespart werden - die einfache Worterklärung mit Übersetzung ist bereits in der Auflistung gut aufgezeigt.

2021-12-09 19:36 UTC, merged