Wissenslandkarte, PRINCE2 7 Grundprinzipien
ManagingProjectsSuccessfully/ManagingProjectsSuccessfully.github.io pull request #184
Opened 2021-11-23 15:12 UTC by za22regi

Freue mich auf dein Review :)

2021-11-30 11:18 UTC, Larf4 requested changes
# Zur Landkarte
| Kriterium | Bewertung|
|-----|---|
| Front-Matter | ja |
| Umfang | ja|
| Belege | ja |
| Links | ja |
| Formatierung | ja |
| Verlinkungen vorhanden | ja |
| Abbildungen | ja|
| Strukturierung des Beitrags | 10 |
| Rechtschreibung | 10|
| Sprache | 10 |
| Inhalt | 10|
| Einordnung in den Kontext | 0|
| Ansprechend für Zielgruppe |10|

# Zusammenfassung

Der Artikel Erklärt, was eine Wissenslandkarte ist, weiterhin werden die verschiedenen Arten der Landkarten aufgeführt. Zuletzt werden Vor- und Nachteile von Wissenslandkarten elaboriert.

# Positive Aspekte

* Sehr schöner Artikel. Durch die vorangestellte Begriffserklärung wird der Leser abgeholt & er versteht das Konzept und die Gründe für die Nutzung. 
* Die Abbildung gibt einen guten Einblick in ein Beispiel
* Vor- und Nachteile fallen großzügig aus
* Format gefällt mir
* Verlikungen, v.A siehe auch gibt eine gute Einbettung in den Kontext

# Negative Aspekte
* Die Quelle zu Hildebrand, 1998 ist bei mir leider grau, anklicken nicht möglich.

# Für PRINCE
| Kriterium | Bewertung|
|-----|---|
| Front-Matter | ja |
| Umfang | ja |
| Belege | ja |
| Links | ja |
| Formatierung | ja |
| Verlinkungen vorhanden | nein |
| Abbildungen | ja |
| Strukturierung des Beitrags | 10 |
| Rechtschreibung | 10|
| Sprache | 10 |
| Inhalt | 10|
| Einordnung in den Kontext | 6 |
| Ansprechend für Zielgruppe | 10|

# Zusammenfassung

Der Beitrag geht intensiv auf die 7 Grundprinzipien von PRINCE 2 ein. Weiterhin werden die Vor- und Nachteile betrachtet.

# Positive Aspekte

Der Artikel geht gut auf die Grundprinzipien ein. 

# Negative Aspekte

* Ich finde du könntest unter "2. Die 7....." noch mehr Quellen per Verweis anführen. (falls es welche gibt). 
* Bau auch eventuell deine 2.te Grafik in Excel nach, dann hast du keinen weißen Rand drumherum. 
* Hau evtl auch das obere Bild raus, hat ja nicht viel mit dem Thema zu tun :). 

Füg dringend noch Verlinkungen auf die Beiträge deiner Kommilitonen ein, da geht bestimmt was, da ja noch 3 andere über PRINCE2 schreiben.

2021-11-30 12:39 UTC, za22regi commented
Am 2021-11-30 12:19, schrieb Larf4:
> @Larf4 requested changes on this pull request.
> 
> | Kriterium | Bewertung|
> |-----|---|
> | Front-Matter | ja |
> | Umfang | ja |
> | Belege | ja |
> | Links | ja |
> | Formatierung | ja |
> | Verlinkungen vorhanden | nein |
> | Abbildungen | ja |
> | Strukturierung des Beitrags | 10 |
> | Rechtschreibung | 10|
> | Sprache | 10 |
> | Inhalt | 10|
> | Einordnung in den Kontext | 6 |
> | Ansprechend für Zielgruppe | 10|
> 
> # Zusammenfassung
> 
> Der Beitrag geht intensiv auf die 7 Grundprinzipien von PRINCE 2 ein.
> Weiterhin werden die Vor- und Nachteile betrachtet.
> 
> # Positive Aspekte
> 
> Der Artikel geht gut auf die Grundprinzipien ein.
> 
> # Negative Aspekte
> 
> * Ich finde du könntest unter "2. Die 7....." noch mehr Quellen per
> Verweis anführen. (falls es welche gibt).
> * Bau auch eventuell deine 2.te Grafik in Excel nach, dann hast du
> keinen weißen Rand drumherum.
> * Hau evtl auch das obere Bild raus, hat ja nicht viel mit dem Thema zu 
> tun :).
> 
> Füg dringend noch Verlinkungen auf die Beiträge deiner Kommilitonen
> ein, da geht bestimmt was, da ja noch 3 andere über PRINCE2 schreiben.

Hey Hey danke dir für dein Feedback! Ich werde es so gut wie möglich 
umsetzen. Aber meine Frage ist, kannst du nicht auf die Verlinkungen 
zugreifen? Habe auf PRINCE2, PRINCE2 Prozesse und PRINCE2 
Projektumgebung verlinkt.

2021-12-03 16:18 UTC, Saskia1403 requested changes
# Für die Wissenslandkarte

| Kriterium | Bewertung|
|-----|---|
| Front-Matter | ja |
| Umfang | ja |
| Belege | ja |
| Links | ja |
| Formatierung | ja |
| Verlinkungen vorhanden | ja |
| Abbildungen | ja |
| Strukturierung des Beitrags | 10 |
| Rechtschreibung | 8 |
| Sprache | 10 |
| Inhalt | 10|
| Einordnung in den Kontext | 10|
| Ansprechend für Zielgruppe | 10|

# Zusammenfassung

Der Beitrag verschafft einem zunächst einen kleinen Überblick über Wissenslandkarten und wann bzw. wofür diese eingesetzt werden. So erfährt man, dass der Wissenspool in den Unternehmen zunehmend steigt und Wissenslandkarten eine gute Methode sind, um sich einen Überblick zu verschaffen und für mehr Transparenz zu sorgen. Anschließend wird kurz auf die verschiedenen Arten von Wissenslandkarten eingegangen, bevor eine Aufzählung der Vor-und Nachteile erfolgt.

# Positive Aspekte

Der Beitrag weist eine schöne Struktur auf und ist informativ und ansprechend geschrieben. Auch ist die zweite Graphik gut thematisch eingebunden und veranschaulicht die davor beschriebene Theorie. 

# Negative Aspekte

* die erste Graphik ist meiner Meinung nach für den Beitrag überflüssig oder sollte besser eingebunden werden
* zu den Vor-und Nachteilen fehlt die Quellenangabe
* der 2te Gliederungspunkt ist sowohl bei den Arten von Wissenslandkarten, als auch bei den Vor-und Nachteilen zu finden
* kleine Flüchtigkeitsfehler: im ersten Absatz sollte es glaub ich statt Arbeitsverläufe, Arbeitsabläufe und statt dazustellen, darzustellen heißen 


# Für Prince 2 - Die 7 Grundprinzipien

| Kriterium | Bewertung|
|-----|---|
| Front-Matter | ja |
| Umfang | ja |
| Belege | ja |
| Links | ja |
| Formatierung | ja |
| Verlinkungen vorhanden | nein |
| Abbildungen | ja |
| Strukturierung des Beitrags | 10 |
| Rechtschreibung | 8 |
| Sprache | 10 |
| Inhalt | 10 |
| Einordnung in den Kontext | 8 |
| Ansprechend für Zielgruppe | 10|

 # Zusammenfassung

Am Anfang gibt der Beitrag eine kleine Einführung in Prince 2 und was man darunter versteht. Anschließend werden alle 7 Grundprinzipien einzelnd näher erläutert und für den Leser verständlich gemacht. Abschließend erfolgt eine kleine Aufzählung der Vor- und Nachteile, die einen kleinen Einblick geben, in welchen Situationen Prince 2 geeignet ist und wann eher nicht. 

 # Positive Aspekte

* der Beitrag ist wie der Vorhergehende gut strukturiert
* der Beitrag liefert einen schönen und vor allem verständlichen Überblick über die 7 Grundprinzipien
* weiterführende Literatur ist angegeben 
* Verweise auf die angrenzenden Themen unter siehe auch

# Negative Aspekte

* keine Verlinkungen im Fließtext, obwohl dies hier leicht möglich wäre
* die Quellenangaben folgen keinem einheitlichen Schema
* bei der Tabelle und dem gesamten Kapitel 2 fehlt die Quellenangabe
* persönlich finde ich die erste Abbildung zu Prince Charming süß, ich weis jedoch nicht, ob es auch zu dem Wikipedia Stil passt
* außerdem sind mir auch hier kleine Fehler aufgefallen: 
 -bei 2.1 Sicherstellen, dass das Projekt geschäftliche Ziele ...
 -bei 2.5 Definition statt Definierung
 -bei 2.6 Erschließung statt Erschließsung

2021-12-06 20:46 UTC, Adaye1e requested changes
# Wissenslandkarte
| Kriterium | Bewertung|
|-----|---|
| Front-Matter | ja |
| Umfang | ja|
| Belege | ja |
| Links | ja|
| Formatierung | ja|
| Verlinkungen vorhanden | ja |
| Abbildungen | ja|
| Strukturierung des Beitrags | 10|
| Rechtschreibung | 9|
| Sprache | 10 |
| Inhalt | 10|
| Einordnung in den Kontext | 10|
| Ansprechend für Zielgruppe | 10|

# Zusammenfassung

Der Beitragt befasst sich mit dem Thema Wissenslandkarten. Diese verschaffen den nötigen Überblick über die Wissensgebiete, was zu effizienteren und effektiveren Arbeitsverläufen führt. Ferner wird der Begriff noch intensiver erläutert und zuletzt werden die Vor- und Nachteile erklärt.

# Positive Aspekte

- Es sind Verlinkungen und weiterführende Literaturen vorhanden, was die Einordnung in den Kontext ermöglicht
- Der Beitrag ist sehr gut strukturiert und vor allem das Inhaltsverzeichnis verschafft einen guten Überblick
- Die wichtigsten Aspekte werden ganz klar und sehr gut auf den Punkt gebracht
- Die Tabelle, die die verschiedenen Arten beschreibt, ist durch die Verwendung von Beispielen ganz gut gelungen

# Negative Aspekte

- Rechtschreibfehler: Statt "Überstreitung" heißt es Überschreitung

# PRINCE2
| Kriterium | Bewertung|
|-----|---|
| Front-Matter | ja |
| Umfang | ja|
| Belege | ja |
| Links | ja|
| Formatierung | ja|
| Verlinkungen vorhanden | ja |
| Abbildungen | ja|
| Strukturierung des Beitrags | 10 |
| Rechtschreibung | 6|
| Sprache | 8|
| Inhalt | 10|
| Einordnung in den Kontext | 10|
| Ansprechend für Zielgruppe | 10|

# Zusammenfassung

Der Beitrag beschreibt zu Beginn die Zusammensetzung des PRINCE2 und es wird darauffolgend erklärt, worum es sich dabei handelt. 
Des Weiteren werden die 7 Grundprinzipien detailliert dargestellt und es werden noch zuletzt die vor und Nachteile genannt



# Positive Aspekte

- Die 7 Grundprinzipien werden sehr gut und detailliert beschrieben
- Verlinkungen sind vorhanden

# Negative Aspekte

- Im Beitrag kommen einige Rechtschreibfehler vor. Ein Beispiel wäre im Unterpunkt: Produkt Orientierung "Defintion" statt Definition oder „Erschlisßung“ statt Erschließung
- Es wäre besser wenn mehr gute Abbildungen vorhanden wären

2021-12-09 19:37 UTC, merged