IT-Projekte_Adaye1e
ManagingProjectsSuccessfully/ManagingProjectsSuccessfully.github.io pull request #186
Opened 2021-11-23 15:40 UTC by Adaye1e

2021-11-29 10:59 UTC, Aseuc commented
| Kriterium | Bewertung|
|-----|---|
| Front-Matter | ja |
| Umfang | ja |
| Belege | ja |
| Links | ja |
| Formatierung | ja |
| Verlinkungen vorhanden | nein |
| Abbildungen | ja |
| Strukturierung des Beitrags | 10 |
| Rechtschreibung | 10|
| Sprache | 10|
| Inhalt | 10|
| Einordnung in den Kontext | 10|
| Ansprechend für Zielgruppe | 10|

# Zusammenfassung
Der Beitrag befasst sich mit den verschiedenen Methoden ein IT-Projekt durchzuführen als auch mit der Präsenz der verschiedenen Methoden in den verschiedensten Bereichen oder Teilen der Welt. Dabei werden auch die unterschiedlichen Methoden genau beschrieben und untereinander verglichen. Des Weiteren werden auch fehlgeschlagene IT-Projekte beleuchtet und zeigen somit auch die Herausforderungen bei IT-Projekten auf. 

# Positive Aspekte
- sehr gute Sprache
- anschaulicher und strukturierter Aufbau des Beitrags
- Bezugnahme auf die angewendeten Abbildungen

# Negative Aspekte
- leider fehlt die Verlinkung auf andere Beiträge wie beispielsweise:   "Wasserfallmodell" könnte man den Beitrag "Wasserfall_Modell.md" verlinken.
- Wenn du die Möglichkeit hast noch weiterführende Literatur zu finden wie Videos oder Bücher, würde ich diese auch noch hinzufügen.

2021-11-30 11:05 UTC, Larf4 requested changes
| Kriterium | Bewertung|
|-----|---|
| Front-Matter | ja |
| Umfang | ja |
| Belege | ja |
| Links |ja|
| Formatierung | ja |
| Verlinkungen vorhanden | nein |
| Abbildungen | ja |
| Strukturierung des Beitrags | 10 |
| Rechtschreibung |10|
| Sprache | 10 |
| Inhalt | 10|
| Einordnung in den Kontext | 7 |
| Ansprechend für Zielgruppe | 10|

# Zusammenfassung

Der Artikel beschreibt mehrere klassische Methoden für die Abwicklung von IT-Projekten. Er zeigt auch Anwendungsszenarien sowie Negativbeispiele.

# Positive Aspekte

Der Artikel ist ansprechend Gestaltet und das Layout ist gut geworden. Die tiefe ist in Bezug auf die Zielgruppe angemessen. Die Mehrheit der wichtigen Kriterien wurden erfüllt. Mir gefallen vor allem die Tollen Abbildungen, die helfen die Schemata zu visualisieren.

# Negative Aspekte
Wichtig wäre noch, dass Verlinkungen zu den Themen der Kommilitonen druchgeführt werden, da dieses Kriterium sehr wichtig ist. Ansonsten schönes Ding!

2021-12-02 16:57 UTC, Saskia1403 requested changes
| Kriterium | Bewertung|
|-----|---|
| Front-Matter | ja |
| Umfang | ja |
| Belege | ja |
| Links | ja|
| Formatierung | ja |
| Verlinkungen vorhanden | nein |
| Abbildungen | ja |
| Strukturierung des Beitrags | 10 |
| Rechtschreibung | 9 |
| Sprache | 8 |
| Inhalt | 9 |
| Einordnung in den Kontext | 6 |
| Ansprechend für Zielgruppe | 9 |

# Zusammenfassung

Nach einer kurzen Definition von IT-Projekten, geht der Beitrag vor allem auf 3 klassische Vorgehensmethoden (Hermes, V-Modell XT und Prince2) im Bereich der Softwareentwicklung ein. Anschließend werden Beispiele für gescheiterte IT-Projekte beschrieben. 

# Positive Aspekte

* Einbindung der Abbildungen in den Text
* klar strukturierter Beitrag
* leicht verständlich geschrieben

# Negative Aspekte

* Leider fehlen die Verlinkungen zu anderen Beiträgen im Text komplett. Diese wären jedoch leicht möglich z.B. in Bezug auf Prince 2 und dem V-Modell. Auch sind bei einem so breit gefächerten Thema die  Verlinkungen zu den angrenzenden Themen etwas wenig. 
* keine weiterführende Literatur
* mir ist aufgefallen, dass bei Prince2 von 7 Grundprinzipien gesprochen wird, in der Tabelle jedoch nur vier stehen. Meine Frage ist, ob es dafür einen spezifischen Grund gibt, denn ich nicht kenne?
* kleine Fehler: z.B. müsste glaube ich unter der Überschrift Barcode Scanner Lesefehler Südengland statt südenglang stehen

2021-12-08 22:21 UTC, Aseuc reviewed
| Kriterium | Bewertung|
|-----|---|
| Front-Matter | ja |
| Umfang | ja |
| Belege | ja |
| Links | ja |
| Formatierung | ja |
| Verlinkungen vorhanden | nein |
| Abbildungen | ja |
| Strukturierung des Beitrags | 10 |
| Rechtschreibung | 10|
| Sprache | 10|
| Inhalt | 10|
| Einordnung in den Kontext | 10|
| Ansprechend für Zielgruppe | 10|

# Zusammenfassung
Der Beitrag befasst sich mit den verschiedenen Methoden die im IT-Projekt durchzuführen sind als auch mit der Präsenz der verschiedenen Methoden in den verschiedensten Wirtschaftsbereichen oder Teilen der Welt. Dabei werden auch die unterschiedlichen Methoden genau beschrieben und untereinander verglichen. Des Weiteren werden auch fehlgeschlagene IT-Projekte beleuchtet und zeigen somit auch die Herausforderungen bei IT-Projekten auf. 

# Positive Aspekte
- sehr gute Sprache
- anschaulicher und strukturierter Aufbau des Beitrags
- Bezugnahme auf die angewendeten Abbildungen

# Negative Aspekte
- Zeile 13: leider fehlt die Verlinkung auf andere Beiträge wie beispielsweise:   "Wasserfallmodell" könnte man den Beitrag "Wasserfall_Modell.md" verlinken.
- Wenn du die Möglichkeit hast noch weiterführende Literatur zu finden wie Videos oder Bücher, würde ich diese auch noch hinzufügen.

2021-12-08 22:29 UTC, Aseuc reviewed
Zeile 13: Beispielsweise könnte man von anderen Kommilitonen das Wasserfallmodell verlinken.

2021-12-08 22:49 UTC, Aseuc requested changes

2021-12-08 22:49 UTC, Aseuc commented on kb/IT-Projekte.md
> +Bei Hermes wird nach den Prinzipien des Wasserfallmodells gearbeitet, siehe folgende Abbildung:![Beispielabbildung](IT-Projekte/Wasserfallmodell.png)[^3].
Wasserfallmodell von einem anderen Kommilitonen verlinken

2021-12-08 22:49 UTC, Aseuc commented on kb/IT-Projekte.md
> +Im Bereich der Softwareentwicklung sind die klassischen Vorgehensmethoden „Hermes“, „PRINCE2“ und „V-Model XT geeignet[^2].
hier könnte man Prince von einem anderen Kommilitonen verlinken

2021-12-08 22:50 UTC, Aseuc requested changes

2021-12-08 22:50 UTC, Aseuc commented on kb/IT-Projekte.md
> +
Wenn möglich noch weiterführende Literatur finden.

2021-12-09 19:37 UTC, merged