VMI_Matrix
ManagingProjectsSuccessfully/ManagingProjectsSuccessfully.github.io pull request #187
Opened 2021-11-23 15:44 UTC by Larf4

2021-11-27 12:11 UTC, up67enyq requested changes
| Kriterium | Bewertung|
|-----|---|
| Front-Matter | ja |
| Umfang | ja|
| Belege | ja|
| Links | ja|
| Formatierung | ja|
| Verlinkungen vorhanden | ja |
| Abbildungen | ja |
| Strukturierung des Beitrags | 10 |
| Rechtschreibung | 7|
| Sprache | 10 |
| Inhalt |10|
| Einordnung in den Kontext | 10|
| Ansprechend für Zielgruppe | 10|

# Zusammenfassung
Der Beitrag fasst die wichtigsten Informationen zu der VMI-Matrix zusammen. Es wird erklärt für was die Buchstaben V,M,I stehen und wie eine solche Matrix in der Regel erstellt wird. Weiter werden Vorteile wie Transparenz und Übersichtlichkeit Herausforderungen wie, zu viele Zuweisungen für einzelne Mitarbeiter gegenübergestellt.


# Positive Aspekte
Gute Abbildung um die VMI-Matrix zu erklären und im allgemeinen gut strukturiert. 
Schöne Einbeziehung und Verlinkung auf weitere Beiträge des Kompendiums.

# Negative Aspekte
Nach der ersten Erwähnung vom Projektstrukturplan gleich (PSP) dahinter schreiben.
Für die Konsistenz in Schritt 5 ein (I) hinter "[...] Informierenden Personen" - informierenden klein
Zeile 23: "Verantwortliche" klein 
Zeile 28 "Erstellt" und "Verwaltet" klein.
Zeile 30: Sicherstellung statt Sicherstellen

Vielleicht noch für die Einheitlichkeit entweder kein Leerzeichen vor Quellen oder ein Leerzeichen. Bei Wiki wird es meistens ohne Leerzeichen gemacht.

2021-11-29 10:30 UTC, Aseuc commented
| Kriterium | Bewertung|
|-----|---|
| Front-Matter | ja |
| Umfang | ja |
| Belege | ja |
| Links | ja|
| Formatierung | ja |
| Verlinkungen vorhanden | ja |
| Abbildungen | ja |
| Strukturierung des Beitrags | 10 |
| Rechtschreibung | 9 |
| Sprache | 10 |
| Inhalt | 10 |
| Einordnung in den Kontext | 10 |
| Ansprechend für Zielgruppe | 10 |

# Zusammenfassung
Der Beitrag ist umfasst alle wichtigen Aspekte zur VMI-Matrix, und gibt Aufschluss über die Verwendung, Anwendung, Einordnung und Vor- und Nachteile, welche die VMI-Matrix für das Projektmanagement bereitstellt. Unter anderem werden die Bedeutung der Buchstaben durch eigene Unterpunkte genauer beschrieben und helfen somit dem Leser noch besser die Matrix verstehen zu können. 

# Positive Aspekte
- passende Abbildung zur Veranschaulichung und Erklärung der VMI-Matrix
- strukturierter und übersichtlicher Aufbau
- Rechtschreibung perfekt bis auf kleine Groß- und Kleinschreibungsfehler
- Verwendung fachspezifischer Wörter

# Negative Aspekte
Groß- und Kleinschreibung:
- Zeile 23: "Verantwortliche" --> "verantwortliche"
- Zeile 28: "Erstellt und Verwaltet" --> "erstellt und verwaltet"

Format: 
- Bei den Vorteilen und Herausforderungen hätte ich die Fußzeile am Ende des letzten Punktes geschrieben

Weiterführende Literatur: 
- Wenn möglich könntest du noch weitere Literatur einfügen wie Videos oder Bücher

2021-11-30 11:13 UTC, Saskia1403 reviewed
| Kriterium | Bewertung|
|-----|---|
| Front-Matter | ja|
| Umfang | nein|
| Belege | ja |
| Links | ja|
| Formatierung | ja|
| Verlinkungen vorhanden | ja|
| Abbildungen | ja|
| Strukturierung des Beitrags |10 |
| Rechtschreibung | 8|
| Sprache | 9 |
| Inhalt | 9|
| Einordnung in den Kontext | 10|
| Ansprechend für Zielgruppe | 10|

# Zusammenfassung

Es wird gezeigt, dass die VMI-Matrix ein wichtiges Tool im klassischen Projektmanagement und vor allem in der Projektplanung ist. Dafür wird zum einen auf die Erstellung der VMI-Matrix und zum anderen auf deren Vor-und Nachteile eingegangen. 

# Positive Aspekte

* einfache und verständliche Erklärung des Aufbaus der VMI-Matrix
* gut strukturierter Beitrag
* passende Verlinkungen zu anderen Beiträgen
* gut ausgewähltes Bild, das den Sachverhalt schön veranschaulicht

# Negative Aspekte

* fast alle Verlinkungen funktioineren (positiv), jedoch öffnet sich der Link unter 
"siehe auch" -> Projektleitung bei mir nicht richtig bzw. es wird page not found angezeigt (negativ)
* die grobe Wörterzahl lag bei mir ohne Quellenverweise bei ca. 430
* ich würde die Abkürzung PSP direkt in Klammern hinter Projektstrukturplan setzen
* Weiterführende Literatur fehlt, vielleicht lässt sich da noch etwas finden
* kleine Fehler in der Rechtschreibung: erstellt, verwaltet und verantwortliche Person, statt Erstellt, Verwaltet und Verantwortliche Person
* das Bild könnte noch besser in den Text intergriert werden, z.B. um eine VMI-Matrix wie in Abbildung 1 zu erstellen, sind die folgenden 5 Schritte nötig: ...

2021-12-08 22:19 UTC, Aseuc reviewed
| Kriterium | Bewertung|
|-----|---|
| Front-Matter | ja |
| Umfang | ja |
| Belege | ja |
| Links | ja|
| Formatierung | ja |
| Verlinkungen vorhanden | ja |
| Abbildungen | ja |
| Strukturierung des Beitrags | 10 |
| Rechtschreibung | 9 |
| Sprache | 10 |
| Inhalt | 10 |
| Einordnung in den Kontext | 10 |
| Ansprechend für Zielgruppe | 10 |

# Zusammenfassung
Der Beitrag ist umfasst alle wichtigen Aspekte zur VMI-Matrix, und gibt Aufschluss über die Verwendung, Anwendung, Einordnung und Vor- und Nachteile, welche die VMI-Matrix für das Projektmanagement bereitstellt. Unter anderem werden die Bedeutung der Buchstaben durch eigene Unterpunkte genauer beschrieben und helfen somit dem Leser noch besser die Matrix verstehen zu können. 

# Positive Aspekte
- passende Abbildung zur Veranschaulichung und Erklärung der VMI-Matrix
- strukturierter und übersichtlicher Aufbau
- Rechtschreibung perfekt bis auf kleine Groß- und Kleinschreibungsfehler
- Verwendung fachspezifischer Wörter

# Negative Aspekte
Groß- und Kleinschreibung:
- Zeile 23: "Verantwortliche" --> "verantwortliche"
- Zeile 28: "Erstellt und Verwaltet" --> "erstellt und verwaltet"

Format: 
- Bei den Vorteilen und Herausforderungen hätte ich die Fußzeile am Ende des letzten Punktes geschrieben

Weiterführende Literatur: 
- Wenn möglich könntest du noch weitere Literatur einfügen wie Videos oder Bücher

2021-12-08 22:38 UTC, Aseuc requested changes
"Erstellt" und "Verwaltet" klein

2021-12-08 22:38 UTC, Aseuc commented on kb/VMI_Matrix.md
> +Die VMI-Matrix wird im Regelfall von der [Projektleitung](Projektleiter.md) Erstellt und Verwaltet. Weiterhin wird die Matrix laufend überprüft und bei Bedarf auch angepasst. 	[^5][^3]
```suggestion
Die VMI-Matrix wird im Regelfall von der [Projektleitung](Projektleiter.md) Erstellt und Verwaltet. Weiterhin wird die Matrix laufend überprüft und bei Bedarf auch angepasst. 	[^5][^3]
```
"Erstellt" und "Verwaltet" klein

2021-12-08 22:40 UTC, Aseuc requested changes

2021-12-08 22:40 UTC, Aseuc commented on kb/VMI_Matrix.md
> +* Schritt 3: Jedem Arbeitspaket wird genau eine Verantwortliche Person (V) zugewiesen. Diese Person erhält ein "V" in der zutreffenden Zelle.
"Verantwortlich"  klein

2021-12-08 22:40 UTC, Aseuc commented on kb/VMI_Matrix.md
> -# Weiterführende Literatur
evtl. findest du noch weiterführend Literatur

2021-12-08 22:40 UTC, Aseuc commented on kb/VMI_Matrix.md
> +Die Zuweisung der "V" Dimension gibt Aufschluss über den Verantwortlichen des Arbeitspakets. Hierbei sollte pro Arbeitspaket nur eine, bei hochkritischen Arbeitspaketen zwei Personen ausgewiesen werd
Sicherstellung statt Sicherstellen

2021-12-09 19:37 UTC, merged