Themen: Asana_PM_Tool und Projekthandbuch
ManagingProjectsSuccessfully/ManagingProjectsSuccessfully.github.io pull request #188
Opened 2021-11-23 15:45 UTC by Saskia1403

An alle Reviewer: vielen Dank schon einmal für euer Feedback.
 Meine Bitte an euch ist, dass ihr vor allem die Links checkt ;)

2021-11-27 12:56 UTC, up67enyq requested changes
| Kriterium | Bewertung|
|-----|---|
| Front-Matter | ja|
| Umfang | ja|
| Belege | ja |
| Links | ja|
| Formatierung | ja|
| Verlinkungen vorhanden | ja |
| Abbildungen | ja |
| Strukturierung des Beitrags | 10 |
| Rechtschreibung | 10|
| Sprache | 7 |
| Inhalt | 8|
| Einordnung in den Kontext | 10|
| Ansprechend für Zielgruppe |8|

# Zusammenfassung
- Asana_PM_Tool
Der Artikel gibt einen kurzen Einblick in die Entstehung, Bedeutung und Funktionen von Asana. Er gibt Informationen zur Anwendung, Preisen und den Nutzen welche durch Asana erhalten werden können. Abrundend gibt er eine kleine Preisübersicht der verschiedenen Optionen für Verwendung des Projektmanagement Tools.

- Projekthandbuch
Der Artikel erklärt zunächst das Ziel des Projekthandbuchs als ein Tool für Projektteammitglieder um einen Überblick über Vorgehen, Ziele und Inhalt zu haben. Er geht weiter darauf ein welche Komponenten im Projekthandbuch enthalten sein sollten und das dies sogar in einer DIN Norm festgehalten ist. Das Projekthandbuch wird vom Projektmanagementhandbuch abgegrenzt da sich das letztere auf allgemeine Regelungen bei Projekten eines Unternehmens beziehen, während das Projekthandbuch lediglich für ein spezielles Projekt gilt. Im weiteren Verlauf werden auf Verschiedene Varianten des Projekthandbuchs eingegangen. Darunter zählen das "V-Modell XT" ,die Projektleitdokumentation und der "Project Management Plan".


# Positive Aspekte
Asana_PM_Tool
- Schöne Abbildung um der schriftlichen Ausführung zu folgen
-  gute Verlinkungen zu angrenzenden Themen
- Gute und knappe Gliederung die die relevanten Teilbereiche gut abdeckt.

Projekthandbuch
- gute Gliederung
- schönen Überblick über andere Varianten
- Abgrenzung zu Projektmanagementhandbuch macht die Funktion noch deutlicher
- viele benutzte Quellen
- gibt einen sehr guten Überblick

# Negative Aspekte
Asana_PM_Tool
- Generell kommen die Quellenverweise meiner Meinung nach ohne Leerzeichen hinter das Satzende. 
- Worauf bezieht sich "auf den Markt gekommen ist" in der Einleitung der Teil davor bezieht sich ja auf das Unternehmen und dann scheinbar auf die Software
- Würde evtl. "bei ihrer Arbeit bei Facebook" stattdessen "für" schreiben
- Die Sprache ist teils etwas einfach gehalten und für den Enzyklopädiestil wird in der Regel weniger "man" oder "die einem zugeordnet wurden" verwendet
- Teilweise sehr lange verschachtelte Sätze
- Bei den Preiskategorien wäre für uns als Zielgruppe evtl. noch die verschiedenen Vorteile relevant, wenn diese offen auf der Seite kommuniziert werden sollten. Der Preis an sich ist als Anhaltspunkt wenig aussagekräftig ohne entsprechende Features stichpunktartig zu erwähnen

Projekthandbuch
- eher wenig aussagekräftige Abbildung (vlt. einen stilisierten Aufbau eines Projekthandbuchs abbilden?)
- "Gibt es eine Projektassistenz, so kann diese Abwandlungen versionieren und speichern" macht keinen Sinn
- "...übergeordnete Ziel des Projekthandbuchs ist, ein..." einen statt ein 
- "..ist es in seiner Ausführung relativ knapp" relativ zu was?
- "...Sammlung aller wichtigen Dokumente, die während dem Projektverlauf" zu während des Projektverlaufs ändern
- bei "V-Model XT" das XT mit verlinken wenn das Modell so heißt?
- im letzten Abschnitt "Project Management Plan" in Anführungszeichen

2021-11-29 11:43 UTC, Aseuc commented
| Kriterium | Bewertung|
|-----|---|
| Front-Matter | ja |
| Umfang | ja|
| Belege | ja |
| Links | ja|
| Formatierung | ja|
| Verlinkungen vorhanden | ja |
| Abbildungen | ja |
| Strukturierung des Beitrags | 10 |
| Rechtschreibung | 10|
| Sprache | 8 |
| Inhalt | 10|
| Einordnung in den Kontext | 10|
| Ansprechend für Zielgruppe | 10|

# Zusammenfassung
Der Beitrag "Projekthandbuch" umfasst die wichtigen Bestandteile, wie der Nutzen, die Verwendung als auch die verschiedenen Varianten des Projekthandbuchs.  Des Weiteren werden auch begriffliche Abgrenzungen vorgenommen, welche dem Leser helfen beispielsweise zwischen Projektmanagementhandbuch und Projekthandbuch zu unterscheiden. Unter anderem findet der Leser einen sehr strukturierten Aufbau der verschiedenen Bereiche vor, welche ihm die Möglichkeit bietet einzelne Teile die evtl. nicht verstanden wurden nachzulesen.  


# Positive Aspekte
- sehr strukturierter Aufbau 
- Abgrenzung von ähnlichen Begriffen
- Vorhandensein von weiterführender Literatur
- Verlinkungen zu angrenzenden Themen

# Negative Aspekte
- teilweise sehr lange und verschachtelte Sätze, welche den Leser beim lesen etwas durcheinander bringen
- kleine grammatikalische Fehler wie Zeile 12: Würde ich schreiben --> Das übergeordnete Ziel des Projekthandbuchs ist es einen Überblick über das Projekt zu verschaffen und die Ausführung relativ knapp zu halten, sodass es nur wichtige Informationen beinhaltet.  
- evtl. mehr auf die Abbildung eingehen

2021-11-29 12:27 UTC, Aseuc commented
| Kriterium | Bewertung|
|-----|---|
| Front-Matter | ja|
| Umfang | ja|
| Belege | ja|
| Links | ja|
| Formatierung | ja|
| Verlinkungen vorhanden | ja |
| Abbildungen | ja|
| Strukturierung des Beitrags | 10 |
| Rechtschreibung |10|
| Sprache | 9 |
| Inhalt | 10|
| Einordnung in den Kontext | 10|
| Ansprechend für Zielgruppe | 10|

# Zusammenfassung

Kurze Zusammenfassung des/der Artikel
Der Beitrag "Asana_PM_Tool" beinhaltet eine Einleitung, welche sich auf die Entstehungsgeschichte von Asana bezieht. Diese gibt auch Aufschluss über die DSGVO des Unternehmens. Des Weiteren werden auch die Funktionen und die verschiedenen Preiskategorien von Asana beleuchtet. Der Leser erhält Informationen über die Anwendung, Preise und den Nutzen welche er durch Asana erhalten kann. Obwohl teilweise lange und verschachtelte Sätze vorhanden sind, ist der Beitrag verständlich und einfach gehalten somit kann der Leser Schritt für Schritt die Geschichte, Funktionen und Preise von Asana kennenlernen. 

# Positive Aspekte
- Bezugnahme auf die Abbildung
- Vorhandensein von weiterführender Literatur
- Verlinkung von passenden angrenzenden Themen 
- sehr gute Rechtschreibung
- sehr guter strukturierter Aufbau
- übersichtliche Darstellung der Preiskategorien

# Negative Aspekte
- statt Zeile 8: "lernten sich bereits zuvor bei ihrer Arbeit für Facebook kennen" --> "lernten sich bereits auf der Arbeit bei Facebook kennen" 
- teilweise lange und verschachtelte Sätze
-  Fußzeilen sollten ohne Leerzeichen an das Satzende kommen

2021-12-03 17:04 UTC, Saskia1403 commented
Vielen Dank schon einmal für den ganzen Input! Ich werde versuchen einiges davon umzusetzen.

2021-12-04 18:01 UTC, urimi0 requested changes
| Kriterium | Bewertung|
|-----|---|
| Front-Matter | ja |
| Umfang | ja |
| Belege | ja |
| Links | ja |
| Formatierung | ja |
| Verlinkungen vorhanden | ja |
| Abbildungen | ja |
| Strukturierung des Beitrags | 8 |
| Rechtschreibung | 8 |
| Sprache | 7 |
| Inhalt | 9 |
| Einordnung in den Kontext | 8 |
| Ansprechend für Zielgruppe | 7 |

# Zusammenfassung

* Asana ist ein Projetkmanagementtool, welches mehrere Features bietet, um die Arbeit in Unternehmen zu vereinfachen. Dabei hat man die Möglichkeit auch Daten aus anderen Programmen wie Excel, etc. mit zu integrieren. 

# Positive Aspekte

* Gute Abbildung.
* Gut erklärt welche Funktionen Asana bietet.
* Links sind richtig.
* Viele Quellen -> Arbeit entstanden aus mehreren Perspektiven



# Negative Aspekte

* Einleitung: zu detailliert. Nicht alle Infos relevant wie die Erklärung des
Namens und Datenschutzrichtlinien.

* Hauptteil: 
Etwas untergliedern wenn möglich (mit Überschriften).
Sprache beachten Bsp.: „Nach der Anmeldung bei Asana, mit zum Beispiel seinem Google Konto…“. Besser -> Nach der Anmeldung mit beispielsweise einem Google Konto kann…
Danach sofort: „gelangt man zur Homepage, auf der man alle Projekte und Aufgaben sieht, die demnächst fällig sind„-> Konto wurde doch gerade erst eingerichtet. Sofort Projekte? Genauer erklären vielleicht.
Kommasetzung nochmal kontrollieren -> „...Integration anderer Tools, wie Teams…“ hier beginnt Aufzählung erst. Kein Komma.

* Tabelle: Ok aber mehr Inhalt was sind die Unterschiede, die dann den Preis ausmachen?

* Bei Weiterführender Literatur: „Features von Asana“ & „Projetktmanagement mit Asana“ führen zur gleichen Seite

2021-12-04 19:27 UTC, urimi0 requested changes
| Kriterium | Bewertung|
|-----|---|
| Front-Matter | ja |
| Umfang | ja |
| Belege | ja |
| Links | ja |
| Formatierung | ja |
| Verlinkungen vorhanden | ja |
| Abbildungen | ja |
| Strukturierung des Beitrags | 9 |
| Rechtschreibung | 8 |
| Sprache | 9 |
| Inhalt | 8 |
| Einordnung in den Kontext | 9 |
| Ansprechend für Zielgruppe | 8 |

# Zusammenfassung

* Ein Projekthandbuch dient als Leitfaden zur Bearbeitung eines Projektes.
Hierbei gibt es eine gewisse Hierarchie. Projektleiter sollen dieses Handbuch erstellen und aktualisieren. Mitarbeiter sollen ihren Fokus auf die Einhaltung dieses Projekthandbuchs dann legen.


# Positive Aspekte

* Gut zu lesen.
* Gut gegliedert.
* Viele Quellen und gute Verlinkungen.
* Gute Überleitung zu naheliegenden Themen.

# Negative Aspekte

* Quelle NR 2 zeigt NOT FOUND an (Hochschule Augsburg).
* Einleitung ist hier eher Hauptteil. Einleitung einfach kürzer halten.
* Ein Satz unter der Überschrift „Varianten des Projekthandbuchs“ nicht nötig, wenn dann zu den Unterpunkten hinzufügen.
* Sprache beachten Bsp.: „Er wird vom Projektmanager mit seinem Team…“ -> Er? Hier lieber „Der Plan“ oder „Dieser“.
* Kommasetzung: „…PID sind zum Beispiel, die Projektdefinition…“ hier kein Komma.
* Abbildung hat keinen wirklichen Inhalt.

2021-12-08 22:15 UTC, Aseuc reviewed
Zeile 8: "lernten sich bereits auf der Arbeit bei Facebook kennen"

2021-12-08 22:17 UTC, Aseuc requested changes
"lernten sich bereits auf der Arbeit bei Facebook kennen"

2021-12-08 22:23 UTC, Aseuc reviewed
| Kriterium | Bewertung|
|-----|---|
| Front-Matter | ja |
| Umfang | ja|
| Belege | ja |
| Links | ja|
| Formatierung | ja|
| Verlinkungen vorhanden | ja |
| Abbildungen | ja |
| Strukturierung des Beitrags | 10 |
| Rechtschreibung | 10|
| Sprache | 8 |
| Inhalt | 10|
| Einordnung in den Kontext | 10|
| Ansprechend für Zielgruppe | 10|

# Zusammenfassung
Der Beitrag "Projekthandbuch" umfasst die wichtigen Bestandteile, wie der Nutzen, die Verwendung als auch die verschiedenen Varianten des Projekthandbuchs.  Des Weiteren werden auch begriffliche Abgrenzungen vorgenommen, welche dem Leser helfen beispielsweise zwischen Projektmanagementhandbuch und Projekthandbuch zu unterscheiden. Unter anderem findet der Leser einen sehr strukturierten Aufbau der verschiedenen Bereiche vor, welche ihm die Möglichkeit bietet einzelne Teile die evtl. nicht verstanden wurden nachzulesen.  Des Weiteren stößt der Leser teilweise auf lange und verschachtelte Sätze, welche das Verstehen des Beitrages erschweren. Aber allgemein gesehen ist der Beitrag sehr gelungen. 


# Positive Aspekte
- sehr strukturierter Aufbau 
- Abgrenzung von ähnlichen Begriffen
- Vorhandensein von weiterführender Literatur
- Verlinkungen zu angrenzenden Themen

# Negative Aspekte
- teilweise sehr lange und verschachtelte Sätze, welche den Leser beim lesen etwas durcheinander bringen
- kleine grammatikalische Fehler wie Zeile 12: Würde ich schreiben --> Das übergeordnete Ziel des Projekthandbuchs ist es einen Überblick über das Projekt zu verschaffen und die Ausführung relativ knapp zu halten, sodass es nur wichtige Informationen beinhaltet.  
- evtl. mehr auf die Abbildung eingehen

2021-12-08 22:23 UTC, Aseuc reviewed
| Kriterium | Bewertung|
|-----|---|
| Front-Matter | ja|
| Umfang | ja|
| Belege | ja|
| Links | ja|
| Formatierung | ja|
| Verlinkungen vorhanden | ja |
| Abbildungen | ja|
| Strukturierung des Beitrags | 10 |
| Rechtschreibung |10|
| Sprache | 9 |
| Inhalt | 10|
| Einordnung in den Kontext | 10|
| Ansprechend für Zielgruppe | 10|

# Zusammenfassung

Kurze Zusammenfassung des/der Artikel
Der Beitrag "Asana_PM_Tool" beinhaltet eine Einleitung, welche sich auf die Entstehungsgeschichte von Asana bezieht. Diese gibt auch Aufschluss über die DSGVO des Unternehmens. Des Weiteren werden auch die Funktionen und die verschiedenen Preiskategorien von Asana beleuchtet. Der Leser erhält Informationen über die Anwendung, Preise und den Nutzen welche er durch Asana erhalten kann. Obwohl teilweise lange und verschachtelte Sätze vorhanden sind, ist der Beitrag verständlich und einfach gehalten somit kann der Leser Schritt für Schritt die Geschichte, Funktionen und Preise von Asana kennenlernen. 

# Positive Aspekte
- Bezugnahme auf die Abbildung
- Vorhandensein von weiterführender Literatur
- Verlinkung von passenden angrenzenden Themen 
- sehr gute Rechtschreibung
- sehr guter strukturierter Aufbau
- übersichtliche Darstellung der Preiskategorien

# Negative Aspekte
- statt Zeile 8: "lernten sich bereits zuvor bei ihrer Arbeit für Facebook kennen" --> "lernten sich bereits auf der Arbeit bei Facebook kennen" 
- teilweise lange und verschachtelte Sätze
-  Fußzeilen sollten ohne Leerzeichen an das Satzende kommen

2021-12-08 22:44 UTC, Aseuc requested changes

2021-12-08 22:44 UTC, Aseuc commented on kb/Projekthandbuch.md
>  Da das übergeordnete Ziel des Projekthandbuchs ist, ein Überblick über das Projekt zu verschaffen, ist es in seiner Ausführung relativ knapp zu halten, sodass es nur alle wichtigen Informationen bein
Zeile 12: Würde ich schreiben --> Das übergeordnete Ziel des Projekthandbuchs ist es einen Überblick über das Projekt zu verschaffen und die Ausführung relativ knapp zu halten, sodass es nur wichtige Informationen beinhaltet.

2021-12-08 22:44 UTC, Aseuc commented on kb/Projekthandbuch.md
>  Da das übergeordnete Ziel des Projekthandbuchs ist, ein Überblick über das Projekt zu verschaffen, ist es in seiner Ausführung relativ knapp zu halten, sodass es nur alle wichtigen Informationen bein
hier evtl. sich mehr auf die Abbildung beziehen was man jetzt da sieht etc.

2021-12-09 19:37 UTC, merged