Risikomatrix und KI_Software_fuer_Projektmanagement
ManagingProjectsSuccessfully/ManagingProjectsSuccessfully.github.io pull request #190
Opened 2021-11-23 15:52 UTC by Aseuc

2021-11-27 14:26 UTC, up67enyq requested changes
| Kriterium | Bewertung|
|-----|---|
| Front-Matter | ja|
| Umfang | ja|
| Belege | ja|
| Links | ja|
| Formatierung | ja|
| Verlinkungen vorhanden | ja|
| Abbildungen | ja|
| Strukturierung des Beitrags | 10 |
| Rechtschreibung | 9|
| Sprache | 9 |
| Inhalt | 10|
| Einordnung in den Kontext | 10|
| Ansprechend für Zielgruppe | 10|

# Zusammenfassung

Der Artikel beschreibt die Relevanz und möglichen Einsatzgebiete von KI im Bezug auf Projektmanagement. KI ist ein Gebiet der Informatik welches mit Automatisierung und maschinellen Lernen dem Menschen beim Projektmanagement beispielsweise durch die Übernahme repetitiver Aufgabe unterstützt.
Es wird weiter eine Abgrenzung zwischen schwacher und starker KI und der verschiedenen Arten des Lernens einer KI gezogen.
Die Bedenken bezüglich KI werden zum Ende relativiert und gut belegt.

# Positive Aspekte
- Ein schönes Schaubild um die Arten des KI-Lernens zu veranschaulichen
- Sehr guter gesamtüberblick über KI
- guter Bezug zum Projektmanagement
- Schöne Gliederung
- Interessante ZDF am Anfang
- Gute Sprache


# Negative Aspekte
- Meiner Meinung nach sollten Quellen zumindest wenn sie am Ende des Satzes stehen direkt hinter den Punkt gesetzt werden (orientiert an Wiki)
- Die Übersicht des Aufbaus hat zumindest bei mir nicht funktioniert und hat mich zum bearbeiten des Beitrags weitergeleitet... Ist die Frage ob sich das für einen eher kurzen Beitrag überhaupt lohnt
- Im Anschnitt zu Bedenken "sogenannter" statt "sogennanter" (ein n zu viel)
- Im Abschnitt "Arten von KI-Software" "das ausführen" -> Ausführen groß, ebenso bei "das beantworten" B groß
- Direkt vor der Abbildung "Beschrieben" klein schreiben
- Nach der Abbildung direkt die Quelle verlinken und Namen der Abbildung einfügen bspw.: "Bild 1: Arten des Maschinellen Lernens[^(Quelle)]"?
- Im Abschnitt unter dem Bild nach "Weitere Aspekte" ein Komma
- Im letzten Abschnitt entscheiden für Gendern oder nicht aber keine Mischung machen sonst sieht es komisch aus, (evtl. dazu dann auch die Artikel Gendern bspw. bei "ein Projektmanager:innen" weiß nicht ob man das macht). Alternativ: "Die Mitarbeitenden"
- "Des Weiteren sind die Bedenken, dass der Mitarbeiter durch eine KI ersetz wird eher unwahrscheinlich" Bedenken können nicht unwahrscheinlich sein hier passt eher unbegründet
- Den letzten Satz würde ich umstellen da sich die 50% sonst eher in der Luft hängen besser evtl: "Ein weiterer Aspekt der die Bedenken schmälern könnte ist, dass die Wahrscheinlichkeit bis 2033 eine "starke KI", die ein eigenes Bewusstsein besitzt, zu entwickeln bei 50% liegt."

2021-12-01 12:21 UTC, TobiasZuerrlein requested changes
# **1. KI Software für Projektmanagement**

| Kriterium | Bewertung|
|-----|---|
| Front-Matter | ja |
| Umfang | ja|
| Belege | ja |
| Links | ja|
| Formatierung | ja|
| Verlinkungen vorhanden | ja|
| Abbildungen | ja |
| Strukturierung des Beitrags | 9 |
| Rechtschreibung | 6|
| Sprache | 7|
| Inhalt | 9|
| Einordnung in den Kontext | 10|
| Ansprechend für Zielgruppe | 10|

# Zusammenfassung

Eine KI kann menschliche Verhaltensmuster imitieren und bestimmte Entscheidungen fällen. Es wird dabei zwischen "starker" und "schwacher" KI unterscheiden. Bei der Verwendung von KI im Projektmanagement ist vor allem das maschinelle Lernen (Unterkategorie von KI) bedeutsam, wodurch beispielsweise frühzeitig Ressourcenengpässe erkannt werden können.
Obwohl sehr viele Experten vom Nutzen von KI im Projektmanagement überzeugt sind, kommt KI hier noch kaum zum Einsatz. KI bringt neben den vielen Vorteilen auch eine Reihe an Bedenken mit sich, die aber relativiert werden müssen.

# Positive Aspekte

- inhaltlich sehr ansprechend
- interessante Erklärungen
- gut ausgewählte und umfangreiche Literatur
- aussagekräftige Abbildung

# Negative Aspekte

- **Front** **Matter**: relevante Tags nicht eingetragen
- **Belege**: Fußnoten fehlen an manchen Absätzen und Sätzen. Fußnoten sind teilweise falsch gesetzt: Soll auf den ganzen Absatz verwiesen werden: Fußnote hinter den letzten Punkt des Absatzes. Soll lediglich auf einen Satz verwiesen werden: Fußnote vor den Punkt des Satzes.
- **Formatierung**: Kommas bei "Buch: Crashkurs KI im Unternehmen," und "Video: KI im Projektmanagement – was kann's? (Teil 1)," am Ende weglassen.  Bei weiterführender Literatur würde ich mich Zitierstilen orientieren.
- **Verlinkungen** **vorhanden**: Etwas wenig Verlinkungen. Beispielsweise kann "Projekt" oder "Mitarbeiter" auch verlinkt werden.
- **Abbildung**: Die Abbildung hat keine Bezeichnung, lediglich "Bild 1".
- **Strukturierung** **des** **Beitrags**: Ich würde das Inhaltsverzeichnis bei so einem kurzen Beitrag weglassen. Den Unterpunkt "Arten von KI-Software" würde ich eine Ebene anheben, da der Oberpunkt "Was ist KI-Software?" sonst nur einen einzigen Unterpunkt hat.
- **Rechtschreibung**: Einige Fehler besonders bei der Groß- und Kleinschreibung. Beispielsweise wird "das ausführen" oder "das beantworten" groß geschrieben. Kommasetzung teilweise falsch oder unvollständig. Beispielsweise bei "fortlaufend trainiert, und optimieren" vor "und" kein Komma. Zusätzlich einige Rechtschreibfehler wie beispielsweise bei "sogennanter" oder "Effizienzssteigerung".
- **Sprache**: Teilweise umgangssprachlich. Beispielsweise besser "Arbeitsgeschwindigkeit anstatt "Arbeitstempo" oder "Projektmanagement-Experten" anstatt "Projektmanagement-Fachleute". Sätze teilweise sehr verschaltet und unverständlich, beispielsweise "Die Künstliche Intelligenz bietet ab einer gewissen Komplexität von Projekten, welche viel Pflege benötigen oder wenn die Aufwandsabschätzung sehr viel Zeit beansprucht, weshalb andere Tätigkeiten vernachlässigt werden, eine Effizienzssteigerung". Der Satz "Ein weiterer Aspekt der die Bedenken schmälern könnte ist, dass die Entwicklung sogennanter "starker KI", welche ein eigenes Bewusstsein besitzen, bis 2033 eine Wahrscheinlichkeit von 50% hat." ist sehr schwer zu lesen und grammatikalisch nicht ganz korrekt. Besser vielleicht: "Ein weiterer Aspekt **,** der die Bedenken schmälern könnte ist, dass die Entwicklung sogenannter "starker KI" bis 2033 lediglich mit einer Wahrscheinlichkeit von 50% erfolgreich abgeschlossen sein wird." Wörter wie "neu" vermeiden.
- **Inhalt**: Die Abkürzung "KI" erklären und einführen.
 "Die KI-Software für das Projektmanagement ist ein sehr neues Thema, denn nur 23% der Befragten gaben an im Projektmanagement mit künstlicher Intelligenz gearbeitet zu haben." --> wo gaben 23% der Befragten das an? --> Die Umfrage sollte meiner Meinung nach genannt werden --> beispielsweise "..nur 23% der Befragten gaben laut einer Umfrage an.."

# **2. Risikomatrix**

| Kriterium | Bewertung|
|-----|---|
| Front-Matter | ja |
| Umfang | ja|
| Belege | ja |
| Links | ja|
| Formatierung | ja|
| Verlinkungen vorhanden | ja|
| Abbildungen | ja |
| Strukturierung des Beitrags | 9 |
| Rechtschreibung | 7|
| Sprache | 7|
| Inhalt | 9|
| Einordnung in den Kontext | 9|
| Ansprechend für Zielgruppe | 9|

# Zusammenfassung

Die Risikomatrix setzt die Eintrittswahrscheinlichkeit und das Schadensausmaß negativer Ereignisse ins Verhältnis und stellt die Ergebnisse tabellarisch dar. Durch Multiplikation beider Faktoren kann der Schadenserwartungswert des jeweiligen Risikos berechnet werden. Die Risikomatrix spielt eine wichtige Rolle im Risiko- und Projektmanagement. Im Rahmen des Risikomanagements werden Risiken mit einer Eintrittswahrscheinlichkeit von über 25% und einer durchschnittlichen Schadenshöhe aktiv geleitet. Im Projektmanagement wird die Matrix hauptsächlich zur Veranschaulichung von Risiken ganzer Projekte oder Projektgruppen angewendet. Allerdings kann man die Risikomatrix aufgrund ihrer begrenzten Aussagefähigkeit kritisieren, da die Variablen stark zeitabhängig sind.

# Positive Aspekte

- inhaltlich sehr ansprechend
- gut ausgewählte und umfangreiche Literatur
- schöne beispielhafte Risikomatrix als Abbildung

# Negative Aspekte

- **Front** **Matter**: relevante Tags nicht eingetragen
- **Belege**: Fußnoten sind teilweise falsch gesetzt: Soll auf den ganzen Absatz verwiesen werden: Fußnote hinter den letzten Punkt des Absatzes. Soll lediglich auf einen Satz verwiesen werden: Fußnote vor den Punkt des Satzes.
- **Formatierung**: Bei weiterführender Literatur würde ich mich an Zitierstilen orientieren.
- **Verlinkungen** **vorhanden**: Etwas wenig Verlinkungen. Beispielsweise kann "Projekt" auch verlinkt werden.
- **Abbildung**: Die Abbildung hat keine Bezeichnung, lediglich "Bild 1".
- **Strukturierung** **des** **Beitrags**: Ich würde das Inhaltsverzeichnis bei so einem kurzen Beitrag weglassen. Außerdem würde ich jeweils einen eigenen Oberpunkt für "Nutzen" und "Kritik" machen. 
- **Rechtschreibung**: Groß- und Kleinschreibung: Beispielsweise wird das Wort "Anhand" kleingeschrieben oder das Wort "entgegenwirken" großgeschrieben. Kommasetzung teilweise falsch oder unvollständig, beispielsweise fehlt bei folgenden Sätzen nach "gibt" und "Darstellung" jeweils ein Komma: "...Darstellungsform gibt kann die Matrix auch eine umgekehrte Beschriftung der Achsen haben", "Die Risikomatrix ist eine zweidimensionale Darstellung welche der systematischen Evaluierung und Bewertung von Risiken dienen soll". 
- **Sprache**: Satzbau teilweise etwas schlecht. Beispielsweise bei "... Ergebnis der Risikoanalyse und Risikobewertung ist, ist es ein wichtiges Instrument ..." am Besten "...ist, ist..." vermeiden. Weiteres Bespiel: "Bei der tabellarischen Darstellung der Risikomatrix wird an der y-Achse die Eintrittswahrscheinlichkeit und an der x-Achse die Schadenshöhe angegeben, da es aber keine einheitliche Darstellungsform gibt kann die Matrix auch eine umgekehrte Beschriftung der Achsen haben" --> vielleicht besser 2 Sätze: "Bei der tabellarischen Darstellung der Risikomatrix wird an der y-Achse die Eintrittswahrscheinlichkeit und an der x-Achse die Schadenshöhe angegeben. Da es aber keine einheitliche Darstellungsform gibt, kann die Matrix auch eine umgekehrte Beschriftung der Achsen haben."
- **Inhalt**: "Durch Multiplikation der Eintrittswahrscheinlichkeit und der Schadenshöhe des Risikos kann der Schadenserwartungswert berechnet werden.": Müsste dieser Satz nicht eigentlich in den Abschnitt "Aufbau und Berechnung"? 
- **Einordnung** **in** **den** **Kontext**: Wenig Bezug zu Projektmanagement.
- **Ansprechend** **für** **Zielgruppe**: Wenig Bezug zu Projektmanagement.

2021-12-06 17:53 UTC, urimi0 requested changes
KI SOFTWARE FUER PROJEKTMANAGEMENT


| Kriterium | Bewertung|
|-----|---|
| Front-Matter | ja |
| Umfang | ja |
| Belege | ja |
| Links | ja |
| Formatierung | ja |
| Verlinkungen vorhanden | ja |
| Abbildungen | ja |
| Strukturierung des Beitrags | 8 |
| Rechtschreibung | 8 |
| Sprache | 7 |
| Inhalt | 9 |
| Einordnung in den Kontext | 7 |
| Ansprechend für Zielgruppe | 8 |

# Zusammenfassung

* Künstliche Intelligenz hilft Menschen Daten zu erhalten bzw. zu schätzen, die hilfreich sind in verschiedenen Gebieten. Hierbei gibt es verschiedene Lernarten von diesen Systemen. Allgemein betrachtet versucht KI, Muster in Daten zu erkennen und diese Weiterzuführen oder an Menschen zu übergeben.

# Positive Aspekte

* Gliederung gut, aber nicht wirklich nötig, da kurzer Beitrag.
* Gute Abbildung.
* Viele Quellen.
* Gute weiterführende Literatur.
* Allgemein gut gegliedert.

# Negative Aspekte

* Verlinkungen zu angrenzenden Themen mehr vielleicht. Nur eine am Anfang recht wenig. 
* Sprache: Manchmal sehr verschachtelte Sätze -> dadurch schwieriger zu lesen
* Kommasetzung manchmal nicht richtig.
* Überschriften „Was ist KI?“ und „Arten von KI“ zu einem Punkt vereinen.
* Quellenangaben wichtig, aber es verschlechtert die Optik des Textes, da sie so häufig auftreten.
* Abbildung Gut, aber für die Größe wenig Inhalt.

2021-12-06 18:41 UTC, urimi0 requested changes
Risikomatrix

| Kriterium | Bewertung|
|-----|---|
| Front-Matter | ja |
| Umfang | ja |
| Belege | ja |
| Links | ja |
| Formatierung | ja |
| Verlinkungen vorhanden | ja |
| Abbildungen | ja |
| Strukturierung des Beitrags | 10 |
| Rechtschreibung | 7 |
| Sprache | 7 |
| Inhalt | 9 |
| Einordnung in den Kontext | 9 |
| Ansprechend für Zielgruppe | 9 |

# Zusammenfassung

* Die Risikomatrix ist eine zweidimensionale Darstellung, die Risiken anhand von Bewertung in Verhältnis stellen soll. Sie ist das Produkt der Risikoanalyse und Risikobewertung, somit ist sie von großer Bedeutung für das Projektmanagement.

# Positive Aspekte

* Sehr gut strukturiert.
* Gute Abbildung.
* Gliederung gut.
* Ich finde den Unterpunkt Kritik sehr gut, quasi als Evaluierung nochmal.

# Negative Aspekte

* Einleitung: Erster und zweiter Satz inhaltlich nicht wirklich verschieden, würde aber die beiden Sätze tauschen da es ein besserer Einstieg wäre.
* Gliederung gut, aber Links funktionieren bei mir nicht.
* Aufbau und Berechnung: „Im Bild 1 wird nochmals anschaulich eine Risikomatrix dargestellt wie vorher schon beschrieben“ -> Satz weglassen, es reicht vorher zu schreiben „(siehe Abbildung)“.
* Kommasetzung manchmal beachten Bsp: „Bei Milderung oder Verlagerung werden Maßnahmen ergriffen die das Risiko eliminieren… “ -> hier vor „,die“ ein Komma setzen.
* Weiterführende Literatur: „Buch zu Risikoanalyse: Risikoanalyse von…“ -> Einfach „Buch:“ hinschreiben da Thema bereits im Titel.
* Quelle: „Schadungserwartungswertes“ führt aber zu „Risikomanagementsystem“? Gewollt oder vielleicht habe ich es nicht ganz verstanden?

2021-12-10 14:35 UTC, merged