New_Work combined changes
ManagingProjectsSuccessfully/ManagingProjectsSuccessfully.github.io pull request #191
Opened 2021-11-23 16:00 UTC by up67enyq

Erste Version für New Work (Klassisches PM, Allgemein)

2021-12-01 10:35 UTC, TobiasZuerrlein requested changes
| Kriterium | Bewertung|
|-----|---|
| Front-Matter | ja |
| Umfang | ja|
| Belege | ja |
| Links | ja|
| Formatierung | ja|
| Verlinkungen vorhanden | ja|
| Abbildungen | ja |
| Strukturierung des Beitrags | 8 |
| Rechtschreibung | 8|
| Sprache | 9|
| Inhalt | 10|
| Einordnung in den Kontext | 10|
| Ansprechend für Zielgruppe | 10|

# Zusammenfassung

New Work ist ein zukunftsorientierter Denkansatz, der sich im Rahmen der professionalisierten Berufungsfindung mit der Sinnhaftigkeit der Arbeit und dem "wirklich, wirklich wollen" des Individuums befasst. New Work gewinnt heutzutage in Unternehmen zunehmend an Bedeutung und spielt auch im Projektmanagement eine wichtige Rolle.

# Positive Aspekte

- Sehr schön zu lesen. Der Beitrag ist sehr flüssig geschrieben
- Inhaltlich sehr ansprechend
- interessante Erklärungen
- Sehr gelungene Formulierungen
- gut ausgewählte und umfangreiche Literatur
- aussagekräftige Abbildung
- humanfy GmbH als schönes Beispiel

# Negative Aspekte

- **Front** **Matter**: relevante Tags nicht eingetragen
- **Belege**: Fußnoten fehlen an manchen Absätzen und Sätzen. Fußnoten sind teilweise falsch gesetzt: Soll auf den ganzen Absatz verwiesen werden: Fußnote hinter den letzten Punkt des Absatzes. Soll lediglich auf einen Satz verwiesen werden: Fußnote vor den Punkt des Satzes.
- **Verlinkungen** **vorhanden**: etwas wenig Verlinkungen. Beispielsweise kann "Projekt" auch verlinkt werden.
- **Strukturierung** **des** **Beitrags**: Im ersten Absatz auch kurz darauf eingehen, dass New Work im Projektmanagement eine wichtige Bedeutung hat. Den Unterpunkt "Grundannahmen" weglassen, da der Oberpunkt "Philosophie" sonst nur einen einzigen Unterpunkt hat.
- **Rechtschreibung**: Im Absatz "Die von Humanfy definierte ... zeigt wie aus der ursprünglichen recht ... ist. Die Methodik beinhaltet die wichtigsten Punkte um die ursprünglichen Anforderungen ... versöhnen." muss beispielsweise glaub ich nach "zeigt" und vor "um" jeweils ein Komma. Das Wort "wollen" wird bei "wirklich, wirklich wollen" einmal groß und einmal klein geschrieben..was ist richtig? Wird bei "wirklich, wirklich Können" das Wort "Können" wirklich groß geschrieben? "Humanfy" muss meiner Meinung nach klein geschrieben werden.
- **Sprache**: Bei "Es geht beim New Work darum diesen Mangel abzubauen..." müsste es "bei New Work" anstatt "beim New Work" heißen, glaube ich. "Eine Auswahl der Konzepte SIND" anstatt "Eine Auswahl der Konzepte ist" würde ich sagen.

2021-12-05 20:08 UTC, GiuliaAng commented
| Kriterium | Bewertung|
|-----|---|
| Front-Matter | ja |
| Umfang | ja|
| Belege | ja |
| Links | ja|
| Formatierung | ja|
| Verlinkungen vorhanden | ja |
| Abbildungen | ja |
| Strukturierung des Beitrags | 8 |
| Rechtschreibung | 9|
| Sprache | 9 |
| Inhalt | 9|
| Einordnung in den Kontext | 9|
| Ansprechend für Zielgruppe | 10|

# Zusammenfassung

New Work ist ein in den 1980er entwickelter innovativer Ansatz, wie sich  das klassische Bild der Arbeit weiterentwickeln kann. Von dem Prinzip des "wirklich, wirklich wollens" bis zur heutigen Interpretation der attraktiv gestalteten Arbeit ist hierbei alles vertreten.

# Positive Aspekte

* Sehr gute sprachliche Ausarbeitung
* Flüssig lesbar
* Sehr interessant mit dem geschichtlichen Hintergrund
* Sehr gute Literaturverweise 
* passende Verweise auf andere Artikel 

# Negative Aspekte

*Einordnung in den Kontext/Inhalt: Der letzte Punkt mit New Work im Projektmanagement würde ich noch mehr einbinden in die vorangegangenen Artikel, da hier noch ein wenig die Überleitung und Verbindung fehlt
* Inhalt: Die Oberbegriffe aus der Abbildung würde ich im Text noch nennen, damit ein Bezug hergestellt wird
* Rechtschreibung: Im ersten Satz fehlt ein Komma "...Anfang, der..."
* Strukturierung des Beitrags: Philosophie ist eine große Überschrift, hat aber nur einen Unterpunkt Grundannahmen. Evtl eine große Überschrift überlegen, wenn es keinen zweiten Unterpunkt gibt
* Strukturierung des Beitrags: Pro Absatz müssen mindestens zwei Sätze vorhanden sein
* Sprache: Solang du die Quelle des Bildes richtig angibst, brauchst du glaube ich kein "ausgearbeitet von", außer du hast etwas verändert, dann würde ich schreiben in Anlehnung an

2021-12-05 21:06 UTC, GiuliaAng requested changes
| Kriterium | Bewertung|
|-----|---|
| Front-Matter | ja |
| Umfang | ja|
| Belege | ja |
| Links | ja|
| Formatierung | ja|
| Verlinkungen vorhanden | ja |
| Abbildungen | ja |
| Strukturierung des Beitrags | 8 |
| Rechtschreibung | 9|
| Sprache | 9 |
| Inhalt | 9|
| Einordnung in den Kontext | 9|
| Ansprechend für Zielgruppe | 10|

# Zusammenfassung

New Work ist ein in den 1980er entwickelter innovativer Ansatz, wie sich  das klassische Bild der Arbeit weiterentwickeln kann. Von dem Prinzip des "wirklich, wirklich wollens" bis zur heutigen Interpretation der attraktiv gestalteten Arbeit ist hierbei alles vertreten.

# Positive Aspekte

* Sehr gute sprachliche Ausarbeitung
* Flüssig lesbar
* Sehr interessant mit dem geschichtlichen Hintergrund
* Sehr gute Literaturverweise 
* passende Verweise auf andere Artikel 

# Negative Aspekte

* Einordnung in den Kontext/Inhalt: Der letzte Punkt mit New Work im Projektmanagement würde ich noch mehr einbinden in die vorangegangenen Artikel, da hier noch ein wenig die Überleitung und Verbindung fehlt
* Inhalt: Die Oberbegriffe aus der Abbildung würde ich im Text noch nennen, damit ein Bezug hergestellt wird
* Rechtschreibung: Im ersten Satz fehlt ein Komma "...Anfang, der..."
* Strukturierung des Beitrags: Philosophie ist eine große Überschrift, hat aber nur einen Unterpunkt Grundannahmen. Evtl eine große Überschrift überlegen, wenn es keinen zweiten Unterpunkt gibt
* Strukturierung des Beitrags: Pro Absatz müssen mindestens zwei Sätze vorhanden sein
* Sprache: Solang du die Quelle des Bildes richtig angibst, brauchst du glaube ich kein "ausgearbeitet von", außer du hast etwas verändert, dann würde ich schreiben in Anlehnung an

2021-12-06 19:32 UTC, urimi0 requested changes
New Work
 
| Kriterium | Bewertung|
|-----|---|
| Front-Matter | ja |
| Umfang | nein |
| Belege | ja |
| Links | ja |
| Formatierung | ja |
| Verlinkungen vorhanden | ja |
| Abbildungen | ja |
| Strukturierung des Beitrags | 9 |
| Rechtschreibung | 8 |
| Sprache | 9 |
| Inhalt | 9 |
| Einordnung in den Kontext | 9 |
| Ansprechend für Zielgruppe | 10 |

# Zusammenfassung

* New Work ist ein Denkansatz, der in den 1980er Jahren begründet wurde. Hierbei soll die Berufung von Menschen, durch Leidenschaft und Wille gewählt und ausgeübt werden. Der Begriff des New Work entwickelt sich stetig weiter und wird immer relevanter für Unternehmen.

# Positive Aspekte

* Sehr gut lesbar.
* Gutes Beispiel mit humanfy GmbH.
* Abbildung informativ. 
* Gute weiterführende Literatur.

# Negative Aspekte

* Den Punkt „Grundannahmen“ würde ich weglassen.
* Umfang: Kontrolle bei Word zeigt ca. 640 Wörter. Ein wenig kürzen. 
* Einleitung: Die Zusammenfassung ausbauen. Kurz beschreiben was als alt angesehen wird und was neu ist.
* Kommasetzung: „Im Gegensatz dazu gibt es Unternehmen die versuchen New Work“ hier nach „Unternehmen“ Komma setzen.
* humanfy: Groß- oder Kleinschreibung? Etwas verwirrend.
* Mehr Verlinkungen möglich.

2021-12-08 14:22 UTC, up67enyq commented
Hey erstmal danke für die Reviews,

ich werde die Anmerkungen so gut wie es geht versuchen umzusetzen, jedoch habe ich bei ein paar Anmerkungen Fragen bzw. Unsicherheiten was nun besser wäre. Ich fange einfach mal von oben an :)

- "beim New Work" werde ich vermutlich zu beim Konzept New Work ändern damit keine Unklarheiten entstehen
- "Eine Auswahl der Konzepte ist..." bleibt meiner Meinung nach Singular da sich das ist auf die Auswahl bezieht: Eine Auswahl ist


- Hier bin ich mit der Kritik ausnahmslos einverstanden wobei ich mir bei dem Komma noch immer nicht sicher bin 🤣 

- Ich dachte in Teams wurde geschrieben zu viel ist in Ordnung solange es kein Roman wird? Stärker kürzen halte ich für schwierig
- ich habe humanfy GmbH klein geschrieben da sich die Firma so selbst im Impressum bezeichnet und habe Humanfy dann als Nomen jedoch groß geschrieben. Was hier richtig ist weiß ich nicht ganz vielleicht beides mal klein und dafür in Anführungszeichen?


Beim Rest bin ich vollkommen bei euch :) Danke, dass ihr drüber geschaut habt und in die Welt des New Works eingetaucht seid 😄

2021-12-09 08:24 UTC, TobiasZuerrlein commented
Hey, danke für die Rückfragen :)

zu 1.: 

- ich würde "Bei dem New Work-Konzept geht es darum, diesen Mangel ..." schreiben. 
- "Eine Auswahl der Konzepte ist" hört sich meiner Meinung nach komisch an. Du hast schon recht, "sind" ist auch nicht viel besser. Vielleicht gefällt dir ja folgender Satz: "Im Folgenden werden einige (dieser) Konzepte kurz vorgestellt:".

Viele Grüße :)

2021-12-09 19:37 UTC, merged