Innovationsprojekte
ManagingProjectsSuccessfully/ManagingProjectsSuccessfully.github.io pull request #200
Opened 2021-11-23 17:01 UTC by pamerkl

2021-12-03 08:04 UTC, Laura1mueller requested changes
Kriterium | Bewertung|
|-----|---|
| Front-Matter | ja |
| Umfang | ja|
| Belege | ja|
| Links | ja|
| Formatierung | ja|
| Verlinkungen vorhanden | ja |
| Abbildungen | ja |
| Strukturierung des Beitrags | 10 |
| Rechtschreibung | 10|
| Sprache | 9 |
| Inhalt | 10|
| Einordnung in den Kontext | 10|
| Ansprechend für Zielgruppe | 10|

# Zusammenfassung

In dem Artikel geht es um die Merkmale von Innovationsprojekten, was diese ausmacht und wie sie aufgebaut sind. Bei der Entwicklung von Innovationsprojekten muss der Zielkonflikt zwischen Zeit, Kosten und Leistung stets betrachtet werden. Innovationsprojekte sind neu und oft sehr Komplex, weshalb sie auch Unsicherheiten und Konfliktpotential mit sich bringen. Die innovativen Projekte lassen sich in verschiedenen Arten gliedern. Zudem ist es wichtig die Projektträger und Projektphasen
zu betrachten.  Auch eine Meilensteinanalyse kann beim Aufbau des Projektes helfen. Um schlussendlich den tatsächlichen Erfolg messen zu können, kann eine Soll-Ist Analyse des Projektes und verschiedenen Kennzahlen aufgestellt werden. 

# Positive Aspekte
- Gute Grafik 
- Tabelle zu den verschiedenen Arten sehr übersichtlich
- Gute Gliederung
- Klar strukturiert 
- Länge passt sehr gut 

# Negative Aspekte

- Der erste Einleitungssatz ist eher ein bisschen verwirrend
- Verlinkungen bei Wörter im Text teilweise falsch
- Im text heißt es Zeit, Qualität und Kosten, bei der Darstellung allerdings „Leistung“
- Die Eigenschaften nochmal deutlich (vielleicht „fett“) hervorheben

2021-12-05 16:31 UTC, ga88maby requested changes
| Kriterium | Bewertung|
|-----|---|
| Front-Matter | ja |
| Umfang | ja|
| Belege | ja |
| Links | ja|
| Formatierung | ja|
| Verlinkungen vorhanden | ja |
| Abbildungen | ja |
| Strukturierung des Beitrags | 10 |
| Rechtschreibung | 10|
| Sprache | 10 |
| Inhalt | 9|
| Einordnung in den Kontext | 10|
| Ansprechend für Zielgruppe | 9|

# Zusammenfassung

In diesem Artikel geht es um die Beziehung zwischen Innovationen und Projekten, wie sie funktioniert und wie Innovation-Projekte aufgestellt sind. Die Umsetzung einer Innovation erfolgt durch ein neues Projekt mit einem klaren Ziel und mit Rücksicht auf Zeit, Leistung und Kosten. Ohne klares Ziel entsteht der Gefahr von Zielkonflikt. Anschließend werden die vier grundlegenden Eigenschaften genannt, die lassen sich auch in mehrere Gruppen aufteilen. Außerdem werden die Projektträger, Projektphasen und Projektmanagement genau beschrieben und vorgestellt. Am Ende wird erklärt, wie Erfolg durch die drei Faktoren Zeit, Leistung, Kosten bemessen wird, dabei werden die Soll-Werte mit Ist-Werte verglichen.

# Positive Aspekte

*  Sehr gute Gliederung
*  Klare Struktur
*  Passendes Schaubild  

# Negative Aspekte

*  Es fehlt eine passende Einleitung

2021-12-06 20:38 UTC, michaelstnt requested changes
| Kriterium | Bewertung|
|-----|---|
| Front-Matter | ja |
| Umfang | ja |
| Belege | ja |
| Links | ja |
| Formatierung | ja |
| Verlinkungen vorhanden | ja |
| Abbildungen | ja |
| Strukturierung des Beitrags | 9 |
| Rechtschreibung | 9 |
| Sprache | 8 |
| Inhalt | 9 |
| Einordnung in den Kontext | 10 |
| Ansprechend für Zielgruppe | 9 |

# Zusammenfassung

Im Artikel Innovationsprojekte werden die wichtigsten Merkmale beleuchtet. So wird am Anfang deutlich, dass der Begriff oftmals falsch verstanden wird und bei der Entwicklung Zeit, Kosten und Leistung in Konflikt zueinander stehen. Grundlegende Eigenschaften wie bspw. Neuheitsgrad und Unsicherheiten sind Hauptbestandteile eines Innovationsprojektes. Eine Unterteilung der Arten wird hinsichtlich Technologie und Markt unterschieden. Projektträger, -phasen und -management sind für den Prozess des Projektes von entscheidender Bedeutung. Die Erfolgsmessung des Innovationsprojektes erfolgt nach einer Soll-Ist-Analyse. Hierbei gilt es zu beachten, dass auch positive Abweichungen zu Misserfolg führen können, sofern Planwerte nicht eingehalten werden. 


# Positive Aspekte

- Im Einleitungssatz werden Unterpunkte aufgriffen, somit eine gute Vorausschau
- Tabelle bzgl. Arten sehr übersichtlich
- Unterpunkte sinnvoll benannt

# Negative Aspekte

- Einleitungssatz nicht klar verständlich
- Text und Bild nicht übereinstimmend (Leistung <-> Qualität); Kundenzufriedenheit nicht im Text erwähnt
- Verlinkungen fehlerhaft
- Kurzer einleitender Satz bei „2.“ wäre schön, um zu wissen worum es geht

2021-12-09 19:37 UTC, merged

2021-12-18 12:13 UTC, pamerkl commented
@michaelstnt @Laura1mueller 

Bei mir funktionieren die Links komischerweise alle...
Könnt ihr mir bitte mal ein Beispiel nennen, wo der Link fehlerhaft war?
Dann kann ich mir das mal nochmal anschauen.

2021-12-18 14:02 UTC, Laura1mueller commented
Ich habe nochmal geschaut, komischerweise gehen die Links jetzt.

2021-12-19 09:36 UTC, pamerkl commented
@Laura1mueller 
ok super, dankeschön :)