Customer_Experience, Wasserfall_Modell
ManagingProjectsSuccessfully/ManagingProjectsSuccessfully.github.io pull request #203
Opened 2021-11-23 17:23 UTC by ga88maby

2021-12-02 22:50 UTC, Laura1mueller requested changes
| Kriterium | Bewertung|
|-----|---|
| Front-Matter | ja|
| Umfang | ja|
| Belege | ja|
| Links | ja|
| Formatierung | ja|
| Verlinkungen vorhanden | teilweise |
| Abbildungen | ja |
| Strukturierung des Beitrags | 8 |
| Rechtschreibung | 4 |
| Sprache | 3 |
| Inhalt | 7 |
| Einordnung in den Kontext | 5 |
| Ansprechend für Zielgruppe | 4 |

# Zusammenfassung

Der Artikel befasst sich mit der Customer Experience (CX). Dabei wird darauf eingegangen, dass CX eine immer wichtigere Rolle im Unternehmen spielt, auch gegenüber Konkurrenten. Die Komponennten Einfachheit, Effektivität und Emotionen haben dabei einen großen Einfluss auf die CX. Das Problem bei der CX liegt darin, dass sie oft zeitverzögert erst umgesetzt werden kann. Langfristig sollen so allerdings Markentreue und Kundenloyalität erreicht werden.  

# Positive Aspekte

- Sehr ausführlich, die wichtigsten Punkte zu CX werden genannt
- Gute Überschriften

# Negative Aspekte

- Teils Rechtschreibfehler, besonders im ersten Absatz
- Öfters stimmt der Satzbau und die Verben Form nicht, am besten nochmal Wort für Wort lesen 
- Schaubild zu groß 
- Direktes Zitat vielleicht eher umschreiben
- Quellen Link direkt auf der Schrift verlinken, sodass man den eigentlichen Link nicht direkt sieht ( Funktioniert, indem man  das Wort in eckige Klammern und den Link in Runde Klammern setzt)
- Überschrift „Ziele Langfristig?“-> Langfristige Ziele  oder vielleicht in Kurz und Langfristig Gliedern
- Geschichte als ersten Gliederungspunkte und nicht nur mit Stichwörtern formulieren
- Mehr als eine weiterführende Literatur
- Vielleicht eine Grafik mehr mehr Bedeutung
- Nicht alles ist Zitiert (?), nach jedem Absatz Quelle zitieren vor allem wenn Block übergreifend
- Das Wasserfallmodell wird nicht erklärt

2021-12-06 16:29 UTC, Laura1mueller requested changes
| Kriterium | Bewertung|
|-----|---|
| Front-Matter | ja|
| Umfang | ja|
| Belege | ja|
| Links | ja|
| Formatierung | ja|
| Verlinkungen vorhanden | ja |
| Abbildungen |ja |
| Strukturierung des Beitrags | 8|
| Rechtschreibung | 6|
| Sprache | 5|
| Inhalt | 9|
| Einordnung in den Kontext | 9|
| Ansprechend für Zielgruppe | 7|

# Zusammenfassung

Das Konzept des Wasserfall-Modells besteht darin, dass ein Projekt in verschiedene Phasen eingeteilt wird.  Die Phasen heißen Anforderung, Entwurf, Implementation, Überprüfung und Wartung.  Eine Phase fängt erst an, wenn die Phase davor abgeschlossen ist. Dies macht die Umsetzung einfacher. Vorteile dieses Modell sind beispielsweise die gute Dokumentation des Entwicklungsprozesses sowie die Bestimmung verschiedener Ziele für einzelne Phasen. Nachteile dagegen sind, dass kaum Spielraum vorhanden ist und man eher unflexibel ist.

# Positive Aspekte
- gute Länge
- Auflistung Vor/Nachteile ist gut
- Schaubild passend


# Negative Aspekte
- Einleitung etwas verwirrend, man weiß nicht wirklich um was es dann geht
- Satzzeichen fehlen
- Satzbau des Öfteren fehlerhaft
- Links so verlinken, dass man nur auf das Wort klicken muss und nicht den ganzen Link sieht ( mit [] und (), habe ich auch in dem anderen Beitrag erklärt)
- Teilweise etwas umgangssprachlich geschrieben

2021-12-07 19:41 UTC, Burcu12 requested changes
| Kriterium | Bewertung|
|-----|---|
| Front-Matter | ja |
| Umfang | ja |
| Belege | ja |
| Links | ja |
| Formatierung | ja |
| Verlinkungen vorhanden | ja |
| Abbildungen | ja |
| Strukturierung des Beitrags | 10 |
| Rechtschreibung | 9 |
| Sprache | 8 |
| Inhalt | 10|
| Einordnung in den Kontext | 10 |
| Ansprechend für Zielgruppe | 10 |

# Zusammenfassung
In dem Artikel Customer Experience wird am Anfang die Unverzichtbarkeit erklärt und wie wichtig es im Unternehmen ist. Die Umsetzung spielt eine wichtige Rolle im Unternehmen. Des Weiteren werden drei verschiedene Internationale Standards ausgeführt. Auf Dauer ist es jedoch notwendig Marken- und Kundenbindung zu erreichen

# Positive Aspekte
Erfolgreiche Struktur. Die Bildauswahl ist gut. Sehr detailliert, die wichtigsten Punkte zu CX werden behandelt.

# Negative Aspekte
Zur Begriffserklärung würde ich eine Überschrift empfehlen.
Die Abbildung ist viel zu groß und es fehlt eine Bildunterschrift.

2021-12-07 19:55 UTC, Burcu12 requested changes
| Kriterium | Bewertung|
|-----|---|
| Front-Matter | ja |
| Umfang | ja |
| Belege | ja |
| Links | ja |
| Formatierung | ja |
| Verlinkungen vorhanden | ja |
| Abbildungen | ja |
| Strukturierung des Beitrags | 10 |
| Rechtschreibung | 8 |
| Sprache | 7 |
| Inhalt | 10|
| Einordnung in den Kontext | 10 |
| Ansprechend für Zielgruppe | 10 |

# Zusammenfassung
Der Artikel Wasserfall-Modell befasst sich mit den verschiedenen Phasen eines unterteilten Projektes. Der Vorteil dieses Modells besteht darin, dass es den Entwicklungsprozess gut dokumentiert und unterschiedliche Ziele für verschiedene Phasen definiert. Auf der anderen Seite hat es den Nachteil, dass man fast keinen Spielraum hat. 

# Positive Aspekte
Erfolgreiche Struktur. Die Bildauswahl ist gut. Sehr detailliert, die wichtigsten Punkte werden behandelt.

# Negative Aspekte
Zur Begriffserklärung würde ich eine Überschrift empfehlen.
Teilweise etwas umgangssprachlich geschrieben.

2021-12-07 20:18 UTC, MariaKaisa requested changes
| Kriterium | Bewertung| 

|-----|---| 

| Front-Matter | ja| 

| Umfang | ja| 

| Belege | ja|  

| Links | ja| 

| Formatierung | ja|  

| Verlinkungen vorhanden | ja| 

| Abbildungen | ja | 
| Strukturierung des Beitrags | 10 | 

| Rechtschreibung | 8| 

| Sprache | 7 | 

| Inhalt | 10|  

| Einordnung in den Kontext | 10| 

| Ansprechend für Zielgruppe | 10| 

 

# Zusammenfassung Kurze Zusammenfassung des Artikels 

Der Artikel behandelt das Thema Customer Experience. Hierbei wird insbesondere auf das Wasserfall Modell Fokus gesetzt. Daraufhin wird eingegangen wie die Methoden um eine positive Customer Experience zu erreichen lauten und dass das Problem darin liegt, dass diese oft zeitverzögernd umgesetzt werden kann, jedoch im langfristigen so Markentreue und Kundenloyalität angestrebt werden. 

# Positive Aspekte Was ist gut 

Man erkennt ohne Probleme, worum es sich im Artikel handelt. Dieser ist leicht zu lesen und verstehen. Dabei ist die Strukturierung der Überschriften sehr gut gelungen und übersichtlich. Der Umfang ist optimal und die Sprache gut verständlich.  

# Negative Aspekte Was geht besser 

Abbildung sehr groß und es fehlt eine Bildunterschrift 

2. Teilweise Umgangssprachlich geschrieben

2021-12-09 19:37 UTC, merged