Ziel Planung
ManagingProjectsSuccessfully/ManagingProjectsSuccessfully.github.io pull request #216
Opened 2021-11-23 20:11 UTC by Emre12345678

2021-12-01 20:37 UTC, CatPec commented on kb/Ziel_Planung.md
> + Grundlage für die Planung ist die Vorgabe der Projektleitung und die Bildung eines Teams, damit die Personen, die später am Projekt arbeiten, bereits in die Planung einbezogen werden. Ausgehend von
Du musst meines Wissens die Überschriften nicht nummerieren.

2021-12-01 20:38 UTC, CatPec commented on kb/Ziel_Planung.md
> +# 1.	Allgemeines zur Projektplanung im klassischen Projektmanagement:
Du musst meines Wissens nach die Überschriften nicht nummerieren.

2021-12-01 20:39 UTC, CatPec commented on kb/Ziel_Planung.md
> + Grundlage für die Planung ist die Vorgabe der Projektleitung und die Bildung eines Teams, damit die Personen, die später am Projekt arbeiten, bereits in die Planung einbezogen werden. Ausgehend von
Da hast du aus Versehen den Text von obendrüber kopiert

2021-12-01 20:42 UTC, CatPec commented on kb/Ziel_Planung.md
> + Grundlage für die Planung ist die Vorgabe der Projektleitung und die Bildung eines Teams, damit die Personen, die später am Projekt arbeiten, bereits in die Planung einbezogen werden. Ausgehend von
Dieser Teil ist leider nicht sehr aussagekräftig. Es wird nicht wirklich klar, was du dem Leser hier mitteilen willst. Vielleicht fällt dir ja hier noch ein schönerer Einleitungssatz/Definition von Ziel Planung ein. Man fühlt sich hier etwas "hineingeworfen" in den Text

2021-12-01 20:45 UTC, CatPec commented on kb/Ziel_Planung.md
> + Es wird außerdem ein Projektmanagementplan erstellt, um die Übersichtlichkeit zu bewahren. Der Projektmanagementplan legt zusätzlich genau fest, welche Verantwortungsbereiche von welchen Mitarbeiter
Der Punkt muss immer nach das [^x]. Dann verlinkt sich das auch direkt mit der Website, von der du zitierst.

2021-12-01 20:46 UTC, CatPec commented on kb/Ziel_Planung.md
> +Oftmals stellt sich die Frage „Kann man mit seinem Team nicht einfach rauslaufen und schauen wie es läuft? “. Dies kann funktionieren ist jedoch sehr unwahrscheinlich, da man mit hoher Wahrscheinlich
Ist das ein direktes Zitat oder kannst du das vielleicht etwas sachlicher ausdrücken?

2021-12-01 20:47 UTC, CatPec commented on kb/Ziel_Planung.md
> +In der Praxis kann aber eine Anfrage zur „Entwicklung eines Projektplans ganz andere Erwartungen haben, da der Begriff „Projektplanung“ als Sammelbegriff interpretiert werden kann. Deshalb stellen di
Was sind die 7W- Fragen? Die hast du davor nicht einmal erwähnt.

2021-12-01 20:50 UTC, CatPec commented on kb/Ziel_Planung.md
> + Grundlage für die Planung ist die Vorgabe der Projektleitung und die Bildung eines Teams, damit die Personen, die später am Projekt arbeiten, bereits in die Planung einbezogen werden. Ausgehend von
Rechtschreibfehler: welcheR in Teilprojekte...
außerdem benutzt du sehr oft das Wort "dann"

2021-12-01 20:51 UTC, CatPec commented on kb/Ziel_Planung.md
> +**4.	Ablauf- und Terminplanung:** Erstellung einer chronologischen Rheinfolge der Arbeitspakete
Reihenfolge nicht Rheinfolge :D

2021-12-01 20:52 UTC, CatPec commented on kb/Ziel_Planung.md
> +Im klassischen Projektmanagement geht es darum, möglichst klare Ziele zu haben, die in der gewünschten Zeit und zu den gewünschten Kosten erreicht werden können. Deshalb spricht man oftmals in diesem
Der Teil gefällt mir sehr gut. Klar ausgedrückt und guter Lesefluss.

2021-12-01 20:54 UTC, CatPec commented on kb/Ziel_Planung.md
> +Ziele sind stets ein Motivationsfaktor. Deshalb kann es durchaus kontraproduktiv sein, sich unangemessene Ziele zu setzen, bei denen vom vornhinein klar ist, dass das Erreichen dieser Ziele sehr schw
Deshalb kann es durchaus kontraproduktiv sein, sich unangemessene Ziele zu setzen,.... -----> Kann  es kontraproduktiv sein oder IST es das ? (Vielleicht schreibst du den Satz nochmal um, damit die Aussage dahinter deutlicher wird.

2021-12-01 20:56 UTC, CatPec commented on kb/Ziel_Planung.md
> +Dies bedeutet, dass das Ziel so deutlich wie möglich gesetzt werden sollen, um später nicht darüber diskutieren zu müssen, ob das Ziel erreicht wurde oder nicht. [^1]
Da würde ich noch etwas ausführlicher drauf eingehen. Die Begriffe der Smart-Regel werden mir so leider nicht ganz klar bzw. die Bedeutung dahinter.

2021-12-01 21:43 UTC, CatPec requested changes
| Kriterium | Bewertung|
|-----|---|
| Front-Matter |ja|
| Umfang |ja|
| Belege |ja|
| Links |nein|
| Formatierung |nein|
| Verlinkungen vorhanden |nein|
| Abbildungen |ja|
| Strukturierung des Beitrags |8|
| Rechtschreibung |7|
| Sprache |5|
| Inhalt |6|
| Einordnung in den Kontext |5|
| Ansprechend für Zielgruppe |4|

# Zusammenfassung

In diesem Artikel geht es insgesamt darum, die grundsätzlichen Aspekte der Zielplanung zu erläutern. Dabei wird sowohl auf die Planung, als auch auf die Durchsetzung eingegangen. Es wird hier sowohl der personelle Aspekt, als auch der finanzielle Aspekt beleuchtet.

Es werden im nächsten Abschnitt die Schritte der Projektplanung aufgezählt und erläutert. Zudem wird auf die Umsetzung in der Praxis eingegangen und die Probleme dabei aufgezählt.

Abschließend werden die Ziele hinter der Zielplanung beleuchtet und auf das magische Dreieck eingegangen. Anhand daran wird erklärt, welche Aspekte in der Zielplanung (Kosten/Leistung/Zeit) nie außer Acht gelassen werden dürfen , um die Hauptziele zu erreichen.

Anhand der SMART-Regel will der Verfasser dem Leser ein Werkzeug an die Hand geben, das Ziele im Vornherein klar definiert, um bei Abschluss eines Projektes dessen Erfolg ohne Schwierigkeiten bewerten zu können.

# Positive Aspekte

Was ist gut 
Der Beitrag an sich ist gut strukturiert. Du hast einen klaren Aufbau, indem du zunächst generell den Begriff Zielplanung erläuterst und dann genauer auf den Sinn dahinter eingehst und auch Probleme und neutrale Handlungsempfehlungen (z.B SMART-Regel) erklärst.

Umfang ist auch passend. Es wird das wichtigste erklärt ohne, dass es den Rahmen sprengt.

# Negative Aspekte:
Negativ ist leider, dass man sich bereits nach dem ersten Satz schwer tut, dem Inhalt deines Textes zu folgen. Der erste Abschnitt ist sehr verwirrend. Es wird nicht klar, was du hier genau sagen möchtest. Das liegt zum Teil auch am sprachlichen Ausdruck. 

Bei der Formatierung ist einiges nicht ganz richtig. Du musst keine Nummerierung benutzen. Auch hast du im ersten Abschnitt des Textes den einen Teil einfach doppelt. Das MUSS auf jeden Fall rausgenommen werden. 

Die Verlinkungen innerhalb des Textes funktionieren leider kein einziges Mal. Das liegt daran, dass die Klammer vor den Punkt muss (Also [^x].) Dann funktioniert der Link, wenn du innerhalb darauf gehst. Außerdem werden die Zahlen dann als blaue Hochzahl erscheinen.

Leider hast du auch innerhalb des Textes kein einziges mal auf einen anderen Kompediumsartikel verlinkt, obwohl das mehrfach möglich gewesen wäre (z.B SMART-Regel oder magisches Dreieck). Dadurch wird der Artikel nicht sehr ansprechend für die Zielgruppe, da sie sich jedes Mal den passenden Artikel dazu heraussuchen müssen. Auch wird nicht ganz klar, wie dein Thema generell in den Kontext des Projektmanagements passt, weil du nicht wirklich erläuterst, in welchen Situationen man denn nun das alles anwendet.

# Was geht besser:

Ich würde innerhalb des Beitrags deutlich häufiger zitieren. Du machst das immer nur am Ende eines langen Absatzes. Sprachlich würde ich den Text auf jeden Fall nochmal überarbeiten. Du doppelst dich leider sehr oft in deinen Formulierungen oder benutzt Füllwörter wie "dann" mehrfach hintereinander, was den Text unsachlich erscheinen lässt. Ein paar Rechtschreibfehler/Zeichensetzungsfehler sind auch drin, diese lassen sich aber schnell ausbessern ;)
Was ich an deiner Stelle auch noch auf jeden Fall machen würde, ist weiterführende Literatur und Siehe auch zu benutzen. Das zeigt, dass du dich mit dem Thema auseinander gesetzt hast und dem Leser die weiterer Recherche erleichterst, indem du im passende Literatur vorschlägst.

Das Inhaltsverzeichnis würde ich weglassen, wenn dann müsste es an den Anfang deines Artikels und nicht an das Ende.  

Wenn du dich da nochmal  bezüglich des Inhalts und des Ausdrucks in den Leser hereinversetzt und bedenkst, dass er sich sehr wahrscheinlich nicht mit dem Thema auskennt und das in deinem "roten Faden" berücksichtigst, wird das bestimmt ein lesenswerter Artikel, Voraussetzung ist auf jeden Fall da :)

2021-12-02 13:09 UTC, MillaLena requested changes
| Kriterium | Bewertung|
|-----|---|
| Front-Matter | ja |
| Umfang | ja |
| Belege | ja |
| Links | ja |
| Formatierung | ja |
| Verlinkungen vorhanden | nein |
| Abbildungen | ja |
| Strukturierung des Beitrags | 6 |
| Rechtschreibung | 6|
| Sprache | 5 |
| Inhalt | 6|
| Einordnung in den Kontext | 7|
| Ansprechend für Zielgruppe | 6|

# Zusammenfassung

Der Artikel zeigt auf, wie Ziele definiert sind und befasst sich mit der Thematik des Ablaufs von der Zielsetzung zur Planung im klassischen Projektmanagement. 

# Positive Aspekte

Die Auswahl der inhaltlichen Punkte des Artikels ist sehr gelungen und das Thema wird in den Kontext des klassischen Projektmanagements eingeordnet.  

# Negative Aspekte

Der Artikel weist noch einige Lücken bzgl. Satzbau und Zeichensetzung auf. Dadurch fällt es noch etwas schwierig, sich ausschließlich auf den Inhalt zu konzentrieren. Das Inhaltsverzeichnis gibt eine gute Übersicht, ist aber evtl. in Anbetracht der Länge des Artikels eher irrelevant und sollte wenn dann am Anfang des Artikels stehen. Die Einleitung ist bereits sehr detailliert - vielleicht könnte man hier eher noch in 2-3 Sätzen allgemein beschreiben womit sich der Artikel beschäftigt. Die Nummerierung bzw. insbesondere die Doppelpunkte in den Überschriften könnte man evtl. weglassen für eine bessere visuelle Darstellung.  Die Abbildung ist etwas umaussagekräftig -vielleicht findet man hierzu noch etwas anschaulicheres. Außerdem liegt keine weiterführende Literatur bzw. Verlinkung zu angrenzenden Themen vor -das wäre durchaus interessant, um Ansatzpunkte für weitere, detaillierte Informationen zum Thema zu haben.  Bei der Erläuterung der Projektplanung in der Praxis ist die Rede von den 7W-Fragen, auf die dann anschließend aber nicht eingegangen wird -hier könnte man auch noch kurz drauf eingehen bzw. zu Erklärungen verlinken. Die Verlinkung der Fußnoten zu den Quellen hat leider nicht funktioniert und auch die Verlinkung im Inhaltsverzeichnis ist fehlerhaft.

2021-12-04 21:12 UTC, FerYilm requested changes
| Kriterium | Bewertung|
|-----|---|
| Front-Matter | ja |
| Umfang | ja |
| Belege | ja |
| Links | nein|
| Formatierung | nein|
| Verlinkungen vorhanden |nein |
| Abbildungen | ja |
| Strukturierung des Beitrags | 7 |
| Rechtschreibung | 7|
| Sprache | 5 |
| Inhalt | 8|
| Einordnung in den Kontext | 6|
| Ansprechend für Zielgruppe | 6|

# Zusammenfassung
Der Artikel gibt zunächst einen Überblick über die einzelnen Planungsphasen im Projektmanagement. Anschließend werden Herausforderungen und Fehler in der Praxis angesprochen und die 7-W-Fragen als eine Hilfestellung während der Projektplanung genannt. Der folgende Abschnitt befasst sich mit der Bedeutung der Ziele und erklärt die notwendige Kompromissbereitschaft mit dem magischen Dreieck. Als Hauptziele des Projektmanagements werden Organisation, Planung, Steuerung und Leitung aufgeführt. Abschließend werden die SMART-Regel und damit zusammenhängend die Bedeutung von realistischen Zielen genannt.

# Positive Aspekte
Der Fließtest umfasst knapp 600 Wörter und enthält Quellen. Die Abbildung vom magischen Dreieck ist passend und veranschaulicht die genannten Zielkonflikte im Projektmanagement. Durch die inhaltliche Aufteilung hat man insgesamt einen guten Überblick über das Thema. 

# Negative Aspekte
Im ersten Abschnitt wiederholt sich ein Absatz, diesen auf jeden Fall noch löschen.
Ich glaube, dass du teilweise vergessen hast, direkte Zitate als solche anzugeben? :'D  (z.B. „Je kürzer die Zeit, desto höher die Kosten. Je umfangreicher die Dienste, desto länger die Zeit")
Die Internetseiten, die in den Quellen als Hyperlinks hinterlegt wurden, funktionieren zwar, aber nicht die internen Links im Inhaltsverzeichnis („404“). (Ich bin mir außerdem nicht sicher, ob ein Inhaltsverzeichnis unbedingt notwendig ist)
Die Codes für die Quellen müssten nochmal überprüft werden, da sie nicht zu den Nachweisen führen (Sie sollten blau sein). 
Im Fließtext sind keine Verlinkungen auf andere Kompendiums- oder externe Beiträge vorhanden. Du könntest z.B die Beiträge für die Themen Projektmanagement und Projektmitarbeiter verlinken.
Damit die Überschriften einheitlich sind, könnte die 2. Themenüberschrift auch im Nominalstil formuliert werden. Die Nummerierungen und die Doppelpunkte könnte man auch weglassen.
Die in der Beispieldatei enthaltenen Überschriften „Siehe auch“ und „Weiterführende Literatur“ fehlen und könnten / sollten noch ergänzt werden.
Einige Formulierungen sind etwas umgangssprachlich, diese könnte man noch sachlicher schreiben (z.B. „…geht man später immer mehr ins Detail.“, „Oftmals stellt sich die Frage „Kann man mit seinem Team nicht einfach rauslaufen und schauen wie es läuft? “. Dies kann funktionieren ist jedoch sehr unwahrscheinlich, da man mit hoher Wahrscheinlichkeit einige Dinge vergessen wird.“). 
Außerdem würde ich im letzten Beispiel nur auf die richtige Herangehensweise mit den 7 W Fragen eingehen und dafür die 7 Ws genauer erklären. Die falsche Methode würde ich weglassen oder nur als z.B. mögliche/typische Fehlerquelle anführen, damit es keine Verwirrungen gibt.
Im Satz „Deshalb stellen die 7W-Fragen einen guten Leitfaden zum Entwickeln eines Projektplans [dar].“ wurde das letzte Wort vergessen. Außerdem gibt es noch ein paar Zeichensetzungsfehler.

Bei der Bearbeitung des Beitrags würde ich besonders auf die Zitate und einen sachliche(re)n Schreibstil achten.

2021-12-09 19:37 UTC, merged

2021-12-21 19:23 UTC, Emre12345678 commented
> Kriterium	Bewertung
> Front-Matter	ja
> Umfang	ja
> Belege	ja
> Links	nein
> Formatierung	nein
> Verlinkungen vorhanden	nein
> Abbildungen	ja
> Strukturierung des Beitrags	7
> Rechtschreibung	7
> Sprache	6
> Inhalt	8
> Einordnung in den Kontext	6
> Ansprechend für Zielgruppe	6
> # Zusammenfassung
> Der Artikel gibt zunächst einen Überblick über die einzelnen Planungsphasen im Projektmanagement. Anschließend werden Herausforderungen und Fehler in der Praxis angesprochen und die 7-W-Fragen als eine Hilfestellung während der Projektplanung genannt. Der folgende Abschnitt befasst sich mit der Bedeutung der Ziele und erklärt die notwendige Kompromissbereitschaft mit dem magischen Dreieck. Als Hauptziele des Projektmanagements werden Organisation, Planung, Steuerung und Leitung aufgeführt. Abschließend werden die SMART-Regel und damit zusammenhängend die Bedeutung von realistischen Zielen genannt.
> 
> # Positive Aspekte
> Der Fließtest umfasst knapp 600 Wörter und enthält Quellen. Die Abbildung vom magischen Dreieck ist passend und veranschaulicht die genannten Zielkonflikte im Projektmanagement. Durch die inhaltliche Aufteilung hat man insgesamt einen guten Überblick über das Thema.
> 
> # Negative Aspekte
> Im ersten Abschnitt wiederholt sich ein Absatz, diesen auf jeden Fall noch löschen. Ich glaube, dass du teilweise vergessen hast, direkte Zitate als solche anzugeben? :'D (z.B. „Je kürzer die Zeit, desto höher die Kosten. Je umfangreicher die Dienste, desto länger die Zeit") Die Internetseiten, die in den Quellen als Hyperlinks hinterlegt wurden, funktionieren zwar, aber nicht die internen Links im Inhaltsverzeichnis („404“). (Ich bin mir außerdem nicht sicher, ob ein Inhaltsverzeichnis unbedingt notwendig ist) Die Codes für die Quellen müssten nochmal überprüft werden, da sie nicht zu den Nachweisen führen (Sie sollten blau sein). Im Fließtext sind keine Verlinkungen auf andere Kompendiums- oder externe Beiträge vorhanden. Du könntest z.B die Beiträge für die Themen Projektmanagement und Projektmitarbeiter verlinken. Damit die Überschriften einheitlich sind, könnte die 2. Themenüberschrift auch im Nominalstil formuliert werden. Die Nummerierungen und die Doppelpunkte könnte man auch weglassen. Die in der Beispieldatei enthaltenen Überschriften „Siehe auch“ und „Weiterführende Literatur“ fehlen und könnten / sollten noch ergänzt werden. Einige Formulierungen sind etwas umgangssprachlich, diese könnte man noch sachlicher schreiben (z.B. „…geht man später immer mehr ins Detail.“, „Oftmals stellt sich die Frage „Kann man mit seinem Team nicht einfach rauslaufen und schauen wie es läuft? “. Dies kann funktionieren ist jedoch sehr unwahrscheinlich, da man mit hoher Wahrscheinlichkeit einige Dinge vergessen wird.“). Außerdem würde ich im letzten Beispiel nur auf die richtige Herangehensweise mit den 7 W Fragen eingehen und dafür die 7 Ws genauer erklären. Die falsche Methode würde ich weglassen oder nur als z.B. mögliche/typische Fehlerquelle anführen, damit es keine Verwirrungen gibt. Im Satz „Deshalb stellen die 7W-Fragen einen guten Leitfaden zum Entwickeln eines Projektplans [dar].“ wurde das letzte Wort vergessen. Außerdem gibt es noch ein paar Zeichensetzungsfehler.
> 
> Bei der Bearbeitung des Beitrags würde ich besonders auf die Zitate und einen sachliche(re)n Schreibstil achten.



> Kriterium	Bewertung
> Front-Matter	ja
> Umfang	ja
> Belege	ja
> Links	nein
> Formatierung	nein
> Verlinkungen vorhanden	nein
> Abbildungen	ja
> Strukturierung des Beitrags	8
> Rechtschreibung	7
> Sprache	5
> Inhalt	6
> Einordnung in den Kontext	5
> Ansprechend für Zielgruppe	4
> # Zusammenfassung
> In diesem Artikel geht es insgesamt darum, die grundsätzlichen Aspekte der Zielplanung zu erläutern. Dabei wird sowohl auf die Planung, als auch auf die Durchsetzung eingegangen. Es wird hier sowohl der personelle Aspekt, als auch der finanzielle Aspekt beleuchtet.
> 
> Es werden im nächsten Abschnitt die Schritte der Projektplanung aufgezählt und erläutert. Zudem wird auf die Umsetzung in der Praxis eingegangen und die Probleme dabei aufgezählt.
> 
> Abschließend werden die Ziele hinter der Zielplanung beleuchtet und auf das magische Dreieck eingegangen. Anhand daran wird erklärt, welche Aspekte in der Zielplanung (Kosten/Leistung/Zeit) nie außer Acht gelassen werden dürfen , um die Hauptziele zu erreichen.
> 
> Anhand der SMART-Regel will der Verfasser dem Leser ein Werkzeug an die Hand geben, das Ziele im Vornherein klar definiert, um bei Abschluss eines Projektes dessen Erfolg ohne Schwierigkeiten bewerten zu können.
> 
> # Positive Aspekte
> Was ist gut: Der Beitrag an sich ist gut strukturiert. Du hast einen klaren Aufbau, indem du zunächst generell den Begriff Zielplanung erläuterst und dann genauer auf den Sinn dahinter eingehst und auch Probleme und neutrale Handlungsempfehlungen (z.B SMART-Regel) erklärst.
> 
> Umfang ist auch passend. Es wird das wichtigste erklärt ohne, dass es den Rahmen sprengt.
> 
> Die Abbildung erfüllt auch auf jeden Fall ihren Zweck und visualisiert gut, was du in deinem Text erklärst.
> 
> # Negative Aspekte:
> Negativ ist leider, dass man sich bereits nach dem ersten Satz schwer tut, dem Inhalt deines Textes zu folgen. Der erste Abschnitt ist sehr verwirrend. Es wird nicht klar, was du hier genau sagen möchtest. Das liegt zum Teil auch am sprachlichen Ausdruck.
> 
> Bei der Formatierung ist einiges nicht ganz richtig. Du musst keine Nummerierung benutzen. Auch hast du im ersten Abschnitt des Textes den einen Teil einfach doppelt. Das MUSS auf jeden Fall rausgenommen werden.
> 
> Die Verlinkungen innerhalb des Textes funktionieren leider kein einziges Mal. Das liegt daran, dass die Klammer vor den Punkt muss (Also [^x].) Dann funktioniert der Link, wenn du innerhalb darauf gehst. Außerdem werden die Zahlen dann als blaue Hochzahl erscheinen.
> 
> Leider hast du auch innerhalb des Textes kein einziges mal auf einen anderen Kompediumsartikel verlinkt, obwohl das mehrfach möglich gewesen wäre (z.B SMART-Regel oder magisches Dreieck). Dadurch wird der Artikel nicht sehr ansprechend für die Zielgruppe, da sie sich jedes Mal den passenden Artikel dazu heraussuchen müssen. Auch wird nicht ganz klar, wie dein Thema generell in den Kontext des Projektmanagements passt, weil du nicht wirklich erläuterst, in welchen Situationen man denn nun das alles anwendet.
> 
> # Was geht besser:
> Ich würde innerhalb des Beitrags deutlich häufiger zitieren. Du machst das immer nur am Ende eines langen Absatzes. Sprachlich würde ich den Text auf jeden Fall nochmal überarbeiten. Du doppelst dich leider sehr oft in deinen Formulierungen oder benutzt Füllwörter wie "dann" mehrfach hintereinander, was den Text unsachlich erscheinen lässt. Ein paar Rechtschreibfehler/Zeichensetzungsfehler sind auch drin, diese lassen sich aber schnell ausbessern ;) Was ich an deiner Stelle auch noch auf jeden Fall machen würde, ist weiterführende Literatur und Siehe auch zu benutzen. Das zeigt, dass du dich mit dem Thema auseinander gesetzt hast und dem Leser die weiterer Recherche erleichterst, indem du im passende Literatur vorschlägst.
> 
> Das Inhaltsverzeichnis würde ich weglassen, wenn dann müsste es an den Anfang deines Artikels und nicht an das Ende.
> 
> Wenn du dich da nochmal bezüglich des Inhalts und des Ausdrucks in den Leser hereinversetzt und bedenkst, dass er sich sehr wahrscheinlich nicht mit dem Thema auskennt und das in deinem "roten Faden" berücksichtigst, wird das bestimmt ein lesenswerter Artikel, Voraussetzung ist auf jeden Fall da :)

@CatPac

2021-12-21 19:27 UTC, Emre12345678 commented
Sehr geehrte Damen und Herren, 
Ich bedanke mich ganz herzlich für euren Review. Ich habe mir alle Vorschläge zu Herzen genommen und zum einen den  Artikel in Bezug auf Sprache und Grammatik verbessert. Ich habe auch meine Quellen bzw. Verweise innerhalb des Textes verbessert, sodass sie funktionieren. Zum anderen habe ich auch auf andere Kompendiumsartikel verwiesen und den Artikel inhaltlich bearbeitet.
@MillaLena @FerYilm @CatPec