Kostentrendanalyse; Scrumbut
ManagingProjectsSuccessfully/ManagingProjectsSuccessfully.github.io pull request #222
Opened 2021-11-23 20:48 UTC by thujavanj

2021-11-26 16:01 UTC, fe94fiqy requested changes
| Kriterium | Bewertung|
|-----|---|
| Front-Matter | ja|
| Umfang | ja|
| Belege | ja |
| Links | ja|
| Formatierung | ja|
| Verlinkungen vorhanden | ja |
| Abbildungen | nein |
| Strukturierung des Beitrags | 10 |
| Rechtschreibung | 10|
| Sprache | 10|
| Inhalt | 10|
| Einordnung in den Kontext | 10|
| Ansprechend für Zielgruppe | 10|

# Zusammenfassung

Der Artikel befasst sich mit einem der Faktoren die berücksichtigt werden müssen im Projektmanagement ,die Kostentrendanalyse .Weiter wird ihre Wichtigkeit anhand  der Vorteilhaftigkeit erläutert  aber auch ins Betracht werden die möglichen Nachteile gezogen.


# Positive Aspekte
Autor  hat die Thema inhaltlich gut erklärt .Der Ablauf  der KTA wird in prägnante Art dargestellt .

# Negative Aspekte
Die Bilder kann man nicht öffnen (error 404 ).

2021-12-05 14:23 UTC, tcansel requested changes
| Kriterium | Bewertung|
|-----|---|
| Front-Matter | ja |
| Umfang | ja |
| Belege | ja |
| Links | ja |
| Formatierung | ja |
| Verlinkungen vorhanden | ja |
| Abbildungen | nein |
| Strukturierung des Beitrags | 10 |
| Rechtschreibung | 10|
| Sprache | 10 |
| Inhalt | 10|
| Einordnung in den Kontext | 10|
| Ansprechend für Zielgruppe | 10|

# Zusammenfassung

Dieser Artikel beschäftigt sich mit dem Thema Kostentrendanalyse. Der Autor geht dabei auf verschiedene Aspekte ein, wie z.B.: Ziele, Vor-& Nachteile und erklärt auch schrittweise den Ablauf der Analyse. 

# Positive Aspekte

•	Front Matter und Quellen sind gut
•	Artikel ist gut strukturiert
•	Gute Einleitung
•	Alle wichtigen Aspekte wurden genannt 

# Negative Aspekte

•	Abbildung kann nicht geöffnet werden
•	Keine Angaben unter „weiterführende Literatur“ zu finden 
•	Am Ende wäre evtl. eine kleine Zusammenfassung sinnvoll

2021-12-05 14:59 UTC, tcansel requested changes
| Kriterium | Bewertung|
|-----|---|
| Front-Matter | ja |
| Umfang | ja |
| Belege | ja |
| Links | ja |
| Formatierung | ja |
| Verlinkungen vorhanden | ja |
| Abbildungen | ja |
| Strukturierung des Beitrags | 9 |
| Rechtschreibung | 10|
| Sprache | 9 |
| Inhalt | 10|
| Einordnung in den Kontext | 10|
| Ansprechend für Zielgruppe | 10|

# Zusammenfassung

Dieser Artikel beschäftigt sich mit dem Thema Scrumbut. Der Autor definiert als erstes den Begriff Scrumbut und geht danach auf die Intention ein. Außerdem geht er auf den Scrumbut Syntax ein und nennt Gründe für diesen. Als letztes bewertet er den Scrumbut.

# Positive Aspekte

•	Front Matter und Quellen sind gut
•	Artikel ist gut strukturiert
•	Alle wichtigen Aspekte wurden genannt 
•	Abbildung passt zum Inhalt
•	Text enthält Verlinkungen 

# Negative Aspekte

•	Das Inhaltsverzeichnis könnte man nach der Definition einfügen (sieht besser aus)
•	Unter der Abbildung fehlt die Beschreibung: der Satz oberhalb der Abbildung könnte hierfür genutzt werden

2021-12-06 22:11 UTC, YeldaUzun requested changes
| Kriterium | Bewertung|
|-----|---|
| Front-Matter | ja |
| Umfang | ja |
| Belege | ja |
| Links | ja |
| Formatierung | ja |
| Verlinkungen vorhanden | ja |
| Abbildungen | nein |
| Strukturierung des Beitrags | 10 |
| Rechtschreibung | 8 |
| Sprache | 8 |
| Inhalt | 10 |
| Einordnung in den Kontext | 10 |
| Ansprechend für Zielgruppe | 10 |

# Zusammenfassung

Der Artikel befasst sich mit der Kostentrendanalyse. Es werden die Vor- und Nachteile, sowie das Ziel der Kostentrendanalyse beschrieben. Anschließend wird der Ablauf der Kostentrendanalyse vorgestellt. 

# Positive Aspekte
Der Artikel beinhaltet Belege und Verlinkungen zu anderen Themen. Die Links der Verlinkungen und Belege funktionieren. Der Umfang von 500 Wörtern wurde eingehalten. 
Es wurde ein guter Überblick über die Kostentrendanalyse geschaffen und auf die wichtigsten Aspekte eingegangen. 

# Negative Aspekte

Die Quellenangabe im zweiten Abschnitt des Artikels wurde vor dem Punkt angegeben. An manchen Stellen im Artikel fehlen Wörter oder es wurden nicht passende Wörter verwendet.
Siehe zum Beispiel: "Jede Analyse sowie jede Prognose und nur so gut wie die Daten aus der sie hervorgehen.". Die Verwendung von "man"-Konstruktion ist für Artikel eher nicht geeignet. Die Abbildung im Artikel lässt sich nicht öffnen. Die Abkürzung KTA wurde im Text nicht erläutert, zudem ist keine weiterführende Literatur angegeben.

2021-12-09 19:40 UTC, merged

2021-12-22 17:24 UTC, thujavanj commented
> Die Bilder kann man nicht öffnen (error 404 ).
Hallo   @fe94fiqy, 
vielen Dank für deine positive Rückmeldung. Anscheinend konnten mehrere Personen meine Bilder nicht öffnen. Ich weiß jedoch nicht genau woran es lag, da ich es genau wie im Beispieltext erklärt gemacht habe. Trotzdem habe ich mein Bildformat von Jpeg auf png geändert. Ich bin mir aber trotzdem nicht sicher, ob es diesmal funktioniert, da ich das Bild schon beim letzten Mal selbst gesehen habe.

2021-12-22 17:34 UTC, thujavanj commented
> • Abbildung kann nicht geöffnet werden • Keine Angaben unter „weiterführende Literatur“ zu finden • Am Ende wäre evtl. eine kleine Zusammenfassung sinnvoll
Hallo @tcansel, 
viel Dank für dein Feedback. Wie ich bereits @fe94fiqy mitgeteilt habe, weiß ich nicht genau woran es liegt, dass man mein Bild nicht sehen kann. Ich selber hab das Bild beim letzten Mal auch schon gesehen und ich habe alles wie im Beispieltext erklärt gemacht. Diesmal habe ich aber das Bildformat auf PNG geändert und hoffe, dass es klappt. Den Punkt weiterführende Literatur habe ich um eine zusätzliche Website ergänzt. Ich bin auch der Meinung, dass ein Fazit alles noch einmal abrunden würde. Jedoch habe ich mich bewusst dagegen entschieden, da mein Artikel sonst den Rahmen von 500 Wörtern überschritten hätte. Der Artikel hatte so schon etwa 520 Wörter.

2021-12-22 17:57 UTC, thujavanj commented
> • Das Inhaltsverzeichnis könnte man nach der Definition einfügen (sieht besser aus) • Unter der Abbildung fehlt die Beschreibung: der Satz oberhalb der Abbildung könnte hierfür genutzt werden
Hallo @tcansel,
ich habe die Punkte, die du erwähnt hast, verbessert. Vielen Dank für deine Tipps.

2021-12-22 18:56 UTC, thujavanj commented
> Die Quellenangabe im zweiten Abschnitt des Artikels wurde vor dem Punkt angegeben. An manchen Stellen im Artikel fehlen Wörter oder es wurden nicht passende Wörter verwendet. Siehe zum Beispiel: "Jede Analyse sowie jede Prognose und nur so gut wie die Daten aus der sie hervorgehen.". Die Verwendung von "man"-Konstruktion ist für Artikel eher nicht geeignet. Die Abbildung im Artikel lässt sich nicht öffnen. Die Abkürzung KTA wurde im Text nicht erläutert, zudem ist keine weiterführende Literatur angegeben.
Hallo @YeldaUzun ,
vielen Dank für deine Rückmeldung. Ich habe alle deine Verbesserungsvorschläge umgesetzt.