Herausforderungen bei internationalen Projekten
ManagingProjectsSuccessfully/ManagingProjectsSuccessfully.github.io pull request #223
Opened 2021-11-23 20:49 UTC by tcansel

2021-11-26 15:28 UTC, fe94fiqy requested changes
| Kriterium | Bewertung|
|-----|---|
| Front-Matter | ja |
| Umfang | ja|
| Belege | ja |
| Links | ja|
| Formatierung | ja|
| Verlinkungen vorhanden | ja |
| Abbildungen | ja |
| Strukturierung des Beitrags | 10|
| Rechtschreibung | 10|
| Sprache | 10 |
| Inhalt | 10|
| Einordnung in den Kontext | 10|
| Ansprechend für Zielgruppe | 10|

# Zusammenfassung

Der Artikel befasst sich mit den Herausforderungen bei Internationalen Projekten das durch eine Vielzahl von Faktoren beeinflusst werden kann wie z.B. rechtlichen ,politischen ,sprachlichen Rahmen und erläutert weiter wie diese zu überwinden sind .

# Positive Aspekte

Autor hat einen sehr strukturierten Einblick in das Thema gegeben .

# Negative Aspekte
Keine.

2021-12-06 17:12 UTC, xyily commented
| Kriterium | Bewertung|
|-----|---|
| Front-Matter | ja |
| Umfang | ja |
| Belege | ja |
| Links | ja |
| Formatierung | ja |
| Verlinkungen vorhanden | ja |
| Abbildungen | ja |
| Strukturierung des Beitrags | 10 |
| Rechtschreibung | 8 |
| Sprache | 10 |
| Inhalt | 9 |
| Einordnung in den Kontext | 10|
| Ansprechend für Zielgruppe | 10|

# Zusammenfassung
Der Artikel befasst sich mit Herausforderungen bei internationalen Projekten. Nach einer kurzen Einführung werden Herausforderungen beleuchtet und anschließend ein Fazit gezogen.

# Positive Aspekte
Der Umfang von 500 Wörtern wurde eingehalten. Belege sind vorhanden und Links funktionieren. Die Formatierung ist gelungen, besonders positiv sind die Unterüberschriften zu den Herausforderungen, da sie zum einfacheren Verständnis beitragen. Die Sprache ist sachlich und angemessen. Der Inhalt ist klar verständlich. 

# Negative Aspekte
Es gab wenige grammatikalische / Rechtschreibfehler (z.B. _Der Einkäufer_ spielt eine zentrale Rolle im internationalen Umfeld: _ihre_ Aufgabe ist es[ …], oder: „Dabei kann es jedoch zu Schwierigkeiten kommen, da bestimmte Ressourcen vor Ort nicht zu finden sind und diese dementsprechend dorthin geliefert werden müssen, _welches_ wiederum mit hohen Kosten verbunden ist“, oder: „Dadurch wird der ganze Prozess noch ein ganzes Stück komplexer; um [...]“ -> wieso ein semikolon?) 
Des Weiteren hätte ich mich über eine kurze Erklärung zur Abbildung gefreut.

2021-12-06 20:14 UTC, xyily reviewed
| Kriterium | Bewertung|
|-----|---|
| Front-Matter | ja |
| Umfang | ja |
| Belege | ja |
| Links | ja |
| Formatierung | ja |
| Verlinkungen vorhanden | ja |
| Abbildungen | ja |
| Strukturierung des Beitrags | 10 |
| Rechtschreibung | 8 |
| Sprache | 10 |
| Inhalt | 9 |
| Einordnung in den Kontext | 10|
| Ansprechend für Zielgruppe | 10|

# Zusammenfassung
Der Artikel befasst sich mit Herausforderungen bei internationalen Projekten. Nach einer kurzen Einführung werden Herausforderungen beleuchtet und anschließend ein Fazit gezogen.

# Positive Aspekte
Der Umfang von 500 Wörtern wurde eingehalten. Belege sind vorhanden und Links funktionieren. Die Formatierung ist gelungen, besonders positiv sind die Unterüberschriften zu den Herausforderungen, da sie zum einfacheren Verständnis beitragen. Die Sprache ist sachlich und angemessen. Der Inhalt ist klar verständlich. 

# Negative Aspekte
Es gab wenige grammatikalische / Rechtschreibfehler (z.B. _Der Einkäufer_ spielt eine zentrale Rolle im internationalen Umfeld: _ihre_ Aufgabe ist es[ …], oder: „Dabei kann es jedoch zu Schwierigkeiten kommen, da bestimmte Ressourcen vor Ort nicht zu finden sind und diese dementsprechend dorthin geliefert werden müssen, _welches_ wiederum mit hohen Kosten verbunden ist“, oder: „Dadurch wird der ganze Prozess noch ein ganzes Stück komplexer; um [...]“ -> wieso ein semikolon?) 
Des Weiteren hätte ich mich über eine kurze Erklärung zur Abbildung gefreut.

2021-12-06 21:24 UTC, YeldaUzun requested changes
| Kriterium | Bewertung|
|-----|---|
| Front-Matter | ja |
| Umfang | ja |
| Belege | ja |
| Links | ja |
| Formatierung | ja |
| Verlinkungen vorhanden | ja |
| Abbildungen | ja |
| Strukturierung des Beitrags | 10 |
| Rechtschreibung | 8 |
| Sprache | 8 |
| Inhalt | 8 |
| Einordnung in den Kontext | 10 |
| Ansprechend für Zielgruppe | 9 |

# Zusammenfassung

Der Artikel befasst sich mit den Herausforderungen bei internationalen Projekten. Hierbei werden Herausforderungen, wie zum Beispiel Machtverhältnisse und Lieferengpässe erläutert. Zum Schluss wurde eine Empfehlung für das meistern von internationalen Projekten gegeben und ein Fazit gezogen. 

# Positive Aspekte
Der Artikel ist in den Herausforderungen unterteilt und weist somit eine sehr gute Struktur auf. Der Rahmen von 500 Wörtern wurde eingehalten. Zudem sind Belege und Verlinkungen vorhanden, sowie eine Abbildung. Die Links der Belege und Verlinkungen funktionieren. 

# Negative Aspekte
Der Artikel weist Kommafehler auf und die Quellenangaben im Text wurden vor dem Punkt gesetzt. [1]. --> .[1]
Die Doppelpunkte im Text stören den Lesefluss. Besser wäre es diese in den Satz einzubauen oder Aufzählungspunkte zu verwenden. Außerdem ist nach den Doppelpunkten die Verwendung von Groß- und Kleinschreibung nicht immer richtig. Im Absatz Lieferengpässe wurde mehrmals der Konnektor "welche" verwendet, eine vielfältigere Wortwahl wäre besser.
Der Inhalt könnte etwas präziser sein. So ist zum Beispiel der Satz: "Damit das Projekt nicht versagt, sollte man miteinander agieren, damit gegen keine Regeln verstoßen wird." Inhaltlich nicht ganz klar. Hierbei stellt sich die Frage, wer miteinander agieren soll, die Politik oder das Team? Auf die Abbildung im Artikel wurde leider nicht eingegangen.

2021-12-06 21:40 UTC, xyily requested changes
| Kriterium | Bewertung|
|-----|---|
| Front-Matter | ja |
| Umfang | ja |
| Belege | ja |
| Links | ja |
| Formatierung | ja |
| Verlinkungen vorhanden | ja |
| Abbildungen | ja |
| Strukturierung des Beitrags | 10 |
| Rechtschreibung | 8 |
| Sprache | 10 |
| Inhalt | 9 |
| Einordnung in den Kontext | 10|
| Ansprechend für Zielgruppe | 10|

# Zusammenfassung
Der Artikel befasst sich mit Herausforderungen bei internationalen Projekten. Nach einer kurzen Einführung werden Herausforderungen beleuchtet und anschließend ein Fazit gezogen.

# Positive Aspekte
Der Umfang von 500 Wörtern wurde eingehalten. Belege sind vorhanden und Links funktionieren. Die Formatierung ist gelungen, besonders positiv sind die Unterüberschriften zu den Herausforderungen, da sie zum einfacheren Verständnis beitragen. Die Sprache ist sachlich und angemessen. Der Inhalt ist klar verständlich. 

# Negative Aspekte
Es gab wenige grammatikalische / Rechtschreibfehler (z.B. _Der Einkäufer_ spielt eine zentrale Rolle im internationalen Umfeld: _ihre_ Aufgabe ist es[ …], oder: „Dabei kann es jedoch zu Schwierigkeiten kommen, da bestimmte Ressourcen vor Ort nicht zu finden sind und diese dementsprechend dorthin geliefert werden müssen, _welches_ wiederum mit hohen Kosten verbunden ist“, oder: „Dadurch wird der ganze Prozess noch ein ganzes Stück komplexer; um [...]“ -> wieso ein semikolon?) 
Des Weiteren hätte ich mich über eine kurze Erklärung zur Abbildung gefreut.

2021-12-06 21:43 UTC, xyily commented
Sorry ich hab beim ersten mal "Review changes" vergessen den Punkt auf "Request changes" zu setzen... @MartinEnders

2021-12-09 19:40 UTC, merged

2021-12-22 18:04 UTC, tcansel commented
Hallo @xyily, vielen Dank für deinen Feedback. Ich habe den Beitrag auf Rechtschreibung/Grammatik geprüft und verbessert. Auch habe ich kurz die Abbildung erklärt.

2021-12-22 18:15 UTC, tcansel commented
Hallo @YeldaUzun, vielen Dank für deinen Feedback. Ich habe die Doppelpunkte im Text entfernt und habe aus dem Satz zwei Sätze gemacht. Ich habe den Beitrag nochmal auf Rechtschreibung, Grammatik und Kommafehler geprüft. Auch habe ich eine Erklärung zur Abbildung ergänzt.