Toyota Produktionssysteme
ManagingProjectsSuccessfully/ManagingProjectsSuccessfully.github.io pull request #224
Opened 2021-11-23 21:02 UTC by YeldaUzun

2021-11-26 14:41 UTC, fe94fiqy requested changes
| Kriterium | Bewertung|
|-----|---|
| Front-Matter | ja |
| Umfang | ja|
| Belege | ja |
| Links | ja|
| Formatierung | ja |
| Verlinkungen vorhanden | ja |
| Abbildungen | ja |
| Strukturierung des Beitrags | 10 |
| Rechtschreibung | 10|
| Sprache | 10 |
| Inhalt | 10|
| Einordnung in den Kontext | 10|
| Ansprechend für Zielgruppe | 10|

# Zusammenfassung

Der Artikel befasst sich mit dem Konzept der Toyota Produktionssystems das für die Verbesserung organisatorischer Abläufe in den 50er entwickelt wurde um somit zur einer erhöhten Qualität und Produktivität führte .

# Positive Aspekte

Autor hat eine sehr strukturierte Darstellung der Prozesse des Produktionssystems erstellt .
# Negative Aspekte

Keine Kommentare zur Verbesserung nötig .

2021-12-01 20:04 UTC, uc00ekun requested changes
| Kriterium | Bewertung|
|-----|---|
| Front-Matter | ja |
| Umfang | ja |
| Belege | ja |
| Links | ja |
| Formatierung | ja |
| Verlinkungen vorhanden | ja |
| Abbildungen | ja |
| Strukturierung des Beitrags | 10 |
| Rechtschreibung | 8 |
| Sprache | 10 |
| Inhalt | 10 |
| Einordnung in den Kontext | 10 |
| Ansprechend für Zielgruppe | 10 |

# Zusammenfassung

Der Artikel befasst sich mit dem Konzept des Toyota Produktionssystems. Hierbei handelt es sich um ein für Toyota entwickelter Produktionsprozess, um organisatorische Abläufe zu verbessern und sowohl Qualität als auch Produktivität zu steigern. Der Autor geht dabei auf die verschiedenen Elemente und Prinzipien des Produktionssystems ein. 

# Positive Aspekte

Der Autor hat den Text mithilfe der Abbildung gut strukturiert dargestellt. Außerdem wurde das Thema sehr gut und einfach erklärt.

# Negative Aspekte

Ein paar Rechtschreib- und Grammatikfehler: z.B. Zeile 1 "ist ein (...) Serienverfahren, das sich" (anstatt dass); bei der Bildbeschreibung "Produktionssystems" (Tippfehler - k und u vertauscht); sowie einige fehlende Kommata (z.B. im Abschnitt Just-In-Time: "nur die Menge (...) zu liefern, die bestellt wurden."

2021-12-06 19:17 UTC, xyily commented
| Kriterium | Bewertung|
|-----|---|
| Front-Matter | ja |
| Umfang | ja |
| Belege | ja |
| Links | ja |
| Formatierung | ja |
| Verlinkungen vorhanden | ja |
| Abbildungen | ja |
| Strukturierung des Beitrags | 10 |
| Rechtschreibung | 9 |
| Sprache | 10 |
| Inhalt | 10 |
| Einordnung in den Kontext | 10|
| Ansprechend für Zielgruppe | 10|

# Zusammenfassung
Der Inhalt widmet sich dem Toyota Produktionssystem, nach kurzer historischer Erklärung werden das Toyota Produktionssystem und die einzelnen Elemente vertieft. 

# Positive Aspekte
Umfang ist in Ordnung, Belege sind vorhanden, Links funktionieren, die Strukturierung ist durch die Unterüberschriften gelungen gestaltet, es sind wie gefordert auch die Verlinkungen zu angrenzenden Themen vorhanden, die gewählte Abbildung passt sehr gut zum Inhalt. Der Artikel ist sehr informativ und interessant. 

# Negative Aspekte
Man könnte außer ein paar fehlenden Kommata höchstens bemängeln, dass der geforderte Umfang überschritten wurde, allerdings finde ich den Artikel so gut wie er ist und würde nichts weglassen wollen. Daher keine Kritik.

2021-12-06 21:42 UTC, xyily requested changes
| Kriterium | Bewertung|
|-----|---|
| Front-Matter | ja |
| Umfang | ja |
| Belege | ja |
| Links | ja |
| Formatierung | ja |
| Verlinkungen vorhanden | ja |
| Abbildungen | ja |
| Strukturierung des Beitrags | 10 |
| Rechtschreibung | 9 |
| Sprache | 10 |
| Inhalt | 10 |
| Einordnung in den Kontext | 10|
| Ansprechend für Zielgruppe | 10|

# Zusammenfassung
Der Inhalt widmet sich dem Toyota Produktionssystem, nach kurzer historischer Erklärung werden das Toyota Produktionssystem und die einzelnen Elemente vertieft. 

# Positive Aspekte
Umfang ist in Ordnung, Belege sind vorhanden, Links funktionieren, die Strukturierung ist durch die Unterüberschriften gelungen gestaltet, es sind wie gefordert auch die Verlinkungen zu angrenzenden Themen vorhanden, die gewählte Abbildung passt sehr gut zum Inhalt. Der Artikel ist sehr informativ und interessant. 

# Negative Aspekte
Man könnte außer ein paar fehlenden Kommata höchstens bemängeln, dass der geforderte Umfang überschritten wurde, allerdings finde ich den Artikel so gut wie er ist und würde nichts weglassen wollen. Daher keine Kritik.

2021-12-06 21:43 UTC, xyily commented
Sorry ich hab beim ersten mal "Review changes" vergessen den Punkt auf "Request changes" zu setzen... @MartinEnders

2021-12-09 19:40 UTC, merged

2021-12-22 19:57 UTC, YeldaUzun commented
Hallo @fe94fiqy, @uc00ekun, @xyily 

vielen Dank für euer Feedback und Bewertung. Die Rechtschreib- und Grammatikfehler wurden verbessert.