Wissensmarkt
ManagingProjectsSuccessfully/ManagingProjectsSuccessfully.github.io pull request #225
Opened 2021-11-23 21:27 UTC by fe94fiqy

2021-12-02 09:22 UTC, CatrinSc requested changes
| Kriterium | Bewertung|
|-----|---|
| Front-Matter | ja |
| Umfang | nein|
| Belege | nein |
| Links | nein|
| Formatierung | nein|
| Verlinkungen vorhanden | nein |
| Abbildungen | nein |
| Strukturierung des Beitrags | 3 |
| Rechtschreibung | 3 |
| Sprache | 2 |
| Inhalt | 8 |
| Einordnung in den Kontext | 2 |
| Ansprechend für Zielgruppe | 7 |

# Zusammenfassung

Der Artikel erklärt den Wissensmarkt und gibt Einblicke in die Vorgänge. Des Weiteren wird eine Einordnung und deren Eignung in die agilen bzw. klassischen Projektmethoden vorgenommen.

# Positive Aspekte

Ich finde den Inhalt gut und auch geeignet für unsere Zielgruppe. Es ist kurz und prägnant formuliert.

# Negative Aspekte

Leider wurden viele Aspekte der Tabelle gänzlich ignoriert (siehe Github Gruppe EInträge anlegen/Review Tabelle). Ich empfehle daher bei der Überarbeitung diese zu beachten, indem du Bilder, Tabellen, Aufzählung, Überschriften etc. einfügst. Leider war es daher etwas langweilig gestaltet. Des Weiteren gibt es sehr viele Rechtschreib- und Grammatikfehler. Ich würde gegebenenfalls einen Freund/Familienmitglied o.ä. nochmal drüber lesen lassen.

2021-12-02 22:10 UTC, uc00ekun requested changes
| Kriterium | Bewertung|
|-----|---|
| Front-Matter | ja |
| Umfang | nein|
| Belege | nein |
| Links | nein|
| Formatierung | nein|
| Verlinkungen vorhanden | nein |
| Abbildungen | nein |
| Strukturierung des Beitrags | 4 |
| Rechtschreibung | 4 |
| Sprache | 3 |
| Inhalt | 8 |
| Einordnung in den Kontext | 3 |
| Ansprechend für Zielgruppe | 8 |

# Zusammenfassung

Der Artikel befasst sich mit dem Thema Wissensmarkt. Dieser soll die Mitarbeiter unter anderem dabei unterstützen, Wissensgemeinschaften zu bilden und Problemlösungen zu finden. Der Autor geht außerdem auf verschiedene Aspekte ein, wie etwa die Vorgehensweise und Abgrenzung zum klassischen Projektmanagement. 

# Positive Aspekte

Das Thema wurde innerhalb vieler Aspekte beleuchtet und anschaulich erklärt.

# Negative Aspekte

Der Autor sollte aufjedenfall die fehlenden Punkte der Tabelle nacharbeiten, wie z.B. eine Abbildung und Verlinkungen einfügen. Wichtig ist es auch, die jeweiligen Quellen im Text anzugeben. Eine Aufzählung ist zwar beim Aspekt der Vorgehensweise vorhanden, jedoch nicht richtig formatiert. Außerdem sind einige Rechtschreib- sowie Grammatikfehler zu finden. Auch einige Formulierungen könnten überarbeitet werden.

2021-12-06 18:25 UTC, xyily commented
| Kriterium | Bewertung|
|-----|---|
| Front-Matter | ja |
| Umfang | nein |
| Belege | nein |
| Links | ja |
| Formatierung | nein |
| Verlinkungen vorhanden | nein |
| Abbildungen | nein |
| Strukturierung des Beitrags | 3 |
| Rechtschreibung | 4 |
| Sprache | 4 |
| Inhalt | 8 |
| Einordnung in den Kontext | 5|
| Ansprechend für Zielgruppe | 7|

# Zusammenfassung
Der Inhalt widmet sich dem Wissensmarkt und erklärt zunächst was ein Wissensmarkt ist und wie er in einer Organisation von Nutzen sein kann.

# Positive Aspekte
Im Quellenverweis verlinkte Links funktionieren. Der Inhalt an sich ist in Ordnung und informativ.
# Negative Aspekte
Der Umfang beträgt nur 378 Wörter, gefordert waren 500. In der Arbeit sind keine Hinweise auf die Quellen angegeben, was auf jeden Fall ergänzt werden sollte. Es wurde kein weiterer Artikel verlinkt, auch das wäre wichtig. Es gibt keine Überschriften, wünschenswert wären Haupt- sowie Unterüberschriften, um den Artikel besser zu strukturieren und interessanter zu gestalten. Es muss auch noch eine Abbildung eingefügt werden. Es fehlen Kommata und es sind einige grammatikalische Fehler zu finden, es wäre gut, wenn jemand zur Hilfe gezogen werden könnte, um diese zu beheben.

2021-12-06 20:12 UTC, xyily reviewed
| Kriterium | Bewertung|
|-----|---|
| Front-Matter | ja |
| Umfang | nein |
| Belege | nein |
| Links | ja |
| Formatierung | nein |
| Verlinkungen vorhanden | nein |
| Abbildungen | nein |
| Strukturierung des Beitrags | 3 |
| Rechtschreibung | 4 |
| Sprache | 4 |
| Inhalt | 8 |
| Einordnung in den Kontext | 5|
| Ansprechend für Zielgruppe | 7|

# Zusammenfassung
Der Inhalt widmet sich dem Wissensmarkt und erklärt zunächst was ein Wissensmarkt ist und wie er in einer Organisation von Nutzen sein kann.

# Positive Aspekte
Im Quellenverweis verlinkte Links funktionieren. Der Inhalt an sich ist in Ordnung und informativ.
# Negative Aspekte
Der Umfang beträgt nur 378 Wörter, gefordert waren 500. In der Arbeit sind keine Hinweise auf die Quellen angegeben, was auf jeden Fall ergänzt werden sollte. Es wurde kein weiterer Artikel verlinkt, auch das wäre wichtig. Es gibt keine Überschriften, wünschenswert wären Haupt- sowie Unterüberschriften, um den Artikel besser zu strukturieren und interessanter zu gestalten. Es muss auch noch eine Abbildung eingefügt werden. Es fehlen Kommata und es sind einige grammatikalische Fehler zu finden, es wäre gut, wenn jemand zur Hilfe gezogen werden könnte, um diese zu beheben.

2021-12-06 21:45 UTC, xyily requested changes
| Kriterium | Bewertung|
|-----|---|
| Front-Matter | ja |
| Umfang | nein |
| Belege | nein |
| Links | ja |
| Formatierung | nein |
| Verlinkungen vorhanden | nein |
| Abbildungen | nein |
| Strukturierung des Beitrags | 3 |
| Rechtschreibung | 4 |
| Sprache | 4 |
| Inhalt | 8 |
| Einordnung in den Kontext | 5|
| Ansprechend für Zielgruppe | 7|

# Zusammenfassung
Der Inhalt widmet sich dem Wissensmarkt und erklärt zunächst was ein Wissensmarkt ist und wie er in einer Organisation von Nutzen sein kann.

# Positive Aspekte
Im Quellenverweis verlinkte Links funktionieren. Der Inhalt an sich ist in Ordnung und informativ.
# Negative Aspekte
Der Umfang beträgt nur 378 Wörter, gefordert waren 500. In der Arbeit sind keine Hinweise auf die Quellen angegeben, was auf jeden Fall ergänzt werden sollte. Es wurde kein weiterer Artikel verlinkt, auch das wäre wichtig. Es gibt keine Überschriften, wünschenswert wären Haupt- sowie Unterüberschriften, um den Artikel besser zu strukturieren und interessanter zu gestalten. Es muss auch noch eine Abbildung eingefügt werden. Es fehlen Kommata und es sind einige grammatikalische Fehler zu finden, es wäre gut, wenn jemand zur Hilfe gezogen werden könnte, um diese zu beheben.

2021-12-06 21:45 UTC, xyily commented
Sorry ich hab beim ersten mal "Review changes" vergessen den Punkt auf "Request changes" zu setzen... @MartinEnders

2021-12-09 19:40 UTC, merged