Gantt_Diagramme
ManagingProjectsSuccessfully/ManagingProjectsSuccessfully.github.io pull request #226
Opened 2021-11-23 21:30 UTC by xyily

2021-12-02 10:09 UTC, CatrinSc requested changes
| Kriterium | Bewertung|
|-----|---|
| Front-Matter | ja |
| Umfang | ja |
| Belege | ja |
| Links | ja |
| Formatierung | ja |
| Verlinkungen vorhanden | ja |
| Abbildungen | ja |
| Strukturierung des Beitrags | 9 |
| Rechtschreibung | 10 |
| Sprache | 10 |
| Inhalt | 10 |
| Einordnung in den Kontext | 10 |
| Ansprechend für Zielgruppe | 10 |

# Zusammenfassung

Der Artikel bietet einen Einblick in das Gantt Diagramm. Man wird über die Entstehung, den Aufbau, die Erstellung sowie die Vor- und Nachteile aufgeklärt.

# Positive Aspekte

Ich finde den Beitrag sehr gut strukturiert sowie verständlich und informativ. Gerade die selbsterstellte Grafik ist sehr gut gelungen. Besonders gelungen ist auch der gut durchdachte und schlüssige Aufbau.

# Negative Aspekte

Negativ wäre für mich persönlich die Durchnummerierung. Ich würde 1.&2. als Überschrift formatieren und die anderen Unterpunkte jeweils als Unterüberschrift. Außerdem verstehe ich diesen 'Tabellensatz' (unter 2.Vor- und Nachteile) nicht.

2021-12-02 22:28 UTC, uc00ekun requested changes
| Kriterium | Bewertung|
|-----|---|
| Front-Matter | ja |
| Umfang | ja |
| Belege | ja |
| Links | ja |
| Formatierung | ja |
| Verlinkungen vorhanden | ja |
| Abbildungen | ja |
| Strukturierung des Beitrags | 10 |
| Rechtschreibung | 9 |
| Sprache | 10 |
| Inhalt | 10  |
| Einordnung in den Kontext | 10 |
| Ansprechend für Zielgruppe | 10 |

# Zusammenfassung

Der Artikel befasst sich mit dem Konzept des Gantt-Diagrammes, welches ein gängiges Werkzeug in der Projektplanung darstellt und dazu dient, die zeitliche Abfolge von Aktivitäten grafisch darzustellen. Der Autor geht hierbei auf verschiedene Aspekte, wie Entstehung, Aufbau, Erstellung sowie Vor- und Nachteile ein.

# Positive Aspekte

Der Artikel ist sehr gut strukturiert und beinhaltet alle wichtigen Informationen rund um das Thema. Die Abbildungen helfen dem besseren Verständnis.

# Negative Aspekte

Es sind einige Kommata-Fehler zu finden (z.B. bei 2.1 Vorteile im ersten Punkt); außerdem erscheint diese Formatierung unter Punkt 2 Vor-/Nachteile eher unpassend

2021-12-06 21:52 UTC, LysanderBenke requested changes
| Kriterium | Bewertung|
|-----|---|
| Front-Matter | ja|
| Umfang | ja|
| Belege | ja|
| Links | ja|
| Formatierung | ja|
| Verlinkungen vorhanden | ja|
| Abbildungen | ja|
| Strukturierung des Beitrags | 10 |
| Rechtschreibung | 9 |
| Sprache | 10 |
| Inhalt | 10 |
| Einordnung in den Kontext | 10 |
| Ansprechend für Zielgruppe | 10 |

# Zusammenfassung

Zuerst wird im Artikel das Gantt.Diagramm erklärt. Daraufhin wird die Geschischte des Gantt-Diagramms erzählt und der Aufbau und sowie die Erstellung des Diagramms erklärt. Zuletzt werden Vor- und Nachteile des Gantt-Diagramms genannt und eine Alternative zu diesem mit einem Beispiel gezeigt.

# Positive Aspekte

Der Inhalt ist leicht verständlich. Der Artikel ist sehr gut strukturiert und nummeriert. Die Sprache und Rechtschreibung zeigen kaum Fehler auf.

# Negative Aspekte

Rechtschreibfehler/Grammatikfehler
 in 1.1: Harmonogramm
1.3: Softwareprogramme
2.2 können, 
2.3 Projekt Umzug
Der Punkt 1 "Was ist ein Gant Diagramm" sollte in der Zusammenfassung stehen und kein extra Punkt sein.

2021-12-09 19:40 UTC, merged

2021-12-22 20:25 UTC, xyily commented
@CatrinSc vielen Dank für dein Feedback. Ich habe 1 und 2 als Überschriften genommen und die anderen Punkte jeweils als Unterpunkte. Auch den Tabellensatz habe ich entfernt.

2021-12-22 20:26 UTC, xyily commented
@uc00ekun Danke für dein Feedback, die Formatierung habe ich geändert und Kommata habe ich ebenfalls verbessert.

2021-12-22 20:27 UTC, xyily commented
@LysanderBenke Danke für dein Feedback. Ich habe die Rechtschreibfehler und Kommata verbessert.