Roadmap
ManagingProjectsSuccessfully/ManagingProjectsSuccessfully.github.io pull request #227
Opened 2021-11-23 21:33 UTC by uc00ekun

2021-12-02 09:46 UTC, CatrinSc requested changes
| Kriterium | Bewertung|
|-----|---|
| Front-Matter | ja |
| Umfang | ja |
| Belege | ja |
| Links | ja |
| Formatierung | ja |
| Verlinkungen vorhanden | ja |
| Abbildungen | ja |
| Strukturierung des Beitrags | 8 |
| Rechtschreibung | 10 |
| Sprache | 10 |
| Inhalt | 10 |
| Einordnung in den Kontext | 10 |
| Ansprechend für Zielgruppe | 10 |

# Zusammenfassung

Der Artikel thematisiert die Roadmap. Darin werden die verschiedenen Arten von Roadmaps erklärt sowie die Erstellung einer solchen. Zuletzt wird diese Thematik noch an einem anschaulichen Beispiel verdeutlicht.

# Positive Aspekte

Ich finde den Artikel sehr anschaulich, interessant und informativ gestaltet. Die Bilder eignen sich sehr gut, um den Inhalt darzustellen. Dieser Beitrag ist sehr kurzweilig.

# Negative Aspekte

Ich würde evtl die Projekt-Roadmap als Unterüberschrift der Kategorisierung machen und vielleicht auch etwas zu einer anderen Roadmap schreiben (z.B. Technologie-Roadmap). Dafür würde ich etwas von den Überschriften weglassen, wo jeweils nur ein Satz dazu steht. Oder einfach Versuchen diese Überschriften zusammenzufassen, damit ein längerer Absatz entsteht. Außerdem würde ich die Erstellung der Roadmap als Überschrift rauslöschen und zum Absatz von Roadmapping hinzufügen.

2021-12-06 21:28 UTC, LysanderBenke requested changes
| Kriterium | Bewertung|
|-----|---|
| Front-Matter | ja|
| Umfang | ja|
| Belege | ja|
| Links | ja|
| Formatierung | ja|
| Verlinkungen vorhanden | ja|
| Abbildungen | ja|
| Strukturierung des Beitrags | 10 |
| Rechtschreibung | 10 |
| Sprache | 10 |
| Inhalt | 9 |
| Einordnung in den Kontext | 10 |
| Ansprechend für Zielgruppe | 9 |

# Zusammenfassung

Kurze Zusammenfassung des/der Artikel

Der Artikel ist gut Strukturiert. Sprache und Rechtschreibung zeigen kaum Fehler auf. Der Artikel ist leich zu verstehen und Inhaltlich gut.

# Negative Aspekte

Rechtschreibfehler:
 Zusammenfassung: vor allem auseinander
Kategorisierung: gramatikalisch nicht "die häufigst" sondern "die am häufigsten"
Projekt-Roadmap würde ich als Unterüberschrift von Kategorisierung sehen.
Da gerade so 500 Wörter mit Quellen: Die vier Arten der Spezifizierungsansätze könnten noch erklärt werden.

2021-12-06 22:00 UTC, uc00ekun commented
@LysanderBenke Danke für dein Review! Ich hätte nur eine Frage bezüglich der Wortanzahl: Die erste Abbildung hatte ich ja selbst erstellt und hatte die Wortanzahl davon mitreingezählt. Zählen die dann nicht mit rein?

2021-12-06 22:03 UTC, LysanderBenke commented
@uc00ekun Ich hatte sie nicht mit dazu gezählt, denke aber schon dass sie dazu gehören. Also passt die Wortanzahl denke ich.

2021-12-06 22:09 UTC, uc00ekun commented
@CatrinSc Danke für dein Review! Ich hätte nur noch kleine Anmerkungen/Fragen: 
1) Ich hatte mich extra auf die Projekt-Roadmap bezogen, da das Modul ja auch vom Projektmanagement handelt. Ist es da dann wirklich nötig, noch beispielsweise die Technologie Roadmap mitreinzunehmen? Ich finde fast, das würde den Rahmen sprengen, oder was meinst du? 
2) Die kleineren Überschriften hatte ich mit Absicht eingebaut, da ich in Bezug auf meine 1. Abbildung die verschiedenen Schritte darstellen wollte, wie man eine Projekt-Roadmap erstellt. Ich hatte es so im Kopf, dass man zu Abbildungen stets Bezug nehmen muss und diese im Text nochmals erklären und näher darauf eingehen soll. Du meintest jetzt, ich solle Teile weglassen, aber dann würden ja Schritte in der Erstellung fehlen - hast du da vielleicht noch einen Tipp für mich, wie ich das besser lösen könnte? Das wäre echt super hilfreich! :)

2021-12-06 22:11 UTC, uc00ekun commented
@LysanderBenke ah okay super danke dir für die schnelle Antwort! Ich kann ja auch morgen in der Vorlesung nochmal nachfragen, dann haben wir eine sichere Antwort.

2021-12-07 11:53 UTC, AmrouHasan requested changes
| Kriterium | Bewertung|
|-----|---|
| Front-Matter | ja |
| Umfang | ja |
| Belege | ja |
| Links | ja |
| Formatierung | ja |
| Verlinkungen vorhanden | ja |
| Abbildungen | ja |
| Strukturierung des Beitrags | 9 |
| Rechtschreibung | 9 |
| Sprache | 10 |
| Inhalt | 10 |
| Einordnung in den Kontext | 10 |
| Ansprechend für Zielgruppe | 10 |

# Zusammenfassung

Der Artikel behandelt das Thema "Roadmap". Dabei handelt es sich um einen generellen Plan, der im Projektmanagement als Planungswerkzeug dient. Zunächst findet man die Kategorisierung in 4 Arten der Roadmap vor. Als nächstes wird die Unterscheidung zur Roadmap im Projektmanagement gezogen. Anschließend findet man die Erklärung des Prozess für die Erstellung einer Roadmap, das sogenannte "Roadmapping" vor. Die 5  Schritte des "Roadmappings" werden im Folgenden erneut erläutert. Abschließend wird das Thema nochmal durch eine visualisierte Darstellung verdeutlicht.

# Positive Aspekte

Der Frontmatter wurde bearbeitet. 
Der Umfang ist optimal.
Jeder größere Absatz ist passenderweise mit einem Beleg ausgestattet. Außerdem gefällt mir die Formatierung der Quellen sehr.
Alle Links funktionieren und wurden an richtiger Stelle eingesetzt.
Die Formatierung sowie die Strukturierung des Inhalts erschaffen ein schönes Gesamtbild des Artikel.
Die Verlinkungen zu anderen Themen sind passend gewählt.
Beide Abbildung sind passend gewählt und erfassen den Kern des Unterpunkts sehr gut.
Die Rechtschreibung ist beinahe perfekt. Die Sprache erwirkt einen sehr sachlichen Eindruck, aber ist trotzdem sehr angenehm zum Lesen. 
Auch der Inhalt wirkt vollständig, sodass man beim Lesen ein gutes Bild von Thema erhält. Außerdem versteht man, wo das Thema "Roadmapping" im Projektmanagement einzuordnen ist.

# Negative Aspekte

In Enzyklopädien sind häufig ein kleines Inhaltsverzeichnis vorhanden. Das würde sogar für noch mehr Strukturierung und Übersichtlichkeit sorgen. 
Es wurden bereits einige von den wenigen Rechtschreibfehlern angesprochen. Ich habe noch "In Folge dessen" bei "Identifizierung von Chancen und Risiken" gefunden, welches eigentlich "Infolgedessen" heißen müsste.

2021-12-07 13:18 UTC, CatrinSc commented
@uc00ekun gerne.
zu 1. nein, musst du nicht zwangsläufig. Ich persönlich hatte mich nur gefragt, ob es da ein Unterschied gäbe und wie der Aussehen würde. Des Weiteren könntest du dann 'sinnvoller' untergliedern in meinen Augen. 
zu 2. doch, du sollst auf jeden Fall Bezug zur Darstellung nehmen. Insofern musst du es auch nicht weglassen, aber ich würde die einzelnen Schritte nicht als Unterüberschift formatieren, sondern eher unter den Roadmapping Absatz als Aufzählung z.B.. Bei deinem Beispiel hast du ja auch Bezug auf die Grafik genommen ohne eine neue Überschrift anzulegen. Finde das daher etwas verwirrend.

2021-12-07 14:49 UTC, uc00ekun commented
@CatrinSc Alles klar, vielen Dank dir! Da werde ich bei der Überarbeitung aufjedenfall versuchen drauf einzugehen.

2021-12-09 19:40 UTC, merged