Forschungsprojekte
ManagingProjectsSuccessfully/ManagingProjectsSuccessfully.github.io pull request #230
Opened 2021-11-23 21:37 UTC by CatrinSc

2021-12-06 21:09 UTC, LysanderBenke requested changes
| Kriterium | Bewertung|
|-----|---|
| Front-Matter | ja |
| Umfang | ja|
| Belege | ja |
| Links | ja|
| Formatierung | ja|
| Verlinkungen vorhanden | ja |
| Abbildungen | ja |
| Strukturierung des Beitrags | 9 |
| Rechtschreibung | 9 |
| Sprache | 10 |
| Inhalt | 10|
| Einordnung in den Kontext | 10|
| Ansprechend für Zielgruppe | 10|

# Zusammenfassung

In dem Artikel geht es um Forschungsprojekte,  einmalig befristete Vorhaben. Zuerst werden typische Kriterien aufgezählt. Als zweites wird die Entwicklung eines Forschungsprojektes erläutert. Dauraufhin wird die Wichtigkeit des Projektmanagements in Forschungsprojekten verdeutlicht. Zuletzt wird der Unterschied von Forschungsprojekten in klassischen und agilen Projektmanagement genannt und ein Lösungsansatz geboten.

# Positive Aspekte

Alle geforderten Kriterien sind erfüllt. Der Artikel ist gut strukturiert und Inhaltlich für jeden verständlich. Die Sprache zeigt keine Fehler auf.

# Negative Aspekte

Strukturierung: 
"Aufgrund ihrer typischen Kriterien haben Forschungsprojekte ein hohes Risiko, nicht erfolgreich zu sein." Diesen Satz würde ich an das Ende der Zusammenfassung packen, da er mit dem Darauf folgenden Sätzen keinen Zusammenhang hat und nach der Zusammenfassung die typischen Kriterien genannt werden und er dann besser eingebettet wäre.
Die Überschrift "Forschungsprojekte im Projektmanagement" passt nicht zu 100 %, da eher die Wichtigkeit von Projektmanagement in Forschungsprojekten erklärt wird.
Rechtschreibung: 
bei "Forschungsprojekte entwickeln" und bei "Forschungsprojekte im Projektmanagement" sollte die Rechtschreibung von einzelnen Wörtern nochmal überarbeitet werden.

2021-12-07 21:46 UTC, AmrouHasan requested changes
| Kriterium | Bewertung|
|-----|---|
| Front-Matter | ja |
| Umfang | ja |
| Belege | ja |
| Links | ja |
| Formatierung | ja |
| Verlinkungen vorhanden | ja |
| Abbildungen | ja |
| Strukturierung des Beitrags | 9 |
| Rechtschreibung | 10 |
| Sprache | 10 |
| Inhalt | 10 |
| Einordnung in den Kontext | 10 |
| Ansprechend für Zielgruppe | 10 |

# Zusammenfassung

Der Artikel befasst sich mit Forschungsprojekten. Dabei handelt es sich um Projekte, die Erkenntnisgewinn in der Forschung erzielen. Zunächst werden einige typische Kriterien solcher Projekte aufgelistet. Als nächstes folgt die Erklärung des Ablaufs der Entwicklung einer Forschungsfrage, welche in einer Abbildung hinterlegt wird. Danach folgt die Abgrenzung der Forschungsprojekte zu denen aus dem Projektmanagement. Schließlich werden noch zwischen klassischen und agilen Forschungsprojekten unterschieden. Zuletzt werden noch Lösungsansätze wie beispielsweise mit Hilfe Microsoft PPM vorgestellt. Der Artikel wird abgerundet mit Verweisen auf aktuelle Forschungsprojekte.

# Positive Aspekte

Alle notwendigen Kriterien wurden optimal erfüllt. Der Artikel ist gut strukturiert und man erkennt direkt worum es sich handelt. Die Abbildungen sind passend gewählt und verdeutlichen den aktuell besprochenen Inhalt sehr gut. Die Belege sind passend gesetzt und mit guten Quellen hinterlegt. Auch inhaltlich wird das gesamte Thema behandelt und vermittelt einen guten Einblick in das Thema. Die Rechtschreibung und Wahl der Worte sind optimal gewählt.

# Negative Aspekte
Persönlich würde ich für noch mehr Strukturierung ein Inhaltsverzeichnis einfügen. 
Ich würde den Abschnitt „Forschungsprojekte entwickeln“ zu „Entwicklung der Forschungsprojekte“ abändern.
Außerdem fehlen noch interne Verlinkungen zu verwandten Themen über „thema.md“.

2021-12-08 12:57 UTC, JennyKonn requested changes
| Kriterium | Bewertung|
|-----|---|
| Front-Matter | ja |
| Umfang | ja|
| Belege | ja |
| Links | ja|
| Formatierung | ja|
| Verlinkungen vorhanden | ja |
| Abbildungen | ja |
| Strukturierung des Beitrags | 9 |
| Rechtschreibung | 10|
| Sprache | 10 |
| Inhalt | 9|
| Einordnung in den Kontext | 10|
| Ansprechend für Zielgruppe | 10|

# Zusammenfassung

Der Artikel informiert über die Kriterien sowie die Entwicklung von Forschungsprojekten. Es erfolgt eine Einordnung von Forschungsprojekten ins Projektmanagement. Hierbei wird sowohl auf klassische und agile Projekte eingegangen, als auch ein Lösungsansatz in Form des Microsoft PPM-Tools vorgestellt. Abschließend wird auf Beispiele zum Thema in Form von aktuellen Forschungsprojekten verwiesen. 

# Positive Aspekte

Hervorzuheben ist meiner Meinung nach der Verweis auf aktuelle Forschungsprojekte am Ende des Artikels. Dies lässt den interessierten Leser weiter in das Thema eintauchen und bereits theoretisch erklärte Aspekte in der Praxis erkennen. Rechtschreibung, Satzbau und Wortwahl sind gut. Das führt dazu, dass der Artikel einfach gelesen werden kann und der Inhalt im Vordergrund steht. Die gewählten Abbildungen sind passend und ergänzen den Text gut. Es wird auf passende angrenzende Themen in verschiedenen Formen verwiesen. 

# Negative Aspekte

Negativ fällt meiner Meinung nach das vergleichsweise umfangreiche Vorwort auf. Es würde sich anbieten die Informationen zu Beginn des Artikels entweder als extra Punkt mit Überschrift aufzuführen oder etwas zu kürzen. Das Vorwort sollte kurz und prägnant den Inhalt des Textes zusammenfassen und nicht direkt umfangreiche Informationen liefern. Der zweite Punkt der mir eher negativ auffällt,  ist die Gestaltung des Abschnittes "Typische Kriterien". Es handelt sich hierbei um eine Oberüberschrift und einige Aufzählungen. Diese sind inhaltlich aber ohne weitere Informationen schwer einzuordnen. (Tipp: Formatiere dein Vorwort als "Definition von Forschungsprojekten" o.ä. um und verwende die "Typische Kriterien von Forschungsprojekten"-Liste hierbei als Unterüberschrift. Dann versteht man den Zusammenhang dieser offenbar zusammengehörenden Punkte besser bzw. es macht deinen Artikel inhaltlich klarer nachvollziehbar durch die deutlichere Strukturierung).

2021-12-09 19:40 UTC, merged

2021-12-14 11:21 UTC, CatrinSc commented
@LysanderBenke Danke für deine Review. Den Satz an eine andere Stelle zu setzen, war eine gute Idee. Die Rechtschreibfehler kann ich allerdings nicht finden. Hast du ein Beispiel?
Des Weiteren habe ich 'Forschungsprojekte im Projektmanagement' gewählt, weil es ja eine Überüberschrift für die klassisch vs. agil und Lösungsansatz Themen sind. Macht es so gesehen mehr Sinn?

2021-12-14 11:34 UTC, LysanderBenke commented
@CatrinSc 
Die Fehler die ich noch gefunden habe sind:
 bei detaillierten fehlt ein l, ("Forschungsprojekte entwickeln")
bei Forschungsprojekt und Projektmanagement-Methode fehlt jeweils ein Buchstabe("Forschungsprojekte im Projektmanagement")
Als ÜberÜberschrift macht es mehr Sinn.

2021-12-14 12:06 UTC, CatrinSc commented
@LysanderBenke ahh vielen Dank! :) hab sie trotz 10 mal lesen einfach nicht gesehen.

2021-12-22 08:58 UTC, CatrinSc commented
@LysanderBenke, @JennyKonn, @AmrouHasan 
erstmal vielen Dank für eure Reviews.
Was ich berücksichtigt habe in meiner Überarbeitung:
1. Die Satzumstellung sowie die Tippfehler in den entsprechenden Abschnitten
2. Das umfangreiche Vorwort gekürzt und eine Überschrift eingefügt (Allgemeines) mit zugehöriger Unterüberschrift (typische Kriterien)
3.  Entwicklung von Forschungsprojekten statt Forschungsprojekte entwickeln sowie weitere Verlinkungen zu internen Beiträgen