Projektantrag
ManagingProjectsSuccessfully/ManagingProjectsSuccessfully.github.io pull request #233
Opened 2021-11-23 21:52 UTC by JennyKonn

2021-11-28 13:13 UTC, Meyu23 requested changes
| Kriterium | Bewertung|
|-----|---|
| Front-Matter | ja |
| Umfang | ja|
| Belege | ja |
| Links | ja|
| Formatierung | ja |
| Verlinkungen vorhanden | ja |
| Abbildungen | ja |
| Strukturierung des Beitrags | 10 |
| Rechtschreibung | 10 |
| Sprache | 9 |
| Inhalt | 10 |
| Einordnung in den Kontext | 10 |
| Ansprechend für Zielgruppe | 10 |

# Zusammenfassung

Der Artikel befasst sich mit dem Thema des Projektantrages. Es wird erläutert, was der Projektantrag beinhaltet und wieso dieser wichtig für ein erfolgreiches Projekt ist.

# Positive Aspekte

Das Thema wird zusammenhängend und gut strukturiert erläutert. Abbildungen, Verlinkungen und Formatierungen wurden korrekt umgesetzt.

# Negative Aspekte

Einige wenige Formulierungen sollten angepasst werden (Bsp: "Menschen haben oft das Bedürfnis haben schon mal anzufangen ohne dass eine konkrete Planung vorliegt.")

2021-12-05 20:21 UTC, BeratGuen requested changes
| Kriterium | Bewertung|
|-----|---|
| Front-Matter | ja |
| Umfang | ja |
| Belege | ja |
| Links | ja |
| Formatierung | ja |
| Verlinkungen vorhanden | ja |
| Abbildungen | ja |
| Strukturierung des Beitrags | 10 |
| Rechtschreibung | 10 |
| Sprache | 9 |
| Inhalt | 10 |
| Einordnung in den Kontext | 10 |
| Ansprechend für Zielgruppe | 10 |

# Zusammenfassung

Der zu bewertende Artikel handelt vom Projektantrag, einem Teil der Planungsphase und dem ersten wichtigen Schritt in Projekten. Angefangen mit der Definition und Einordnung ins Projekt wird schließlich der genaue Inhalt des Projektes beschrieben. Der Projektantragt hilft bei der Entscheidungsfindung des Auftraggebers, ist nicht allgemein vorgeschrieben und kann an individuelle Bedürfnisse angepasst werden. 


# Positive Aspekte
Der Beitrag beschreibt den Projektantrag ausführlich und logisch strukturiert. Es wurden alle Kriterien eingehalten und sinnvoll umgesetzt. Auf korrekte Rechtschreibung, Grammatik und inhaltliche Korrektheit wurde geachtet und die Formulierung ist weitestgehend im Enzyklopädiestil. Durch den reichlichen Bezug auf angrenzende Themengebiete wurde der Beitrag gut in den Kontext des Projektmanagements eingeordnet.

# Negative Aspekte

Im letzten Absatz wurde nicht auf den Enzyklopädiestil geachtet. 
Eventuell wäre eine Unterscheidung in der Angabe der Quellen im Text sinnvoll. Dazu z.B. die externen Quellen nur als Fußnoten und weitere Github Beiträge innerhalb des Textes als Link hinterlegen. Dies ist soweit mir bekannt keine Pflicht und hat somit keinen Einfluss in meiner Bewertung.
__

2021-12-05 21:16 UTC, ksushaW requested changes
| Kriterium | Bewertung|
|-----|---|
| Front-Matter | ja|
| Umfang | ja|
| Belege | ja|
| Links | ja|
| Formatierung | ja|
| Verlinkungen vorhanden | ja|
| Abbildungen | ja|
| Strukturierung des Beitrags | 10 |
| Rechtschreibung | 10|
| Sprache | 10 |
| Inhalt | 10|
| Einordnung in den Kontext | 10|
| Ansprechend für Zielgruppe | 10|

# Zusammenfassung

In dem Beitrag geht es um grundlegende Informationen - wie im Haupttitel erkennbar ist - zum Projektantrag. Der Text beginnt mit einer Definition, welche erläutert um welche Art von Dokument es sich handelt. Anschließend wird aufgezeigt, dass man den Projektantrag für verschiedene Projekt-Arten sinnvoll einsetzen kann. Zudem werden in dem Beitrag auf den Aufbau & Inhalt des Projektantrages eigegangen. Abschließend wird auf den Nutzen des Dokuments eingegangen.

# Positive Aspekte

Der Text ist insgesamt gut strukturiert. Die verschiedenen Absätze des Beitrages werden mit passenden Titeln versehen. Die Formulierungen sind sachlich und verständlich geschrieben. Positiv ist auch, dass eine Abbildung zu sehen ist, sodass dem Leser das Thema sehr anschaulich dargeboten wird. Inhaltlich werden in dem Text wirklich nur die Punkte erläutert wie sie in den Titeln zu entnehmen sind. Der Beitrag konzentriert sich auf das  Wesentliche & es werden keine unnötigen nebensächlichen Aspekte aufgeführt. Ein weiterer positiver Aspekt ist, dass im Abschnitt "Nutzen" zusätzlich auf ein Zitat Stellung genommen wird, um die Wichtigkeit des Projektantrags zu verdeutlichen.

# Negative Aspekte

Insgesamt gibt es eigentlich nichts zu beanstanden. Es wäre ggf. ein kleines "Vorwort" wünschenswert.

2021-12-08 08:11 UTC, CatrinSc commented
@JennyKonn 
Hey, wusste nicht, wie ich dich am besten erreichen kann, aber mir fehlt von dir noch eine Review.

2021-12-08 13:01 UTC, JennyKonn commented
> @JennyKonn Hey, wusste nicht, wie ich dich am besten erreichen kann, aber mir fehlt von dir noch eine Review.

Ist erledigt. @CatrinSc

2021-12-09 19:40 UTC, merged