Ausgangsanalyse.md
ManagingProjectsSuccessfully/ManagingProjectsSuccessfully.github.io pull request #234
Opened 2021-11-23 22:06 UTC by ksushaW

2021-12-03 13:34 UTC, Ne88peni requested changes
| Kriterium | Bewertung|
|-----|---|
| Front-Matter | ja |
| Umfang | ja |
| Belege | ja |
| Links | ja |
| Formatierung | ja |
| Verlinkungen vorhanden | nein |
| Abbildungen | nein |
| Strukturierung des Beitrags | 10 |
| Rechtschreibung | 10 |
| Sprache | 10 |
| Inhalt | 8 |
| Einordnung in den Kontext | 9 |
| Ansprechend für Zielgruppe | 9 |

# Zusammenfassung

Der Artikel gibt einen guten Überblick über das Thema "Ausgangsanalyse". Er geht auf die verschiedenen Faktoren ein, die anhand einer Umfeldanalyse ermittelt werden. Dazu beschreibt er verständlich die Ausgangsanalyse als Basis für Stakeholder- und Risikoanalyse.


# Positive Aspekte

* Der Artikel ist gut strukturiert und ausführlich.
* Die Vorgabe von +/- 500 Wörtern wurde perfekt eingehalten im Rahmen der 10% Abweichung.

# Negative Aspekte

* Verlinkungen und Abbildungen fehlen. Das macht den Artikel ein bisschen trocken.
* Weiterführende Literatur fehlt.

2021-12-05 15:41 UTC, Meyu23 commented
| Kriterium | Bewertung|
|-----|---|
| Front-Matter | ja |
| Umfang | ja|
| Belege | ja |
| Links | ja |
| Formatierung | ja |
| Verlinkungen vorhanden | nein |
| Abbildungen | nein |
| Strukturierung des Beitrags | 10 |
| Rechtschreibung | 10 |
| Sprache | 10 |
| Inhalt | 9 |
| Einordnung in den Kontext | 8 |
| Ansprechend für Zielgruppe | 9 |

# Zusammenfassung

Der Artikel gibt einen strukturierten Überblick über das Thema "Ausgangsanalyse". Verschiedene Unternehmensumfeldfakoren werden näher erklärt. Anschließend wird verständlich und zusammenhängend erklärt wie diese Informationen, welche aus der Ausgangsanalyse stammen für weitere Analysen, wie z.B. die Stakeholder- oder Risikoanalyse, verwendet werden können.

# Positive Aspekte

Das Thema wird ausführlich, zusammenhängend und gut strukturiert erläutert. Die verwendete Sprache ist sachlich und nüchtern. Die Länge des Beitrages stimmt mit den Vorgaben überein.

# Negative Aspekte

Der Beitrag könnte etwas anschaulicher gestaltet werden durch die Ergänzung von  Abbildungen oder Tabellen. Außerdem fehlen die Verlinkungen zu anderen MPS-Themen, sodass die Zuordnung in den Gesamtkontext nicht ganz ausgearbeitet ist.

2021-12-05 15:45 UTC, Meyu23 requested changes
| Kriterium | Bewertung|
|-----|---|
| Front-Matter | ja |
| Umfang | ja|
| Belege | ja |
| Links | ja |
| Formatierung | ja |
| Verlinkungen vorhanden | nein |
| Abbildungen | nein |
| Strukturierung des Beitrags | 10 |
| Rechtschreibung | 10 |
| Sprache | 10 |
| Inhalt | 9 |
| Einordnung in den Kontext | 8 |
| Ansprechend für Zielgruppe | 9 |

# Zusammenfassung

Der Artikel gibt einen strukturierten Überblick über das Thema "Ausgangsanalyse". Verschiedene Unternehmensumfeldfakoren werden näher erklärt. Anschließend wird verständlich und zusammenhängend erklärt wie diese Informationen, welche aus der Ausgangsanalyse stammen für weitere Analysen, wie z.B. die Stakeholder- oder Risikoanalyse, verwendet werden können.

# Positive Aspekte

Das Thema wird ausführlich, zusammenhängend und gut strukturiert erläutert. Die verwendete Sprache ist sachlich und nüchtern. Die Länge des Beitrages stimmt mit den Vorgaben überein.

# Negative Aspekte

Der Beitrag könnte etwas anschaulicher gestaltet werden durch die Ergänzung von  Abbildungen oder Tabellen. Außerdem fehlen die Verlinkungen zu anderen MPS-Themen, sodass die Zuordnung in den Gesamtkontext nicht ganz ausgearbeitet ist.

2021-12-07 14:38 UTC, BeratGuen requested changes
| Kriterium | Bewertung|
|-----|---|
| Front-Matter | ja |
| Umfang | ja |
| Belege | ja |
| Links | ja |
| Formatierung | ja |
| Verlinkungen vorhanden | nein |
| Abbildungen | nein |
| Strukturierung des Beitrags | 9 |
| Rechtschreibung | 10 |
| Sprache | 10 |
| Inhalt | 9 |
| Einordnung in den Kontext | 8 |
| Ansprechend für Zielgruppe | 8 |

# Zusammenfassung
Der Beitrag stellt die Bedeutung des Spezialistenteams in Bezug auf das klassische Projektmanagement dar. Es besteht aus Mitgliedern mit hohen Fachkompetenzen, die vom Projektmanager in das Team einberufen werden. Zusammen mit den weiteren beteiligten Mitgliedern des Projektes bildet sich das Spitzenteam, welches durch die im Beitrag genannten sieben Faktoren charakterisiert wird. 


# Positive Aspekte
Der Beitrag ist inhaltlich und sprachlich korrekt verfasst und strukturiert gestaltet. Dabei wurde auf korrekte Rechtschreibung, Grammatik, Formatierung und sachliche Wortwahl im Sinne des Enzyklopädiestils, sowie auf durchgängigen Quellenbezug geachtet. Die einführende Definition bietet eine erste Einordnung in den Kontext.

# Negative Aspekte
Durch die Verwendung einer Abbildung, sowie Verlinkung zu weiteren Github Beiträgen, können die vorgegebenen Kriterien erfüllt werden. 
Zusätzlich könnte der Aufgabenbereich des Spezialistenteams im Projekt näher erläutert werden, sowie ein Bezug zwischen den genannten Faktoren und den Einfluss des Spezialistenteams auf diese, hergestellt werden.

2021-12-08 16:09 UTC, Meyu23 requested changes
| Kriterium | Bewertung|
|-----|---|
| Front-Matter | ja |
| Umfang | ja|
| Belege | ja |
| Links | ja |
| Formatierung | ja |
| Verlinkungen vorhanden | nein |
| Abbildungen | nein |
| Strukturierung des Beitrags | 10 |
| Rechtschreibung | 10 |
| Sprache | 10 |
| Inhalt | 9 |
| Einordnung in den Kontext | 8 |
| Ansprechend für Zielgruppe | 9 |

# Zusammenfassung

In dem Beitrag wird die Bedeutung und Merkmale von Spezialistenteams erläutert. Es handelt sich um eine Gruppe von Fachexperten, welche benötigtes Fachwissen für die Projekte mitbringen. Insgesamt bilden die Mitglieder eines solchen Teams das Spitzenteam. Dieses wird in die verschiedenen Merkmale aufgeteilt und erklärt. Schließlich wird am Ende des Artikels eine kurze schlüssige Zusammenfassung gegeben.

# Positive Aspekte

Das Thema wird ausführlich, zusammenhängend und gut strukturiert erläutert. Der Beitrag verwendet sachliche Sprache und korrekte Rechtschreibung. Die Länge des Beitrages stimmt mit den Vorgaben überein. Die einführende Definition des Themas ist sehr gut.

# Negative Aspekte

Der Beitrag könnte etwas anschaulicher gestaltet werden durch die Ergänzung von  Abbildungen oder Tabellen. Außerdem fehlen die Verlinkungen zu anderen MPS-Themen, sodass die Zuordnung in den Gesamtkontext nicht ganz ausgearbeitet ist. Zwei Quellen sind vielleicht ein bisschen zu wenig, da auch auf keine weiterführende Literatur verwiesen wurde.

2021-12-09 19:40 UTC, merged