Microsoft_Planner_PM_Tool & SAFe_Lean_Agile_Mindset
ManagingProjectsSuccessfully/ManagingProjectsSuccessfully.github.io pull request #235
Opened 2021-11-23 22:34 UTC by BeratGuen

2021-12-03 12:57 UTC, Ne88peni requested changes
| Kriterium | Bewertung|
|-----|---|
| Front-Matter | ja |
| Umfang | ja |
| Belege | ja |
| Links | ja |
| Formatierung | ja |
| Verlinkungen vorhanden | ja |
| Abbildungen | ja |
| Strukturierung des Beitrags | 10 |
| Rechtschreibung | 10 |
| Sprache | 10 |
| Inhalt | 9 |
| Einordnung in den Kontext | 10 |
| Ansprechend für Zielgruppe | 10 |

# Zusammenfassung

Der Artikel gibt einen guten Überblick über Microsoft Planner. Er beschreibt die Oberfläsche und erklärt die Funktionen von Microsoft Planner. Dazu vergleicht er den Microsoft Planner zu MS To Do und MS Project.

# Positive Aspekte

* Der ganze Artikel wurde auf den Punkt gebracht und ist für den Leser verständlich.
* Die Sprache ist sehr sachlich.

# Negative Aspekte

* Ich würde Wikipedia nicht als Quelle nehmen.
* Bei "Oberfläsche und Funktionen" würde ich das anders machen, z.B: oberhalb jedes Bildes würde ich schreiben, welche Fläsche das ist.

* Zum Schluss würde ich ein Fazit oder eine kurze Zusammenfassung schreiben.

2021-12-07 16:46 UTC, christian-anghel requested changes
| Kriterium | Bewertung|
|-----|---|
| Front-Matter | ja |
| Umfang | ja |
| Belege | ja |
| Links | ja |
| Formatierung | ja |
| Verlinkungen vorhanden | ja |
| Abbildungen | ja |
| Strukturierung des Beitrags | 10 |
| Rechtschreibung | 9 |
| Sprache | 9 |
| Inhalt | 10 |
| Einordnung in den Kontext | 10 |
| Ansprechend für Zielgruppe | 10 |

# Zusammenfassung

Der Artikel befasst sich mit dem Projektmanagement Tool Microsoft Projects. Dabei wird nach einer kurzen Einleitung mit generellen Informationen die Funktion anhand von Bildern aus dem Programm beschrieben und dann noch ein Vergleich zu den anderen Programmen für Projektmanagement von Microsoft gegeben.

# Positive Aspekte

Der Artikel ist gut strukturiert und fokussiert sich auf die Funktionen des Programms. Besonders gut finde ich die selbst erstellten Bilder zur Veranschaulichung der Oberfläche. Außerdem wird duch den Vergleich mit anderen Programmen auch noch ein sehr guter Kontext zu anderen Themengebieten gegeben.

# Negative Aspekte

Vereinzelt sind noch Rechtschreibfehler da. Die Tabelle ist beim ersten mal lesen etwas unübersichtlich, und - dadurch, dass es keine kompletten Sätze sind - nicht sofort durchschaubar was gemeint ist.

2021-12-08 16:30 UTC, Meyu23 requested changes
| Kriterium | Bewertung|
|-----|---|
| Front-Matter | ja |
| Umfang | ja|
| Belege | ja |
| Links | ja |
| Formatierung | ja |
| Verlinkungen vorhanden | ja |
| Abbildungen | ja |
| Strukturierung des Beitrags | 10 |
| Rechtschreibung | 10 |
| Sprache | 10 |
| Inhalt | 10 |
| Einordnung in den Kontext | 10 |
| Ansprechend für Zielgruppe | 10 |

# Zusammenfassung

Der Artikel handelt von dem Projektmanagement Tool Microsoft Projects. Zuerst werden allgemeine Informationen für einen generellen Überblick gegeben. Anschließend werden mithilfe von vielen Screenshots die Funktionen des Programmes aufgezeigt. Zum Schluss wird das Programm noch mit einem anderen Projektmanagement Programm von Microsoft verglichen.

# Positive Aspekte

Das Thema wird ausführlich, zusammenhängend und gut strukturiert erläutert. Der Beitrag verwendet sachliche Sprache und korrekte Rechtschreibung. Die Länge des Beitrages stimmt mit den Vorgaben überein. Der Artikel ist durch die vielen Abbildungen sehr übersichtlich und leicht zu verstehen. Das Inhaltsverzeichnis am Anfang bietet noch mehr Übersichtlichkeit, was in dem Beitrag erläutert wird. Es wird auf einige andere Beiträge verwiesen.

# Negative Aspekte
nichts

2021-12-08 22:45 UTC, Meyu23 requested changes
| Kriterium | Bewertung|
|-----|---|
| Front-Matter | ja |
| Umfang | ja|
| Belege | ja |
| Links | ja |
| Formatierung | ja |
| Verlinkungen vorhanden | ja |
| Abbildungen | ja |
| Strukturierung des Beitrags | 10 |
| Rechtschreibung | 10 |
| Sprache | 9 |
| Inhalt | 10 |
| Einordnung in den Kontext | 10 |
| Ansprechend für Zielgruppe | 10 |

# Zusammenfassung

Der Artikel gibt einen strukturierten Überblick zum Thema Lean Agile Mindset. Zuerst wird das Thema durch ein Zitat definiert und anschließend mithilfe einer Abbildung in vier verschiedene Unterpunkte unterteilt. Zum Schluss wird erklärt in wieweit die Unterpunkte wichtig für Führungskräfte sind.

# Positive Aspekte

Das Thema wird ausführlich, zusammenhängend und gut strukturiert erläutert. Der Beitrag verwendet sachliche Sprache und korrekte Rechtschreibung. Die Länge des Beitrages stimmt mit den Vorgaben überein. Der Artikel ist durch die Abbildung und auch Verwendung von Auflistungen sehr übersichtlich und leicht zu lesen. Das Inhaltsverzeichnis am Anfang bietet noch mehr Übersichtlichkeit. Es wird auf einige andere Beiträge verwiesen.

# Negative Aspekte
An ein paar Stellen sollte die Grammatik überprüft werden. Bei der englischen Definition am Anfang fehlen noch die Anführungszeichen, da es sich um ein Zitat handelt. Die Quellen 1 und 2 sind der gleiche Link.

2021-12-09 19:40 UTC, merged

2021-12-21 16:29 UTC, BeratGuen commented
@Ne88peni 
> Kriterium	Bewertung
> Front-Matter	ja
> Umfang	ja
> Belege	ja
> Links	ja
> Formatierung	ja
> Verlinkungen vorhanden	ja
> Abbildungen	ja
> Strukturierung des Beitrags	10
> Rechtschreibung	10
> Sprache	10
> Inhalt	9
> Einordnung in den Kontext	10
> Ansprechend für Zielgruppe	10
> # Zusammenfassung
> Der Artikel gibt einen guten Überblick über Microsoft Planner. Er beschreibt die Oberfläsche und erklärt die Funktionen von Microsoft Planner. Dazu vergleicht er den Microsoft Planner zu MS To Do und MS Project.
> 
> # Positive Aspekte
> * Der ganze Artikel wurde auf den Punkt gebracht und ist für den Leser verständlich.
> * Die Sprache ist sehr sachlich.
> 
> # Negative Aspekte
> * Ich würde Wikipedia nicht als Quelle nehmen.
> * Bei "Oberfläsche und Funktionen" würde ich das anders machen, z.B: oberhalb jedes Bildes würde ich schreiben, welche Fläsche das ist.
> * Zum Schluss würde ich ein Fazit oder eine kurze Zusammenfassung schreiben.


Hi,

erstmal vielen Dank für dein positives Feedback.
Bevor der Beitrag in die zweite Review Phase geht würde ich noch gerne auf die von dir genannten negativen Aspekte eingehen:

- In der zweiten Session vom 02.11.2021 ab 1h 43min wird von Martin erwähnt, dass Wikipedia Artikel als Quellen zugelassen sind. Daher habe ich hier keine Änderungen vorgenommen. 

- Bei der Tabelle sehe ich es wie du und habe hier nochmal Änderungen vorgenommen. Darunter auch zu jeder Abbildung eine Überschrift hinzugefügt, um zu verdeutlichen auf welche Oberfläche hier eingegangen wird.

- Ein Fazit oder eine Zusammenfassung habe ich bereits anfangs weggelassen, da wir im Wikipedia-Stil bzw. Enzyklopädie -Stil und nüchtern schreiben sollen.

2021-12-21 20:19 UTC, BeratGuen commented
@Meyu23 

> Kriterium	Bewertung
> Front-Matter	ja
> Umfang	ja
> Belege	ja
> Links	ja
> Formatierung	ja
> Verlinkungen vorhanden	ja
> Abbildungen	ja
> Strukturierung des Beitrags	10
> Rechtschreibung	10
> Sprache	9
> Inhalt	10
> Einordnung in den Kontext	10
> Ansprechend für Zielgruppe	10
> # Zusammenfassung
> Der Artikel gibt einen strukturierten Überblick zum Thema Lean Agile Mindset. Zuerst wird das Thema durch ein Zitat definiert und anschließend mithilfe einer Abbildung in vier verschiedene Unterpunkte unterteilt. Zum Schluss wird erklärt in wieweit die Unterpunkte wichtig für Führungskräfte sind.
> 
> # Positive Aspekte
> Das Thema wird ausführlich, zusammenhängend und gut strukturiert erläutert. Der Beitrag verwendet sachliche Sprache und korrekte Rechtschreibung. Die Länge des Beitrages stimmt mit den Vorgaben überein. Der Artikel ist durch die Abbildung und auch Verwendung von Auflistungen sehr übersichtlich und leicht zu lesen. Das Inhaltsverzeichnis am Anfang bietet noch mehr Übersichtlichkeit. Es wird auf einige andere Beiträge verwiesen.
> 
> # Negative Aspekte
> An ein paar Stellen sollte die Grammatik überprüft werden. Bei der englischen Definition am Anfang fehlen noch die Anführungszeichen, da es sich um ein Zitat handelt. Die Quellen 1 und 2 sind der gleiche Link.

Hi,

vielen Dank für dein positives Feedback.
Bevor der Beitrag in die zweite Review Phase geht würde ich noch gerne auf die von dir genannten negativen Aspekte eingehen:

- Ich hoffe ich habe alle Grammatikfehler entfernen können.
- Die Anführungszeichen habe ich ergänzt.
- Die Quellen habe ich etwas geändert, sodass die zweite Quelle nun stimmen sollte. Um auf weiteres Feedback einzugehen habe ich mich noch auf zwei weitere bezogen.

2021-12-21 21:40 UTC, BeratGuen commented
@christian-anghel 
> Microsoft_Planner_PM_Tool:
> 
> Kriterium	Bewertung
> Front-Matter	ja
> Umfang	ja
> Belege	ja
> Links	ja
> Formatierung	ja
> Verlinkungen vorhanden	ja
> Abbildungen	ja
> Strukturierung des Beitrags	10
> Rechtschreibung	9
> Sprache	9
> Inhalt	10
> Einordnung in den Kontext	10
> Ansprechend für Zielgruppe	10
> # Zusammenfassung
> Der Artikel befasst sich mit dem Projektmanagement Tool Microsoft Projects. Dabei wird nach einer kurzen Einleitung mit generellen Informationen die Funktion anhand von Bildern aus dem Programm beschrieben und dann noch ein Vergleich zu den anderen Programmen für Projektmanagement von Microsoft gegeben.
> 
> # Positive Aspekte
> Der Artikel ist gut strukturiert und fokussiert sich auf die Funktionen des Programms. Besonders gut finde ich die selbst erstellten Bilder zur Veranschaulichung der Oberfläche. Außerdem wird duch den Vergleich mit anderen Programmen auch noch ein sehr guter Kontext zu anderen Themengebieten gegeben.
> 
> # Negative Aspekte
> Vereinzelt sind noch Rechtschreibfehler da. Die Tabelle ist beim ersten mal lesen etwas unübersichtlich, und - dadurch, dass es keine kompletten Sätze sind - nicht sofort durchschaubar was gemeint ist.
> 
> SAFe_Lean_Agile_mindset
> 
> Kriterium	Bewertung
> Front-Matter	ja
> Umfang	ja
> Belege	ja
> Links	ja
> Formatierung	ja
> Verlinkungen vorhanden	ja
> Abbildungen	ja
> Strukturierung des Beitrags	9
> Rechtschreibung	10
> Sprache	8
> Inhalt	10
> Einordnung in den Kontext	10
> Ansprechend für Zielgruppe	10
> # Zusammenfassung
> Der Artikel gibt einen Überblick über Das Lean-Agile-Mindset. Zuerst mit einer Definition und dann wird im Detail das SAFe House of Lean angeschaut
> 
> # Positive Aspekte
> Der Artikel ist gut strukturiert, die Abbildung ist gut gewählt, aussagekräftig und wird dann noch ausführlich erklärt.
> 
> # Negative Aspekte
> 2 Quellen erscheinen etwas wenig für so ein komplexes Thema, auch wirkt die Sprache stellenweise zu kompliziert (zb Definition), kann aber auch am komplexen Thema liegen, bei dem Fachbegriffe unvermeidbar sind. Der Anfang sollte nicht auf englisch sein und dann nochmal auf deutsch übersetzt werden. Eins davon sollte reichen (deutsch, wenn es nicht ein direktes Zitat ist).

Hi,

vielen Dank für dein positives Feedback.
Bevor der Beitrag in die zweite Review Phase geht würde ich noch gerne auf die von dir genannten negativen Aspekte eingehen:


Microsoft Planner:

- Ich habe einige Rechtschreibfehler verbessert
- Bei der Tabelle gebe ich dir Recht. Leider konnte ich diese mit Markdown nicht so umsetzen wie gewünscht. Im ersten Entwurf sollte dieser Abschnitt im Fließtext erklärt werden, aufgrund der Wortanzahl (ca. 900 Wörter), habe ich mich für das Tabellenformat entschieden. Ziel war es mit Hilfe der Abbildungen und den kurzen Stichpunkten die Hauptfunktionen  kurz und knapp zu erklären. Daher habe ich hier einige Formatänderungen zur besseren Lesbarkeit umgesetzt und einige Stichpunkte umformuliert.


Lean Agile Mindset:

- Zu den Quellen habe ich weitere ergänzt. 
- Einige Stellen habe ich zum besseren Verständnis umformuliert.
- Das Thema ist durchaus etwas Komplex. Teilweise ist es etwas schwierig das ganze Sinngemäß wiederzugeben und deshalb die Fachbegriffe. Durch Verlinkung zu den weiteren Beiträgen des Scaled Agile Frameworks sollte das Thema etwas greifbarer werden, jedoch ist mir aufgefallen, dass diese Beiträge nicht bearbeitet wurden. Durch die weiterführende Literatur und die zusätzliche Quelle hoffe ich, dass der Beitrag nun etwas verständlicher geworden ist.