(1)Who is Who_Projektmanagement/ (2)Resource Leveling
ManagingProjectsSuccessfully/ManagingProjectsSuccessfully.github.io pull request #238
Opened 2021-11-23 23:26 UTC by Ne88peni

2021-12-07 18:39 UTC, christian-anghel requested changes
# Resource Leveling:

| Kriterium | Bewertung|
|-----|---|
| Front-Matter | ja |
| Umfang | nein |
| Belege | ja |
| Links | ja |
| Formatierung | ja |
| Verlinkungen vorhanden | nein |
| Abbildungen | ja |
| Strukturierung des Beitrags | 10 |
| Rechtschreibung | 10 |
| Sprache | 10 |
| Inhalt | 8 |
| Einordnung in den Kontext | 9 |
| Ansprechend für Zielgruppe | 10 |

# Zusammenfassung

Man bekommt hier einen ausführlichen Artikel über das Resource Leveling, in dem die Definition, der Einsatz und die verschiedenen Techniken des Resource Leveling aufgezeigt werden

# Positive Aspekte
Der Artikel geht sehr ins Detail und man bekommt einen großen Überblick, ist sehr gut strukturiert und aud einem sprachlich hohen Niveau ohne zu kompliziert zu sein.

# Negative Aspekte

Der Artikel ist viel zu lang für die Vorgabe (Fazit wirklich nötig?), auch sind keine Verlinkungen zu anderen ähnlichen Themen da (nur externe Links, aber andere GitHub Artikel aus unserem Kurs auch wichtig). Der Artikel wiederholt sich auch inhaltlich mehrmals (zb vor der Definition und dann Definition)

---

# Who is Who Projektmanagement

| Kriterium | Bewertung|
|-----|---|
| Front-Matter | ja |
| Umfang | nein |
| Belege | ja |
| Links | ja |
| Formatierung | ja |
| Verlinkungen vorhanden | nein |
| Abbildungen | nein |
| Strukturierung des Beitrags | 10 |
| Rechtschreibung | 10 |
| Sprache | 10 |
| Inhalt | 10 |
| Einordnung in den Kontext | 9 |
| Ansprechend für Zielgruppe | 10 |

# Zusammenfassung

Der Artikel stellt die verschiedenen Personen die am Projektmanagement beteiligt sind, welche Rollen es gibt und wie diese verteilt werden.

# Positive Aspekte
Es ist sehr einfach und angenehm zu lesen, sehr gut strukturiert und auch inhaltlich hat man nach dem lesen das Gefühl einen guten Überblick über das Thema zu haben.

# Negative Aspekte

Der Artikel ist zu lang für die Vorgabe, auch sind wieder keine Verlinkungen zu anderen ähnlichen Themen da. Eine Abbildung fehlt ebenfalls.

2021-12-08 00:09 UTC, mirela08 requested changes
# RESOURCE LEVELING: 

| Kriterium | Bewertung|
|-----|---|
| Front-Matter | ja |
| Umfang | ja |
| Belege | ja |
| Links | ja |
| Formatierung | ja |
| Verlinkungen vorhanden | nein |
| Abbildungen | ja |
| Strukturierung des Beitrags | 9 |
| Rechtschreibung | 10 |
| Sprache | 10 |
| Inhalt | 9 |
| Einordnung in den Kontext |10 |
| Ansprechend für Zielgruppe | 10 |

# Zusammenfassung

Der Artikel beschreibt das Thema Resource Leveling sehr definiert, indem auf die Definition, den Einsatz und die verschiedenen Techniken, wie das Crashing oder das Fast Tracking, eingegangen wird. 

# Positive Aspekte
Ich finde gut, dass sehr viel Mühe in den Artikel gesteckt wurde. Es wurden viele Aspekte und Schlüsselbegriffe thematisiert, was den Artikel natürlich länger machen.
Die Abbildung passt gut in den Kontext und man merkt, dass der Verfasser sich ordentlich mit dem Thema verfasst hat. Die Links funktionieren einwandfrei. Erwähnenswert ist auch die Strukturierung des Artikels, welche mir gefällt.

# Negative Aspekte

Es fehlt leider die Quelle der Abbildung. Man hätte Schlüsselbegriffe **hervorheben** können um den Artikel leserlicher zu machen. Auch wären Verlinkungen zu anderen GitHub Themen super gewesen. Man hätte den Artikel an manchen Passagen kürzen können.



# Who is Who Projectmanagement:

| Kriterium | Bewertung|
|-----|---|
| Front-Matter | ja |
| Umfang | ja |
| Belege | ja |
| Links | ja |
| Formatierung | ja |
| Verlinkungen vorhanden | nein |
| Abbildungen | nein |
| Strukturierung des Beitrags | 8 |
| Rechtschreibung | 10 |
| Sprache | 9 |
| Inhalt | 10|
| Einordnung in den Kontext | 10|
| Ansprechend für Zielgruppe | 10|

# Zusammenfassung

Der Artikel befasst sich vor allem mit den verschiedenen Rollen in einem Projekt, deren Findung und der Rollenbeschreibung. Die typischen Projektrollen werden durch Unterpunkte aufgeschlüsselt und der Vorgang der Rollenfindung wird auch thematisiert.

# Positive Aspekte

Der Artikel ist Inhaltlich sehr umfangreich und informativ. Für den Leser ist er verständlich und einfach zu lesen. Es werden alle relevanten Punkte aufgegriffen, um das Thema zu verstehen. Man merkt, dass der Verfasser viel Zeit in Recherche investiert hat. Schlüsselbegriffe wurden schön hervorgehoben und die Tabelle ist gut gestaltet worden. Die Links funktionieren auch einwandfrei.

# Negative Aspekte

Es fehlt leider eine Abbildung, welche das Thema noch anschaulicher machen würden. Auch hätte man auf angrenzende GitHub Themen verlinken können, statt den Wikipeda Artikeln. Um den Artikel kompakter zu machen, könnte man sich etwas kürzer halten. (Beim Thema Beteiligte und Projektrollen).

2021-12-08 20:48 UTC, Teemoma requested changes
**Ressource_Leveling**
| Kriterium | Bewertung|
|-----|---|
| Front-Matter | ja |
| Umfang | ja|
| Belege | ja|
| Links | ja|
| Formatierung | ja|
| Verlinkungen vorhanden |  nein |
| Abbildungen | ja|
| Strukturierung des Beitrags | 8|
| Rechtschreibung | 9|
| Sprache | 9|
| Inhalt | 9|
| Einordnung in den Kontext | 9|
| Ansprechend für Zielgruppe | 9|

# Zusammenfassung

Dieser Artikel beschreibt die Definition von Ressourcen leveling , Einsatz und Technik.  Beschreibt gleichzeitig vier Gründe für die Gleichheit der Ressourcen.


# Positive Aspekte

Der Artikel ist übersichtlich aufgebaut, bietet dem Leser eine ausführliche Einführung in die Ressourcen leveling und die Wortzahl ist angemessen.


# Negative Aspekte

Es gibt keinen Verlinkung zu diesem Artikel.Ich denke, die Definition ist etwas zu lang und enthält einige irrelevante Inhalte.

** Who is Who Projectmanagement**
| Kriterium | Bewertung|
|-----|---|
| Front-Matter | ja |
| Umfang | ja|
| Belege | ja|
| Links | ja|
| Formatierung | ja|
| Verlinkungen vorhanden | nein |
| Abbildungen | nein |
| Strukturierung des Beitrags | 9|
| Rechtschreibung | 9|
| Sprache | 10 |
| Inhalt | 9|
| Einordnung in den Kontext | 10|
| Ansprechend für Zielgruppe | 9|

# Zusammenfassung

Dieser Artikel beschreibt das Projektmanagement verschiedener Personen und ihre unterschiedlichen Rollen.

# Positive Aspekte

Der Artikel ist klar und umfassend. Die Sprache ist sehr professionell und detailliert. Und Angemessene Anzahl von Zitierung.

# Negative Aspekte

Mangel an geeigneten Diagrammen und Verlinkungen.  Die Länge des Artikels kann entsprechend reduziert werden.

2021-12-08 20:50 UTC, Teemoma requested changes
**Ressource_Leveling**
| Kriterium | Bewertung|
|-----|---|
| Front-Matter | ja |
| Umfang | ja|
| Belege | ja|
| Links | ja|
| Formatierung | ja|
| Verlinkungen vorhanden |  nein |
| Abbildungen | ja|
| Strukturierung des Beitrags | 8|
| Rechtschreibung | 9|
| Sprache | 9|
| Inhalt | 9|
| Einordnung in den Kontext | 9|
| Ansprechend für Zielgruppe | 9|

# Zusammenfassung

Dieser Artikel beschreibt die Definition von Ressourcen leveling , Einsatz und Technik.  Beschreibt gleichzeitig vier Gründe für die Gleichheit der Ressourcen.


# Positive Aspekte

Der Artikel ist übersichtlich aufgebaut, bietet dem Leser eine ausführliche Einführung in die Ressourcen leveling und die Wortzahl ist angemessen.


# Negative Aspekte

Es gibt keinen Verlinkung zu diesem Artikel.Ich denke, die Definition ist etwas zu lang und enthält einige irrelevante Inhalte.

 **Who is Who Projectmanagement**
| Kriterium | Bewertung|
|-----|---|
| Front-Matter | ja |
| Umfang | ja|
| Belege | ja|
| Links | ja|
| Formatierung | ja|
| Verlinkungen vorhanden | nein |
| Abbildungen | nein |
| Strukturierung des Beitrags | 9|
| Rechtschreibung | 9|
| Sprache | 10 |
| Inhalt | 9|
| Einordnung in den Kontext | 10|
| Ansprechend für Zielgruppe | 9|

# Zusammenfassung

Dieser Artikel beschreibt das Projektmanagement verschiedener Personen und ihre unterschiedlichen Rollen.

# Positive Aspekte

Der Artikel ist klar und umfassend. Die Sprache ist sehr professionell und detailliert. Und Angemessene Anzahl von Zitierung.

# Negative Aspekte#

Mangel an geeigneten Diagrammen und Verlinkungen.  Die Länge des Artikels kann entsprechend reduziert werden.

2021-12-09 19:40 UTC, merged