Uebersicht_PM_Tools
ManagingProjectsSuccessfully/ManagingProjectsSuccessfully.github.io pull request #239
Opened 2021-11-23 23:42 UTC by christian-anghel

Hier meine Pull Request für das Thema Übersicht Projektmanagement Tools

2021-12-02 00:10 UTC, mirela08 requested changes
| Kriterium | Bewertung|
|-----|---|
| Front-Matter | ja |
| Umfang | ja |
| Belege | ja |
| Links | ja |
| Formatierung | ja |
| Verlinkungen vorhanden | ja |
| Abbildungen | ja |
| Strukturierung des Beitrags | 9 |
| Rechtschreibung | 9 |
| Sprache | 8 |
| Inhalt | 10 |
| Einordnung in den Kontext | 10 |
| Ansprechend für Zielgruppe |10|

# Zusammenfassung
Kurze Zusammenfassung des/der Artikel

Der Artikel befasst sich mit den verschiedenen Werkzeugen des Projektmanagements. Es werden wichtige Schlüsselbegriffe erläutert und das Konzept der Tools erläutert mit Angaben zur Statistik. 

# Positive Aspekte

Was ist gut (Bezug zur Tabelle)

Ich finde gut, dass der Artikel einen roten Faden hat und Struktur aufzeigt. Angefangen bei der Geschichte bis hin zu den Vor- & Nachteilen. Es wurden aussagekräftige Abbildungen genutzt, um das Thema näher zu erläutern. Besonders gefällt mir die selbst erstellte Tabelle zur Projektplanung. Die Überschriften wurden gut gewählt und alle Links/Belege funktionieren einwandfrei. Der Artikel lässt sich einfach lesen uns wurde sehr verständlich verfasst, entsprechend der Zielgruppe angepasst. Im Ganzen ein sehr guter Artikel!

# Negative Aspekte

Was geht besser (Bezug zur Tabelle)

Der Artikel zeigt die gute Recherche des Verfassers auf, jedoch hätte man an einigen Passagen (z.B Kommunikation und Zusammenarbeit) etwas mehr auf das Thema eingehen können, was aber bei dem Wörterlimit von 500 verständlich ist. Um den Artikel etwas professioneller wirken zu lassen, könnte man eventuell mehr Fachbegriffe verwenden, damit es einem "Wikipedia-Eintrag" ähnelt. Auch wäre das Beifügen von weiterführender Literatur, für Interessierte, von Vorteil.

2021-12-04 12:27 UTC, JacquelineRal requested changes
| Kriterium | Bewertung|
|-----|---|
| Front-Matter | ja |
| Umfang | ja |
| Belege | ja |
| Links | ja|
| Formatierung | ja|
| Verlinkungen vorhanden |  nein |
| Abbildungen | ja |
| Strukturierung des Beitrags | 10 |
| Rechtschreibung | 10 |
| Sprache | 8 |
| Inhalt | 9 |
| Einordnung in den Kontext | 10|
| Ansprechend für Zielgruppe | 9 |

# Zusammenfassung

Der Artikel befasst sich mit den Aufgaben von Projektmanagement-Tools und gibt einen kleinen Einblick in die Geschichte und Entstehung, als auch die Vor-und Nachteile solcher Tools. 

# Positive Aspekte

Der Artikel ist sehr übersichtlich, da es schöne Abbildungen und eine gute Struktur und Formatierung gibt. Alle Links funktionieren einwandfrei. Der Artikel ist verständlich geschrieben und gibt inhaltlich einen guten ersten Einblick in das Thema. Toll ist auch die Verlinkung einzelner Begriffe in der Tabelle. 

# Negative Aspekte

Eine Verlinkung zu einem anderen Thema wäre eventuell noch schön gewesen. Teilweise könnte man mehr Fachbegriffe einfließen lassen und das Sprachniveau vereinzelt anheben.

2021-12-08 20:03 UTC, Teemoma requested changes
| Kriterium | Bewertung|
|-----|---|
| Front-Matter | ja|
| Umfang | ja|
| Belege | ja|
| Links | ja|
| Formatierung | ja|
| Verlinkungen vorhanden | nein |
| Abbildungen |  nein |
| Strukturierung des Beitrags | 9 |
| Rechtschreibung | 10|
| Sprache | 9 |
| Inhalt | 8|
| Einordnung in den Kontext | 10|
| Ansprechend für Zielgruppe | 8|

# Zusammenfassung

Der Artikel befasst sich mit Übersicht_PM_Tools. Der Autor verwendet eine Geschichte, um den Artikel einzuführen. Es wurde wichtige Aufgaben eines Projektmanagement-Tools und Vor- und Nachteile beschrieben.

# Positive Aspekte

Der Artikel ist klar und umfassend.  Als Meinungsbeweis dienen zwei geeignete Diagramme.  Die zitierte Quelle ist sehr gut.

# Negative Aspekte
Dem Artikel fehlt ein Bild.  Es wäre schön, wenn es mehr professionelle Beschreibungen gäbe.  Auch die Sprache hat Verbesserungspotential.

2021-12-09 19:40 UTC, merged

2021-12-23 15:37 UTC, christian-anghel commented
Hallo,
@Teemoma @mirela08 @JacquelineRal 

Vielen Dank für euer Feedback, ich habe eure Kritik gelesen und angesprochene Dinge verbessert. Hier mein kleiner Überblick:

- Ich habe das Sprachniveau möglichst angehoben
- Verlinkungen sollten nun funktionieren
- Weiterführende Literatur wurde hinzugefügt
- Das Thema "Kommunikation und Zusammenarbeit" wurde näher erläutert