(1) RACI & (2) Scrum_at_Scale
ManagingProjectsSuccessfully/ManagingProjectsSuccessfully.github.io pull request #244
Opened 2021-11-24 00:48 UTC by mirela08

2021-12-04 12:08 UTC, JacquelineRal requested changes
| Kriterium | Bewertung|
|-----|---|
| Front-Matter | ja |
| Umfang | ja |
| Belege | ja |
| Links | ja|
| Formatierung | ja |
| Verlinkungen vorhanden | ja |
| Abbildungen | ja |
| Strukturierung des Beitrags | 10 |
| Rechtschreibung | 10|
| Sprache | 10 |
| Inhalt | 10|
| Einordnung in den Kontext | 10|
| Ansprechend für Zielgruppe | 10|

# Zusammenfassung

RACI ist eine Technik mithilfe derer man erkennt, wer in einem Projekt für was verantwortlich ist. Die Aufgaben sind in die vier Teilbereiche Responsible, Accountable, Consulted und Informed aufgeteilt. Eine Person kann hierbei auch für mehrere Aufgaben verantwortlich sein. Raci dient dazu eine Übersicht über alle Personen und deren Aufgaben zu behalten.

# Positive Aspekte

Inhaltlich, als auch sprachlich ist der Artikel sehr gut gelungen, ebenso die Struktur. Alle Links funktionieren einwandfrei. Auch die Formatierung ist sehr übersichtlich.

# Negative Aspekte

Zu dem Artikel lassen sich keine negativen Aspekte finden.

2021-12-07 20:52 UTC, lianalia requested changes
1. RACI 

| Kriterium | Bewertung|
|-----|---|
| Front-Matter | ja |
| Umfang | ja |
| Belege | ja |
| Links | ja |
| Formatierung | ja |
| Verlinkungen vorhanden | ja |
| Abbildungen | ja |
| Strukturierung des Beitrags | 10 |
| Rechtschreibung | 10 |
| Sprache | 10 |
| Inhalt | 10|
| Einordnung in den Kontext | 10|
| Ansprechend für Zielgruppe |10|

# Zusammenfassung

Der Artikel befasst sich mit RACI, das eine Technik zur Analyse und Darstellung von Verantwortlichkeiten beschreibt. Die Bereiche sind Responsible, Accountable, Consulted, Informed. Diese Aspekte werden Personen zugeteilt, dabei kann nur eine Person jeweils responsible oder accountable sein, die restlichen Punkte können wiederholt auftreten. Die RACI Matrix nutzt vor allem der graphischen Übersicht, verbessert Kommunikation und legt Verantwortlichkeiten klar fest. Dem gegenüber stehen hoher Aufwand bei Erstellung der Matrix und Unübersichtlichkeit bei großen Projekten.

# Positive Aspekte

Die Kriterien zu Front-Matter, Umfang und Belegen sind alle erfüllt. Die Links zu weiterführenden Artikeln und externen Seiten funktionieren. Wichtige Aussagen oder Worte werden vorgehoben. Der Sprachstil ist formal, sachlich und leicht verständlich. Die Struktur ist klar und übersichtlich. Sowohl die Tabelle als auch die Grafik sind gut eingebaut und bieten eine klare visuelle Übersicht über das Thema.  Der Inhalt ist sehr gut aufbereitet und ist ansprechend für den Leser. Die weiterführende Literatur greift weitere interessante Aspekte im Bezug zum Thema auf.

# Negative Aspekte

Nur Kleinigkeiten: Der Punkt „RACI-VS“ im Punkt Varianten ist anders formatiert als die restlichen Punkte (Zeile 88). Die Quellenverweise könnte man jeweils nach den Absätzen hinzufügen, statt an die Überschriften.

2. Scrum at Scale

| Kriterium | Bewertung|
|-----|---|
| Front-Matter | ja |
| Umfang | ja|
| Belege | ja |
| Links | ja |
| Formatierung | ja |
| Verlinkungen vorhanden | ja |
| Abbildungen | ja |
| Strukturierung des Beitrags | 10 |
| Rechtschreibung | 10|
| Sprache | 9 |
| Inhalt |10|
| Einordnung in den Kontext | 10|
| Ansprechend für Zielgruppe | 10|

# Zusammenfassung

Scrum at Scale beschreibt ein Framework zur Skalierung von Scrum. Das Konzept ermöglicht mehreren Teams eine Zusammenarbeit in komplexen Umgebungen und bietet somit auch Großunternehmen die Möglichkeit Scrum effektiv einzusetzen. Das Scrum at Scale Framwork wird in zwei Zyklen unterteilt: Product Owner und Scrum Master Zyklus.

# Positive Aspekte

Die Kriterien zu Front-Matter, Umfang und Belegen sind alle erfüllt. Die Links zu weiterführenden Artikeln und externen Seiten funktionieren. In-text Verlinkungen sind richtig eingearbeitet und funktionieren. Die Struktur ist sehr übersichtlich und Inhalte werden verständlich dargestellt. Die Graphiken unterstützen den Leser dabei, komplexe Sachverhalte schnell zu verstehen. Grammatik und Rechtschreibung sind einwandfrei umgesetzt, sprachlich ist der Artikel weitestgehend korrekt.
# Negative Aspekte

Das „wir“ (Zeile 45 & 48) am besten umschreiben. Quelle 3 im Verzeichnis ist nicht ganz korrekt angegeben. 

Ansonsten beide Artikel sehr gut geschrieben!

2021-12-08 21:23 UTC, Teemoma requested changes
**RACI**
| Kriterium | Bewertung|
|-----|---|
| Front-Matter | ja |
| Umfang | ja|
| Belege | ja|
| Links | ja|
| Formatierung | ja|
| Verlinkungen vorhanden | ja|
| Abbildungen | nein|
| Strukturierung des Beitrags | 10|
| Rechtschreibung | 10|
| Sprache | 10 |
| Inhalt | 9|
| Einordnung in den Kontext | 9|
| Ansprechend für Zielgruppe | 9|

# Zusammenfassung

Dieser Artikel beschreibt ausführlich die Definition von RACI, die Vor- und Nachteile der RACI-Matrix und die Varianten von RACI.

# Positive Aspekte

Die Sprache ist sehr professionell und detailliert. Der Artikel ist klar und umfassend, vermittelt dem Leser ein klares und umfassendes Verständnis des Themas RACI.


# Negative Aspekte

Mangel an geeigneter Abbildung.


**Scrum at Scale**

| Kriterium | Bewertung|
|-----|---|
| Front-Matter | ja|
| Umfang | ja|
| Belege | ja |
| Links | ja|
| Formatierung | ja|
| Verlinkungen vorhanden | ja |
| Abbildungen | ja|
| Strukturierung des Beitrags | 9|
| Rechtschreibung | 10|
| Sprache | 10|
| Inhalt | 9|
| Einordnung in den Kontext | 10|
| Ansprechend für Zielgruppe | 10|

#Zusammenfassung

Dieser Artikel stellt das ein Framework zur Skalierung von Scrum sowie zwei Teile davon vor: Product Owner und Scrum Master Zyklus.

# Positive Aspekte

Die Sprache ist sehr professionell und detailliert.Dieser Artikel vermittelt dem Leser ein klares und umfassendes Verständnis des Thema.



# Negative Aspekte

Es wäre schön, wenn der Inhalt zum Thema mehr angereichert wäre.

2021-12-08 21:24 UTC, Teemoma requested changes
**RACI**
| Kriterium | Bewertung|
|-----|---|
| Front-Matter | ja |
| Umfang | ja|
| Belege | ja|
| Links | ja|
| Formatierung | ja|
| Verlinkungen vorhanden | ja|
| Abbildungen | nein|
| Strukturierung des Beitrags | 10|
| Rechtschreibung | 10|
| Sprache | 10 |
| Inhalt | 9|
| Einordnung in den Kontext | 9|
| Ansprechend für Zielgruppe | 9|

# Zusammenfassung

Dieser Artikel beschreibt ausführlich die Definition von RACI, die Vor- und Nachteile der RACI-Matrix und die Varianten von RACI.

# Positive Aspekte

Die Sprache ist sehr professionell und detailliert. Der Artikel ist klar und umfassend, vermittelt dem Leser ein klares und umfassendes Verständnis des Themas RACI.


# Negative Aspekte

Mangel an geeigneter Abbildung.


**Scrum at Scale**

| Kriterium | Bewertung|
|-----|---|
| Front-Matter | ja|
| Umfang | ja|
| Belege | ja |
| Links | ja|
| Formatierung | ja|
| Verlinkungen vorhanden | ja |
| Abbildungen | ja|
| Strukturierung des Beitrags | 9|
| Rechtschreibung | 10|
| Sprache | 10|
| Inhalt | 9|
| Einordnung in den Kontext | 10|
| Ansprechend für Zielgruppe | 10|

# Zusammenfassung

Dieser Artikel stellt das ein Framework zur Skalierung von Scrum sowie zwei Teile davon vor: Product Owner und Scrum Master Zyklus.

# Positive Aspekte

Was ist gut (Bezug zur Tabelle)

# Negative Aspekte

Was geht besser (Bezug zur Tabelle)

2021-12-09 19:40 UTC, merged

2021-12-16 01:28 UTC, mirela08 commented
Hallo @Teemoma ,
ich bedanke mich für dein Feedback! Ich glaube bei dem Artikel "RACI" hast du die kleine Abbildung übersehen. Sie ist in Farbe und sieht tatsächlich aus, wie eine selbst erstellte Tabelle. Ich werde versuchen diese Abbildung zu vergrößern, damit sie besser zu sehen ist. 
Viele Grüße :)

2021-12-16 01:30 UTC, mirela08 commented
Hallo @lianalia ,
vielen Dank für dein tolles Feedback. Du hast sehr gute Augen, ein paar Sachen habe ich selber nicht erkannt. Ich werde deine Verbesserungsvorschläge berücksichtige. 
Liebe Grüße