Zukunftswerkstatt; Softskills im PM
ManagingProjectsSuccessfully/ManagingProjectsSuccessfully.github.io pull request #249
Opened 2021-11-24 09:42 UTC by ig27oqaf

2021-12-04 16:32 UTC, 5SY5 requested changes
| Kriterium | Bewertung|
|-----|---|
| Front-Matter | nein|
| Umfang | ja|
| Belege | ja |
| Links | ja|
| Formatierung | ja|
| Verlinkungen vorhanden | ja |
| Abbildungen | ja |
| Strukturierung des Beitrags | 7 |
| Rechtschreibung | 9|
| Sprache | 10 |
| Inhalt | 8|
| Einordnung in den Kontext | 9|
| Ansprechend für Zielgruppe | 8|

# Zusammenfassung

Am Anfang des Artikels werden Projektmanagement und Soft Skills kurz definiert. Anschließend wird direkt Bezug auf die Softskills genommen, indem die Problematik bei fehlenden Soft Skills erläutert wird. Des Weiteren werden Teilbereiche beleuchtet.

# Positive Aspekte

Der Artikel ist sehr gut abgerundet und erklärt die genannten Sachverhalte in einem guten sprachlichen Niveau. Insgesamt ein guter Artikel

# Negative Aspekte

Zunächst einmal gibt es teilweise grammatikalische Fehler wie z.B. im ersten Absatz " persönliche Werte (z. B. Fairness & Respekt), persönlichen Eigenschaften" hier könnte das zweite persönlich gestrichen werden (sprachlich angenehmer). Weiterhin ist die gewählt Struktur nicht sehr vorteilhaft, da dadurch nicht erkenntlich wird was der Inhalt nun Aussagen soll. Es ist nicht ersichtlich in welchen Kompetenzbereichen die Inhalte eingeordnet sind, die mit der gewählten Abbildung (die nicht weiter erklärt wurde) aufgeführt werden. 
Dazu könnte man z.B. die Struktur aus dieser Website als Vorlage verwenden https://unternehmer.de/lexikon/online-marketing-lexikon/soft-skills. Außerdem wäre es wünschenswert Weiterführende Literaturen zu empfehlen (falls es die geben sollte).

2021-12-04 17:01 UTC, 5SY5 requested changes
| Kriterium | Bewertung|
|-----|---|
| Front-Matter | ja |
| Umfang | ja|
| Belege | ja |
| Links | ja|
| Formatierung | ja|
| Verlinkungen vorhanden | ja|
| Abbildungen | ja|
| Strukturierung des Beitrags | 10 |
| Rechtschreibung | 9|
| Sprache | 9 |
| Inhalt | 10|
| Einordnung in den Kontext | 10|
| Ansprechend für Zielgruppe | 10|

# Zusammenfassung

Der Artikel beginnt mit einer kurzen Überleitung zur Methode Zukunftswerkstatt und bezieht sich im Anschluss auf den geschichtlichen Aspekt der Methode. Daraufhin werden die einzelnen Anwendungsgebiete aufgelistet und erklärt, dass die Anwendung bis hin zu mehreren Tagen ansetzbar ist. Um die Anwendung durchzuführen wird im nächsten Abschnitt der Ablauf erklärt. Abschließend bezieht sich der Autor auf das Praxisbeispiel von Google.

# Positive Aspekte

Ein sehr schöner kompakter Bericht,  der sprachlich sehr gut zu verstehen ist. Lobenswert ist hier die Struktur und der Einbezug eines Praxisbeispiels, dass die Methode verständlicher ausdrückt. Insgesamt Top Leistung :).

# Negative Aspekte

Bei der Anwendung wird plötzlich von JBZ Werkstatt gesprochen. AM besten vorab erklären, dass der Begriff sowohl so oder so genannt werden kann. (Es kommt zu leichten Verwirrungen)
Ansonsten wäre es schön noch weiterführende Literatur einzufügen. (Falls auffindbar)

2021-12-05 16:24 UTC, LKmps2021 requested changes
Softskills_im_Projektmanagement
| Kriterium | Bewertung|
|-----|---|
| Front-Matter | ja |
| Umfang | ja |
| Belege | nein |
| Links | ja |
| Formatierung | ja |
| Verlinkungen vorhanden | ja |
| Abbildungen | ja |
| Strukturierung des Beitrags | 8 |
| Rechtschreibung | 9 |
| Sprache | 9 |
| Inhalt | 9 |
| Einordnung in den Kontext | 9 |
| Ansprechend für Zielgruppe | 9 |

# Zusammenfassung

Der Artikel beschäftigt sich mit dem Thema Softskills im Projektmanagement. Hierbei wird zunächst das Thema definiert und im Anschluss geht der Autor anhand einer Aufzählung auf die wichtigsten Kompetenzen Eigeninitiative, Vernetztes Denken, Kooperation und Konfliktfähigkeit, Flexibilität/Agilität und Innovationsfähigkeit im Bereich der Soft Skills ein. 

# Positive Aspekte

Es gibt einige Verlinkungen zu anderen Themenbereichen. Außerdem funktionieren sowohl die eingefügten Links von den Quellen als auch die direkten Verlinkungen auf die anderen Themenbereiche. Es lassen sich kaum Rechtschreibfehler finden und die Sätze sind klar strukturiert und sinnvoll aufgebaut. Das Thema wurde kompakt und präzise erläutert und interessant wiedergegeben.

# Negative Aspekte

Die Quellen wurden ohne Titel der Artikel angegeben. Interessant wäre auch zusätzliche weiterführende Literatur. Außerdem sollte zur Grafik aktiv eine Quelle verlinkt werden. Man könnte die Grafik vielleicht auch nach oben vor dem Punkt Eigeninitiative verschieben und sie kurz erläutern und auf sie eingehen.
Auch könnte man den Punkt vor der Grafik als eigenes Kapitel nehmen. Man könnte es dann als Fazit bezeichnen. 
Auch könnte man überlegen, die Punkte der Aufzählung (Punkte: Eigeninitiative, Vernetztes Denken, Kooperation und Konfliktfähigkeit, Flexibilität / Agilität, Innovationsfähigkeit) zu Überschriften zweiten Grades zu machen (mit ## davor) oder diese Punkte schöner zu formatieren, indem man beispielsweise den Text einrückt nach einem Stichpunkt.



Zukunftswerkstatt
| Kriterium | Bewertung|
|-----|---|
| Front-Matter | ja |
| Umfang | ja |
| Belege |  nein |
| Links | ja |
| Formatierung | ja |
| Verlinkungen vorhanden | ja |
| Abbildungen | ja |
| Strukturierung des Beitrags | 8 |
| Rechtschreibung | 9 |
| Sprache | 10 |
| Inhalt | 9 |
| Einordnung in den Kontext | 10 |
| Ansprechend für Zielgruppe | 9 |

# Zusammenfassung

Der Artikel beschreibt das Thema der Zukunftswerkstatt. Im ersten Abschnitt wird das Thema definiert. Im zweiten Abschnitt wird die Geschichte der Zukunftswerkstätten erläutert. Danach werden die Anwendungsfälle kurz stichpunktartig aufgeführt. Im nächsten Kapitel werden dann die drei Phasen: Kritikphase - Bestandsaufnahme, Fantasie- & Utopiephase, Realisierungs- Strategiephase erläutert und zum Abschluss wird nochmal auf die Anwendung in der Praxis von Zukunftswerkstätten am Beispiel von Google eingegangen. 

# Positive Aspekte

Es gibt viele Verlinkungen zu anderen Themenbereichen. Außerdem funktionieren sowohl die eingefügten Links von den Quellen als auch die direkten Verlinkungen auf die anderen Themenbereiche. Die Struktur ist klar verständlich und sinnvoll. Nur das Kapitel Anwendung der JBZ Werkstatt würde ich nach das Kapitel Ablauf einordnen. Die Sätze sind klar formuliert und haben Struktur. Es lassen sich kaum Rechtschreibfehler finden. Es macht Spaß den Artikel zu lesen, da er das wesentliche prägnant zusammenfasst.

# Negative Aspekte

Die Quellen wurden ohne Titel der Artikel angegeben. Außerdem sollte zur Grafik aktiv eine Quelle (Fußnote) verlinkt werden. Interessant wäre auch zusätzliche weiterführende Literatur. 
Man könnte noch einige der Kreativitätstechniken zusätzlich oder doppelt verlinken, z.B Brainstorming in Kapitel „I. Kritikphase | Bestandsaufnahme“. 
In dem Kapitel „Anwendung der JBZ Werkstatt“ würde ich vor der Aufzählung kurz einleiten und erläutern was im Folgenden aufgezählt wird. Zusätzlich würde ich den Begriff JBZ erläutern.

2021-12-06 21:20 UTC, zo54hoko requested changes
Soft Skills im Projektmanagement 
| Kriterium | Bewertung|
|-----|---|
| Front-Matter | ja |
| Umfang | ja |
| Belege | ja |
| Links | ja |
| Formatierung | ja |
| Verlinkungen vorhanden | ja |
| Abbildungen | ja |
| Strukturierung des Beitrags | 9 |
| Rechtschreibung | 10 |
| Sprache | 10 |
| Inhalt | 9 |
| Einordnung in den Kontext | 8 |
| Ansprechend für Zielgruppe | 9 |
 
# Zusammenfassung
Der Beitrag befasst sich mit den soft Skills im Projektmanagement. Anfangs geht der Autor auf die allgemeine Definition der soft Skills ein und welche Bedeutung diese für Projekte haben. Dabei spielen  persönliche Werte (z. B. Fairness & Respekt), persönlichen Eigenschaften (z. B. Geduld), individuellen Fähigkeiten (z. B. Kritikfähigkeit) und soziale Kompetenzen (z. B. Kommunikationsfähigkeit) von Führungskräften und Mitarbeitern eines Unternehmens eine wichtige Rolle.  Des Weiteren wird auf die Problematik des Fehlens von soft Skills im Projektmanagement eingegangen. Zum Schluss werden wichtige soft Skills im Projektmanagement angesprochen, die unteranderem Eigeninitiative, vernetztes Denken, Kooperation und Konfliktfähigkeit, Flexibilität/ Agilität und Innovationsfähigkeit sind.
 
 
# Positive Aspekte

Alle Kriterien sind erfüllt. Die Struktur ist sehr schön und gibt dem Leser die Möglichkeit dem Inhalt gut zu folgen. Die Rechtschreibung und Grammatik ist einwandfrei. Es wurde eine sachliche leicht verständliche Sprache gewählt. Der Verfasser hat viele Verlinkungen zu angrenzenden Themen eingefügt und alle Links, die der Beitrag enthält funktionieren.  Insgesamt ein gelungener Beitrag, der rundum informiert.
 
# Negative Aspekte

Der Übergang zu den einzelnen soft Skills im Projektmanagement fehlt, diesen könnte man noch erstellen. Man könnte noch auf weiterführende Literatur hinweisen, die das Thema weitervertiefen oder auf verwandte Themen hinweisen. Die Quellen zu den Abbildungen sollten hinzugefügt werden und man könnte noch auf die Abbildungen im Text eingehen.




Zukunftswerkstatt
| Kriterium | Bewertung|
|-----|---|
| Front-Matter | ja |
| Umfang | ja |
| Belege | ja |
| Links | ja |
| Formatierung | ja |
| Verlinkungen vorhanden | ja |
| Abbildungen | ja |
| Strukturierung des Beitrags | 10 |
| Rechtschreibung | 9 |
| Sprache | 10 |
| Inhalt | 8 |
| Einordnung in den Kontext | 8 |
| Ansprechend für Zielgruppe | 9 |


# Zusammenfassung

Der Beitrag informiert über die Zukunftswerkstatt. Zunächst geht es um die geschichtlichen Hintergründe des Konzepts, das es seit mehr als 25 Jahre bereits gibt. Im Folgenden werden die Anwendungsbereiche der Zukunftswerkstatt gezeigt, wie zum Beispiel zur Teamentwicklung, im Projektmanagement oder zur Demokratiebildung im schulischen und außerschulischen Bereich. Zum Schluss geht der Autor auf den Ablauf der Zukunftswerkstatt ein, der aus drei Phasen besteht. Der Ablauf beginnt mit der Kritikphase bzw. Bestandsaufnahme, wird fortgeführt mit der Fantasie- & Utopiephase und wird beendet mit der Realisierungs- l Strategiephase.

# Positive Aspekte

Alle Kriterien sind erfüllt. Die Struktur ist sehr schön und gibt dem Leser die Möglichkeit dem Inhalt gut zu folgen. Die Rechtschreibung und Grammatik ist einwandfrei. Der Enzyklopädie Stil wurde erfüllt und die Sprache ist leicht verständlich gewählt. Der Verfasser hat viele Verlinkungen zu angrenzenden Themen eingefügt und alle Links, die der Beitrag enthält funktionieren. Ein guter Beitrag, der Spaß macht zu lesen. 
 
# Negative Aspekte

Zunächst würde ich erwähnen, dass man ein wenig erzählt was genau die JBZ ist. Man könnte noch auf weiterführende Literatur hinweisen, die das Thema weitervertiefen oder auf verwandte Themen hinweisen. Die Quellen zu den Abbildungen sollten hinzugefügt werden und man könnte noch auf die Abbildungen im Text eingehen.

2021-12-09 19:40 UTC, merged