GPM_Institution; Aktuelle Entwicklungen im PM
ManagingProjectsSuccessfully/ManagingProjectsSuccessfully.github.io pull request #250
Opened 2021-11-24 09:45 UTC by zo54hoko

2021-12-04 22:17 UTC, 5SY5 requested changes
**Review zu Aktuelle Entwicklungen im PM**
| Kriterium | Bewertung|
|-----|---|
| Front-Matter | ja |
| Umfang | ja|
| Belege | ja |
| Links | ja|
| Formatierung | ja|
| Verlinkungen vorhanden | ja |
| Abbildungen | ja |
| Strukturierung des Beitrags | 10 |
| Rechtschreibung | 9|
| Sprache | 8 |
| Inhalt | 9|
| Einordnung in den Kontext | 10|
| Ansprechend für Zielgruppe | 10|

# Zusammenfassung

Der Artikel leitet das Thema an anfangs kurz ein. Daraufhin wird Bezug auf die 7 Prinzipen genommen, die einzeln erklärt werden. Anschließend folgen die aktuellen Trends im Projektmanagement, indem Ansätze die im Projektmanagement aufgelistet werden und genau geschildert werden. Zum Schluss wird mithilfe einer Grafik, die aufzeigt welche agilen Methoden angewendet werden, das Thema visuell abgerundet. 

# Positive Aspekte

Ein insgesamt runder Bericht. Es wird die Thematik gut verdeutlicht und dargestellt. Andere Themen wurden umfassen verlinkt und einbezogen. Es gibt ein guten allgemeinen Überblick über den aktuellen Stand im Projektmanagement.

# Negative Aspekte

Ein Verbesserungsvorschlag wäre, dass vielleicht vorab kurz definiert wird was Projektmanagement 4.0 ist. Also in Endeffekt was darunter zu verstehen ist. Außerdem würde ich mal nach Weiterführende Literatur suchen, vielleicht findest du etwas :). Es wäre gut, wenn die Grafik etwas beschrieben wird. Heißt mit ein zwei Sätzen kurz auf die Grafik eingehen, damit sie nicht so hin geklatscht wirkt. Aber das sind nur kleine Anmerkungen :)

2021-12-04 22:47 UTC, 5SY5 requested changes
**Review zu GPM Institution**

| Kriterium | Bewertung|
|-----|---|
| Front-Matter | ja |
| Umfang | ja|
| Belege | ja |
| Links | ja|
| Formatierung | ja|
| Verlinkungen vorhanden | ja |
| Abbildungen | ja |
| Strukturierung des Beitrags | 10 |
| Rechtschreibung | 9|
| Sprache | 9|
| Inhalt | 8|
| Einordnung in den Kontext | 10|
| Ansprechend für Zielgruppe | 10|

# Zusammenfassung

Der Artikel beginnt mit einer kurzen Erläuterung über die GPM Institution. Der nächste Punkt ist die Geschichte, indem die Gründung und das Ursprungsziel beschrieben werden.  Anschließend werden die Auszeichnung mit denen der GPM andere Unternehmen etc. auszeichnet. Daraufhin bezieht sich der Autor kurz auf die Studien und rundet es mit einer Grafik ab. Als nächstes wird das Flüchtlingsprojekt erwähnt und zum Schluss wird auf, die seit 1992 existierende, GPM Young Crew eingegangen.

# Positive Aspekte

Es ist ein sprachlich guter Artikel, der sauber strukturiert ist. Außerdem werden hier sehr viele Aspekte aufgegriffen und somit ein umfangreicher Überblick über das Thema geschaffen. Im groben und ganzen ein sehr gelungener Artikel.

# Negative Aspekte

Ein Verbesserungsvorschlag wäre, dass mehr in die Studien eingegangen wird (wenn sich auch etwas interessantes finden lässt) und dafür vielleicht die Auszeichnungen kurz angerissen werden. Außerdem würde es Sinn machen die Grafik zu erklären, da dieser einen inhaltlichen Mehrwert bietet. Heißt ein paar Sätze dazu, was die Kernaussage der Grafik ist würde schon reichen.  Vielleicht hilft es weiterführende Literatur zu verwenden, um mehr Inhalt für die Studien zu erhalten. Sonst wirklich sehr schön :)

2021-12-05 14:34 UTC, LKmps2021 requested changes
#Aktuelle Entwicklungen im PM
| Kriterium | Bewertung|
|-----|---|
| Front-Matter | ja |
| Umfang | nein |
| Belege | nein |
| Links | ja |
| Formatierung | ja |
| Verlinkungen vorhanden | ja |
| Abbildungen | ja |
| Strukturierung des Beitrags | 3 |
| Rechtschreibung | 9 |
| Sprache | 5 |
| Inhalt | 5 |
| Einordnung in den Kontext | 9 |
| Ansprechend für Zielgruppe | 3 |

# Zusammenfassung

In dem Artikel geht es um die aktuellen Entwicklungen im Projektmanagement. Es wird zu Beginn kurz in das Thema eingeleitet. Danach werden Die 7 Prinzipien von Projektmanagement 4.0 kurz erklärt und aufgeführt und zum Schluss werden noch einige Projektmanagement Trends aufgeführt. 

# Positive Aspekte

Es lassen sich viele Verlinkungen zu anderen Themenbereichen in dem Artikel finden. Außerdem funktionieren sowohl die eingefügten Links von den Quellen als auch die direkten Verlinkungen auf die anderen Themenbereiche. Es lassen sich kaum Rechtschreibfehler finden, wenige Wortendungen sind falsch und es wurden einzelne Kommafehler gemacht.  Der Fachbegriff Mehrwert wurde falsch als Nährwert bezeichnet.

# Negative Aspekte

Leider wurden keine passenden Einleitungen bzw. Übergänge zu den einzelnen Themen gefunden und es wurden Themen teilweise komplett kontextlos nacheinander aufgeführt. So werden z.B „Die 7 Prinzipien von Projektmanagement 4.0“ ohne Überleitung und Begründung warum sie relevant und wichtig für das Thema sind, aufgeführt. Dadurch fühlt es sich beim Lesen an, als wären die Themengebiete zusammenhangslos ausgewählt worden.  Auch fehlt bei der Abbildung die Quellenangabe und die Grafik sollte zusätzlich kurz erklärt und in das Thema eingeordnet werden. Beispiel: die Jahresangabe aus welchem Jahr die Grafik stammt usw. Die Quellen wurden ohne Titel der Artikel angegeben. Den Umfang würde ich reduzieren, da dieser 600 Wörter umfasst (20% zu viel). Der Fachbegriff Mehrwert wurde falsch als Nährwert bezeichnet.
Man könnte schönere Formatierungen verwenden, z.B. den Text einrücken nach einem Stichpunkt. Auch die Sätze könnten schöner formuliert werden, da sie teilweise umständlich sind, z.B.“ Neue Herausforderungen entwickeln sich unter anderem durch den schnellen technischen Fortschritt, die Megatrends, wodurch eine digitale Transformation entsteht und auch durch die Globalisierung entwickeln sich Komplexitäten für das Projektmanagement.“ Der Inhalt ist meiner Meinung nach nur teilweise relevant und gut ausgewählt. Aus meiner Sicht wurde das Kapitel Aktuelle Projektmanagement Trends an sich gut ausgewählt. Das ausgewählte Thema „Die 7 Prinzipien von Projektmanagement 4.0“ ist aus meiner Sicht aus dem gegebenen Kontext nicht gut ausgewählt worden, da nicht deutlich wird, warum es für den Artikel relevant ist.  Interessant wäre auch zusätzliche weiterführende Literatur.

#GPM_Institution
| Kriterium | Bewertung|
|-----|---|
| Front-Matter | ja |
| Umfang | ja |
| Belege | nein |
| Links | ja |
| Formatierung | ja |
| Verlinkungen vorhanden | ja |
| Abbildungen | ja |
| Strukturierung des Beitrags | 6 |
| Rechtschreibung | 9 |
| Sprache | 7 |
| Inhalt | 4 |
| Einordnung in den Kontext | 8 |
| Ansprechend für Zielgruppe | 3 |

# Zusammenfassung

Der Artikel befasst sich mit dem Thema die Deutsche Gesellschaft für Projektmanagement (GPM) . Er beginnt mit einer kurzen Definition und einer Einführung in die Geschichte der GPM. Danach werden die Auszeichnungen der Gesellschaft aufgeführt und kurz auf eine Studie eingegangen. Abschließend werden nochmal zwei Projekt der GPM beleuchtet.

# Positive Aspekte

Es lassen sich einige Verlinkungen zu anderen Themenbereichen in dem Artikel finden. Außerdem funktionieren sowohl die eingefügten Links von den Quellen als auch die direkten Verlinkungen auf die anderen Themenbereiche. Es lassen sich kaum Rechtschreibfehler finden und die Sätze sind größtenteils klar strukturiert.

# Negative Aspekte

Es fehlt die Quellenangabe zur Grafik. Außerdem sollten die Hintergründe bzw. der Kontext zu dem Projekt, aus dem die Grafik entstanden ist, erläutert werden. In den Quellenangaben wurden nur die Links ohne Titel der Artikel angegeben.
Man könnte bessere Formatierungen verwenden, z.B. den Text einrücken nach einem Stichpunkt. 
Der Artikel könnte auch anders strukturiert werden. Es könnten bessere Einleitungen bzw. Übergänge zu den Themen verfasst werden. Außerdem würde ich die Überschriften anders gliedern, z.B #Wichtige Projekte, ## Das GPM Flüchtlingsprojekt, ## YOUNG CREW
Der Artikel enthält oftmals unnötige Informationen, z.B den Satz: „Die aktuell gültige Version ICB 4.0 wurde 2015 von der IPMA veröffentlicht und wird seit Februar 2018 von der GPM in Deutschland genutzt.“ Meiner Meinung für einen kurz Artikel nicht relevant bzw. kann man auch kürzer fassen.
Leider enthält der Artikel wenig Erklärung zu den als Beispiel aufgeführten Projekten. Z.B im Kapitel „Das GPM Flüchtlingsprojekt“ fehlt, wie sich die Projektmanager im Projekt eingesetzt haben usw. Zusätzlich wurde dort ein komplett zusammenhangsloser Satz: „Herausfordernde Gegebenheiten können durch Projektmanagement, das strategisches und operatives Handeln fördert, einfacher gehandhabt werden. Für alle Beteiligten kann so das ideale Ergebnis mittels Methoden und unterschiedlichster Instrumente erzielt werden“, verwendet, der ohne Überleitung und Eingliederung in das Projekt für sich steht. 
Diskutierbar ist außerdem, ob es sinnvoll ist, dass der größte Themenblock die Auszeichnungen des Instituts ist. Meiner Meinung nach sollte das Vorgehen und das, was das Institut besonders macht bzw. revolutioniert, im Projektmanagement hervorgehoben werden.

2021-12-07 21:53 UTC, loritschka requested changes
**Review zu Aktuelle Entwicklungen im PM**

| Kriterium | Bewertung|
|-----|---|
| Front-Matter | ja |
| Umfang | ja |
| Belege | nein |
| Links | ja|
| Formatierung | ja|
| Verlinkungen vorhanden | ja |
| Abbildungen | ja |
| Strukturierung des Beitrags | 10 |
| Rechtschreibung | 9|
| Sprache | 9 |
| Inhalt |8|
| Einordnung in den Kontext |8|
| Ansprechend für Zielgruppe |9|

# Zusammenfassung
Das Thema des Artikels sind die aktuellen Entwicklungen im Projektmanagement. Der erste Teil erläutert die 7 Prinzipien von Projektmanagement 4.0, die Projektteams bei der Planung und Durchführung von erfolgreichen Projekten unterstützen sollen. Der zweite Teil beschäftigt sich mit aktuellen Trends im Bereich Projektmanagement und betont ihre Wichtigkeit für zukünftige Projekte.  

# Positive Aspekte
Der Artikel hat eine gute Struktur, sowie eine korrekte und übersichtliche Formatierung. Die Inhalte finde ich interessant und informativ. Besonders gut ist, dass es viele Verlinkungen zu anderen Beiträgen gibt.

# Negative Aspekte

Ein Verbesserungsvorschlag wäre Projektmanagement als kleine Einführung kurz zu definieren. Die Quellen könnten noch ein bisschen angepasst werden - die zweite und die dritte sind gleich und es ist keine Quelle zu der Abbildung angegeben. 
Du könntest noch etwas konkretes zu den Entwicklungen hinzufügen, wenn du weitere Informationen findest (vielleicht einen von den Trends als „Unterthema“ wählen und näher erläutern?). Dafür könntest du den ersten Abschnitt ein bisschen verkürzen (ist interessant, aber eher allgemein und hat mit Trends nichts zu tun). 
Es können noch kleine Verbesserungen in Bezug auf die Sprache gemacht werden. 
Beispiele:
-	Zeile 33: Es ist „Nährwert“ statt „Mehrwert“ versehentlich geschrieben.
-	Zeile 29: Der Satz klingt, meiner Meinung nach, etwas ungenau.






**Review zu GPM_Institution**

| Kriterium | Bewertung|
|-----|---|
| Front-Matter | ja |
| Umfang | ja |
| Belege | nein |
| Links | ja|
| Formatierung | ja|
| Verlinkungen vorhanden | ja |
| Abbildungen | ja |
| Strukturierung des Beitrags | 10 |
| Rechtschreibung |9|
| Sprache | 9 |
| Inhalt |9|
| Einordnung in den Kontext |10|
| Ansprechend für Zielgruppe |10|

# Zusammenfassung

Als Einführung stellt der Artikel die Institution GPM kurz vor. Im ersten Abschnitt wird auf die Geschichte, Ziele und Tätigkeiten eingegangen. Danach sind die Auszeichnungen, die GPM an Organisationen und Unternehmen verlieht, aufgelistet und erläutert. Der nächste Punkt sind die Studien, die entweder von der GPM selbst oder von anderen Organisationen durchgeführt werden. Hier ist eine konkrete Studie visuell dargestellt. Zum Schluss berichtet der Artikel von zwei Initiativen vom GPM – das zwischen 2015 und 2017 umgesetzte Flüchtlingsprojekt und die GPM Young Crew, die junge Projektmanager vernetzt. 

# Positive Aspekte

Der Artikel behandelt kurz viele wichtige Aspekte. Dadurch bekommt man einen sehr guten Überblick über das Thema. Ich finde es besonders gut, dass konkrete Beispiele aus der Tätigkeit der GPM genannt sind (Das Flüchtlingsprojekt und die GPM Young Crew). Der Artikel ist übersichtlich und gut strukturiert.

# Negative Aspekte

Die Informationen über die Studien finde ich ein bisschen zu knapp. Vielleicht könntest du noch etwas dazu schreiben. Die Abbildung würde ich kurz erläutern. Für mich persönlich wäre es interessant mehr über die Tätigkeiten von GPM Young Crew zu erfahren – weiterführende Literatur dazu wäre super. Es wurde keine Quelle zu der Abbildung genannt.
Zeile 41: Es gibt einen kleinen Fehler in dem Satz.
Zeile 59: Der letzte Satz lässt sich etwas schwer lesen bzw. verstehen. Kann meiner Meinung nach verkürzt werden. 

Sonst alles super 💯

2021-12-09 19:41 UTC, merged