Cynefin Framework und Projektmanagement für Circular Economy
ManagingProjectsSuccessfully/ManagingProjectsSuccessfully.github.io pull request #252
Opened 2021-11-24 09:59 UTC by 5SY5

2021-11-29 19:27 UTC, JanBaumgart requested changes
# Bewertung Cynefin-Framework

| Kriterium | Bewertung|
|-----|---|
| Front-Matter | ja |
| Umfang | ja|
| Belege | ja |
| Links | nein|
| Formatierung | ja|
| Verlinkungen vorhanden | nein |
| Abbildungen | ja |
| Strukturierung des Beitrags | 1-10 |
| Rechtschreibung | 1-10|
| Sprache | 1-10 |
| Inhalt | 1-10|
| Einordnung in den Kontext | 1-10|
| Ansprechend für Zielgruppe | 1-10|

# Zusammenfassung

Kurze Zusammenfassung des/der Artikel

# Positive Aspekte

Was ist gut (Bezug zur Tabelle)

# Negative Aspekte

Was geht besser (Bezug zur Tabelle)

2021-11-29 19:27 UTC, JanBaumgart requested changes
# Bewertung Projektmanagement_fuer_Circular_Economy

| Kriterium | Bewertung|
|-----|---|
| Front-Matter | ja |
| Umfang | nein|
| Belege | ja|
| Links | nein|
| Formatierung | ja|
| Verlinkungen vorhanden | nein |
| Abbildungen | ja |
| Strukturierung des Beitrags | 1-10 |
| Rechtschreibung | 1-10|
| Sprache | 1-10 |
| Inhalt | 1-10|
| Einordnung in den Kontext | 1-10|
| Ansprechend für Zielgruppe | 1-10|

# Zusammenfassung

Kurze Zusammenfassung des/der Artikel

# Positive Aspekte

Was ist gut (Bezug zur Tabelle)

# Negative Aspekte

Was geht besser (Bezug zur Tabelle)

2021-12-04 19:33 UTC, pu79xube reviewed
| Kriterium | Bewertung|
|-----|---|
| Front-Matter | ja |
| Umfang | ja |
| Belege | ja |
| Links | ja |
| Formatierung | ja |
| Verlinkungen vorhanden | ja |
| Abbildungen | ja |
| Strukturierung des Beitrags | 9 |
| Rechtschreibung | 10 |
| Sprache | 9 |
| Inhalt | 10 |
| Einordnung in den Kontext | 9 |
| Ansprechend für Zielgruppe | 9 |

# Zusammenfassung

Die kurze Beschreibung und Definition führen in das Thema ein. 
Durch eine Abbildung wird auf die 4 Hauptdomänen des Cynefin-Frameworks eingingen und übergeleitet. Diese werden im anschließenden genauer erläutert und erklärt. 
Nächster Punkt sind die Probleme des Frameworks, welche auch durch eine Abbildung unterstützt werden. 

Mithilfe einer Tabelle werden die Anwendungen( Anwendungstipps) auf Projekte genauer dargestellt.

Abschließend wird ein Fazit gezogen und mit einem Zitat untermauert. Und die Aussage des Artikels untermauert. 



# Positive Aspekte

Besonders gut gefällt mir die Struktur sowie die Abbildungen ( diese sind sehr gut gewählt ). Sie unterstützen bildlich bei dem Verständnis der einzelnen Hauptdomänen. 

Die Grammatik sowie die Rechtschreibung sind ausgezeichnet ( habe keinen Fehler gefunden )  

Auch die Tabelle hilft stark beim Verständnis und die Quellen sind sehr gut dargelegt. 


Alles in allem der beste Beitrag den ich gelesen habe ( * Daumen hoch *) 




# Negative Aspekte

Meiner Meinung nach gibt es nicht viel auszusetzen. Eines der wenigen Mankos ist für mich das Fazit, welches zu viele " neue Informationen" enthält.
Übersichtshalber würde ich die Verlinkung aus der Tabelle nehmen ( Zeile 81) 
( Hat meinen Fokus sehr auf die Verlinkung und weg von der Tabelle gelenkt) 

UND  Zeile 101 Arbeitsauftrag ..> nicht Aurbeitsauftrag ( einziger Fehler den ich finde) 

Ansonsten wirklich SUPER !

2021-12-07 22:35 UTC, loritschka requested changes
**Review zu Cynefin-Framework**

| Kriterium | Bewertung|
|-----|---|
| Front-Matter | ja |
| Umfang | ja |
| Belege | nein |
| Links | nein|
| Formatierung | ja|
| Verlinkungen vorhanden | ja |
| Abbildungen | ja |
| Strukturierung des Beitrags | 10 |
| Rechtschreibung |10|
| Sprache | 10 |
| Inhalt |10|
| Einordnung in den Kontext |10|
| Ansprechend für Zielgruppe |10|

# Zusammenfassung
Der Artikel setzt sich mit dem Thema Cynefin-Framework auseinander. Es wird zunächst erklärt was das Cynefin-Framework ist und womit sich das Modell beschäftigt. Im ersten Abschnitt werden die fünf Problemdomänen des Frameworks beschrieben. Als nächstes geht der Autor auf die Probleme des Frameworks ein. Zum Schluss werden die vier Vorgehensweisen des Cynefin Frameworks erläutert, sowie Beispiele dazu gegeben. 

# Positive Aspekte
Der Artikel ist gut strukturiert und verschafft einen guten Überblick über die Thematik. Durch die zwei Abbildungen und die Tabelle sind die Inhalte sehr übersichtlich veranschaulicht, was das Lesen und das Verständnis erleichtert. Ich finde es besonders gut, dass es wissenschaftliche Literatur verwendet wird. 

# Negative Aspekte
Es gibt meiner Meinung nach nicht viel zu kritisieren. Meine Tipps zur Verbessrung wären:
-	Quellen zu den Abbildungen angeben. Es gibt zwar Links, aber nicht zu der tatsächlichen 
        Quellen, sondern zu dem Ordner im GitHub, wo die Abbildungen hochgeladen sind. 
-	Vielleicht könntest du die weiterführende Literatur noch verlinken, damit man sie schnell 
        öffnen kann ohne zu suchen. 
-	Der Link „Arbeitsauftrags“ im Fazit funktioniert nicht. 


**Review zu Circular Economy**

| Kriterium | Bewertung|
|-----|---|
| Front-Matter | ja |
| Umfang | ja |
| Belege | nein |
| Links | nein|
| Formatierung | ja|
| Verlinkungen vorhanden | ja |
| Abbildungen | ja |
| Strukturierung des Beitrags | 10 |
| Rechtschreibung |10|
| Sprache | 10 |
| Inhalt |9|
| Einordnung in den Kontext |9|
| Ansprechend für Zielgruppe |9|

#Zusammenfassung
Der Artikel befasst sich mit dem Thema Circular Economy. Als Einführung erklärt der Autor was darunter zu verstehen ist und welche Hauptziele sie verfolgt. Der erste Abschnitt nennt und beschreibt die drei Grundsätze der Circular Economy, die auf umweltfreundliche und effiziente Nutzung von Ressourcen fokussiert sind. Als nächstes werden Denkansätze zur Circular Economy erläutert. Zum Schluss werden die Vorteile für die Umwelt und Unternehmen, die einer Kreislaufwirtschaft mit sich bringt, genannt. 

#Positive Aspekte
Der Artikel hat eine übersichtliche Struktur und passende Formatierung. Die Abbildungen sind gut und erleichtern den Leser beim Aufnehmen der Inhalte. Man bekommt ein gutes erstes Verständnis über das Thema, da der Artikel die wichtigsten Aspekte der Kreislaufwirtschaft behandelt. Durch die zur Verfügung gestellte weiterführende Literatur, sowie Verlinkungen zu anderen Beiträgen, kann das Thema noch vertieft werden. 

#Negative Aspekte
Die ersten zwei Verbesserungsvorschläge sind wie bei deinem anderen Artikel. Es fehlen die Quellen zu den Abbildungen (nur die GitHub Ordner mit den hochgeladenen Bildern sind verlinkt) und die weiterführende Literatur könnte noch verlinkt werden. Ein weiterer Tipp wäre die Circular Economy etwas mehr auf Projektmanagement zu beziehen, wenn du Informationen dazu findest. Und die Verlinkung „Ressourcen“ in Zeile 76 funktioniert nicht.

2021-12-09 19:41 UTC, merged