Risikobewertung von Umweltrisiken
ManagingProjectsSuccessfully/ManagingProjectsSuccessfully.github.io pull request #253
Opened 2021-11-24 10:00 UTC by loritschka

2021-11-29 16:59 UTC, JanBaumgart requested changes
| Kriterium | Bewertung|
|-----|---|
| Front-Matter | ja|
| Umfang | ja|
| Belege | ja |
| Links | ja |
| Formatierung | ja|
| Verlinkungen vorhanden | ja |
| Abbildungen | ja |
| Strukturierung des Beitrags | 9 |
| Rechtschreibung | 7 |
| Sprache | 7 |
| Inhalt | 9 |
| Einordnung in den Kontext | 6 |
| Ansprechend für Zielgruppe | 7 |

# Zusammenfassung

Der Artikel befasst sich mit der Identifizierung, Auseinandersetzung und Umgang mit verschiedenen Arten von Umweltrisiken. Zuerst wird in einer Einleitung ein Überblick über verschiedene Risikoarten gegeben um die Identifikation zu erleichtern. Daraufhin wird auf einen der 4 Risikoarten übergeleitet und in die Hauptthematik eingeführt indem die Umweltrisiken weiter aufgespalten und -gegliedert werden, in "interne Risiken" und "externe Risiken". Abgerundet wird dieser Abschnitt mit einer übersichtlichen Abbildung. In folge dessen werden Wege zur Bewertung und Analyse von Umweltrisiken aufgezeigt und erläutert. Zum Schluss wird noch auf die Maßnahmen zur Vermeidung und Minimierung von Umweltrisiken eingegangen.
Abseits des Inhalts werden zum Schluss noch weitere Lesetipps und ähnliche Beiträge, sowie die Quellen, verlinkt.

# Positive Aspekte

Der Artikel hat mit Augenmerk auf das Ziel von 500 Wörtern (es sind ca. 540 ohne Überschriften) einen inhaltlich sehr gute Zusammenfassung der Thematik der Umweltrisiken gegeben. Die Strukturierung wies einen Roten Faden mit einer sauberen Einleitung und einem klaren Schluss mit Handlungsempfehlungen auf. Die Sprache  war im Grunde angemessen und in Ordnung. Rechtschreibung wies keine groben Verstöße beim lesen auf. Besonders gut fand ich die Abbildung welche sehr simpel aber effektiv den 2. Abschnitt zusammenfasst.

# Negative Aspekte

Der Artikel hätte zu Beginn einmal den Titel beinhalten können um einen direkten Blick zur Einordnung zu Geben. Zudem sind kleinere Grammatik-"Fehler" enthalten, Bsp. im 2. Satz des 2. Abschnitts hätte ich es als schöner empfunden wenn "[...] IN Folge unternehmerischer Tätigkeit [...]" genutzt worden wäre. Ist zwar nicht Falsch, aber in meinen Augen etwas sehr umgangssprachliches Deutsch für einen Artikel. Zudem sind 1 - 2 Sätze enthalten die sich etwas lang ziehen und 4x mit einem Komma getrennt werden, hier könnte man es zur Vereinfachung beim lesen simpler halten und die Sätze etwas strukturieren.
Die Sprache ist, wie gesagt, angemessen aber um das maximale raus zu holen kann bei einem Artikel wie diesem auch mal der ein oder andere Fachbegriff extra eingebaut werden, also nur als Tipp ;).
Abbildung fand ich super, aber gerade deswegen fände ich beim 3. Abschnitt eine Abbildung, welche die Analysen kurz bildlich beschreibt, super.
Bei der Einordnung in unser Hauptthema "Projektmanagement" fehlt es mir etwas am Bezug. im ganzen Artikel wird nur ein einziges mal das Wort "Projekt" genutzt, inhaltlich also etwas zu stark abgegrenzt. Bei der Zielgruppe ebenso, das Thema der Umweltrisiken wird zwar gut aufgegriffen, aber es fehlt nun mal am Projekt-Aspekt.  
Versuche außerdem noch mehr Verlinkungen im Text zu anderen Beiträgen zu finden und einzubauen, auch wieder zum Stichpunkt "Projektkontext".

2021-12-04 18:55 UTC, pu79xube requested changes
| Kriterium | Bewertung|
|-----|---|
| Front-Matter | ja |
| Umfang | ja |
| Belege | ja |
| Links | ja |
| Formatierung | ja |
| Verlinkungen vorhanden | ja |
| Abbildungen | ja |
| Strukturierung des Beitrags | 9 |
| Rechtschreibung | 8 |
| Sprache | 7 |
| Inhalt | 8 |
| Einordnung in den Kontext | 9 |
| Ansprechend für Zielgruppe | 8 |

# Zusammenfassung

Das Thema des Artikels ist die Risikobewertung der Umweltrisiken von Unternehmen. Der Artikel beschäftigt sich besonders mit den internen sowie externen Umweltrisiken. Im folgenden wird weiter auf die Bewertung und Analyse von Umweltrisiken eingegangen. 
Das ganze wird des Weiteren durch ein Bild anschaulich verdeutlicht. 

# Positive Aspekte

Besonders gut ist die deutliche Aufteilung in interne und externe Umweltrisiken. des Weiteren finde ich, dass das Schaubild sehr gut gewählt ist und gut das Thema beschreibt und erklärt.

Durch die  sehr gute Strukturierung bleibt man gut im Thema und versteht ohne viel zu überlegen was gemeint ist und auf was sich bezogen wird. 

Orthographisch und Grammatikalisch ist der Beitrag auch gut, mir sind keine drastischen Verstöße aufgefallen. 

Alles in allem ein sehr guter Beitrag, da besonders auf die Unternehmerische Sicht ( Finanzen, Chancen und Risiken) eingegangen wird. 

# Negative Aspekte

Was mir als erstes ins Auge gesprungen ist, sind die Aufzählungen ( Zeile 22 sowie 23), 
welche etwas kürzer gefasst werden könnten. ( Mag ich persönlich einfach nicht :D )


Des Weiteren wird durch die häufigen Relativsätze das lesen erschwert. 
--> Meiner Meinung nach lieber kurze Sätze. 

Den Absatz : "Identifizierung und Bewertung " hätte ich optisch etwas mehr gegliedert ( Absatz/Absätze oder z.B. durch eine Weitere Abbildung

Nächster Punkt ist die Kommasetzung, wie z.B. in Zeile 86( Eine Maßnahme zur Meinung ..... , ist ....)

2021-12-06 10:22 UTC, annaflbr requested changes
| Kriterium | Bewertung|
|-----|---|
| Front-Matter | ja |
| Umfang | ja|
| Belege | nein | 
| Links | ja|
| Formatierung | ja|
| Verlinkungen vorhanden | ja |
| Abbildungen | ja |
| Strukturierung des Beitrags | 7 |
| Rechtschreibung | 9|
| Sprache | 8 |
| Inhalt | 10|
| Einordnung in den Kontext | 10|
| Ansprechend für Zielgruppe | 9|

# Zusammenfassung
Der Artikel beschäftigt sich mit der Risikobewertung von Umweltrisiken und geht hierbei zunächst auf verschiedene Risikoarten ein. Anschließend werden die Arten von Umweltrisiken näher beleuchtet und hierbei vor allem der Unterschied zwischen der internen und externen Perspektive beleuchtet. Anschließend behandelt der Artikel die Identifizierung und Bewertung von Umweltrisiken, hierbei steht vor Allem die Planung von Gegenmaßnahmen und die frühzeitige Erkennung im Vordergrund. Zuletzt geht der Artikel auf Maßnahmen zur Vermeidung und Minimierung von Umweltrisiken ein. 

# Positive Aspekte
Besonders gut finde ich den klaren Bezug zum Thema Projektmanagement, der im ganzen Artikel ersichtlich ist. Zudem weist der Artikel so gut wie keine Rechtschreibfehler auf.
Das Schaubild ist sehr ansprechend und passend gewählt. Der Unterschied von externen und internen Risiken wird hier gut verdeutlicht und ist gut in den Artikel mit eingebunden
 
# Negative Aspekte
Ich würde mit in dem Artikel etwas mehr Struktur durch beispielsweise Unterüberschriften wünschen, da der Artikel fast ausschließlich aus Fließtext besteht. Unterüberschriften bieten sich zum Beispiel gut bei dem Thema interne und externe Risiken an. 
Teilweise sind die Sätze etwas verschachtelt und der Zusammenhang der Aussagen wird nicht wirklich deutlich (Beispielsweise bei „Die Fehlerbaumanalyse…)

Am Ende des zweiten Absatzes wirken die Sätze sehr aneinandergereiht, ohne sich strukturell zu ergänzen:
(„ Die Bewertung ist oft komplex und mit Schwierigkeiten verbunden, weil die Umweltrisiken nicht vorhersehbar sind. Zuerst wird die Eintrittswahrscheinlichkeit und die damit verbundenen Schäden für die Umwelt bzw. das Unternehmen abgeschätzt, um die finanziellen Folgen beziffern zu können. Bei der Umweltrisikobewertung erhält man eine Schadensumverteilung, die angibt, mit welcher Wahrscheinlichkeit ein Schaden einen bestimmten Wert übersteigt“) 

Leider fehlt bei der Abbildung die Bildquelle.

2021-12-09 19:41 UTC, merged

2021-12-21 19:19 UTC, loritschka commented
Vielen Dank für die Verbesserungsvorschläge!

Ich habe den Titel und noch eine Abbildung im zweiten Abschnitt eingefügt. Es gab keine Quelle zu der ersten Abbildung, weil ich sie beide selbst erstellt habe. (ist jetzt in den Quellenverzeichnis vermerkt). 

Der Artikel hat ein paar neue Unterüberschriften, welche die Struktur verbessern. Außerdem habe ich manche Sätze verkürzt und versucht die Sprache zu verbessern. 

Bezüglich der Einordnung in das Hauptthema. Meiner Meinung nach hat der Artikel einen guten Bezug zum Projektmanagement. Wenn Projekte mit Umweltrisiken verbunden sind, sollte das Management entsprechend mit diesen umgehen. Im Artikel geht es um die erforderlichen Schritte zur Bewertung bzw. Minimierung von Umweltrisiken (Identifizierung --> Bewertung --> Treffen von Maßnahmen)