Rollen-klassisch
ManagingProjectsSuccessfully/ManagingProjectsSuccessfully.github.io pull request #258
Opened 2021-11-24 11:00 UTC by greifchristina

2021-12-03 18:14 UTC, TimSchwehn requested changes
Kriterium | Bewertung|
|-----|---|
| Front-Matter | ja|
| Umfang | ja|
| Belege | ja |
| Links | nein|
| Formatierung | ja|
| Verlinkungen vorhanden | ja|
| Abbildungen | ja|
| Strukturierung des Beitrags | 9 |
| Rechtschreibung | 8|
| Sprache | 8 |
| Inhalt | 10|
| Einordnung in den Kontext | 10|
| Ansprechend für Zielgruppe |10|

# Zusammenfassung

Der Artikel beschreibt die unterschiedlichen und vielfältigen Rollen innerhalb eines Projektes. Für mich stellt der Artikel einen generalistischen Überblick über die Projektrollen dar und gibt eine gute Übersicht über die Thematik, ohne zu sehr in die Tiefe zu gehen. Zunächst werden die einzelnen Rollen kurz vorgestellt, bevor detaillierter auf die jeweiligen Aufgaben- und Kompetenzbereiche eingegangen wird. Dazu werden zu jedem Bereich die wichtigsten Aspekte zusammengefasst. Für einen detaillierten Überblick enthält der Artikel Verlinkungen zu den entsprechenden Themengebieten. Abschließend wird mit dem Thema Multiprojektmanagement der Blickwinkel vergrößert und mögliche Erweiterungen aufgezeigt. 

# Positive Aspekte

Besonders gut gefällt mir der inhaltliche Aufbau des Artikels. Es ist eine klare Struktur und eine Gliederung erkennbar. Der / die Lesende wird gut abgeholt und in das Thema eingeführt. Der Artikel ist ansprechend gestaltet und macht Spaß zu lesen. Die wichtigsten Projektrollen werden eingeführt und gut beschrieben. Besonders gefällt mir, dass der Artikel die vielfältigen Schnittstellen zu anderen Bereichen betrachtet und das Thema in einen großen Kontext einordnet. Durch die große Anzahl von Verlinkungen erhält der/die Lesende einen guten Überblick über die Thematik und hat die Möglichkeit, direkt weiterführende Themen zu betrachten. 

# Negative Aspekte
- Link zu Qualitätssicherung funktioniert nicht, Qualitätsziele verlinkt auf Qualitätssicherung
- Sprachlich kann der Artikel an der ein oder anderen Stelle ausgebessert werden. 
Der Genitiv zu Projekt wird unterschiedlich verwendet (Projekts, Projektes) => besser für den Lesefluss wäre hier Einheitlichkeit
- In manchen Überschriften ist ein Doppelpunkt, welchen ich rausstreichen würde. 
- Projektleiter: "...ein Projektleiter verschiedene Kompetenzen..."
- Projektteam: "... das Projektteam besteht aus verschiedenen Mitarbeitern, die für die im Projekt benötigten... Dabei werden von verschiedenen..."
- Projektteam: " der finanziellen Mitteln als auch..."

2021-12-06 17:00 UTC, HAhmedFAU commented
| Kriterium | Bewertung|
|-----|---|
| Front-Matter | ja |
| Umfang | ja |
| Belege | ja |
| Links | ja |
| Formatierung | ja |
| Verlinkungen vorhanden | ja |
| Abbildungen | nein |
| Strukturierung des Beitrags | 9 |
| Rechtschreibung | 9 |
| Sprache | 9 |
| Inhalt | 10 |
| Einordnung in den Kontext | 10 |
| Ansprechend für Zielgruppe | 10 | 

# Zusammenfassung

In diesem Artikel werden die verschiedenen Rollen in einem Projekt beschrieben. Beginnend mit den einzelnen Rollen werden diese mit den wichtigsten Informationen beschrieben und dementsprechend mit den Aufgaben und Verantwortlichkeiten ausgeführt. Zudem wird am Ende das Multiprojektmanagement erwähnt um das Thema etwas zu erweitern.

# Positive Aspekte

Positiv an diesem Text fand ich persönlich die Strukturierung der einzelnen Rollen. Dadurch, dass die Rollen nacheinander aufgezählt wurden und die wichtigsten Elemente erwähnt wurden, konnte ich als Leser gut mitkommen. Des Weiteren fand ich die Erweiterung durch das Multiprojektmanagement gut, da man so etwas mehr zum Thema aufnehmen konnte und nicht nur eine Aufzählung von den Rollen zum normalen Projekt hatte. Zum Schluss fiel mir der Wiederaufgriff von der Einleitung positiv auf und hat somit eine gute Rundung zum Text gebracht.

# Negative Aspekte

- Vielleicht mehr Abbildungen
- Punkte in der Überschrift

2021-12-07 13:33 UTC, nikl9 requested changes
| Kriterium | Bewertung|
|-----|---|
| Front-Matter | ja |
| Umfang | ja |
| Belege | ja |
| Links | ja |
| Formatierung | ja |
| Verlinkungen vorhanden | ja |
| Abbildungen | ja |
| Strukturierung des Beitrags | 10 |
| Rechtschreibung | 8 |
| Sprache | 9 |
| Inhalt | 10|
| Einordnung in den Kontext | 10|
| Ansprechend für Zielgruppe | 10|

# Zusammenfassung

Der Artikel befasst sich mit den verschiedenen Rollen innerhalb eines Projektes. Es werden die verschiedenen Rollen aufgezählt und eine Abbildung gibt einen kurzen Überblick über diese. Anschließend werden die einzelnen Rollen erklärt, indem zu jedem Bereich die wichtigsten Bereiche zusammengetragen werden. Eine Erweiterung durch das Multiprojektmanagement schließt den Artikel ab. 

# Positive Aspekte

Der Artikel ist sehr gut strukturiert aufgebaut. Mir gefällt besonders, dass der Artikel allgemein gehalten ist und so unnötig Informationen weggelassen werden. Die einzelnen Rollen werden kurz und prägnant erklärt, wodurch der Leser schnell und leicht verstehen kann um was es geht. Das einbeziehen anderer Artikel durch entsprechende Verlinkungen stellt ebenfalls eine positiven Aspekt dar.

# Negative Aspekte

* Projektteam: fehlendes Leerzeichen zwischen "... verschiedenen Mitarbeitern,..."
* Projektteam: sprachlicher Fehler bei "... der finanziellen Mittel als auch..."

2021-12-07 14:37 UTC, HAhmedFAU requested changes
| Kriterium | Bewertung|
|-----|---|
| Front-Matter | ja |
| Umfang | ja |
| Belege | ja |
| Links | ja |
| Formatierung | ja |
| Verlinkungen vorhanden | ja |
| Abbildungen | ja |
| Strukturierung des Beitrags | 9 |
| Rechtschreibung | 9 |
| Sprache | 9 |
| Inhalt | 10 |
| Einordnung in den Kontext | 10 |
| Ansprechend für Zielgruppe | 10 | 

# Zusammenfassung

In diesem Artikel werden die verschiedenen Rollen in einem Projekt beschrieben. Beginnend mit den einzelnen Rollen werden diese mit den wichtigsten Informationen beschrieben und dementsprechend mit den Aufgaben und Verantwortlichkeiten ausgeführt. Zudem wird am Ende das Multiprojektmanagement erwähnt um das Thema etwas zu erweitern.

# Positive Aspekte

Positiv an diesem Text fand ich persönlich die Strukturierung der einzelnen Rollen. Dadurch, dass die Rollen nacheinander aufgezählt wurden und die wichtigsten Elemente erwähnt wurden, konnte ich als Leser gut mitkommen. Des Weiteren fand ich die Erweiterung durch das Multiprojektmanagement gut, da man so etwas mehr zum Thema aufnehmen konnte und nicht nur eine Aufzählung von den Rollen zum normalen Projekt hatte. Zum Schluss fiel mir der Wiederaufgriff von der Einleitung positiv auf und hat somit eine gute Rundung zum Text gebracht.

# Negative Aspekte

- Wenige Abbildungen

2021-12-09 19:41 UTC, merged

2021-12-12 18:59 UTC, greifchristina commented
Hallo @HAhmedFAU ,
danke für dein Feedback. Könntest du mir vielleicht sagen, was dir bei dem Bild angezeigt wird, da du ja schreibst das es nicht funktioniert. Das irritiert mich nämlich ein wenig, da die beiden anderen Reviewer bei Bild ja geschrieben haben und ich das so interpretiere, dass es bei ihnen funktioniert.
Danke.

2021-12-14 11:03 UTC, HAhmedFAU commented
> Hallo @HAhmedFAU , danke für dein Feedback. Könntest du mir vielleicht sagen, was dir bei dem Bild angezeigt wird, da du ja schreibst, dass es nicht funktioniert. Das irritiert mich nämlich ein wenig, da die beiden anderen Reviewer bei Bild ja geschrieben haben und ich das so interpretiere, dass es bei ihnen funktioniert. Danke.

Alles gut, da hat bei mir etwas nicht gestimmt. 
Ich sehe die Abbildung ganz normal, habe es überarbeitet.

2021-12-14 12:08 UTC, greifchristina commented
> > Hallo @HAhmedFAU , danke für dein Feedback. Könntest du mir vielleicht sagen, was dir bei dem Bild angezeigt wird, da du ja schreibst, dass es nicht funktioniert. Das irritiert mich nämlich ein wenig, da die beiden anderen Reviewer bei Bild ja geschrieben haben und ich das so interpretiere, dass es bei ihnen funktioniert. Danke.
> 
> Alles gut, da hat bei mir etwas nicht gestimmt. Ich sehe die Abbildung ganz normal, habe es überarbeitet.

ok, danke