Storytelling
ManagingProjectsSuccessfully/ManagingProjectsSuccessfully.github.io pull request #264
Opened 2021-11-24 12:26 UTC by aculsalocin

2021-12-06 20:11 UTC, SaskiaHe requested changes
| Kriterium | Bewertung|
|-----|---|
| Front-Matter | ja|
| Umfang | ja|
| Links | ja|
| Formatierung | ja|
| Verlinkungen vorhanden |nein |
| Abbildungen | ja |
| Strukturierung des Beitrags | 10 |
| Rechtschreibung |10|
| Sprache | 10 |
| Inhalt | 10|
| Einordnung in den Kontext | 5|
| Ansprechend für Zielgruppe | 10|

# Zusammenfassung 

Der Artikel beschreibt wie man die Erzählmethode Storytelling im Projektmanagement gut einbinden kann. Außerdem wird daraufhin auf die einzelnen Phasen des Storytellings im Projektmanagement eingegangen. 

# Positive Aspekte

Der Einleitungssatz ist super gelungen. 
Der Aufbau ist gut, man kommt vom allgemeinen hin zu detaillierteren Aussagen. Es wird immer mehr in das Thema eingetaucht. 
Die Grafik ist verständlich und hilft es nachvollziehen zu können.
Sprache, Rechtschreibung und Formatierung sind top.

# Negative Aspekte

Nur eine kleine Anmerkung, es sind keinerlei andere Beiträge verlinkt, eventuell könntest du da noch ein oder zwei hinzufügen.
Und du gehst erst relativ spät auf die Grafik ein, vielleicht könntest du das irgendwie mehr miteinander verbinden.

2021-12-07 08:48 UTC, aculsalocin commented
Hey,
vielen Dank für dein Feedback, das nehme ich mir zu Herzen und überlege was ich verbessern kann. Zu den zwei r im Front-Matter. Das ist von Martin, ich hab daran nichts geändert, aber ja ich spreche das nochmal an. Nur eine Frage, warum genau hast du "1" bei Einordnung in den Kontext eingetragen? Wegen den fehlenden verlinkten Artikeln? Da zu "Einordnung" auch sowas gehört, wie textuelle Beschreibung wo das Thema einzuordnen ist, etc., weil das hab ich ja. Trotzdem vielen Dank!

2021-12-07 08:58 UTC, SaskiaHe commented
Hey, 
ah okay sorry klar, es fehlen ja nur die Verlinkungen.
Dann änder ich das mal um ich dachte das bezieht sich nur auf die Verlinkungen.

2021-12-07 20:03 UTC, creepol requested changes
| Kriterium | Bewertung|
|-----|---|
| Front-Matter | ja|
| Umfang | ja|
| Belege | ja|
| Links | ja|
| Formatierung | ja|
| Verlinkungen vorhanden | nein|
| Abbildungen | ja|
| Strukturierung des Beitrags | 10 |
| Rechtschreibung | 10|
| Sprache | 10 |
| Inhalt | 10|
| Einordnung in den Kontext |7|
| Ansprechend für Zielgruppe | 9|

# Zusammenfassung

Der Artikel befasst sich mit Storytelling im Bereich des Projektmanagements. Mithilfe von Storytelling wird im Projektmanagement versucht, die Motivation der Mitarbeiter durch eine Geschichte, welche den tieferen Sinn des Projekts verdeutlicht, zu erhöhen. Im weiteren Verlauf des Artikels wird der Aufbau einer guten Geschichte beschrieben.

# Positive Aspekte

Mir gefällt die Einleitung mit dem Zitat wirklich gut. Inhaltlich ist der Artikel auch sehr gut gelungen, der Text ist gut lesbar und verständlich. Außerdem hat der Artikel eine klare Struktur durch Absätze und gut gesetzte Überschriften. Die Abbildung ist klar und verständlich.

# Negative Aspekte

Verlinkungen zu anderen Themengebieten fehlen leider. Da vielleicht noch welche einfügen. Die Graphik könnte noch etwas mehr in den Text integriert werden.

2021-12-09 19:41 UTC, merged

2021-12-10 10:04 UTC, flxrbnk commented
<html>
<body>
<!--StartFragment-->
Sorry für die verspätete Review :-)

Kriterium | Bewertung
-- | --
Front-Matter |          ja
Umfang | ja
Links | ja
Formatierung | ja
Verlinkungen vorhanden | nein
Abbildungen | ja
Strukturierung des Beitrags | 10
Rechtschreibung | 10
Sprache | 10
Inhalt |  10
Einordnung in den Kontext | 8
Ansprechend für Zielgruppe | 10

<h1 dir="auto" style="box-sizing: border-box; font-size: 2em; margin: 24px 0px 16px; font-weight: 600; line-height: 1.25; padding-bottom: 0.3em; border-bottom: 1px solid var(--color-border-muted); color: rgb(36, 41, 47); font-family: -apple-system, BlinkMacSystemFont, &quot;Segoe UI&quot;, Helvetica, Arial, sans-serif, &quot;Apple Color Emoji&quot;, &quot;Segoe UI Emoji&quot;; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">Zusammenfassung</h1><p dir="auto" style="box-sizing: border-box; margin-top: 0px; margin-bottom: 16px; color: rgb(36, 41, 47); font-family: -apple-system, BlinkMacSystemFont, &quot;Segoe UI&quot;, Helvetica, Arial, sans-serif, &quot;Apple Color Emoji&quot;, &quot;Segoe UI Emoji&quot;; font-size: 14px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">Der Beitrag informiert über das Storytelling im Kontext von Projektmanagement. Es wird erklärt, was das Ziel des Storytellings ist und welche Elemente Bestandteil von Geschichten sein sollten. </p><h1 dir="auto" style="box-sizing: border-box; font-size: 2em; margin: 24px 0px 16px; font-weight: 600; line-height: 1.25; padding-bottom: 0.3em; border-bottom: 1px solid var(--color-border-muted); color: rgb(36, 41, 47); font-family: -apple-system, BlinkMacSystemFont, &quot;Segoe UI&quot;, Helvetica, Arial, sans-serif, &quot;Apple Color Emoji&quot;, &quot;Segoe UI Emoji&quot;; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">Positive Aspekte</h1><p dir="auto" style="box-sizing: border-box; margin-top: 0px; margin-bottom: 16px; color: rgb(36, 41, 47); font-family: -apple-system, BlinkMacSystemFont, &quot;Segoe UI&quot;, Helvetica, Arial, sans-serif, &quot;Apple Color Emoji&quot;, &quot;Segoe UI Emoji&quot;; font-size: 14px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">Der Text ist leicht verständlich verfasst und führt angenehm in die Thematik ein. Beim Lesen bekommt man ein gutes Verständnis über das Thema.
</p><h1 dir="auto" style="box-sizing: border-box; font-size: 2em; margin: 24px 0px 16px; font-weight: 600; line-height: 1.25; padding-bottom: 0.3em; border-bottom: 1px solid var(--color-border-muted); color: rgb(36, 41, 47); font-family: -apple-system, BlinkMacSystemFont, &quot;Segoe UI&quot;, Helvetica, Arial, sans-serif, &quot;Apple Color Emoji&quot;, &quot;Segoe UI Emoji&quot;; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">Negative Aspekte</h1><p dir="auto" style="box-sizing: border-box; margin-top: 0px; margin-bottom: 0px !important; color: rgb(36, 41, 47); font-family: -apple-system, BlinkMacSystemFont, &quot;Segoe UI&quot;, Helvetica, Arial, sans-serif, &quot;Apple Color Emoji&quot;, &quot;Segoe UI Emoji&quot;; font-size: 14px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">Als kleiner Verbesserungsvorschlag: Würde statt "Durch..." nicht mehr das Wort "Innerhalb .... der Einführung der Kollegen und Mitarbeiter" passen?

Der Satz "Dadurch kann man deren intrinsische Motivation steigern, was sowohl für die Mentalität der Mitarbeiter förderlich ist, als auch diese produktiver arbeiten lässt" hört sich etwas schief an, vielleicht ohne "sowohl...als auch" Formulierung? 

Im Satz "Nun muss man den Kollegen den Projektprozess und die Projektdurchführung durch die Geschichte vermitteln" würde sich vielleicht "Als Nächstes" am Satzanfang besser anhören.</p><!--EndFragment-->
</body>
</html>

2021-12-10 15:41 UTC, flxrbnk commented
<html>
<body>
<!--StartFragment-->

Sorry für die verspätete Review (Im Form eines Kommentars) :-)
Kriterium | Bewertung
-- | --
Front-Matter | ja
Umfang | ja
Links | ja
Formatierung | ja
Verlinkungen vorhanden | nein
Abbildungen | ja
Strukturierung des Beitrags | 10
Rechtschreibung | 10
Sprache | 10
Inhalt | 10
Einordnung in den Kontext | 8
Ansprechend für Zielgruppe | 10

<h1 dir="auto" style="box-sizing: border-box; font-size: 2em; margin: 24px 0px 16px; font-weight: 600; line-height: 1.25; padding-bottom: 0.3em; border-bottom: 1px solid var(--color-border-muted); color: rgb(36, 41, 47); font-family: -apple-system, BlinkMacSystemFont, &quot;Segoe UI&quot;, Helvetica, Arial, sans-serif, &quot;Apple Color Emoji&quot;, &quot;Segoe UI Emoji&quot;; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">Zusammenfassung</h1><p dir="auto" style="box-sizing: border-box; margin-top: 0px; margin-bottom: 16px; color: rgb(36, 41, 47); font-family: -apple-system, BlinkMacSystemFont, &quot;Segoe UI&quot;, Helvetica, Arial, sans-serif, &quot;Apple Color Emoji&quot;, &quot;Segoe UI Emoji&quot;; font-size: 14px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">Der Beitrag informiert über das Storytelling im Kontext von Projektmanagement. Es wird erklärt, was das Ziel  des Storytellings ist und welche Elemente Bestandteil einer Geschichte sein sollten. 
</p><h1 dir="auto" style="box-sizing: border-box; font-size: 2em; margin: 24px 0px 16px; font-weight: 600; line-height: 1.25; padding-bottom: 0.3em; border-bottom: 1px solid var(--color-border-muted); color: rgb(36, 41, 47); font-family: -apple-system, BlinkMacSystemFont, &quot;Segoe UI&quot;, Helvetica, Arial, sans-serif, &quot;Apple Color Emoji&quot;, &quot;Segoe UI Emoji&quot;; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">Positive Aspekte</h1><p dir="auto" style="box-sizing: border-box; margin-top: 0px; margin-bottom: 16px; color: rgb(36, 41, 47); font-family: -apple-system, BlinkMacSystemFont, &quot;Segoe UI&quot;, Helvetica, Arial, sans-serif, &quot;Apple Color Emoji&quot;, &quot;Segoe UI Emoji&quot;; font-size: 14px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">Der Text ist leicht verständlich verfasst und führt angenehm in die Thematik ein. Beim Lesen kriegt mder Leser ein grundlegendes Verständnis über das Thema.<br style="box-sizing: border-box;"></p><h1 dir="auto" style="box-sizing: border-box; font-size: 2em; margin: 24px 0px 16px; font-weight: 600; line-height: 1.25; padding-bottom: 0.3em; border-bottom: 1px solid var(--color-border-muted); color: rgb(36, 41, 47); font-family: -apple-system, BlinkMacSystemFont, &quot;Segoe UI&quot;, Helvetica, Arial, sans-serif, &quot;Apple Color Emoji&quot;, &quot;Segoe UI Emoji&quot;; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">Negative Aspekte</h1><p dir="auto" style="box-sizing: border-box; margin-top: 0px; margin-bottom: 0px !important; color: rgb(36, 41, 47); font-family: -apple-system, BlinkMacSystemFont, &quot;Segoe UI&quot;, Helvetica, Arial, sans-serif, &quot;Apple Color Emoji&quot;, &quot;Segoe UI Emoji&quot;; font-size: 14px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"><br style="box-sizing: border-box;">Als kleinen Verbesserungsvorschlag, würde statt "Durch..." nicht mehr das Wort "Innerhalb ... der Einführung der Kollegen und Mitarbeiter" passen?
Der Satz "Dadurch kann man deren intrinsische Motivation steigern, was sowohl für die Mentalität der Mitarbeiter förderlich ist, als auch diese produktiver arbeiten lässt" hört sich etwas schief an, vielleicht ohne "sowohl...als auch" Formulierung? 
Im Satz "Nun muss man den Kollegen den Projektprozess und die Projektdurchführung durch die Geschichte vermitteln" würde am Satzanfang vielleicht "Als Nächstes" besser passen<br style="box-sizing: border-box;"></p><!--EndFragment-->
</body>
</html>