Action_Points und Megatrends
ManagingProjectsSuccessfully/ManagingProjectsSuccessfully.github.io pull request #267
Opened 2021-11-24 12:53 UTC by SaskiaHe

2021-11-30 19:16 UTC, Tjara1 requested changes
| Kriterium | Bewertung|
|-----|---|
| Front-Matter | ja |
| Umfang | ja |
| Belege | ja |
| Links | ja |
| Formatierung | ja |
| Verlinkungen vorhanden | ja |
| Abbildungen | ja |
| Strukturierung des Beitrags | 10 |
| Rechtschreibung | 10 |
| Sprache | 8 |
| Inhalt | 10 |
| Einordnung in den Kontext | 10 |
| Ansprechend für Zielgruppe | 10|

# Zusammenfassung

Bei komplexen Projekten ist es sinnvoll Teilprojekte und dazu wiederum untergliederte Arbeitspakete zu definieren. Diese werden als Action Points bezeichnet. Arbeitspakete enthalten Pläne für Kosten, Zeit und die Projektstruktur und werden jeweils von ausgewählten Personen betreut. Durch eine Abbildung wird das verdeutlicht. Im Projektstrukturplan bilden die Action Points die letzte Instanz.

# Positive Aspekte

Deine Abbildung ist toll gewählt. Sie gibt einen verständlichen Überblick und hat mir geholfen das Geschriebene besser nachvollziehen zu können. Außerdem ist es schön, dass Du mit viel Formatierungsmöglichkeiten gearbeitet hast. Das äußere Erscheinungsbild ist sehr ansprechend. Auch die Struktur und den Aufbau hast Du gelungen umgesetzt.

# Negative Aspekte

Manche Sätze fand ich ein wenig schwer zu verstehen. Beispielsweise "Bei der Prozent-Regel wird empfohlen, den Umfang des Arbeitspaketes von bis zu 5% des Gesamtprojektes nicht zu überschreiten.1 Dabei ergeben sich ca. 20 Arbeitspakete, welche eine gute Basis und Transparenz bilden."... Ich checke hier nicht, wie du auf 20 Arbeitspakete kommst, also von was rechnest Du die 5% ab? Vielleicht kannst Du darauf nochmal näher eingehen. Beim Projektstrukturplan hast du Stichpunkte eingefügt, zwei davon sind Links, einer nicht. Soll das so sein? -wirkt ein wenig uungewollt. Sonst ist echt alles Top!

2021-12-04 17:20 UTC, On11ybid requested changes
| Kriterium | Bewertung|
|-----|---|
| Front-Matter | ja |
| Umfang | ja|
| Belege | ja |
| Links | ja |
| Formatierung | ja |
| Verlinkungen vorhanden | ja |
| Abbildungen | ja |
| Strukturierung des Beitrags | 10 |
| Rechtschreibung | 10|
| Sprache | 7 |
| Inhalt | 9 |
| Einordnung in den Kontext | 10|
| Ansprechend für Zielgruppe | 10|

# Zusammenfassung

Der Artikel befasst sich mit dem Konzept der Action Points, welche auch unter dem Namen Arbeitspakete bekannt sind. Sie sind die kleinsten, nicht mehr untergliederbaren Einheiten in einem komplexen Projekt und beinhalten Pläne zur Kosten-, Zeit- und Projektstruktur. Die Arbeitspakete können von mehreren Personen abgearbeitet werden und von einer Person betreut werden, die im direkten Kontakt zum Teilprojektleiter steht.

# Positive Aspekte

Der Artikel ist inhaltlich sehr verständlich, was durch schönen Abbildungen nochmals bekräftigt wurde. Die farbigen und in guter größe formatierten Abbildungen und der sinnvoller Aufbau des Beitrages tragen gemeinsam zu einem attraktiven Erscheinungsbild bei.

# Negative Aspekte

Gewisse Sätze könnte man sprachlich besser formulieren durch Nutzung von Synonymen. Des weiteren würde ich beim Projektstrukturplan anfangs einen Satz anwenden der die Arbeitspakete direkt mit den Projektstrukturplan in Verbindung bringt.

2021-12-07 12:06 UTC, SaskiaHe commented
Hey ihr, 
danke für eure Reviews.
Ich wollte euch nur nochmal dran erinnern, dass es zwei Artikel sind. 
Action Points habt ihr ja schon gemacht, aber ich denke ich müsstet für Megatrends auch noch ein Review schreiben.
Danke :)

2021-12-07 14:07 UTC, jsk0lb requested changes
| Kriterium | Bewertung|
|-----|---|
| Front-Matter | ja/ nein |
| Umfang | ja/ nein|
| Belege | ja/ nein |
| Links | ja/ nein|
| Formatierung | ja/ nein|
| Verlinkungen vorhanden | ja/ nein |
| Abbildungen | ja/ nein |
| Strukturierung des Beitrags | 1-10 |
| Rechtschreibung | 1-10|
| Sprache | 1-10 |
| Inhalt | 1-10|
| Einordnung in den Kontext | 1-10|
| Ansprechend für Zielgruppe | 1-10|

# Zusammenfassung

Kurze Zusammenfassung des/der Artikel

# Positive Aspekte

Was ist gut (Bezug zur Tabelle)

# Negative Aspekte

Was geht besser (Bezug zur Tabelle)

2021-12-09 19:41 UTC, merged

2021-12-10 15:18 UTC, On11ybid reviewed
| Kriterium | Bewertung|
|-----|---|
| Front-Matter | ja |
| Umfang | ja|
| Belege | ja |
| Links | ja |
| Formatierung | ja |
| Verlinkungen vorhanden | ja |
| Abbildungen | ja |
| Strukturierung des Beitrags | 10 |
| Rechtschreibung | 10|
| Sprache | 9 |
| Inhalt | 9 |
| Einordnung in den Kontext | 9 |
| Ansprechend für Zielgruppe | 10|

# Zusammenfassung

Der Artikel befasst sich mit dem Konzept der Megatrends. Diese sind Veränderungen im Projektmanagement, mit denen sich ein Projektmanager auseinandersetzen muss. Der Projektmanager entschedeidet nach Relevanz der Projekt, welche er trotz dessen Herausforderungen weiterführen möchte. In globalen Angelegenheiten wie es im Zeit der Covid 19 Pandemie der Fall ist, sind viele Firmen Herausforderungen ausgeliefert um der weltweiten Maßnahmen gerecht zu handeln. Hier werden die Projektmanager gefragt. 

# Positive Aspekte

Der Artikel ist sprachlich wie auch inhaltlich sehr gut. Die schönen Abbildungen wurden sinnvoll gewählt und tragen zu einem attraktiven Erscheinungsbild bei. Die Punkte wurden sinnvoll gewählt und in richtiger Reihenfolge geordnet, sodass Sie eine guten Überblick über das Thema verschaffen. Des weiteren wurde richtig formartiert und auch Verlinkungen angegeben.

# Negative Aspekte

Quellen sollen Veröffentlichungsjahr beinhalten (Zitierstil beachten). Wieso wurden Gänsefüßchen bei den Überschriften benutzt? Manche Wörter kommen öfters vor, Synonyme sollten dir helfen bestimmte Sachen sprachlich besser zu erklären. Des weiteren fehlen bei den Abbildungen die Beschriftung.

2021-12-22 17:37 UTC, SaskiaHe commented
Danke für eure Kommentare, ich habe versucht diese alle umzusetzen.
Hoffe man kann mit dem einen Satz mehr das mit den 5% nun besser verstehen.
Habe auch mehrere Synonyme nun verwendet und nochmal auf Rechtschreibfehler geprüft.
:)