Netzplantechnik.md
ManagingProjectsSuccessfully/ManagingProjectsSuccessfully.github.io pull request #268
Opened 2021-11-24 12:57 UTC by On11ybid

2021-11-24 13:13 UTC, On11ybid commented
Tut mir leid für die vielen commits wovon einige echt unnötig waren -> z.B "Merge Pull Request", da ich unter Zeitdruck mal stand obwohl die Abgabe ja erst heute ist :D.

Lg
On11ybid

2021-12-01 07:27 UTC, Tjara1 requested changes
| Kriterium | Bewertung|
|-----|---|
| Front-Matter | ja |
| Umfang | ja |
| Belege | ja |
| Links | nein|
| Formatierung | ja |
| Verlinkungen vorhanden | nein |
| Abbildungen | ja |
| Strukturierung des Beitrags | 9 |
| Rechtschreibung | 10 |
| Sprache | 8 |
| Inhalt | 10|
| Einordnung in den Kontext | 10|
| Ansprechend für Zielgruppe | 10|

# Zusammenfassung

Bei der Netzplantechnik wird Das Projekt in einzelne Teilprojekte unterteilt, welche als Graph abegebildet werden können. Dabei unterscheidet man zwischen grundlegenden Abbildungsmöglichkeiten, dem Ereignisknoten, dem Vorgangspfeil und dem Vorgangsknoten-Netzplan. Mit der Netzplantechnik kann ein Überblick über den strukturellen Ablauf des Projekts gegeben werden. Aspekte wie die Zeit- und Kostenplanung spielen eine entscheidende Rolle.

# Positive Aspekte

Die Abbildungen sind gut gewählt, sie verdeutlichen die Thematik. Außerdem ist es gut, dass Du eine Stichpunktliste aufgeführt hast. Auch die Quellen sind gut in den Beitrag eingearbeitet. 

# Negative Aspekte

Ich hätte Deinen Beitrag anders Strukturiert. Ich hätte die Überschrift "Arten der Netzplantechnik" als erstes positioniert, danach deine Abbildung eingefügt und zum Schuss "Projektplanung der Netzplantechnik" aufgeführt. Zu Beginn fehlt mir ein wenig der Einstieg/ die Erklärung des Ganzen. Im ersten Satz von "Arten der Netzplantechnik" stimmt irgendwie der Satzbau nicht, vielleicht kannst du diesen nochmal abändern.

2021-12-04 16:32 UTC, NinaNagel requested changes
| Kriterium | Bewertung|
|-----|---|
| Front-Matter |  ja |
| Umfang | ja|
| Belege | ja |
| Links | nein|
| Formatierung | ja|
| Verlinkungen vorhanden | nein |
| Abbildungen | ja |
| Strukturierung des Beitrags | 7 |
| Rechtschreibung | 8 |
| Sprache | 9 |
| Inhalt | 10 |
| Einordnung in den Kontext | 9|
| Ansprechend für Zielgruppe | 10 |

# Zusammenfassung

Dieser Artikel handelt von der Netzplantechnik. Zunächst wird auf einzelne Elemente der Technik eingegangen. Diese werden außerdem durch Abbildungen illustriert. Danach werden die verschiedenen Arten der NPT aufgeführt. Als letztes wird die NPT in den Kontext der Projektplanung eingebettet und erklärt.

# Positive Aspekte

Der Beitrag ist sprachlich gut verfasst. Es sind keine zu verschachtelten Sätze vorhanden. Man bekommt ein Bild davon, wie die Technik funktioniert.

# Negative Aspekte

Die Rechtschreibung und Grammatik ist an manchen Stellen fehlerhaft. An einer Stelle im Text findet man einen Satz, welchen man deswegen leider nicht versteht.

Die Strukturierung passt soweit, obwohl man die Arten der NPT an den Anfang hätte setzten können. Das ist jedoch Geschmackssache. Für den letzten Punk "Projektplanung der Netzplantechnik" wäre es besser gewesen, Unterüberschriften zu verwenden. Somit wären die einzelnen Schritte verständlicher gewesen.

Bei den Abbildungen fehlt mir leider ein geeignetes Beispiel, wie ein Netzplan konkret in einem Projekt aussehen könnte. Außerdem steht bei Abbildung 2 vornweg nochmal die Beschriftung für Abbildung 1.

2021-12-07 13:11 UTC, jsk0lb requested changes
| Kriterium | Bewertung|
|-----|---|
| Front-Matter | ja/ nein |
| Umfang | ja/ nein|
| Belege | ja/ nein |
| Links | ja/ nein|
| Formatierung | ja/ nein|
| Verlinkungen vorhanden | ja/ nein |
| Abbildungen | ja/ nein |
| Strukturierung des Beitrags | 1-10 |
| Rechtschreibung | 1-10|
| Sprache | 1-10 |
| Inhalt | 1-10|
| Einordnung in den Kontext | 1-10|
| Ansprechend für Zielgruppe | 1-10|

# Zusammenfassung

Kurze Zusammenfassung des/der Artikel

# Positive Aspekte

Was ist gut (Bezug zur Tabelle)

# Negative Aspekte

Was geht besser (Bezug zur Tabelle)

2021-12-09 19:41 UTC, merged