Barcamp Methode, VModell
ManagingProjectsSuccessfully/ManagingProjectsSuccessfully.github.io pull request #273
Opened 2021-11-24 14:31 UTC by fabriGH

2021-11-30 16:57 UTC, Nikleldi requested changes
| Kriterium | Bewertung|
|-----|---|
| Front-Matter | ja |
| Umfang | ja|
| Belege | ja |
| Links | ja|
| Formatierung | ja|
| Verlinkungen vorhanden | ja |
| Abbildungen | ja |
| Strukturierung des Beitrags | 10 |
| Rechtschreibung | 9|
| Sprache | 9 |
| Inhalt | 10|
| Einordnung in den Kontext | 10|
| Ansprechend für Zielgruppe | 10|

# Zusammenfassung

Der Artikel handelt von der Moderationsmethode Barcamp. Der Artikel ist aufgebaut aus einer Begriffserklärung, dem allgemeinen Ablauf von Barcamps, Vor- und Nachteilen, No Gos, einem Gut zu wissen Abschnitt und der weiterführenden Literatur beziehungsweise den Quellen.

Ein Barcamp ist eine Moderationsmethode, besonders geeignet für 24-100 Teilnehmer, mit dem Ziel Probleme zu lösen oder Innovationen zu provozieren. Klassischerweise werden dabei Menschen aus verschiedensten Bereichen (Unternehmensabteilungen, Forschungsgruppen, etc.) zusammen getan.
Der allgemeine Ablauf des Barcamps ist in 5 Schritte aufgeteilt. Als erstes findet die Eröffnung statt. Hierbei werden die Teilnehmer begrüßt und Ihnen das Konzept der Barcamp Methode erläutert. Dabei steht vor allem die Vermittlung der Wertewelt von Barcamps im Vordergrund, beispielweise die Tatsache, dass alle Teilnehmer sich auf einer Stufe befinden und, dass es keine falschen Antworten gibt.
Als nächstes folgt die Themenfindung und Sessionplanung. Hierbei werden Themen auf einer Metaplanwand gesammelt und Räume und Besprechungszeiten festgelegt.
Als nächstes beginnt die Session. Zwischen den Sessions liegen 15 Minuten Pause.
Als viertes folgt der Abschluss.  Barcamps können von einigen Stunden bis zu mehreren Tagen dauern. Es endet erst, wenn alle Themen abgeschlossen sind. Am Ende folgt eine Feedbackrunde. Der letzte Schritt sieht vor alle gesammelten Infos zusammen zu tragen und zu einem Dokumenten zusammenzufügen. Dieses ist dann für alle Teilnehmer einsehbar.
Einige Tage später ist eine Abschlussauswertung vorgesehen, welche die vergangenen Prozesse und Abläufe reflektiert. Gleichzeitig soll ausgewertet werden, wie effizient die Barcamp Methode für das jeweilige Unternehmen bzw. Forschungsgruppe war.

Vorteile des Barcamp sind zum einen erstaunliche Ergebnisse, eine Entfaltung und Abwechslung der Teilnehmer und die Tatsache, dass es sich um eine Teambuilding Maßnahme handelt.

Nachteile hingegen sind der Kosten/Zeitaufwand, zum Teil unmotivierte Teilnehmer, ein ungeordneter Ablauf und etwaige Unstimmigkeiten zwischen den Teilnehmern.

No-Goes sind vordefinierte Themen, Abwählen von Themen ( bei zu geringer Interesse), Anpassen von Themen durch den Barcamp-Moderator, Moderation der Sessions durch das Orga-Team, Dokumentation der Sessions durch das Orga-Team, Aufnahmen der Sessions und der Ausschluss von Personen.

Gut zu wissen ist im Hinblick auf die Barcamp Methode, den Teilnehmern Mut zuzusprechen. 
Oftmals sind Teilnehmer beim ersten Mal mitmachen überfordert, daher muss das Orga Team jederzeit unterstützen können. Gleichzeitig muss der Barcamp Moderator den Fokus darauf setzen die Teilnehmer vorwiegend sprechen zu lassen und Vertrauen zu den Teilnehmern aufbauen.


# Positive Aspekte

Der Artikel ist leicht leserlich und bietet einen sehr guten Überblick über die Barcamp Methode. Er ist zudem gut strukturiert und sehr interessant.
Besonders gut ist die Tabelle, da hier ein genauer Überblick über die Vor-und Nachteile geboten wird. Es ist klar zu erkennen, dass sich der Autor ausführlich mit der Materie beschäftigt hat. Die Tatsache, dass Videomaterial als Teil der weiterführenden Literatur aufgeführt wird ist ebenfalls sehr stimmig und in jedem Fall sehr passend für die Zielgruppe (Studenten). 

# Negative Aspekte

Ab und zu wurde der Enzyklopädie Schreibstil nicht ganz eingehalten, was jedoch nicht weiter stört. Weiterhin ist ein Rechtschreibfehler aufgefallen, was zudem auch nicht sehr dramatisch ist. In der Tabelle könnte noch ein bisschen mehr auf den Kontext der jeweiligen Zeilen eingegangen werden.

2021-12-07 09:14 UTC, ebressel requested changes
| Kriterium | Bewertung|
|-----|---|
| Front-Matter | ja |
| Umfang | ja|
| Belege | ja |
| Links | ja|
| Formatierung | ja|
| Verlinkungen vorhanden | nein |
| Abbildungen | ja|
| Strukturierung des Beitrags | 10 |
| Rechtschreibung | 8|
| Sprache | 9 |
| Inhalt | 10|
| Einordnung in den Kontext | 10|
| Ansprechend für Zielgruppe | 10|

# Zusammenfassung

Der Artikel behandelt das Thema von "Barcamps", einer Moderationsmethode für Großgruppen, die sich als Strategien der Problemlösung und Innovationsfindung eignet. Das Thema wird mit einer Abbildung von Teilnehmenden der Veranstaltung eingeleitet. Im Bezug zu diesem Thema wird der Begriff geklärt und der Allgemeine Ablauf dieser Moderationsmethode augezeigt, welcher in 5 Schritten (eröffnung, Themenfindung & Sessionplanung, Sessionstart, Abschluss, Danach) erfolgt. Diese einzelnen Schritte werden jeweils mit ein paar Sätzen beschrieben und geben kurz und knapp eine Idee, wie der jeweilige Schritt typischerweise aussieht. Danach wird auf die Vor und Nachteile der Barcamps anhand einer Tabelle eingegangen und zusätzlich die No-Gos hervorgehoben. Abgerundet wird der Artikel mit ein paar zusätzlichen "Facts" "Gut zu Wissen". 

# Positive Aspekte

Vor allem ist mir die Struktur des Artikels aufgefallen. Man bekommt einen echt guten einblick in das Thema, indem erst der Begriff allgemein definiert wird und der Ablauf Schritt für Schritt erklärt wird. Auch sehr positiv finde ich die Abbildung so eines Barcamps, wodurch man sich auch besser vorstellen kann, wie diese Veranstaltung in der Realität aussehen kann. Die Tabelle zu den Vor und Nachteilen geben auch kurz und übersichtlichtlich einen Überblick zu diesen Aspekten.

# Negative Aspekte

Zur Rechtschreibung und Sprache:
-  (...) zwei Dutzend (...) (bei "Was ist ein Barcamp?")
- Teilnehmer, (Komma fehlt; (...) Zwischen den Sessions (...) (bei "Sessionstart")
- (...) ungeordneter Ablauf (bei "Nachteile")
- (...) mit dem gesamten Team stattfinden, um (Komma) (bei "Nach dem Barcamp")
- bei (zu) geringem Interesse (bei "No Gos")
- Teilnehmer, die (Komma); (...) in der Eröffnungsrede (...) (bei "Gut zu wissen")
 Verlinkungen:
- fehlen zu angrenzenden Themen

Neben der Rechtschreibung und den Verlinkungen habe ich nicht viel anzumerken, vielleicht kannst du noch ein oder zwei weitere Quellen einbeziehen, die 3 vielleicht etwas wenig ist für den ganzen Text. (dabei geht 1 Quelle ja schon auf die Abbildung, also dann nur 2 für den Text). Eine Quelle fehlt auch auf jeden Fall beim Unterpunkt "Gut zu wissen".
Ansonsten schon echt ein super Beitrag :)

2021-12-07 12:55 UTC, ebressel requested changes
| Kriterium | Bewertung|
|-----|---|
| Front-Matter | ja |
| Umfang | nein|
| Belege | ja |
| Links | ja|
| Formatierung | nein|
| Verlinkungen vorhanden | ja |
| Abbildungen | ja|
| Strukturierung des Beitrags | 10 |
| Rechtschreibung | 10|
| Sprache | 9 |
| Inhalt | 9|
| Einordnung in den Kontext | 10|
| Ansprechend für Zielgruppe | 10|

# Zusammenfassung

Der Artikel behandelt das Thema "V-Modell", einem Vorgehensmodell des Projektmanagements, das eigentlich aus der Softwareentwicklung entsprungen ist. Es dient dazu, ein Projekt in einzelnen Phasen zu intensiv testen, um allgemein die Entwicklung des Projektes effizient zu unterstützen. Eine Abbildung zu Beginn des Artikels gibt eine visuelle Auskunft darüber, wie so ein V-Modell in der Theorie aussieht und die alle (Teil-)Phasen abbildet.. Die Aussage der Abbildung über die grobe Idee des VModells wird durch einen Text unterstützt. Das VModell wird im weiteren Verlauf des Artikels detaillierter beschrieben, indem auf alle Teil-Phasen (Entwurfphase, Implementierungsphase, Test und Validierungsphase genauer eingegangen wird, indem jeweils erklärt wird, was in dieser Phase erarbeitet wird und welche Fragen geklärt werden. Danach wird auf die Vor- und Nachteile der VMethode anhand einer Tabelle eingegangen. Abgerundet wird der Artikel mit der Nennung der Anwendungsbereiche des VModells (zB. in der medizintechnik).

# Positive Aspekte

Da es sich bei diesem Thema um ein Modell handelt, finde ich es super, dass eine Abbildung zu der Struktur und des Aufbaus der Methode eingebettet wurde. So kann man sich die Vorgehensweise als Leser deutlich besser vorstellen. Auch Allgemein ist die Struktur des Beitrags wirklich übersichtlich und man wird easy durch die Theamtik geführt. 
Auch finde ich es super, dass auch auf die Unter/teilphasen genauer eingegangen wurde. Hier fand ich es besonders gut, wenn die Fragen  genannt wurden, die es in der jeweiligen Phase zu klären gab.

# Negative Aspekte

Zur Rechtschreibung und Sprache:
- (..) den Endnutzern entsprechen, um (Komma) (bei "Abnahmetest")
- (...) des gesamten Systems (bei "Vorteile")

Zum Umfang und Inhalt:
Dieser Artikel befasst ungefähr 435 Wörter, vielleicht könntest du ganz am Anfang nochmal nochmal genauer auf die Verwendung der Methode eingehen oder kurz ein konkretes Beispiel nennen, wenn zum Schluss die Anwendungsbereiche genannt werde. Außerdem würde ich noch anmerken, dass mit den Quellen nicht die Überschriften, sondern die den jeweiligen relevanten Sätze/Abschnitte den Inhalt belegen musst. 

Zur Formatierung:
Hier habe ich "nein" angegeben, weil die Nummerierung der Test und Validierungsphase nochmal überarbeiten musst: es müsste ja dann 3.1 und 3.2 statt 1.1, ... sein

Ansonsten auch schon ein super Artikel :)

2021-12-08 11:02 UTC, Lui03 requested changes
| Kriterium | Bewertung|
|-----|---|
| Front-Matter | ja |
| Umfang | ja|
| Belege | nein |
| Links | ja |
| Formatierung | ja|
| Verlinkungen vorhanden | nein | 
| Abbildungen | ja|
| Strukturierung des Beitrags | 8 |
| Rechtschreibung | 7|  
| Sprache | 8 | 
| Inhalt | 7| 
| Einordnung in den Kontext | 2|
| Ansprechend für Zielgruppe | 10|



# Zusammenfassung

Die Moderationsmethode „Barcamp“ ist ein Zusammentreffen von bis zu mehreren Hundert Menschen aus den unterschiedlichsten Bereichen eines Unternehmens. Während der 5 Phasen, welche die Teilnehmer:innen durchlaufen, sollen Probleme gelöst und innovative Ideen gesammelt werden.
Wichtig ist, dass die Moderator:innen den Teilnehmern:innen blind vertrauen und das Organisations-Team zur Unterstützung bereitsteht.
Begonnen wird mit der Eröffnungsrunde, bei der jeder ermutigt werden soll, sein Potenzial auszuschöpfen, um seinen Beitrag zu leisten.
Anschließend beginnt die Themenfindung und Sessionplanung. Hier werden Themen zusammengetragen, die das Interesse wecken. Als Nächstes folgt der Sessionstart. Die Sessions erfolgen zeitgleich oder nacheinander und die Teilnehmer:innen wechseln selbstständig zwischen den Themen für bestmöglichen Erfolg. Der Abschluss eines effizienten Barcamps erfolgt erst, nachdem alle Themen abgearbeitet wurde. Nach dem Barcamp werden die Ergebnisse zusammengefasst und zum Beispiel in Form einer Software-Lösung für jeden zugänglich gemacht.
Nachteile hierbei könnten zum einen der Kosten- und Zeitaufwand darstellen und die Unstimmigkeiten zwischen den Teilnehmer:innen. Zu den Vorteilen gehören jedoch die erstaunlichen Ergebnisse und die Abwechslung für die Mitarbeiter:innen.

# Positive Aspekte

Zunächst ist, bezüglich des Front-Matters, positiv aufgefallen, dass hier mehrere Tags eingefügt wurden.
Auch aus der Sicht des Umfangs ist der Beitrag mit ca. 500 Wörter (ohne Überschriften) perfekt ausgearbeitet worden.
Die Links funktionieren und leiten einen auf die angegebenen Seiten weiter.
Überschriften wurden korrekt gekennzeichnet und die Aufzählung, bezüglich des Ablaufs eines Barcamps, spiegelt die Phasen gut wider, die während der Methode durchlaufen werden.
Die Abbildung gibt einen Einblick in die Methode des Barcamps und ist gut gewählt, um den Lesern eine Vorstellung des Umfangs und Aufbaus zu geben.
Sprachlich ist der Beitrag gut verständlich und deshalb auch sehr ansprechend für die Zielgruppe.



# Negative Aspekte

Für mich persönlich sind es zu wenige Belege, da eine der drei Quellen zudem noch eine Bildquelle ist. Über die Universitäts-Bibliothek gibt es einige Bücher, die laut dem Inhaltsverzeichnis auch das Thema Barcamp behandeln (Gruppenarbeit: Methoden – Techniken – Anwendungen von Martin Baumann; Leadership: bewährte und aktuelle Aspekte der Führung von Andreas Werner; Praxis der Gruppenarbeit: Prozesse partizipativ gestalten von Paul Krummenacher). Außerdem sind einige Abschnitte, wie beispielsweise „Gut zu wissen“ überhaupt nicht durch Fußnoten belegt worden.
Bezüglich Rechtschreibung und Grammatik sollte der Beitrag nochmal überarbeitet werden. Beispiele hierfür sind das Wort „Dutzent“ im Abschnitt „Was ist Barcamp?“ und der erste Satz, der grammatikalisch richtig „Barcamp ist eine Moderationsmethode…“ heißen müsste. 
Inhaltlich sind mir ein paar Aspekte nicht klar. Im Abschnitt „2. Themenfindung und Sessionpalanung“ wird gesagt, wenn zwei oder mehrere ähnliche Themen von den Anbietern erkannt werden, können diese zusammengelegt werden. Im Abschnitt „No-Gos“ wird jedoch gesagt, dass Themen durch den Moderator nicht zusammengelegt werden können. Zunächst klingt dies widersprüchlich. Liegt hier der Unterschied zwischen Moderator und Anbieter? Was genau ist mit Anbieter gemeint? Dies wird bedauerlicherweise im Beitrag nicht genau erklärt. 
Eine Einordnung in den Kontext, in Bezug auf angrenzende Themen, ist hier leider nicht möglich, da weder andere Beiträge aus dem Kompendium verlinkt wurden noch Über- und Unterthemen, insbesondere in Bezug auf das Projektmanagement, genannt wurden. Beispielsweise die Provokationstechniken könnten hier verlinkt werden, da im Beitrag auch von Innovationen, die provoziert werden sollen, gesprochen wird.

2021-12-08 12:47 UTC, Nikleldi requested changes
| Kriterium | Bewertung|
|-----|---|
| Front-Matter | ja |
| Umfang | nein|
| Belege | ja |
| Links | ja|
| Formatierung | ja|
| Verlinkungen vorhanden | ja |
| Abbildungen | ja |
| Strukturierung des Beitrags | 10 |
| Rechtschreibung | 10|
| Sprache | 9|
| Inhalt | 9|
| Einordnung in den Kontext | 10|
| Ansprechend für Zielgruppe | 10|

# Zusammenfassung
Der Artikel handelt vom "V-Modell", einem Vorgehensmodell aus dem Projektmanagement, welche ursprünglich aus der Softwareentwicklung stammt. Mit dem V-Modell wird ein Projekt in verschiedene Phasen aufgeteilt, getestet, integriert und wieder zusammengefügt.
Ziel ist es, die Entwicklung des Projekts zu fördern. Eine Abbildung zeigt, wie die verschiedenen Phasen aussehen.
Das V-Modell wird im weiteren Verlauf des Artikels detaillierter beschrieben, indem auf alle Teil-Phasen (Entwurfphase, Implementierungsphase, Test und Validierungsphase) näher eingegangen wird. Darin werden die phasenzugehörigen Tests und Spezifikationen erklärt.
Abschließend werden in Form einer Tabelle die Vor -und Nachteile des V-Modells aufgezeigt und abgeschlossen wird der Text mit einer Aufzählung der Anwendungsbereiche.

# Positive Aspekte

Der Beitrag ist gut geschrieben und übersichtlich gestaltet. Als Leser ohne Vorkenntnisse kann man sich ein gutes Verständnis über das Modells aneignen. Besonders geeignet ist hierbei die Abbildung, da diese den Inhalt passend visualisiert. Die Struktur ist sehr gut und man bekommt leicht verständlich einen Überblick überdie Methode.

# Negative Aspekte

Leider wurde der Umfang mit 435 Wörtern nicht ganz erreicht (500 Wörter wurden als Untergrenze gennannt). Eventuell ist das durch ein kurzes Beispiel oder Fazit schnell hinzugefügt.

Zur Rechtschreibung und Sprache:

 1.4 Abnahmetest:  (... )den Endnutzern Entsprechen ("entsprechen" groß geschrieben) ( Komma vergessen) um (...) 
 Vor- und Nachteile Tabelle  (... ) des gesamten System (des gesamten Systems)

Bis auf die Kleinigkeiten aber ein sehr guter Artikel!

2021-12-09 14:48 UTC, Lui03 requested changes
| Kriterium | Bewertung|
|-----|---|
| Front-Matter | ja |
| Umfang | nein|
| Belege | nein |
| Links | ja |
| Formatierung | nein|
| Verlinkungen vorhanden | ja| 
| Abbildungen | ja|
| Strukturierung des Beitrags | 9 | 
| Rechtschreibung | 10|  
| Sprache | 9| 
| Inhalt | 8| 
| Einordnung in den Kontext | 9|
| Ansprechend für Zielgruppe | 10|



# Zusammenfassung

Bei der Anwendung des V-Modells werden Projekte in 3 fest definierte Phasen untergliedert. Der Name ergibt sich aus dem V-förmigen Aufbau des Modells, und ein wesentlicher Unterschied zu anderen Modellen liegt in den zusätzlichen Testphasen. Die erste Phase, auch „Entwurfsphase“ genannt, übersetzt Anforderungen in einen Systementwurf, der, je tiefer man geht, weiter verbessert wird.
Die zweite Phase ist die Implementierungsphase und variiert je nach Projekt.
In der Test- und Validierungsphase, welche die dritte und letzte Phase des Modells darstellt, steht jede Ebene der dazugehörigen Entwurfsphase gegenüber und es wird nach dem Bottom-Up-Prinzip vorgegangen.
Vorteile des V-Modells sind zum einen der einfache Aufbau und die frühe Erkennung von Problemen, andererseits aber auch die geringe Notwendigkeit an Kommunikation mit dem Kunden.
Die Nachteile hierbei sind jedoch die ausführliche Dokumentation und geringe Flexibilität.

# Positive Aspekte

Zunächst ist, bezüglich des Front-Matters, positiv aufgefallen, dass hier mehrere Tags eingefügt wurden.
Die Links funktionieren und leiten auf die entsprechende Seite weiter
Außerdem wurde der Beitrag des Wasserfallmodells sehr gut in den Text eingearbeitet. Dies führt ebenfalls zu einem steigenden Interesse für weitere Themenbereiche und Modelle. Die Abbildung spiegelt gut den beschriebenen Aufbau des Modells wider und ist nachvollziehbar.
Rechtschreib- Und Grammatikfehler sind mir während des Durchlesens nicht aufgefallen.
Die Einordnung in den Kontext ist durch die Verlinkung des anderen Beitrags, der Begriffserklärungen durch Wikipedia und dem Einbezug des Projektmanagements sehr gut gelungen.


# Negative Aspekte

Zunächst fällt der Umfang des Beitrags auf, der mit ca. 430 Wörtern etwas zu kurz ausfällt. Hier könnte Beispielsweise noch auf Weiterentwicklungen, wie das V-Modell 97 oder das V-Modell XT, eingegangen werden oder ein kurzes Fazit mit Bezug auf das klassische Projektmanagement verfasst werden, was sich wiederum auch positiv im Hinblick auf den Inhalt spiegeln würde.
Für mich persönlich sind es zu wenige Belege, da eine der drei Quellen zudem noch eine Bildquelle ist. Über die Universitäts-Bibliothek findet man einige Bücher, die laut dem Inhaltsverzeichnis auch das V-Modell behandeln (Das V-Modell in der Praxis : Grundlagen, Erfahrungen, Werkzeuge von Gerhard Versteegen).
Bezüglich der Formatierung ist mir aufgefallen das im Abschnitt „zu 3: …“ die Unterpunkte falsch eingefügt wurden. Dies müsste, meines Erachtens nach, 3.1, 3.2, … heißen.

2021-12-09 19:41 UTC, merged