Konfliktmanagement
ManagingProjectsSuccessfully/ManagingProjectsSuccessfully.github.io pull request #276
Opened 2021-11-24 14:51 UTC by Lui03

2021-12-04 12:40 UTC, Cari02 requested changes
| Kriterium | Bewertung|
|-----|---|
| Front-Matter | ja |
| Umfang | ja | 
| Belege | ja |
| Links | ja |
| Formatierung | ja | 
| Verlinkungen vorhanden | ja |
| Abbildungen | ja |
| Strukturierung des Beitrags | 10 |
| Rechtschreibung | 8 |
| Sprache | 10 |
| Inhalt | 8 |
| Einordnung in den Kontext | 10 |
| Ansprechend für Zielgruppe | 9 |

# Zusammenfassung
Der Artikel befasst sich mit dem Konzept des Konfliktmanagements.
Hierbei versucht man Konflikte frühestmöglich zu erkennen, zu vermeiden oder zu lösen.
In der Einleitung wird das Thema kurz definiert. Als Übergang wird strukturiert erklärt, wie Konflikte früh erkannt werden, und die zentralen Aufgaben der Projektleitung hierbei.
Dabei kann man Konflikte zwei Überbegriffen zuordnen, den sachlichen und den psychosozialen Konflikten, die in einer Tabelle aufgelistet werden.
Der Hauptteil wird mit dem Rollenkonflikt eingeleitet, dieser zeigt die Uneinigkeit eines Projektteams über die Verteilung der einzelnen Aufgaben. Als Lösungsansatz für dieses Problem wird die RASIC-Matrix vorgestellt. Diese sorgt dafür zu erkennen, welcher Mitarbeiter für welche Beschäftigung zuständig ist. Diese wird zudem anschaulich als Grafik dargestellt. 
Zum Ende wird auf den Nutzen des Konfliktmanagements für das klassische Projektmanagement eingegangen. Der Beitrag wird mit einer Kritik und Überleitung zum agilen Projektmanagement abgerundet.

# Positive Aspekte
Inhaltlich sowie sprachlich ist der Artikel sachlich, gut und deutlich geschrieben, sodass der Kontext leicht verständlich ist und es somit einen sehr gelungenen Zusammenhang ergibt.
Der Beitrag ist gut strukturiert, welches durch die gewählten Unterpunkte verdeutlicht wird, die dem Inhalt einen roten Faden geben. 
Die Quellen und Verlinkungen zu anderen Beiträgen des Kompendiums wurden richtig den Inhalten zugeordnet und sind somit gut in das gesamte Themengebiet eingearbeitet.
Durch die vielen Verlinkungen zu angrenzenden Themen wurde eine sehr gute Verbindung zu dem Hauptthema Projektmanagement und der Einordnung in den Kontext hergestellt.
Die Grafik wurde gut gewählt, ist anschaulich und leicht verständlich.

# Negative Aspekte
Die Sprache des Artikels ist gut gewählt, jedoch sollte hier die Rechtschreibung und Grammatik, vor allem aber die Kommasetzung nochmals überarbeitet werden.
Der Umfang mit der Richtlinie von ca. 500 Wörtern ist mit ca. 450 Wörtern gerade noch in der vorgegebenen Länge, könnte jedoch etwas ausgearbeitet werden, wie beispielsweise bei einer ausführlicheren Beschreibung der Grafik.
Das Fazit und die Kritik könnten noch ausgebaut werden, indem man z.B. genauer darauf eingeht, wieso das Konfliktmanagement für das klassische Projektmanagement geeignet ist, um so zusammenfassend die wichtigsten Punkte des Konfliktmanagements erneut aufzugreifen. Dabei wäre es übersichtlicher , wenn der Aspekt Kritik und Fazit separiert erläutert wird.

2021-12-06 00:50 UTC, SimaSol requested changes
| Kriterium | Bewertung|
|-----|---|
| Front-Matter | ja |
| Umfang | nein|
| Belege | ja |
| Links | ja |
| Formatierung | ja |
| Verlinkungen vorhanden | ja |
| Abbildungen | ja |
| Strukturierung des Beitrags | 9 |
| Rechtschreibung | 9 |
| Sprache | 9 |
| Inhalt | 9 |
| Einordnung in den Kontext | 10 |
| Ansprechend für Zielgruppe | 10 |

# Zusammenfassung

Der Artikel befasst sich mit der Identifizierung, Auseinandersetzung und dem Lösen von Konflikten im Projektmanagement. 
Zuerst wird in der Einleitung das Konfliktmanagement näher definiert, um die Identifikation zu erleichtern. 
Im nächsten Absatz wird darauf hingewiesen, dass Konflikte auch frühzeitig in der Projektstart-Phase entstehen können und folglich eine Erkennung dieses Problems so schnell wie möglich erfolgen sollte. 
Daraufhin werden die verschiedenen Arten von Konflikten anhand einer, aus meiner Sicht sehr hilfreichen Tabelle, aufgeführt und in "sachliche" sowie "psychosoziale Konflikte" aufgespalten. 
In Folge dessen wird im nächsten Abschnitt die Erkennung, Analyse und das Lösen des Konflikts näher erörtert. Dabei wird eine vereinfachte, jedoch sehr anschauliche Abbildung der R.A.S.I.C Matrix, die auch im klassischen Projektmanagement verwendet wird, aufgezeigt. 
Zum Abschluss wird noch auf das Fazit und die Kritik des Konfliktmanagements im klassichen Projektmanagement eingegangen.
Abseits des Inhalts werden zum Schluss noch weitere Lesetipps und ähnliche Beiträge, sowie die Quellen, verlinkt.

# Positive Aspekte

Der Artikel hat eine inhaltlich gute Zusammenfassung der Thematik des Konfliktmanagements gegeben. Dieser kann aber auf jeden Fall noch mehr ausgeweitet werden. 
Die Strukturierung wies eine saubere Einleitung und einen klaren Schluss auf. 
Die Sprache ist angemessen und in Ordnung. Der Satzbau ist nicht zu kompliziert gebildet und sehr verständlich für den Leser. 
Besonders gut habe ich die Abbildung sowie die Tabelle empfunden, die simpel aber sehr effektiv zur Veranschaulichung für den Leser bestimmt sind.
Die Einordnung in unser Hauptthema "Projektmanagement" erfüllt der Artikel inhaltlich ebenfalls.

# Negative Aspekte

Der Artikel kann gerne wenn nicht sogar unbedingt noch um einiges ausgebaut werden. 
Der Umfang von ca. 500 Wörtern (hier: nur ca. 468 Wörter) wurde nicht ganz erreicht.
Außerdem wurde ein Komma im ersten Abschnitt im dritten Absatz bei "[...] hat man sich Gedanken gemacht !,! welche verschiedenen Arten es von Konflikten gibt. [...]:" vergessen.

Ideen für die Erweiterung des Artikel: 
- Wie geht ein Unternehmen (ein Unternehmen als Beispiel nennen) mit Konflikten im Projekt um
- Gibt es evtl. verschiedene Ansätze für das Lösen von Konflikten in Projekten

2021-12-06 14:25 UTC, Lars428 requested changes
| Kriterium | Bewertung|
|-----|---|
| Front-Matter | ja |
| Umfang | ja |
| Belege | ja |
| Links | ja |
| Formatierung | ja |
| Verlinkungen vorhanden | ja |
| Abbildungen | ja |
| Strukturierung des Beitrags | 9 |
| Rechtschreibung | 7 |
| Sprache | 9 |
| Inhalt | 8 |
| Einordnung in den Kontext | 10 |
| Ansprechend für Zielgruppe | 9 |

# Zusammenfassung

„Konfliktmanagement bezeichnet den Prozess der Konflikterkennung, -analyse, -lösung und der nachhaltigen Konfliktvermeidung.“ Konflikte können in zwei Arten eingeordnet werden. Sachliche Konflikte und psychosoziale Konflikte. Die Aufgabenverteilung ist im klassischen Projektmangament sehr wichtig, um Konflikte zu vermeiden. Mithilfe einer R.A.S.I.C Matrix kann im klassischen Projektmanagement vorab die Rollenverteilung veranschaulicht und verwaltet werden. Außerdem muss beim Konfliktmanagment beachtet werden, dass Menschen emotional und nicht immer rational handeln.

# Positive Aspekte

Der Artikel fasst die Thematik Konfliktmangement gut zusammen und ordnet sie gut in den Gesamtkontext ein. Auch die Strukturierung und die Sprache sind gut gelungen. Die Tabelle und die Abbildung/Matrik sing gut gewählt und passen gut in den Artikel.

# Negative Aspekte

Die Formatierung der Übschriften ist meiner Meinung nach fehlerhaft. Man sollte keinen Unterpunkt 1.1 einführen wenn es keinen Punkt 1.2 gibt. Außerdem sollte man nach dem 1. immer ein Leerzeichen lassen. Der Artikel ist mit ca 450 Wörtern an der unteren Grenze der Vorgabe und könnte noch ein paar Aspekte mehr vertragen. Die Kommasetzung sollte nocheinmal überprüft werden (Einleitung).

2021-12-09 19:41 UTC, merged

2021-12-22 20:47 UTC, Lui03 commented
@Lars428 Vielen Dank für deine positive und negative Kritik.
Ich habe versuch den Aspekt bezüglich der Leerzeichen hinter den Nummern zu verbessern.
Außerdem hast du bemängelt, dass hier kein 1.1 vorhanden sein sollte, wenn es kein 1.2 gibt. Leider habe ich dies nicht ganz nachvollziehen können, da mir hier kein Weg eingefallen ist, wie ich dies hätte umgehen können. Zudem hast du mir auch leider keinen Verbesserungsvorschlag diesbezüglich genannt.
Danke trotzdem für deine Bewertung. Rechtschreibung, Kommasetzung und Umfang habe ich im neuen Beitrag nochmal überarbeitet. :)