"Projekt_Charta" und "Scrum_Metrics" Abgabe
ManagingProjectsSuccessfully/ManagingProjectsSuccessfully.github.io pull request #286
Opened 2021-11-24 16:12 UTC by efdil

"Scrum_Metrics" für agil
"Projekt_Charta" für klassisch

viel spaß beim lesen :)

2021-12-03 12:50 UTC, MrSommC requested changes
Kriterium | Bewertung|
|-----|---|
| Front-Matter | ja|
| Umfang | ja|
| Belege | ja |
| Links | ja|
| Formatierung | ja|
| Verlinkungen vorhanden | ja|
| Abbildungen | ja |
| Strukturierung des Beitrags | 10 |
| Rechtschreibung | 8|
| Sprache | 9 |
| Inhalt | 9|
| Einordnung in den Kontext | 9|
| Ansprechend für Zielgruppe | 9|
# Zusammenfassung
Der Artikel beschäftigt sich mit der sogenannten „Projekt Charta“. Dabei handelt es sich um ein Dokument, welches die wichtigsten Punkte eines Projekts beschreibt.
Im vorliegenden Artikel wird zunächst definiert was eine Projekt Charta ist. Des Weiteren wird erläutert welche Funktionen eine Projekt Charta im Projektverlauf einnehmen kann. Dabei wird auf die verschiedenen Zeitpunkte des Projekts Rücksicht genommen. Anschließend werden die Bestandteile einer Projekt Charta genannt und häufige Fehlerquellen beschrieben. 
Es folgt ein Beispiel einer Projekt Charta sowie ein abschließendes Fazit. 
Kurze Zusammenfassung des/der Artikel

# Positive Aspekte
Die beispielhafte Abbildung der Projekt Charta ist sehr anschaulich und hilft beim Verständnis der Thematik weiter. Generell ist der Artikel gut strukturiert und angenehm zu lesen. 
Ebenfalls sind die Bereiche „Siehe auch“ und „Weiterführende Literatur“ umfassend bearbeitet und ermöglichen es sich tiefer mit dem Themenfeld auseinanderzusetzen. 

Was ist gut (Bezug zur Tabelle)
Sehr gut ist die Strukturierung des Beitrags, die Überschriften sowie Unterüberschriften sind immer gut gewählt und ermöglichen es den Artikel gut zu Überblicken. 
Die Quellen sind ebenfalls gut gewählt, sie haben einen guten Umfang.
# Negative Aspekte
Ein sehr kleiner Kritikpunkt ist, dass die Schreibweise des Begriffs Projekt Charta in der ersten Unterüberschrift zu Project Charta wechselt. Allerdings ist dies natürlich nur ein kleiner Kritikpunkt
Was geht besser (Bezug zur Tabelle)
Meiner Meinung nach beinhaltet der Artikel recht viele Aufzählungspunkte, hier könnte zur Abwechslung häufiger im Fließtext geschrieben werden.

2021-12-03 13:11 UTC, MrSommC requested changes
Kriterium | Bewertung|
|-----|---|
| Front-Matter | nein |
| Umfang | ja|
| Belege | ja|
| Links | ja|
| Formatierung | ja|
| Verlinkungen vorhanden | ja|
| Abbildungen | ja |
| Strukturierung des Beitrags |10 |
| Rechtschreibung |9 |
| Sprache | 9 |
| Inhalt | 10|
| Einordnung in den Kontext | 9|
| Ansprechend für Zielgruppe | 9|
# Zusammenfassung
Der Artikel beschäftigt sich mit der sogenannten „Scrum Metrics“. Dabei handelt es sich um Messwerte, welche von Scrum Teams ermittelt werden um ihre Effizienz und Effektivität zu beobachten und zu steigern.
Im vorliegenden Artikel wird zunächst definiert was eine Scrum Metrics ist. Des Weiteren wird erläutert, welche Vorteile der Einsatz einer Scrum Metrics im Projektverlauf haben kann.
In einer Grafik wird eine Scrum Metrics in einem Scrum Sprint visualisiert. Im weiteren Verlauf des Artikels wird näher auf die Sprint Planung, Team Geschwindigkeit, Team Kapazität, Focus Faktor und Sprint Burndown eingegangen 

# Positive Aspekte
Sehr gut sind die verschiedenen Grafiken. Sie helfen dabei einen visuellen Einblick in die Bereiche Scrum Metrics im Scrum Sprint, die Team Geschwindigkeit und den Sprint Burndown zu liefern.

Was ist gut 
Die Strukturierung des Beitrags ist sehr gut, so sind die Überschriften sowie Unterüberschriften passend gewählt und helfen dabei den Artikel zu strukturieren. 
Ebenfalls ist positiv zu erwähnen, dass einige Verlinkungen eingefügt wurden, somit kann direkt auf verwandte Artikel zugegriffen werden. 
Die Quellen sind gut gewählt, sie haben einen guten Umfang. 
# Negative Aspekte
Der Artikel gefällt mir sehr gut und ich kann keine negativen Punkte anführen 
Was geht besser 
Auch hier habe ich keine nennenswerten Kritikpunkte

2021-12-04 01:02 UTC, efdil commented
@MrSommC Hey, danke für die Reviews, jedoch bin ich etwas verloren damit. Für beide meiner Beiträge existieren die Front-Matter, daher verstehe ich das 'nein' bei dem einen nicht. Wäre auch mega cool sowie Hilfreich wenn du die Punktabzüge begründen könntest. Dadurch kann ich diese in der 2. Runde ja auf die Ganzpunktzahl Hochbearbeiten.

So genau weiß ich auch nicht mehr in welcher Vorlesung das behandelt wurde, aber soweit ich weiß sind ja pro Pull-Request, jeweils ein Review abzugeben der auch alle Beiträge darin bewertet.

Freut mich wenn du die Reviews dementsprechend nochmal überarbeiten kannst.

2021-12-04 10:04 UTC, MrSommC commented
Heyy,

Das nein war keine Absicht, ich ändere es gerne nochmal.

Sorry dafür, ich bin mit dem GitHub System nicht wirklich vertraut.

Ich schau gleich nochmal drüber.

Liebe Grüße

Christoph
efdil ***@***.***> schrieb am Sa. 4. Dez. 2021 um 02:02:

> @MrSommC <https://github.com/MrSommC> Hey, danke für die Reviews, jedoch
> bin ich etwas verloren damit. Für beide meiner Beiträge existieren die
> Front-Matter, daher verstehe ich das 'nein' bei dem einen nicht. Wäre auch
> mega cool sowie Hilfreich wenn du die Punktabzüge begründen könntest.
> Dadurch kann ich diese in der 2. Runde ja auf die Ganzpunktzahl
> Hochbearbeiten.
>
> So genau weiß ich auch nicht mehr in welcher Vorlesung das behandelt
> wurde, aber soweit ich weiß sind ja pro Pull-Request, jeweils ein Review
> abzugeben der auch alle Beiträge darin bewertet.
>
> Freut mich wenn du die Reviews dementsprechend nochmal überarbeiten kannst.
>
> —
> You are receiving this because you were mentioned.
>
>
> Reply to this email directly, view it on GitHub
> <https://github.com/ManagingProjectsSuccessfully/ManagingProjectsSuccessfully.github.io/pull/286#issuecomment-985935082>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AWGFW47WW53FI43ACSP5HXLUPFSBVANCNFSM5IWOXGSQ>
> .
> Triage notifications on the go with GitHub Mobile for iOS
> <https://apps.apple.com/app/apple-store/id1477376905?ct=notification-email&mt=8&pt=524675>
> or Android
> <https://play.google.com/store/apps/details?id=com.github.android&referrer=utm_campaign%3Dnotification-email%26utm_medium%3Demail%26utm_source%3Dgithub>.
>
>

2021-12-07 11:34 UTC, FAUdennis96 requested changes
| Kriterium | Bewertung|
|-----|---|
| Front-Matter | ja |
| Umfang | ja|
| Belege | ja |
| Links | ja|
| Formatierung | ja|
| Verlinkungen vorhanden | ja |
| Abbildungen | ja |
| Strukturierung des Beitrags | 10 |
| Rechtschreibung | 9|
| Sprache | 10 |
| Inhalt | 9|
| Einordnung in den Kontext | 10|
| Ansprechend für Zielgruppe | 10|

# Zusammenfassung

Der Artikel befasst sich mit der "Project Charta". Zu Beginn werden die Begrifflichkeiten geklärt und wie eine "Project Charta" beginnt. Im Weiteren werden die Funktionen zu Beginn und im Verlauf des Projekts erläutert. Anschließend werden die Bestandteile und häufig gemachte Fehler herausgearbeitet. Abschließend wird auf ein Praxisbeispiel eingegangen gefolgt von einem kleinen Fazit.

# Positive Aspekte

Der Beitrag ist sehr gut strukturiert und die Verschiedenen Überschriften leiten den Leser wunderbar durch den Artikel. Das Thema wird gut erklärt und auch die gewählte Grafik passt sehr gut. Sie visualisiert die vorangegangenen Informationen und wertet den Beitrag auf.

# Negative Aspekte

Ein kleiner Kritikpunkt sind die vielen Aufzählungspunkte. Vielleicht ist es möglich die weniger wichtigen Punkte wegzulassen. Oder einen Fließtext daraus zu machen.

2021-12-07 12:24 UTC, FAUdennis96 requested changes
| Kriterium | Bewertung|
|-----|---|
| Front-Matter | ja |
| Umfang | ja|
| Belege | ja |
| Links | ja|
| Formatierung | ja|
| Verlinkungen vorhanden | ja|
| Abbildungen | ja |
| Strukturierung des Beitrags | 10|
| Rechtschreibung |10|
| Sprache |10 |
| Inhalt | 9|
| Einordnung in den Kontext | 9|
| Ansprechend für Zielgruppe | 10|

# Zusammenfassung

Der Artikel befasst sich mit dem Thema "Scrum Metrics".  Der Begriff wird ausführlich erklärt und durchleuchtet, bevor verschiedene Einsatzfelder aufgezählt werden. Im Folgenden wird auf die Vorteile eingegangen und Unterschiede zu "Key Performance Indicators" werden herausgearbeitet. Anschließend werden "Scrum Metrics in Scrum Scripts" beschrieben. Ein Fazit zum Ende rundet den Artikel ab.

# Positive Aspekte

Der Artikel ist gut strukturiert. Dadurch findet sich der Leser sehr gut zurecht, obwohl er mit dem Thema im Vorfeld nicht vertraut ist. Ein weiterer positiver Aspekt ist die Auswahl der Grafiken, sie stellen einen Mehrwert für den Artikel dar und veranschaulichen die Theorie. Zusätzlich stellt das kleine Fazit eine gelungene Abrundung des Artikels dar. 

# Negative Aspekte

Ein ganz kleiner Kritikpunkt gilt den Unterüberschriften "Sprintkapazität", "Focus Factor" und "Sprint Burndown". Es ist bei erster Berührung mit dem Thema nicht ganz klar woher diese Begriffe kommen oder in welchen Kontext sich einzuordnen sind.

2021-12-07 22:02 UTC, AbderrahmaneBennani requested changes
| Kriterium | Bewertung|
|-----|---|
| Front-Matter | ja |
| Umfang | ja |
| Belege | ja |
| Links | ja |
| Formatierung | ja |
| Verlinkungen vorhanden | ja |
| Abbildungen | ja |
| Strukturierung des Beitrags | 10 |
| Rechtschreibung | 9 |
| Sprache | 10 |
| Inhalt | 10 |
| Einordnung in den Kontext | 10|
| Ansprechend für Zielgruppe | 10|

# Zusammenfassung
Projekt_Charta.md
In diesem Artikel geht es um die Projekt Charta. Zuerst wurde den Begriff definiert. Dann wurden die Funktionen eines Project Charta zu Beginn des Projekts als auch während des Projekts mithilfe einer Abbildung erklärt. Danach wurden die Bestandteile eines Project Charta und Häufige Fehler bei der Erstellung einer Project Charta genannt und erläutert. Anschließend gab es ein Beispiel einer Project Charta und ein kleines Fazit.

Scrum_Metrics.md
In diesem Artikel geht es um Scrum Metrics. Zuerst wurde Scrum Metrics definiert und mögliche Vorteile im Projektverlauf erläutert. Dann wurde der Unterschied zu KPI’s genannt. Danach wurden verschiedene wiederkehrende Ereignisse eines Scrum Sprint mit Hilfe der Abbildungen erläutert. Anschließend gab es ein kleines Fazit.

# Positive Aspekte
Projekt_Charta.md
Artikel war sehr interessant zu lesen. Strukturierung war dank der Überschriften leicht zu verfolgen. Interne Verlinkungen fand ich gut. Abbildungen sind hilfreich, um den Inhalt zu verstehen.

Scrum_Metrics.md
Die Abbildungen fand ich sehr gut, man kann dadurch die Ereignisse eines Scrum Sprint sehr gut verstehen. Artikel ist sehr gut strukturiert. Interne Verlinkungen fand ich auch gut.

# Negative Aspekte
Projekt_Charta.md
- Wechsel zwischen Projekt Charta und Project Charta in Überschriften.
- Sehr kleine Rechtschreibfehler sonst perfekt.

Scrum_Metrics.md
- Artikel finde ich schon ziemlich gut.

2021-12-09 19:41 UTC, merged