Ideen_Marathon, Scrum_Guide, MrSommC
ManagingProjectsSuccessfully/ManagingProjectsSuccessfully.github.io pull request #289
Opened 2021-11-24 16:37 UTC by MrSommC

2021-12-05 15:29 UTC, Lukas1401 requested changes
| Kriterium | Bewertung|
|-----|---|
| Front-Matter | ja |
| Umfang | ja |
| Belege | ja |
| Links | ja |
| Formatierung | ja |
| Verlinkungen vorhanden | ja |
| Abbildungen | ja |
| Strukturierung des Beitrags | 10 |
| Rechtschreibung | 9 |
| Sprache | 9 |
| Inhalt | 10 |
| Einordnung in den Kontext | 10 |
| Ansprechend für Zielgruppe | 10 |

# Zusammenfassung

Der Artikel befasst sich mit dem Konzept des Ideen-Marathons. Zunächst wird der Ideen-Marathon in den Kontext des klassischen Projektmanagements eingeordnet. Anschließend werden die Hintergründe und das Grundprinzip näher erläutert. Danach werden die Regeln des Ideen-Marathons genauer beschrieben.

# Positive Aspekte

Positiv zu nennen ist die gute Strukturierung des Artikels. Dadurch lässt sich der Artikel gut lesen und man kann dem Inhalt besser folgen. Außerdem ist er auch sprachlich gut geschrieben, was zusammen mit der guten Strukturierung dazu führt, dass der Inhalt leicht verständlich ist und man ein gutes Verständnis über den beschriebenen Ideen-Marathon bekommt. Auch die Abbildung stellt eine gute Visualisierung des Ideen-Marathons dar, wodurch man sich den Ablauf besser vorstellen kann.

# Negative Aspekte

Negativ anzumerken wäre, dass an wenigen Stellen ein Komma fehlt und ein Rechtschreibfehler vorhanden ist. Bei der Abbildung könnte man Punkt 4 und Punkt 6 vertauschen, da es so den Pfeilen besser folgen würde.

2021-12-05 16:01 UTC, Lukas1401 requested changes
| Kriterium | Bewertung|
|-----|---|
| Front-Matter | ja |
| Umfang | ja |
| Belege | ja |
| Links | ja |
| Formatierung | ja |
| Verlinkungen vorhanden | ja |
| Abbildungen | ja |
| Strukturierung des Beitrags | 10 |
| Rechtschreibung | 9 |
| Sprache | 9 |
| Inhalt | 9 |
| Einordnung in den Kontext | 9 |
| Ansprechend für Zielgruppe | 10 |

# Zusammenfassung

Der Artikel befasst sich mit dem Scrum-Guide. Zu Beginn wird der Scrum Guide näher beschrieben und die Bedeutung von Scrum im Kontext des agilen Projektmanagements erläutert. Danach werden die konkreten Inhalte des Scrum-Guides genannt und im Folgenden näher erläutert und beschrieben. Anschließend wird auf die Scrum-Ereignisse eingegangen und zum Schluss findet eine Visualisierung des Scrum-Prozesses statt.

# Positive Aspekte

Positiv ist die gute Strukturierung des Beitrags zu nennen, dies macht ihn sehr übersichtlich und führt dazu, dass man dem Artikel sehr gut folgen kann. Auch die Sprache ist positiv hervorzuheben, da der Beitrag gut leserlich und dadurch auch die beschriebenen Inhalte leichter zu verstehen sind. Zudem ist auch die Einordnung in den Kontext gut gelungen und es wurde auf auch häufig andere Artikel des Kompendiums verlinkt. Die Grafik zum Schluss stellt auch eine gute Visualisierung eines Scrum-Prozesses dar.

# Negative Aspekte

Kleinere negative Aspekte wären bei der Verlinkung bzw. bei einem Quellenverweis zu nennen. Unter der Überschrift "siehe auch" ist eine fehlerhafte Verlinkung auf "Projektmanagement". Bei der "Sprint-Retrospektive" funktioniert der Quellenverweis leider nicht. Zudem könnte man bei dem Aspekt "Scrum-Werte" ,bei den konkreten Inhalten des Scrum-Guides, eventuell noch eine Verlinkung auf das Thema "Scrum_Values" einfügen.

2021-12-06 14:31 UTC, nicolasrmg requested changes
## Scrum Guide

| Kriterium | Bewertung|
|-----|---|
| Front-Matter | ja |
| Umfang | ja |
| Belege | ja |
| Links | ja |
| Formatierung | ja |
| Verlinkungen vorhanden | ja |
| Abbildungen | ja |
| Strukturierung des Beitrags | 10 |
| Rechtschreibung | 10 |
| Sprache | 9 |
| Inhalt | 10 |
| Einordnung in den Kontext | 10 |
| Ansprechend für Zielgruppe | 10|

# Zusammenfassung

Der Beitrag gibt einen ausführlichen Überblick über den Scrum-Prozess und die verschiedenen Rollen.

# Positive Aspekte

Grafik zu Scrum Guide rundet gut ab und fasst noch einmal zusammen; sehr ordentliche Struktur mit linearem Verlauf erleichtert das Textverständnis; keine Rechtschreibfehler; interessanter Beitrag für einen ersten Einblick in die Scrum-Thematik

# Negative Aspekte

Siehe auch: letzte Verlinkung geht nicht
Sprint-Retrospektive: Fußnote nicht formatiert
Scrum-Rollen: ScrumMaster mit Leerzeichen oder Bindestrich
Die letzten drei Sätze des Front-Matters klingen etwas schwammig, ggf. zu einem Satz zusammenfügen
Bei Formulierung „Was genau ist Scrum“ Fragezeichen verwenden.


## Ideen Marathon

| Kriterium | Bewertung|
|-----|---|
| Front-Matter | ja |
| Umfang | ja |
| Belege | ja |
| Links | ja |
| Formatierung | ja |
| Verlinkungen vorhanden | ja |
| Abbildungen | ja |
| Strukturierung des Beitrags | 10 |
| Rechtschreibung | 9 |
| Sprache | 10 |
| Inhalt | 10 |
| Einordnung in den Kontext | 10 |
| Ansprechend für Zielgruppe | 10|

# Zusammenfassung

Der Artikel vermittelt Informationen zu der Kreativitätstechnik von Takeo Higuchi zur Ideenfindung für Einzelpersonen, einschließlich der Regelungen zur Anwendung.

# Positive Aspekte

selbsterstellte Grafik zu Ideen Marathon sehr gut/kreativ (wenn auch mit optimierungsbedarf: siehe unten); klare Struktur mit linearem Verlauf; aktueller Stand über Higuchi sehr interessant und als Beispiel für die Effektivität besonders sinnvoll

# Negative Aspekte

4. Absatz: kreatives „Denken“ großschreiben
3. Absatz von hinten: bestenfalls zusammenschreiben
2-3 Kommasetzungsfehler
Grafik unschlüssig: Pfeile folgen anderer Reihenfolge als die Nummerierungen, irreführend

2021-12-08 17:53 UTC, JonathanLoewing reviewed
# Ideenmarathon
| Kriterium | Bewertung|
| ---------- | ----------- |
| Front-Matter | ja |
| Umfang | ja |
| Belege | ja |
| Links | ja |
| Formatierung | ja |
| Verlinkungen vorhanden | ja |
| Abbildungen | ja |
| Strukturierung des Beitrags | 10 |
| Rechtschreibung | 10 |
| Sprache | 9 |
| Inhalt | 9 |
| Einordnung in den Kontext | 10 |
| Ansprechend für die Zielgruppe | 10 |

# Zusammenfassung
Der Beitrag handelt von dem Ideenmarathon. Dies ist eine Technik mit der einzelne Personen leichter zu kreativen Ideen finden. Die grundliegenenden Prinzipien und Regeln werden genannt und erklärt und zum Schluss noch einmal visualisiert.
# Positive Aspekte

- Gute Beispiele und Graphik
- Einfache Erklärungen
- Struktur (Reihenfolge der Abschnitte gut gewählt)

# Negative Aspekte
Auch wenn die Graphik sehr gut informiert und sogar selbsterstellt ist, wäre vielleicht noch ein kurzer Kommentar darunter gut um nochmal auf diese einzugehen.

# Scrum Guide
| Kriterium | Bewertung|
| ---------- | ----------- |
| Front-Matter | ja |
| Umfang | ja |
| Belege | ja |
| Links | ja |
| Formatierung | ja |
| Verlinkungen vorhanden | ja |
| Abbildungen | ja |
| Strukturierung des Beitrags | 10 |
| Rechtschreibung | 10 |
| Sprache | 10 |
| Inhalt | 10 |
| Einordnung in den Kontext | 10 |
| Ansprechend für die Zielgruppe | 10 |

# Zusammenfassung
Der Scrum Guide ist eine Anleitung für Scrum und dessen Inhalt.
# Positive Aspekte

- Viele funktionierende Links
- Struktur
- kurze prägnante Erklärungen

# Negative Aspekte
Wie auch beim Ideenmarathon würde eine kurze Erläuterung zur Graphik noch in den Artikel passen.

2021-12-09 19:42 UTC, merged