pull request_Kennenlernspiele
ManagingProjectsSuccessfully/ManagingProjectsSuccessfully.github.io pull request #293
Opened 2021-11-24 16:47 UTC by viktoria110

2021-11-30 11:24 UTC, Theresa1703 requested changes
| Kriterium | Bewertung|
|-----|---|
| Front-Matter | ja |
| Umfang | ja |
| Belege | nein |
| Links | ja |
| Formatierung | ja |
| Verlinkungen vorhanden | ja |
| Abbildungen | ja |
| Strukturierung des Beitrags | 10 |
| Rechtschreibung | 9 |
| Sprache | 10 |
| Inhalt | 10 |
| Einordnung in den Kontext | 9 |
| Ansprechend für Zielgruppe | 10 |

# Zusammenfassung
Das Thema Kennenlernspiele wird kurz definiert und daraufhin deren Einsatz in Projekten und Beispiele jeweils für persönliche als auch Online-Kennenlernspiele gegeben.

# Positive Aspekte
- Struktur und Sprache sind gut

# Negative Aspekte
- Belege: Abbildungen und manche Absätze haben keine Quellenangabe
- Rechtschreibung: Willkommenseinsgefühls, Gallerie > Galerie, Home Office > Home-Office/Homeoffice

2021-12-06 17:37 UTC, Christoph-Mantsch commented
| Kriterium | Bewertung|
|-----|---|
| Front-Matter | ja |
| Umfang | ja|
| Belege |  nein |
| Links | ja|
| Formatierung | ja|
| Verlinkungen vorhanden | ja |
| Abbildungen | ja |
| Strukturierung des Beitrags | 9 |
| Rechtschreibung | 8 |
| Sprache |9 |
| Inhalt | 10|
| Einordnung in den Kontext | 10|
| Ansprechend für Zielgruppe | 10|

# Zusammenfassung

Zu Beginn des Beitrags wird eine Definition und erste Eindrücke des Themas Kennenlernspiele geschaffen. Zudem wird genannt, wie Kennenlernspiele in Projekten eingebunden werden können und wie dies grob abläuft. Anschließend werden 2 verschiedene Arten von Kennenlernspielen mit Beispielen differenziert: Kennenlernspiele vor Ort und im Home Office. Zuletzt wird auch eine Verbindung zum allgegenwärtigen Thema "Covid-19-Pandemie" hergestellt. 

# Positive Aspekte

Der Artikel ist sehr übersichtlich und informativ gelungen. Die Struktur sowie die Sprache des Beitrags ist positiv. 
Zudem bietet der Beitrag dem Leser, der sich mit dieser Thematik zu Beginn nicht auskennt, eine sehr gute Übersicht.
Inhaltlich ist der Beitrag auch sehr überzeugend und auch in den Kontext sehr gut eingeordnet. 

# Negative Aspekte

Bei den Quellenangaben kommt es häufig zu Dopplungen. Es würde reichen, eine Quelle nur einmal anzugeben und im Text mit derselben Anmerkungsziffer darauf Bezug zu nehmen. 
Teilweise sehr verschachtelte Sätze.
Kommasetzungsfehler: Zeile 13 nach dem Wort "geringer", Zeile 63 nach dem Wort "Gelegenheit".

2021-12-06 21:02 UTC, Christoph-Mantsch reviewed
| Kriterium | Bewertung|
|-----|---|
| Front-Matter | ja |
| Umfang | ja|
| Belege |  nein |
| Links | ja|
| Formatierung | ja|
| Verlinkungen vorhanden | ja |
| Abbildungen | ja |
| Strukturierung des Beitrags | 9 |
| Rechtschreibung | 8 |
| Sprache |9 |
| Inhalt | 10|
| Einordnung in den Kontext | 10|
| Ansprechend für Zielgruppe | 10|

# Zusammenfassung

Zu Beginn des Beitrags wird eine Definition und erste Eindrücke des Themas Kennenlernspiele geschaffen. Zudem wird genannt, wie Kennenlernspiele in Projekten eingebunden werden können und wie dies grob abläuft. Anschließend werden 2 verschiedene Arten von Kennenlernspielen mit Beispielen differenziert: Kennenlernspiele vor Ort und im Home Office. Zuletzt wird auch eine Verbindung zum allgegenwärtigen Thema "Covid-19-Pandemie" hergestellt.


# Positive Aspekte

Der Artikel ist sehr übersichtlich und informativ gelungen. Die Struktur sowie die Sprache des Beitrags ist positiv.
Zudem bietet der Beitrag dem Leser, der sich mit dieser Thematik zu Beginn nicht auskennt, eine sehr gute Übersicht.
Inhaltlich ist der Beitrag auch sehr überzeugend und auch in den Kontext sehr gut eingeordnet.

# Negative Aspekte

Bei den Quellenangaben kommt es häufig zu Dopplungen. Es würde reichen, eine Quelle nur einmal anzugeben und im Text mit derselben Anmerkungsziffer darauf Bezug zu nehmen.
Teilweise sehr verschachtelte Sätze.
Kommasetzungsfehler: Zeile 13 nach dem Wort "geringer", Zeile 63 nach dem Wort "Gelegenheit".

2021-12-07 15:51 UTC, Christoph-Mantsch requested changes
| Kriterium | Bewertung|
|-----|---|
| Front-Matter | ja |
| Umfang | ja|
| Belege |  nein |
| Links | ja|
| Formatierung | ja|
| Verlinkungen vorhanden | ja |
| Abbildungen | ja |
| Strukturierung des Beitrags | 9 |
| Rechtschreibung | 8 |
| Sprache |9 |
| Inhalt | 10|
| Einordnung in den Kontext | 10|
| Ansprechend für Zielgruppe | 10|

# Zusammenfassung

Zu Beginn des Beitrags wird eine Definition und erste Eindrücke des Themas Kennenlernspiele geschaffen. Zudem wird genannt, wie Kennenlernspiele in Projekten eingebunden werden können und wie dies grob abläuft. Anschließend werden 2 verschiedene Arten von Kennenlernspielen mit Beispielen differenziert: Kennenlernspiele vor Ort und im Home Office. Zuletzt wird auch eine Verbindung zum allgegenwärtigen Thema "Covid-19-Pandemie" hergestellt.


# Positive Aspekte

Der Artikel ist sehr übersichtlich und informativ gelungen. Die Struktur sowie die Sprache des Beitrags ist positiv.
Zudem bietet der Beitrag dem Leser, der sich mit dieser Thematik zu Beginn nicht auskennt, eine sehr gute Übersicht.
Inhaltlich ist der Beitrag auch sehr überzeugend und auch in den Kontext sehr gut eingeordnet.

# Negative Aspekte

Bei den Quellenangaben kommt es häufig zu Dopplungen. Es würde reichen, eine Quelle nur einmal anzugeben und im Text mit derselben Anmerkungsziffer darauf Bezug zu nehmen.
Teilweise sehr verschachtelte Sätze.
Kommasetzungsfehler: Zeile 13 nach dem Wort "geringer", Zeile 63 nach dem Wort "Gelegenheit".

2021-12-08 16:40 UTC, LucaH12 requested changes
| Kriterium | Bewertung|
|-----|---|
| Front-Matter | ja |
| Umfang | ja|
| Belege |  ja |
| Links | ja|
| Formatierung | ja|
| Verlinkungen vorhanden | ja |
| Abbildungen | ja |
| Strukturierung des Beitrags | 10 |
| Rechtschreibung | 9 |
| Sprache |10 |
| Inhalt | 10|
| Einordnung in den Kontext | 10|
| Ansprechend für Zielgruppe | 10|

# Zusammenfassung

Nach einer kurzen Definition wird der Einsatz von Kennenlernspielen in Projekten diskutiert und anschließend Beispiele von Kennenlernspielen aufgezeigt. 
Anschließend geht es darum, wie sich Kennenlernspiele vor Ort umsetzen lassen.
Zuletzt wird auf die Corona-Pandemie eingegangen und Beispielspiele genannt, die auch im Home-Office umgesetzt werden können.

# Positive Aspekte

- gute Struktur: Man wird verständlich in das Thema eingeführt und findet sich gut zurecht
- sehr gute Orientierung an Beispielen: viele praktische Beispiele, gut erklärt
- viele Quellen, gut belegt und viele Verlinkungen
- nahezu fehlerfreie Sprache und Rechtschreibung
- sehr schöner Bezug auf die Covid-Pandemie und wie Kennenlernspiele auch Online stattfinden können

# Negative Aspekte

- Kommasetzung in Zeile 13 nach "geringer" und Zeile 63 nach "Gelegenheit"
- "Willkommenseinsgefühls" klingt komisch
- Quelle für Abbildung nicht auffindbar

2021-12-09 19:42 UTC, merged