Extreme Programming
ManagingProjectsSuccessfully/ManagingProjectsSuccessfully.github.io pull request #308
Opened 2021-11-24 19:08 UTC by 29834

2021-12-03 20:21 UTC, Aaron-WS requested changes
| Kriterium | Bewertung|
|-----|---|
| Front-Matter | ja|
| Umfang | ja|
| Belege | ja |
| Links | ja|
| Formatierung | ja|
| Verlinkungen vorhanden | ja |
| Abbildungen | ja|
| Strukturierung des Beitrags | 10 |
| Rechtschreibung | 9|
| Sprache |10 |
| Inhalt | 10|
| Einordnung in den Kontext | 10|
| Ansprechend für Zielgruppe | 10|

# Zusammenfassung

In diesem Beitrag wird Extreme Programming erklärt. Diese agile Methode wird in der Softwareentwicklung eingesetzt. Nach einer kurzen Einleitung mit historischen Fakten erklärt der Beitrag Rollen, Werte und die Vor- und Nachteile.

# Positive Aspekte
* Du hast viele Belege benutzt.
* Die Länge der einzelnen Absätze ist ausgewogen.
* Die Abbildung ist sehr passend.

# Negative Aspekte
* Du könntest auch im Text Verlinkungen einbauen. Zum Beispiel bei Scrum und Kanban in Zeile 18.
* Du könntest mehr Tags einfügen.

2021-12-06 20:04 UTC, niru1999 requested changes
| Kriterium | Bewertung|
|-----|---|
| Front-Matter | ja |
| Umfang | ja |
| Belege | nein |
| Links | ja|
| Formatierung | ja|
| Verlinkungen vorhanden | nein |
| Abbildungen | ja |
| Strukturierung des Beitrags | 10 |
| Rechtschreibung | 9 |
| Sprache | 8 |
| Inhalt | 7 |
| Einordnung in den Kontext |10|
| Ansprechend für Zielgruppe |10|

# Zusammenfassung
Der Artikel handelt von Extreme Programming. Dabei wird auf den historischen Hintergrund eingegangen. Weiterführend werden die einzelnen Rollen und deren Werte aufgelistet. Abschließend werden auf die Vor- und Nachteile hingewiesen. 

# Positive Aspekte

- alles gut verlinkt jeder Absatz ist mit einer Quelle vermerkt
- kurz und wichtige Aspekte werden bei den Werten hervorgehoben
- Das Bild ist treffend und beschreibt den ganzen Prozess

# Negative Aspekte
- kleine Satzbau Fehler (z.B. im 3. Absatz bei Vor- und Nachteilen)
- Das Bild hat keine Bildunterschrift und die Quelle wurde nicht vermerkt
- auf das Bild wird nicht eingegangen
- man hätte auch im Text die Verlinkungen einbauen können wie

2021-12-06 23:25 UTC, NK0100 requested changes
| Kriterium | Bewertung|
|-----|---|
| Front-Matter | ja |
| Umfang | ja |
| Belege | nein |
| Links | ja |
| Formatierung | ja |
| Verlinkungen vorhanden | ja |
| Abbildungen | ja |
| Strukturierung des Beitrags | 8 |
| Rechtschreibung | 9 |
| Sprache | 9 |
| Inhalt | 8 |
| Einordnung in den Kontext | 10 |
| Ansprechend für Zielgruppe | 9 |

# Zusammenfassung

Der Artikel widmet sich dem sogenannten Extreme Programming. Extreme Programming ist neben Scrum und Kanban eine agile Entwicklungsmethode aus der Softwareentwicklung. Zunächst wird die Methode definiert und in einen chronologischen Zusammenhang gesetzt. Im Anschluss folgen die im Extreme Programming verankerten Rollen, Werte und Vor- und Nachteile, welche sich bei Anwendung der Methode ergeben können. 

# Positive Aspekte

Ich finde Deinen Artikel durchaus gelungen und informativ! Ich mag Deine sehr kurzen und treffenden Sätze, sowie die logischen Zusammenhänge, welche sich auch in der Struktur/Aufbau widerspiegeln. Darüber hinaus finde ich Deine Belege z.B. im Buch „Beck, K. (2000): Extreme Programming explained - Embrace Chance. Massachusetts: Addison-Wesley“, welche Du mit Seitenzahlen belegt hast sehr gut gewählt. Deine Links funktionieren einwandfrei und auch der Umfang von 500 Zeichen wurde erreicht. Sprachlich kann ich keine gravierenden Fehler finden. Deine gewählte Abbildung ist auch gut gewählt und ergänzt sich super mit dem dabeistehenden Text. 

# Negative Aspekte

Grundsätzlich und insbesondere am Anfang finde ich die Strukturierung Deines Artikels gut, allerdings ist es für Personen, die nicht viel Hintergrundwissen haben etwas kryptisch zu verstehen, was sich unter dem Gliederungspunkt „Werte“ verbirgt, vielleicht hätte man da gleich in der Überschrift etwas präziser arbeiten können. Auch in der Vor – und Nachteile Sektion hätte ich mir ein oder zwei Sätze mehr zum Kontext bzw. einleitend gewünscht, z.B. „Es ergeben sich im Rahmen des Extreme Programmings folgende Vor- und Nachteile: … “ – aber das ist Meckern auf hohem Niveau. Damit verbunden wäre auch ein kurzer Wrap-up am Ende ganz schön gewesen. Leider fehlt die Quellenangabe der Abbildung - vielleicht könntest Du diese noch ergänzen. Des Weiteren könntest Du auch im Text Verlinkungen einbauen, welche Du z.B. auch unten bei „siehe auch“ bereits aufgezählt hast. Aber wie bereits gesagt außer der fehlende Beleg/Quelle des Bildes, sehe ich keinen super gravierenden Fehler - good job!

2021-12-09 19:42 UTC, merged

2021-12-21 20:17 UTC, 29834 commented
@niru1999 @NK0100 @Aaron-WS 
Vielen Dank für eure Reviews! Ich habe eure Anmerkungen jetzt in meinen Artikel eingebaut und verbessert. Ich habe Verlinkungen und Tags eingefügt. Satzbaufehler im 3. Absatz wurden korrigiert und ich habe eine Bildunterschrift und Quelle meiner Abbildung eingefügt. Ich habe den Gliederungspunkt `Werte` ausgearbeitet und die Einleitung der `Vor- und Nachteile` überarbeitet. Ich bin etwas auf meine Abbildung eingegangen, konnte aber aufgrund des Wörterumfangs mein Fazit nicht länger ausarbeiten. Ebenfalls habe ich eine Tabelle für übersichtlichere Ansicht der Rollen eingefügt.