Risikotransfer
ManagingProjectsSuccessfully/ManagingProjectsSuccessfully.github.io pull request #309
Opened 2021-11-24 19:15 UTC by niru1999

2021-12-02 16:23 UTC, felixba213 requested changes
| Kriterium | Bewertung|
|-----|---|
| Front-Matter | ja |
| Umfang | ja |
| Belege | ja |
| Links | ja |
| Formatierung | ja |
| Verlinkungen vorhanden | ja |
| Abbildungen | ja |
| Strukturierung des Beitrags | 9 |
| Rechtschreibung | 9 |
| Sprache | 9 |
| Inhalt | 10 |
| Einordnung in den Kontext | 10 |
| Ansprechend für Zielgruppe | 10 | 

# Zusammenfassung

Der Artikel handelt von dem Risikotransfer. Der Risikotransfer wird dem Risikomanagement zugeordnet und steht dort für die Planung zur Risikovorbeugung, wodurch das Risiko auf dritte übertragen werden kann. Daraufhin werden verschiedene Methoden des Risikotransfers dargestellt. Hierzu zählen Versicherungen, Derivate, Factoring und Leasing die jeweils näher erläutert werden. Im Anschluss werden dann noch Vor- und Nachteile separat erläutert und es wird die Erkenntnis getroffen, dass auf lange Sicht ein ordnungsgemäß durchgeführter Risikotransfer nur Vorteile mit sich bringt.

# Positive Aspekte

Dein Artikel bietet für Außenstehende einen sehr guten ersten Überblick über die Thematik. Der Umfang von ca. 500 Wörter wurde gut eingehalten. Zudem überzeugt dein Artikel durch eine fast fehlerlose Rechtschreibung und deinen sehr interessant gestalteten Inhalt. Deine Grafik ist meiner Meinung nach auch sehr gut gewählt. Die Einordnung in den Gesamtzusammenhang ist dir ebenfalls sehr gut gelungen.

# Negative Aspekte

Bis auf ein paar Kleinigkeiten gibt dein Artikel nicht so viele negative Aspekte her. Mir ist aufgefallen, dass du andere Artikel auf GitHub nicht so wie im Template verlinkst. Dies könntest du bei Gelegenheit noch anpassen. Die Strukturierung bzw. die Wahl deiner Darstellung des 2. Gliederungspunktes (Verschiedene Methoden des Risikotransfers) würde ich etwas anders machen, aber das ist Geschmackssache. Ein kleiner Rechtschreibfehler hat sich unter dem Gliederungspunkt "Vorteile" eingeschlichen. Hier müsste es "Mit dem Risikotransfer..." heißen.

2021-12-03 19:54 UTC, Aaron-WS requested changes
| Kriterium | Bewertung|
|-----|---|
| Front-Matter | ja|
| Umfang | ja|
| Belege | ja|
| Links | ja|
| Formatierung | ja|
| Verlinkungen vorhanden | ja|
| Abbildungen | ja |
| Strukturierung des Beitrags | 10 |
| Rechtschreibung | 10|
| Sprache | 9 |
| Inhalt | 5 |
| Einordnung in den Kontext | 5 |
| Ansprechend für Zielgruppe | 5|

# Zusammenfassung

Dieser Beitrag befasst sich mit Risikotransfer. Dazu werden 4 Beispiele gegeben und die Vor- und Nachteile genannt.

# Positive Aspekte

* Die Struktur des Beitrags ist sehr übersichtlich und hat einen roten Faden.
* Alle Ja-Nein Kriterien wurden erfolgreich umgesetzt.
* Der Beitrag lässt sich flüssig lesen und hat keine Rechtschreibfehler.

# Negative Aspekte

* Der Beitrag passt, meiner Meinung nach, eher in den Kontext Geschäftsrisiken als in den Kontext Projektmanagement. Ich denke das liegt an dem Fokus auf finanzielle Risiken, statt zum Beispiel das Risiko des Scheiterns eines Projektes zu betrachten.
* Die Zielgruppe Start-up Gründer findet in diesem Beitrag keine Informationen für einen Risikotransfer, obwohl jedes Start-up das Risiko hat nicht wirtschaftlich zu sein. (siehe Fazit)

2021-12-07 00:19 UTC, NK0100 requested changes
| Kriterium | Bewertung|
|-----|---|
| Front-Matter | ja |
| Umfang | ja |
| Belege | ja |
| Links | ja |
| Formatierung | ja |
| Verlinkungen vorhanden | ja |
| Abbildungen | ja |
| Strukturierung des Beitrags | 10 |
| Rechtschreibung | 9 |
| Sprache | 10 |
| Inhalt | 8 |
| Einordnung in den Kontext | 7 |
| Ansprechend für Zielgruppe | 7 |

# Zusammenfassung

Der Artikel befasst sich mit dem Thema Risikotransfer im Projektmanagement und umfasst vier Methoden des Risikotransfers: Versicherungen, Derivate, Factoring und Leasing, sowie damit verbunden Vor- und Nachteilen und ein abschließendes Fazit. Per Definition steht der Risikotransfer im Risikomanagement für die Planung zur Risikovorbeugung.


# Positive Aspekte

Ich finde Deinen Artikel gelungen und informativ! Ich mag Deine vollständige und sehr durchdachte Strukturierung des Artikels, welche sogar ein Inhaltsverzeichnis enthält. Auch Deine Links im Text und im „Anhang“ funktionieren einwandfrei. Gleiches gilt für die Anzahl an Zeichen bzw. den Umfang von mind. 500 Wörtern. Darüber hinaus ist Deine Abbildung sehr gut verständlich und mit Quelle versehen. Auch wurden alle Ko-Kriterien erfüllt. 


# Negative Aspekte

Grundsätzlich lassen sich nicht viele Verbesserungsmöglichkeiten finden, jedoch ist für mich als Leser der Gap von den verschiedenen Methoden zu den Vor- und Nachteilen zu groß, da erst bei letzterem und in der Einleitung wirklich auf den Projektbezug eingegangen wird aber nicht die Zusammenhänge. Ich denke das könnte man mit zusätzlicher Literatur vielleicht noch etwas schlüssiger gestalten. Damit komme ich auch schon zu meinem zweiten kleinen Kritikpunkt, die Anzahl der Quellen und „Siehe auch“ Links könnten etwas mehr sein. Ein kleiner Rechtschreibfehler hat sich leider unter 3. Vorteile bei „Mit den Risikotransfer“ statt „Mit dem Risikotransfer“ eingeschlichen. Zuletzt ist mir noch aufgefallen, dass Dein Inhaltsverzeichnis eine Nummerierung aufweist, allerdings in den Überschriften im Text nicht – vielleicht kannst Du das noch ergänzen. Nichtsdestotrotz sehr informativ – good job!

2021-12-09 19:42 UTC, merged

2021-12-21 19:34 UTC, niru1999 commented
@felixba213 ich bedanke mich bei dir für deine hilfreiche Review. Ich habe man Rechtschreibfehler ausgebessert und die Verlinkungen auch korrigiert. Ich habe sehr lange darüber nachgedacht wie ich es anders gliedern sollte, bin aber zum Entschluss gekommen das es mir so am besten gefällt aber dennoch vielen dank

2021-12-21 19:56 UTC, niru1999 commented
@Aaron-WS danke für deine Review. Ich hab sie mir durchgelesen und kann dir leider nicht ganz zu stimmen. Beim Risikotransfer geht es nun mal darum, die finanziellen Risiken zu verringern. Dies gilt auch für Start-ups und die Methoden die im Beitrag erwähnt wurden können auch von denen ausgeübt werden. Dennoch bedanke ich mich für deine Review.

2021-12-21 20:27 UTC, niru1999 commented
@NK0100 vielen Dank für deine Review. Ich habe versucht auf all deine Punkte einzugehen. Ich wünscht ich könnte den Gap zwischen den Methoden und den Vor- und Nachteilen verringern, jedoch muss ich die maximale Anzahl er Wörter einhalten und das würde den Rahmen sprengen. Ich habe es mit zusätzlicher Literatur versucht. Die Nummerierung war so gewollt da es bei Wikipedia meistens auch so gemacht wird.  Ich bedanke mich bei dir.