Virtual Reality
ManagingProjectsSuccessfully/ManagingProjectsSuccessfully.github.io pull request #311
Opened 2021-11-24 19:30 UTC by NK0100

2021-12-02 16:22 UTC, felixba213 requested changes
| Kriterium | Bewertung|
|-----|---|
| Front-Matter | ja |
| Umfang | nein |
| Belege | ja |
| Links | nein |
| Formatierung | ja |
| Verlinkungen vorhanden | ja |
| Abbildungen | ja |
| Strukturierung des Beitrags | 10 |
| Rechtschreibung | 9 |
| Sprache | 9 |
| Inhalt |  10 |
| Einordnung in den Kontext | 10 |
| Ansprechend für Zielgruppe | 9 |

# Zusammenfassung

Der Artikel zum Thema Virtual Reality bietet einen sehr guten Überblick über dieses Themengebiet. Es beginnt mit einem guten und ansprechenden Einstieg, darauf folgt die Definition von Virtual Reality und die Abgrenzung zu Augmented Reality und Mixed Reality. Der Anwendungsbereich von Virtual Reality wird sehr ausführlich erläutert und dabei wird deutlich das der Einsatz der VR-Technologien im Projektmanagement sehr vielfältig ist. Der Einsatz von VR führt unter anderem häufig zu engagierteren Mitarbeitern und erhöht auch die Produktion. Diese beiden sind nur zwei von vielen Vorteilen die dargestellt werden. Neben Vor- und Nachteilen wird die SWOT-Analyse zur Implementierung von AR/VR-Technologien verwendet. Abschließend wird ein Blick auf die Möglichkeiten der Zukunft geworfen, die für die VR im Projektmanagement sehr vielversprechend klingen.

# Positive Aspekte

Deine Strukturierung und deine Formatierung sehen sehr gut aus. Dies vermittelt dem Leser direkt ein positives Bild von deinem Artikel. Auch inhaltlich ist dein Artikel sehr gut gestaltet, dabei wird es beim Lesen keineswegs langweilig und man lernt einige neue Dinge dazu. Zudem wurde der Artikel gut in den Gesamtzusammenhang eingeordnet und ist deshalb bis auf ein zwei negative Aspekte ein sehr gelungener Artikel.

# Negative Aspekte

Ich schätze deine Mühe und deinen Aufwand, jedoch sollte der Umfang das nächste mal besser eingehalten werden. Es waren ca. 500 Wörter dafür angesetzt und dieser Artikel kommt auf mehr als 1500. Ein weiteres KO-Kriterium, das nicht eingehalten wurde sind die Links, bei denen einige nicht funktionieren oder nicht zielführend sind. Bsp.: "Phasen des Projektmanagements" führt zu einem Ordner, bei "SWOT-Analyse" kommt eine Fehlermeldung (Error 404), obwohl "SWOT-Analyse" unter dem Gliederungspunkt "Siehe auch" richtig verlinkt wurde. Wenn man einen Unterpunkt macht (4.1) sollte man wenn möglich auch einen zweiten (4.2) machen, aber das ist auch Geschmackssache. Ein paar kleine Rechtschreibfehler haben sich eingeschlichen, wie zum Beispiel "potenzeielle Einfluss...". Dies ist aber halb so wild, denn es ist menschlich mal ein zwei kleine Rechtschreibfehler zu machen. Bezüglich des Satzbaus ist es empfehlenswert, die sehr langen Sätze durch einen Punkt zu trennen, damit sie für den Leser leichter verständlich sind. (siehe SWOT-Analyse Absatz) Außerdem ist mir noch aufgefallen, dass dein Bild, nicht wie im Template vorgegeben, verlinkt ist. Vielleicht kannst du das noch anpassen.

2021-12-08 16:43 UTC, TobiasVoigt92 requested changes
| Kriterium | Bewertung|
|-----|---|
| Front-Matter | ja |
| Umfang | nein |
| Belege | ja |
| Links | nein |
| Formatierung | ja |
| Verlinkungen vorhanden | ja |
| Abbildungen | ja |
| Strukturierung des Beitrags | 10 |
| Rechtschreibung | 9 |
| Sprache | 9 |
| Inhalt | 10 |
| Einordnung in den Kontext | 10 |
| Ansprechend für Zielgruppe | 9 |

# Zusammenfassung

Der Beitrag befasst sich mit dem Thema Virtual Reality. Durch die Globalisierung und die Tatsache, dass Fernarbeit immer mehr an Bedeutung gewinnt, stehen Unternehmen vor der Herausforderung die Kommunikation und Durchführung von Projekten virtuell zu organisieren. Ideal dafür sind beispielsweise virtuelle Konferenzen, welche durch Virtual Reality tools lebendiger werden und mehr Interaktionen fördern. Im Gegensatz dazu werden bei Augmented Reality Dinge die nicht vorhanden sind hinzugefügt oder welche die schon da sind, verbessert. Die Verknüpfung der realen und digitalen Welt wird als Mixed Reality bezeichnet. Schon heute findet Virtual Reality Anwendung in vielen Branchen. Den Vorteilen von geringeren Kosten und weniger Umweltbelastung steht die Gefahr des Verlustes von realen Interaktionen gegenüber. Die Investitionen und Weiterentwicklung in diese Technologie steigt und es ist zu erwarten, dass es in naher Zukunft so bleibt oder zu einem weiteren Anstieg kommt. 

# Positive Aspekte

* Inhaltlich sehr gelungen und informativ 
* Gut und schlüssig strukturiert 
* Verlinkungen funktionieren einwandfrei 
* Gute Rechtschreibung Grammatik 

# Negative Aspekte

* Umfang nicht erfüllt 
* Links korrigieren 

Ideen zum Upgrade:
* Anwendungsbeispiele reduzieren 
* SWOT Analyse weglassen

2021-12-08 16:46 UTC, Constll requested changes
| Kriterium | Bewertung|
|-----|---|
| Front-Matter | ja |
| Umfang | nein|
| Belege | ja |
| Links | nein |
| Formatierung | ja |
| Verlinkungen vorhanden | ja |
| Abbildungen | ja |
| Strukturierung des Beitrags | 9 |
| Rechtschreibung | 9 |
| Sprache | 10 |
| Inhalt | 10 |
| Einordnung in den Kontext | 10 |
| Ansprechend für Zielgruppe | 10 |

# Zusammenfassung

Der Artikel befasst sich mit dem Thema Virtual Reality im Projektmanagement. Anfangs wird VR definiert und gegenüber anderen Technologien abgegrenzt. Es wird auf die Anwendungsbereiche eingegangen und es werden die Vorteile sowie auch die Nachteile von Virtual Reality im Kontext mit dem Projektmanagement beleuchtet. Außerdem wird eine SWOT-Analyse durchgeführt und zum Schluss die Future Trends vorgestellt.

# Positive Aspekte

Die Belege sind vollständig und es gibt Verlinkungen zu anderen Artikeln, außerdem sind Abbildungen, sowie auch eine Tabelle vorhanden.
Der Artikel hat eine gute Strukturierung und passende Überleitungen zwischen den Unterpunkten. Sehr schön und anschaulich finde ich die SWOT-Analyse.

# Negative Aspekte

Der Umfang des Beitrags ist mit etwas mehr als 1500 Wörtern zu groß geraten.
Einige Links im Fließtext funktionieren nicht bzw. führen entweder zu externen Quellen oder nicht zu dem richtigen Github-Artikel.
Um die Übersichtlichkeit noch etwas zu verbessern, würde ich die Vor- und Nachteile von VR im PM jeweils als einzelne Überschrift aufführen.

2021-12-09 19:42 UTC, merged

2021-12-22 18:53 UTC, NK0100 commented
@Constll @felixba213 @TobiasVoigt92 vielen lieben Dank für Eure Reviews und Verbesserungsvorschläge. Ich habe die Links überarbeitet, Vor- und Nachteile separat mit Unterpunkten aufgeführt und so viel wie möglich gekürzt (es ist immer noch etwas viel :D). Die SWOT Analyse habe ich jedoch im Artikel beibehalten, da ich finde sie zeigt wichtige Punkte passend zum Thema auf.  Anbei ein Link zum überarbeiteten Artikel zum Thema [Virtual Reality](https://github.com/NK0100/ManagingProjectsSuccessfully.github.io/blob/main/kb/Virtual_Reality.md)