Digitalisierung im PM
ManagingProjectsSuccessfully/ManagingProjectsSuccessfully.github.io pull request #315
Opened 2021-11-24 19:58 UTC by Viktoria1412

Ein Artikel ist nicht verlinkt, weil ich den Github Namen bei den forks nicht finden konnte. Das wird noch erledigt.

2021-12-07 19:12 UTC, enesmvlt requested changes
| Kriterium | Bewertung|
|-----|---|
| Front-Matter | ja |
| Umfang | ja |
| Belege | ja |
| Links | ja |
| Formatierung | ja |
| Verlinkungen vorhanden | ja |
| Abbildungen | ja |
| Strukturierung des Beitrags | 10 |
| Rechtschreibung | 10|
| Sprache | 9 |
| Inhalt | 9 |
| Einordnung in den Kontext | 10|
| Ansprechend für Zielgruppe | 10|

# Zusammenfassung
Der Artikel beschreibt zuerst kurz, dass Digitalisierung sehr kontextabhängig ist und verschafft so von Anfang an, einen klaren Blick zur Einordung der Thematik. Bei der Digitalisierung im Projektmanagement ist vor allem der Einsatz von digitalen Geräten und Werkzeugen. Diese Neurungen tragen so einen erheblichen Beitrag zu einer effizienteren Art zu Arbeiten im Projektmanagement. Damit zusammenhängend wird der Fokus auf das Datenmanagement und auf die Kommunikation. Im Datenmanagement werden digitale Kommunikationsplattformen wie bspw. Trello und Cloudtechnologien als Beispiele für die erleichterten Datenaustausch und den verbesserten Überblick aufgezeigt. So ist vor allem die Kommunikation im Projektmanagement ein relevanter Faktor für den Projekterfolg. Zu den Potenzialen der Digitalisierung im Projektmanagement gehören so die Möglichkeiten: mehrere Projekte gleichzeitig ausführen zu können, da man einen besseren Überblick hat, eine gesteigerte Effizienz durch eine bessere Analyse von Daten und eine leichtere Einbindungsmöglichkeit von externen Partnern. Neben den Potentialen, werden ebenfalls Herausforderungen wie: die Notwendigkeit einer genaueren Schwerpunktsetzung in Projekten und die anspruchsvolle Aufgabe, Strukturen im Unternehmen zu digitalisieren. Hierzu wird im Beitrag die Abbildung „Unternehmerische Herausforderungen bei der Digitalisierung“ aufgezeigt.

# Positive Aspekte
Der Front-Matter ist korrekt ausgefüllt und der Text danach ist direkt angehängt. Der Artikel gibt einen sehr guten Einblick in die Digitalisierung von PM. Er hilft den Begriff der Digitalisierung richtig einzuordnen und geht auf einige fundamentale Merkmale ein. Hierbei ist die Sprache sehr sachlich und prägnant gewählt. Beim Lesen des Artikels wird man gut an das Thema hingeführt. So kann man sich am Ende des Artikels besser in die Herausforderungen reindenken. Die eingebetteten Links funktionieren und führen einen schnell weiter. Die Verlinkungen zu anderen Artikeln im Kompendium funktionieren zum Großteil.

# Negative Aspekte
Im Abschnitt „Grundlegende Aspekte der Digitalisierung im Projektmanagement“ ist im Text der Zeilenabstand größer als im restlichen Text. In den Unterpunkten sind keine Abschnitte und der Zeilenabstand ist hier wieder geringer als in den übrigen Textpassagen.

2021-12-08 12:55 UTC, Viktoria1412 commented
@enesmvlt Hey, danke erstmal für das Review!
Das mit den Zeilenabständen werde ich auf jeden Fall einheitlicher gestalten. Ich wollte aber mal bezüglich der fehlenden Abschnitte bei den Unterpunkten fragen, was du damit meinst? 
Auch wäre es echt hilfreich, wenn du mir sagen könntest, was ich an der Sprache und inhaltlich verbessern kann bzw. wieso Punkte abgezogen wurden, um es dann bei der finalen Abgabe besser zu machen. :)
Wäre dankbar über eine Antwort!

2021-12-08 17:42 UTC, seriousTake requested changes
| Kriterium | Bewertung|
|-----|---|
| Front-Matter | ja |
| Umfang | ja |
| Belege | ja |
| Links | ja |
| Formatierung | ja |
| Verlinkungen vorhanden | ja |
| Abbildungen | ja |
| Strukturierung des Beitrags | 9 |
| Rechtschreibung | 10 |
| Sprache | 10 |
| Inhalt | 8 |
| Einordnung in den Kontext | 10 |
| Ansprechend für Zielgruppe | 10 |

# Zusammenfassung

Der Beitrag befasst sich mit der Digitalisierung im PM. Beide Begriffe werden erst einzeln erklärt und im Anschluss im gemeinsamen Kontext definiert. Im Anschluss werden grundlegende Aspekte angesprochen. Es wird erklärt wie wichtig und hilfreich die Nutzung von modernen Geräten und Software im PM ist. Darunter fällt die Planung und Kommunikation. Potenziale wie die steigende Effizienz bzw. Produktivität des Teams werden näher betrachtet. Als letztes werden Herausforderungen betrachtet, wo z.B. die fehlende Flexibilität von Unternehmen genannt wird.

# Positive Aspekte

Die Strukturierung des Beitrags ist gelungen, da man einen sanften Einstieg in das Thema genießt, danach aber direkt das Wesentliche betrachtet. Potenziale und Herausforderungen lesen sich wie Vor- und Nachteile. Der Beitrag ist informativ und für jeden verständlich genug geschrieben. Die Rechtschreibung und Grammatik scheint vollkommen in Ordnung zu sein. Die Grafik passt zum Thema.

# Negative Aspekte

Ein Fazit, welches nicht nur Vor- und Nachteile anspricht fehlt. Hier könnte man z.B. Zukunftsprognose durchführen.

2021-12-08 18:47 UTC, enesmvlt commented
> @enesmvlt Hey, danke erstmal für das Review!
> Das mit den Zeilenabständen werde ich auf jeden Fall einheitlicher gestalten. Ich wollte aber mal bezüglich der fehlenden Abschnitte bei den Unterpunkten fragen, was du damit meinst?
> Auch wäre es echt hilfreich, wenn du mir sagen könntest, was ich an der Sprache und inhaltlich verbessern kann bzw. wieso Punkte abgezogen wurden, um es dann bei der finalen Abgabe besser zu machen. :)
> Wäre dankbar über eine Antwort!

Hey, mit den Abschnitten meinte ich, dass bei  „Datenmanagement“ und „Kommunikation“ keine Abschnitte drin sind. Im restlichen Text haben kürzere Passagen dennoch Abschnitte. Diese Stellen stechen dann nur etwas heraus. Inhaltlich könnte man evtl. noch ein Fazit schreiben :)

2021-12-08 20:32 UTC, Viktoria1412 commented
Alles klar. Werde schauen, wie ich das besser machen kann. 
Danke!

2021-12-08 22:40 UTC, 12Yousuf requested changes
| Kriterium | Bewertung|
|-----|---|
| Front-Matter | ja |
| Umfang | ja |
| Belege | ja |
| Links | ja |
| Formatierung | ja |
| Verlinkungen vorhanden | ja |
| Abbildungen | ja |
| Strukturierung des Beitrags | 9|
| Rechtschreibung | 10|
| Sprache | 10|
| Inhalt | 10|
| Einordnung in den Kontext | 10|
| Ansprechend für Zielgruppe | 10|

# Zusammenfassung

In dem Artikel wird im Rahmen des Projektmanagements auf die Digitalisierung eingegangen. Zunächst werden die Begrifflichkeiten definiert bzw. erklärt. Anschließend wurden die grundlegenden Aspekte der Digitalisierung im Projektmanagement mittels der zwei Unterpunkte Datenmanagement und Kommunikation erläutert. Hier geht es vor allem darum, wie groß und entscheidend die Arbeit mit digitalen Arbeitsgeräten momentan ist. Diese helfen nämlich nicht nur bei der Gestaltung von Projekten sondern optimieren die Kommunikation innerhalb eines Projektes, so dass Informationen viel leichter ausgetauscht werden können. 
Des Weiteren wird im Artikel auf das Potenzial eines Projektes in Verbindung mit der Digitalisierung und den daraus folgenden Herausforderungen erläutert. Dadurch, dass man nun mit digitalen Speichermedien viel effizienter arbeitet, steigen auch zeitgleich die Erwartungen. Dies wird zum Schluss mittels einer Abbildung dargestellt.   

# Positive Aspekte

Der Artikel beginnt zunächst mit dem Klären der Begrifflichkeiten und führt im Anschluss zum Hauptthema. Das verleiht dem Beitrag Struktur und macht es dem Leser einfach sich mit der ganzen Thematik vertraut zu machen. Die Sprache ist einfach und sachlich gehalten worden. Außerdem ist die Grafik passend ausgewählt worden, da diese die Herausforderungen nochmals neben der Erklärung besser verdeutlichen. Sowohl die Verlinkungen mit den anderen Beiträgen als auch die Quellen lassen sich formgemäß öffnen. 

# Negative Aspekte

Nach dem Front-Matter fände ich es schöner, wenn der Artikel mit einer Überschrift beginnen würde und nicht direkt mit dem Inhalt. 
Ein Inhaltsverzeichnis würde es dem Leser einfacher machen sich zu Beginn mit der Struktur des Beitrags vertraut zu machen.

2021-12-09 19:48 UTC, merged