Add Projektmanagement_Branchenspezifisch.md
ManagingProjectsSuccessfully/ManagingProjectsSuccessfully.github.io pull request #316
Opened 2021-11-24 20:10 UTC by enesmvlt

2021-12-07 14:40 UTC, laradag requested changes
| Kriterium | Bewertung|
|-----|---|
| Front-Matter | ja |
| Umfang | ja |
| Belege | ja |
| Links | ja |
| Formatierung | ja |
| Verlinkungen vorhanden | ja |
| Abbildungen | ja |
| Strukturierung des Beitrags | 10 |
| Rechtschreibung | 9 |
| Sprache | 10 |
| Inhalt | 10 |
| Einordnung in den Kontext | 10|
| Ansprechend für Zielgruppe | 10|

# Zusammenfassung

Der Artikel befasst sich mit dem branchenspezifischen Projektmanagement. Es wird zunächst durch die Erklärung von "Projekt" und "Projektmanagement" zu dem Thema hingeführt und anschließend auf Inhalte zu den Branchen, branchenspezifische Charakteristika, Unternehmensumfeld und branchenspezifischen Anforderungen eingegangen.

# Positive Aspekte

Der Artikel gibt einen sehr guten Einblick in das branchenspezifische Projektmanagement. Die Struktur ist hierbei sehr gut gedacht, da durch die vorangehende Definition von Projekt und Projektmanagement allgemein zum Thema hingeführt wird.
Es wurde stets eine sachliche Sprache benutzt v.A. das Kapitel "siehe auch" ist sehr gut an Wikipedia angelehnt.
Die Abbildung ist äußerst passend gewählt und der Inhalt im allgemeinen sehr gut vermittelt.

# Negative Aspekte
Der Bereich unter Front-Matter und über der Überschrift "Projekt" (Kurzbeschreibung zu Projektmanagement [...] oben im Front-Matter (Bereich zwischen den ---).) kann aus dem Beitrag gelöscht werden, da es sich um Instruktion handelt.
Im letzten Satz des zweiten Kapitels "Projektmanagement" kann "Gleichermaßen **ist es einer der Nebenziele**," mit "Gleichermaßen ist es **eines** der Nebenziele" oder "Gleichermaßen **sind es** Nebenziele" ersetzt werden.
Beim Kapitel "Branchenspezifische Anforderungen" im 5. Satz kann "**Bei** komplizierteren Projekten ist dann die Reden" mit "**Von** komplizierteren Projekten ist dann die Rede" ersetzt werden.

2021-12-08 17:22 UTC, seriousTake requested changes
| Kriterium | Bewertung|
|-----|---|
| Front-Matter | ja |
| Umfang | nein |
| Belege | ja |
| Links | ja |
| Formatierung | ja |
| Verlinkungen vorhanden | ja |
| Abbildungen | ja |
| Strukturierung des Beitrags | 9 |
| Rechtschreibung | 10 |
| Sprache | 10 |
| Inhalt | 8 |
| Einordnung in den Kontext | 9 |
| Ansprechend für Zielgruppe | 9 |

# Zusammenfassung

Der Beitrag befasst sich mit dem branchenspezifischen Projektmanagement. Zuerst wird das Projektmanagement erklärt bevor man auf branchenspezifische Eigenschaften eingeht. Dies ist kurz gefasst, da es auch nicht das eigentliche Thema ist. Im Anschluss wird angemerkt, dass eben das Anwenden in verschiedenen Branchen unterschiedliche Probleme birgt. Hier werden auch verschiedene Charakteristika aufgeführt. Das Unternehmensumfeld ist anscheinend ein wichtiger Faktor im Lösungsfindungsprozess. Durch eine Grafik wird mit einer kurzen Erklärungen auch dargestellt, warum jede Branche verschiedene Anforderungen im PM hat. Das auch so z.B. sich für das klassische oder agile PM entschieden wird. Dies kommt einem Fazit gleich.

# Positive Aspekte

Die Strukturierung des Beitrags ist gut gelungen, da erst allgemein in das Thema eingeführt wird und danach das spezifische Problem bzw. Thema genauer betrachtet wird. Die Grafik ist sinnvoll eingesetzt worden. Es finden keine Abschweifungen vom eigentlichen Thema statt. Sprache und Rechtschreibung sind einwandfrei.

# Negative Aspekte

Es ist schade, dass es kein zusätzliches Fazit gibt, welches alles noch genauer zusammenfasst. Es scheinen, etwas weniger als 500 Wörter zu sein. Das Thema scheint teilweise nur oberflächlich bearbeitet worden zu sein(deshalb Inhalt 8).

2021-12-08 22:46 UTC, 12Yousuf requested changes
| Kriterium | Bewertung|
|-----|---|
| Front-Matter | ja |
| Umfang | ja |
| Belege | ja |
| Links | ja |
| Formatierung | ja |
| Verlinkungen vorhanden | ja |
| Abbildungen | ja |
| Strukturierung des Beitrags | 9 |
| Rechtschreibung | 10|
| Sprache | 10 |
| Inhalt | 10|
| Einordnung in den Kontext | 10|
| Ansprechend für Zielgruppe | 10|

# Zusammenfassung

Zu Beginn des Artikels wird auf das Hauptthema hingeführt, indem die Begrifflichkeiten „Projekt“ und „Projektmanagement“ erklärt werden. Anschließend geht es um das Projektmanagement in verschiedenen Branchen und Branchenspezifische Charakteristika.  Hier wird veranschaulicht, welche Rolle das Projektmanagement in den verschiedenen Branchen spielt und welche Funktionen bzw. Charakteristika dabei entscheidend sind. 
Ein weiterer wichtiger Faktor ist das Unternehmensumfeld, worauf im Anschluss eingegangen wird.  Zuletzt wird mittels einer Abbildung die Branchenspezifischen Anforderungen dargestellt und anschließend erklärt. 

# Positive Aspekte

Der Artikel ist gut gelungen, da dieser unter anderem sehr übersichtlich ist. Mit den Erklärungen der Begrifflichkeiten zu Beginn wird gut zum Thema hingeführt. Des Weiteren wurde stets eine sachliche Sprache verwendet. Die Abbildung ist auch sehr passend ausgewählt worden und unterstützt den Lesern dabei die Branchenspezifischen Anforderungen zusammen mit den Erklärungen besser zu verstehen.   

# Negative Aspekte

Der Text in dem Bereich über der ersten Überschrift „Projekt“ sollte rausgelöscht werden, da dieser noch aus dem unbearbeiteten Review Template stammt. 
Es wäre schön gewesen, wenn der Artikel noch ein Inhaltsverzeichnis gehabt hätte, welches dem Leser zu Beginn einen direkten Einblick über die Thematiken des Artikels gegeben hätte.

2021-12-09 19:48 UTC, merged

2021-12-21 23:14 UTC, enesmvlt commented
Hallo, vielen Dank für euer ausführliches Feedback. Ich habe die genannten Verbesserungsvorschläge und Korrekturen beim Überarbeiten berücksichtigt und vorgenommen.