Fertigstellung des Beitrags zum Projektmanagement
ManagingProjectsSuccessfully/ManagingProjectsSuccessfully.github.io pull request #317
Opened 2021-11-24 20:12 UTC by seriousTake

2021-12-07 17:51 UTC, laradag requested changes
| Kriterium | Bewertung|
|-----|---|
| Front-Matter | ja |
| Umfang | ja |
| Belege | ja |
| Links | ja |
| Formatierung | ja |
| Verlinkungen vorhanden | nein |
| Abbildungen | ja |
| Strukturierung des Beitrags | 8 |
| Rechtschreibung | 8 |
| Sprache | 8 |
| Inhalt | 10 |
| Einordnung in den Kontext | 10|
| Ansprechend für Zielgruppe | 9 |

# Zusammenfassung

Im Artikel wird im Sinne des klassischen Projektmanagements "nicht-funktionale Anforderungen" betrachtet. Der Begriff wird definiert, von funktionalen Anforderungen abgegrenzt. Dies wird anhand eines Beispiels vertieft. Anschließend sich mit der Erfolgsmessung und Dokumentation von nicht-funktionalen Anforderungen beschäftigt und mit einem Fazit abgerundet.

# Positive Aspekte

Besonders hervorzuheben sind die verschiedenen Blickwinkel, mit denen das Thema beleuchtet wurden. Auch der Enzyklopädiestil ist durch die Struktur gegeben (z.B. Kapitel siehe auch). Es wurde ein guter Überblick über das Thema verschafft, der durch die sehr gute Wahl der Abbildung zusätzlich unterstrichen wurde. Die Belege wurden zu den Quellen verlinkt, welche sich stets aufrufen lassen haben.

# Negative Aspekte

Allgemein kann die Struktur des Artikels optimiert werden. So ließe sich 1. Definition und Unterschied zu funktionalen Anforderungen in zwei Kapitel aufteilen - 1. Definition, 2. Unterschiede.
Wenn es von mir richtig verstanden wurde, sind außerdem die Kapitel "Fazit", "siehe auch " und "Quellen" auf derselben Hierarchiestufe, wie die nummerierten Kapitel. Deshalb wäre die Nummerierung dieser Kapitel ebenfalls sinnvoll (4. Fazit, 5. Siehe auch, 6. Quellen).

Es wurde auf keine der anderen Themenbereiche verlinkt, hierbei würde sich die direkte Verlinkung von Themen, wie z.B. "Projektmanagement", "funktionale Anforderungen", "Anforderungsmanagement" und "Erfolgsmessung" ergeben.

Zum Teil fehlen Quellenangaben, wie z.B. unter 1. im letzten Absatz, im Absatz zum Smartphonespiel (ich bin mir nicht sicher, ob das Beispiel selbst ausgedacht ist und sich deshalb auf keine Quelle bezieht oder ob die Verlinkung fehlt), im 2. Kapitel die letzten 3 Sätze vor der Abbildung, im 3. Kapitel der letzte Satz.

Sprachlich wurde meist der sachliche Stil eingehalten. An einigen wenigen Punkten gibt es Verbesserungsvorschläge z.B.: Nominalstil in den Überschriften: 2. Erfolgsmessung, 3. Dokumentation von nicht-funktionalen Anforderungen.
Im 1. Kapitel klingt das "wie bereits erwähnt" nicht sachlich.
Der 1. Satz des Beispiels klingt ebenfalls unsachlich. Ein Verbesserungsvorschlag wäre beispielsweise: "Zur Veranschaulichung wird folgender Auftrag betrachtet."
Unwissenschaftliche Worte wie "selbstverständlicherweise" , "eventuell" oder "versuchen" (persönliche Einschätzung und Geschmackssache, an sich auf keinen Fall falsch)

Bezüglich der Rechtschreibung sollte sich im Allgemeinen entschieden werden, ob "Nicht-Funktionale" und "Funktionale" oder "nicht-funktionale" und "funktionale" geschrieben wird, jedoch nicht gemischt. Im Smartphonespiel-Beispiel fehlt im letzten Satz nach "erwartet" ein Komma. Im letzten Satz vor der Abbildung ist nach "stets" ein Komma zu viel. Im Fazit sollten die Spiegelpunkte einheitlich entweder mit großen oder kleinen Buchstaben beginnen.

2021-12-08 20:31 UTC, Harthauer requested changes
| Kriterium | Bewertung|
|-----|---|
| Front-Matter | ja |
| Umfang | ja|
| Belege | ja |
| Links | ja|
| Formatierung | ja|
| Verlinkungen vorhanden | nein |
| Abbildungen | ja |
| Strukturierung des Beitrags | 9 |
| Rechtschreibung | 9|
| Sprache | 9 |
| Inhalt | 10|
| Einordnung in den Kontext | 10|
| Ansprechend für Zielgruppe |10|

# Zusammenfassung

Der Artikel befasst sich mit nicht Funktionalen Anforderungen im PM. Der Begriff wird zuerst definiert und vom Funktionalen Anforderungen unterschieden und mit einem Beispiel veranschaulicht. Danach wird die Erfolgsmessung und Dokumentation von nicht-funktionalen Anforderungen erläutert. Der Beitrag endet mit einem zusammenfassendem Fazit.

# Positive Aspekte

Sehr schöne Grafiken die gut in den Beitrag eingebunden wurden. Fazit fasst alles nochmal zusammen. Das Bsp. hilft viel für das Verständnis. 

# Negative Aspekte

Über dem ersten Absatz würde ich eine Überschrift machen, es steht verloren da und passt anschaulich nicht in den Beitrag. Bei weitere Unterschiede würde ich Tabelle ausbauen. Es fehlen Verlinkungen zu anderen Beiträgen und Teilweise auch Quellen.

2021-12-08 22:50 UTC, 12Yousuf requested changes
| Kriterium | Bewertung|
|-----|---|
| Front-Matter | ja |
| Umfang | ja |
| Belege | ja |
| Links | ja |
| Formatierung | ja |
| Verlinkungen vorhanden | nein |
| Abbildungen | ja |
| Strukturierung des Beitrags | 8 |
| Rechtschreibung | 8 |
| Sprache | 9 |
| Inhalt | 10|
| Einordnung in den Kontext | 9 |
| Ansprechend für Zielgruppe |10 |

# Zusammenfassung

In dem Artikel wird im Rahmen des Projektmanagements näher auf die nicht funktionalen Anforderungen eingegangenen. Zunächst wurde anhand einer Definition die Begrifflichkeit erklärt. Anschließend wurde ein Vergleich zu den funktionalen Anforderungen gezogen, sodass der Unterschied beider ersichtlich wird. Anhand eines Beispiels wird Im Anschluss die Auswirkung der nicht funktionalen Anforderungen auf den Erfolg eines Produktes veranschaulicht. Der Artikel beschäftigt sich als letztes mit der Dokumentation nicht funktionaler Anforderungen und wird mit einem Fazit, welches die wichtigsten Anhaltspunkte darstellt, beendet. 

# Positive Aspekte

Das Thema wurde sehr gut innerhalb des Artikels erklärt. Die Tabelle stellt den Unterschied zwischen funktionalen und nicht funktionalen Anforderungen sehr gut dar. Des Weiteren wurde die Abbildung sehr passend gewählt, da diese bildlich nochmals das Erfolgspotenzial veranschaulicht.  Die Absätze wurden mit den Quellen richtig verlinkt und diese lassen sich ebenfalls formgemäß aufrufen. 


# Negative Aspekte

Zunächst wurden leider keine Verlinkungen mit anderen Beiträgen vorgenommen. Unter dem Punkt drei wurde das Wort „SRS“ nicht mit einem Beitrag verlinkt, sondern lediglich mit einer Quelle. In dem Artikel gäbe es außerdem einige Möglichkeiten die Verlinkungen vorzunehmen, welche ich im Folgenden nenne:  Funktionale Anforderungen, Projektmanagement, Erfolgsmessung 

Ein Inhaltsverzeichnis wäre wünschenswert gewesen und die Überschriften sind nur teilweise nummeriert.  Besser wäre es, wenn man alle Unterschriften nummeriert, das heißt auch der Punkt Fazit und Quellen, sodass die Struktur vom Anfang beibehalten wird. Ansonsten macht es den Anschein, dass diese beiden Punkte Unterpunkte der Überschrift 3 sind. Alternativ könnte man auch die Nummerierung der Überschriften weglassen. Zur Optimierung der Struktur fände ich es außerdem schöner, wenn zu Beginn die Punkte Definition und Unterschiede des Themas unter getrennten Überschriften behandelt werden. 

Der Artikel wurde sachlich verfasst, jedoch sind mir einige Rechtschreibfehler aufgefallen, die im Folgenden aufzähle. 
-	Im zweiten Absatz der Definition fehlt ein Komma vordem „wie“ und nach dem „erwähnt“ 
-	Im dritten Absatz der Definition fehlt ein Komma nach dem „beispielweise“ 
-	In dem Absatz vor der Abbildung kommt nach dem „stets“ kein Komma

2021-12-09 19:48 UTC, merged

2021-12-22 20:44 UTC, seriousTake commented
> Kriterium	Bewertung
> Front-Matter	ja
> Umfang	ja
> Belege	ja
> Links	ja
> Formatierung	ja
> Verlinkungen vorhanden	nein
> Abbildungen	ja
> Strukturierung des Beitrags	9
> Rechtschreibung	9
> Sprache	9
> Inhalt	10
> Einordnung in den Kontext	10
> Ansprechend für Zielgruppe	10
> # Zusammenfassung
> Der Artikel befasst sich mit nicht Funktionalen Anforderungen im PM. Der Begriff wird zuerst definiert und vom Funktionalen Anforderungen unterschieden und mit einem Beispiel veranschaulicht. Danach wird die Erfolgsmessung und Dokumentation von nicht-funktionalen Anforderungen erläutert. Der Beitrag endet mit einem zusammenfassendem Fazit.
> 
> # Positive Aspekte
> Sehr schöne Grafiken die gut in den Beitrag eingebunden wurden. Fazit fasst alles nochmal zusammen. Das Bsp. hilft viel für das Verständnis.
> 
> # Negative Aspekte
> Über dem ersten Absatz würde ich eine Überschrift machen, es steht verloren da und passt anschaulich nicht in den Beitrag. Bei weitere Unterschiede würde ich Tabelle ausbauen. Es fehlen Verlinkungen zu anderen Beiträgen und Teilweise auch Quellen.

Danke für die Kritik. Den oberen Absatz habe ich unter die erste Überschrift verschoben.

2021-12-22 21:04 UTC, seriousTake commented
> Kriterium	Bewertung
> Front-Matter	ja
> Umfang	ja
> Belege	ja
> Links	ja
> Formatierung	ja
> Verlinkungen vorhanden	nein
> Abbildungen	ja
> Strukturierung des Beitrags	8
> Rechtschreibung	8
> Sprache	8
> Inhalt	10
> Einordnung in den Kontext	10
> Ansprechend für Zielgruppe	9
> # Zusammenfassung
> Im Artikel wird im Sinne des klassischen Projektmanagements "nicht-funktionale Anforderungen" betrachtet. Der Begriff wird definiert, von funktionalen Anforderungen abgegrenzt. Dies wird anhand eines Beispiels vertieft. Anschließend sich mit der Erfolgsmessung und Dokumentation von nicht-funktionalen Anforderungen beschäftigt und mit einem Fazit abgerundet.
> 
> # Positive Aspekte
> Besonders hervorzuheben sind die verschiedenen Blickwinkel, mit denen das Thema beleuchtet wurden. Auch der Enzyklopädiestil ist durch die Struktur gegeben (z.B. Kapitel siehe auch). Es wurde ein guter Überblick über das Thema verschafft, der durch die sehr gute Wahl der Abbildung zusätzlich unterstrichen wurde. Die Belege wurden zu den Quellen verlinkt, welche sich stets aufrufen lassen haben.
> 
> # Negative Aspekte
> Allgemein kann die Struktur des Artikels optimiert werden. So ließe sich 1. Definition und Unterschied zu funktionalen Anforderungen in zwei Kapitel aufteilen - 1. Definition, 2. Unterschiede. Wenn es von mir richtig verstanden wurde, sind außerdem die Kapitel "Fazit", "siehe auch " und "Quellen" auf derselben Hierarchiestufe, wie die nummerierten Kapitel. Deshalb wäre die Nummerierung dieser Kapitel ebenfalls sinnvoll (4. Fazit, 5. Siehe auch, 6. Quellen).
> 
> Es wurde auf keine der anderen Themenbereiche verlinkt, hierbei würde sich die direkte Verlinkung von Themen, wie z.B. "Projektmanagement", "funktionale Anforderungen", "Anforderungsmanagement" und "Erfolgsmessung" ergeben.
> 
> Zum Teil fehlen Quellenangaben, wie z.B. unter 1. im letzten Absatz, im Absatz zum Smartphonespiel (ich bin mir nicht sicher, ob das Beispiel selbst ausgedacht ist und sich deshalb auf keine Quelle bezieht oder ob die Verlinkung fehlt), im 2. Kapitel die letzten 3 Sätze vor der Abbildung, im 3. Kapitel der letzte Satz.
> 
> Sprachlich wurde meist der sachliche Stil eingehalten. An einigen wenigen Punkten gibt es Verbesserungsvorschläge z.B.: Nominalstil in den Überschriften: 2. Erfolgsmessung, 3. Dokumentation von nicht-funktionalen Anforderungen. Im 1. Kapitel klingt das "wie bereits erwähnt" nicht sachlich. Der 1. Satz des Beispiels klingt ebenfalls unsachlich. Ein Verbesserungsvorschlag wäre beispielsweise: "Zur Veranschaulichung wird folgender Auftrag betrachtet." Unwissenschaftliche Worte wie "selbstverständlicherweise" , "eventuell" oder "versuchen" (persönliche Einschätzung und Geschmackssache, an sich auf keinen Fall falsch)
> 
> Bezüglich der Rechtschreibung sollte sich im Allgemeinen entschieden werden, ob "Nicht-Funktionale" und "Funktionale" oder "nicht-funktionale" und "funktionale" geschrieben wird, jedoch nicht gemischt. Im Smartphonespiel-Beispiel fehlt im letzten Satz nach "erwartet" ein Komma. Im letzten Satz vor der Abbildung ist nach "stets" ein Komma zu viel. Im Fazit sollten die Spiegelpunkte einheitlich entweder mit großen oder kleinen Buchstaben beginnen.

Der Aufbau des Beitrags und die Nummerierung der Überschriften wurde überarbeitet. Beitragsverlinkung ist erfolgt.  Quellenangaben wurden überprüft und angepasst. Entsprechende Fehler in Sprache und Rechtschreibung wurden verbessert.
Vielen Dank für das Feedback!

2021-12-22 21:06 UTC, seriousTake commented
> Kriterium	Bewertung
> Front-Matter	ja
> Umfang	ja
> Belege	ja
> Links	ja
> Formatierung	ja
> Verlinkungen vorhanden	nein
> Abbildungen	ja
> Strukturierung des Beitrags	8
> Rechtschreibung	8
> Sprache	9
> Inhalt	10
> Einordnung in den Kontext	9
> Ansprechend für Zielgruppe	10
> # Zusammenfassung
> In dem Artikel wird im Rahmen des Projektmanagements näher auf die nicht funktionalen Anforderungen eingegangenen. Zunächst wurde anhand einer Definition die Begrifflichkeit erklärt. Anschließend wurde ein Vergleich zu den funktionalen Anforderungen gezogen, sodass der Unterschied beider ersichtlich wird. Anhand eines Beispiels wird Im Anschluss die Auswirkung der nicht funktionalen Anforderungen auf den Erfolg eines Produktes veranschaulicht. Der Artikel beschäftigt sich als letztes mit der Dokumentation nicht funktionaler Anforderungen und wird mit einem Fazit, welches die wichtigsten Anhaltspunkte darstellt, beendet.
> 
> # Positive Aspekte
> Das Thema wurde sehr gut innerhalb des Artikels erklärt. Die Tabelle stellt den Unterschied zwischen funktionalen und nicht funktionalen Anforderungen sehr gut dar. Des Weiteren wurde die Abbildung sehr passend gewählt, da diese bildlich nochmals das Erfolgspotenzial veranschaulicht. Die Absätze wurden mit den Quellen richtig verlinkt und diese lassen sich ebenfalls formgemäß aufrufen.
> 
> # Negative Aspekte
> Zunächst wurden leider keine Verlinkungen mit anderen Beiträgen vorgenommen. Unter dem Punkt drei wurde das Wort „SRS“ nicht mit einem Beitrag verlinkt, sondern lediglich mit einer Quelle. In dem Artikel gäbe es außerdem einige Möglichkeiten die Verlinkungen vorzunehmen, welche ich im Folgenden nenne: Funktionale Anforderungen, Projektmanagement, Erfolgsmessung
> 
> Ein Inhaltsverzeichnis wäre wünschenswert gewesen und die Überschriften sind nur teilweise nummeriert. Besser wäre es, wenn man alle Unterschriften nummeriert, das heißt auch der Punkt Fazit und Quellen, sodass die Struktur vom Anfang beibehalten wird. Ansonsten macht es den Anschein, dass diese beiden Punkte Unterpunkte der Überschrift 3 sind. Alternativ könnte man auch die Nummerierung der Überschriften weglassen. Zur Optimierung der Struktur fände ich es außerdem schöner, wenn zu Beginn die Punkte Definition und Unterschiede des Themas unter getrennten Überschriften behandelt werden.
> 
> Der Artikel wurde sachlich verfasst, jedoch sind mir einige Rechtschreibfehler aufgefallen, die im Folgenden aufzähle.
> 
> * Im zweiten Absatz der Definition fehlt ein Komma vordem „wie“ und nach dem „erwähnt“
> * Im dritten Absatz der Definition fehlt ein Komma nach dem „beispielweise“
> * In dem Absatz vor der Abbildung kommt nach dem „stets“ kein Komma

Beitragsverlinkung ist erfolgt. Inhaltsverzeichnis, Aufbau und Nummerierung wurde angepasst. Rechtschreibfehler und Grammatikfehler wurden ausgebessert. Vielen Dank für das Feedback und allen Vorschlägen.

2022-01-19 18:21 UTC, 12Yousuf commented
| Kriterium | Bewertung|
|-----|---|
| Front-Matter | ja |
| Umfang | ja |
| Belege | ja |
| Links | ja |
| Formatierung | ja |
| Verlinkungen vorhanden | ja |
| Abbildungen | ja |
| Strukturierung des Beitrags | 10 |
| Rechtschreibung | 10 |
| Sprache | 10 |
| Inhalt | 10|
| Einordnung in den Kontext | 10 |
| Ansprechend für Zielgruppe |10 |

# Zusammenfassung

In dem Artikel wird im Rahmen des Projektmanagements näher auf die nicht funktionalen Anforderungen eingegangenen. Zunächst wurde anhand einer Definition die Begrifflichkeit erklärt. Anschließend wurde ein Vergleich zu den funktionalen Anforderungen gezogen, sodass der Unterschied beider ersichtlich wird. Anhand eines Beispiels wird Im Anschluss die Auswirkung der nicht funktionalen Anforderungen auf den Erfolg eines Produktes veranschaulicht. Der Artikel beschäftigt sich als letztes mit der Dokumentation nicht funktionaler Anforderungen und wird mit einem Fazit, welches die wichtigsten Anhaltspunkte darstellt, beendet. 

# Positive Aspekte

Alle Veränderungen sind vorgenommen worden, sodass der Artikel nun in einer sehr guten Verfassung ist. Die Rechtschreibfehler wurden ebenfalls korrigiert.

# Negative Aspekte

In der neuen Version sind mir keine negativen Aspekte mehr aufgefallen. Der Artikel ist im Allgemeinen gut gelungen.