Top-Down Planning
ManagingProjectsSuccessfully/ManagingProjectsSuccessfully.github.io pull request #319
Opened 2021-11-24 20:12 UTC by laradag

2021-12-02 21:52 UTC, xe28dita requested changes
| Kriterium | Bewertung|
|-----|---|
| Front-Matter | ja|
| Umfang | ja|
| Belege | ja|
| Links | ja|
| Formatierung | ja|
| Verlinkungen vorhanden | ja|
| Abbildungen | ja|
| Strukturierung des Beitrags |8 |
| Rechtschreibung |9|
| Sprache | 8|
| Inhalt | 10|
| Einordnung in den Kontext |10|
| Ansprechend für Zielgruppe |10|

# Zusammenfassung

Kurze Zusammenfassung des/der Artikel

# Positive Aspekte

Was ist gut (Bezug zur Tabelle)
Ich finde den Beitrag gut durchdacht und angenehm zu lesen. Als Leser hat man den Eindruck, alles wichtige über dieses Thema gelesen zu haben. 

# Negative Aspekte

Was geht besser (Bezug zur Tabelle)
Das Inhaltsverzeichnis sollte an erster Stelle vor der Definition stehen.
Du hast den Enzyklopädiestil bis auf den Teil mit den Vor- und Nachteilen gut beibehalten. Da solltest du durchgehend beim Nominalstil bleiben (z.B. "Verbesserte Delegierung von Mitarbeitern auf niedrigerer Organisationsebene durch klaren Führungsstil")

2021-12-07 09:01 UTC, LaHe27 requested changes
| Kriterium | Bewertung|
|-----|---|
| Front-Matter | ja | 
| Umfang | ja | 
| Belege | ja | 
| Links | ja | 
| Formatierung | ja | 
| Verlinkungen vorhanden | ja | 
| Abbildungen | ja | 
| Strukturierung des Beitrags | 10 | 
| Rechtschreibung | 8 | 
| Sprache | 8 | 
| Inhalt | 10| 
| Einordnung in den Kontext | 10| 
| Ansprechend für Zielgruppe | 10| 

# Zusammenfassung

Der Artikel befasst sich mit dem Top-Down Planning, welches das Gegenteil des Bottom-up Plannings darstellt. Im Artikel wird zu erst auf das Konzept des Top-Down Plannings eingegangen und danach Vor- sowie Nachteile erläutert und in einer Tabelle verschiedene Anwendungsbereich anhand von Beispielen erklärt.

# Positive Aspekte

Ich finde, du hast deinen Beitrag gut gegliedert und auch die Bilder passen gut dazu. Auch die Sprache und der Stil sind sehr verständlich.
Ich finde es auch sehr gut, dass du ein paar kritische Aspekte des Top-Down Plannings aufgeführt hast.

# Negative Aspekte

Du könntest Projektmanagement (unter "Konzept") noch verlinken
"Zentral" gehört klein geschrieben (unter "Konzept")
Unter Vorteile ist beim ersten Punkt ein kleiner Rechtschreibfehler, das müsste "wieder" heißen

2021-12-08 20:04 UTC, Harthauer requested changes
| Kriterium | Bewertung|
|-----|---|
| Front-Matter | ja |
| Umfang | ja |
| Belege | ja|
| Links | ja|
| Formatierung | ja |
| Verlinkungen vorhanden | ja |
| Abbildungen | ja |
| Strukturierung des Beitrags | 10 |
| Rechtschreibung | 9|
| Sprache | 10 |
| Inhalt | 10|
| Einordnung in den Kontext | 10|
| Ansprechend für Zielgruppe | 10|

# Zusammenfassung

Der Beitrag befasst sich mit dem Thema Top Down Planning und schlüsselt diesen nach seinem Konzept, Kritische Auseinandersetzung mit Top-Down Planning und Anwendungen von Top-Down Planning auf. 

# Positive Aspekte

Der Artikel ist sehr sachlich geschrieben und hält sich trotzdem knapp. Die Formatierung der Vor-/Nachteile gefällt mir sehr.

# Negative Aspekte

Das Inhaltsverzeichnis ist nummeriert, die Überschriften nicht, würde die auch nummerieren. In der Tabelle bei Politik hast du aus versehen OFtmals geschrieben.

2021-12-09 19:48 UTC, merged

2021-12-18 10:00 UTC, laradag commented
Hi @xe28dita : Vielen Dank für dein Feedback. Gerne habe ich deine genannten Punkte umgesetzt. Bei einem Punkt würde ich jedoch um deine Rückmeldung bitten. Es wurde kritisiert, das Inhaltsverzeichnis ganz oben zu setzen. Dieses Inhaltsverzeichnis habe ich jedoch bewusst unterhalb des einleitenden Satzes gestellt, da wir uns am Stil  von Wikipedia orientieren sollen und dort im Falle eines Inhaltsverzeichnis vorher ein einleitender Satz steht (s. https://en.wikipedia.org/wiki/Top-down_and_bottom-up_design). Würde sich deine Kritik durch meine Begründung erübrigen?
Vielen Dank und liebe Grüße.