Update Projektmanagementhandbuch und Scrum von User Harthauer
ManagingProjectsSuccessfully/ManagingProjectsSuccessfully.github.io pull request #320
Opened 2021-11-24 20:17 UTC by Harthauer

2021-12-02 21:04 UTC, xe28dita requested changes
| Kriterium | Bewertung|
|-----|---|
| Front-Matter | ja|
| Umfang | ja|
| Belege | ja|
| Links | ja|
| Formatierung | ja|
| Verlinkungen vorhanden | ja|
| Abbildungen | ja|
| Strukturierung des Beitrags | 10 |
| Rechtschreibung | 8|
| Sprache | 8|
| Inhalt | 10|
| Einordnung in den Kontext | 10|
| Ansprechend für Zielgruppe | 10|

# Zusammenfassung

Der Beitrag ist gut und klar strukturiert. Zudem ist ein durchgehender roter Faden vorhanden.



# Positive Aspekte

Was ist gut (Bezug zur Tabelle)
Wie oben bereits gesagt, gut strukturiert, einfache Sprache, gute Rechtschreibung. 
Inhaltlich ist alles wichtige zu lesen. Eventuell könntest du noch 1-2 Sätze über die Nachteile des Handbuchs erzählen, sofern du die 500 Wörter nicht zu sehr überschreitest.

# Negative Aspekte

Was geht besser (Bezug zur Tabelle)
Ich habe keine Rechtschreibfehler entdeckt allerdings hast du mehrere Kommafehler gemacht. Ich finde den Sprachstil generell gut verständlich und du solltest umgangssprachliche Formulierungen wie "die es so noch nicht gibt." vermeiden.
Eine Abbildung ist zwar vorhanden aber ich wüsste nicht, ob ein Icon als Abbildung durchgehen würde. Vielleicht findest du ja etwas anderes?

2021-12-07 09:53 UTC, LaHe27 requested changes
| Kriterium | Bewertung|
|-----|---|
| Front-Matter | ja |
| Umfang | nein|
| Belege | ja |
| Links | ja |
| Formatierung | ja|
| Verlinkungen vorhanden | ja |
| Abbildungen | ja |
| Strukturierung des Beitrags | 10 |
| Rechtschreibung | 10|
| Sprache | 9 |
| Inhalt | 9 |
| Einordnung in den Kontext | 10|
| Ansprechend für Zielgruppe | 10|

# Zusammenfassung

Im den beiden Beitrag geht es um das Projektmanagementhandbuch und SCRUM. Beide Beiträge bieten einen guten Überblick über die Themen. Bei SCRUM wird auf die wichtigen Begriffe, den Ablauf sowie die Rollen eines SCRUM Teams eingegangen. Der Beitrag zum Projektmanagementhandbuch befasst sich mit der Abgrenzung zum Projekthandbuch, sowie Aufbau und Inhalten und den Vorteilen.

# Positive Aspekte

Ich finde beide Beiträge sind wirklich sehr gut strukturiert und bieten den richtigen Überblick über die Themen. Auch die Rechtschreibung ist sehr gut. 
Vor allem die Abgrenzung zum Projekthandbuch finde ich sehr gut und sehr wichtig.
Die Abbildung bei SCRUM finde ich sehr gut..

# Negative Aspekte

Beim Beitrag Projektmanagement Handbuch sind es aktuell nur ca. 420 Wörter. Vielleicht kannst du noch 4-5 Sätze irgendwo ergänzen, vllt. mit Beispielen oder dem "Erfinder" des Handbuchs.
Bei SCRUM sind es knapp unter 500 Wörter.

Bei Siehe auch würde ich bei beiden Beiträgen jeweils den Link auf diese Seite rauslöschen.

Bei den Quellen meinte Martin, glaub ich, in einem Teams Beitrag, dass wir die Quellen nach der Überschrift benennen sollten und diese dann verlinken.

Folgende Beiträge könntest du noch Verlinken: 
"Projektmanagement", "Projekthandbuch" (in der Überschrift), "Projekt", "Projektleitung"
- bei dem SCRUM Beitrag fehlen viele Verlinkungen (z.B. SCRUM Artefakte, Product Backlog,...)

Falls es sich bei der Abgrenzung der beiden Handbücher in den "" jeweils um direkte Zitate handelt, wäre es vielleicht gut, direkt dahinter die genaue Quelle anzugeben.

2021-12-08 14:24 UTC, alexandermueller296 requested changes
# Projektmanagementhandbuch

| Kriterium | Bewertung|
|-----|---|
| Front-Matter | ja |
| Umfang | nein |
| Belege | ja |
| Links | ja |
| Formatierung | ja |
| Verlinkungen vorhanden | ja |
| Abbildungen | ja |
| Strukturierung des Beitrags | 10 |
| Rechtschreibung | 10 |
| Sprache | 10 |
| Inhalt | 9 |
| Einordnung in den Kontext | 10 |
| Ansprechend für Zielgruppe | 10 |

# Zusammenfassung

Der Artikel beschäftigt sich mit dem Thema „Projektmanagementhandbuch“. Er Gibt einen guten Überblick über das Thema.

# Positive Aspekte

Schön leserlicher Artikel, gute Sprache, gute Rechtschreibung. Er ist klar strukturiert und in einer einfachen Sprache formuliert.

# Negative Aspekte

Man könnte noch Links im Fließtext einbauen. Die Abbildung ist auch gut gewählt, jedoch wäre ein Bild mit eigener Aussage vielleicht eine bessere Option. Eventuell noch einen Punkt mit Nachteilen, wenn schon Vorteile genannt werden. Zudem sind es zu wenige Wörter (ca. 425). Dies könnte man mit den Nachteilen auffüllen.

# Scrum

| Kriterium | Bewertung|
|-----|---|
| Front-Matter | ja |
| Umfang | ja |
| Belege | ja |
| Links | ja |
| Formatierung | ja |
| Verlinkungen vorhanden | ja |
| Abbildungen | ja |
| Strukturierung des Beitrags | 10 |
| Rechtschreibung | 10 |
| Sprache | 10 |
| Inhalt | 10 |
| Einordnung in den Kontext | 10 |
| Ansprechend für Zielgruppe | 10 |

# Zusammenfassung

Der Artikel „Scrum“ erklärt zuerst in einer kurzen Übersicht das Thema im Allgemeinen mit einer Definition. Zeigt dann wichtige Begriffe in Scrum und den Ablauf mit den verschiedenen Phasen. Zuletzt wird noch das Scrum Team mit Hilfe einer Tabelle erläutert.

# Positive Aspekte

Der Artikel ist sehr gut strukturiert und man sieht den Roten Faden von Anfang an. Schön sind die Verlinkungen, welche in den Fließtext eingearbeitet sind. 7 Quellen geben ein breites Spektrum an Wissensquellen. Es wurde mit verschiedenen Mitteln gearbeitet (Stichpunkte, Tabelle). 

# Negative Aspekte

Bei „Siehe auch“ (Link auf diese Seite) noch rauslöschen, da es ein Link auf die gleiche Seite verlinkt, auf der man sich befindet. Möglicherweise noch ein Paar Wörter verlinken.

2021-12-09 19:48 UTC, merged

2021-12-22 13:25 UTC, Harthauer commented
Hallo,
vielen dank für euer Feedback! Ich werde im Folgendem auf das eingehen was ich von euren Tipps nicht umgesetzt habe und warum

- Ich habe nichts über den Erfinder des PM Handbuches gefunden und auch keine Nachteile davon, habe dafür den Inhalt vom PMH ausgeweitet und Vorteile zu Nutzen geändert und diesen Abschnitt auch ausgeweitet

- Projektmanagement und Projekthandbuch hab ich nicht in der Überschrift, sondern im Fließtext markiert, wollte keine 2 Hyperlinks in einem Wort haben