Agiles Manifest und Projektteam_Kultur
ManagingProjectsSuccessfully/ManagingProjectsSuccessfully.github.io pull request #322
Opened 2021-11-24 20:26 UTC by LaHe27

2021-12-07 12:59 UTC, gelfertfelix requested changes
# Review: Agiles Manifest

| Kriterium | Bewertung |
|-----|---|
| Front-Matter | ja |
| Umfang | ja |
| Belege | nein |
| Links | ja |
| Formatierung | ja |
| Verlinkungen vorhanden | ja |
| Abbildungen | ja |
| Strukturierung des Beitrags | 10 |
| Rechtschreibung | 10 |
| Sprache | 10 |
| Inhalt | 10 |
| Einordnung in den Kontext | 10 |
| Ansprechend für Zielgruppe | 10 |

## Zusammenfassung

In diesem Artikel geht es um das Thema "Agiles Manifest". Anfangs wird die Herkunft und Bedeutung des Begriffs definiert, anschließend werden dessen vier Leitsätze und dessen 12 Prinzipien vorgestellt. Abschließend wird die heutige Bedeutung des Manifests betont.

## Positive Aspekte

Zuerst wird der Begriff "Agiles Manifest" definiert, dabei gefällt mir der kleine Exkurs über das Ski Wochenende sehr gut! Klar könnte man sagen dass dies eine unwichtige Information ist, jedoch glaube ich dass genau solche Dinge im Gedächtnis bleiben. Im Nachhinein fällt es einem somit leichter, sich an den Beitrag zu erinnern. Der Artikel ist sehr gut strukturiert, sodass ich mich schnell zurecht finden konnte. Alle wichtigen Information wurden auf den Punkt zusammengefasst, sodass ich einen sehr guten Überblick über das Thema bekommen habe. Der letzte Absatz unter dem Titel "Heutige Bedeutung" gefällt mir als "rundes Ende" sehr gut. Er ermöglicht es mir das Thema in einen Zusammenhang mit angrenzenden Themen zu bringen.

## Negative Aspekte

Leider konnte ich ich keinen Beleg zur Abbildung finden. Ich würde vorschlagen dass man unterhalb der Abbildung einen Abbildungstitel hinzufügt und diesen belegt/verlinkt. Die Quelle sollte also schnell und eindeutig zu finden sein, alternativ über ein Abbildungsverzeichnis am Ende? Zudem muss ich gestehen, dass mir der Mehrwert der Abbildung nicht ersichtlich ist. "Ich bin nach der Abbildung nicht schlauer als vorher". Ich kann mir vorstellen, dass es schwierig ist zu diesem Thema eine passende Abbildung zu finden, aber vielleicht gibt es ja doch noch eine andere? 

# Review: Projektteam_Kultur

| Kriterium | Bewertung|
|-----|---|
| Front-Matter | ja |
| Umfang | ja |
| Belege | nein |
| Links | ja |
| Formatierung | ja |
| Verlinkungen vorhanden | ja |
| Abbildungen | ja |
| Strukturierung des Beitrags | 9 |
| Rechtschreibung | 10 |
| Sprache | 10 |
| Inhalt | 10 |
| Einordnung in den Kontext | 10 |
| Ansprechend für Zielgruppe | 10 |

## Zusammenfassung

In diesem Artikel geht es um das Thema "Projektteam_Kultur". Es wird erläutert wie eine Kultur aus dem Zusammenspiel von Werten, Normen, Denkhaltungen und Paradigmen entsteht. Dabei werden Kulturen nicht nur im allgemeinen betrachtet, sondern auf auf der Ebene eines Projektteams. Diese Ebene wird anhand von Beispielen veranschaulicht und mit angrenzenden Themen in Verbindung gebracht.

## Positive Aspekte

Im ganzen Artikel kann man immer wieder praxisnahe Beispiele finden, die das Thema "greifbarer" machen. Es gefällt mir sehr gut dass der Artikel stark mit angrenzenden Themen (Projektleiter, Projektkommunikation, Projekt Kick-Off, Projekt) vernetzt wurde. Kleine Anmerkung hierzu: Eine Verlinkung direkt am Begriff selber fände ich noch schöner, da man so besser von Artikel zu Artikel wechseln kann. Die Einordnung des Themas in den Kontext ist sehr gut gelungen. Es wurde genau erklärt, wie sich eine Projektteam Kultur von der allgemeinen Kultur spezialisiert und welche Rolle sie für ein Unternehmen spielen kann. Der Artikel behandelt ein Thema das eigentlich selbsterklärend ist bzw. ein Thema bei dem viele Personen schon ein Vorwissen mitbringen. Dennoch wurde das Thema interessant erleuchtet, sodass ich Spaß beim lesen hatte und mir neues Wissen aneignen konnte.

## Negative Aspekte

Die Strukturierung des Beitrages ist im allgemeinen gut gelungen, jedoch fände ich den Erzählstrang etwas schlüssiger, wenn der Absatz "Kultur im Allgemeinen" am Anfang des Artikels gesetzt wäre. 
Ich würde hier gerne auf mein Review zum Thema "Agiles Manifest" zurückgreifen, da sich ein negativer Aspekt in diesem Artikel wiederholt: Leider konnte ich ich keinen Beleg zur Abbildung finden. Ich würde vorschlagen dass man unterhalb der Abbildung einen Abbildungstitel hinzufügt und diesen belegt/verlinkt. Die Quelle sollte also schnell und eindeutig zu finden sein, alternativ über ein Abbildungsverzeichnis am Ende? Zudem muss ich gestehen, dass mir der Mehrwert der Abbildung nicht ersichtlich ist. "Ich bin nach der Abbildung nicht schlauer als vorher". Ich kann mir vorstellen, dass es schwierig ist zu diesem Thema eine passende Abbildung zu finden, aber vielleicht gibt es ja doch noch eine andere?

2021-12-07 23:25 UTC, LeahMtmb requested changes
# Review Agiles Manifest

| Kriterium | Bewertung|
|-----|---|
| Front-Matter | ja|
| Umfang | ja|
| Belege | ja |
| Links | ja|
| Formatierung | ja|
| Verlinkungen vorhanden | ja |
| Abbildungen | ja|
| Strukturierung des Beitrags | 10 |
| Rechtschreibung | 9|
| Sprache | 8|
| Inhalt | 10|
| Einordnung in den Kontext | 10|
| Ansprechend für Zielgruppe | 9|

# Zusammenfassung

Zuerst wird das agile Manifest definiert. Danach werden dessen Leitsätze und Prinzipien erläutert. Abschließend wird noch erklärt, wie das "Agile Manifest" im heutigen Kontext einzuordnen ist.

# Positive Aspekte

Durch deine Formatierung, ist dein Artikel sehr übersichtlich und super strukturiert. Du hast alles verständlich und prägnant wiedergegebenen, sodass ich nach einmaligem Lesen das Thema sofort verstanden habe. Was die Sprache und die Rechtschreibung betrifft, habe ich auch wenig anzumerken. Alles in allem ist dein Artikel echt sehr gelungen!

# Negative Aspekte

Bei den Stichpunkten der zwölf Prinzipien wird es leicht unübersichtlich. Deshalb würde ich bei den Stichpunkten, das Wichtigste fett hervorzuheben oder die Stichpunkte prägnant zusammenfassen und anschließend darunter eine kurze Erklärung hinzufügen. Abschließend enthält der Artikel noch kleine Tippfehler. Da ist es am besten abschließend mit einem Grammatikprüfer, wie https://languagetool.org/de, drüber zugehen.

2021-12-07 23:37 UTC, LeahMtmb requested changes
# Review Agiles Manifest

| Kriterium | Bewertung|
|-----|---|
| Front-Matter | ja|
| Umfang | ja|
| Belege | ja |
| Links | ja|
| Formatierung | ja|
| Verlinkungen vorhanden | ja |
| Abbildungen | ja|
| Strukturierung des Beitrags | 10 |
| Rechtschreibung | 9|
| Sprache | 8|
| Inhalt | 10|
| Einordnung in den Kontext | 10|
| Ansprechend für Zielgruppe | 9|

# Zusammenfassung

Zuerst wird das agile Manifest definiert. Danach werden dessen Leitsätze und Prinzipien erläutert. Abschließend wird noch erklärt, wie das "Agile Manifest" im heutigen Kontext einzuordnen ist.

# Positive Aspekte

Durch deine Formatierung, ist dein Artikel sehr übersichtlich und super strukturiert. Du hast alles verständlich und prägnant wiedergegebenen, sodass ich nach einmaligem Lesen das Thema sofort verstanden habe. Was die Sprache und die Rechtschreibung betrifft, habe ich auch wenig anzumerken. Alles in allem ist dein Artikel echt sehr gelungen!

# Negative Aspekte

Bei den Stichpunkten der zwölf Prinzipien wird es leicht unübersichtlich. Deshalb würde ich bei den Stichpunkten, das Wichtigste fett hervorzuheben oder die Stichpunkte prägnant zusammenfassen und anschließend darunter eine kurze Erklärung hinzufügen. Abschließend enthält der Artikel noch kleine Tippfehler. Da ist es am besten abschließend mit einem Grammatikprüfer, wie https://languagetool.org/de, drüber zugehen.

Review Projektteam_Kultur
| Kriterium | Bewertung|
|-----|---|
| Front-Matter | ja|
| Umfang | nein|
| Belege | ja |
| Links | ja|
| Formatierung | ja|
| Verlinkungen vorhanden | ja |
| Abbildungen | ja|
| Strukturierung des Beitrags | 10 |
| Rechtschreibung | 9|
| Sprache | 9|
| Inhalt | 10|
| Einordnung in den Kontext | 10|
| Ansprechend für Zielgruppe | 9|

# Zusammenfassung

Nachdem der Begriff „Projektteam“ definiert wurde, wurde noch der Nutzen von den „Spielregeln“ der Zusammenarbeit erklärt. Anschließend erfolgen noch einige Beispiele. Abschließend wurde die Kultur im allgemeinen Kontext definiert und anhand eines drei-Ebenen-Modell im Zusammenhang mit dem Projektmanagement gebracht.

# Positive Aspekte

Dieser Begriff ist an sich nicht einfach zu definieren. Dieses Problem bist du gut umgegangen und kreativ gelöst. Deine Bespiele sind auch gut gewählt und sehr anschaulich, um das Thema besser nachvollziehen zu können. Dasselbe gilt auch für die Abbildung, die die eigentliche Devise des Themas super wiedergibt.

# Negative Aspekte

Dein Artikel erfüllt leider nicht die geforderte Mindestanzahl an Wörtern.  

Wie beim anderen Artikel würde ich auch mit einem Grammatikprüfer darüber gehen.

2021-12-08 14:33 UTC, alexandermueller296 requested changes
# Agiles Manifest

| Kriterium | Bewertung|
|-----|---|
| Front-Matter | ja |
| Umfang | ja |
| Belege | ja |
| Links | ja |
| Formatierung | ja |
| Verlinkungen vorhanden | ja |
| Abbildungen | ja |
| Strukturierung des Beitrags | 10 |
| Rechtschreibung | 9 |
| Sprache | 10 |
| Inhalt | 9 |
| Einordnung in den Kontext | 10 |
| Ansprechend für Zielgruppe | 10 |

# Zusammenfassung

Zu Beginn des Artikels wird ein kurzer Überblick über die Entstehung und den Inhalt des agilen Manifests gegeben. Danach wird auf die vier Leitsätze und die 12 Prinzipien eingegangen. Zum Schluss wird noch auf die heutige Bedeutung des agilen Manifests eingegangen. 

# Positive Aspekte

Es wurde eine schöne strukturierte und übersichtliche Form des Artikels gewählt.  Bei der Sprache wurde auf Gendern geachtet, was einen modernen Schreibstil zeigt. Zusätzlich wurde der Artikel in einem schön leserlichen Stil geschrieben und ist sehr interessant geschrieben.

# Negative Aspekte

Unter den negativen Aspekt sind mir eher kleinere Fehler bzw. Verbesserungsvorschläge aufgefallen. Bei der Quellenangabe wurde ein Rechtschreibfehler gemacht (Gesichte). Die Abbildung ist bei mir etwas unscharf, vielleicht wurde die Datei nicht richtig heruntergeladen. Möglicherweise könnte man eine übersichtlichere Art der Aufzählung unter den „Zwölf Prinzipien“ wählen, da es auf den ersten Blick etwas viel ist.  Möglicherweise könnte man eine Verlinkung innerhalb eines Fließtextes einbauen.

# Projektteam_Kultur

| Kriterium | Bewertung|
|-----|---|
| Front-Matter | ja/ nein |
| Umfang | ja |
| Belege | ja |
| Links | ja |
| Formatierung | ja |
| Verlinkungen vorhanden | ja |
| Abbildungen | ja |
| Strukturierung des Beitrags | 9 |
| Rechtschreibung | 10 |
| Sprache | 10 |
| Inhalt | 10 |
| Einordnung in den Kontext | 10 |
| Ansprechend für Zielgruppe | 10 |

# Zusammenfassung

In diesem Artikel geht es um Projektteam bzw. Projektkultur. Zu beginn wird eine kurze Erklärung des Begriffs getätigt. Danach geht es um Spielregeln bei der Zusammenarbeit, welche mit einigen Beispielen dargestellt werden. Des wird die Kultur im Allgemeinen erklärt und dessen Ebenen. 

# Positive Aspekte

Der Artikel ist schön gegliedert in die Einführung, die Spielregeln und die Kultur. Es wird gut auf die Überpunkte eingegangen und alles sehr verständlich erklärt. Das Bild ist im Zusammenhang mit dem Text sehr gut gewählt und gibt die Wichtigkeit des Teamgedankens wieder.

# Negative Aspekte

Der Artikel erfüllt leider nicht die Untergrenze von 500 Wörtern, jedoch habe ich es auch am Anfang so verstanden das es 500- 5% bzw. 500+5% sein sollen. Bei der Strukturierung würde ich „Spielregeln bei der Zusammenarbeit“ und „Kultur im Allgemeinen“ tauschen, da es für mich einen schöneren Fluss geben würde.

2021-12-09 19:48 UTC, merged