Stakeholderanalyse
ManagingProjectsSuccessfully/ManagingProjectsSuccessfully.github.io pull request #330
Opened 2021-11-24 21:18 UTC by DanielLu21

Hallo, 
dies ist der 1. Entwurf meines Beitrags zur Stakeholderanalyse. Vielen Dank für Euer Review.

2021-12-04 16:43 UTC, ux49azap requested changes
| Kriterium | Bewertung|
|-----|---|
| Front-Matter | ja|
| Umfang | ja|
| Belege | ja|
| Links | ja|
| Formatierung | ja|
| Verlinkungen vorhanden | ja|
| Abbildungen | ja |
| Strukturierung des Beitrags | 10 |
| Rechtschreibung |9|
| Sprache | 10 |
| Inhalt | 10|
| Einordnung in den Kontext | 10|
| Ansprechend für Zielgruppe |10|

# Zusammenfassung

Der Artikel beschäftigt sich mit der sogenannten Stakeholderanalyse. Zu Beginn des Artikels wird dieser Begriff definiert. Es handelt sich hierbei um die systematische Identifikation und Steuerung der gesamten Interessengruppen eines Projektes. Anschließend wird dessen Hintergrund erklärt und eine Vielzahl von Beispielen für interne und externe Stakeholder genannt. Die Notwendigkeit einer Stakeholderanalyse ist essenziell, da das Handeln der verschiedenen Interessengruppen einen großen Einfluss auf die Erfolgswahrscheinlichkeit eines Projektes hat. Im Folgenden wird auf die Anwendung der Stakeholderanalyse eingegangen. Zunächst kommt es zur Identifikation und Kategorisierung der verschiedenen Interessengruppen. Für diesen Vorgang werden viele beispielhafte Verfahren genannt. Anschließend muss deren Einstellung gegenüber dem Projekt bewertet werden. Daraufhin wird ein Ranking erstellt, in welchem die Stakeholder nach ihrer Relevanz geordnet werden. Es folgt eine Darstellung eines beispielhaften Templates für eine Stakeholderanalyse. Zusätzlich wird die Macht/Interesse-Matrx nach Johnson/Scholes visuell dargestellt. Zum Schluss wird eine Kontrolle der Zielerreichung durchgeführt, woraus wichtige Erfahrungen für zukünftige Projekte gezogen werden.

# Positive Aspekte

Zu Beginn des Artikels wird auf den Hintergrund der Stakeholderanalyse eingegangen, wodurch das Thema sehr gut in den Kontext eingeordnet wird. Außerdem wird dem Leser dadurch der Einstieg in das Thema erleichtert. Der gesamte Artikel lässt sich sehr flüssig und angenehm lesen. Das Front-Matter wurde korrekt ausgefüllt und der Umfang des Beitrags wurde erfüllt. Es wurden außerdem alle Absätze umfassend mit Quellen belegt, welche die Möglichkeit bieten, sich tiefer mit dem Themenfeld auseinanderzusetzen. Zusätzlich gibt es Verlinkungen zu angrenzenden Beiträgen, welche alle einwandfrei funktionieren. Die Formatierung des gesamten Artikels ist sehr gut und für Aufzählungen wurden Punktelisten gewählt. Die Grafiken sind ebenfalls sehr treffend gewählt und veranschaulichen das Geschriebene gut. Der Artikel ist außerdem gut strukturiert, was den Inhalt für die Zielgruppe verständlich und zugleich ansprechend macht.


# Negative Aspekte

Ein einziger Kritikpunkt ist die Rechtschreibung, welche an wenigen Stellen noch angepasst werden muss. Hier wurden lediglich einzelne Buchstaben vertauscht, ein Satzzeichen zu viel gesetzt oder ein Wort vergessen. Ansonsten sind keine negativen Punkte anzuführen.

2021-12-09 19:48 UTC, merged

2021-12-15 10:18 UTC, CTM-development commented
| Kriterium | Bewertung|
|-----|---|
| Front-Matter | ja |
| Umfang | ja |
| Belege | ja  |
| Links | ja|
| Formatierung | ja |
| Verlinkungen vorhanden | ja |
| Abbildungen | ja |
| Strukturierung des Beitrags | 10 |
| Rechtschreibung | 10 |
| Sprache | 10 |
| Inhalt | 10 |
| Einordnung in den Kontext | 10 |
| Ansprechend für Zielgruppe | 10 |

# Zusammenfassung

Der Artikel erklaert Stakeholderanalyse, die Grundlagen und Relevanz dieser sowie den Praxisprozess fuer den Anwendungsfall.

# Positive Aspekte

Durchweg guter Artikel. Verlinkungen sind ausreichend vorhanden und sinnvoll eingesetzt. Die Formulierung und Strukturierung des Artikels ist auch durchwegs sehr gut. Die beiden Abbildungen ergaenzen den Artikel sinnvoll.

# Negative Aspekte

-

2021-12-15 10:18 UTC, CTM-development commented
Von mir lieder mit einiger Verspaetung, sorry. Hatte Ende letzter Woche schon erste Klausuren :(

2021-12-21 14:34 UTC, DanielLu21 commented
> Kriterium	Bewertung
> Front-Matter	ja
> Umfang	ja
> Belege	ja
> Links	ja
> Formatierung	ja
> Verlinkungen vorhanden	ja
> Abbildungen	ja
> Strukturierung des Beitrags	10
> Rechtschreibung	9
> Sprache	10
> Inhalt	10
> Einordnung in den Kontext	10
> Ansprechend für Zielgruppe	10
> # Zusammenfassung
> Der Artikel beschäftigt sich mit der sogenannten Stakeholderanalyse. Zu Beginn des Artikels wird dieser Begriff definiert. Es handelt sich hierbei um die systematische Identifikation und Steuerung der gesamten Interessengruppen eines Projektes. Anschließend wird dessen Hintergrund erklärt und eine Vielzahl von Beispielen für interne und externe Stakeholder genannt. Die Notwendigkeit einer Stakeholderanalyse ist essenziell, da das Handeln der verschiedenen Interessengruppen einen großen Einfluss auf die Erfolgswahrscheinlichkeit eines Projektes hat. Im Folgenden wird auf die Anwendung der Stakeholderanalyse eingegangen. Zunächst kommt es zur Identifikation und Kategorisierung der verschiedenen Interessengruppen. Für diesen Vorgang werden viele beispielhafte Verfahren genannt. Anschließend muss deren Einstellung gegenüber dem Projekt bewertet werden. Daraufhin wird ein Ranking erstellt, in welchem die Stakeholder nach ihrer Relevanz geordnet werden. Es folgt eine Darstellung eines beispielhaften Templates für eine Stakeholderanalyse. Zusätzlich wird die Macht/Interesse-Matrx nach Johnson/Scholes visuell dargestellt. Zum Schluss wird eine Kontrolle der Zielerreichung durchgeführt, woraus wichtige Erfahrungen für zukünftige Projekte gezogen werden.
> 
> # Positive Aspekte
> Zu Beginn des Artikels wird auf den Hintergrund der Stakeholderanalyse eingegangen, wodurch das Thema sehr gut in den Kontext eingeordnet wird. Außerdem wird dem Leser dadurch der Einstieg in das Thema erleichtert. Der gesamte Artikel lässt sich sehr flüssig und angenehm lesen. Das Front-Matter wurde korrekt ausgefüllt und der Umfang des Beitrags wurde erfüllt. Es wurden außerdem alle Absätze umfassend mit Quellen belegt, welche die Möglichkeit bieten, sich tiefer mit dem Themenfeld auseinanderzusetzen. Zusätzlich gibt es Verlinkungen zu angrenzenden Beiträgen, welche alle einwandfrei funktionieren. Die Formatierung des gesamten Artikels ist sehr gut und für Aufzählungen wurden Punktelisten gewählt. Die Grafiken sind ebenfalls sehr treffend gewählt und veranschaulichen das Geschriebene gut. Der Artikel ist außerdem gut strukturiert, was den Inhalt für die Zielgruppe verständlich und zugleich ansprechend macht.
> 
> # Negative Aspekte
> Ein einziger Kritikpunkt ist die Rechtschreibung, welche an wenigen Stellen noch angepasst werden muss. Hier wurden lediglich einzelne Buchstaben vertauscht, ein Satzzeichen zu viel gesetzt oder ein Wort vergessen. Ansonsten sind keine negativen Punkte anzuführen.

Hallo ux49azap,

vielen Dank für Dein ausführliches Feedback! Ich werde bei meiner Überarbeitung Deine Anmerkungen berücksichtigen. 

Beste Grüße
Daniel

2021-12-21 14:35 UTC, DanielLu21 commented
> Kriterium	Bewertung
> Front-Matter	ja
> Umfang	ja
> Belege	ja
> Links	ja
> Formatierung	ja
> Verlinkungen vorhanden	ja
> Abbildungen	ja
> Strukturierung des Beitrags	10
> Rechtschreibung	10
> Sprache	10
> Inhalt	10
> Einordnung in den Kontext	10
> Ansprechend für Zielgruppe	10
> # Zusammenfassung
> Der Artikel erklaert Stakeholderanalyse, die Grundlagen und Relevanz dieser sowie den Praxisprozess fuer den Anwendungsfall.
> 
> # Positive Aspekte
> Durchweg guter Artikel. Verlinkungen sind ausreichend vorhanden und sinnvoll eingesetzt. Die Formulierung und Strukturierung des Artikels ist auch durchwegs sehr gut. Die beiden Abbildungen ergaenzen den Artikel sinnvoll.
> 
> # Negative Aspekte

Hallo CTM-development,

vielen Dank für Dein Feedback!

Beste Grüße 
Daniel