Kaizen.md Beitrag
ManagingProjectsSuccessfully/ManagingProjectsSuccessfully.github.io pull request #331
Opened 2021-11-24 21:22 UTC by tkessler94

:)

2021-12-04 13:41 UTC, ux49azap requested changes
| Kriterium | Bewertung|
|-----|---|
| Front-Matter | nein |
| Umfang | nein|
| Belege | ja |
| Links | nein|
| Formatierung | nein|
| Verlinkungen vorhanden | ja |
| Abbildungen | ja |
| Strukturierung des Beitrags | 8 |
| Rechtschreibung | 7|
| Sprache | 7 |
| Inhalt | 8|
| Einordnung in den Kontext | 9|
| Ansprechend für Zielgruppe | 8|

# Zusammenfassung

Der Artikel befasst sich mit der japanischen Lebens- und Arbeitsphilosophie „Kaizen“, welche ein kontinuierliches Streben nach Verbesserung beinhaltet. Im vorliegenden Artikel wird der Begriff zunächst erläutert und anschließend in den historischen Kontext eingeordnet.  Des Weiteren wird die Ausführung des PCDA-Zyklus erklärt. Dabei handelt es sich um ein Konzept, bei welchem jeder Mitarbeiter die Möglichkeit hat, Verbesserungsvorschläge zu äußern, welche den Wertschöpfungsablauf des Unternehmens verbessern. Anschließend wird ein Ausblick gegeben und die Erfolgsgeschichte des Toyota Produktionssystems als Beispiel genannt. Abschließend werden noch die Voraussetzungen und die Ausführung von Kaizen erläutert und mithilfe einer Grafik veranschaulicht.

# Positive Aspekte

Die Begriffserklärung sowie die Einordnung in den historischen Kontexts zu Beginn des Beitrags sind gut gelungen und erleichtern dem Leser den Einstieg in das Thema. Die beispielhafte Abbildung ist ebenfalls gut gewählt und hilft beim Verständnis der Thematik weiter. Außerdem ist der Bereich „Verwandte Artikel“ umfassend bearbeitet und ermöglicht es, sich tiefer mit dem Themenfeld auseinanderzusetzen. 

# Negative Aspekte

Sprachlich weißt der Artikel einige Lücken auf: die Rechtschreibung, der Satzbau und die Sprache sollten hier überarbeitet werden. Im Front-Matter wurde keine Auswahl bei der Anrechnung (k oder a) getroffen. Der Umfang des Textes ist leider etwas zu kurz, hier sollten noch einige Sätze ergänzt werden . Die Großzahl der Links funktioniert einwandfrei, allerdings wird der erste Link bei den Quellen nicht im Text angezeigt und kann somit nicht aufgerufen werden. Bei den Formatierungen gibt es bei der letzten Überschrift "Voraussetzungen und Ausführung" einen Fehler, diese wird im Text nicht als Überschrift angezeigt.

2021-12-04 16:45 UTC, nrivo requested changes
| Kriterium | Bewertung|
|-----|---|
| Front-Matter | nein |
| Umfang | nein|
| Belege | ja |
| Links | ja |
| Formatierung | ja|
| Verlinkungen vorhanden | ja|
| Abbildungen | ja|
| Strukturierung des Beitrags | 8 |
| Rechtschreibung | 6|
| Sprache | 6|
| Inhalt | 7|
| Einordnung in den Kontext | 8|
| Ansprechend für Zielgruppe | 7|

# Zusammenfassung

Der Artikel befasst sich mit der Methodik von „Kaizen“, welche das Streben nach kontinuierlicher und unendlicher Verbesserung zum Inhalt hat. Dabei wird in diesem Artikel unter anderem die Bedeutung des Begriffs erklärt sowie der historische Hintergrund beleuchtet. Kaizen wird als Kern der Lean Management Philosophie gesehen. Den größten Erfolg hatte Kaizen beim Toyota Produktionssystem. Die Umsetzung von Kaizen erfolgt dabei in Workshops, in denen Verbesserungen konsolidiert werden und dabei der „PCDA-Zyklus“ herangezogen wird. Dabei handelt es sich um eine feste Ablauffolge, bei der zuerst Abweichungen erkannt werden, hierfür Verbesserungsvorschläge geplant werden, welche daraufhin ausgeführt werden. Zum Schluss wird deren Wirksamkeit überprüft und bei Erfolg ein neuer Standard gesetzt. Dieser Ablauf wird dabei durch eine Abbildung visualisiert.

# Positive Aspekte

Gelungen ist der Einstieg in das Thema mit der Darstellung der Bedeutung von Kaizen. Positiv fällt auf, dass das Konzept von Kaizen in Unternehmen beschrieben wird und in den historischen Kontext gesetzt wird. Auch ist positiv hervorzuheben, dass der Artikel anhand eines Beispiels die praktische Umsetzung von Kaizen erläutert. Gelungen ist auch die Erklärung des „PDCA-Zyklus“, wodurch eine Vorstellung des Konzepts geschaffen wird und zum Verständnis des Artikels sehr gut beiträgt. Durch die beigefügte Abbildung wird der Prozess gut veranschaulicht. Weiter wurde die Quelle für die Abbildung angegeben. Zudem funktionieren alle Links. Unter "Verwandte Artikel" lassen sich viele Links finden, sodass man sich in das Thema ausführlich vertiefen kann.

# Negative Aspekte

Der Artikel weist einige Mängel auf. So wurde im Front-Matter nicht angegeben, für welchen Bereich der Artikel angerechnet werden soll. Der Umfang fällt etwas kurz aus und sollte daher erweitert werden. Die Abbildung wurde so platziert, dass die Zeile umgebrochen wurde und der vorhergegangene Satz somit strukturell auseinandergerissen wird. Zur Vermeidung von Zeilenumbrüchen sollte deshalb die Abbildung unter dem vollständigen Absatz platziert werden. Inhaltlich fehlt der gedankliche Übergang vom „PDCA-Zyklus“ in der historischen Einordnung zum Kaizen. Auch sollte „Lean Management“ entweder kurz erklärt oder zu einer Seite verlinkt werden. Alternativ würde auch eine Verlinkung bei „Verwandte Artikel“ zur Erklärung beitragen. 
Des Weiteren enthält der Artikel einige Schwächen in der Rechtschreibung sowie Grammatik und sollte dahingehend überarbeitet werden. Beispielsweise wird in der historischen Einordnung „PCDA-Zyklus“ statt „PDCA-Zyklus“ geschrieben oder bei „Wirtschaftsstandort“ das zweite „t“ ausgelassen. Unklar bleibt, ob Kaizen wie in der Artikelüberschrift zusammengeschrieben wird oder getrennt wie in den Kapiteln „Ausblick“ und „Bekannte Beispiele“. 
Bei der Formatierung traten kleine Fehler auf. So wird hinter der Überschrift „Kaizen“ „[1]“ angezeigt. Auch wurde die Unterüberschrift „##Voraussetzungen und Ausführung“ im Kapitel „Bekannte Beispiele“ nicht als solche dargestellt, sondern befindet sich im Fließtext. Bei der Quelle wird „[Kaizen, Lean Management und Digitalisierung]“ nicht als Link angezeigt. Es sollte mehr als eine Quelle verwendet werden. Zudem sollte zumindest jeder Absatz eine Quellenangabe enthalten. Vorliegend wurde jedoch nur die Abbildung mit einer Quelle versehen.

2021-12-09 19:48 UTC, merged

2021-12-15 10:17 UTC, CTM-development commented
Von mir leider mit einiger Verspaetung, hatte Ende letzter Woche schon Klausuren :]

2021-12-15 10:18 UTC, CTM-development commented
| Kriterium | Bewertung|
|-----|---|
| Front-Matter | nein |
| Umfang | ja |
| Belege | ja  |
| Links | nein |
| Formatierung | nein |
| Verlinkungen vorhanden | ja |
| Abbildungen | ja |
| Strukturierung des Beitrags | 7 |
| Rechtschreibung | 6 |
| Sprache | 6 |
| Inhalt | 8 |
| Einordnung in den Kontext | 8 |
| Ansprechend für Zielgruppe | 7 |

# Zusammenfassung

Der Artikel befasst sich mit dem Unternehmenskonzept "Kaizen". Es wird auf die historische Entstehung von Kaizen und dessen Bedeutung in der japanischen Firmenkultur eingegangen. Als Anwedungsbeispiel wird Toyotas Produktionssystem erwaehnt.

# Positive Aspekte

Der Begriff Kaizen wurde gut erklaert. Die Historische Einordnung und das Aufzeigen der Relevanz von Kaizen fuer die japanische Firmenkultur wurde anschaulich gezeigt.

# Negative Aspekte

Nur eine Quelle ist etwas spaerlich meiner Meinung nach. 
In vielen Saetzen fehlen teilweise Woerter.
Es wurden kaum Verweise auf andere Kompendiums-Artikel verwendet. 
Die Strukturierung ist etwas komisch meiner Meinung nach, ich glaube aber auch, dass mind. eine Uberschrifft im Text verloren gegangen ist, bzw. nicht funktioniert. 
Ich wuerde den Text unter "Bekannte Beispiele" noch etwas aufspalten, um da nicht so einen riessigen Textblock zu haben.