Klassische Missverstaendnisse
ManagingProjectsSuccessfully/ManagingProjectsSuccessfully.github.io pull request #332
Opened 2021-11-24 21:25 UTC by ux49azap

2021-12-07 12:48 UTC, emir-eroglu requested changes
| Kriterium | Bewertung|
|-----|---|
| Front-Matter | ja |
| Umfang | ja|
| Belege | ja |
| Links | ja|
| Formatierung | ja|
| Verlinkungen vorhanden | ja |
| Abbildungen | ja|
| Strukturierung des Beitrags |10 |
| Rechtschreibung | 10|
| Sprache | 9 |
| Inhalt | 10|
| Einordnung in den Kontext | 10|
| Ansprechend für Zielgruppe | 9|

# Zusammenfassung
Interessante Einführung in das Thema Missverständnisse in Projekten. Die  Ursachen der Missverständnisse werden im weiteren Verlauf, in Bezug auf das klassische Projektmanagement, genauer dargestellt. Das alles wird mit Abbildungen untermauert und mündet in einem abschließenden Fazit.


# Positive Aspekte
* Beitrag schafft ein gutes allgemeines Verständnis zu dem Thema
* Kurze und prägnante Formulierungen 
* Erklärung der Gründe von Missverständnissen
* Einfache Abbildungen  

# Negative Aspekte
* Ich persönlich würde jedes Wort mehrfach verlinken,  sodass man nicht nach der Verlinkung sucht. (z.B.: "Projektmanagement" ist nur einmal verlinkt aber kommt öfters vor. Dies würde ich auch im weiteren Verlauf jeweils einzeln verlinken.
* Optisch könnte man die Unterpunkte von der Größe her besser anpassen, in dem Fall verkleinern. Überschrift > Unterpunkte (1 bis 5) > Unterpunkt 4.1 
Was geht besser (Bezug zur Tabelle)

2021-12-08 15:54 UTC, nrivo requested changes
| Kriterium | Bewertung|
|-----|---|
| Front-Matter | ja|
| Umfang | ja|
| Belege | ja |
| Links | ja|
| Formatierung | nein|
| Verlinkungen vorhanden | ja |
| Abbildungen | ja|
| Strukturierung des Beitrags | 8 |
| Rechtschreibung | 10|
| Sprache | 10 |
| Inhalt | 10|
| Einordnung in den Kontext | 10|
| Ansprechend für Zielgruppe | 10|

# Zusammenfassung

Der Artikel befasst sich mit Missverständnissen im klassischen Projektmanagement. Dabei wird erläutert, durch welche Eigenschaften des klassischen Projektmanagements es zu Missverständnissen kommen kann. Da das klassische Projektmanagement auf einem monolithischen Ansatz beruht, das Endergebnis des Projekts somit zu dessen Beginn bereits feststeht, können Missverständnisse durch die mangelnde Flexibilität des klassischen Projektmanagements bei Veränderungen entstehen. Auch führt der Einbezug von Reserve zu potenziellen Missverständnissen, da dadurch eine konkrete Planung an Transparenz verliert. Darüber hinaus ergeben sich Unstimmigkeiten durch die Unteilbarkeit der Projektphasen in kleinere Blöcke, wodurch sich Fehlentscheidungen erst nach der Projektphase bemerkbar machen. Eng damit verbunden ist die Problematik, dass ein Feedback des Auftraggebers erst am Ende des Projekts erfolgt, was weiteren Raum für Missverständnisse schafft. Durch unverhältnismäßige Rahmenbedingungen verstärken sich diese Missverständnisse. Somit ist immer zuvor abzuwägen, ob die Anwendung des klassischen Projektmanagements bei einem bestimmten Projekt sinnvoll ist oder das agile Projektmanagement vorzugswürdiger ist.

# Positive Aspekte

Positiv auffallend ist der gute Einstieg, der den Leser sofort abholt. Die Sätze sind kurz und einfach gehalten, wodurch man dem Text sehr leicht folgen kann und direkt ein Verständnis für die Thematik bekommt. Auch ist die Unterteilung der Missverständnisse in einzelne Kapitel sehr gelungen und trägt zu einer guten Übersichtlichkeit bei. Die Abbildungen sind einfach gehalten und veranschaulichen den Text sehr verständlich. Gelungen sind sowohl Rechtschreibung als auch Grammatik, der Artikel ist sehr sachlich geschrieben und zeigt eine gute inhaltliche Gliederung auf. Die einzelnen Überschriften zeigen die Missverständnisse übersichtlich auf. 

# Negative Aspekte

Etwas irreführend sind die nummerierten Überschriften. So ist nicht klar verständlich, ob die Überschriften 1. bis 5. bereits die einzelnen Missverständnisse darstellen oder „1. Ursache der Missverständnisse“ die Einleitung für die in 2. bis 5. aufgeführten Missverständnisse bildet. Insbesondere der letzte Satz in diesem Kapitel („Dieser standardisierte Vorgang kann im Laufe des Projekts allerdings zu mehreren verschiedenen Missverständnissen führen.“) lässt darauf schließen, dass „1. Ursache der Missverständnisse“ eine Hinleitung zu den einzelnen Missverständnissen darstellt, die anschließend in 2. bis 5. aufgeführt werden. Sollte 1. nur die Hinleitung sein, so wäre es geschickter, die nachfolgenden Kapitel als Unterüberschriften zur „Ursache der Missverständnisse“ zu verfassen. Zählt hingegen bereits „1. Ursache der Missverständnisse“ zu den aufgeführten Missverständnissen, so wäre es gegebenenfalls vorteilhaft, auf die Missverständnisse in diesem Kapitel näher einzugehen und genauer zu erklären, worin genau das Missverständnis liegt.

Grundsätzlich wäre es sinnvoller, bei den Überschriften die Nummerierung gänzlich wegzulassen.

Bei der strukturellen Gliederung ist darauf zu achten, dass immer mindestens zwei Überschriften bzw. Unterüberschriften vorhanden sind. Vorliegend besteht „4. Unstimmigkeiten beim Projektablauf“ jedoch nur aus einem Unterpunkt (4.1.). Daher sollte entweder noch ein zweiter Unterpunkt (4.2.) hinzugefügt werden oder der Unterpunkt insgesamt weggelassen werden.

Optimalerweise sollte noch der Begriff „Missverständnisse“ erklärt werden, da für den Leser unklar bleibt, ob damit Missverständnisse zwischen den Beteiligten eines Projekts gemeint sind oder ob damit vielmehr die generelle Fehlvorstellung bzw. falsche Erwartungshaltung vom klassischen Projektmanagement gemeint ist.

2021-12-09 19:48 UTC, merged

2021-12-15 10:15 UTC, CTM-development commented
| Kriterium | Bewertung|
|-----|---|
| Front-Matter | ja |
| Umfang | ja |
| Belege | ja  |
| Links | ja|
| Formatierung | ja |
| Verlinkungen vorhanden | ja |
| Abbildungen | ja |
| Strukturierung des Beitrags | 7 |
| Rechtschreibung | 10 |
| Sprache | 8 |
| Inhalt | 9 |
| Einordnung in den Kontext | 10 |
| Ansprechend für Zielgruppe | 10 |

# Zusammenfassung

Der zaehlt verschiedenen moegliche Missverstaendnisse des klassischen Projektmanagements auf, erlaeuter jeweils gut die Ursachen und Auswirkungen dieser Missverstaendnisse.

# Positive Aspekte

Im Grossen und Ganzen ist der Artikel im jetztigen Zustand schon sehr gelungen, mir sind nur wirklich vereinzelt kleinere Maengel/ bzw. Aenderungswuensche aufgefallen. Im komplette Artikel wurde inhaltlich sinnvoll und haeufig verlinkt.

# Negative Aspekte

Evtl. persoenlicher Geschmack, aber ich wuerde die Ueberschriften nicht durchnummerieren. Auch ist mir nicht ganz klar, anhand was die Ueberschriften konkret strukturiert sind. Ist das eine Aufzaehlung von moeglichen Missverstaendnissen? Falls ja, wuerde ich das anfangs evtl. kurz erwaehnen.

2021-12-15 10:16 UTC, CTM-development commented
Von mir nun leider mit einiger Verspaetung, hatte Ende letzter Woche schon Klausuren.

2021-12-17 18:48 UTC, ux49azap commented
> Von mir nun leider mit einiger Verspaetung, hatte Ende letzter Woche schon Klausuren.

Hallo CTM-development, danke dennoch für das verspätete Feedback. 

Deine Rückmeldung zur Struktur des Artikels verstehe ich und werde ich bei meiner Überarbeitung beachten.

Unklar ist mir allerdings dein Abzug bei der Sprache, da du hierzu keinerlei Angaben gemacht hast.
Wäre schön wenn du das noch ergänzen könntest :)

Viele Grüße