Projektcontrolling
ManagingProjectsSuccessfully/ManagingProjectsSuccessfully.github.io pull request #338
Opened 2021-11-24 21:55 UTC by hake1110

2021-12-05 18:10 UTC, goekcen01 requested changes
| Kriterium | Bewertung|
|-----|---|
| Front-Matter | ja |
| Umfang | nein | 
| Belege | ja |
| Links | ja |
| Formatierung | ja |
| Verlinkungen vorhanden | ja |
| Abbildungen | ja |
| Strukturierung des Beitrags | 9 |
| Rechtschreibung | 10 |
| Sprache | 10 |
| Inhalt | 10 |
| Einordnung in den Kontext | 10 |
| Ansprechend für Zielgruppe | 10 |

# Zusammenfassung

Der Artikel beschäftigt sich mit dem Thema "Projektcontrolling". Zunächst einmal wird der Begriff des Projektcontrollings definiert. Im Anschluss werden die drei Teilbereiche des Projektcontrollings im einzelnen ausgeführt. Abschließend werden noch die Kennzahlen und Methoden des Projektcontrollings dargestellt.


# Positive Aspekte
* Übersichtliche Strukturierungen, sowohl inhaltlich als auch visuell
* Korrekte Formatierung
* Die Aufteilung bei der weiterführenden Literatur gefällt mir gut
* Es wurde auf zahlreiche Beiträge aus dem Kompendium Bezug genommen
* Die eingefügten Abbildungen passen gut zum Inhalt  

# Negative Aspekte
* Kleiner Verbesserungsvorschlag für eine noch bessere Strukturierung: Der Text über der ersten Überschrift ist etwas zu lang für eine Kurzbeschreibung; hier würde ich eher eine kurze Begriffserklärung vorschlagen
* Mit einem Umfang von ca. 660 Wörter ist der Artikel zu lang
* Beim Abschnitt "Teilbereiche des Projektcontrollings" fehlen Quellenverweise bzw. Belege; hier würde ich mehr Fußnoten empfehlen

2021-12-07 10:21 UTC, hake1110 commented
Danke für das konstruktive Feedback.
Zum 1. negativen Aspekt: Der Text wird etwas länger, da die Definition laut DIN auch etwas länger ist. Ich wollte aber nichts von der Definition weglassen und finde die Länge ist noch im Rahmen und überschaubar
Zum 2. negativen Aspekt: Zitat Martin: "Kurze Anmerkung zur Bewertung des Umfangs: Bitte so bewerten, dass es ab 500 Wörtern ein 'ja' gibt. Wenn es mehr sind ist das unproblematisch (ausser jemand hat da den totalen Roman geschrieben)"
Ich denke mit 660 Wörtern liege ich da noch im Rahmen ;)
Zum 3. negativen Aspekt: Es fehlen keine Quellen, sondern ich habe nur eine Quelle verwendet. Es war schwierig dazu mehrere brauchbare Quellen zu finden, aber vllt kann ich noch eine weitere Quelle dazu finden

2021-12-08 03:25 UTC, phiLippFAU requested changes
| Kriterium | Bewertung |
|-----|---|
| Front-Matter | ja |
| Umfang | ja |
| Belege | ja |
| Links | ja |
| Formatierung | ja |
| Verlinkungen vorhanden | ja |
| Abbildungen | ja |
| Strukturierung des Beitrags | 9 |
| Rechtschreibung | 10 |
| Sprache | 9 |
| Inhalt | 9 |
| Einordnung in den Kontext | 10 |
| Ansprechend für Zielgruppe | 10 |


# Zusammenfassung

Der Beitrag beschäftigt sich mit dem Thema „Projektcontrolling“. Zu Beginn wird der Begriff definiert. Im Hauptteil liegt der Fokus auf den drei Teilbereichen des Projektcontrollings sowie den Kennzahlen und Methoden. Die einzelnen Bereiche wie auch die unterschiedlichen Methoden werden dabei jeweils ausführlich beschrieben und erklärt.


# Positive Aspekte

* übersichtliche Strukturierung (Zwischenüberschriften verhelfen zu einem stimmigen Gesamteindruck)
* Abbildungen unterstützen den Inhalt gut
* sinnvoll eingebaute Verlinkungen zu anderen Artikeln + unter "Siehe auch" alle noch einmal aufgeführt
* Links funktionieren einwandfrei
* guter Lesefluss


# Negative Aspekte

* Strukturierung:
fehlende Überschrift zwischen "Front-Matter" und "Definition";
derzeit noch im Rahmen, jedoch bei weiterer Ausführung und Zunahme von Inhalt würde es sich anbieten mit 1., 2., 3., ... (oder a), b), c), ...) zu arbeiten, um den Überblick bei den Zwischenüberschriften nicht zu verlieren

* Sprache/Umfang:
häufig zu ausführlich formuliert (siehe bspw. 1. Absatz), daher Artikel mit 600+ Wörtern zu lang

* Links:
bei den Quellen: Titel der Websiten mit hinterlegtem Link ansprechender (anstatt der reinen URL)

2021-12-08 08:25 UTC, hake1110 commented
Danke für das Feedback @phiLippFAU 
**Zur Strukturierung**: 1. Im Template steht explizit, dass zwischen Front matter und Definition keine Überschrift eingefügt werden soll, das geschieht automatisch.
**Zur Sprache / Umfang:** In dem Kommentar darüber habe ich schon mal darauf hingewiesen, dass 660 Wörter noch im Rahmen sind. Ich werde aber nochmal überprüfen, ob ich mich an manchen Stellen kürzer fassen kann. Bei der Definition erachte ich alle genannten Details als wichtig.
**Zu den Links:** Da hast du recht, da werde ich noch mal drüber schauen

2021-12-08 16:18 UTC, Angie4321 commented
Hey, kannst du bitte aufhören deinen Beitrag jetzt schon zu ändern. Es ist immer noch der Review-Prozess, d.h. bei jeder Änderung, die du speicherst, bekommen deiner 3 Reviewer eine E-Mail. Ich habe heute bestimmt schon 40 Mails deswegen.

Liebe Grüße

2021-12-08 16:24 UTC, phiLippFAU commented
Ja, ist echt nervig, stimme da @Angie4321 zu.

2021-12-08 16:44 UTC, phiLippFAU commented
@hake1110 Hallo???

2021-12-08 17:36 UTC, Angie4321 requested changes
Hinweis: Leider kann ich nicht den ursprünglichen Beitrag reviewen, da der/die Verfasser/in bereits nach den ersten 2 Review´s Änderungen vorgenommen hat. Ich bewerte somit den Beitrag zum Stand 08.12.2021, 18:15 Uhr.

| Kriterium | Bewertung|
|-----|---|
| Front-Matter | ja |
| Umfang | ja |
| Belege | ja |
| Links | ja |
| Formatierung | ja |
| Verlinkungen vorhanden | ja |
| Abbildungen | ja |
| Strukturierung des Beitrags | 9 |
| Rechtschreibung | 9 |
| Sprache | 10 |
| Inhalt | 10 |
| Einordnung in den Kontext | 10 |
| Ansprechend für Zielgruppe | 10 |

# Zusammenfassung

Zu Beginn wird der Begriff "Projektcontrolling" definiert und anschließend eingeordnet in das Thema Projektmanagement. Im Hauptteil werden zum Einen die verschiedenen Teilbereiche des Projektcontrollings erläutert und zum Anderen  Kennzahlen und Methoden im Projektcontrolling vorgestellt. Veranschaulicht wird der Beitrag mit passenden Bildern.

# Positive Aspekte

- kurze und prägnante Einleitung, welche zum Weiterlesen anregt
- schöne Einordnung in das Thema Projektmanagement
- Abbildungen veranschaulichen den Inhalt gut
- leicht lesbar durch den einfachen Satzbau und die sachliche Sprache
- Der Verweis auf die weiterführende Literatur und die zahlreichen Bezüge zu anderen Beiträgen aus dem Kompendium gefällt mir gut.

# Negative Aspekte

- Um den Überblick bei den zahlreichen Zwischenüberschriften zu bewahren, wäre es vielleicht sinnvoll mit 1.,2.,3. usw. oder a),b),c) zu arbeiten.
- Bei den Abbildungsunterschriften sollten die Punkte weg, da es sich hierbei nicht um Sätze handelt.
- vielleicht die Links lieber mit Titel der Websiten hinterlegen, statt mit der reinen URL
- ein Rechtschreib-/Grammatikfehler ist mir noch aufgefallen bei der Meilensteinanalyse letzter Satz, am Besten das "sich" raus nehmen, ansonsten sehr schön geschrieben

2021-12-08 18:32 UTC, hake1110 commented
Sorry war mir nicht bewusst, dass ihr jedes mal ne Mail bekommt. Dachte man kann schon seinen Beitrag korrigieren, sobald die ersten Reviews da sind. @phiLippFAU @Angie4321

2021-12-09 19:49 UTC, merged