Update Machine_Learning_im_Projektmanagement.md
ManagingProjectsSuccessfully/ManagingProjectsSuccessfully.github.io pull request #340
Opened 2021-11-24 22:14 UTC by phiLippFAU

2021-12-05 23:03 UTC, goekcen01 requested changes
| Kriterium | Bewertung|
|-----|---|
| Front-Matter | ja |
| Umfang | ja |
| Belege | ja |
| Links | ja |
| Formatierung | ja |
| Verlinkungen vorhanden | ja |
| Abbildungen | ja |
| Strukturierung des Beitrags | 7 |
| Rechtschreibung | 9 |
| Sprache | 10 |
| Inhalt | 8 |
| Einordnung in den Kontext | 10 |
| Ansprechend für Zielgruppe | 9 |

# Zusammenfassung

Der Artikel befasst sich mit Machine Learning im Projektmanagement. Anfangs wird zunächst einmal Machine Learning allgemein definiert. Danach wir die Arbeitsweise von ML im PM erklärt und es wird auf die 4 Stufen des ML´s eingegangen. Nachdem daraufhin die Einsatzgebiete von ML im PM erläutert wurden, wird der Artikel mit dem aktuellen Stand, den Zielen und Chancen abgeschlossen. 

# Positive Aspekte
* Bezugnahme auf angrenzende Themen 
* Gute Rechtschreibung/Grammatik 
* Es wurden den Inhalt ergänzende Abbildungen eingesetzt
* Die Links funktionieren
* Es werden Fachwörter genutzt, allgemein ist die Sprache gut verständlich und sachlich


# Negative Aspekte
* Keine weiterführende Literatur vorhanden
* Die Überschriften sind zu lang; z.B. könntest du nur "Die 4 Stufen des Machine Learning", anstelle eines ganzen Satzes, als Überschrift nehmen
* Die Nummerierung der Überschriften würde ich persönlich weglassen
* Nachdem ML allgemein erklärt wurde, fehlt m.M.n. eine kurze Verknüpfung zum Einsatz im PM. Ich würde dir empfehlen, den Einsatz bzw. die Einsatzgebiete von ML im PM vor die Arbeitsweise zu ziehen
* Bei dem Punkt  "4 Stufen von ML" würde ich dir raten die Aufzählung wie beim Template mit 1.,2.,... zu formatieren
* Der letzte Abschnitt (v.A. die letzten zwei Sätze) könnten inhaltlich nochmal überarbeitet werden. Die ersten zwei Sätze sind ziemlich ähnlich wie der Text aus der angegeben Quelle. Hier würde ich empfehlen eigene Beispiele aus dem Alltag einzubringen. Anstelle der offenen Frage im Anschluss könntest du näher auf die Ziele, Chancen oder bereits für die Zukunft geplante Einsätze von ML im PM eingehen.
* Bei dem letzten Satz verwirren mich die Wörter "daher" und " die Folge". Auf was sich diese Wörter beziehen, konnte ich leider nicht ganz verstehen

2021-12-08 04:27 UTC, phiLippFAU commented
Hey, Danke für das ausführliche Feedback.

Ich hätte ein paar Nachfragen bzw. Erklärungen zu den negativen Aspekten und den daraus resultierenden Punktabzügen:

* Überschrift ist zu lang bezogen auf "Die 4 Stufen des Machine Learning": 
soll in dem Sinne keine wirkliche Überschrift sein (daher auch ohne Nummerierung), sondern den Satz visuell hervorheben ohne das der Lesefluss darunter leidet

* "Ich würde dir empfehlen, den Einsatz bzw. die Einsatzgebiete von ML im PM vor die Arbeitsweise zu ziehen":
sehe ich anders, da es sich bei der Arbeitsweise wie auch bei der Definition in gewisser Weise um Theorie handelt und sich die Einsatzgebiete (Praxis) besser mit den Zielen und Chancen im Fazit verknüpfen lassen

* Aufzählung wie beim Template formatieren:
hätte nicht zu den Nummerierungen der Hauptüberschriften gepasst, werde diese aber weglassen und die Stadien dann von (1) zu 1. usw. ändern

* zum letzten Abschnitt:
fand die zitierten Sätze haben es ziemlich auf den Punkt gebracht, daher habe ich sie so aus der Quelle übernommen, aber den Vorschlag mit eigenen Beispielen werde ich auf jeden Fall berücksichtigen;
näher auf die Ziele, Chancen, Einsätze einzugehen ist geplant, hätte nur den 500 Wörter - Rahmen um einiges gesprengt;
"daher": bezogen auf die verschiedenen Möglichkeiten, die die KI bzw. ML bietet;
"die Folge": ... ein großer Teil der Zeit wird mit Routineaufgaben verbracht, daraus folgt, dass die [Zeit] dann für weitaus sinnvollere Tätigkeiten fehlt

* Rechtschreibung?

Würde mich freuen, wenn du dein Review unter den genannten Punkten nochmal durchgehen und gegebenfalls überarbeiten könntest. :)

2021-12-08 16:38 UTC, phiLippFAU commented
Danke für dein Review. @jacobbocai 

Kurz 2 Punkte zu deinen negativen Aspekten:

* Wenige Verlinkungen:
Es haben sich meiner Ansicht nach keine weiteren Artikel des Kompendiums dafür angeboten, wäre für konkrete Vorschläge dankbar.

* Vertauschen von Prescriptive und Predictive:
Stimmt nicht, müssest du nochmal in die Quelle reinschauen, da es im Beitrag in korrekter Reihenfolge wiedergegeben wurde.

2021-12-08 18:12 UTC, Phr4nk20 requested changes
| Kriterium | Bewertung|
|-----|---|
| Front-Matter | ja |
| Umfang | ja |
| Belege | ja |
| Links | ja |
| Formatierung | ja |
| Verlinkungen vorhanden | ja |
| Abbildungen | ja |
| Strukturierung des Beitrags | 10 |
| Rechtschreibung | 10 |
| Sprache | 10 |
| Inhalt | 10 |
| Einordnung in den Kontext | 9 |
| Ansprechend für Zielgruppe | 10 |

# Zusammenfassung

Der Artikel befasst sich mit Machine Learning im Projektmanagement. Zu Beginn des Beitrags wird Machine Learning allgemein definiert. Die Grundlagen der Arbeitsweise von ML im PM einschließlich die 4 Stufen des ML´s werden beleuchtet. Nun werden Einsatzgebiete von ML im PM erläutert. Der Artikel schließt mit einem Ausblick über Ziele, Chance und Herausforderungen

# Positive Aspekte

Der Artikel ist gut strukturiert. Trotz der eingeschränkten maximalen Länge des Beitrags und dem doch großen Umfang von ML wurde ein guter Überblick geschaffen. 
Gute Rechtschreibung/Grammatik
Gut lesbare, verständliche und sinnvolle Abbildungen wurden eingesetzt
Verlinkungen auf andere Beiträge sind vorhanden und funktionieren
Allgemein ist die Sprache gut verständlich und sachlich

# Negative Aspekte

Keine weiterführende Literatur vorhanden
Der Inhalt von "3. Spezifische Einsatzgebiete von Machine Learning im Projektmanagement", besonders Absatz zwei und drei, wirkt auf mich noch nicht optimal strukturiert.
Allgemeine Hinweise:
Die Überschriften könnten teilweise prägnanter sein
Die Nummerierung der Überschriften ist m.M.n. nicht nötig
Bei der Aufzählung der 4 Stufen des ML würde ich die gleiche Formatierung wie im Rest des Beitrags wählen.

2021-12-08 19:41 UTC, goekcen01 commented
Hey, hier noch ein paar Kommentare meinerseits:

> * Überschrift ist zu lang bezogen auf "Die 4 Stufen des Machine Learning":
>   soll in dem Sinne keine wirkliche Überschrift sein (daher auch ohne Nummerierung), sondern den Satz visuell hervorheben ohne das der Lesefluss darunter leidet

Mein Änderungsvorschlag bezieht sich hier eigentlich auf alle Überschriften. M.m.n ist es nicht notwendig bei jeder Überschrift "Machine Learning im Projektmanagement" reinzuschreiben.


>   fand die zitierten Sätze haben es ziemlich auf den Punkt gebracht, daher habe ich sie so aus der Quelle übernommen, aber den Vorschlag mit eigenen Beispielen werde ich auf jeden Fall berücksichtigen;

Hier müsstest du dann bitte deutlicherer machen, dass es sich um ein Zitat handelt. z.B. mit Anführungszeichen.


>   näher auf die Ziele, Chancen, Einsätze einzugehen ist geplant, hätte nur den 500 Wörter - Rahmen um einiges gesprengt;

Ja klar, das war nur ein Vorschlag für einen Alternative zu der offenen Frage. Die bleibt ja leider unbeantwortet. Da ich anfangs die abschließenden Sätze nicht ganz verstanden hatte, wollte ich dir für eine eventuelle Überarbeitung paar Ideen mitgeben.

2021-12-09 19:49 UTC, merged