PRINCE2 & Impediment Backlog
ManagingProjectsSuccessfully/ManagingProjectsSuccessfully.github.io pull request #352
Opened 2021-11-24 22:40 UTC by patrick203494

2021-12-06 15:49 UTC, larissadiscua requested changes
| Kriterium | Bewertung|
|-----|---|
| Front-Matter | ja|
| Umfang | ja|
| Belege | ja |
| Links | ja|
| Formatierung | ja|
| Verlinkungen vorhanden | ja|
| Abbildungen | ja|
| Strukturierung des Beitrags | 10 |
| Rechtschreibung | 10|
| Sprache | 10 |
| Inhalt | 10|
| Einordnung in den Kontext | 10|
| Ansprechend für Zielgruppe | 10|

# Zusammenfassung

Im Beitrag zum Impediment Backlog geht es um verschiedene Störfaktoren, die Projekte beeinflussen können. Bei diesen Störfaktoren kann es sich von zu hohen Raumtemperaturen, bis hin zu persönlichen Konflikten untereinander handeln. Im Backlog soll vermerkt werden, wer betroffen ist, wie lange die Störung schon andauert und wer eine mögliche Kontaktperson sein kann. Durch diesen Beitrag lernt man, dass ein Impediment Backlog zwar häufig unterschätzt wird, jedoch eine wichtige Rolle in jedem Scrum-Projekt spielt.

Beim Beitrag zu PRINCE2 lernt man, dass dies ein Ansatz für die Ausgestaltung, Organisation und Management von Projekten ist. Man erfährt das Wichtigste zu den vier Grundbausteinen und den sieben Grundprinzipien, die sich mit verschiedenen Fragestellungen auseinander setzen. Zum Schluss werden noch die Stärken und mögliche Schwächen besprochen.

# Positive Aspekte

Die Beiträge sind beide sprachlich und inhaltlich sehr gut gestaltet, sie sind einfach und verständlich geschrieben und geben einen guten Überblick über die beiden Themen. Man erfährt Grundlegendes und dank zahlreicher Verlinkungen besteht die Möglichkeit, sich intensiver mit den Themen auseinanderzusetzen.

# Negative Aspekte

Meiner Meinung nach gibt es nichts zu bemängeln.

2021-12-08 18:11 UTC, Loris18 requested changes
| Kriterium | Bewertung|
|-----|---|
| Front-Matter | ja |
| Umfang | ja |
| Belege | ja |
| Links | ja |
| Formatierung | ja |
| Verlinkungen vorhanden | ja |
| Abbildungen | ja |
| Strukturierung des Beitrags | 10 |
| Rechtschreibung | 10 |
| Sprache | 10 |
| Inhalt | 10 |
| Einordnung in den Kontext |10 |
| Ansprechend für Zielgruppe | 10 |

# Zusammenfassung

Der Beitrag über Impediment Backlog handelt von Störfaktoren, die während eines Projektes auftreten können und deren visuelle Darstellung durch den Backlog. Dabei werden verschiedene Störfaktoren beleuchtet, sowie der idealtypische Ablauf beschrieben, diese Störfaktoren zu beseitigen. In dem Beitrag wird vor allem die Notwendigkeit eines Backlogs für Projekte herausgearbeitet und mit einem passenden Fazit abgerundet.

Der Beitrag bzgl. PRINCE2 setzt sich mit einem Best-Practice-Ansatz für Ausgestaltung, Organisation und Management von Projekten jeglicher Art auseinander. Dabei wird zunächst auf die Entwicklung des Ansatzes eingegangen. Anschließend werden die 4 Grundbausteine genannt und die 7 Grundprinzipen des Ansatzes erläutert. Abschließend erhält man einen Überblick über die Stärken und Schwächen des Ansatzes, sowie die Zertifizierung.

# Positive Aspekte

Die Strukturierung der Beiträge, die Auswahl der Abbildungen, die flüssige Lesbarkeit, die regelmäßigen Absätze und die klar verständlichen Sätze sind perfekt gelungen. Alles in allem geben die beiden Beträge einen kompakten und sehr verständlichen Überblick über die jeweilige Thematik, ohne zu stark ins Detail zu gehen. Auch die Einordnung in den Themenkontext ist sehr gelungen.

# Negative Aspekte

Ich kann dir keine Verbesserungsvorschläge geben, da die beiden Beiträge wirklich sehr gelungen sind und ich keinen Verbesserungsbedarf sehe.

2021-12-08 18:41 UTC, Paulqe42kuno requested changes
#Impediments Backlog:

| Kriterium | Bewertung|
|-----|---|
| Front-Matter | ja |
| Umfang | ja |
| Belege | ja |
| Links | ja |
| Formatierung | ja |
| Verlinkungen vorhanden | ja |
| Abbildungen | ja |
| Strukturierung des Beitrags | 10 |
| Rechtschreibung | 10 |
| Sprache | 10 |
| Inhalt | 10 |
| Einordnung in den Kontext | 10 |
| Ansprechend für Zielgruppe | 10 |

## Zusammenfassung
Der Artikel beschäftigt sich mit Impediments und dem Impediment Backlog. Impediments sind auftretende Hindernisse während eines Scrumprojekts, wie beispielsweise persönliche Konflikte zwischen Teammitgliedern . Der Impediment Backlog ist ein Verzeichnis, welches diese Hindernisse auflistet und priorisiert. Diese Verzeichnis wird beispielsweise in Form von  Excel-Tabellen oder in Projektmanagement - Tools dargestellt. Für das Vorgehen gegen Impediments und das Führen des Verzeichnis ist der Scrum-Master verantwortlich. Der idealtypische Umgang mit Impediments wird in 5 Phasen gegliedert: Aufnehmen, Priorisieren, Veröffentlichen, Handeln, Informieren. 

## Positive Aspekte
Du hast sehr viele Verlinkungen. Diese und die Links der Quellen funktionieren auch alle. Du hast an allen Stellen Belege und ebenfalls sehr viele. Inhalt Sprache und Aufbau sind top. Sehr guter Artikel insgesamt. 

## Negative Aspekte
Gleich im ersten Satz müsste das dann nicht in Klammern deutsch: "Behinderungen" heißen? Ich dachte lange der Artikel handelt von Impediment und nicht von den backlogs speziell. Aber da es keinen Artikel zu Impediments gibt passt das denke ich so. Ansonsten konnte ich tatsächlich keine Verbesserungsvorschläge finden. Ich glaube du kannst es mit gutem Gewissen abgegeben. 

#Prince 2:

| Kriterium | Bewertung|
|-----|---|
| Front-Matter | ja |
| Umfang | ja |
| Belege | ja |
| Links | ja |
| Formatierung | ja |
| Verlinkungen vorhanden | ja |
| Abbildungen | ja |
| Strukturierung des Beitrags | 10 |
| Rechtschreibung | 10 |
| Sprache | 10 |
| Inhalt | 10 |
| Einordnung in den Kontext | 10 |
| Ansprechend für Zielgruppe | 10 |

## Zusammenfassung
PRINCE2 Projektmanagement ist eine klassische Projektmanagementmethode für die Ausgestaltung, die Organisation und das Management von Projekten und kann auf jedes Projekt angewendet werden. Die vier Grundbausteine dieser Methodik sind: Die 7 PRINCE2 Grundprinzipien, die 7 PRINCE2 Themen (Business Case, Organisation, Qualität, Pläne, Risiken, Änderungen, Fortschritt), die 7 PRINCE2 Prozesse sowie die Anpassung von PRINCE2 an die Projektumgebung. Zum Schluss geht der Artikel noch auf die Stärken und Schwächen von PRINCE2 sowie dessen Zertifizierung ein. 

## Positive Aspekte
Du hast sehr viele Belege. Die Links dahinter funktionieren auch alle. Du hast ein Haufen Verlinkungen und diese funktionieren auch alle. Die Sprache Aufbau und Inhalt ist top. Super finde ich ebenfalls, dass du bei den Grundbausteinen von PRINCE2 geschaut hast, welche in diesem Kompendium verwendet werden und welche du noch erläutern musst. Insgesamt ein sehr guter Artikel.

## Negative Aspekte
Die Wort Anzahl ist sehr knapp. Soweit ich das richtig erfasst habe erreichst du diese nur mit den Überschriften. Ich weiß nicht ob diese dazuzählen. Ich würde entweder Vorteile und Nachteile schreiben oder Stärken und Schwächen. Des weiteren konnte ich wieder keine Punkte finden.

2021-12-09 19:50 UTC, merged

2021-12-21 08:28 UTC, patrick203494 commented
@larissadiscua @Paulqe42kuno @Loris18 
Hallo zusammen, 
danke für eure Reviews! :-)
Hat mich sehr gefreut, euer gutes Feedback zu hören.

------
@Loris18 
Bzgl. Impediment Backlog: 
Ich habe die Reihenfolge in der Einleitung vertauscht, sodass als erstes auf das Impediment Backlog eingegangen wird und dann erst im Anschluss Impediments erklärt. Da es wie du schon meintest keinen eigenständigen Artikel dazu gibt, ist es meiner Meinung nach Sinnvoll, genauer darauf einzugehen. Ich denke das macht dann in der Reihenfolge auf jeden Fall auch mehr Sinn, danke für den Tipp!

Bzgl. PRINCE2:
Guter Hinweis, ich habe auf "Vorteile" und "Nachteile" abgeändert.
Bzgl. der Wortanzahl bin ich mir jedoch nicht ganz sicher, was du meinst. Ich habe nochmal nachgesehen und den Artikel in Word reinkopiert. Dann hab ich alle Überschriften, Abbildung und Abbildungsbeschriftung rausgenommen und bin trotzdem bei über 510 Wörtern (Sofern man den Tabelleninhalt mitzählt) 
Aber die Überschriften zählen glaub ich ohnehin mit dazu, also sollte das eh kein Problem sein :-)
------

Lieben Gruß
Patrick