World Café
ManagingProjectsSuccessfully/ManagingProjectsSuccessfully.github.io pull request #355
Opened 2021-11-24 22:47 UTC by larissadiscua

2021-12-06 23:08 UTC, Loris18 requested changes
| Kriterium | Bewertung|
|-----|---|
| Front-Matter | ja |
| Umfang | ja |
| Belege | ja |
| Links | ja |
| Formatierung | ja |
| Verlinkungen vorhanden | ja |
| Abbildungen | ja |
| Strukturierung des Beitrags | 8 |
| Rechtschreibung |10|
| Sprache | 10|
| Inhalt |9|
| Einordnung in den Kontext | 7|
| Ansprechend für Zielgruppe |9|

# Zusammenfassung

Die World Café Methode ist eine interaktive Alternative zur klassischen Diskussion und soll Probleme aus verschiedenen Perspektiven betrachten, um neue Sichtweisen erhalten. Ein großer Vorteil ist die Wissensvernetzung und die Stärkung von Beziehungen zwischen Teilnehmenden und Teams. Wichtig zu beachten ist, dass bei der Planung vorab einige Fragen geklärt werden müssen, wie z.B. Kernthematik, Gruppenaufteilungen und Teilnehmerzahl, welche stark variieren kann. Zu Beginn des Cafés werden die Formalitäten  geklärt, sowie Moderatoren zu verschiedenen Tischen zugeteilt. Etwa 30 Minuten werden dort Themen mit sich wechselnden Teams von 4 bis 5 Leuten diskutiert, wobei die Diskussionsergebnisse der vorherigen Gruppen zu Beginn jeder Runde vom Moderator präsentiert werden. Hier empfiehlt sich, die jeweilige Diskussion mit Skizzen oder Stichpunkten festzuhalten. Am Ende werden die Ergebnisse in der gesamten Runde präsentiert und Lösungsmöglichkeiten zur Thematik abgeleitet.

# Positive Aspekte

Die Abbildung ist sehr gut gewählt, da sie sehr verständlich ist. Zudem funktionieren alle Links und Quellverweise. Der Beitrag ist klar und verständlich geschrieben, wodurch man einen kompakten Überblick über das Thema erhält. Zudem erleichtern die Absätze im Teil "Ablauf" den Lesefluss und sind gut gesetzt.

# Negative Aspekte

Den Teil "Eignung" würde ich auflösen und in den oberen bzw. unteren Abschnitt einfügen, da sich die letzten beide Sätze vom 1. Teil des Beitrags und dieses Teils sehr stark ähneln.
Zudem würde ich noch die Überschrift "World Café" vor Beginn des Beitrags ergänzen.
Möglicherweise könnte man die Aufzählung beim Teil "Planung" als Schaubild darstellen und allgemein einen kurzen Bezug zum Projektmanagement herstellen.
Als letzten Punkt hätte ich noch den Vorschlag, die Abbildung zu beschriften. (Sollte man soweit ich weiß bei jedem Artikel machen, aber bin mir da selbst nicht zu 100% sicher)

2021-12-07 01:08 UTC, Eugen0209 requested changes
| Kriterium | Bewertung|
|-----|---|
| Front-Matter | ja |
| Umfang | ja |
| Belege | ja |
| Links | ja |
| Formatierung | ja |
| Verlinkungen vorhanden | ja |
| Abbildungen | ja |
| Strukturierung des Beitrags | 9 |
| Rechtschreibung | 8 |
| Sprache | 9 |
| Inhalt | 10 |
| Einordnung in den Kontext | 9 |
| Ansprechend für Zielgruppe | 10 |

# Zusammenfassung

Der Artikel befasst sich mit der World Café Methode. Sie weist Ähnlichkeiten zur klassischen Diskussion auf, aber unterscheidet sich nicht unwesentlich. Probleme werden aus verschiedenen Perspektiven betrachtet, die neue Sichtweisen eröffnen kann. Vorteile sind Netzwerke, Innovation und Teambildung. Gruppenaufteilungen und Teilnehmerzahl können sich stark unterscheiden und werden individuell angepasst. Beim Ablauf werden die Formalitäten anfangs geklärt, danach erfolgt die Zuteilung der Moderatoren zu den jeweiligen Tischen. Diskussionen dauern meistens eine halbe Stunde, wobei sich die Teams (4-5 Personen) abwechseln. Zu Beginn jeder neuen Diskussionsrunde werden gesammelte Ideen aus der vorherigen Runde präsentiert. Skizzen oder Stichpunkten sind erwünscht festzuhalten. Schlussendlich werden die Ergebnisse dem gasamten Plenum vorgestellt und Lösungsoptionen erarbeitet.

# Positive Aspekte

Die Struktur vom Beitrag imponiert und ist schlüssig aufgebaut. Der Beitrag gibt einen guten Einblick in das Themengebiet und ist interessant formuliert. Besonders gut fand ich die Illustration durch die Abbildung. Links sowie Quellenverweise sind funktionstüchtig. Eine gute Anzahl an Literatur wird verwendet und viele andere kreative Methoden aufgezeigt.

# Negative Aspekte

Das Kapitel "Eignung" hängt zwischen den Teilen in der Luft. Es sollte entweder mit der Einführung zusammengeführt werden oder optional entfernt werden. Es weist große Ähnlichkeit mit den ersten Sätzen auf. Außerdem gibt es im Textteil keine Verlinkung zu angrenzenden Themengebieten. Vielleicht könnte man im Textteil dies besser miteinbinden. Im Kapitel "Vorteile" sind mir zwei kleine Fehler bei der Rechtschreibung aufgefallen.

2021-12-07 22:21 UTC, bilgesb requested changes
| Kriterium | Bewertung|
|-----|---|
| Front-Matter | ja|
| Umfang | ja|
| Belege | ja|
| Links | ja|
| Formatierung | ja|
| Verlinkungen vorhanden | ja|
| Abbildungen | ja|
| Strukturierung des Beitrags | 9 |
| Rechtschreibung | 10|
| Sprache | 10 |
| Inhalt | 10|
| Einordnung in den Kontext | 9|
| Ansprechend für Zielgruppe | 10|

# Zusammenfassung

Dieser Artikel handelt von der World Cafe Methode, die eine Alternative zu Seminaren und Konferenzen darstellt. Hierbei steht die Interaktion und die Vernetzung von Wissen im Vordergrund. Die Teilnehmer werden dazu aufgefordert ihre Gedanken, Stichpunkte etc. auf der Tischdecke niederzuschreiben.

# Positive Aspekte
Der Artikel wurde leicht verständlich und sehr gut geschrieben. Die Abbildung finde ich besonders passend, da diese an eine bemalte Tischdecke erinnert. 
Links und Verlinkungen funktionieren alle.

# Negative Aspekte
Ich würde dir raten deine Einleitung und die Eignung zusammenzuführen und diesem neuen Absatz eine geeignete Überschrift zu geben.
Bei den Vorteilen müsste "Interdisziplinär" klein geschrieben werden.
Bei der Planung fehlt einmal ein Fragezeichen.

2021-12-09 19:50 UTC, merged

2021-12-22 12:24 UTC, larissadiscua commented
Danke für eure Reviews !

@Loris18 die Idee mit dem Schaubild ist gut, jedoch wüsste ich jetzt nicht genau, wie ich dies umsetzen sollte, daher würde ich es bei der bereits vorhandenen Aufzählung belassen. Trotzdem danke für deinen Vorschlag.