ADKAR Modell
ManagingProjectsSuccessfully/ManagingProjectsSuccessfully.github.io pull request #357
Opened 2021-11-24 22:50 UTC by bilgesb

2021-12-07 17:39 UTC, qu68paka requested changes
| Kriterium | Bewertung|
|-----|---|
| Front-Matter | nein |
| Umfang | ja |
| Belege | ja |
| Links | ja |
| Formatierung | ja |
| Verlinkungen vorhanden | nein |
| Abbildungen | ja |
| Strukturierung des Beitrags | 9 |
| Rechtschreibung | 8 |
| Sprache | 10 |
| Inhalt | 10|
| Einordnung in den Kontext | 10 |
| Ansprechend für Zielgruppe | 9 |

# Zusammenfassung
Der Artikel gibt Auskunft über das ADKAR Modell von Proscigründer Jeff Hiatt, der „ein zielorientiertes Change-Management-Modell“ ist. ADKAR ist ein Akronym und steht für die Schritte zur Veränderung auf individueller und organisatorischer Ebene, nämlich „Awareness“, „Desire“, „Knowledge“, „Ability“, „Reinforcement“. Im Folgenden werden diese detailliert erklärt. Das Modell wird bei persönlichen und bei größeren Gruppierungen angewendet. Zum Ende sind die Vor- und Nachteile aufgelistet.


# Positive Aspekte

Gelungene Struktur.
Die Abbildung ist passend.
Die Links der Quellen funktionieren.




# Negative Aspekte

In Bezug zur Rechtschreibung: Im ersten Satz steht es „zielorientiertes“ statt „zielorientiertes“. Die Kommasetzung muss auch geprüft werden. 
Es gibt nur eine Verlinkung im Text.
Es fehlt eine Tabelle.

2021-12-08 00:51 UTC, Eugen0209 commented on kb/ADKAR_Model.md
> +Das ADKAR Modell von Proscigründer Jeff Hiatt „ist ein zielorientriertes [Change-Management](https://github.com/ManagingProjectsSuccessfully/ManagingProjectsSuccessfully.github.io/tree/main/kb/Change
Falsch verlinket. Da muss nach /Change_Management noch ein .md hin. Also sollte es so aussehen: [Change-Management](https://github.com/ManagingProjectsSuccessfully/ManagingProjectsSuccessfully.github.io/tree/main/kb/Change_Management.md). Bei mir komme ich jetzt an der richtigen Stelle raus ;)

2021-12-08 01:31 UTC, Eugen0209 requested changes
| Kriterium | Bewertung|
|-----|---|
| Front-Matter | ja |
| Umfang | ja |
| Belege | ja |
| Links | nein |
| Formatierung | ja |
| Verlinkungen vorhanden | ja |
| Abbildungen | ja |
| Strukturierung des Beitrags | 10 |
| Rechtschreibung | 9 |
| Sprache | 8 |
| Inhalt | 10 |
| Einordnung in den Kontext | 7 |
| Ansprechend für Zielgruppe | 9 |

# Zusammenfassung

Das ADKAR Modell ist ein Change-Management Modell. Dabei ist es ein Leitfaden für Veränderungen auf individueller und organisatorischer Ebene. Das ADKAR Modell besteht aus den fünf Stufen Bewusstsein, Wünsche, Wissen, Fähigkeiten und Verstärkung. Die Stufen sollten nicht übersprungen, sondern nacheinander und individuell durchgeführt werden. Es ist eine regelmäßige Evaluierung von Nöten. Die Anwendung erfolgt auch bei Gruppen. Am Ende gibt es Vor- und Nachteile, wobei Mitarbeiter eine wichtige Rolle spielen, aber die Komplexität nicht zu unterschätzen ist.

# Positive Aspekte

Was mir sehr gut gefällt, ist die Strukturierung und der Aufbau des Beitrags. Viele Absätze erleichtern den Lesefluss erheblich. Die Grafik ist passend gewählt. Eine Tabelle brauchst du meines Wissens nicht (in Bezug auf den anderen Reviewer). Laien wird das Wissen anschaulich und verständlich vermittelt.

# Negative Aspekte

Eine Verlinkung zu angrenzenden Themengebieten/Beiträgen ist ok, aber mehr wären wünschenswert (falls möglich). Problematik wurde schon im Kommentar von mir geschildert mit der Verlinkung "Change-Management". Man kommt nämlich nicht im Beitrag raus, sondern im Ordner. Keine weiterführende Literatur wird angegeben. Kapitel 4 ist etwas zu kurz geraten, denn 2. Sätze zu einer Hauptüberschrift sind mMn. zu wenig. Ich würde entweder den Teil mit Teil 1 zusammenführen oder etwas mehr zu den Anwendungsbereichen schreiben, damit es nicht so "leer"/"nackig" aussieht. Ich habe nochmal drübergeschaut und der Beitrag hat ca. 480 Wörter und es sollten meines Wissens mindestens 500 sein. Also 20 Wörter sind für mich nicht der Rede wert, aber ich weiß nicht wie streng bewertet wird. Das dann auch ggf. anpassen ;)

2021-12-08 21:34 UTC, kutaydogan requested changes
| Kriterium | Bewertung|
|-----|---|
| Front-Matter | ja |
| Umfang | ja|
| Belege | ja|
| Links | ja |
| Formatierung | ja|
| Verlinkungen vorhanden | nein |
| Abbildungen | ja |
| Strukturierung des Beitrags | 9 |
| Rechtschreibung | 8|
| Sprache | 8 |
| Inhalt | 9|
| Einordnung in den Kontext | 9|
| Ansprechend für Zielgruppe | 9|

# Zusammenfassung

Im Artikel wird zunächst das ADKAR-Modell definiert und erklärt und anschließend darauf hingewiesen, dass es sich um ein Akronym handelt. Diese Zusammensetzung wird dann erläutert. Zum Schluss wird die Funktion und Anwendungsbereiche dargelegt, sowie Vor- und Nachteile abgewägt.

# Positive Aspekte

-	Es wurde simpel und gut verständlich geschrieben
-	Passendes Bild
-	Die Struktur ist übersichtlich


# Negative Aspekte

-	3) und 4) könnte man zusammenfassen, um es übersichtlicher zu gestalten
-	Es fehlen Verlinkungen zu verwandten Beiträgen, die man ergänzen könnte (falls möglich)
-	Rechtschreibfehler in der ersten Zeile „zielorientriertes“

2021-12-09 19:50 UTC, merged

2021-12-20 14:21 UTC, bilgesb commented
> Kriterium	Bewertung
> Front-Matter	nein
> Umfang	ja
> Belege	ja
> Links	ja
> Formatierung	ja
> Verlinkungen vorhanden	nein
> Abbildungen	ja
> Strukturierung des Beitrags	9
> Rechtschreibung	8
> Sprache	10
> Inhalt	10
> Einordnung in den Kontext	10
> Ansprechend für Zielgruppe	9
> # Zusammenfassung
> Der Artikel gibt Auskunft über das ADKAR Modell von Proscigründer Jeff Hiatt, der „ein zielorientiertes Change-Management-Modell“ ist. ADKAR ist ein Akronym und steht für die Schritte zur Veränderung auf individueller und organisatorischer Ebene, nämlich „Awareness“, „Desire“, „Knowledge“, „Ability“, „Reinforcement“. Im Folgenden werden diese detailliert erklärt. Das Modell wird bei persönlichen und bei größeren Gruppierungen angewendet. Zum Ende sind die Vor- und Nachteile aufgelistet.
> 
> # Positive Aspekte
> Gelungene Struktur. Die Abbildung ist passend. Die Links der Quellen funktionieren.
> 
> # Negative Aspekte
> In Bezug zur Rechtschreibung: Im ersten Satz steht es „zielorientiertes“ statt „zielorientiertes“. Die Kommasetzung muss auch geprüft werden. Es gibt nur eine Verlinkung im Text. Es fehlt eine Tabelle.

Hallo Lilyana,
Vielen Dank für deine Bewertung! Ich werde die angemerkten Stellen auf jeden Fall überarbeiten. 
Ich habe jedoch noch zwei kleine Fragen zu deiner Bewertung. Du hast angemerkt, dass ich das Front-Matter nicht ausgefüllt habe. Wird dir mein Front-Matter nicht korrekt angezeigt oder soll hier noch etwas ergänzt werden? 
Du hast auch genannt, dass eine Tabelle fehlt. Weißt du, ob eine Tabelle hinzugefügt werden soll?
Vielen Dank und viele Grüße
Bilge

2021-12-20 14:28 UTC, bilgesb commented on kb/ADKAR_Model.md
> +Das ADKAR Modell von Proscigründer Jeff Hiatt „ist ein zielorientriertes [Change-Management](https://github.com/ManagingProjectsSuccessfully/ManagingProjectsSuccessfully.github.io/tree/main/kb/Change
Hallo Eugen,

Vielen Dank für deine Bewertung und die Hinweise!! :)

Viele Grüße

Bilge