Projekt_Nearshoring und Soziale_Aspekte_des_Projektmanagements
ManagingProjectsSuccessfully/ManagingProjectsSuccessfully.github.io pull request #358
Opened 2021-11-24 22:52 UTC by Eugen0209

2021-12-08 08:38 UTC, charles0209 requested changes
| Kriterium | Bewertung|
|-----|---|
| Front-Matter | ja |
| Umfang | nein |
| Belege | ja |
| Links | ja |
| Formatierung | ja |
| Verlinkungen vorhanden | ja |
| Abbildungen | ja |
| Strukturierung des Beitrags | 10 |
| Rechtschreibung | 9 |
| Sprache | 10 |
| Inhalt | 10|
| Einordnung in den Kontext | 10 |
| Ansprechend für Zielgruppe | 10 |

# Zusammenfassung

Der Artikel befasst sich mit dem Thema "Projekt Nearshoring". Zunächst wird der Begriff definiert und mit dem Gegenbegriff verdeutlicht. Anschließend werden die Ziele des Nearshorings anhand von örtlichen Gegebenheiten erläutert. Vor- und Nachteile sind zentrale Themen des Beitrags. Der Schluss wird durch eine Einschätzung des Zukunftspotenzials abgerundet.

# Positive Aspekte

* alle Links und Verlinkungen funktionieren und sind fehlerfrei
* hohes Sprachniveau
* das Thema wurde sehr verständlich erläutert
* angenehm lesbar durch gute Strukturierung und Themenübergänge

# Negative Aspekte

* Der Artikel hat einen Umfang von ca. 480 Wörtern; Die Mindestanzahl beträgt jedoch 500 Wörter
* Verlinkungen zu weiteren Themengebieten würden den Beitrag noch interessanter gestalten, wie z.b zum Thema "Projekt" oder "Projektabschluss"
* Die Idee mit der Abbildung finde ich sehr gut. Eine Kleinigkeit, die auf dem ersten Blick täuschen könnte, ist die Höhe der Balken. Optisch verdienen z.B. deutsche Projektmanager etwa das doppelte von rumänischen. Nach den Werten unterscheiden sich beide jedoch mehr als um den Faktor 4.

Rechtschreibfehler:
* Dienstleistungs-brereich -> Dienstleistungsbereich
* VAriante da -> Variante dar
* Tschchien -> Tschechien
* nachteile -> Nachteile
* Sichherheit -> Sicherheit
*  Unternehmens-einheiten -> Unternehmenseinheiten

2021-12-08 19:33 UTC, qu68paka requested changes
| Kriterium | Bewertung|
|-----|---|
| Front-Matter | ja |
| Umfang | ja |
| Belege | ja |
| Links | ja |
| Formatierung | ja |
| Verlinkungen vorhanden | ja |
| Abbildungen | ja |
| Strukturierung des Beitrags | 8 |
| Rechtschreibung | 8 |
| Sprache | 10 |
| Inhalt | 9 |
| Einordnung in den Kontext | 10 |
| Ansprechend für Zielgruppe | 10 |

# Zusammenfassung
Der Artikel informiert über das Projekt Nearshoring. Dass bedeutet, dass die betrieblichen Aktivitäten in nahegelegene Länder verlagert werden. Zuerst wird der Grund für die Delokalisierung und das Ziel des Nearshorings anhand eines Beispiels erläutert. Anschließend sind die Vor- und Nachteile detailliert beschrieben. Ein von den Vorteilen ist, dass das Nearshorings die Kommunikation und Kooperation leichter macht und verbessert. Es kann auch die Transportkosten und –zeiten senken. Andererseits erhöht sich den Kommunikationsaufwand. Auch der Konkurrenzdruck nimmt zu. Trotzdem prognostiziert der Artikel, dass die Anwendung des Projekt Nearshorings steigen wird.

# Positive Aspekte

Die Links funktionieren.
Der Wortwahl ist gut.
Die Abbildung passt zum Text.
Es gibt Verlinkungen zu angrenzenden Themen.



# Negative Aspekte

In Bezug zur Rechtschreibung: Es gibt einige kleine Schreibfehler.
Es fehlt eine Tabelle.
480 Wörter reichen wahrscheinlich, aber du kannst noch 20 schreiben.

2021-12-08 21:02 UTC, kutaydogan requested changes
# Projekt Nearshoring

| Kriterium | Bewertung|
|-----|---|
| Front-Matter | ja |
| Umfang | ja |
| Belege | ja |
| Links | ja|
| Formatierung | ja |
| Verlinkungen vorhanden | ja |
| Abbildungen | ja |
| Strukturierung des Beitrags | 10 |
| Rechtschreibung | 8|
| Sprache | 8 |
| Inhalt | 10|
| Einordnung in den Kontext | 10|
| Ansprechend für Zielgruppe | 9|

# Zusammenfassung

Im Artikel geht es um Projekt Nearshoring, das zuerst definiert und erklärt wird. Daraufhin werden die Ziele dargelegt, sowie Vor- und Nachteile abgewägt.

# Positive Aspekte

-	Sehr gut und simpel strukturiert
-	Verständlich geschrieben
-	Links sowie Verweise vollständig 

# Negative Aspekte

-	Einige Rechtschreibfehler

Ansonsten sehr schön!



# Soziale Aspekte des Sozialmanagements

| Kriterium | Bewertung|
|-----|---|
| Front-Matter | ja |
| Umfang | ja |
| Belege | ja |
| Links | ja |
| Formatierung | ja |
| Verlinkungen vorhanden | ja |
| Abbildungen | ja |
| Strukturierung des Beitrags | 8 |
| Rechtschreibung | 10|
| Sprache | 9 |
| Inhalt | 10|
| Einordnung in den Kontext | 9|
| Ansprechend für Zielgruppe | 9|

# Zusammenfassung

Im Artikel werden zunächst die Softskills erklärt und die Beteiligten in einem Projekt genannt, daraufhin wird die Relevanz der Kompetenzen des Projektleiters grafisch bewertet. Zum Schluss werden die Erfolgsfaktoren genannt und ein Fazit gezogen.

# Positive Aspekte

-	Sehr übersichtlich und simpel erklärt
-	Keine Rechtschreibfehler


# Negative Aspekte

-	Den Abschnitt „Soziale Kompetenz“ eventuell in den Text am Anfang einbringen und die letzten zwei Überschriften zusammenfassen, sodass es nochmal strukturierter aussieht.

2021-12-08 22:00 UTC, charles0209 requested changes
# Soziale Aspekte des Projektmanagements

| Kriterium | Bewertung|
|-----|---|
| Front-Matter | ja |
| Umfang | ja|
| Belege | ja |
| Links | ja |
| Formatierung | ja|
| Verlinkungen vorhanden | ja |
| Abbildungen | ja |
| Strukturierung des Beitrags | 9 |
| Rechtschreibung | 10 |
| Sprache | 9 |
| Inhalt | 10 |
| Einordnung in den Kontext | 9 |
| Ansprechend für Zielgruppe | 9 |

# Zusammenfassung

Der Beitrag behandelt die Sozialen Aspekte des Projekmanagements. Zur Einführung in das Thema wird die Bedeutung von Sozialen Aspekten innerhalb eines Projektteams erklärt. Anschließend werden die Aufgaben der fünf Projektrollen erläutert, wobei der Projektleiter eine zentrale Rolle im Team einnimmt. Zum Schluss wird auf die Soziale Kompetenz und die Erfolgsfaktoren eines Projektes eingeangen. Das Fazit verdeutlicht die Relevanz von Sozialen Aspekten und rundet den Beitrag ab.

# Positive Aspekte

* Vorgegebener Umfang von 500 Wörtern wurde sehr gut getroffen
* Der Artikel beinhaltet keine Rechtschreibfehler
* sehr übersichtliche Absätze und informativ
* Link und Verlinkungen funktionieren einwandfrei
* Die Abbildung betont nochmal die Wichtigkeit von Sozialkompetenzen

# Negative Aspekte

* Verlinkung zu weiteren angrenzenden Themengebieten wäre wünschenswert
* eine Abbildung zu den Projektrollen würden die Zusammenhänge nochmal optisch darstellen

2021-12-09 19:50 UTC, merged

2021-12-22 16:43 UTC, Eugen0209 commented
Erstmal vielen Dank für eure Bewertungen!
@charles0209 
Also beim 1. Beitrag habe ich nun die 500 Wörter erreicht, die Rechtschreibfehler ausgebessert und die Verlinkungen hinzugefügt. Bei der Grafik gebe ich dir recht, jedoch weiß ich nicht wie ich die Grafik ändern und es umsetzen könnte, da die Grafik so vorzufinden war. Außerdem gab es keine andere Grafik, die so gut gepasst hat. Deshalb würde ich es so belassen, aber danke für den Vorschlag.

Beim 2. Beitrag habe ich auch nun deutlich mehr Verlinkungen gemacht und dein Vorschlag mit dem Schaubild ist auch nicht verkehrt. Da ich jetzt auch eine Verlinkung zu den (Projekt)rollen habe und es 2 Beiträge mit den entsprechenden Schaubildern gibt (Der 2. Beitrag ist "Projektmitarbeiter"), finde ich noch eine Grafik überflüssig.

@qu68paka 
Deine Anmerkungen habe ich ausgebessert. Eine Tabelle ist nicht verpflichtend, sondern nur eine Grafik. Eine Tabelle ist optional und würde meines Erachtens keinen Mehrwert hier bieten bzw. nicht reinpassen. 

@kutaydogan 
Die Rechtschreibfehler habe ich ausgebessert und deinen 1. Vorschlag zum 2. Beitrag nicht umgesetzt, weil die "soziale Kompetenz" mMn. nach der Abbildung genauer erläutert werden soll. Aus der Grafik wird ersichtlich, dass eben die soziale Kompetenz am wichtigsten bei Projektleitern ist und das wollte ich mit einer Unterüberschrift nochmal hervorheben. 
Zum anderen Aspekt kann ich konstatieren, dass die 2. Idee zur Strukturierung sehr gut ist und ich diese umgesetzt habe. 

LG und schöne Feiertage
Eugen