Minimum_Viable_Product
ManagingProjectsSuccessfully/ManagingProjectsSuccessfully.github.io pull request #361
Opened 2021-11-24 22:59 UTC by charles0209

2021-12-07 19:41 UTC, Leon1906 requested changes
| Kriterium | Bewertung|
|-----|---|
| Front-Matter | ja |
| Umfang | ja |
| Belege | ja |
| Links | ja |
| Formatierung | ja |
| Verlinkungen vorhanden | ja |
| Abbildungen | ja |
| Strukturierung des Beitrags | 10 |
| Rechtschreibung | 10 |
| Sprache | 10 |
| Inhalt | 10 |
| Einordnung in den Kontext | 10 |
| Ansprechend für Zielgruppe | 10 |

# Zusammenfassung

Das MVP ist das Ausgangsprodukt zum Markteintritt und  für die Lösung eines aktuellen Problems entwickelt. Anhand eines Bildes wird auf verschiedene Konzepte eingegangen und so die Methodik hinter dem MVP erläutert.

Dann wird ein Bogen zum Agilen Projektmanagement geschlagen und die Bedeutsamkeit des MVP unter Anderem für Startups aufgezeigt. Vorteile wie eine Risikominimierung wird zentral herausgestellt und anschaulich erklärt.

# Positive Aspekte

Sehr informativer und perfekt geschriebener Artikel. Sprache auf hohem Niveau, die den Lesefluss ermöglicht und das Thema sehr spannend gestaltet. 

Man hat zu jeder Zeit das Gefühl, dass der Verfasser kompetent ist und in der Lage ist, das Thema für jeden verständlich zu erläutern. Dies geschieht auch anhand von Beispielen und wirklich umfangreichen Links und Quellen.


# Negative Aspekte

Nichts auszusetzen. Wirklich sehr gelungen!

2021-12-08 17:13 UTC, fadiarabo requested changes
| Kriterium | Bewertung | 
| -- | -- | 
| Front-Matter | ja | 
|Umfang | ja | 
| Belege | ja | 
| Links | ja | 
|Formatierung | ja | 
|Verlinkungen vorhanden | ja | 
|Abbildungen | ja | 
|Strukturierung des Beitrags | 10 | 
|Rechtschreibung | 9 | 
|Sprache | 10 | 
|Inhalt | 9 | 
|Einordnung in den Kontext | 10 | 
|Ansprechend für Zielgruppe | 9 | 

# Zusammenfassung 

Der Beitrag befasst sich mit dem Thema Minimum Viable Product und bildet den ersten Lösungsansatz zur Problembehebung eines Produktes. Wichtig ist es Informationen über das Produkt zu sammeln und Kundenbewertungen in die Entwicklung mit einfließen zu lassen

  

# Positive Aspekte 

  
Die Verlinkungen zu weiteren Themen in diesem Bericht sind gut gesetzt worden, sodass man von einem zum anderen Thema springen kann ohne viel zu suchen. Die Illustration wurde gut gewählt und ich finde es gut, dass du sehr stark darauf eingegangen bist


  
# Negative Aspekte 



Du benutzt oft eine Menge von Aneinanderreihungen von Nebensätzen, welche deine Sätze immer sehr lang macht. Ich würde nach ein paar Kommas einfach den Satz beenden, damit sich das besser liest.

An sich ein sehr gelungener Beitrag!

2021-12-08 18:10 UTC, hello-pukeko requested changes
| Kriterium | Bewertung|
|-----|---|
| Front-Matter | ja |
| Umfang | ja |
| Belege | ja |
| Links | ja |
| Formatierung | ja |
| Verlinkungen vorhanden | ja |
| Abbildungen | ja |
| Strukturierung des Beitrags | 10 |
| Rechtschreibung | 10 |
| Sprache | 10 |
| Inhalt | 10|
| Einordnung in den Kontext | 10 |
| Ansprechend für Zielgruppe | 10 |

# Zusammenfassung

In dem Entwicklungskonzept MVP wird für den/die Kunden/Kundin von Beginn an ein Nutzwert geschaffen. Iterativ werden Veränderungen vorgenommen bis die Stakeholder zufrieden sind.

# Positive Aspekte

Die Kurzbeschreibung zu Beginn finde ich super auf den Punkt gebracht. Da weiß man gleich, worum es geht. Auch in deiner Definition ist es super formuliert und es wird sehr schnell klar, was ein MVP ist. Deine Quellen sind sehr schön verlinkt und auch die Siehe auch-Links sind passend und hilfreich.

Ein sehr gelungener Artikel! Vielen Dank für den tollen Artikel! Ich habe was dazugelernt! 😊

# Negative Aspekte

- Im Absatz unter „Konzept des MVP“ fehlt im 3. Satz ein „e“, um aus „Element“ den Plural „Elemente“ zu machen :D
- Im gleichen Satz fehlt beim Wort „beispielsweise“ ein „e“ am Ende
- „Während“ ist eine Präposition mit Genitiv. Im 5. Satz (immer noch Absatz „Konzept des MVP“) muss es also heißen „während des Entwicklungsprozesses“
- Im Absatz unter „Startups“ brauchst du ein anderes Verb anstelle von „gelang“. Zum Beispiel „erlangte das Konzept weltweite Bekanntheit“.
- Im gleichen Satz: „Betont“ ein Konzept? Das klingt irgendwie komisch.
- Immer noch im gleichen Satz: „während des Produktentwicklungsprozesses“
- Bitte gehe nochmal deinen Text durch und gendere. (Zum Beispiel im Absatz „Konzept des MVP“ „den Nutzer“ und „der Kunde“)

2021-12-09 19:50 UTC, merged

2021-12-21 21:24 UTC, charles0209 commented
@Leon1906 
Vielen Dank für den Review.

2021-12-21 21:37 UTC, charles0209 commented
@hello-pukeko 
Danke dir für den Review und die guten Verbesserungsvorschläge. Ich habe nun fast alle Fehler korrigiert. Bei 2 Punkten kann ich jedoch nicht zustimmen. Im Absatz „Startups“ bezieht sich das Verb „betonte“ nicht auf das Konzept, sondern auf das Wort „Bedeutsamkeit“. Außerdem besteht in MPS keine Pflicht, zu gendern.

2021-12-22 18:54 UTC, hello-pukeko commented
> Hallo @hello-pukeko,
> 
> danke dir für den Review und die guten Verbesserungsvorschläge. Ich habe nun fast alle Fehler korrigiert. Bei 2 Punkten kann ich jedoch nicht zustimmen. Im Absatz „Startups“ bezieht sich das Verb „betonte“ nicht auf das Konzept, sondern auf das Wort „Bedeutsamkeit“. Außerdem besteht in MPS keine Pflicht, zu gendern.

Hallo @charles0209

Danke für deine Antwort. Dass das Verb "betonte" sich auf "Beudeutsamkeit" bezieht, habe ich verstanden. "Bedeutsamkeit" ist schließlich in deinem Satz das Objekt. Das Subjekt in deinem Satz ist jedoch "Konzept". Dort stand: "Das Konzept gelang (besser: erlangte) Bekanntheit und betonte die Bedeutsamkeit des Lernens". Und dieser zweite Teil, fand ich, klang komisch. "Das Konzept betont etwas", doch bei längerem Überlegen finde ich es nicht mehr so komisch. :smile: 

Zum Gendern:
Auf Teams gab es am 24.11.2021 um 19:02 Uhr einen Post von Ferdinand Eckl im Channel "MPS Kompendium" zum Thema Gendern. Daraus verstand ich, dass es vom Lehrstuhl gewünscht ist, dass wir unsere Artikel genderneutral formulieren. Welche Form, ob mit Sternchen, Doppelpunkt, Unterstrich etc. bleibt uns freigestellt.