Vorgehensmodelle
ManagingProjectsSuccessfully/ManagingProjectsSuccessfully.github.io pull request #362
Opened 2021-11-24 23:00 UTC by hello-pukeko

Hallo liebe Reviewer:innen,

vielen Dank, dass ihr meinen Beitrag reviewt! :) Ich bin gespannt auf euer Feedback.
Wie kommt der Beitrag bei euch an? Wird verständlich, was Vorgehensmodelle sind?
Findet ihr die Bilder passend, helfen sie beim Verständnis oder verwirren sie nur?
Ich hätte gerne noch einen kurzen Abschnitt zu "Auswahl und Anpassung eines Vorgehensmodells" eingebracht, aber es war zu lang. Vielleicht habt ihr ja Anmerkungen, wo man etwas kürzen könnte/müsste?
Ich freue mich auf eure Rückmeldungen! :)

Viele Grüße
Carolin

2021-11-29 11:33 UTC, AnnaSophieNi requested changes
| Kriterium | Bewertung|
|-----|---|
| Front-Matter | ja |
| Umfang | ja|
| Belege | ja |
| Links | ja|
| Formatierung | ja|
| Verlinkungen vorhanden | ja |
| Abbildungen | ja |
| Strukturierung des Beitrags | 10|
| Rechtschreibung | 10|
| Sprache | 8|
| Inhalt | 8|
| Einordnung in den Kontext | 9|
| Ansprechend für Zielgruppe | 9|

# Zusammenfassung

Der Beitrag umfasst das Thema Vorgehensmodelle, bei welchen es sich um zeitliche Abläufe bzw. Vorgehensweisen für die Bearbeitung eines Projekts handelt. Es wird zwischen klassischen und agilen Vorgehensmodellen unterschieden. Wobei klassische aus aufeinander abfolgenden Phasen bestehen, während agile Modelle auf iterativen und inkrementellen Vorgehen beruhen.

# Positive Aspekte

Der Artikel ist grundsätzlich sehr gut strukturiert. Die verschiedenen Grafiken helfen dabei den Inhalt besser zu veranschaulichen und werden sehr gut eingesetzt. Auch die Verlinkungen zu angrenzenden Themen werden gekonnt eingesetzt. Insgesamt ein sehr ansprechender Beitrag!

# Negative Aspekte

"Vorgehensmodelle sind dabei von Methoden zu unterscheiden. In einem Vorgehensmodell können verschiedene Methoden angewandt werden,1 die durch das Vorgehensmodell vorgegeben sein können.4 Abbildung 1 zeichnet einen Überblick über Bestandteile eines Vorgehensmodells." Bei der Begriffsdefinition hast du o.g. Satz verfasst. Ich finde diesen leider nicht sehr gelungen und kann mir nur schwierig etwas darunter vorstellen. Vielleicht könntest du die Abgrenzung zwischen Methoden und Vorgehensmodellen noch mit einem Beispiel belegen, damit der Unterschied deutlich wird.

Auch die Tabelle finde ich leider sehr schwierig nachzuvollziehen. Manche Zellen sind komplett leer und es fehlt eine Art "Erklärung/Legende". Damit meine ich "Was steht in welcher Zeile der Tabelle". Vielleicht könntest du diese nochmal ein wenig überarbeiten, damit ihr Inhalt klarer wird.

Insgesamt finde ich deinen Beitrag aber trotzdem gelungen!

2021-12-07 16:06 UTC, fadiarabo requested changes
| Kriterium | Bewertung |
| -- | -- |
|Front-Matter | ja |
|Umfang | ja |
|Belege | ja |
|Links | ja |
|Formatierung | ja |
|Verlinkungen vorhanden | ja |
|Abbildungen | ja |
|Strukturierung des Beitrags | 10 |
|Rechtschreibung | 9 |
|Sprache | 9 |
|Inhalt | 9 |
|Einordnung in den Kontext | 10 |
|Ansprechend für Zielgruppe | 9 |

# Zusammenfassung

Der Beitrag befasst sich mit dem Thema Vorgehensmodelle, zeigt ihre zeitlichen Abläufe sowohl auch unterschiedliche Arten von Vorgehensmodellen. Die Verlinkungen sind durchgehend vorhanden und die Quellen sehr wissenschaftlich. Die klassische als auch agile Variante gibt einen sehr informativen Einblick in das Thema Vorgehensmodelle

# Positive Aspekte

Die Auswahl der Quellen ist sehr präzise entschieden worden und trägt stark zur Professionalität des Berichts bei. Zudem ist ein klarer roter Faden vom Anfang bis zum Ende zu sehen, sodass man von Anfang an gut mitkommt. Verlinkungen sind ebenfalls immer vorhanden, wenn man sie benötigt.

# Negative Aspekte

Der einzige Punkt, der ein kleines Fragezeichen für mich dargestellt hat, war der Aufbau der Tabelle. Inhaltlich versteht man die Zuordnung jeder Zeile und Spalte, jedoch sind die unnötigen freien Plätze zwischen dem Inhalt nicht notwendig.

2021-12-07 19:58 UTC, Leon1906 requested changes
| Kriterium | Bewertung|
|-----|---|
| Front-Matter | ja |
| Umfang | ja |
| Belege | ja |
| Links | ja |
| Formatierung | ja |
| Verlinkungen vorhanden | ja |
| Abbildungen | ja |
| Strukturierung des Beitrags | 9 |
| Rechtschreibung | 9 |
| Sprache | 8 |
| Inhalt | 10 |
| Einordnung in den Kontext | 9 |
| Ansprechend für Zielgruppe | 10 |

# Zusammenfassung

Der Artikel befasst sich mit dem Thema Vorgehensmodelle. Es wird zwischen klassischen, agilen und hybriden Modellen unterschieden. In der Tabelle wird auf die verschiedenen Klassifizierungen von Vorgehensmodellen eingegangen, die sich je nach Literatur unterscheiden.

Zu jedem Modell werden Vor- und Nachteile aufgezeigt.


# Positive Aspekte

Sehr gut gewählte Bilder, und eine wirklich übersichtliche Tabelle. Der Artikel ist sehr informativ und lässt auf eine intensive Auseinandersetzung mit dem Thema schließen.

Das Nischen-Thema wurde sehr anschaulich und umfangreich erläutert. Sehr gute Gliederung mit den wesentlichen Punkten.



# Negative Aspekte

Sprache an manchen Stellen vielleicht zu wissenschaftlich (ist aber natürlich themenbedingt). Mein persönlicher Eindruck ist, dass der Artikel etwas zu lang ist. In diesem Fall kommt es der Qualität aber meiner Meinung nach eher zu Gute.

2021-12-09 19:50 UTC, merged

2021-12-22 18:28 UTC, hello-pukeko commented
@AnnaSophieNi Vielen Dank für dein Feedback! :)

Deine Anmerkung zu Methoden, habe ich gelöst, indem ich noch ein Beispiel eingefügt habe. Die Anmerkung fand ich sehr gut. Ich hoffe es wird mit dem Beispiel klar 😊

Die Tabelle habe ich ebenfalls geändert.

(Ursprünglich hatte ich mir mit der Zeilenaufteilung gedacht, dass ich Kategorien, die bei den unterschiedlichen Autor:innen inhaltlich ähnlich waren (auch wenn sie andere Titel hatten) gruppiere. Da Autor Timinger vier Kategorien hatte, wovon jeweils zwei zusammengefasst ähnlich zu je einer Kategorie der anderen waren, entstanden dort Leerzeilen. Und bei den Autoren Wieczorrek & Mertens gab es keine ähnliche Kategorie zu Prototyping dafür zwei weitere die gar nicht zu Kategorien der anderen Autor:innen vergleichbar waren.)

Da jede:r Autor:in eben andere Kategorien definiert, habe ich es nicht geschafft „Überschriften“ für die einzelnen Zeilen zu finden.

Im Markdown gibt es leider kaum Formatierungsmöglichkeiten von Tabellen. Sonst hätte ich die Gruppierungen gerne durch farbliche Zellen oder dickere Rahmenlinien kenntlich gemacht. Da ich auch nach viel Recherche und Kombinieren mit HTML im Markdown keine Lösung hingekriegt habe, habe ich **nun je Autor eine Liste in eine Zelle gesetzt, sodass es keine leeren Zellen mehr gibt**.

Für diese Variante fiel mir als ‚Überschrift‘ für die erste Zeile „Autor:innen“ und für die zweite Zeile „Arten von Vorgehensmodellen laut Autor*innen“ ein. Leider wurde bei einer weiteren Spalte die Tabelle so lang, dass man seitlich scrollen muss. Das fand ich der Übersichtlichkeit nicht förderlich.

Daher habe ich den Satz über der Tabelle von "Einen Überblick über mögliche Klassifizerungen liefert Tabelle 1" zu "Einen Überblick über Klassifizierungen unterschiedlicher Autor:innen liefert Tabelle 1" geändert. Damit soll klarer werden, dass je Spalte die Kategorien einer Autor:innengruppe aufgelistet sind.

Ich hoffe die Änderungen helfen beim Verständnis. Nach einigem Überlegen kam ich darauf, dass ich die Tabelle auch gänzlich streichen könnte, da der Artikel auch ohne Tabelle klar wird. Doch eine Review-Person fand die Tabelle „eine wirklich übersichtliche Tabelle“, daher wollte ich sie nicht ganz raus löschen. :D

2021-12-22 18:31 UTC, hello-pukeko commented
@fadiarabo Vielen Dank für dein Feedback!

An der Tabelle habe ich nun grundlegende Veränderungen vorgenommen. :smile:

*Zum Hintergrund:*
(Ursprünglich hatte ich mir mit der Zeilenaufteilung gedacht, dass ich Kategorien, die bei den unterschiedlichen Autor:innen inhaltlich ähnlich waren (auch wenn sie andere Titel hatten) gruppiere. Da Autor Timinger vier Kategorien hatte, wovon jeweils zwei zusammengefasst ähnlich zu je einer Kategorie der anderen waren, entstanden dort Leerzeilen. Und bei den Autoren Wieczorrek & Mertens gab es keine ähnliche Kategorie zu Prototyping dafür zwei weitere die gar nicht zu Kategorien der anderen Autor:innen vergleichbar waren.)

Im Markdown gibt es leider kaum Formatierungsmöglichkeiten von Tabellen. Sonst hätte ich die Gruppierungen gerne durch farbliche Zellen oder dickere Rahmenlinien kenntlich gemacht. Da ich auch nach viel Recherche und Kombinieren mit HTML im Markdown keine Lösung hingekriegt habe, habe ich nun je Autor eine Liste in eine Zelle gesetzt, sodass es keine leeren Zellen mehr gibt.

Für diese Variante fiel mir als ‚Überschrift‘ für die erste Zeile „Autor:innen“ und für die zweite Zeile „Arten von Vorgehensmodellen laut Autor*innen“ ein. Leider wurde bei einer weiteren Spalte die Tabelle so lang, dass man seitlich scrollen muss. Das fand ich der Übersichtlichkeit nicht förderlich.

Daher habe ich den Satz über der Tabelle von "Einen Überblick über mögliche Klassifizerungen liefert Tabelle 1" zu "Einen Überblick über Klassifizierungen unterschiedlicher Autor:innen liefert Tabelle 1" geändert. Damit soll klarer werden, dass je Spalte die Kategorien einer Autor:innengruppe aufgelistet sind.

Ich hoffe die Änderungen helfen beim Verständnis. Nach einigem Überlegen kam ich darauf, dass ich die Tabelle auch gänzlich streichen könnte, da der Artikel auch ohne Tabelle klar wird. Doch eine Review-Person fand die Tabelle „eine wirklich übersichtliche Tabelle“, daher wollte ich sie nicht ganz raus löschen. :D

2021-12-22 18:32 UTC, hello-pukeko commented
@Leon1906 Vielen Dank für dein Feedback! 😊

Da ich von den anderen beiden Reviewer:innen Feedback erhalten habe, dass die leeren Zellen in der Tabelle nicht gut seien, habe ich die Tabelle nun angepasst. Ich hoffe dir gefällt sie auch weiterhin, vielleicht ja sogar noch besser!