(1) Routineprojekte & (2) Scrum_Artefakte
ManagingProjectsSuccessfully/ManagingProjectsSuccessfully.github.io pull request #366
Opened 2021-11-25 11:01 UTC by fadiarabo

2021-11-27 11:08 UTC, Gilchus requested changes
| Kriterium | Bewertung|
|-----|---|
| Front-Matter | ja|
| Umfang | nein|
| Belege | ja|
| Links | ja|
| Formatierung | ja|
| Verlinkungen vorhanden | ja|
| Abbildungen | ja|
| Strukturierung des Beitrags | 9 |
| Rechtschreibung |8|
| Sprache | 8 |
| Inhalt | 8|
| Einordnung in den Kontext | 7|
| Ansprechend für Zielgruppe | 9|

# Zusammenfassung

Der Beitrag befasst sich mit Routine-Projekten. Der Fokus wird auf einzelne Bestandteile eines Routine Projektes gelegt, wie z.B. Reviews und Evaluierung. Außerdem wird der Unterschied zwischen Peer Reviews und Mitarbeitergesprächen erläutert.

# Positive Aspekte

Die Struktur des Beitrags ist gut gelungen. Jede Überschrift wird entweder durch kurze und präzise Textabschnitte erklärt oder durch eine Abbildung dem Leser näher gebracht. Ebenfalls wurde eine Tabelle zur Hilfe gezogen um den Unterschied zweier Bestandteile genauer zu beleuchten. Über den kompletten Beitrag hinweg wurden Verweise auf die Quellen richtig gesetzt.

# Negative Aspekte

Da der Umfang nicht komplett ausgeschöpft ist, wäre eine genauere Einbettung in den Kontext, meiner Meinung nach, gerechtfertigt (Also bei der Einleitung). Falls möglich wäre auch noch eine kurze Erläuterung zu dem Reflexionsgespräch für das Verständnis gut. 
Ansonsten sind nur kleine Rechtschreib-/Grammatikfehler unterlaufen.

2021-11-27 11:25 UTC, Gilchus requested changes
| Kriterium | Bewertung|
|-----|---|
| Front-Matter | ja |
| Umfang | ja|
| Belege | ja |
| Links | ja|
| Formatierung | ja|
| Verlinkungen vorhanden |ja |
| Abbildungen | ja |
| Strukturierung des Beitrags | 10 |
| Rechtschreibung | 9|
| Sprache | 9|
| Inhalt | 10|
| Einordnung in den Kontext | 7|
| Ansprechend für Zielgruppe | 10|

# Zusammenfassung

Der Beitrag befasst sich mit den SCRUM Artefakten und deren Umsetzung. Nach kurzer und präziser Erklärung von Product Backlog, Sprint Backlog und Produktinkrement, werden diese in den größeren Kontext von SCRUM verständlich eingebettet. 

# Positive Aspekte

Die Gliederung dieses Beitrages ist sehr gelungen. Dem Leser werden zunächst die Artefakte erläutert und anschließend anhand eines sehr geeigneten Schaubildes in SCRUM eingeordnet. Die Tabelle am Ende des Beitrages gibt nochmal einen wunderbaren abschließenden Überblick der Artefakte und der Rollenaufteilung.  

# Negative Aspekte

Um den fehlenden Bezug zum Kontext herzustellen, könntest du einfach Beiträge zu den einzelnen Artefakten (falls vorhanden) einfügen. 

Bei "Siehe auch" hast du sowohl bei dem Beitrag als auch bei deinem letzten noch den Link zu deiner eigenen Seite drin. 

Bei der Verlinkung unter deiner Tabelle hast glaube ich versehentlich ein "^" zu viel gemacht.

2021-11-29 11:56 UTC, AnnaSophieNi requested changes
| Kriterium | Bewertung|
|-----|---|
| Front-Matter | ja |
| Umfang | nein|
| Belege | nein |
| Links | nein|
| Formatierung | ja|
| Verlinkungen vorhanden | nein |
| Abbildungen | ja |
| Strukturierung des Beitrags | 5|
| Rechtschreibung | 7|
| Sprache | 6 |
| Inhalt | 4|
| Einordnung in den Kontext | 5|
| Ansprechend für Zielgruppe | 5|

# Zusammenfassung

Routine Projekte zählen zu den 4 Arten des Projektmanagements.
Review Workshops helfen dabei Fortschritt im Team zu reflektieren und dokumentieren und können einige Chancen im Vergleich zu Mitarbeitergesprächen mit sich bringen.

# Positive Aspekte

Das eingesetzte Bild veranschaulicht den Prozess der Review Workshops gut.

# Negative Aspekte

Die Sprache, die du in deinem Beitrag verwendet hast,  wirkt auf mich nicht sehr "wissenschaftlich" eher ein wenig umgangssprachlich. Du hast außerdem oft Leerzeichen vergessen oder falsche Artikel benutzt (siehe:Die Interesse des Vorgesetzten).
Auch die Quelle zu deiner Grafik, ebenso wie Verlinkungen etc. fehlen.

Insgesamt ist mir nicht klar geworden, ob dein Thema nun Routineprojekte oder Review Workshops waren. Routine Projekte werden meiner Meinung nach überhaupt nicht erklärt ("Routine-Projekte gehören zu den 4 Arten des Projektmanagements und stellen eine wichtige Art und Weise dar, sein Projekt anzugehen." Mit diesem Satz hast du deinen Beitrag begonnen -allerdings ist er ziemlich "nichtssagend". Was Routineprojekte sind wird mir dadurch nicht klar.) 
Nach dieser kurzen Einleitung sprichst du von Review Workshops ? In welchem Zusammenhang stehen diese zu deinem Thema? Warum genau wird das jetzt so ausführlich besprochen? 

Insgesamt ist mir durch deinen Artikel nicht wirklich klar geworden was das Thema ist. Ich finde alles ziemlich oberflächlich behandelt und auch die gewählte Sprache nicht so gut gelungen. Ich glaube wenn du deinen Artikel nochmal überarbeitest und ein bisschen weiter in die Tiefe gehst, kannst du noch ziemlich viel herausholen.

2021-11-30 10:51 UTC, AnnaSophieNi requested changes
Kriterium | Bewertung|
|-----|---|
| Front-Matter | ja|
| Umfang | ja|
| Belege | ja |
| Links | nein|
| Formatierung | ja|
| Verlinkungen vorhanden |nein |
| Abbildungen | ja |
| Strukturierung des Beitrags | 7|
| Rechtschreibung | 8|
| Sprache | 7|
| Inhalt | 8|
| Einordnung in den Kontext | 7|
| Ansprechend für Zielgruppe | 8|

# Zusammenfassung

Der Artikel befasst sich mit den 3 Artefakten des Scrum Prozesses: dem Product Backlog, Sprint Backlog und dem Produktinkrement.
Alle 3 Artefakten sind für ein "mit Scrum gemanagtes" Projekt notwendig und müssen Anwendung finden. Dabei ist es besonders wichtig, dass alle Mitwirkenden Zugriff haben.

# Positive Aspekte

Der Artikel ist gut strukturiert und gibt einen guten Überblick in Scrum Artefakte.
Die Überschriften geben eine klare Struktur wider, wodurch sich der Leser gut zurecht finden kann.

# Negative Aspekte
Leider fehlen Verlinkungen zu angrenzenden Themen. Vor allem zum Thema Scrum, Agiles PM,  etc. können hier gut Verlinkungen eingebettet werden.

Dein Einleitungssatz ist sehr "umgangssprachlich" geschrieben (siehe : "Es gibt im SCRUM"). Wenn du den Satz ein wenig umstellst, wird er vermutlich gleich ganz anders wirken und das Problem ist behoben.

Leider kann ich deine Tabelle nicht so ganz nachvollziehen. Hier fehlen mir wieder die Erläuterungen etc.
Auch die gewählte Abbildung zeigt meiner Meinung nach nicht die 3 Artefakte, sondern den gesamten SCRUM Prozess. (Was auch gut ist aber ich bin mir nicht sicher, ob das so gut zu deinem Beitrag passt)

Die Quellenangabe hinter deiner Tabelle (3) ist falsch angegeben, das kannst du auch noch ausbessern.

2021-12-07 20:20 UTC, Leon1906 requested changes
| Kriterium | Bewertung|
|-----|---|
| Front-Matter | ja |
| Umfang | ja |
| Belege | ja |
| Links | ja |
| Formatierung | ja |
| Verlinkungen vorhanden | ja |
| Abbildungen | ja |
| Strukturierung des Beitrags | 7 |
| Rechtschreibung | 7 |
| Sprache | 7 |
| Inhalt | 7 |
| Einordnung in den Kontext | 6 |
| Ansprechend für Zielgruppe | 7 |

# Zusammenfassung

Der Artikel beschäftigt sich mit Review-Workshops und Peer-Reviews. Diese werden eingesetzt um das Voranschreiten zu dokumentieren.

Es wird auf Fragen eingegangen, die sich während des Prozesses stellen und der Ablauf eines solchen Workshops wird skizziert.

In der Tabelle steht Kollegenfeedback/ Kritik von Vorgesetzten entgegen. 

# Positive Aspekte

Die Tabelle ist hilfreich zur Abwägung beider Optionen. Durch die erwähnten Fragen kann man sich den Ablauf gut vorstellen. Durch die einfache Sprache grundsätzlich sehr angenehm zu lesen. Rechtschreibung und Wortwahl okay. Verständlichkeit definitiv gegeben. Bild vorhanden.



# Negative Aspekte

An manchen Stellen mehr Fachsprache und weniger persönliche Wertungen. Durch den hohen Anteil an Fragen wirkt der Artikel letztendlich zu monoton und wenig ansprechend für die Zielgruppe. Der niedrige Anteil an Informationen (demgegenüber aber hoher Praxisbezug) führt zu niedriger Attraktivität den Leser.

2021-12-09 20:00 UTC, merged