Projektmanagement in Startups + Product Owner
ManagingProjectsSuccessfully/ManagingProjectsSuccessfully.github.io pull request #367
Opened 2021-11-25 13:04 UTC by Leon1906

2021-11-26 16:40 UTC, TommiMueller requested changes
| Kriterium | Bewertung|
|-----|---|
| Front-Matter | ja |
| Umfang | ja|
| Belege | nein |
| Links | ja|
| Formatierung | ja|
| Verlinkungen vorhanden | nein |
| Abbildungen | ja|
| Strukturierung des Beitrags | 8 |
| Rechtschreibung | 9|
| Sprache | 8 |
| Inhalt | 7|
| Einordnung in den Kontext | 5|
| Ansprechend für Zielgruppe | 7|

# Zusammenfassung

Ein Product Owner ist ein zentraler Part im SCRUM-Prozess.
Seine Aufgaben sind:
- Interessenvertretung der Kunden
- Leitung des Projektteams und des Scrum Masters:
- - Product Owner ist kein Part des Teams, trifft aber die Entscheidungen
- Verantwortung für den Product Backlog
- Mitverfolgung der Fortschritte
- Kreieren einer Produktvision

# Positive Aspekte

- Die Abbildungen sind gut übersichtlich und passend zum Inhalt.
- Es wurde durch Überschriften und Listen gut strukturiert.
- Der Beitrag wurde in den Kontext eingebettet
- Links funktionieren

# Negative Aspekte

- Der Text könnte durch kursive und fette Schrift bei wichtigen Punkten noch besser gestaltet werden
- Im Absatz *Arbeit mit Developer Team und Scrum Master* müsste der Satz wie folgt ausgebessert werden: **Bei dem Team von Entwicklern handelt es sich um ~~ein~~ selbstorganisierte Mitarbeiter.**
-  Der Beitrag ist zwar gut in den Kontext eingebettet. Es fehlen aber Verlinkungen zu den angrenzenden Themen. Beispielsweise könnte man einen Link zur Markdown-Datei vom **Scrum Master** einfügen.
- Der Beitrag zum Projektmanagement in Startups fehlt?? Ist das beabsichtigt?
- Die Fußnoten sollen glaube ich am Ende des Satzes stehen und nicht am Anfang.
- Bei den Abbildungen fehlen die Verlinkungen.
- Bei vielen Sätzen fehlen auch Fußnoten zu den Quellen.
- Es fehlt der Bereich unter dem Text, bei dem auf **weiterführende Literatur** verwiesen wird.
- Bei den Quellen ist nur der Link eingefügt. Es sollte noch ein Name für die Quelle eingefügt werden.

2021-11-27 12:33 UTC, Gilchus requested changes
| Kriterium | Bewertung|
|-----|---|
| Front-Matter | ja|
| Umfang | ja|
| Belege | ja|
| Links | ja|
| Formatierung | ja|
| Verlinkungen vorhanden | nein |
| Abbildungen | ja |
| Strukturierung des Beitrags | 9 |
| Rechtschreibung | 10|
| Sprache | 9 |
| Inhalt | 7|
| Einordnung in den Kontext | 9|
| Ansprechend für Zielgruppe | 10|

# Zusammenfassung

Der Product Owner ist ein wichtiger Bestandteil eines SCRUM Teams. Er ist die Schnittstelle zwischen Kunden, Entwicklerteam und Management. Der Beitrag beschreibt die konkreten Aufgaben des Product Owners und zeigt wie diese notwendig im SCRUM Prozess sind.

# Positive Aspekte

Die Struktur des Beitrages ist übersichtlich gestaltet und erleichtert durch Auflistungen mancher Aspekte das Lesen. Die gewählten Abbildungen sind einfach zu verstehen und unterstreichen das Geschriebene. 

# Negative Aspekte

Ich persönlich finde es ein wenig verwirrend die Verlinkungen zu den Quellen am Anfang eines Abschnittes zu setzen. Dadurch versteht man nicht so ganz auf was sich alles die Quelle bezieht. 

Bei "Rollen in einem Scrum Team" könntest du, falls es vom Umfang her passt, einen kurzen und knappen Satz zu Scrum Master und Entwicklungsteam schreiben oder einfach die dazugehörigen Beiträge verlinken.

2021-11-27 12:46 UTC, Gilchus requested changes
| Kriterium | Bewertung|
|-----|---|
| Front-Matter | ja |
| Umfang | ja|
| Belege | ja |
| Links | ja|
| Formatierung | ja|
| Verlinkungen vorhanden |  nein |
| Abbildungen | ja |
| Strukturierung des Beitrags | 9 |
| Rechtschreibung | 10|
| Sprache | 10 |
| Inhalt | 9 |
| Einordnung in den Kontext | 7 |
| Ansprechend für Zielgruppe | 10|

# Zusammenfassung

Der Beitrag befasst sich mit Projektmanagement in Start Up Unternehmen. Es werden sowohl der klassische als auch der agile Ansatz dargestellt und bewertet ob diese für Start Up Unternehmen geeignet sind.

# Positive Aspekte

Die Struktur des Beitrages ist sehr gelungen und ermöglicht dem Leser ein  "einfaches Lesen". Die präzise Wortwahl und gute Rechtschreibung erleichtern das verstehen der Inhalte für den Leser. Die Gestaltung der Überschriften als Frage machen den Beitrag ansprechend. 

# Negative Aspekte

Die Verlinkung der Quellen vor den Textpassagen machen es leider nicht klar ersichtlich welche Information aus welcher Quelle stammt. Zum Beispiel ist es nicht klar ob es deine persönliche Meinung ist wie gut klassisches PM für Start Ups ist oder ob diese Erkenntnisse aus der Quelle 2 hervorgehen. 

Ich finde die Einleitung über der ersten Abbildung, sowie die erste Abbildung wirklich ansprechend. Ich könnte mir jedoch vorstellen, dass es nicht die Vorgaben des Formats erfüllt. Wir sollten ja eher einen Artikel in Wikipedia-style schreiben.

2021-11-28 15:55 UTC, TommiMueller requested changes
| Kriterium | Bewertung|
|-----|---|
| Front-Matter | ja |
| Umfang | ja|
| Belege | nein |
| Links | ja|
| Formatierung | ja|
| Verlinkungen vorhanden | nein |
| Abbildungen | ja|
| Strukturierung des Beitrags | 10 |
| Rechtschreibung | 7|
| Sprache | 6 |
| Inhalt | 8|
| Einordnung in den Kontext | 5|
| Ansprechend für Zielgruppe | 7|

# Zusammenfassung

Start-Ups sind junge, neu gegründete Unternehmen. Meistens werden Projekte in Start-Ups durch agiles Projektmanagement geregelt. Besonders Design Thinking und Lean Startup sind agile Methoden, welche gerne in Start-Ups genutzt werden.

# Positive Aspekte


- Es wurde durch Überschriften und Listen gut strukturiert.
- Der Beitrag wurde in den Kontext eingebettet
- Links funktionieren
- Es wurde ein guter Überblick über das Thema gegeben

# Negative Aspekte


-  Der Beitrag ist zwar gut in den Kontext eingebettet. Es fehlen aber Verlinkungen zu den angrenzenden Themen. Beispielsweise könnte man einen Link zur Markdown-Datei von der **Lean-Methode** einfügen.
- Die Fußnoten sollen am Ende des Satzes stehen und nicht am Anfang.
- Bei der Abbildung fehlt die Verlinkung.
- Bei vielen Sätzen fehlen auch Fußnoten zu den Quellen.
- Es fehlt der Bereich unter dem Text, bei dem auf **weiterführende Literatur** verwiesen wird.
- Bei den Quellen ist nur der Link eingefügt. Es sollte noch ein Name für die Quelle eingefügt werden.
- Teilweise sind Fehler in Groß- und Kleinschreibung vorhanden.
- Es könnte noch etwas mehr im Enzyklopädie-Stil geschrieben werden (Beispielsweise im Fazit: *Abschließend lässt sich sagen* ist eher im Stil eines Aufsatzes als im Stil einer Enzyklopädie

2021-11-29 12:18 UTC, AnnaSophieNi requested changes
| Kriterium | Bewertung|
|-----|---|
| Front-Matter | ja |
| Umfang | ja|
| Belege | ja|
| Links | nein|
| Formatierung | ja|
| Verlinkungen vorhanden | nein |
| Abbildungen | ja|
| Strukturierung des Beitrags | 7 |
| Rechtschreibung | 8|
| Sprache | 8 |
| Inhalt | 8|
| Einordnung in den Kontext | 6|
| Ansprechend für Zielgruppe | 9|

# Zusammenfassung

Der Beitrag befasst sich mit der Arbeit des Product Owners im Scrum Prozess. Der Product Owner ist grundsätzlich für die Wertsteigerung des Produkts und für die Leitung des Teams verantwortlich. Die  Interessenvertretung der Kunden, Verantwortung für den Product Backlog uvm. fällt ebenfalls in seinen Zuständigkeitenbereich.

# Positive Aspekte

Ich finde der Beitrag ist gut strukturiert. Der Leser erhält einen guten und verständlichen Einblick in den Aufgabenbereich des Product Owners.

# Negative Aspekte

Leider fehlt eine Tabelle. Vielleicht hast du noch eine Idee wie du diese mit einbinden könntest.

Mir persönlich haben die vielen "Überschriften" = Aufgaben des Product Owners ein wenig in meinem Lesefluss gestört. Ich hatte ständig das Gefühl unterbrochen zu werden. Vielleicht könntest du die Überschriften-Größe anders wählen, damit man nicht das Gefühl hat, dass ständig ein neues Thema begonnen wird. Vielleicht hilft auch kursive Schrift.

Ich finde das Ende deines Beitrags recht "abrupt". Ein Schlusssatz/Fazit etc. könnten deinen Text noch gut abrunden! Auch ein der Bezug zum Bild fehlt. Vielleicht kannst du darauf noch verweisen?

Mir ist außerdem aufgefallen, dass dein Text keine Verlinkungen enthält und die Einbettung zum Kontext fehlt. Dem Leser ist z.B. vielleicht nicht bewusst was ein Product Backlog ist. Mit Hilfe einer Verlinkung zu einem anderen Beitrag kannst du dieses Problem sehr geschickt umgehen und den Leser aufklären.

2021-11-30 10:34 UTC, AnnaSophieNi requested changes
| Kriterium | Bewertung|
|-----|---|
| Front-Matter | ja |
| Umfang | ja|
| Belege | ja/ nein |
| Links | nein|
| Formatierung | ja|
| Verlinkungen vorhanden |nein |
| Abbildungen | ja |
| Strukturierung des Beitrags | 10 |
| Rechtschreibung | 8|
| Sprache | 10|
| Inhalt | 10|
| Einordnung in den Kontext | 6|
| Ansprechend für Zielgruppe |10|

# Zusammenfassung

Der Artikel befasst sich mit dem Thema Projektmanagement in Startups. Dabei wird sich zunächst mit dem klassischen und anschließend mit dem agilen Projektmanagement auseinander gesetzt. Beide Varianten können in StartUps Anwendung finden und bringen gewisse Vor- und Nachteile.
Verschiedene Methoden wie das Design Thinking, Lean Startup (Agil) werden ebenfalls erläutert.

# Positive Aspekte

Der Artikel ist sehr gut strukturiert. Angefangen mit allgemeinen Erläuterungen wird zunächst das klassische Projektmanagement in Startups und anschließend das agile beleuchtet. Das Fazit rundet den Text gut ab.
Auch die Abbildungen sind sehr gut gewählt und veranschaulichen das Geschriebene.

# Negative Aspekte
An manchen Stellen passen Groß-und Kleinschreibung nicht so ganz. Manchmal hast du auch einen einzelnen Buchstaben vergessen. 

Leider fehlen Verlinkungen in deinem Text. Mit Hilfe dessen könntest du deinen Artikel auch besser in den Kontext einbetten. (Zum Beispiel Verlinkung auf Projektleiter, Wasserfall-Methode, Scrum, etc.)

Mir ist außerdem aufgefallen, dass die Quellenangaben zu den Bildern nicht vorhanden sind.

2021-12-09 20:01 UTC, merged