Empowerment
ManagingProjectsSuccessfully/ManagingProjectsSuccessfully.github.io pull request #371
Opened 2021-12-10 08:19 UTC by TobiasZuerrlein

**Reviewer seposer:**

_„Abbildung mit Aussage einbinden, z.B. Graph, Studie etc. (kann mir vorstellen dass es schwierig ist was zu finden, würde aber die Qualität des Beitrags nochmal erhöhen.“_ – Leider finde ich tatsächlich keine passendere Abbildung. Ich habe aber Abbildung 1 in den Text eingebunden.

_„Zu viele Links im Text, die vielen blauen Links lassen den Text unruhig wirken. Vielleicht jedes Wort nur einmal verlinken.“_ – Da hast du definitiv Recht, das habe ich abgeändert. Danke für den Hinweis.

_„Leider funktionieren die Links nicht bzw. verweisen auf Beiträge die mir nur mit dem template von MPS angezeigt werden...kann auch an meinem GitHub liegen, weiß nicht!“_ – Das müsste daran gelegen haben, dass der Pull request von Martin noch nicht freigegeben war. Mittlerweile funktionieren die Links.

_„Der letzte Absatz zum Arbeitsmarkt wirkt etwas inhaltlich etwas abgekoppelt zum Text. Warum gehört der dazu?“_ –  Da gebe ich dir Recht, ich habe den Absatz entfernt und dafür den Absatz „Bedingungen für Empowerment“ etwas erweitert. Danke für den Hinweis.

Vielen Dank fürs Korrekturlesen und das ausführliche Feedback 😊

**Reviewer GiuliaAng:**

_„Sprache: "Normalerweise derjenige" im ersten Abschnitt klingt etwas umgangssprachlich. Hier besser anders formulieren.“_ – Da hast du Recht, das habe ich abgeändert. Danke für den Hinweis.

_„Struktur: Zweites Bild etwas zu groß, hindert den Lesefluss an dieser Stelle. Entweder etwas kleiner machen oder nach dem zweiten Absatz unter Definition ziehen. In dem zweiten Fall nochmal die eigentliche Definition klarer von dem zweiten Abschnitt ("Im Sinne...") mit der Überleitung zum Projektmanagement abgrenzen.“_ – Danke für den Hinweis, ich habe das Bild etwas verkleinert.

 _„Weiterführende Literatur könnte verlinkt werden z.B. zu der Springer-Website, damit man direkt sich das Buch ansehen kann“_ – Leider gibt es bei diesen Büchern keine Springer-Links und aus Professionalitätsgründen möchte ich nicht auf Online– Buchhändler verlinken.

_„Belege: Unter Reaktionsfähigkeit besser den ganzen Absatz mit 5 referenzieren und nur den einen Satz mit 2. Jeden einzelnen Satz mit einer Referenz zu versehen ist sehr viel.“_ – Nach meinem Kenntnisstand muss man jeden Satz einzeln zitieren, sofern nicht der gesamte Absatz aus der gleichen Quelle stammt. Hast du vielleicht eine Quelle, in der steht, dass man so zitieren darf, wie du es vorschlägst? Dafür wäre ich dir sehr dankbar.

Vielen Dank fürs Korrekturlesen und das ausführliche Feedback 😊

**Reviewer DaLob98:**

_„Im Absatz „Qualität von Entscheidungen“ kann man „...natürlich ebenfalls von Relevanz...“ natürlich vor ebenfalls weglassen“_ – Da hast du definitiv Recht, habe ich abgeändert. Danke für den Hinweis.

_„Die Wörter, wo nur die Hälfte des Wortes verlinkt ist, irritieren nur, entweder das ganze Wort verlinken oder die Verlinkung weglassen“_ –  Da muss ich dir auch Recht geben. Ich habe es geändert, danke für den Hinweis.

_„Im Abschnitt "Definition" eigenmächtig (falsche Aussage), besser eigenständig“_ – Das sehe ich auch so, danke.

_„Fehlendes Komma „... Kostenmanagement und Zeitmanagement, davon betroffen.““_ – Laut https://www.duden.de/rechtschreibpruefung-online wäre es ein Fehler dort ein Koma einzufügen.

Vielen Dank fürs Korrekturlesen und das ausführliche Feedback 😊

2021-12-13 08:38 UTC, MartinEnders commented
Hi, ist das schon die finale Version für die Abgabe?
Falls nicht bitte den Pull-Request schließen und vorerst im eigenen Fork arbeiten.

2021-12-15 12:10 UTC, TobiasZuerrlein commented
> Hi, ist das schon die finale Version für die Abgabe? Falls nicht bitte den Pull-Request schließen und vorerst im eigenen Fork arbeiten.

Hi Martin, ja das ist die finale Version, sofern die Reviewer damit einverstanden sind. Es gibt ein paar Ding, die ich anders als die Reviewer sehe, aber das habe ich oben ausführlich kommentiert. Habe ich das so richtig gemacht, oder hätte ich erst mit den Reviewern diese Dinge, die ich anders sehe, absprechen müssen und erst dann den PR stellen sollen?

2022-01-11 14:34 UTC, seposer requested changes
| Kriterium | Bewertung|
|-----|---|
| Front-Matter | ja |
| Umfang | ja|
| Belege | ja |
| Links | ja|
| Formatierung | ja|
| Verlinkungen vorhanden | ja |
| Abbildungen | ja |
| Strukturierung des Beitrags | 10 |
| Rechtschreibung | 10|
| Sprache | 10 |
| Inhalt | 10|
| Einordnung in den Kontext | 10|
| Ansprechend für Zielgruppe | 10|

# Zusammenfassung

Empowerment beschreibt das Konzept, das Mitglieder eines Teams selber Verantwortung und Kompetenz übernehmen. Dafür sind flache Strukturen geeignet. Wichtig ist eine offene, vertrauensvolle und respektvolle Umgangsweise im Team.

# Positive Aspekte

- sehr schöne Formulierungen und Satzbau
- sehr informativ
- gute Struktur

# Negative Aspekte

- "Empowerment ermöglicht somit Projektarbeit" --> Ist "Empowerment ist somit essentiell für funktionierende Projektarbeit" nicht besser?

2022-01-19 15:46 UTC, DaLob98 requested changes
| Kriterium | Bewertung|
|-----|---|
| Front-Matter | ja |
| Umfang | ja|
| Belege | ja |
| Links | ja|
| Formatierung | ja|
| Verlinkungen vorhanden | ja|
| Abbildungen | ja|
| Strukturierung des Beitrags | 10 |
| Rechtschreibung | 10|
| Sprache | 10 |
| Inhalt | 10|
| Einordnung in den Kontext | 10|
| Ansprechend für Zielgruppe | 10|

# Zusammenfassung

Empowerment bedeutet im Allgemeinen den Prozess und die Unterstützung der Emanzipation. Im Projektteam bedeutet Empowerment mehr Eigenverantwortung und ein Mitbestimmungsrecht der Projektmitarbeiter. Die Bedingungen für Empowerment sind dabei, hierarchische und bürokratische Blockaden zu reduzieren und das Zulassen einer offenen Fehlerkultur, dadurch wird eine optimale Projektarbeit erst ermöglicht. Die Vorteile von Empowerment sind deshalb eine höhere Mitarbeitermotivation, schnellere Reaktionszeit bei der Entscheidungsfindung und qualitativ bessere Entscheidungen für die Stakeholder zu treffen.

# Positive Aspekte

Inhaltlich wurde das Thema sehr gut und bündig zusammengefasst

Verbesserungsvorschläge wurden gut umgesetzt

Gute Unterteilung in übersichtliche Abschnitte 

Reichlich Weiterführende Literatur

# Negative Aspekte

Von meiner Seite gibt es nichts mehr anzumerken

2022-01-25 13:50 UTC, merged