Update MeisterTask_PM_Tool.md
ManagingProjectsSuccessfully/ManagingProjectsSuccessfully.github.io pull request #373
Opened 2021-12-10 16:19 UTC by nazarelsaifi

Updated MeisterTask page

2021-12-13 08:38 UTC, MartinEnders commented
Hi, ist das schon die finale Version für die Abgabe?
Falls nicht bitte den Pull-Request schließen und vorerst im eigenen Fork arbeiten.

2022-01-14 17:28 UTC, starni26 requested changes
| Kriterium | Bewertung|
|-----|---|
| Front-Matter | ja |
| Umfang | ja |
| Belege | ja |
| Links | ja |
| Formatierung | ja |
| Verlinkungen vorhanden | ja |
| Abbildungen | ja |
| Strukturierung des Beitrags | 10 |
| Rechtschreibung | 10 |
| Sprache | 10 |
| Inhalt | 10 |
| Einordnung in den Kontext | 10 |
| Ansprechend für Zielgruppe | 10 |

# Zusammenfassung

Meister Task Tool und Vergleich des Tools zu Trello

# Positive Aspekte

Ein ziemlich gut gelungener Artikel 

Wie schon im ersten Review angemerkt, eine Perfekte Fassung

# Negative Aspekte

2022-01-15 14:15 UTC, schooschef requested changes
| Kriterium | Bewertung|
|-----|---|
| Front-Matter | ja|
| Umfang | ja|
| Belege | ja|
| Links | ja|
| Formatierung | ja|
| Verlinkungen vorhanden | ja|
| Abbildungen | ja|
| Strukturierung des Beitrags | 10 |
| Rechtschreibung | 10|
| Sprache | 10 |
| Inhalt | 10|
| Einordnung in den Kontext | 10|
| Ansprechend für Zielgruppe | 10|

# Zusammenfassung

Unverändert

# Positive Aspekte

Wirklich sehr gelungen und gut zu lesen!

2022-01-18 16:27 UTC, SimonM211 requested changes
| Kriterium | Bewertung|
|-----|---|
| Front-Matter | ja |
| Umfang | ja |
| Belege | ja |
| Links | ja |
| Formatierung | ja |
| Verlinkungen vorhanden | ja |
| Abbildungen | ja |
| Strukturierung des Beitrags | 10 |
| Rechtschreibung | 10 |
| Sprache | 10 |
| Inhalt | 10 |
| Einordnung in den Kontext | 10 |
| Ansprechend für Zielgruppe | 10 |

# Zusammenfassung

Unverändert

# Positive Aspekte

Verbesserungsvorschläge wurden gut umgesetzt

2022-01-25 13:50 UTC, merged