Neuer Pull Request für 6_3_5_Methode und Retrospective
ManagingProjectsSuccessfully/ManagingProjectsSuccessfully.github.io pull request #377
Opened 2021-12-13 22:58 UTC by nta01

2021-12-28 12:56 UTC, nta01 commented
Hallo zusammen,

hier findet ihr meine beiden Themen die 6_3_5_Methode und die Retrospective. Ich habe beiden Beiträge mit dem Feedback meiner Kommiliton*innen angepasst. Wünsche waren jeweils:

**6_3_5_Methode**
- Bezug zum Projektmanagement ergänzen - umgesetzt 
- Länge des Textes anpassen - umgesetzt
- Ergänzung Erklärung der Zahlen 6,3,5 - Wurde nicht umgesetzt, da schon vorhanden. Wurde aber kursiv gemacht, damit es noch deutlicher ist.
- Passende Formatierung der Überschrift "Vorgehen" - umgesetzt
- Beschriftung der Abbildung ohne "Abbildung" davor - umgesetzt
- Nominalstil bei Vor- und Nachteilen - umgesetzt 
- Verlinkung weiterführender Literatur - umgesetzt

**Retrospective** 
-Bezug zum Projektmanagement ergänzen - umgesetzt 
- Länge des Textes anpassen - umgesetzt
- Passende Formatierung der Überschrift "Vorgehen" - umgesetzt
- Beschriftung der Abbildung ohne "Abbildung" davor - umgesetzt
- Nominalstil bei Vor- und Nachteilen - umgesetzt 
- Verlinkung weiterführender Literatur - umgesetzt

LG, Nathalie

2022-01-13 10:34 UTC, Maximilian219 reviewed
# 6-3-5- Methode

| Kriterium | Bewertung|
|-----|---|
| Front-Matter | ja|
| Umfang | ja|
| Belege | ja |
| Links | ja|
| Formatierung | ja|
| Verlinkungen vorhanden | ja|
| Abbildungen | ja |
| Strukturierung des Beitrags | 10 |
| Rechtschreibung | 10|
| Sprache | 9 |
| Inhalt | 10|
| Einordnung in den Kontext | 9|
| Ansprechend für Zielgruppe | 10|

## Zusammenfassung

Die 6-3-5-Methode ist eine Brainwriting-Kreativitätstechnik, bei der jede der sechs Personen im Team jeweils drei Themen auf jeweils einem Zettel notiert und diese dann an jede Person im Team (also ingesamt fünf Mal) weiterreicht. So können in kurzer Zeit bis zu 108 Ideen gesammelt werden 
Der Vorgang besteht aus einer Einführung, 5. Runden in denen der Zettel eines Teammitglieds gelesen und ergänzt wird, sowie einer Bewertung und Verarbeitung nach der Themensammlung.


## Positive Aspekte

* Anmerkungen wurden angenommen und ergänzt
* Artikel ließt sich flüssig und verständlich 
* Positive Aspekte aus erstem Review: 
	* Belege sind vorhanden und gut eingesetzt worden
	* Alle Links funktionieren
	* Die Überschriften sind gut gewählt, womit die Struktur klar und logisch erkennbar wird
	* Der Artikel erklärt die 6-3-5 Methode sachlich und verständlich und motiviert dazu es selbst auszuprobieren

	

## Negative Aspekte

Keine nennenswerten negativen Aspekten mehr vorhanden


# Retrospective

| Kriterium | Bewertung|
|-----|---|
| Front-Matter | ja|
| Umfang | ja|
| Belege | ja |
| Links | ja|
| Formatierung | ja|
| Verlinkungen vorhanden | ja|
| Abbildungen | ja |
| Strukturierung des Beitrags | 10 |
| Rechtschreibung | 10|
| Sprache | 9 |
| Inhalt | 10|
| Einordnung in den Kontext | 9|
| Ansprechend für Zielgruppe | 10|

## Zusammenfassung

Eine Retrospective ist ein repetitiver Vorgang bei der Anwendung von agilen Projektmanagementmethoden. Innerhalb der Retrospective wird kritisch bewertet, wie der vorangegangene Sprint verlaufen ist, indem Feedback aller Teammitglieder eingeholt wird.
Dies dient zur Optimierung und Entwicklung von Arbeitsabläufen und Zusammenarbeit.
Es existieren viele Ansätze zur Gestaltung eines Sprints. Im Artikel werden folgende Beispiele beschrieben: 

* Simples Analoges Vorgehen
* Nutzen von digitalen Vorlagen
* Einsatz von Spielen 

Ziel ist es, eine Agenda mit Themen zu erstellen, welche im darauffolgenden Sprint verbessert, abgeschafft oder beibehalten werden sollen 

## Positive Aspekte

* Verbesserungsvorschläge wurden gut umgesetzt
* Positive Aspekte aus erstem Review:
	* Fremdwörter werden mithilfe von Hyperlinks erklärt
	* Alle Links funktionieren
	* Die Strukturierung ist logisch und vorteilhaft gewählt
	* Keine Rechtschreibfehler
	* Es wurde eine sachliche und verständliche Sprache verwendet 
	* Der Artikel verschafft einen sehr guten Überblick über das Thema 


## Negative Aspekte

Keine nennenswerten negativen Aspekten mehr vorhanden
 

2022-01-13 13:00 UTC, lucas100700 reviewed
# *6_3_5 Methode*

| Kriterium | Bewertung|
|-----|---|
| Front-Matter | ja |
| Umfang | ja|
| Belege | ja |
| Links | ja|
| Formatierung | ja|
| Verlinkungen vorhanden | ja |
| Abbildungen | ja|
| Strukturierung des Beitrags | 9|
| Rechtschreibung | 10|
| Sprache | 10 |
| Inhalt | 10|
| Einordnung in den Kontext | 10|
| Ansprechend für Zielgruppe | 10|

# Zusammenfassung
Der Artikel stellt die 6_3_5 Methode vor. Dabei handelt es sich um eine Brainwriting-Kreativitätstechnik. Es wird der Ablauf und die Vor- und Nachteile dieser Methode beschrieben. Der Ablauf ist in einer übersichtlichen Tabelle dargestellt. 
Neben weiteren wissenswerten Informationen wird am Schluss noch auf weiterführende Literatur und weitere Kompendiums Einträge verwiesen. 

# Positive Aspekte
* Einordnung in den Kontext Projektmanagement 
* Formatierung der Punkte Vorgehen und Ablauf wurde angepasst
* Redundante Inforamtionen wurden entfernt
* Die weiterführende Literatur ist mit Links versehen worden

# Negative Aspekte

* Alle Punkte wurden berücksichtigt 

# *Retroperspektive* 

| Kriterium | Bewertung|
|-----|---|
| Front-Matter | ja|
| Umfang | ja|
| Belege | ja |
| Links | ja|
| Formatierung | ja|
| Verlinkungen vorhanden | ja|
| Abbildungen | ja |
| Strukturierung des Beitrags | 8 |
| Rechtschreibung |10|
| Sprache | 10|
| Inhalt | 9|
| Einordnung in den Kontext | 10|
| Ansprechend für Zielgruppe | 10|

# Zusammenfassung

Der Artikel befasst sich mit der Retroperspektive als Element des agilen Projektmanagements. Zu Beginn wird erläutert, dass die Retroperspektive nach den sich wiederholenden Iterationen im Scrum-Verfahren Anwendung findet. Im Anschluss werden verschiedene Herangehensweisen dargestellt: Simples analoges Vorgehen, Nutzen von digitalen Vorlagen (Miro, etc.) oder der Einsatz von Spielen. 
Zum Abschluss werden noch die Vor- bzw. die Nachteile der Retroperspektive dargestellt. 
# Positive Aspekte

* Der Umfang wurde angepasst und erfüllt jetzt die Anforderungen 
* Verlinkung der weiterführenden Literatur wurde umgesetzt

# Negative Aspekte

* Leider immer noch keine Verlinkungen von anderen Kompendiumsbeiträgen im Text z.B. "Sprint"
* Sonst keine Verbesserungen mehr :D

2022-01-18 10:53 UTC, MoritzBock requested changes
# 6_3_5_Methode

| Kriterium | Bewertung|
|-----|---|
| Front-Matter | ja|
| Umfang | ja|
| Belege | ja|
| Links | ja|
| Formatierung | ja|
| Verlinkungen vorhanden | ja|
| Abbildungen | ja|
| Strukturierung des Beitrags | 10 |
| Rechtschreibung | 10|
| Sprache | 10 |
| Inhalt | 10|
| Einordnung in den Kontext | 10|
| Ansprechend für Zielgruppe | 10|

# Zusammenfassung

Die 6_3_5-Methode ist eine Kreativtechnik zur Ideenfindung und -sammlung. Hierbei werden kleine Gruppen gebildet, wobei jeder auf einen Zettel Ideen aufschreibt. Im Anschluss werden die Zettel weitergegeben und von der nächsten Person bearbeitet, indem neue Ideen angefügt oder an vorhandene Ideen angeknüpft wird. Somit können innerhalb kürzester Zeit sehr viele neue Ideen generiert werden.

# Positive Aspekte

Alle im ersten Review genannten positiven Aspekte. Zusätzlich wurden die vorgeschlagenen Verbesserungen insgesamt sehr gut umgesetzt.

# Negative Aspekte

Keine besonderen negativen Aspekte mehr auffällig.


# Retrospective

| Kriterium | Bewertung|
|-----|---|
| Front-Matter | ja|
| Umfang | ja|
| Belege | ja|
| Links | ja|
| Formatierung | ja|
| Verlinkungen vorhanden | ja|
| Abbildungen | ja|
| Strukturierung des Beitrags | 10 |
| Rechtschreibung | 10|
| Sprache | 10 |
| Inhalt | 10|
| Einordnung in den Kontext | 10|
| Ansprechend für Zielgruppe | 10|

# Zusammenfassung

Retroperspective beschreibt einen sich wiederholenden Vorgang, in welchem kritisch bewertet wird, was seit dem vorherigen Sprint gut und schlecht gelaufen ist und wo es Verbesserungspotential gibt. Ebenso ist es das Ziel eine Liste zu erstellen in welcher festgehalten wird, was für zukünftige Sprints verbessert, abgeschafft oder behalten werden sollen.

# Positive Aspekte

Alle im ersten Review genannten positiven Aspekte. Zusätzlich wurden die vorgeschlagenen Verbesserungen insgesamt sehr gut umgesetzt.

# Negative Aspekte

Keine besonderen negativen Aspekte mehr auffällig.

2022-01-25 13:51 UTC, merged