Projektmanagement_4_0
ManagingProjectsSuccessfully/ManagingProjectsSuccessfully.github.io pull request #382
Opened 2021-12-15 11:18 UTC by wernerni

2022-01-14 17:25 UTC, MarcelFAU commented
| Kriterium | Bewertung|
|-----|---|
| Front-Matter | ja |
| Umfang | ja |
| Belege | ja |
| Links | ja|
| Formatierung | ja|
| Verlinkungen vorhanden | ja |
| Abbildungen | ja|
| Strukturierung des Beitrags | 10 |
| Rechtschreibung | 10|
| Sprache | 10 |
| Inhalt | 10|
| Einordnung in den Kontext | 10|
| Ansprechend für Zielgruppe | 10|

# Zusammenfassung

siehe erste Review

# Positive Aspekte

Alles ;)

# Negative Aspekte

/

2022-01-16 10:26 UTC, nahihiry requested changes
| Kriterium | Bewertung|
|-----|---|
| Front-Matter | ja |
| Umfang | ja|
| Belege | ja |
| Links | ja|
| Formatierung | ja|
| Verlinkungen vorhanden | ja |
| Abbildungen | ja |
| Strukturierung des Beitrags | 10 |
| Rechtschreibung | 10|
| Sprache | 10 |
| Inhalt | 10|
| Einordnung in den Kontext | 10|
| Ansprechend für Zielgruppe | 10|

# Zusammenfassung

Siehe erste Review

# Positive Aspekte
Immer noch ein wirklich toller Beitrag! 

# Negative Aspekte
Keine.

2022-01-16 22:00 UTC, Miki2701 requested changes
| Kriterium | Bewertung|
|-----|---|
| Front-Matter | ja |
| Umfang | ja |
| Belege | ja |
| Links | ja|
| Formatierung | ja |
| Verlinkungen vorhanden | ja |
| Abbildungen | ja |
| Strukturierung des Beitrags | 10 |
| Rechtschreibung | 10|
| Sprache | 10 |
| Inhalt | 10|
| Einordnung in den Kontext | 10|
| Ansprechend für Zielgruppe | 10|

# Zusammenfassung

Siehe 1. Review

# Positive Aspekte

Nach wie vor ein sehr gelungener Artikel:)

# Negative Aspekte

Hab nichts negatives anzumerken.

2022-01-19 16:02 UTC, MarcelFAU requested changes
| Kriterium | Bewertung|
|-----|---|
| Front-Matter | ja |
| Umfang | ja |
| Belege | ja |
| Links | ja|
| Formatierung | ja|
| Verlinkungen vorhanden | ja |
| Abbildungen | ja|
| Strukturierung des Beitrags | 10 |
| Rechtschreibung | 10|
| Sprache | 10 |
| Inhalt | 10|
| Einordnung in den Kontext | 10|
| Ansprechend für Zielgruppe | 10|

# Zusammenfassung

siehe erste Review

# Positive Aspekte

Alles ;)

# Negative Aspekte

/

2022-01-25 13:51 UTC, merged