(1)Who_is_Who_Projektmanagement/ (2) Resource Leveling (16.12.2021)
ManagingProjectsSuccessfully/ManagingProjectsSuccessfully.github.io pull request #385
Opened 2021-12-16 14:42 UTC by Ne88peni

2021-12-22 20:25 UTC, Ne88peni commented
https://github.com/ManagingProjectsSuccessfully/ManagingProjectsSuccessfully.github.io/pull/238#pullrequestreview-825651061

@christian-anghel @mirela08 @Teemoma 

Hallo zusammen,

vielen Dank für eure Reviews. 
In diesem Kommentar möchte ich euch einen kurzen Überblick über die Hauptveränderungen an meinen Beiträgen geben.

Beim Beitrag zu Resource Leveling habe ich folgende Änderungen gemacht:

* Es wurden im Beitrag weitere Github Beiträge verlinkt.
* Die Zahl der Wörter im Beitrag wurde verringert.

Beim Beitrag zu Who_is_Who_Projektmanagement:

* Eine Abbildung wurde hinzugefügt.
* Die Zahl der Wörter wurde reduziert.
* Es wurden im Beitrag weitere Github Beiträge verlinkt.
* Irrelevante Inhalte wurden entfernt.

2022-01-16 21:26 UTC, mirela08 requested changes
| Kriterium | Bewertung|
|-----|---|
| Front-Matter | ja |
| Umfang | ja |
| Belege | ja |
| Links | ja |
| Formatierung | ja |
| Verlinkungen vorhanden | ja |
| Abbildungen | ja |
| Strukturierung des Beitrags | 10 |
| Rechtschreibung | 10|
| Sprache | 10 |
| Inhalt | 10|
| Einordnung in den Kontext | 10|
| Ansprechend für Zielgruppe | 10|

Beide Beiträge sind jetzt einwandfrei. Alle Verbesserungsvorschläge wurden berücksichtigt.

2022-01-18 17:06 UTC, christian-anghel requested changes
| Kriterium | Bewertung|
|-----|---|
| Front-Matter | ja |
| Umfang | ja |
| Belege | ja |
| Links | ja |
| Formatierung | ja |
| Verlinkungen vorhanden | ja |
| Abbildungen | ja |
| Strukturierung des Beitrags | 10 |
| Rechtschreibung | 10 |
| Sprache | 10 |
| Inhalt | 10|
| Einordnung in den Kontext | 10 |
| Ansprechend für Zielgruppe | 10 |
# Zusammenfassung
Ein Artikel geht um Resource Leveling, die Ziele davon und verschiedene Techniken.
Der andere Artikel geht um die verschiedenen Rollen und Beteiligten im Projektmanagement.
# Positive Aspekte
Durch das Kürzen der Artikel fällt das Lesen einfacher und alles wirkt mehr auf den Punkt gebracht. Die Abbildung bei Who_is_Who_Projektmangement ist gut gewählt. Die Verlinkungen geben beim lesen eine gute Einordnung zu nahe liegenden Themen.
# Negative Aspekte
Es wurden alle negativen Aspekte verbessert.

2022-01-19 21:34 UTC, Teemoma requested changes
| Kriterium | Bewertung|
|-----|---|
| Front-Matter | ja |
| Umfang | ja|
| Belege | ja |
| Links | ja|
| Formatierung | ja|
| Verlinkungen vorhanden | ja |
| Abbildungen | ja |
| Strukturierung des Beitrags | 10 |
| Rechtschreibung |10|
| Sprache | 10 |
| Inhalt | 10|
| Einordnung in den Kontext |10|
| Ansprechend für Zielgruppe |10|

# Zusammenfassung
Gut gemacht, keine negative Aspekte.

2022-01-25 13:51 UTC, merged