Herausforderungen_bei_internationalen_Projekten.md
ManagingProjectsSuccessfully/ManagingProjectsSuccessfully.github.io pull request #386
Opened 2021-12-17 11:25 UTC by tcansel

2021-12-22 18:21 UTC, tcansel commented
Ich habe den Beitrag wie empfohlen auf Rechtschreibung, Grammatik und Kommafehler geprüft. Die vorhandenen Doppelpunkte im Text habe ich entfernt. Außerdem habe ich eine Erklärung zur Abbildung geschrieben.

2022-01-16 15:27 UTC, xyily requested changes
| Kriterium | Bewertung|
|-----|---|
| Front-Matter | ja|
| Umfang | ja|
| Belege | ja |
| Links | ja|
| Formatierung | ja|
| Verlinkungen vorhanden | ja|
| Abbildungen | ja|
| Strukturierung des Beitrags | 10 |
| Rechtschreibung | 10|
| Sprache | 10 |
| Inhalt | 10|
| Einordnung in den Kontext | 10|
| Ansprechend für Zielgruppe | 10|

# Zusammenfassung

Im Artikel werden die Herausforderungen bei internationalen Projekten beschrieben.

# Positive Aspekte
- Der Artikel war bereits bei Review 1 sehr gut und Verbesserungsvorschläge wurden umgesetzt, zb wurde die Abbildung erklärt.
- Umfang passt, Inhalt ist ansprechend und interessant, vorhandene Verlinkungen funktionieren, Struktur des Beitrags ist ansprechend gestaltet, Rechtschreibfehler wurden ausgebessert

# Negative Aspekte

keine

2022-01-17 23:19 UTC, YeldaUzun requested changes
| Kriterium | Bewertung|
|-----|---|
| Front-Matter | ja |
| Umfang | ja |
| Belege | ja |
| Links | ja |
| Formatierung | ja |
| Verlinkungen vorhanden | ja |
| Abbildungen | ja |
| Strukturierung des Beitrags | 10 |
| Rechtschreibung | 9 |
| Sprache | 10 |
| Inhalt | 10 |
| Einordnung in den Kontext | 10|
| Ansprechend für Zielgruppe | 10|

# Zusammenfassung
Der Artikel befasst sich mit Herausforderungen die bei internationalen Projekten aufkommen. Es werden einige Herausforderungen erläutert und ein Fazit gezogen. 

# Positive Aspekte
- Belege und Verlinkungen zu anderen Themen vorhanden. 
- Links und Verlinkungen funktionieren. 
- Umfang wurde eingehalten. 
- Abbildung vorhanden, wurde erläutert und lässt sich öffnen. 
- Verbesserungsvorschläge wurden umgesetzt.  
- Interessanter Artikel der einen guten Überblick über die Herausforderungen bei internationalen Projekten schafft. 

# Negative Aspekte

- Der Artikel weist einige Kommafehler auf.

2022-01-22 17:22 UTC, fe94fiqy requested changes
| Kriterium | Bewertung|
|-----|---|
| Front-Matter | ja |
| Umfang | ja|
| Belege | ja|
| Links | ja|
| Formatierung | ja|
| Verlinkungen vorhanden | ja |
| Abbildungen | ja |
| Strukturierung des Beitrags | 10 |
| Rechtschreibung | 10|
| Sprache | 10 |
| Inhalt | 10|
| Einordnung in den Kontext | 10|
| Ansprechend für Zielgruppe | 10|

# Zusammenfassung

Der Artikel befasst  sich mit den Herausforderungen von Internationalen Projekten .

# Positive Aspekte

Sehr strukturiert dargestellt .Verlinkungen ,Links funktionieren .Umfang eingehalten .

# Negative Aspekte

Keine Verbesserungsvorschläge .

2022-01-25 13:51 UTC, merged