Best_Practices final
ManagingProjectsSuccessfully/ManagingProjectsSuccessfully.github.io pull request #389
Opened 2021-12-18 09:27 UTC by tobi0211

2021-12-21 19:35 UTC, tobi0211 commented
Vielen Dank für euer Feedback, folgende Änderungen wurden von mir vorgenommen:
- Neuformulierung Kurzbeschreibung von Best Practices
- Angabe "Siehe auch" und "Weiterführende Literatur"
- Fehlerbehebung Verlinkungen
- Bei "Quellen": Verlinkung zeigt nun Überschrift d. Quelle statt nur den Link
- Korrektur von Rechtschreib- & Grammatikfehlern sowie Formalitäten

2022-01-14 09:22 UTC, jnsdhr requested changes
| Kriterium | Bewertung|
|-----|---|
| Front-Matter | ja |
| Umfang | ja|
| Belege | ja|
| Links | ja|
| Formatierung | ja|
| Verlinkungen vorhanden | ja|
| Abbildungen | ja |
| Strukturierung des Beitrags |10 |
| Rechtschreibung |10|
| Sprache | 9 |
| Inhalt | 10|
| Einordnung in den Kontext | 10|
| Ansprechend für Zielgruppe | 10|

# Zusammenfassung

Der Artikel behandelt allgemeine Handlungsempfehlungen, die sich in der Praxis als sinnvoll gezeigt haben und empirisch analysiert wurden.

# Positive Aspekte

Der Text ist sehr übersichtlich und strukturiert, sodass der Leser den Inhalt leicht verinnerlichen kann. Dazu trägt auch die gut gewählte Graphik bei.  Auch positiv anzumerken ist, dass alle Kritikpunkte umgesetzt wurde,

# Negative Aspekte
Bei der Formulierung "sowohl als auch" ist kein Komma notwendig.

2022-01-15 13:43 UTC, Irishcoffee09 requested changes
| Kriterium | Bewertung|
|-----|---|
| Front-Matter | ja |
| Umfang | ja |
| Belege | ja |
| Links | ja |
| Formatierung | ja |
| Verlinkungen vorhanden | ja |
| Abbildungen | ja |
| Strukturierung des Beitrags |10|
| Rechtschreibung |10|
| Sprache |10|
| Inhalt |10|
| Einordnung in den Kontext |10|
| Ansprechend für Zielgruppe |10|

# Zusammenfassung

Der Artikel behandelt die Best Practices, die ein Vergessen von wichtigen Punkten in der Projektplanung verhindern sollen. Es werden sechs bewährte Vorgehensweisen genauer erläutert.

# Positive Aspekte

Positiv hervorzuheben ist die Struktur und der Aufbau des Beitrags. Die Einleitung stellt kurz das Problem einer detaillierten Projektplanung dar und somit die Notwendigkeit von Best Practices. Im Folgenden wird auf jede Methode ausführlich eingegangen. Auch die Auswahl dieser bestimmten sechs Methoden ist gut getroffen. Der Artikel ist verständlich geschrieben und weckt das Interesse an dem Thema.
Durch eine Abbildung werden Projektphasen und Arbeitspakete in einem Zeitplan visualisiert. Die Illustration ist sinnvoll im Kontext eingebettet und wird zusätzlich noch sehr gut erläutert.
Verlinkungen im Fließtext funktionieren und sind gut gewählt. Die verwendeten Quellen sind ausreichend und es liegen keine Rechtschreibfehler und Grammatikfehler vor.

Es wurde auf alle Kritikpunkte des ersten Reviews eingegangen. Es liegt jetzt eine sehr gut formulierte Einleitung (mit gefordertem Kurzzusammenfassungs-Charakter) vor und ebenso findet man nun sinnvolle, weiterführende Literatur am Ende des Artikels.

# Negative Aspekte

Es sind keine negativen Aspekte mehr ersichtlich. TOP Artikel!

2022-01-15 15:15 UTC, BelmontR requested changes
| Kriterium | Bewertung|
|-----|---|
| Front-Matter | ja|
| Umfang | ja|
| Belege | ja|
| Links | ja|
| Formatierung | ja|
| Verlinkungen vorhanden | ja|
| Abbildungen | ja|
| Strukturierung des Beitrags | 10 |
| Rechtschreibung | 9|
| Sprache | 10 |
| Inhalt | 10|
| Einordnung in den Kontext | 10|
| Ansprechend für Zielgruppe | 10|

# Zusammenfassung

Der Artikel zählt sechs "Best Practices" auf und führt sie aus.

# Positive Aspekte

Die Kurzbeschreibung am Anfang wurde sehr gut überarbeitet und ist nun auch wirklich eine Kurzbeschreibung und keine Einleitung mehr. Sprache und Rechtschreibung sind makellos, die sprachlichen Überarbeitungen sind sehr gut gelungen. Die Struktur ist weiterhin übersichtlich.

# Negative Aspekte

Die Quellenangaben sind weiterhin nach dem Punkt, obwohl sie vor dem Punkt sein müssten.

2022-01-25 13:51 UTC, merged