Top_Down_Planning
ManagingProjectsSuccessfully/ManagingProjectsSuccessfully.github.io pull request #390
Opened 2021-12-18 09:49 UTC by laradag

2022-01-13 15:14 UTC, LaHe27 requested changes
| Kriterium | Bewertung|
|-----|---|
| Front-Matter | ja | 
| Umfang | ja | 
| Belege | ja | 
| Links | ja | 
| Formatierung | ja | 
| Verlinkungen vorhanden | ja | 
| Abbildungen | ja | 
| Strukturierung des Beitrags | 10 | 
| Rechtschreibung | 10 | 
| Sprache | 10 | 
| Inhalt | 10| 
| Einordnung in den Kontext | 10| 
| Ansprechend für Zielgruppe | 10| 

# Zusammenfassung

Der Artikel befasst sich mit dem Top-Down Planning, welches das Gegenteil des Bottom-up Plannings darstellt. Im Artikel wird zu erst auf das Konzept des Top-Down Plannings eingegangen und danach Vor- sowie Nachteile erläutert und in einer Tabelle verschiedene Anwendungsbereich anhand von Beispielen erklärt.

2022-01-18 17:42 UTC, Harthauer reviewed
| Kriterium | Bewertung|
|-----|---|
| Front-Matter |ja|
| Umfang | ja|
| Belege | ja|
| Links | ja|
| Formatierung | ja|
| Verlinkungen vorhanden | ja|
| Abbildungen | ja |
| Strukturierung des Beitrags | 10 |
| Rechtschreibung |10|
| Sprache |10 |
| Inhalt |10|
| Einordnung in den Kontext |10|
| Ansprechend für Zielgruppe |10|

# Zusammenfassung

Der Artikel befasst sich mit Top-Down Planning. Im Beitrag wird zu erst das Konzept des Top-Down Plannings erläutert und dann Vor- und Nachteile davon aufgezählt. Im letzten Abschnitt wird die Anwendung von Top-Down Planning tabellarisch aufgezeigt.

# Positive Aspekte
Das Thema wird vor allem durch die Gliederung am Anfang klar strukturiert und  der Schreibstil ist auch sachlich. Durch die Abstände zwischen den Absätzen lässt sich der Artikel sehr angenehm lesen genauso wie durch die Stichpunkte bei der kritischen Auseinandersetzung mit Top-Down Planning und der Tabelle bei der Anwendung.

# Negative Aspekte

Soweit ich weiß muss man ein ''Siehe auch'' an angrenzenden GitHub Beiträgen von anderen Kommilitonen unten anfügen, ''Weiterführende Literatur'' sollte unten auch angeführt werden. Bei ''Weiterführende Literatur'' könntest du Themenverwandte Artikel nehmen die es nicht in den endgültigen Artikel geschafft haben.
Und vielleicht findest du noch eine Abbildung mit bisschen mehr Text und Aussagekraft. Ansonsten ist es ein gelungener Artikel in welchem unsere Review Vorschläge umgesetzt wurden.

2022-01-18 21:28 UTC, xe28dita commented
| Kriterium | Bewertung|
|-----|---|
| Front-Matter | ja|
| Umfang | ja|
| Belege | ja|
| Links | ja|
| Formatierung | ja|
| Verlinkungen vorhanden | ja|
| Abbildungen | ja|
| Strukturierung des Beitrags |10 |
| Rechtschreibung |10|
| Sprache | 10|
| Inhalt | 10|
| Einordnung in den Kontext |10|
| Ansprechend für Zielgruppe |10|

# Zusammenfassung

Zunächst wird das Konzept erklärt und anschließend die Vor- und Nachteile.

# Positive Aspekte

Du hast meinen Verbesserungsvorschlag für die Vor- und Nachteile beachtet. Der Beitrag lässt sich nun noch besser lesen als vorher. Im Gesamten ein sehr guter Beitrag.

# Negative Aspekte

Nichts zu meckern :)

2022-01-22 20:57 UTC, xe28dita reviewed
| Kriterium | Bewertung|
|-----|---|
| Front-Matter | ja|
| Umfang | ja|
| Belege | ja|
| Links | ja|
| Formatierung | ja|
| Verlinkungen vorhanden | ja|
| Abbildungen | ja|
| Strukturierung des Beitrags |10 |
| Rechtschreibung |10|
| Sprache | 10|
| Inhalt | 10|
| Einordnung in den Kontext |10|
| Ansprechend für Zielgruppe |10|

# Zusammenfassung

Zunächst wird das Konzept erklärt und anschließend die Vor- und Nachteile.

# Positive Aspekte

Du hast meinen Verbesserungsvorschlag für die Vor- und Nachteile beachtet. Der Beitrag lässt sich nun noch besser lesen als vorher. Im Gesamten ein sehr guter Beitrag.

# Negative Aspekte

Nichts zu meckern :)

2022-01-25 13:51 UTC, merged