Hive_PM_Tool & Stand_Ups
ManagingProjectsSuccessfully/ManagingProjectsSuccessfully.github.io pull request #394
Opened 2021-12-18 11:41 UTC by Gilchus

2022-01-16 10:02 UTC, TommiMueller requested changes
| Kriterium | Bewertung|
|-----|---|
| Front-Matter | ja |
| Umfang | ja|
| Belege | nein |
| Links | nein|
| Formatierung | ja|
| Verlinkungen vorhanden | nein |
| Abbildungen | ja |
| Strukturierung des Beitrags | 6 |
| Rechtschreibung | 9|
| Sprache | 9 |
| Inhalt | 10|
| Einordnung in den Kontext | 4|
| Ansprechend für Zielgruppe | 7|

# Zusammenfassung

Das Hive PM Tool lässt Projekte zentralisiert und Cloud basiert mittels einer Software verwalten. Auf dem **Dashboard** kann der Nutzer seine Aktivitäten einsehen. Hive lässt sich mit vielen Drittanbieter Softwares verbinden (Beispielsweise der Mail-Adresse).  Es ist ein übersichtliches Tool, welches sich benutzerspezifisch einstellen lässt. 
Es ist in unterschiedlichen Preiskategorien erhältlich.

# Positive Aspekte

- Ausführlich und verständlich erklärt.
- Im Wikipedia-Stil geschrieben
- Tabelle eingefügt
-  Die Abbildungen lassen sich mittlerweile erkennen


# Negative Aspekte

- Bei Quellen wurde nur Link eingefügt und kein Name
- Links zu **Gantt** und **Kanban** verlinken auf leere Einträge
- Groß- und Kleinschreibung, sowie Zeichensetzung ist an manchen Stellen noch falsch.
- Abbildungen ohne Quellenangabe
- Viele Sätze sind nicht mit einer Fußnote versehen
- Es wird kaum Bezug zu Themen anderer Beiträge genommen und es wurden auch keine anderen Beiträge im Text verlinkt. Man könnte beispielsweise im Abschnitt *Preiskategorien* einen Link zum Beitrag zu **Projekten** schalten
- Der Text ist etwas zu lang, aber Martin meinte ja das geht in Ordnung.
- Ich konnte nur den Hive_PM_Tool Beitrag finden, nicht aber den zu Stand_Ups
- Man könnte bei der Tabelle noch eine Spalte einfügen und dann links als "Überschriften" Preis und Nutzer einfügen
- Leider wurden nicht viele meiner Vorschläge der ersten Runde berücksichtigt

2022-01-16 10:17 UTC, Gilchus commented
Servus Tommi,
also bei mir sind die Links zu Kanban und Gantt nicht leere Seiten sondern einfach die mds im repo. Außerdem finde ich auch meinen angepassten Beitrag zu Stand_Ups. Der Grund das viele Sätze nicht mit einer Fußnote versehen sind liegt daran, dass ich den Beitrag auf Basis eigener Erfahrung schreiben musste da es ein Tool ist. Die Abbildungen hab ich per SS selber aufgenommen, weshalb ich keine Quelle eingefügt habe/konnte. Ebenfalls kann ich deine Bewertung bei Strukturierung des Beitrags nicht nachvollziehen, da sich die Strukturierung des Beitrags an der Strukturierung des Programms orientiert. 

Grüße Gilchus

2022-01-16 12:53 UTC, TommiMueller commented
Hi Gilchus,

die Links verweisen bei mir auch auf die mds im repo. Jedoch wurden in diesen mds keine Veränderungen vorgenommen. Es sind noch die ursprünglichen "Template-Einträge". Ich würde dann am besten nachdem die Pull-Requests von Martin gemerged wurden nachschauen, ob in diesen mds nun wirkliche Beiträge vorhanden sind.
Könntest du mir vielleicht helfen, wie ich den anderen Beitrag finde? Ich gehe bei deinem Pull-Request immer auf "View-File" und bekomme dann nur den für Hive angezeigt.
Das mit den Fußnoten wusste ich nicht und geht dann natürlich in Ordnung, wenn es auf deinen eigenen Erfahrungen basiert. 
Die Bepunktung für die Strukturierung habe ich nur so gewählt, da ich finde, dass die großen Abbildungen störend sind. Die restliche Strukturierung des Beitrags finde ich gut.

Hoffe die Erklärung hilft dir :)

2022-01-17 17:03 UTC, ChrisBohl commented
<html><body>
<!--StartFragment-->

<html><body>
<!--StartFragment-->

Kriterium | Bewertung
-- | --
Front-Matter | ja
Umfang | ja
Belege | nein
Links | nein
Formatierung | ja
Verlinkungen vorhanden | nein
Abbildungen | ja
Strukturierung des Beitrags | 8
Rechtschreibung | 10
Sprache | 10
Inhalt | 10
Einordnung in den Kontext | 6
Ansprechend für Zielgruppe | 8

<!--EndFragment-->
</body>
</html>


<h1 dir="auto">Zusammenfassung</h1>
<p dir="auto">Der Artikel berichtet vom Hive Projektmanagement tool. Dieses Tool wird auf verschiedene Themenbereiche im Sinne des Nutzers durchleuchtet, wie etwa Bedienung und Mehrwert für den Nutzer. Es stellt sich heraus, dass das UI sehr intuitiv ist und benutzerfreundlich. Ebenso ist eine Migration in die Software durch zahlreiche Erweiterungen ein Plus für diese Software.</p>
<h1 dir="auto">Positive Aspekte</h1>
<p dir="auto">Sehr toll! Es liest sich gleich so viel besser, wenn die Abbildungen sichtbar sind! Insgesamt finde ich es einen sehr guten Artikel, der im richtigen Wikipedia Stil geschrieben ist und ansprechend für die Zielgruppe ist</p>
<h1 dir="auto">Negative Aspekte</h1>
<p dir="auto">Links funktionieren nicht. (Siehe auch). Die Verlinkungen zu anderen Beiträgen, sind insgesamt etwas kurz gekommen. Schön wärs, wenn die Abbildungen auch gleichzeitig auf die jeweilige Quelle verweisen. 
</body>
</html>

2022-01-25 13:51 UTC, merged