Infrastrukturprojekte,Abhängigkeitsmanagement
ManagingProjectsSuccessfully/ManagingProjectsSuccessfully.github.io pull request #429
Opened 2021-12-20 14:37 UTC by MillaLena

2022-01-18 19:27 UTC, FerYilm requested changes
| Kriterium | Bewertung|
|-----|---|
| Front-Matter | ja |
| Umfang | ja|
| Belege | ja |
| Links | ja|
| Formatierung | ja|
| Verlinkungen vorhanden | ja |
| Abbildungen | ja |
| Strukturierung des Beitrags | 10 |
| Rechtschreibung | 10|
| Sprache | 10 |
| Inhalt | 10|
| Einordnung in den Kontext | 10|
| Ansprechend für Zielgruppe | 10|

# Zusammenfassung
Der erste Beitrag handelt vom Abhängigkeitsmanagement und beginnt mit einer kurzen Definition des Begriffs. Anschlißend wird die Bedeutung für den agilen Kontext erklärt und dann näher auf die Bedeutung von Abhängigkeiten im Allgemeinen eingegangen. Abschließend wird die Vorgehensweise beschrieben und als Bespiel für die Strukturierung das Kanban Board erwähnt. 

Im zweiten Beitrag geht es um Infrastrukturprojekte, wobei viele Bespiele genannt werden. Anschließend werden die Grenzen im klassischen PM beschrieben und mit einem weiteren Beispiel verdeutlicht. Als möglichen Lösungsansatz wird abschließend das hybride PM aufgeführt.

# Positive Aspekte
Mir hatten beide Beiträge bereits in der ersten Runde inhaltlich und sprachlich sehr gefallen. Die Themen beider Artikel sind gut gewählt und dadurch informativ.
Du hast in beiden Themen an passenden Stellen Aufzählungen eingebaut, wodurch ich die Beiträge insgesamt sehr übersichtlich finde. (v.a. bei den Beispielen im Beitrag über Infrasturkturprojekte). Der Absatz über die Arten von Abhängigkeiten wird jetzt auch deutlich übersichtlicher. Neu ist auch der eigene Absatz für das Beispiel Berliner Flughafen und die kursive Schrift bei den Zitaten. :)


# Negative Aspekte
Mir sind nur kleine Kommsasetzungsfehler aufgefallen. Ansonsten habe ich keine Kritikpunkte.

Beitrag Abhängigkeitsmanagement:

"...Überblick über alle Aufgaben zu behalten, indem man.."

Beitrag Infrastrukturprojekte:
"...Meilensteine zu definieren, weil der genaue Prozess..."
"...abgestimmt sein, um Risiken zu minimieren..."
"...Ablauforganisation übernommen und..."

2022-01-18 21:44 UTC, thujavanj commented
# Abhängigkeitsmanagement

| Kriterium | Bewertung|
|-----|---|
| Front-Matter | ja|
| Umfang | ja|
| Belege | ja|
| Links | ja|
| Formatierung | ja|
| Verlinkungen vorhanden | ja|
| Abbildungen | ja |
| Strukturierung des Beitrags | 10 |
| Rechtschreibung | 10|
| Sprache | 10 |
| Inhalt | 10|
| Einordnung in den Kontext | 10|
| Ansprechend für Zielgruppe | 10|

## Zusammenfassung
Der erste Artikel befasst sich mit dem Thema Abhängigkeitsmanagement. Dies ist vor allem im agilen Management essenziell, da hier viele kleinere Gruppen an einem Projekt arbeiten. Um jedoch effizienter zu arbeiten, ist es wichtig störende Abhängigkeiten aus dem Weg zu räumen, um die Effizienz in einem Unternehmen zu erhöhen und sich nicht gegenseitig im Weg zu stehen. 

In dem zweiten Artikel geht es um Infrastrukturprojekte. Die Autorin erklärt zuerst, welche Arten von Infrastrukturprojekten existieren. Anschließend wird darüber diskutiert, ob ein agiles und klassisches Projektmanagement besser ist. Die Autorin kommt zum Entschluss, eine hybride Form aus beiden Arten ist die beste Form des Projektmanagements.  
Kurze Zusammenfassung des/der Artikel

## Positive Aspekte
Ich habe nach wie vor keine Fehler anzumerken. Deine Beiträge sind übersichtlich, informativ und einfach zu verstehen. Es wurden viele angrenzende Themen markiert, sowie viele Beiträge verlinkt. Außerdem wurden Bilder  gut gewählt und unterstreichen deinen Beitrag zusätzlich. Eine sehr gelungene Arbeit. 

## Negative Aspekte

2022-01-19 19:37 UTC, Quapoapo requested changes
# Abhängigkeitsmanagement 

| Kriterium | Bewertung|
|-----|---|
| Front-Matter | ja |
| Umfang | ja |
| Belege | ja |
| Links | ja |
| Formatierung | ja |
| Verlinkungen vorhanden | ja |
| Abbildungen | ja |
| Strukturierung des Beitrags | 10 |
| Rechtschreibung | 10 |
| Sprache | 10 |
| Inhalt | 10 |
| Einordnung in den Kontext | 10 |
| Ansprechend für Zielgruppe | 10 |

# Zusammenfassung

Der Beitrag handelt vom agilen Abhängigkeitsmanagement. Zu Beginn ist eine Definition gegeben. In den folgenden Punkten wird das Thema im Zusammenhang mit dem agilen Projektmanagement dargelegt. Noch dazu werden Funktionen und Arten von Abhängigkeiten aufgezeigt. Abschließen werden die Vorgehensweisen des Themas und das Strukturieren von Abhängigkeiten erklärt. 

# Positive Aspekte

Die Links und Belege welche hier eingefügt wurden funktionieren. Noch dazu wird auf weitere verwandte Beiträge verlinkt. Der Umfang des Beitrags ist gut gewählt. Der Beitrag ist gut zu lesen und schnell verständlich auch für Personen ohne Vorwissen zu diesem Thema. Weiterhin ist es sehr sinnvoll gestaltet zu beschreiben welche Themen das Abhängigkeitsmanagement beinhaltet und die Funktionen von Abhängigkeiten zu definieren. Das Kanban Board ist mit einer Abbildung gut veranschaulicht worden. Die Kritik wurde angenommen und die angesprochenen Rechtschreibfehler wurden korrigiert. Noch dazu wurde die Abbildung korrekt beschriftet. Das Abhängigkeitsmanagement wurde hier in einem gelungenen Beitrag erläutert.

# Negative Aspekte
Das ein oder andere Komma.

# Infrastruktur Projekte

| Kriterium | Bewertung|
|-----|---|
| Front-Matter | ja |
| Umfang | ja |
| Belege | ja |
| Links | ja |
| Formatierung | ja |
| Verlinkungen vorhanden | ja |
| Abbildungen | ja |
| Strukturierung des Beitrags | 10 |
| Rechtschreibung | 10 |
| Sprache | 10 |
| Inhalt | 10 |
| Einordnung in den Kontext | 10 |
| Ansprechend für Zielgruppe | 10|

# Zusammenfassung

Dieser Beitrag handelt von Infrastruktur Projekten. Am Anfang wird eine Definition gegeben und das Thema wird mit dem klassischen Projektmanagement in Verbindung gesetzt. Es wird auf Arten von Infrastrukturproblemen eingegangen. Hierfür wird der Berlinger Flughafen als Beispiel herangezogen. Noch dazu werden die Grenzen des klassischen Projektmanagements gezeigt. Abschließen wird die Frage gestellt ob das hybride Projektmanagement eine Lösung wäre. 

# Positive Aspekte

Der Umfang des Beitrags ist passend gewählt. Es wurde richtig zitiert und alle Verlinkungen funktionieren. Der Aufbau des Beitrags ist gut gewählt und eine Fragestellung am Ende ist, welche möglicherweise eine Lösung für die Zukunft wäre, ist eine gute Abrundung des Beitrags. Außerdem ist das Beispiel des Berliner Flughafens sehr gut gewählt. Auch hier wurden Satzzeichen und Rechtschreibung verbessert und die kritisierten Sachen verbessert. Ebenfalls wurde die Abbildung richtig beschriftet. Noch dazu wurde sich dem Zitat angenommen und es wurde überarbeitet. Im Großen und Ganzen ein gelungener Beitrag. 

# Negative Aspekte
Das ein oder andere Komma.

2022-01-22 20:39 UTC, thujavanj reviewed
# Abhängigkeitsmanagement

| Kriterium | Bewertung|
|-----|---|
| Front-Matter | ja|
| Umfang | ja|
| Belege | ja|
| Links | ja|
| Formatierung | ja|
| Verlinkungen vorhanden | ja|
| Abbildungen | ja |
| Strukturierung des Beitrags | 10 |
| Rechtschreibung | 10|
| Sprache | 10 |
| Inhalt | 10|
| Einordnung in den Kontext | 10|
| Ansprechend für Zielgruppe | 10|

## Zusammenfassung
Der erste Artikel befasst sich mit dem Thema Abhängigkeitsmanagement. Dies ist vor allem im agilen Management essenziell, da hier viele kleinere Gruppen an einem Projekt arbeiten. Um jedoch effizienter zu arbeiten, ist es wichtig störende Abhängigkeiten aus dem Weg zu räumen, um die Effizienz in einem Unternehmen zu erhöhen und sich nicht gegenseitig im Weg zu stehen. 

In dem zweiten Artikel geht es um Infrastrukturprojekte. Die Autorin erklärt zuerst, welche Arten von Infrastrukturprojekten existieren. Anschließend wird darüber diskutiert, ob ein agiles und klassisches Projektmanagement besser ist. Die Autorin kommt zum Entschluss, eine hybride Form aus beiden Arten ist die beste Form des Projektmanagements.  
Kurze Zusammenfassung des/der Artikel

## Positive Aspekte
Ich habe nach wie vor keine Fehler anzumerken. Deine Beiträge sind übersichtlich, informativ und einfach zu verstehen. Es wurden viele angrenzende Themen markiert, sowie viele Beiträge verlinkt. Außerdem wurden Bilder  gut gewählt und unterstreichen deinen Beitrag zusätzlich. Eine sehr gelungene Arbeit. 

## Negative Aspekte

2022-01-25 13:52 UTC, merged