Themen: Asana_PM_Tool und Projekthandbuch
ManagingProjectsSuccessfully/ManagingProjectsSuccessfully.github.io pull request #434
Opened 2021-12-20 16:09 UTC by Saskia1403

Hi an meine Reviewer*innen

Also ich habe versucht alle eure Vorschläge in meine Beiträge zu übernehmen. Solltet ihr trotzdem noch Fragen haben oder etwas anmerken wollen, dann schreibt mir gerne.

2022-01-12 13:37 UTC, up67enyq commented
Kriterium | Bewertung
-- | --
Front-Matter | ja
Umfang | ja
Belege | ja
Links | ja
Formatierung | ja
Verlinkungen vorhanden | ja
Abbildungen | ja
Strukturierung des Beitrags | 10
Rechtschreibung | 9
Sprache | 9
Inhalt | 10
Einordnung in den Kontext | 10
Ansprechend für Zielgruppe | 10

# Zusammenfassung
- Asana_PM_Tool
Der Artikel gibt einen kurzen Einblick in die Entstehung, Bedeutung und Funktionen von Asana. Er gibt Informationen zur Anwendung, Preisen und den Nutzen welche durch Asana erhalten werden können. Abrundend gibt er eine Preisübersicht der verschiedenen Optionen und deren Vorteile für Verwendung des Projektmanagement Tools.

- Projekthandbuch
Der Artikel erklärt zunächst das Ziel des Projekthandbuchs als ein Tool für Projektteammitglieder um einen Überblick über Vorgehen, Ziele und Inhalt zu haben. Er geht weiter darauf ein welche Komponenten im Projekthandbuch enthalten sein sollten und das dies sogar in einer DIN Norm festgehalten ist. Das Projekthandbuch wird von der Projektdokumentation  und dem Projektmanagementhandbuch abgegrenzt da sich das letztere auf allgemeine Regelungen bei Projekten eines Unternehmens beziehen, während das Projekthandbuch lediglich für ein spezielles Projekt gilt. Im weiteren Verlauf werden auf Verschiedene Varianten des Projekthandbuchs eingegangen. Darunter zählen das "V-Modell XT" ,die Projektleitdokumentation und der "Project Management Plan".

# Positive Aspekte
- Asana_PM_Tool
Schöne Abbildung um der schriftlichen Ausführung zu folgen
sehr gute Menge an Verlinkungen zu angrenzenden Themen
Sinnvolle Gliederung die die relevanten Teilbereiche gut abdeckt.
Alle Kritikpunkte abgearbeitet und verbessert

- Projekthandbuch
Abbildung des 4-Phasen-Modells sehr gut
gute Gliederung
schönen Überblick über andere Varianten
Abgrenzung zu Projektmanagementhandbuch macht die Funktion noch deutlicher
viele benutzte Quellen
gibt einen sehr guten Überblick

# Negative Aspekte

- Asana_PM_Tool
Ich würde die Fußnoten hinter die Satzzeichen packen weil es so auch bei Wiki gemacht wird, ich kann hier jedoch auch falsch liegen und würde da mal schauen was die anderen zwei Reviewer*innen dazu sagen. :)
Bei den Funktionen: 
muss das ein Google Konto sein oder reicht auch eine normale Mailadresse? Wenn ja würde ich das allgemeiner formulieren.
Im Abschnitt "Die Inbox":
Benachrichtigungen statt "Benachrichtungen"
"Auch bekommt der Nutzer eine Benachrichtigung in 'seine' Inbox" hier fände ich "seine" besser
"... wird ihm die Option angeboten, jede Benachrichtigung automatisch als E-Mail zu versenden" hier müsste eher "als E-Mail versendet zu bekommen" stehen da ja nicht der Nutzer die Mail schreibt.

- Projekthandbuch
würde die Einleitung genau anders rum aufbauen. Dachte am Anfang es geht um das 4-Phasen-Modell.
Vielleicht anfangen mit "Struktur ist maßgeblich..." dann "Das Projekthandbuch verschafft allen Teammitgliedern eines Projektes einen Überblick über Ziele und Inhalte." -> Überblick über 4-Phasen-Modell
"..ist es in seiner Ausführung ziemlich knapp" ziemlich kann weg gelassen werden um prägnanter zu sein.
im letzten Abschnitt "Project Management Plan" in Anführungszeichen.

2022-01-12 19:44 UTC, urimi0 requested changes
| Kriterium | Bewertung|
|-----|---|
| Front-Matter | ja |
| Umfang | ja |
| Belege | ja |
| Links | ja |
| Formatierung | ja |
| Verlinkungen vorhanden | ja |
| Abbildungen | ja |
| Strukturierung des Beitrags | 10 |
| Rechtschreibung | 9 |
| Sprache | 9 |
| Inhalt | 9 |
| Einordnung in den Kontext | 10 |
| Ansprechend für Zielgruppe | 10 |

# Zusammenfassung
* Asana ist ein Projetkmanagementtool, welches mehrere Features bietet, um die Arbeit in Unternehmen zu vereinfachen. Dabei hat man die Möglichkeit auch Daten aus anderen Programmen wie Excel, etc. mit zu integrieren.
# Positive Aspekte

* Links wurden korrigiert
* Viele Quellen -> Arbeit entstanden aus mehreren Perspektiven
* Gute Abbildung.
* Gut erklärt welche Funktionen Asana bietet.
* Sprache wurde gut überarbeitet
* Besser strukturiert aber inhaltlich wenig Veränderung

# Negative Aspekte

* Preistabelle vielleicht ein wenig detaillierter in den Funktionen, die man erhält für den 
jeweiligen Aufpreis.

* Der Punkt „Berichte“ könnte weggelassen oder woanders hinzugefügt werden

* Ansonsten keine weiteren Kritikpunkte

2022-01-12 20:07 UTC, urimi0 requested changes
| Kriterium | Bewertung|
|-----|---|
| Front-Matter | ja |
| Umfang | ja |
| Belege | ja |
| Links | ja |
| Formatierung | ja |
| Verlinkungen vorhanden | ja |
| Abbildungen | ja |
| Strukturierung des Beitrags | 10 |
| Rechtschreibung | 9 |
| Sprache | 9 |
| Inhalt | 10 |
| Einordnung in den Kontext | 10 |
| Ansprechend für Zielgruppe | 10 |

# Zusammenfassung
* Ein Projekthandbuch dient als Leitfaden zur Bearbeitung eines Projektes.
Hierbei gibt es eine gewisse Hierarchie. Projektleiter sollen dieses Handbuch erstellen und aktualisieren. Mitarbeiter sollen ihren Fokus auf die Einhaltung dieses Projekthandbuchs dann legen.

# Positive Aspekte

* Neue Abbildung viel besser
* Gute Überleitung zu naheliegenden Themen.
* Quellen wurden korrigiert
* Besser strukturiert 
* Gute Einleitung mit Abbildung

# Negative Aspekte

* Ein Satz unter „Varianten des Projekthandbuchs“ nicht wirklich nötig.

* Keine weiteren Kritikpunkte.

2022-01-13 22:13 UTC, Aseuc commented
| Kriterium | Bewertung|
|-----|---|
| Front-Matter | ja|
| Umfang | ja|
| Belege | ja|
| Links | ja|
| Formatierung | ja|
| Verlinkungen vorhanden | ja|
| Abbildungen | ja |
| Strukturierung des Beitrags |10 |
| Rechtschreibung | 8|
| Sprache | 9 |
| Inhalt | 10|
| Einordnung in den Kontext | 10|
| Ansprechend für Zielgruppe | 10|
# Zusammenfassung
In dem Beitrag Asana_PM_Tool wird auf kurz auf die Entstehungsgeschichte von Asana Inc. eingegangen. Danach werden die verschiedenen Funktionen von Asana beschrieben und erklärt. Durch Schaubilder wird dem Leser einfach verdeutlicht wie einfach der Umgang mit dem Asana_PM_Tool ist. Unter anderem werden die verschiedenen Items, welche es im Tool gibt detailliert beschrieben und erklärt.
# Positive Aspekte
-	alle Links funktionieren bei mir einwandfrei und sind vorhanden
-	es wird auf die Abbildungen eingegangen und passen zum Inhalt
-	gut strukturierter Beitrag
-	Quellen wurden überarbeitet
# Negative Aspekte
-	„die Möglichkeit ein Übereinkommen“ zwischen „Möglichkeit“ und „ein“ sollte ein Komma gesetzt werden
-	Um den Wiki-Zitierregeln zu entsprechen sollten die Fußnoten nach dem Punkt gesetzt werden falls sich die Quelle auf den gesamten Absatz beziehen. Beziehen sie sich die Quellen nur auf den einen Satz sollte die Fußnote vor dem Punkt stehen. 
-	„Im Register „Meine Aufgaben“, befinden sich alle“ sollte zwischen dem Gänsefüßchen und dem „befinde“ kein Komma gesetzt werden
-	Bei „Benachrichtgungen“ im Absatz Inbox fehlt ein „i“ -> „Benachrichtigungen“
-	Im Absatz Inbox -> „Hinzufügen einer neuen Aufgabe, eines“ -> Komma evtl. entfernen
-	„Darüber hinaus gibt es in der Inbox die Möglichkeit Nachrichten an andere Teammitglieder“ -> zwischen „Möglichkeit“ und „Nachrichten“ evtl. ein Komma setzen
-	Bei „Das Aufgaben-Fenster“ -> „um den nicht verantwortlichen Teammitgliedern, einen Überblick zu verschaffen“ -> sollte das Komma entfernt werden zwischen „Teammitglieder“ und „einen“
-	Bei „Berichte“ -> „hinaus die Möglichkeit unter dem Register Berichte“ -> ein Komma zwischen „Möglichkeit“ und „unter" setzen
-	Letzter Absatz -> „Je nachdem welche Ansprüche ein Unternehmen“ -> zwischen „nachdem“ und „welche“ ein Komma setzen

2022-01-13 22:37 UTC, Aseuc commented
| Kriterium | Bewertung|
|-----|---|
| Front-Matter | ja|
| Umfang | ja|
| Belege | ja|
| Links | ja|
| Formatierung | ja|
| Verlinkungen vorhanden | ja|
| Abbildungen | ja |
| Strukturierung des Beitrags |10 |
| Rechtschreibung | 8|
| Sprache | 9 |
| Inhalt | 10|
| Einordnung in den Kontext | 10|
| Ansprechend für Zielgruppe | 10|
# Zusammenfassung
In dem Beitrag Projekthandbuch wird der Zusammenhang zwischen 4-Phasen-Modell und dem Projekthandbuch erklärt. Des Weiteren wird das Projekthandbuch definiert und seine Funktionen erklärt. 
Durch eine Begriffliche Abgrenzung von ähnlichen Begriffen wird dem Leser aufgezeigt, welche unterschiede es zwischen den verschiedenen Handbüchern gibt. Unter werden auch andere Varianten von Projekthandbüchern näher erklärt und definiert. 

# Positive Aspekte
-	alle Links funktionieren bei mir einwandfrei und sind vorhanden
-	gut strukturierter Beitrag
-	Quellen wurden überarbeitet
-	Viele Quellen wurden eingesetzt
-	Sprache hat sich sehr verbessert, es ist jetzt viel verständlicher
-	Detailreiche und gute Erklärungen der verschiedenen Projekthandbücher
# Negative Aspekte
-	Um den Wiki-Zitierregeln gerecht zu werden müssen die Fußnoten der Quellen hinter dem Punkt stehen falls sich die Quelle auf den Absatz bezieht. Falls sich die Quelle nur auf den Satz bezieht muss die Fußnote vor dem Punkt stehen.
-	Leider funktioniert bei mir das Bild nicht -> Fehlercode 404 page not found
-	„Im Zuge dessen, hat sich“ -> Komma entfernen
-	„alle Phasen des Projektes hinweg, einen Überblick“ -> Komma entfernen
-	„Als wichtiges Artefakt des klassischen Projektmanagements, kann das Projekthandbuch“ -> Komma entfernen
-	„Speziellen umfasst ist nicht“ -> Komma zwischen „umfasst“ und „ist“
-	„Aufzählung aller Projektbeteiligten, sowie ihrer“ -> Komma entfernen
-	„sowohl für die Erstellung, als auch“ -> Komma entfernen
-	„Projektassistenz“ -> sollte evtl. „Projektassistent“ heißen
-	„jede neue Version, von dem“ -> Komma entfernen
-	„Durchführung des Projekts und die anstehenden Entwicklungsaufgaben.““ -> Gänsefuß hinter Entwicklungsaufgaben entfernen 
-	„Konfigurations-, Risiko-, und Kommunikationsmanagementstrategie.“ -> kein Komma vor einem und -> Komma vor dem und entfernen
-	„Ähnlich wie beim V-Modell XT, definiert das britisches“ -> hier sollte evtl. kein Komma gesetzt werden
-	„Zeitplan und Kosten des Projektes, sowie einen Anforderungs-, Änderungs- und“ -> Komma entfernen

2022-01-13 22:38 UTC, Aseuc requested changes
-	Um den Wiki-Zitierregeln gerecht zu werden müssen die Fußnoten der Quellen hinter dem Punkt stehen falls sich die Quelle auf den Absatz bezieht. Falls sich die Quelle nur auf den Satz bezieht muss die Fußnote vor dem Punkt stehen.
-	Leider funktioniert bei mir das Bild nicht -> Fehlercode 404 page not found
-	„Im Zuge dessen, hat sich“ -> Komma entfernen
-	„alle Phasen des Projektes hinweg, einen Überblick“ -> Komma entfernen
-	„Als wichtiges Artefakt des klassischen Projektmanagements, kann das Projekthandbuch“ -> Komma entfernen
-	„Speziellen umfasst ist nicht“ -> Komma zwischen „umfasst“ und „ist“
-	„Aufzählung aller Projektbeteiligten, sowie ihrer“ -> Komma entfernen
-	„sowohl für die Erstellung, als auch“ -> Komma entfernen
-	„Projektassistenz“ -> sollte evtl. „Projektassistent“ heißen
-	„jede neue Version, von dem“ -> Komma entfernen
-	„Durchführung des Projekts und die anstehenden Entwicklungsaufgaben.““ -> Gänsefuß hinter Entwicklungsaufgaben entfernen 
-	„Konfigurations-, Risiko-, und Kommunikationsmanagementstrategie.“ -> kein Komma vor einem und -> Komma vor dem und entfernen
-	„Ähnlich wie beim V-Modell XT, definiert das britisches“ -> hier sollte evtl. kein Komma gesetzt werden
-	„Zeitplan und Kosten des Projektes, sowie einen Anforderungs-, Änderungs- und“ -> Komma entfernen

2022-01-16 10:32 UTC, Saskia1403 commented
Danke für euer Feedback! Bezüglich der Verlinkung der Quellen habe ich nochmal nachgesehen und folgendes herausgefunden: ja, es stimmt bei Wikipedia kommt die Quelle tatsächlich nach dem Punkt. Allerdings wurden in dem Beispieltext von dem Kompendium, den jeder am Anfang hatte, die Quellen vor dem Punkt verlinkt. Deshalb werde ich auch bei dieser Methode bleiben.

2022-01-25 13:52 UTC, merged