Pareto-Prinzip NEUE VERSION
ManagingProjectsSuccessfully/ManagingProjectsSuccessfully.github.io pull request #437
Opened 2021-12-20 16:39 UTC by nahihiry

2021-12-21 17:20 UTC, nahihiry commented
Umgesetztes Feedback:
• Mathematischen Hintergrund einbezogen (Das Pareto-Prinzips im Koordinatensystem)
   => Sinnvollere Abbildung ausgesucht und erklärt
• Das Pareto-Prinzip auf das Projektmanagement bezogen
• Verlinkungen eingefügt für eine bessere Einordnung in den Kontext
• Vergleich mit der Pomodoro-Technik klarer erklärt
• Verbesserungen in der Rechtschreibung
• Erster Absatz erklärt was das Pareto-Prinzip ist und nennt nicht nur die Zielsetzung des Prinzips
• Ersten und zweiten Gliederungspunkt vertauscht für eine bessere Struktur

2022-01-15 23:27 UTC, JonasMallwitz requested changes
| Kriterium | Bewertung|
|-----|---|
| Front-Matter | ja|
| Umfang | ja|
| Belege | ja|
| Links | ja|
| Formatierung | ja|
| Verlinkungen vorhanden | ja|
| Abbildungen | ja|
| Strukturierung des Beitrags | 9 |
| Rechtschreibung | 7|
| Sprache | 7 |
| Inhalt | 8|
| Einordnung in den Kontext | 9|
| Ansprechend für Zielgruppe | 8|

# Zusammenfassung

Der Artikel befasst sich mit dem Pareto-Prinzip und zieht Parallelen zum PM. 

# Positive Aspekte

Der Artikel ist sinnvoll strukturiert und weist eine logische Gliederung auf. Der Artikel hat sich allgemein im Vergleich zur ersten Version deutlich verbessert! 

# Negative Aspekte

Leider sind immer noch viele sprachliche und grammatikalische Fehler vorhanden (bspw. "den" statt "dem"). Man hätte zudem ein konkretes Fallbeispiel (Unternehmen oder Organisation) nennen und beschreiben können, in der das Pareto-Prinzip angewandt wird, anstelle einzelne Beispiele ohne Kontext zu nennen. Dies würde den Artikel einen höheren Grad an Authentizität geben.

2022-01-17 11:09 UTC, mickey0684 requested changes
| Kriterium | Bewertung|
|-----|---|
| Front-Matter | ja |
| Umfang | ja |
| Belege | ja |
| Links | ja |
| Formatierung | ja |
| Verlinkungen vorhanden | ja |
| Abbildungen | ja |
| Strukturierung des Beitrags | 8 |
| Rechtschreibung | 8 |
| Sprache | 9 |
| Inhalt | 10 |
| Einordnung in den Kontext | 10 |
| Ansprechend für Zielgruppe | 8 |

# Zusammenfassung

Der Artikel befasst sich mit dem Pareto-Prinzip und dem einhergehenden Zeitmanagement

# Positive Aspekte

Vergleich mit einer anderen Zeitersparnis Technik, gutes Diagramm zur Pareto-Verteilung

# Negative Aspekte

2-3 Rechtschreibfehler entdeckt; Verlinkung zum Projektmanagement fehlerhaft; Tabelle mit den Beispielen für mich nicht verständlich bspw. Mitarbeiter und Fehltage: wie hängt das mit 20% Aufwand und 80% Ergebnis zusammen?--> hätte man vielleicht kurz erklären können

2022-01-18 12:06 UTC, Mezhonnov reviewed
| Kriterium | Bewertung|
|-----|---|
| Front-Matter | ja| 
| Umfang | ja |
| Belege | ja |
| Links | ja |
| Formatierung | ja |
| Verlinkungen vorhanden | ja |
| Abbildungen | ja |
| Strukturierung des Beitrags | 10 |
| Rechtschreibung | 9 |
| Sprache | 9 |
| Inhalt | 10|
| Einordnung in den Kontext | 10 |
| Ansprechend für Zielgruppe | 10 |

# Zusammenfassung

Das nach Vilfredo Pareto benannte Pareto-Prinzip (oder die Pareto-Methode) befasst sich mit der Beziehung zwischen Aufwand und Ergebnis: 80% der Wirkung können durch 20% der beteiligten Faktoren erreicht werden.

# Positive Aspekte

Der Artikel sieht viel besser aus (als 1te Version). Gliederung und Inhalt finde ich TOP.

# Negative Aspekte

Ein paar Rechtscreibfehler. 
Das Bild ist bei mir nicht angezeigt 😢

2022-01-25 13:53 UTC, merged