Patch 2
ManagingProjectsSuccessfully/ManagingProjectsSuccessfully.github.io pull request #446
Opened 2021-12-20 22:30 UTC by AlineBurger

2021-12-21 16:31 UTC, AlineBurger commented
Folgendes Feedback wurde umgesetzt:

Um den Beitrag ansprechender für die Zielgruppe zu gestalten habe ich: 
- Abbildung eingefügt
- Punkteliste eingefügt
- Mehr Absätze eingebaut.

Sonstige Veränderungen:
- Front Matter vervollständigt 
- anfängliche Aufzählung herausgenommen
- Wiederholung eines Abschnitts gelöscht

2022-01-13 12:10 UTC, moritzgrt reviewed
| Kriterium | Bewertung|
|-----|---|
| Front-Matter | ja|
| Umfang | ja|
| Belege | ja |
| Links | ja|
| Formatierung | ja|
| Verlinkungen vorhanden | ja|
| Abbildungen | ja |
| Strukturierung des Beitrags | 10 |
| Rechtschreibung | 10|
| Sprache | 10 |
| Inhalt | 10|
| Einordnung in den Kontext | 9|
| Ansprechend für Zielgruppe | 10|

# Zusammenfassung

Der Artikel befasst sich im Allgemeinen mit Change Management. Genauer werden die einzelnen Schritten und Phasen des Change Managements beleuchtet.

# Positive Aspekte
Schöne Abbildung und Punktliste.
Die Strukturierung im Vergleich zur ersten Review Runde weist einen deutlichen roten Faden auf und ist gut nachvollziehbar. 


# Negative Aspekte

Die Kritik aus der ersten Review Runde wurde vollständig umgesetzt.

2022-01-14 09:11 UTC, Leni2505 requested changes
| Kriterium | Bewertung|
|-----|---|
| Front-Matter | ja |
| Umfang | ja |
| Belege | ja |
| Links | ja |
| Formatierung | ja |
| Verlinkungen vorhanden | ja |
| Abbildungen | ja |
| Strukturierung des Beitrags | 10 |
| Rechtschreibung | 9|
| Sprache | 10 |
| Inhalt | 10 |
| Einordnung in den Kontext | 10 |
| Ansprechend für Zielgruppe | 10 |

# Zusammenfassung

Der Beitrag befasst sich mit dem Change Management, wobei besonders auf die einzelnen Phasen des Change Managements eingegangen wird.


#Positive Aspekte 

Du hast alle Verbesserungsvorschläge gut umgesetzt. 
Dein Artikel ist jetzt viel übersichtlicher und besser strukturiert. 

#Negative Aspekte

Bei der Überschrift "Phasen des Change Managements" fehlt bei Management ein "a".

2022-01-14 11:21 UTC, ow79arux requested changes
| Kriterium | Bewertung|
|-----|---|
| Front-Matter | ja |
| Umfang | ja|
| Belege | ja |
| Links | ja
| Formatierung | ja|
| Verlinkungen vorhanden | ja |
| Abbildungen | ja |
| Strukturierung des Beitrags | 0 |
| Rechtschreibung | 8|
| Sprache | 10 |
| Inhalt | 10|
| Einordnung in den Kontext | 9|
| Ansprechend für Zielgruppe | 9|

# Zusammenfassung

Der Artikel befasst sich mit dem Change Management und erläutert vor allem die einzelnen Phasen.

# Positive Aspekte
* gute Abblidung
* schön gegliedert

# Negative Aspekte
Das meiste aus der Kritik wurde umgesetzt. Hier nur noch ein paar Kleinigkeiten zur Verbesserung:
* Für die Phasen würde ich Unterüberschriften verwenden, da das Folgende alles zu Phasen gehört. Sieht dadurch zugehöriger aus.
* Bei "Phasen des Change Mangements": " Im Folgenden möchte ich den typischen Setup und Ablauf solch eines Projektes darstellen" neutrale Formulierung verwenden, wie z.B im folgenden wird dargestellt...
* In der Anlaufphase noch ein kleiner Fehler: nach "Idealerweise werden deshalb im Umfeld des Kick-Off alle" Projektbeteiligten

2022-01-18 20:25 UTC, AlineBurger commented
> Kriterium	Bewertung
> Front-Matter	ja
> Umfang	ja
> Belege	ja
> Links	ja
> Formatierung	ja
> Verlinkungen vorhanden	ja
> Abbildungen	ja
> Strukturierung des Beitrags	0
> Rechtschreibung	8
> Sprache	10
> Inhalt	10
> Einordnung in den Kontext	9
> Ansprechend für Zielgruppe	9
> # Zusammenfassung
> Der Artikel befasst sich mit dem Change Management und erläutert vor allem die einzelnen Phasen.
> 
> # Positive Aspekte
> * gute Abblidung
> * schön gegliedert
> 
> # Negative Aspekte
> Das meiste aus der Kritik wurde umgesetzt. Hier nur noch ein paar Kleinigkeiten zur Verbesserung:
> 
> * Für die Phasen würde ich Unterüberschriften verwenden, da das Folgende alles zu Phasen gehört. Sieht dadurch zugehöriger aus.
> * Bei "Phasen des Change Mangements": " Im Folgenden möchte ich den typischen Setup und Ablauf solch eines Projektes darstellen" neutrale Formulierung verwenden, wie z.B im folgenden wird dargestellt...
> * In der Anlaufphase noch ein kleiner Fehler: nach "Idealerweise werden deshalb im Umfeld des Kick-Off alle" Projektbeteiligten

2022-01-18 20:32 UTC, AlineBurger commented
@ow79arux vielen Dank für deine Bewertung! Bei "Strukturierung des Beitrags" hast du mir 0 Punkte vergeben. Handelt es sich aufgrund deines sonst positiven Feedbacks vielleicht um einen Tippfehler? 
LG

2022-01-19 12:45 UTC, ow79arux commented
@AlineBurger oh sorry ja ist ein Tippfehler sollte eigentlich eine 10 sein.

2022-01-25 13:53 UTC, merged