Bottom Up Planning
ManagingProjectsSuccessfully/ManagingProjectsSuccessfully.github.io pull request #453
Opened 2021-12-21 09:40 UTC by FAUdennis96

Bottom Up Planning beschreibt eine Herangehensweise für Projekte. Die Planung beginnt auf den unteren Hierarchieebenen und arbeitet sich nach oben, in die Führungsebenen.
Der Gegenspieler dazu ist das Top Down Planning, bei dem der Planungsprozess in der Regel entgegengesetzt verläuft. 

# Bottom Up Planning

Der Grundstein für die im folgenden Beitrag beschriebene Thematik, wurde schon ca 340 v. Chr. gelegt. Auf den griechischen Universalgelehrten [Aristoteles](https://de.wikipedia.org/wiki/Aristoteles) lässt sich der Satz „Das Ganze ist mehr als die Summe seiner Teile“ zurückführen. Dieses Zitat stammt aus einer Sammlung von Texten, welche „Metaphysik“ genannt wird[^1].

![image](https://user-images.githubusercontent.com/92928630/143274774-cfc8e827-57e2-444a-95f2-88b1e4cc9f1e.png)

Das große Ganze, also das Ergebnis eines Prozesses oder Projekts ist dass, worauf es im Endeffekt ankommt. Es gibt in der Regel mehrere Wege, Methoden und Vorgehensweisen um erfolgreich zu sein. Bezogen auf das Agile Projektmanagement unterscheidet man die [Top_Down_Planning](Top_Down_Planning.md) und die Bottom Up Planning Methode. Hierbei unterscheidet sich lediglich die Vorgehensweise, der Output ist in der Regel identisch. Beide Methoden haben Ihre Vor- und Nachteile und sind als Ganzes, wenn sie kombiniert werden, mehr wert als die Summe der Einzelteile. Im Folgenden wird die Bottom Up Planning Methode vorgestellt.

## Wie funktioniert Bottom Up Planning?

Bottom Up bedeutet frei übersetzt von unten nach oben. Die Planung wird „unten“ gestartet und arbeitet sich Stück für Stück nach „oben“. Bei der Bottom Up Planning Methode werden zunächst relativ enge Ziele auf den unteren Ebenen der Organisationshierarchie festgelegt. Sie werden dann schrittweise in den Rahmen der globalen Ziele und Strategie auf höheren Ebenen integriert. Es handelt sich ebenso um eine Methode, zur Planung als auch für die Definition von Unternehmenszielen und Möglichkeiten für deren Erreichung[^2].
Diese Herangehensweise zielt darauf ab einen Plan auf einer unteren, sinnvollen Klassifizierungsebene zu erstellen. Die Planung bewegt sich dann schrittweise aufwärts - von unten nach oben. Jede Ebene plant ihre Ziele und Maßnahmen und leitet ihren Teilplan an die übergeordnete Ebene weiter. Dort werden die Teilpläne koordiniert, kontrolliert, integriert, ergänzt und wiederum an die nächsthöhere Ebene weitergegeben. 

![image](https://user-images.githubusercontent.com/92928630/143275928-341298e9-9093-4511-aa5c-43a1136ab7d4.png)

Der [Aggregationsgrad](https://www.fremdwort.de/suchen/bedeutung/aggregationsgrad) nimmt dabei stetig zu[^3]. Am Ende des Prozesses steht die strategische Planung. Vorteile dieser dezentralen Vorgehensweise sind zum einen eine hohe Motivation und Identifikation der Mitarbeiter mit dem erstellten Plan. Sie haben in der Regel Zugang zu allen wichtigen Informationen und werden unmittelbar in die Planung eingebunden, statt von oben „verplant“ zu werden. Das breit gefächerte und zugleich detaillierte Wissen der Fachkräfte wird genutzt und schafft ein starkes Zugehörigkeitsgefühl[^4]. Zum anderen ist die erhöhte Realisierbarkeit ein Vorteil, da das Fachwissen der Mitarbeiter auf allen Ebenen miteinbezogen wird. Zu den wesentlichen Nachteilen der Bottom Up Planung zählt neben dem hohen Koordinations- und Zeitaufwand insbesondere die Gefahr, dass sich die einzelnen Teilpläne inhaltlich wieder sprechen und dass sich die einzelnen Planungseinheiten weniger ambitionierte Ziele setzen oder diese lediglich fortschreiben. Dies kann letztlich dazu führen, dass das gesamtunternehmerische Zielniveau nicht erreicht wird[^5]. 

## Wo kommt Bottom Up Planning zum Einsatz?

Die Anwendungsbereiche sind schier endlos. Von der Informatikbranche, über die städtische und regionale Raumplanung bis hin zu Marketingstrategien sind [Top_Down_Planning](Top_Down_Planning.md) und Bottom Up Planning Methoden beliebt[^6].Ein prominentes Beispiel für den Wandel zum Bottom Up Ansatz stellt die [New York Times](https://www.nytimes.com/subscription?campaignId=7UXFY&ds_c=71700000074377394&gclid=CjwKCAiA4veMBhAMEiwAU4XRrxJ7baq3Vw4ZRV62Qfy0EOZmwmyQYrDtExpYe8A33M2WSUxHs5CzqBoCc0AQAvD_BwE&gclsrc=aw.ds) dar. Vor einigen Jahren wurde in den USA darüber berichtet, dass die Geschäftsleitung der einflussreichen US-Amerikanischen Tageszeitung das Gefühl hatte, nicht in der Lage zu sein die erforderlichen Bedingungen für die Entstehung eines dynamischen Arbeitsumfeldes und eine erfolgreiche Organisation zu erfüllen. Zentralisierte Führung hatte zur Folge, dass leitende Redakteure sich völlig kontrolliert fühlten und keinen Spielraum für Eigenengagement hatten. Alle Projektentscheidungen wurden nur von den Gefühlen und Meinungen des Projektmanagers beeinflusst. Das Ergebnis war eine schlechte Zusammenarbeit der Journalisten und wenig Motivation für die tägliche Arbeit. Den leitenden Führungskräften wurde bewusst, dass sie ihren Teams mehr Freiheit geben mussten und den Führungsstil ändern sollten. Es dauerte einige Zeit bis ein Bottom Up Management in die Organisation eingeführt werden konnte. Doch seither bestätigen die Mitarbeiter, dass die Zusammenarbeit effizienter und effektiver ist[^7].

# Quellen

[^1]: https://de.wikipedia.org/wiki/Metaphysik_(Aristoteles)
[^2]: https://www.jedox.com/de/blog/top-down-bottom-up-planung/
[^3]: https://www.evolutionizer.com/blog/planungsrichtung-gegenstromverfahren
[^4]: https://blog.hubspot.de/sales/bottom-up-ansatz
[^5]: https://www.evolutionizer.com/blog/planungsrichtung-gegenstromverfahren
[^6]: https://de.wikipedia.org/wiki/Top-down_und_Bottom-up
[^7]: https://www.wrike.com/de/blog/top-down-und-bottom-up-projektmanagement-verhaeltnis-der-vorteile-der-beiden-ansaetze/

2021-12-21 09:47 UTC, FAUdennis96 commented
Auf die Kritikpunkte Abschlussfazit und Abbildung mit mehr Mehrwert konnte ich nicht mehr eingehen, da zum einen der 500-Wörterrahmen schon extrem von mir ausgereizt war und ich zum anderen keinen bessere Abbildung finden konnte.

2022-01-16 12:53 UTC, JonathanLoewing reviewed
| Kriterium | Bewertung|
| ---------- | ----------- |
| Front-Matter | ja |
| Umfang | ja |
| Belege | ja |
| Links | ja |
| Formatierung | ja |
| Verlinkungen vorhanden | ja |
| Abbildungen | ja |
| Strukturierung des Beitrags | 10 |
| Rechtschreibung | 10 |
| Sprache | 10 |
| Inhalt | 10 |
| Einordnung in den Kontext | 10 |
| Ansprechend für die Zielgruppe | 10 |

# Positive Aspekte
Die gewünschten Verbesserungen aus den Reviews wurden gut umgesetzt. 
Ein sehr gelungener Artikel.
# Negative Aspekte
Die Quellenverlinkung bei den Bildern fehlt.

2022-01-16 15:21 UTC, MrSommC requested changes
| Kriterium | Bewertung|
|-----|---|
| Front-Matter | ja|
| Umfang | ja|
| Belege | ja|
| Links | ja|
| Formatierung | ja|
| Verlinkungen vorhanden | ja|
| Abbildungen | ja|
| Strukturierung des Beitrags |10 |
| Rechtschreibung |10|
| Sprache |10 |
| Inhalt |9|
| Einordnung in den Kontext |10|
| Ansprechend für Zielgruppe |10|

# Positive Aspekte
Artikel sehr gut überarbeitet

# Negative Aspekte
Verlinkung bei den Bildern fehlt, demnach Abzug bei Inhalt.

2022-01-16 15:22 UTC, Lukas1401 requested changes
| Kriterium | Bewertung|
|-----|---|
| Front-Matter | ja |
| Umfang | ja |
| Belege | ja |
| Links | ja |
| Formatierung | ja |
| Verlinkungen vorhanden | ja |
| Abbildungen | ja |
| Strukturierung des Beitrags | 10 |
| Rechtschreibung | 10|
| Sprache | 10 |
| Inhalt | 10 |
| Einordnung in den Kontext | 10 |
| Ansprechend für Zielgruppe | 10 |

# Zusammenfassung

In dem Artikel geht es um das sogenannte Bottom Up Planning. Zunächst wird der Grundstein dieser Methode und der Unterschied zur Top Down Planning Methode erläutert. Danach wird beschrieben, wie das Bottom Up Planning funktioniert, wobei dies auch graphisch visualisiert wurde. Zum Schluss werden mögliche Anwendungsbereiche genannt.

# Positive Aspekte

Gute Überarbeitung des Artikels.

# Negative Aspekte

Verlinkungen der Quellen bei den Bildern fehlen.

2022-01-25 13:56 UTC, merged