Projektphasen klassisch final
ManagingProjectsSuccessfully/ManagingProjectsSuccessfully.github.io pull request #456
Opened 2021-12-21 09:58 UTC by vegas1337

2021-12-22 12:31 UTC, vegas1337 commented
Ich habe durch die Reviews folgendes verbessert:
- Hauptüberschrift
- Rechtschreibung
- Bild eingefügt
- "Siehe auch" und "Weiterführende Literatur" angehängt

2022-01-13 20:21 UTC, AnjaKlostermeier requested changes
| Kriterium | Bewertung|
|-----|---|
| Front-Matter | nein|
| Umfang | ja|
| Belege | ja|
| Links | ja|
| Formatierung | ja|
| Verlinkungen vorhanden | ja|
| Abbildungen | ja|
| Strukturierung des Beitrags | 10|
| Rechtschreibung | 10|
| Sprache | 10 |
| Inhalt | 10|
| Einordnung in den Kontext | 10|
| Ansprechend für Zielgruppe | 10|

# Zusammenfassung
Dieser Artikel handelt von den klassischen Projektphasen. Zuerst wird der Begriff definiert und zu den Projektphasen im Detail übergeleitet. Danach wurden die einzelnen Phasen kurz beschrieben. Zuletzt erfolgt eine komprimierte Zusammenfassung.

# Positive Aspekte
Der Artikel ist in einer gut verständlichen Sprache geschrieben. Auch wurde er durch Überschriften unterschiedlicher Größe gut strukturiert. Es sind einige Verlinkungen zu bekannten Themen vorhanden. So kann man das Thema sehr gut in den Kontext einordnen. Auch wurde weiterführende Literatur zur Verfügung gestellt. Quellen und eine Abbildung ist vorhanden. Die Zusammenfassung am Ende gefällt mir gut. 

# Negative Aspekte
Da die bereits vorgefertigte Tabelle zu Beginn mit dem Title, tags etc. schon vorgegeben war, benötigt man keine erneute große Überschrift mit dem Titel (doppelt). 
Ebenso funktioniert die Verlinkung der Quelle 5 im Quellenverzeichnis nicht.

2022-01-17 15:03 UTC, Phil224 requested changes
| Kriterium | Bewertung|
|-----|---|
| Front-Matter | ja |
| Umfang | nein|
| Belege | ja |
| Links | ja|
| Formatierung | ja|
| Verlinkungen vorhanden | ja|
| Abbildungen | ja|
| Strukturierung des Beitrags | 10 |
| Rechtschreibung | 10|
| Sprache | 10 |
| Inhalt | 10|
| Einordnung in den Kontext | 10|
| Ansprechend für Zielgruppe | 10|

# Zusammenfassung

Der Artikel beschäftigt sich mit den Projektphasen von klassischen Projekten. Dabei wird zunächst der Begriff Projektphase definiert und in das Thema eingeführt, anschließend werden die einzelnen Projektphasen betrachtet.

# Positive Aspekte

Der Beitrag ist sprachlich sehr gut geschrieben und perfekt durch Überschriften verschiedenster Größen strukturiert. Der Beitrag ist sehr gut in den Kontext eingebunden, dabei sind vor allem die vielen Verlinkungen hervorzuheben. Die Grafik sowie die dazugehörige Zusammenfassung am Ende des Beitrags rundet das Thema sehr gut ab. 


# Negative Aspekte

Leider ist der Text mit über 700 Wörtern immer noch zu lang, ggf. könnte man diesen daher noch kürzen. Die Verlinkung der Quelle 5 im Quellenverzeichnis funktioniert zudem nicht.

2022-01-18 16:47 UTC, LindaStu requested changes
| Kriterium | Bewertung|
|-----|---|
| Front-Matter | ja |
| Umfang | nein|
| Belege | ja |
| Links | ja|
| Formatierung | ja|
| Verlinkungen vorhanden | ja |
| Abbildungen | ja |
| Strukturierung des Beitrags | 10 |
| Rechtschreibung | 9|
| Sprache | 10 |
| Inhalt | 10|
| Einordnung in den Kontext | 10|
| Ansprechend für Zielgruppe | 10|

# Zusammenfassung

Zuerst wird der Begriff Projektphase kurz beschrieben, und in Phasen aufgeteilt. Dann folgen die einzelnen Phasen im Detail.

# Positive Aspekte

Gut erklärt, sehr ausführlich. Im Text selbst wurde oft auf andere Themen eingegangen und verlinkt, finde ich sehr gut. Zudem wurde eine Grafik hinzugefügt, dadurch wird der Text anschaulicher. Es wurden auch Links zu Siehe auch und Weiterführende Literatur hinzugefügt. Die meisten Rechtschreibfehler wurden auch verbessert.

# Negative Aspekte

Die 5. Quelle hat immer noch keinen Link, zudem ist der Text zu lang und ganz am Ende wurden Phasen ohne h geschrieben. Aber sind nur Kleinigkeiten.

2022-01-25 13:57 UTC, merged