Risikomanagement_finished
ManagingProjectsSuccessfully/ManagingProjectsSuccessfully.github.io pull request #459
Opened 2021-12-21 10:30 UTC by jnsdhr

2021-12-22 15:10 UTC, jnsdhr commented
Vielen Dank für die hilfreichen Reviews! 
Nach der Analyse habe ich folgendes verbessert:
- das 2. Bild wurde etwas kleiner gemacht und der Link herausgeschnitten
- die Unterüberschriften beim 4. Punkt wurden in der Form 4.1, 4.2 usw. neu angeordnet
-  bei 4.3 wurden die Stichpunkte der Möglichkeiten neu formatiert
- der Satz, welcher die zentrale Aufgabe des Risikomanagements beschreibt, wurde grammatikalisch verbessert
- bei Punkt 5 wurde ein Doppelpunkt eingefügt
- es wurde auf andere Beiträge verlinkt

was wurde nicht verbessert:
- weiterhin eher stichpunktartig, da sich das meiner Meinung nach bei diesem Thema besser anbietet und das Lesen sowie Verständnis erleichtert
- Fazit-Länge unverändert, da ein Fazit mehr zusammenfassen als neue Informationen generieren soll

2022-01-16 11:28 UTC, DanielLeiLei reviewed
| Kriterium | Bewertung|
|-----|---|
| Front-Matter | nein |
| Umfang | ja |
| Belege | ja |
| Links | ja |
| Formatierung | ja |
| Verlinkungen vorhanden | ja |
| Abbildungen | ja |
| Strukturierung des Beitrags | 10 |
| Rechtschreibung | 10 |
| Sprache | 10 |
| Inhalt | 10 |
| Einordnung in den Kontext | 10 |
| Ansprechend für Zielgruppe | 10 |

# Zusammenfassung

Siehe Review 1

# Positive Aspekte
1. Rechtschreibung und sprachliche Verbesserungen wurden durchgeführt
2. Überschriftenstrukturierung wurde verbessert (v.a. ab Überschrift 4 wurde untergliedert)
3. Weitere Verlinkungen wurden hinzugefügt (z.B. 4.2 "Risikomatrix" oder bei 3. "Top-Down-Ansatz"

# Negative Aspekte

Leider immer noch kein "Front-Matter" Text hinzugefügt  --> Bitte vergleiche nochmal mit anderen Beiträgen. In diesem Abschnitt (quasi direkt unter der Tabelle ganz oben, bei der du Titel, tags, author usw. festlegst) musst du dein Thema kurz zusammenfassend in 1-2 Sätzen darstellen.

2022-01-17 17:27 UTC, GEDA9263 reviewed
| Kriterium | Bewertung|
|-----|---|
| Front-Matter |nein|
| Umfang |ja|
| Belege |ja |
| Links |ja|
| Formatierung |ja|
| Verlinkungen vorhanden | ja |
| Abbildungen | ja |
| Strukturierung des Beitrags | 10 |
| Rechtschreibung | 10|
| Sprache | 10 |
| Inhalt | 10|
| Einordnung in den Kontext | 10 |
| Ansprechend für Zielgruppe | 10 |

# Zusammenfassung

Siehe erstes Review

# Positive Aspekte

Der Beitrag ist entsprechend verbessert worden und nun gibt es fast nichts mehr auszusetzen.

# Negative Aspekte

Einziger negativer Aspekt, die initialen Sätze des Front-Matters fehlen noch, diese evtl. noch ergänzen.

2022-01-21 09:43 UTC, JanEhrFAU requested changes
| Kriterium | Bewertung|
|-----|---|
| Front-Matter | nein |
| Umfang | ja |
| Belege | ja |
| Links | ja |
| Formatierung | ja |
| Verlinkungen vorhanden | ja |
| Abbildungen | ja |
| Strukturierung des Beitrags | 10 |
| Rechtschreibung | 10 |
| Sprache | 10 |
| Inhalt | 10 |
| Einordnung in den Kontext | 10 |
| Ansprechend für Zielgruppe | 10 |

# Zusammenfassung

Siehe erstes Review 

# Positive Aspekte

Auf viele Bemerkungen wurde eingegangen und Fehler wurden verbessert. Insgesamt ein gelungener Beitrag.

# Negative Aspekte

- Front-Matter Einführung fehlt; außerdem eventuell Tags bearbeiten, wen nur der klassische
und nicht der agile Teil behandelt wird
- Am Anfang von 3. ist Risikomanagement getrennt geschrieben. Falls das in der genannten Norm so steht, passt das natürlich, falls nicht würde ich es an die andere Schriftweise anpassen
- An manchen Stellen ist zwischen dem letzten Wort und der Fußnote und an manchen nicht; auch das würde ich einheitlich machen

2022-01-25 13:57 UTC, merged