PMBOK-Guide
ManagingProjectsSuccessfully/ManagingProjectsSuccessfully.github.io pull request #467
Opened 2021-12-21 13:47 UTC by FerYilm

2022-01-17 15:44 UTC, tcansel requested changes
| Kriterium | Bewertung|
|-----|---|
| Front-Matter | ja |
| Umfang | ja|
| Belege | ja |
| Links | ja|
| Formatierung | ja|
| Verlinkungen vorhanden | ja |
| Abbildungen | ja |
| Strukturierung des Beitrags | 10 |
| Rechtschreibung | 10|
| Sprache | 10 |
| Inhalt | 10|
| Einordnung in den Kontext | 10|
| Ansprechend für Zielgruppe | 10|

# Zusammenfassung

Der Artikel befasst sich mit dem Thema PMBOK-Guide. Dabei handelt es sich um ein Nachschlagwerk des PMI. Die Autorin geht zunächst auf den Aufbau des PMBOK-Guides ein. Dieses wird anschließend in Inhalt des Standards und in Inhalt des Leitfadens unterteilt und nähergebracht.

# Positive Aspekte

* inhaltlich ist der Artikel verständlich
* der Artikel ist sehr gut strukturiert
* Belege und Verlinkungen funktionieren
* Tabelle & Abbildung vorhanden

# Negative Aspekte

keine

2022-01-18 18:42 UTC, Quapoapo approved these changes
| Kriterium | Bewertung|
|-----|---|
| Front-Matter | ja |
| Umfang | ja |
| Belege | ja |
| Links | ja |
| Formatierung | ja |
| Verlinkungen vorhanden | ja |
| Abbildungen | ja |
| Strukturierung des Beitrags | 10 |
| Rechtschreibung | 10 |
| Sprache | 10 |
| Inhalt | 10 |
| Einordnung in den Kontext | 10 |
| Ansprechend für Zielgruppe | 10 |

# Zusammenfassung

Der Artikel befasst sich mit dem Thema PMBOK-Guide. Zunächst wird das Thema definiert und das Datum der Erstveröffentlichung genannt. Daraufhin wird auf den Aufbau und auf die Themenbereiche des PMBOK-Guides eingegangen. Der Inhalt des Standards wir ebenfalls dargelegt. Abschließen werden Grundsätze und Aufgaben des Guides aufgezeigt. 

# Positive Aspekte

Zunächst ein Mal ist es gut, dass genannt wurde wann die Erstveröffentlichung des Handbuchs stattgefunden hat. Die Definition zeigt auf wie dieser Guide im Projektmanagement genutzt wird. Passend gewählt ist als ersten Punkt den Aufbau aufzuführen. Noch dazu wurde berichtet welche Themen sich in der aktuellen Ausgabe im Gegensatz zu älteren Ausgaben geändert haben. Die Links zu anderen Themen funktionieren und sind gut im Text integriert. Mit einer Abbildung wurde außerdem das Wertlieferungssystem aufgezeigt. Noch dazu war es sehr hilfreich, dass sowohl das System for Value Delivery als auch die Projekt Management Principles aufgezeigt und beschrieben wurden. Die Kritik wurde sehr gut angenommen und umgesetzt. Der Beitrag ist nun viel angenehmer zu lesen und alle Verlinkungen funktionieren nun richtig. Ebenfalls wurde die Rechtschreibung verbessert. Es gibt nichts mehr auszusetzen und den Beitrag kann man als sehr gelungen bezeichnen.  

# Negative Aspekte

2022-01-18 21:34 UTC, thujavanj commented
| Kriterium | Bewertung|
|-----|---|
| Front-Matter | ja |
| Umfang | ja|
| Belege | ja|
| Links | ja|
| Formatierung | ja|
| Verlinkungen vorhanden | ja|
| Abbildungen | ja|
| Strukturierung des Beitrags | 10 |
| Rechtschreibung | 10|
| Sprache | 9 |
| Inhalt | 10|
| Einordnung in den Kontext | 10|
| Ansprechend für Zielgruppe | 10|

# Zusammenfassung

Der Artikel befasst sich mit dem PMBOK Guide. Dabei handelt es sich, ähnlich wie ein Scrum Guide, um eine Anleitung/ Nachschlagewerk für  das klassische Projektmanagement. Der Autor geht in dem Artikel darauf ein, wie die neuste Ausgabe gegliedert ist und geht zudem auf die einzelnen Themen grob ein. 

# Positive Aspekte
* Die von mir im letzten Review kritisierten Absätze lassen sich wesentlich einfacher lesen (Tailoring, Project Management Principles)
* lange Sätze wurden umformuliert und sind so einfacher zu verstehen
* es sind mehr Verlinkungen vorhanden als vorher 


# Negative Aspekte

2022-01-22 20:40 UTC, thujavanj reviewed
| Kriterium | Bewertung|
|-----|---|
| Front-Matter | ja |
| Umfang | ja|
| Belege | ja|
| Links | ja|
| Formatierung | ja|
| Verlinkungen vorhanden | ja|
| Abbildungen | ja|
| Strukturierung des Beitrags | 10 |
| Rechtschreibung | 10|
| Sprache | 9 |
| Inhalt | 10|
| Einordnung in den Kontext | 10|
| Ansprechend für Zielgruppe | 10|

# Zusammenfassung

Der Artikel befasst sich mit dem PMBOK Guide. Dabei handelt es sich, ähnlich wie ein Scrum Guide, um eine Anleitung/ Nachschlagewerk für  das klassische Projektmanagement. Der Autor geht in dem Artikel darauf ein, wie die neuste Ausgabe gegliedert ist und geht zudem auf die einzelnen Themen grob ein. 

# Positive Aspekte
* Die von mir im letzten Review kritisierten Absätze lassen sich wesentlich einfacher lesen (Tailoring, Project Management Principles)
* lange Sätze wurden umformuliert und sind so einfacher zu verstehen
* es sind mehr Verlinkungen vorhanden als vorher 


# Negative Aspekte

2022-01-25 13:57 UTC, merged