Barcamp Methode und V-Modell (Überarbeitet)
ManagingProjectsSuccessfully/ManagingProjectsSuccessfully.github.io pull request #469
Opened 2021-12-21 14:02 UTC by fabriGH

2022-01-18 11:25 UTC, ebressel requested changes
| Kriterium | Bewertung|
|-----|---|
| Front-Matter | ja |
| Umfang | ja|
| Belege | ja |
| Links | ja|
| Formatierung | ja|
| Verlinkungen vorhanden | ja |
| Abbildungen | ja|
| Strukturierung des Beitrags | 10 |
| Rechtschreibung | 10|
| Sprache | 10 |
| Inhalt | 10|
| Einordnung in den Kontext | 10|
| Ansprechend für Zielgruppe | 10|

# Zusammenfassung
Der Artikel behandelt das Thema von "Barcamps". Das Thema wird mit einer Abbildung von Teilnehmenden der Veranstaltung eingeleitet. Im Bezug zu diesem Thema wird der Begriff geklärt und der Allgemeine Ablauf dieser Moderationsmethode augezeigt, welcher in 5 Schritten erfolgt. Danach wird auf die Vor und Nachteile der Barcamps anhand einer Tabelle eingegangen und zusätzlich die No-Gos hervorgehoben. Abgerundet wird der Artikel mit ein paar zusätzlichen "Facts" "Gut zu Wissen".

# Positive Aspekte
Den Artikel finde ich nun wirklich top, von der Struktur zum Inhalt finde ich alles super. Man bekommt einen guten Einblick in das Thema trotz der "nur" 500 Wörter als Umfang. 

# Negative Aspekte
Jetzt sind mir keine negativen Aspekte mehr aufgefallen :)

2022-01-18 11:38 UTC, ebressel requested changes
| Kriterium | Bewertung|
|-----|---|
| Front-Matter | ja |
| Umfang | nein|
| Belege | ja |
| Links | ja|
| Formatierung | ja|
| Verlinkungen vorhanden | ja |
| Abbildungen | ja|
| Strukturierung des Beitrags | 10 |
| Rechtschreibung | 10|
| Sprache | 10 |
| Inhalt | 10|
| Einordnung in den Kontext | 10|
| Ansprechend für Zielgruppe | 10|

# Zusammenfassung

Der Artikel behandelt das Thema "V-Modell. Es dient dazu, ein Projekt in einzelnen Phasen zu intensiv testen, um allgemein die Entwicklung des Projektes effizient zu unterstützen. Das VModell wird im weiteren Verlauf des Artikels detaillierter beschrieben, indem auf alle Teil-Phasen genauer eingegangen wird, indem jeweils erklärt wird, was in dieser Phase erarbeitet wird und welche Fragen geklärt werden. Danach wird auf die Vor- und Nachteile der VMethode anhand einer Tabelle eingegangen. Abgerundet wird der Artikel mit der Nennung der Anwendungsbereiche und einem  Einblick in die Weiterentwicklung des VModells. 

# Positive Aspekte

Noch immer finde ich es super, dass eine Abbildung zu der Struktur und des Aufbaus der Methode eingebettet wurde. So kann man sich die Vorgehensweise als Leser deutlich besser vorstellen. Alle negativen Aspekte des vorgherigen Reviews wurden ausgebessert (zB: wurde zum Schluss noch auf "Weiterentwicklung" eingegangen und die genannten Rechtschreibfehler ausgebessert), deshalb habe ich nichts anzumerken. Auch Allgemein ist die Struktur des Beitrags wirklich übersichtlich und man wird easy durch die Theamtik geführt.
Auch finde ich es super, dass auch auf die Unter/teilphasen genauer eingegangen wurde. Hier fand ich es besonders gut, wenn die Fragen genannt wurden, die es in der jeweiligen Phase zu klären gab.

# Negative Aspekte

Ist alles super! :)

2022-01-18 14:12 UTC, Lui03 requested changes
| Kriterium | Bewertung|
|-----|---|
| Front-Matter | ja |
| Umfang | ja |
| Belege |nein |
| Links | ja |
| Formatierung | ja |
| Verlinkungen vorhanden | ja |
| Abbildungen | ja |
| Strukturierung des Beitrags | 8 |
| Rechtschreibung | 7|
| Sprache | 8 |
| Inhalt | 8 |
| Einordnung in den Kontext | 9 |
| Ansprechend für Zielgruppe | 10 |

# Zusammenfassung
Die Moderationsmethode „Barcamp“ ist ein Zusammentreffen von bis zu mehreren Hundert Menschen aus den unterschiedlichsten Bereichen eines Unternehmens. Während der 5 Phasen, welche die Teilnehmer:innen durchlaufen, sollen Probleme gelöst und innovative Ideen gesammelt werden.
Wichtig ist, dass die Moderator:innen den Teilnehmern:innen blind vertrauen und das Organisations-Team zur Unterstützung bereitsteht.
Begonnen wird mit der Eröffnungsrunde, bei der jeder ermutigt werden soll, sein Potenzial auszuschöpfen, um seinen Beitrag zu leisten.
Anschließend beginnt die Themenfindung und Sessionplanung. Hier werden Themen zusammengetragen, die das Interesse wecken. Als Nächstes folgt der Sessionstart. Die Sessions erfolgen zeitgleich oder nacheinander und die Teilnehmer:innen wechseln selbstständig zwischen den Themen für bestmöglichen Erfolg. Der Abschluss eines effizienten Barcamps erfolgt erst, nachdem alle Themen abgearbeitet wurden. Nach dem Barcamp werden die Ergebnisse zusammengefasst und zum Beispiel in Form einer Software-Lösung für jeden zugänglich gemacht.
Nachteile hierbei könnten zum einen der Kosten- und Zeitaufwand darstellen und die Unstimmigkeiten zwischen den Teilnehmer:innen. Zu den Vorteilen gehören jedoch die erstaunlichen Ergebnisse und die Abwechslung für die Mitarbeiter:innen.
# Positive Aspekte
Bezogen auf mein letztes Review zu diesem Beitrag wurden die positiven Aspekte alle beibehalten. Zusätzlich kam noch dazu, dass der Kritikpunkt „fehlende Verlinkungen zu angrenzenden Themengebiete und Beiträgen aus dem Kompendium“ gut umgesetzt wurde, da ein Beitrag aus dem Kompendium im Text verlinkt wurde und noch zusätzlich dazu passende Beiträge aufgezählt wurden.
# Negative Aspekte
Leider sind mir immer noch ein paar negative Aspekte aufgefallen. Zum einen fehlt immer noch ein Beleg zu dem Punkt „Vor und Nachteile von Barcamps“, da hier keine Quelle verlinkt wurde. 
Auch bezüglich der Rechtschreibung und Grammatik sind mir immer noch Fehler aufgefallen, beispielsweise wurde sehr oft „das“ anstatt „dass“ geschrieben und ein paar Kommas fehlen ebenfalls (ca. 5). 
Inhaltlich wurde meine Frage bezüglich der Themenzusammenführung weder als Kommentar beantwortet noch inhaltlich so verbessert, dass es für mich verständlich wurde.
Generell wurde inhaltlich meines Erachtens, fast nichts verändert, weswegen ich bei meiner Bewertung nicht viel verändern konnte.

2022-01-19 09:42 UTC, Nikleldi approved these changes
| Kriterium | Bewertung|
|-----|---|
| Front-Matter | ja |
| Umfang | ja|
| Belege | ja|
| Links | ja|
| Formatierung | ja|
| Verlinkungen vorhanden | ja |
| Abbildungen | ja/ nein |
| Strukturierung des Beitrags | 10 |
| Rechtschreibung | 10|
| Sprache | 10 |
| Inhalt |10|
| Einordnung in den Kontext |10|
| Ansprechend für Zielgruppe |10|

# Zusammenfassung

Der Artikel handelt von der Moderationsmethode Barcamp. Der Artikel ist aufgebaut aus einer Begriffserklärung, dem allgemeinen Ablauf von Barcamps, Vor- und Nachteilen, No Gos, einem Gut zu wissen Abschnitt und der weiterführenden Literatur beziehungsweise den Quellen.
Ein Barcamp ist eine Moderationsmethode, besonders geeignet für 24-100 Teilnehmer, mit dem Ziel Probleme zu lösen oder Innovationen zu provozieren. Klassischerweise werden dabei Menschen aus verschiedensten Bereichen (Unternehmensabteilungen, Forschungsgruppen, etc.) zusammen getan.
Vorteile des Barcamp sind zum einen erstaunliche Ergebnisse, eine Entfaltung und Abwechslung der Teilnehmer und die Tatsache, dass es sich um eine Teambuilding Maßnahme handelt.
Nachteile hingegen sind der Kosten/Zeitaufwand, zum Teil unmotivierte Teilnehmer, ein ungeordneter Ablauf und etwaige Unstimmigkeiten zwischen den Teilnehmern.

No-Goes sind vordefinierte Themen, Abwählen von Themen ( bei zu geringer Interesse), Anpassen von Themen durch den Barcamp-Moderator, Moderation der Sessions durch das Orga-Team, Dokumentation der Sessions durch das Orga-Team, Aufnahmen der Sessions und der Ausschluss von Personen.

# Positive Aspekte

Bensonders positiv sind die bereits genannten Punkte: Der Artikel ist leicht leserlich und bietet einen sehr guten Überblick über die Barcamp Methode. Er ist zudem gut strukturiert und sehr interessant. Besonders gut ist die Tabelle, da hier ein genauer Überblick über die Vor-und Nachteile geboten wird. Es ist klar zu erkennen, dass sich der Autor ausführlich mit der Materie beschäftigt hat. Die Tatsache, dass Videomaterial als Teil der weiterführenden Literatur aufgeführt wird ist ebenfalls sehr stimmig und in jedem Fall sehr passend für die Zielgruppe (Studenten).
Der Artikel ist nun komplett und es gibt nichts zu bemängeln.

# Negative Aspekte

Auf die Kritik wurde reagiert und mir sind keine weiteren negativen Punkte aufgefallen.

2022-01-19 09:58 UTC, Nikleldi approved these changes
| Kriterium | Bewertung|
|-----|---|
| Front-Matter | ja |
| Umfang | ja|
| Belege | ja |
| Links | ja|
| Formatierung | ja|
| Verlinkungen vorhanden | ja |
| Abbildungen | ja |
| Strukturierung des Beitrags |10 |
| Rechtschreibung |10|
| Sprache | 10 |
| Inhalt | 10|
| Einordnung in den Kontext | 10|
| Ansprechend für Zielgruppe |10|

# Zusammenfassung

Der Artikel handelt vom "V-Modell", einem Vorgehensmodell aus dem Projektmanagement, welche ursprünglich aus der Softwareentwicklung stammt. Mit dem V-Modell wird ein Projekt in verschiedene Phasen aufgeteilt, getestet, integriert und wieder zusammengefügt.
Ziel ist es, die Entwicklung des Projekts zu fördern. Eine Abbildung zeigt, wie die verschiedenen Phasen aussehen.
Das V-Modell wird im weiteren Verlauf des Artikels detaillierter beschrieben, indem auf alle Teil-Phasen (Entwurfphase, Implementierungsphase, Test und Validierungsphase) näher eingegangen wird. Darin werden die phasenzugehörigen Tests und Spezifikationen erklärt.
Abschließend werden in Form einer Tabelle die Vor -und Nachteile des V-Modells aufgezeigt und abgeschlossen wird der Text mit einer Aufzählung der Anwendungsbereiche.

# Positive Aspekte

Der Beitrag ist nach wie vor gut geschrieben und übersichtlich gestaltet. Als Leser ohne Vorkenntnisse kann man sich ein gutes Verständnis über das Modell aneignen. Besonders geeignet ist hierbei die Abbildung, da diese den Inhalt passend visualisiert. Die Struktur ist sehr gut und man bekommt leicht verständlich einen Überblick über die Methode.
Die negativen Kritikpunkte wurden ausgebessert.

# Negative Aspekte

Keine Kritikpunkte.

2022-01-25 13:57 UTC, merged