Hive_PM & Stand_Ups
ManagingProjectsSuccessfully/ManagingProjectsSuccessfully.github.io pull request #47
Opened 2021-11-13 11:30 UTC by Gilchus

First final Version of both topics. 
Hive_PM for classic PM.
Stand_Ups for agile PM.

2021-11-26 12:52 UTC, ChrisBohl requested changes
| Kriterium | Bewertung|
|-----|---|
| Front-Matter | ja |
| Umfang | ja|
| Belege | ja |
| Links | ja|
| Formatierung | nein????|
| Verlinkungen vorhanden | ja |
| Abbildungen | ja |
| Strukturierung des Beitrags | 10 |
| Rechtschreibung | 10|
| Sprache | 10 |
| Inhalt | 10|
| Einordnung in den Kontext | 10|
| Ansprechend für Zielgruppe | ???|

#Ich hatte das Problem (das kann aber auch nur an mir liegen?), 
dass ich nicht die formatierte Version, sondern nur die RAW-Version einsehen konnte. Dementsprechend konnte ich die Abbildungen nur in den files nachsehen. Darum versuch ich weitestgehend -insofern dies möglich- den Inhalt zu reviewen.

# Zusammenfassung

Das Hive PM Tool ist ein plattformbasiertes (und ai-basiertes?) Projektmanagementtool zur Verbesserung der Produktivität und des Prozessmanagements. Es stellt den Nutzern ein intuitiv anwendbares Dashboard zur Verfügung, dass ihnen ihr Aufgaben- und Zeitmanagement vereinfacht. Weiterhin werden verschiedene Apps von Drittanbietern zur Verfügung gestellt, um eine möglichst einfache Kollaboration von Content auf der Plattform zu gewährleisten.

# Positive Aspekte

Der Artikel setzt sich umfangreich und vertiefend mit einem komplexen PM Tool auseinander, und ich finde, dass das gut strukturiert und qualitativ gehaltvoll vollzogen worden ist. Eine sehr schöne Arbeit.

# Negative Aspekte

Die Verlinkung zu anderen Artikeln könnten noch etwas "bunter" ausgestaltet sein. 
Falls das Problem mit der Formatierung nicht an mir liegt, wäre das noch ein Punkt in diesem Segment.

2021-11-26 16:10 UTC, TommiMueller requested changes
Genau wie bei ChrisBohl ist es mir nur möglich die Raw-Datei einzusehen. Daher würde ich empfehlen dieses Problem erst zu beheben, bevor ich meinen Review abgebe.
Ein reibungsloser Review-Prozess ist meiner Meinung nach nämlich nur anhand der Raw-Datei schwer möglich.

2021-11-26 17:31 UTC, TommiMueller requested changes
| Kriterium | Bewertung|
|-----|---|
| Front-Matter | ja |
| Umfang | nein|
| Belege | nein |
| Links | nein|
| Formatierung | nein|
| Verlinkungen vorhanden | nein |
| Abbildungen | ja |
| Strukturierung des Beitrags | 7 |
| Rechtschreibung | 8|
| Sprache | 9 |
| Inhalt | 10|
| Einordnung in den Kontext | 5|
| Ansprechend für Zielgruppe | 7|

# Zusammenfassung

Das Hive PM Tool lässt Projekte zentralisiert und Cloud basiert mittels einer Software verwalten. Auf dem **Dashboard** kann der Nutzer seine Aktivitäten einsehen. Hive lässt sich mit vielen Drittanbieter Softwares verbinden (Beispielsweise der Mail-Adresse).  Es ist ein übersichtliches Tool, welches sich benutzerspezifisch einstellen lässt. 
Es ist in unterschiedlichen Preiskategorien erhältlich.

# Positive Aspekte

- Ausführlich und verständlich erklärt.
- Gute Struktur
- Im Wikipedia-Stil geschrieben
- Tabelle eingefügt


# Negative Aspekte

- Abbildungen werden nicht richtig angezeigt
- Bei Quellen wurde nur Link eingefügt und kein Name
- Links zu **Gantt** und **Kanban** funktionieren nicht
- Groß- und Kleinschreibung, sowie Zeichensetzung ist an manchen Stellen noch falsch.
- Abbildungen ohne Quellenangabe
- Viele Sätze sind nicht mit einer Fußnote versehen
- Es wird kaum Bezug zu Themen anderer Beiträge genommen und es wurden auch keine anderen Beiträge im Text verlinkt. Man könnte beispielsweise im Abschnitt *Preiskategorien* einen Link zum Beitrag zu **Projekten** schalten
- Der Text ist etwas zu lang, aber Martin meinte ja das geht in Ordnung.

2021-11-28 16:16 UTC, eddq2000 commented
Hallo,

ich finde irgenwie keinen der beiden Beiträge...

Könnte mir da jemand weiterhelfen, wo ich die finde?

2021-12-09 19:22 UTC, merged