Projektstart
ManagingProjectsSuccessfully/ManagingProjectsSuccessfully.github.io pull request #471
Opened 2021-12-21 15:20 UTC by samed1907

2022-01-12 17:56 UTC, Philip290899 requested changes
| Kriterium | Bewertung|
|-----|---|
| Front-Matter | ja |
| Umfang | ja |
| Belege | ja |
| Links | ja |
| Formatierung | ja |
| Verlinkungen vorhanden | ja |
| Abbildungen | ja |
| Strukturierung des Beitrags | 8 |
| Rechtschreibung | 8 |
| Sprache | 7 |
| Inhalt | 8 |
| Einordnung in den Kontext | 8 |
| Ansprechend für Zielgruppe | 8 |

# Zusammenfassung

Zu Beginn wird der Begriff Projektstart definiert. Der Start eines Projektes wird in die Bereiche Auftragsklärung, Zieldefinierung, Verantwortlichkeiten und Kosten-/Terminplanung eingeteilt. Im nächsten Schritt wird die Vorgehensweise und Planung eines Projektes erläutert. Zu den wichtigsten Faktoren zählen hierbei: Projektstruktur, Pakete und Maßnahmen, Kick-Off und Bottom Up/Top Down. Danach werden die fünf verschiedenen Projektphasen (Vorbereiten, Initiieren, Planen, Steuern und Abschließen) erklärt. Als letztes werden die Einflüsse auf Projekte offengelegt. Dies wird durch die Umweltanalyse ermöglicht.


# Positive Aspekte

Gute, detaillierte Zusammenfassung deines Themas. 842 Wörter sind ziemlich viel. Abbildungen sind vorhanden, jedoch fehlen dazu in dieser Version zwei Quellenangaben. Nachdem man die Quellenangaben der Abbildungen und alle funktionierenden Links in der ersten Version nachschauen kann, habe ich in der Tabelle trotzdem zweimal "Ja" angegeben. Die Formatierungen sorgen für eine gute Struktur. Punktelisten und Überschriften sind vorhanden.

# Negative Aspekte

Die Datei Projektstart.md ist im falschen Ordner. Die Datei sollte in den Ordner "kb" und nicht in "Verwaltung". Die Abbildungen fehlen ebenfalls im Ordner (der Ordner ohne die Endung .md). Zu zwei der drei Abbildungen sind in dieser Version keine Quellenangaben mehr vorhanden.
  
Sprachlicher Ausdruck: 
* "Das Thema "Projektstart" kann man **definieren als dem** "Termin, zu dem der Lenkungsausschuss den Beginn des Projekts genehmigt.""
* "Wie schon oben erwähnt stellt sich zunächst die Frage, wie man überhaupt **ein** Projekt beginnt."
* "Um die Wünsche des Auftraggebers zu **treffen** und Auseinandersetzungen..."
* "...Der Projektstatus sollte regelmäßig ausgetauscht werden. Um Innovationen..."
* "...in einzelne Maßnahmen eingeteilt..."
*  "...Risiken identifiziert und das Team zusammengestellt.  ..."
* "...geplant und festgehalten.  ..."
* "...**der** Umfeld eines Projekts..."
* "...**Z.b**....,stattdessen z.B."
* Bei Siehe auch: "Projektabschluss"

Leerzeichen nach dem Punkt: z.B.: "...sowie Sachmittel.Der Projektstatus sollte..." 
Die Verlinkungen "Umfeldanalyse" und "Auftragsklärung" sollten im Text nicht auf externe Internetseiten führen, sondern nur innerhalb des Kompendium.
Achte bei den direkten Zitaten auf die richtige Zitierweise. Außerdem sollte man mit direkten Zitaten eher sparsam sein und nur verwenden, wenn es wirklich sehr wichtig ist.
Bei der Weiterführenden Literatur auf Leerzeichen achten.
Die dritte Quelle funktioniert in der finalen Version nicht mehr.

**Update**: Leider wurden nicht alle Kritikpunkte vollständig umgesetzt.

2022-01-14 13:30 UTC, efdil commented
| Kriterium | Bewertung|
|-----|---|
| Front-Matter | ja |
| Umfang | ja|
| Belege | ja |
| Links | ja|
| Formatierung | ja|
| Verlinkungen vorhanden | ja|
| Abbildungen | ja |
| Strukturierung des Beitrags | 10 |
| Rechtschreibung | 8|
| Sprache | 9 |
| Inhalt |10|
| Einordnung in den Kontext | 10|
| Ansprechend für Zielgruppe |10|

# Zusammenfassung

Im Artikel wird erläutert, was unter dem Beginn eines Projekts zu verstehen ist und fasst dies kurz und sachlich zusammen. Unter Projektstart, ist dementsprechend der Termin, wobei der Beginn des Projekts durch einen Vorstand genehmigt wird gemeint. Dabei wird auch erklärt wie man ein Projekt beginnt, wie man bei der Planung vorgehen sollte, welche Phasen dabei durchgegangen werden müssen und welche potenziellen Einflüsse es im Projektstart geben kann.

# Positive Aspekte

Dass die Abgabe im falschen Ordner war  wurde behoben indem es dem richtigen Ordner zugeordnet wurde.
Abbildungen wurden ebenfalls in kb zugeordnet.

Es wurden mehr Verlinkungen ins interne Kompendium hinzugefügt.

# Negative Aspekte

Rechtschreibung wurde nach erstem Review überarbeitet, jedoch nicht ausreichend.
Rechtschreibung: Es haben sich ganz kleine, aber im ganzen Text verteilte Schreibfehler eingeschlichen. (Bspw: Wie der Name schon sagt wird der Umnfeld eines Projekts...  oder  ...wie man überhaupt einen Projekt... ) Daher am besten kurz den ganzen Text überfliegen. Duden Korrektur oder MS Word kann man dazu auch gut anwenden.

2022-01-14 13:33 UTC, efdil requested changes
| Kriterium | Bewertung|
|-----|---|
| Front-Matter | ja |
| Umfang | ja|
| Belege | ja |
| Links | ja|
| Formatierung | ja|
| Verlinkungen vorhanden | ja|
| Abbildungen | ja |
| Strukturierung des Beitrags | 10 |
| Rechtschreibung | 8|
| Sprache | 9 |
| Inhalt |10|
| Einordnung in den Kontext | 10|
| Ansprechend für Zielgruppe |10|

# Zusammenfassung

Im Artikel wird erläutert, was unter dem Beginn eines Projekts zu verstehen ist und fasst dies kurz und sachlich zusammen. Unter Projektstart, ist dementsprechend der Termin, wobei der Beginn des Projekts durch einen Vorstand genehmigt wird gemeint. Dabei wird auch erklärt wie man ein Projekt beginnt, wie man bei der Planung vorgehen sollte, welche Phasen dabei durchgegangen werden müssen und welche potenziellen Einflüsse es im Projektstart geben kann.

# Positive Aspekte

Dass die Abgabe im falschen Ordner war  wurde behoben indem es dem richtigen Ordner zugeordnet wurde.
Abbildungen wurden ebenfalls in kb zugeordnet.

Es wurden mehr Verlinkungen ins interne Kompendium hinzugefügt.

# Negative Aspekte

Rechtschreibung wurde nach erstem Review überarbeitet, jedoch nicht ausreichend.
Rechtschreibung: Es haben sich ganz kleine, aber im ganzen Text verteilte Schreibfehler eingeschlichen. (Bspw: Wie der Name schon sagt wird der Umnfeld eines Projekts...  oder  ...wie man überhaupt einen Projekt... ) Daher am besten kurz den ganzen Text überfliegen. Duden Korrektur oder MS Word kann man dazu auch gut anwenden.

2022-01-18 13:02 UTC, AbderrahmaneBennani requested changes
| Kriterium | Bewertung|
|-----|---|
| Front-Matter | ja |
| Umfang | ja |
| Belege | ja |
| Links | ja |
| Formatierung | ja |
| Verlinkungen vorhanden | ja |
| Abbildungen | ja |
| Strukturierung des Beitrags | 10 |
| Rechtschreibung | 7|
| Sprache | 9 |
| Inhalt | 10|
| Einordnung in den Kontext | 10|
| Ansprechend für Zielgruppe | 10|

# Positive Aspekte
Die Verlinkungen ins Kompendium und Gute Artikelstruktur fand ich toll.

# Negative Aspekte
Es gibt noch ein paar Rechtschreibfehler.

2022-01-25 13:57 UTC, merged