Aktualisierte Version Provokationstechnik
ManagingProjectsSuccessfully/ManagingProjectsSuccessfully.github.io pull request #473
Opened 2021-12-21 15:29 UTC by Nikleldi

- Verlinkungen zu anderen Beiträge eingefügt
- Einordnung in Kontext Projektmanagment hinzugefügt
- Rechtschreibung korrigiert
- unwichtige Inhalte gekürzt
- Sprache verbessert
- ähnliche Themen zu "siehe auch" hinzugefügt

2022-01-15 15:25 UTC, Lars428 requested changes
| Kriterium | Bewertung|
|-----|---|
| Front-Matter | ja |
| Umfang | ja |
| Belege | ja |
| Links | ja |
| Formatierung | ja |
| Verlinkungen vorhanden | ja |
| Abbildungen | ja |
| Strukturierung des Beitrags | 10 |
| Rechtschreibung | 10 |
| Sprache | 10 |
| Inhalt | 10 |
| Einordnung in den Kontext | 10 |
| Ansprechend für Zielgruppe | 10 |

# Zusammenfassung

Der Artikel befasst sich mit dem Thema Provokationstechnik auch als Mentale Provokation bezeichnet. Diese Methode wird zur Ideenfindung genutzt. Es sollen bestehende Annahmen und Sichtweisen hinterfragt werden, um neue Ideen zu generieren. Um keine Ablehnung zu erzeugen empfiehlt es sich die Provokation immer anzukündigen, indem man das Wort PO voranstellt. Vorteile sind, dass alte Denkmuster durchbrochen werden und dass die Kreativität angeregt wird. Nachteile sind, dass der Umgang mit Provokationen Menschen zu Anfang sehr schwer fallen können und dass die provokation oft zu weit von der Realität entfernt ist.

# Positive Aspekte

Alle Verbesserungsvorschläge wurden umgesetzt.

# Negative Aspekte

Mir sind keine negativen Aspekte mehr aufgefallen.

2022-01-18 13:47 UTC, Lui03 requested changes
| Kriterium | Bewertung|
|-----|---|
| Front-Matter | ja |
| Umfang | ja |
| Belege  |ja |
| Links | ja |
| Formatierung | ja |
| Verlinkungen vorhanden | ja |
| Abbildungen | ja |
| Strukturierung des Beitrags | 10 |
| Rechtschreibung | 8|
| Sprache | 10 |
| Inhalt | 10 |
| Einordnung in den Kontext | 9 |
| Ansprechend für Zielgruppe | 10 |


# Zusammenfassung
Durch die Erfindung der Provokationstechnik von Edwar Bono, soll es Menschen, beispielsweise in Ideenfindungsworkshops, leichter fallen neue Aspekte in Betracht zu ziehen und Ihnen Anreize schaffen. Diese Art der Provokation nennt sich mentale Provokation. Dies soll jedoch nicht zu unerwünschten Diskussionen führen. Deshalb werden Aussagen, die zu den mentalen Provokationen dienen, mit PO am Anfang des Satzes gekennzeichnet, was im Kontext als „was wäre, wenn…“ interpretiert werden soll. Im Folgenden ein Beispiel:
Alle Lehrer lieben Ihre Schüler
PO Alle Lehrer lieben Ihre Schüler
Was wäre, wenn alle Lehrer Ihre Schüler lieben.
Es gibt sechs unterschiedliche Verfahren, um Provokationen zu generieren.
Annahme aufheben, Idealfall, Umkehrung, Übertreibung, Zufall und Verfälschung.
Der komplexeste Teil nach der Gestaltung einer Provokation ist die Lösungsfindung. Beispiel für eine Lösung, die aus einer Provokation resultiert, ist der Ansatz „PO die Schule hat kein Gebäude“ aus dem die Idee des Homeschoolings entstehen könnte.
Zusammenfassend lässt sich sagen, dass Provokationen die Kreativität anregen, jedoch geschickt eingefädelt werden müssen, um Menschen dadurch nicht zu entmutigen.

# Positive Aspekte
Bezogen auf mein letztes Review zu diesem Beitrag wurden die positiven Aspekte alle beibehalten.
Zusätzlich wurde der Kritikpunkt, dass der Beitrag zu lang sei, inklusive meiner Verbesserungsvorschläge, perfekt umgesetzt, da unnötig viele Beispiele weggelassen wurden, wodurch das Durchlesen des Beitrags viel angenehmer gestaltet wurde.
 Trotz der Verkürzung des Beitrags wurde ebenfalls auf das Hauptthema Projektmanagement eingegangen und ein Beitrag aus dem Kompendium verlinkt, was hier gut gelungen ist, und somit zu einer besseren Einordnung in den Kontext führt.
Der Absatz „Methoden, um Provokationen zu generieren“ ist meiner Meinung nach sehr gut gelungen, da die vielen Ebenen durch Stichpunkte ersetzt wurden und dies nun viel übersichtlicher gestaltet wurde.
Meine Kritikpunkte bezüglich Grammatik und Sprache wurden auch alle Punkte ausgebessert.
Zusammenfassend finde ich, ist der überarbeitete Beitrag sehr gut gelungen und alle wichtigsten Kritikpunkte wurden sehr gut umgesetzt.

# Negative Aspekte
Ein paar kleine Kritikpunkte sind mir noch aufgefallen.
Am Anfang des Beitrags ist immer noch eine Überschrift vorhanden, die hier nicht notwendig war.
Die Rechtschreibung weist leider immer noch Fehler auf. (so genannt  sogenannt; in Frage  infrage; beispielweise  beispielsweise)
Bezüglich der Einordnung in den Kontext habe ich auch nur 9 Punkte gegeben, da im Text nur ein weiterer Beitrag markiert wurde, und unter „Siehe auch“ der Beitrag „Brainstorming“ verlinkt wurde, welcher jedoch nicht geschrieben wurde.

2022-01-18 22:50 UTC, Cari02 requested changes
| Kriterium | Bewertung|
|-----|---|
| Front-Matter | ja|
| Umfang | ja |
| Belege | ja |
| Links | ja |
| Formatierung | ja|
| Verlinkungen vorhanden | ja |
| Abbildungen | ja|
| Strukturierung des Beitrags | 10 |
| Rechtschreibung | 8 |
| Sprache | 9 | 
| Inhalt | 10 | 
| Einordnung in den Kontext | 10 | 
| Ansprechend für Zielgruppe | 10 |

# Zusammenfassung
Der Artikel befasst sich mit der Provokationstechnik und den Nutzen, Methoden und Anwendungen dieser. Eingeführt wurde sie durch Edward de Bono und dient zur Ideenfindung. 
Im Hauptteil wird die Provokation definiert, die für die Ideenfindung von großer Bedeutung ist. Indem festgefahrene Meinungen hinterfragt werden, um neue Anreize und Sichtweisen zu schaffen. Provokationen sollen hierbei Anregungen darstellen, sie werden durch PO am Satzanfang markiert. Daraufhin wird auf den Nutzen eingegangen. Dieser wird mit einer anschaulichen Grafik erklärt und liegt darin neue Dinge zu erwägen, durch Ideenfindungsworkshops können beispielsweise neue Produkte erzeugt werden. Es gibt sechs verschiedene Methoden, um Provokationen herzustellen: Annahme aufheben, Idealfall, Umkehrung, Übertreibung, Zufall und Verfälschung. 
Abschließend wird auf die Anwendung der Provokationstechnik eingegangen, welcher die Lösungsideen beinhaltet, die zum schwersten Teil der Provokationstechnik gehört. 
Abgerundet wird der Artikel mit den Vor- und Nachteilen und dem Fazit zur Provokationstechnik.

# Positive Aspekte
Die Verbesserungsvorschläge des letzten Reviews wurden gut umgesetzt, der Beitrag wurde gekürzt und der Umfang des Artikels stimmt mit der Vorgabe von ca. 500 Wörtern überein. Die Verlinkungen zu anderen Kompendien wurden nachträglich eingefügt, somit kann man das Thema gut in den Kontext einordnen. Durch das Einfügen eines Fazits weist der Artikel eine gute Struktur auf.

# Negative Aspekte
Die Sprache des Artikels ist gut gewählt, jedoch weist der Artikel kleine Fehler bei der Rechtschreibung und Grammatik auf wie: in frage (infrage) oder beispielweise (beispielsweise)

2022-01-19 10:26 UTC, Nikleldi commented
> Kriterium 	Bewertung
> Front-Matter 	ja
> Umfang 	ja
> Belege 	ja
> Links 	nein
> Formatierung 	ja
> Verlinkungen vorhanden 	ja
> Abbildungen 	ja
> Strukturierung des Beitrags 	10
> Rechtschreibung 	8
> Sprache 	10
> Inhalt 	10
> Einordnung in den Kontext 	9
> Ansprechend für Zielgruppe 	10
> # Zusammenfassung
> 
> Durch die Erfindung der Provokationstechnik von Edwar Bono, soll es Menschen, beispielsweise in Ideenfindungsworkshops, leichter fallen neue Aspekte in Betracht zu ziehen und Ihnen Anreize schaffen. Diese Art der Provokation nennt sich mentale Provokation. Dies soll jedoch nicht zu unerwünschten Diskussionen führen. Deshalb werden Aussagen, die zu den mentalen Provokationen dienen, mit PO am Anfang des Satzes gekennzeichnet, was im Kontext als „was wäre, wenn…“ interpretiert werden soll. Im Folgenden ein Beispiel: Alle Lehrer lieben Ihre Schüler PO Alle Lehrer lieben Ihre Schüler Was wäre, wenn alle Lehrer Ihre Schüler lieben. Es gibt sechs unterschiedliche Verfahren, um Provokationen zu generieren. Annahme aufheben, Idealfall, Umkehrung, Übertreibung, Zufall und Verfälschung. Der komplexeste Teil nach der Gestaltung einer Provokation ist die Lösungsfindung. Beispiel für eine Lösung, die aus einer Provokation resultiert, ist der Ansatz „PO die Schule hat kein Gebäude“ aus dem die Idee des Homeschoolings entstehen könnte. Zusammenfassend lässt sich sagen, dass Provokationen die Kreativität anregen, jedoch geschickt eingefädelt werden müssen, um Menschen dadurch nicht zu entmutigen.
> # Positive Aspekte
> 
> Bezogen auf mein letztes Review zu diesem Beitrag wurden die positiven Aspekte alle beibehalten. Zusätzlich wurde der Kritikpunkt, dass der Beitrag zu lang sei, inklusive meiner Verbesserungsvorschläge, perfekt umgesetzt, da unnötig viele Beispiele weggelassen wurden, wodurch das Durchlesen des Beitrags viel angenehmer gestaltet wurde. Trotz der Verkürzung des Beitrags wurde ebenfalls auf das Hauptthema Projektmanagement eingegangen und ein Beitrag aus dem Kompendium verlinkt, was hier gut gelungen ist, und somit zu einer besseren Einordnung in den Kontext führt. Der Absatz „Methoden, um Provokationen zu generieren“ ist meiner Meinung nach sehr gut gelungen, da die vielen Ebenen durch Stichpunkte ersetzt wurden und dies nun viel übersichtlicher gestaltet wurde. Meine Kritikpunkte bezüglich Grammatik und Sprache wurden auch alle Punkte ausgebessert. Zusammenfassend finde ich, ist der überarbeitete Beitrag sehr gut gelungen und alle wichtigsten Kritikpunkte wurden sehr gut umgesetzt.
> # Negative Aspekte
> 
> Ein paar kleine Kritikpunkte habe ich noch, zum Beispiel wurde die 5. Quelle leider immer noch nicht verlinkt. Außerdem ist am Anfang immer noch eine Überschrift vorhanden, die hier nicht notwendig war. Die Rechtschreibung weist leider immer noch Fehler auf. (so genannt  sogenannt; in Frage  infrage; beispielweise  beispielsweise) Des Weiteren ist mir noch aufgefallen, dass hier die Verlinkungen zu anderen Internetseiten falsch umgesetzt wurde. Dies müsste beispielsweise bei „Kreativitätstechniken“ wie folgt aussehen: [Kreativitätstechniken] (https://de.wikipedia.org/wiki/Kreativit%C3%A4tstechniken) . Bezüglich der Einordnung in den Kontext habe ich auch nur 9 Punkte gegeben, da im Text nur ein weiterer Beitrag markiert wurde, und unter „Siehe auch“ der Beitrag „Brainstorming“ verlinkt wurde, welcher jedoch nicht geschrieben wurde.




Vielen Dank für das Feedback!

Ich hab ein paar Fragen zur Kritik:
- Inwiefern wurde die Verlinkung zu anderen Webseiten falsch umgesetzt?
- Die Rechtschreibfehler sind ärgerlich, aber sind 20% Abzug (8/10) bei zwei Formfehlern und einem vergessenen s in einem gesamten Artikel wirklich gerechtfertigt? 
- Die Überschrift ist vorhanden, damit der Artikel dem "Wikepdia Stil ähnelt" wie in der Aufgabenstellung beschrieben
- 9/10 Punkte bei Einordnung in den Kontext finde ich auch ein bisschen unglücklich gewählt, da der Artikel an mehreren Stellen und mit Verlinkung in das Oberthema eingeordnet wird

2022-01-19 10:33 UTC, Nikleldi commented
> Kriterium 	Bewertung
> Front-Matter 	ja
> Umfang 	ja
> Belege 	ja
> Links 	ja
> Formatierung 	ja
> Verlinkungen vorhanden 	ja
> Abbildungen 	ja
> Strukturierung des Beitrags 	10
> Rechtschreibung 	8
> Sprache 	9
> Inhalt 	10
> Einordnung in den Kontext 	10
> Ansprechend für Zielgruppe 	10
> # Zusammenfassung
> 
> Der Artikel befasst sich mit der Provokationstechnik und den Nutzen, Methoden und Anwendungen dieser. Eingeführt wurde sie durch Edward de Bono und dient zur Ideenfindung. Im Hauptteil wird die Provokation definiert, die für die Ideenfindung von großer Bedeutung ist. Indem festgefahrene Meinungen hinterfragt werden, um neue Anreize und Sichtweisen zu schaffen. Provokationen sollen hierbei Anregungen darstellen, sie werden durch PO am Satzanfang markiert. Daraufhin wird auf den Nutzen eingegangen. Dieser wird mit einer anschaulichen Grafik erklärt und liegt darin neue Dinge zu erwägen, durch Ideenfindungsworkshops können beispielsweise neue Produkte erzeugt werden. Es gibt sechs verschiedene Methoden, um Provokationen herzustellen: Annahme aufheben, Idealfall, Umkehrung, Übertreibung, Zufall und Verfälschung. Abschließend wird auf die Anwendung der Provokationstechnik eingegangen, welcher die Lösungsideen beinhaltet, die zum schwersten Teil der Provokationstechnik gehört. Abgerundet wird der Artikel mit den Vor- und Nachteilen und dem Fazit zur Provokationstechnik.
> # Positive Aspekte
> 
> Die Verbesserungsvorschläge des letzten Reviews wurden gut umgesetzt, der Beitrag wurde gekürzt und der Umfang des Artikels stimmt mit der Vorgabe von ca. 500 Wörtern überein. Die Verlinkungen zu anderen Kompendien wurden nachträglich eingefügt, somit kann man das Thema gut in den Kontext einordnen. Durch das Einfügen eines Fazits weist der Artikel eine gute Struktur auf.
> # Negative Aspekte
> 
> Die Sprache des Artikels ist gut gewählt, jedoch weist der Artikel kleine Fehler bei der Rechtschreibung und Grammatik auf wie: in frage (infrage) oder beispielweise (beispielsweise)

Vielen Dank für das Feedback!

Ich habe eine Frage zur Kritik: 
Die Rechtschreibfehler sind ärgerlich, aber 20% Abzug (8/10) bei zwei Formfehlern und einem vergessenen "s" in einem gesamten Artikel scheinen nicht ganz gerechtfertigt zu sein. 
Zumal die Frage weshalb bei Sprache 9/10 bewertet wurde, wenn die Fehler in der Rechtschreibung liegen?

Vielen Dank :)

2022-01-19 20:05 UTC, Lui03 commented
> Vielen Dank für das Feedback!
> 
> Ich hab ein paar Fragen zur Kritik:
> 
> * Inwiefern wurde die Verlinkung zu anderen Webseiten falsch umgesetzt?
> * Wieso wurde dementsprechend bei Links pauschal "Nein" geschrieben? Es sind eindeutig Links vorhanden.
> * Die Rechtschreibfehler sind ärgerlich, aber 20% Abzug (8/10) bei zwei Formfehlern und einem vergessenen s in einem gesamten Artikel scheinen nicht ganz gerechtfertigt zu sein.
> * Die Überschrift ist vorhanden, damit der Artikel dem "Wikepdia Stil ähnelt" wie in der Aufgabenstellung beschrieben.
> * 9/10 Punkte bei Einordnung in den Kontext finde ich auch ein bisschen unglücklich gewählt, da der Artikel an mehreren Stellen und mit Verlinkung in das Oberthema eingeordnet wird.
> 
> Vielen Dank :)

Hallo @Nikleldi :)

Bezüglich der Links habe ich meine Bewertung überarbeitet, da ich nochmal den Beitrag durchgelesen habe und ich dir recht geben muss, dass hier ein "Nein" nicht gerechtfertigt war. Ich habe mir nochmal angeschaut wie die Links eingebaut werden sollten , da ich dies scheinbar Anfangs falsch verstanden habe.
Der Kritikpunkt Rechtschreibung ist meiner Meinung nach jedoch nachvollziehbar, da meine genannten Beispiele für Rechtschreibfehler nicht die einzigen waren, ich jedoch nicht alle aufzählen wollte. Es ging mir allgemein darum, dass die Rechtschreibung nochmal verbessert werden müsste. (Weitere Beispiele: des klassischen Projektmanagement --> des klassischen Projektmanagements, drauf --> darauf, Anwendnung --> Anwendung)
Ebenfalls bezüglich der Einordnung in den Kontext hatte ich es schön gefunden, wenn hier mehr Beiträge aus dem Kompendium im Text verlinkt gewesen wären, da somit nicht nur das Oberthema erwähnt worden wäre, sondern auch weitere Unterthemen, um den Leser auf andere Bereiche zu verweisen. Deswegen habe ich "nur" 9 Punkte gegeben, obwohl ich dies auch schon als eine nahezu perfekte Bewertung empfinde.

Danke dir auch für deinen Kommentar :)
Ich hoffe meine Kritik ist nun nachvollziehbar für dich.

2022-01-19 21:41 UTC, Cari02 commented
> Vielen Dank für das Feedback!
> 
> Ich habe eine Frage zur Kritik: Die Rechtschreibfehler sind ärgerlich, aber 20% Abzug (8/10) bei zwei Formfehlern und einem vergessenen "s" in einem gesamten Artikel scheinen nicht ganz gerechtfertigt zu sein. Zumal die Frage weshalb bei Sprache 9/10 bewertet wurde, wenn die Fehler in der Rechtschreibung liegen?
> 
> Vielen Dank :)

Hallo @Nikleldi 
Vielen Dank für deinen Kommentar!

Ich versuche dir gerne meine Punkte zu erklären.
Die 8 Punkte bei der Rechtschreibung habe ich damit gerechtfertigt, dass sich die aufgezeigten Rechtschreibfehler öfter wiederholt haben. Zudem sind dies nicht die einzigen Fehler in dem Artikel gewesen, nur die häufigsten. 
Weitere wären beispielsweise Mentale (mentale) oder des klassischen Projektmanagement (Projektmanagements)…
Die 9 Punkte bei der Sprache sind immer noch sehr gut, jedoch hast du manchmal die Umgangssprache verwendet, wie zum Beispiel drauf statt darauf. 
Sätze wie: Dabei findet Wirkung der Provokation lediglich im Denken stattfindet. Sind sprachlich auch nicht optimal.

Ich hoffe, dass ich es dir verständlich erklären konnte. :)

2022-01-25 13:57 UTC, merged