Risikomatrix und KI_Software_fuer_Projektmanagement 2.0
ManagingProjectsSuccessfully/ManagingProjectsSuccessfully.github.io pull request #475
Opened 2021-12-21 15:47 UTC by Aseuc

2021-12-23 10:43 UTC, Aseuc commented
Ich danke allen Reviewern für die konstruktive Kritik an meinen Beiträgen.
- Ich habe versucht alle negativen Aspekte an meinen Beiträgen zu beseitigen, außer beim Inhalt und Einordnung in den Kontext ist es natürlich nicht möglich die ganzen Beiträge neu zu schreiben, weil dann evtl. neue Fehler auftreten könnten. 
- Zu der weiterführenden Literatur habe ich versucht mich an einem Zitierstil zu orientieren. 
- Da mehrere von euch meinten, dass eine Gliederung bei den kurzen Beiträgen nicht Sinnvoll ist habe ich diese letztendlich rausgenommen. 
- Die Fußnoten sollten jetzt passen und sind an der Fußnotensetzung in Wikipedia angelehnt. 
- Zu den Verlinkungen habe ich versucht so viel zu verlinken wie es mir möglich war.
- Das der Link des Schadenserwartungswert auf Risikomanagementsystem führt ist richtig, wenn man den Beitrag/Artikel liest wird erklärt wie dieser zustande kommt.
- Im Front Mattern sollten jetzt die passenden Tags drinnen, da bin ich mir aber nicht sicher ob diese passen, da in anderen Beiträgen auch nur klassisch oder agil als Tag reingeschrieben wurde. 
- Das Gender habe ich auch komplett rausgenommen.
- Angestrichene Rechtschreibfehler und zu sehr verschachtelte Sätze habe ich umgeschrieben und verbessert. 
- Die Abkürzung KI wird jetzt am Anfang des Beitrages KI_Software_fuer_Projektmanagement erklärt und der Name der Studie und wer befragt wurde wird jetzt auch genannt.
-  Auch habe ich bei der Risikomatrix die Einleitung verändert also den ersten und zweiten Satz vertauscht.
- Bei der Risikomatrix wurde auch der Punkt übernommen das die Berechnung des Schadenserwartungswertes zu Aufbau und Berechnung gehört. 

Mit freundlichen Grüßen
Tobias Busse

2022-01-12 14:34 UTC, up67enyq commented
Kriterium | Bewertung
-- | --
Front-Matter | ja
Umfang | ja
Belege | ja
Links | ja
Formatierung | ja
Verlinkungen vorhanden | ja
Abbildungen | ja
Strukturierung des Beitrags | 10
Rechtschreibung | 9
Sprache | 9
Inhalt | 10
Einordnung in den Kontext | 10
Ansprechend für Zielgruppe | 10

# Zusammenfassung
- KI_Software
Der Artikel beschreibt die Relevanz und möglichen Einsatzgebiete von KI im Bezug auf Projektmanagement. KI ist ein Gebiet der Informatik welches mit Automatisierung und maschinellen Lernen dem Menschen beim Projektmanagement beispielsweise durch die Übernahme repetitiver Aufgabe unterstützt.
Es wird weiter eine Abgrenzung zwischen schwacher und starker KI und der verschiedenen Arten des Lernens einer KI gezogen.
Die Bedenken bezüglich KI werden zum Ende relativiert und gut belegt.

- Risikomatrix
Der Artikel beschreibt den Aufbau, die Benutzung und den Nutzen sogenannter Risikomatrizen.
Eine Risikomatrix wird generell tabellarisch dargestellt. Dabei trägt entweder die x- oder y-Achse die Eintrittswahrscheinlichkeit eines Ereignisses (Risiko) und die andere Achse das korrespondierende Schadensausmaß. Aus der Multiplikation dieser beiden Werte werden Schadenserwartungswerte gebildet und die Felder der Risikomatrix entsprechend dieser Werte farblich eingefärbt.
Der Schadenserwartungswert stellt sich neben der Visualisierungsfähigkeit als einer der größten Nutzen im allgemeinen heraus. Im Bezug auf das Risikomanagement liegt der Nutzen vor allem darin, dass ab einer Eintrittswahrscheinlichkeit von über 25% und einer durchschnittlichen Schadenshöhe, Risiken aktiv gemanaged werden.
Im Projektmanagement kann die Risikomatrix durch die Veranschaulichung der Risiken im Projektbezug punkten und bietet somit auch eine gute Grundlage zur Priorisierung von Risiken.
Kritik an der Risikomatrix findet sich vor allem in ihrem zeitabhängigen Bezug der einzelnen Risiken da sich Variablen stetig verändern können.

# Positive Aspekte

- KI_Software
Ein schönes Schaubild um die Arten des KI-Lernens zu veranschaulichen
Sehr guter Gesamtüberblick über KI
guter Bezug zum Projektmanagement
Sehr viele Verlinkungen
Schöne Gliederung
Interessante ZDF am Anfang
Gute Sprache
Verbesserungsvorschläge sehr gut umgesetzt

- Risikomatrix
Schöne Gliederung
Fasst den Nutzen sehr umfassend zusammen
erklärt den Aufbau sehr schön
Verständliche und prägnante Sprach
Verbesserungsvorschläge gut umgesetzt

# Negative Aspekte

- KI_Software
Nach der Abbildung direkt die Quelle verlinken und Namen der Abbildung einfügen bspw.: "Bild 1: Arten des Maschinellen Lernens[^(Quelle)]"?
Vielleicht etwas häufig "Des Weiteren"


- Risikomatrix"
In der Einleitung evtl. direkt Bezug zum PM herstellen
Im Satz "In der Matrix werden die Risiken so positioniert, sodass eine gewichtete und vergleichende Darstellung besteht" ist durch das "sodass" eine Dopplung vom "so". Also entweder nur , dass oder das "so" weg lassen.
Vor dem Schaubild ist ein kleiner Rechtschreibfehler: "Riskomatrix" statt "Risiko..."
Im Abschnitt "Nutzen Allgemein" sollte nach dem ersten "ist" ein Punkt kommen. 
Im selben Abschnitt wäre glaube ich "Deshalb ist ~~es~~ **sie** ein wichtiges Instrument", weil es ja die Matrix ist, besser
"Anzahl der Kritikalität von Risiken" hört sich holprig an
Im Abschnitt Kritik würde ich nach "... Darstellung von Einzelrisiken ist" einen Punkt machen und dann mit "Das bedeutet..." weiter machen.

2022-01-13 19:37 UTC, urimi0 requested changes
KI_Software_fuer_Projektmanagement 2.0

| Kriterium | Bewertung|
|-----|---|
| Front-Matter | ja |
| Umfang | ja |
| Belege | ja |
| Links | ja |
| Formatierung | ja |
| Verlinkungen vorhanden | ja |
| Abbildungen | ja |
| Strukturierung des Beitrags | 9 |
| Rechtschreibung | 9 |
| Sprache | 9 |
| Inhalt | 10 |
| Einordnung in den Kontext | 9 |
| Ansprechend für Zielgruppe | 10 |

# Zusammenfassung
* Künstliche Intelligenz hilft Menschen Daten zu erhalten bzw. zu schätzen, die hilfreich sind in verschiedenen Gebieten. Hierbei gibt es verschiedene Lernarten von diesen Systemen. Allgemein betrachtet versucht KI, Muster in Daten zu erkennen und diese Weiterzuführen oder an Menschen zu übergeben.
# Positive Aspekte

* Mehr Verlinkungen vorhanden.
* Besser strukturiert.
* Gute weiterführende Literatur.
* Viele Quellen.
* Kritik wurde gut umgesetzt.

# Negative Aspekte

* Einleitung wurde verbessert (Umfrage detaillierter), aber würde in einem Satz genauer erklären was KI ist. Anstatt nur was es ausgeschrieben bedeutet.
* Die Abbildung finde ich persönlich zu groß für den Inhalt.
* Keine weiteren Kritikpunkte.

2022-01-13 20:10 UTC, urimi0 requested changes
Risikomatrix

| Kriterium | Bewertung|
|-----|---|
| Front-Matter | ja |
| Umfang | ja |
| Belege | ja |
| Links | ja |
| Formatierung | ja |
| Verlinkungen vorhanden | ja |
| Abbildungen | ja |
| Strukturierung des Beitrags | 10 |
| Rechtschreibung | 9 |
| Sprache | 9 |
| Inhalt | 9 |
| Einordnung in den Kontext | 10 |
| Ansprechend für Zielgruppe | 10 |

# Zusammenfassung
* Die Risikomatrix ist eine zweidimensionale Darstellung, die Risiken anhand von Bewertung in Verhältnis stellen soll. Sie ist das Produkt der Risikoanalyse und Risikobewertung, somit ist sie von großer Bedeutung für das Projektmanagement.

# Positive Aspekte

* Sehr gut strukturiert.
* Gute Abbildung.
* Den Unterpunkt Kritik finde ich sehr gut.
* Kritik gut umgesetzt.

# Negative Aspekte

* Einleitung würde ich verändern (siehe letztes Review).
* „Des Weiteren“ ein wenig häufig.
* Kleinere Grammatik-/Rechtschreibfehler.
* Keine weiteren Kritikpunkte.

2022-01-17 09:06 UTC, TobiasZuerrlein requested changes
# **1. KI Software für Projektmanagement**

| Kriterium | Bewertung|
|-----|---|
| Front-Matter | ja |
| Umfang | ja|
| Belege | ja |
| Links | ja|
| Formatierung | ja|
| Verlinkungen vorhanden | ja|
| Abbildungen | ja |
| Strukturierung des Beitrags | 10 |
| Rechtschreibung | 8|
| Sprache | 7|
| Inhalt | 10|
| Einordnung in den Kontext | 10|
| Ansprechend für Zielgruppe | 10|

# Zusammenfassung

Eine KI kann menschliche Verhaltensmuster imitieren und bestimmte Entscheidungen fällen. Es wird dabei zwischen "starker" und "schwacher" KI unterscheiden. Bei der Verwendung von KI im Projektmanagement ist vor allem das maschinelle Lernen (Unterkategorie von KI) bedeutsam, wodurch beispielsweise frühzeitig Ressourcenengpässe erkannt werden können.
Obwohl sehr viele Experten vom Nutzen von KI im Projektmanagement überzeugt sind, kommt KI hier noch kaum zum Einsatz. KI bringt neben den vielen Vorteilen auch eine Reihe an Bedenken mit sich, die aber relativiert werden müssen.

# Positive Aspekte

- Inhaltlich sehr ansprechend
- Interessante Erklärungen
- Gut ausgewählte und umfangreiche Literatur
- Aussagekräftige Abbildung
- Verbesserungsvorschläge größtenteils gut eingearbeitet

# Negative Aspekte

- **Front** **Matter**: Relevante Tags nicht ausreichend ausgefüllt.
- **Belege**: Ich würde die Fußnoten immer am Ende eines Satzes platzieren. Mitten im Satz ist meiner Meinung nach nicht korrekt.
- **Abbildung**: Bezeichnung unter der Abbildung platzieren, wie im Beispieltext von Martin.
- **Rechtschreibung**: Kommasetzung teilweise falsch oder unvollständig. Ein Beispiel: "Weitere Aspekte, wobei die KI-Software für das Projektmanagement von Vorteil sein kann ist die Übernahme repetitiver Arbeiten, wie Meeting-Organisation...": Nach "sein" fehlt ein Komma , nach "Arbeiten" ist ein Komma zu viel. Mein Tipp: Prüfe deinen Text unter https://www.duden.de/rechtschreibpruefung-online.
- **Sprache**:  Wörter wie "neu" vermeiden ("ein sehr neues Thema"). Bei "Des Weiteren sind die Bedenken, dass der Mitarbeiter durch eine KI ersetzt wird eher unbegründet, denn die Handlungsempfehlungen zu verhandeln oder Stakeholder zu akquirieren werden auch in Zukunft ein Projektmanager übernehmen müssen." muss das "ein" vor "Projektmanager" entfernt werden. "Beispiele einer schwachen KI sind ..." anstatt "Beispiele einer schwachen KI wären...". Den Satz "Unter der Abkürzung KI ist die Künstliche Intelligenz zu verstehen oder auch AI, welche ausgeschrieben artifizielle Intelligenz ist." würde ich rausnehmen und lieber so beginnen: "Die Künstliche-Intelligenz-Software (KI-Software) für das ..."

# **2. Risikomatrix**

| Kriterium | Bewertung|
|-----|---|
| Front-Matter | ja |
| Umfang | ja|
| Belege | ja |
| Links | ja|
| Formatierung | ja|
| Verlinkungen vorhanden | ja|
| Abbildungen | ja |
| Strukturierung des Beitrags | 10|
| Rechtschreibung | 10|
| Sprache | 8|
| Inhalt | 10|
| Einordnung in den Kontext | 9|
| Ansprechend für Zielgruppe | 9|

# Zusammenfassung

Die Risikomatrix setzt die Eintrittswahrscheinlichkeit und das Schadensausmaß negativer Ereignisse ins Verhältnis und stellt die Ergebnisse tabellarisch dar. Durch Multiplikation beider Faktoren kann der Schadenserwartungswert des jeweiligen Risikos berechnet werden. Die Risikomatrix spielt eine wichtige Rolle im Risiko- und Projektmanagement. Im Rahmen des Risikomanagements werden Risiken mit einer Eintrittswahrscheinlichkeit von über 25% und einer durchschnittlichen Schadenshöhe aktiv geleitet. Im Projektmanagement wird die Matrix hauptsächlich zur Veranschaulichung von Risiken ganzer Projekte oder Projektgruppen angewendet. Allerdings kann man die Risikomatrix aufgrund ihrer begrenzten Aussagefähigkeit kritisieren, da die Variablen stark zeitabhängig sind.

# Positive Aspekte

- Inhaltlich sehr ansprechend
- Gut ausgewählte und umfangreiche Literatur
- Schöne beispielhafte Risikomatrix als Abbildung
- Verbesserungsvorschläge größtenteils gut eingearbeitet


# Negative Aspekte

- **Front** **Matter**: Relevante Tags nicht ausreichend ausgefüllt.
- **Belege**: Ich würde die Fußnoten immer am Ende eines Satzes platzieren. Mitten im Satz ist meiner Meinung nach nicht korrekt.
- **Abbildung**: Bezeichnung unter der Abbildung platzieren, wie im Beispieltext von Martin.
- **Sprache**: Aus "Die Risikomatrix hilft bei der Beurteilung von Risiken, da es das Ergebnis der Risikoanalyse und Risikobewertung ist, deshalb ist es ein wichtiges Instrument des Projekt- und Risikomanagements." würde ich zwei Sätze machen ("...Risikobewertung ist. Deshalb ..."). Bei "Des Weiteren ist die Risikomatrix ideal für die Visualisierung und Kommunikation von Risikobewertungen und geben Auskunft über die Anzahl der Kritikalität von Risiken." muss es heißen "...und gibt...". Den Satz "Zunächst ist die Aussagekraft der Risikomatrix sehr schwach, da sie nur eine zeitabhängige Darstellung von Einzelrisken ist, bedeutet die Variablen können sich jederzeit verändern." würde ich umschreiben zu "...Einzelrisiken ist. Dies bedeutet, dass...".  Den Satz "Unter anderem sind die qualitativen und quantitativen Aussagen begrenzt, denn viele Risiken mit geringen Wahrscheinlichkeiten und Auswirkungen können äquivalent wirken zu einem Risiko mit großer Wahrscheinlichkeit und Auswirkung." würde ich auch etwas umschreiben: "Unter anderem sind die qualitativen und quantitativen Aussagen begrenzt, denn viele Risiken mit geringen Wahrscheinlichkeiten und Auswirkungen können äquivalent zu einem Risiko mit großer Auswirkung und Wahrscheinlichkeit sein."
- **Einordnung** **in** **den** **Kontext**: Etwas wenig Bezug zu Projektmanagement.
- **Ansprechend** **für** **Zielgruppe**: Etwas wenig Bezug zu Projektmanagement.

2022-01-25 13:57 UTC, merged