Six Sigma Statistische Versuchsplanung
ManagingProjectsSuccessfully/ManagingProjectsSuccessfully.github.io pull request #476
Opened 2021-12-21 16:22 UTC by elainevmd

2021-12-21 16:33 UTC, elainevmd commented
Feedback wurde umgesetzt:
•	Quellen einheitlich gestaltet
•	Verlinkungen eingefügt für die bessere Einordnung in den Kontext
•	Abbildung eingefügt
•	1.2 Einleitungssatz eingefügt
•	Sprache/Grammatik/Zeichensetzung verbessert
•	Quellenangaben vor dem Punkt im Satz gestellt

2022-01-12 19:19 UTC, tobi0211 reviewed
| Kriterium | Bewertung|
|-----|---|
| Front-Matter | ja |
| Umfang | ja|
| Belege | ja |
| Links | ja|
| Formatierung | ja|
| Verlinkungen vorhanden | ja |
| Abbildungen | ja |
| Strukturierung des Beitrags | 10 |
| Rechtschreibung | 8|
| Sprache | 7 |
| Inhalt | 10|
| Einordnung in den Kontext | 8|
| Ansprechend für Zielgruppe | 10|

# Zusammenfassung

Der Artikel beschreibt die stat. Versuchsplanung. Einleitend wird auf die Six Sigma und den DMAIC-Zyklus eingegangen, bevor anschließend die stat. Versuchsplanung inkl. Vorgehen erklärt wird und die Schritte / Phasen geschildert werden.

# Positive Aspekte

Inhaltlich und strukturell gefällt mir der Artikel wirklich gut, es wird Interesse an einem zuvor unbekannten Thema geweckt. Die numerische Gliederung gibt dem Artikel die richtige Struktur.
Es wurde auf das gegebene Feedback eingegangen und z.B. eine Graphik eingefügt, die m.E. sehr gut zum Artikel passt. Darüber hinaus wurden Verlinkungen auf Themen im Kontext eingefügt und die Quellen einheitlich gestaltet. Die Links funktionieren alle.


# Negative Aspekte

Es gibt noch Rechtschreib- (z.B. „Der rote Faden bildet“) und Kommafehler (z.B. vor „um“ direkt im 2.Satz), sie wurden aber schon reduziert. 
Der Schreibstil gefällt mir grundsätzlich gut, allerdings gibt es im oberen und mittleren Teil einige Sätze, die sich einfach unrund lesen lassen (Bsp: „Bei der Analyse, dem dritten Schritt, werden die Kernursachen des Problems analysiert und wie man dieses lösen kann, hierbei handelt es sich bereits um den vierten Schritt, dem verbessern.“). Wie in der vorherigen Review-Runde bereits erwähnt, würde ich solche Sätze in 2 Sätze aufteilen. 
Auf Six Sigma wurde unter „Siehe auch“ 2 mal verwiesen (Link 1&3). Zudem wurden teils selbe Quellen mehrfach verwendet, jeweils unter anderer Fußnote.

2022-01-15 13:30 UTC, Irishcoffee09 requested changes
| Kriterium | Bewertung|
|-----|---|
| Front-Matter | ja |
| Umfang | ja |
| Belege | ja |
| Links | ja |
| Formatierung | ja |
| Verlinkungen vorhanden | ja |
| Abbildungen | ja |
| Strukturierung des Beitrags |10|
| Rechtschreibung |10|
| Sprache |10|
| Inhalt |9|
| Einordnung in den Kontext |10|
| Ansprechend für Zielgruppe |9|

# Zusammenfassung

Der Artikel behandelt die statistische Versuchsplanung als Teil der Six Sigma Qualität Philosophie. Zunächst wird die Six Sigma Methode erklärt und ihre Vorteile werden aufgezeigt, später wird die statistische Versuchsplanung inklusive der genauen Vorgehensweise erläutert.

# Positive Aspekte

Positiv hervorzuheben ist die Struktur und der Aufbau des Beitrags. Die Einleitung gibt schnell einen groben Überblick, was man sich unter dem (auf den ersten Blick sehr abstrakten) Thema vorstellen kann. Im Folgenden wird zuerst der Rahmen der Six Sigma Methode erklärt, bevor der Autor ins Detail geht mit den 9 Schritten der Versuchsplanung. Überschriften und Aufzählungen sind vorhanden, es wurde strukturiert beim Verfassen der Arbeit vorgegangen. Der Artikel ist verständlich geschrieben und weckt das Interesse an dem Thema.

Die kritisierten Grammatik-, Komma- und Rechtschreibfehler wurden ausgebessert. Ebenso wurde eine anschauliche Abbildung zum DMAIC-Zyklus eingefügt und auch weitere Literatur ist jetzt aufgeführt. Es wurde auf die Kritikpunkte im ersten Review eingegangen.


# Negative Aspekte

Leider werden bei der Quellenangabe ganz unten immer noch wiederholt die gleichen Quellen aufgelistet. Verlinkungen auf angrenzende Themenbereiche sind im „Siehe auch“-Bereich vorhanden, im Fließtext (trotz vorhandenen Möglichkeiten) allerdings nicht.

2022-01-15 14:58 UTC, BelmontR requested changes
| Kriterium | Bewertung|
|-----|---|
| Front-Matter | ja|
| Umfang | ja|
| Belege | ja|
| Links | ja|
| Formatierung | ja|
| Verlinkungen vorhanden | ja|
| Abbildungen | ja|
| Strukturierung des Beitrags | 10 |
| Rechtschreibung | 10|
| Sprache | 10 |
| Inhalt | 10|
| Einordnung in den Kontext | 10|
| Ansprechend für Zielgruppe | 8|

# Zusammenfassung

Der Artikel erklärt die statistische Versuchsplanung und geht dabei auch kurz auf Six Sigma und den DMAIC-Zyklus ein.

# Positive Aspekte

Der Artikel ist weiterhin sehr gut strukturiert, der Sprachstil ist gut gewählt und es gibt kaum bis keine Tipp- bzw, Rechtschreibfehler.
Es wurde weiterführende Literatur hinzugefügt und auch die Sparte "Siehe auch" wurde gefüllt. Die Zitate wurden passend überarbeitet. Abbildungen wurden hinzugefügt. Die neuen Abbildungen sind sehr gut gewählt und tragen gut zum Verständnis bei.
Die meisten kritisierten Aspekte wurden ausgebessert.

# Negative Aspekte

Zwar wurden nun Verlinkungen zu anderen Themen hinzugefügt, jedoch nicht im Fließtext sondern nur unter "Siehe auch" und "Weiterführende Literatur". Es gibt immer noch doppelte Quellen im Quellenverzeichnis.

2022-01-25 13:57 UTC, merged