2.Update_Funktionale_Anforderungen
ManagingProjectsSuccessfully/ManagingProjectsSuccessfully.github.io pull request #484
Opened 2021-12-21 18:03 UTC by LysanderBenke

2021-12-21 18:08 UTC, LysanderBenke commented
Erklärungen:
Überschriften zur Verständlichkeit abgeändert.
Text, der nicht zum Thema gehörte gelöscht.
Textstelle in eine Tabelle umgewandelt, damit eine Verbildlichung existiert, da ich keine sinnvollen Bilder gefunden habe.
zusätzliche Verlinkungen zu angrenzenden Themen.

2022-01-12 14:04 UTC, ksushaW requested changes
| Kriterium | Bewertung|
|-----|---|
| Front-Matter | ja|
| Umfang | ja|
| Belege | ja|
| Links | ja|
| Formatierung | ja|
| Verlinkungen vorhanden | ja|
| Abbildungen | nein |
| Strukturierung des Beitrags | 10 |
| Rechtschreibung | 10|
| Sprache | 10 |
| Inhalt |10|
| Einordnung in den Kontext | 10|
| Ansprechend für Zielgruppe | 10|

# Zusammenfassung

In dem Beitrag geht es um funktionale Anforderungen. Zunächst werden die Unterschiede zwischen funktionalen & nicht-funktionalen Anforderungen tabellarisch gegenübergestellt. Zudem wird auf die Bedeutung der Anforderungsklarheit hingewiesen, also dass es wichtig ist seine Anforderungen klar & eindeutig zu formulieren zur Vermeidung von Fehlern & Missverständnissen. Zudem wird auf die Ermittlung dieser eingegangen. Anschließend werden die verschiedenen Arten funktionaler Anforderungen nacheinander vorgestellt. Zum Schluss wird darauf eingegangen, dass trotz Festhalten von funktionalen Anforderungen Änderungen auftreten können.

# Positive Aspekte

Der Beitrag ist insgesamt gut gelungen. Er ist mit passenden Überschriften gut strukturiert. Der Text ist sachlich & auf verständlicher Art & Weise formuliert. Positiv ist außerdem, dass man eine Tabelle in den Beitrag integriert hat, um die Unterschiede zwischen funktionalen & nicht-funktionalen Anforderungen visuell zu veranschaulichen. Außerdem wird in den Erklärungen immer Bezug zum Oberthema "Projekt" genommen.

# Negative Aspekte

Ein paar kleine Tippfehler waren zu erkennen. Ein zusätzliches Bild wäre wünschenswert. Ansonsten gibt es nichts zu beanstanden.

2022-01-18 17:51 UTC, JennyKonn reviewed
| Kriterium | Bewertung|
|-----|---|
| Front-Matter | ja |
| Umfang | ja|
| Belege | ja |
| Links | ja|
| Formatierung | ja|
| Verlinkungen vorhanden | ja |
| Abbildungen | nein |
| Strukturierung des Beitrags | 10 |
| Rechtschreibung | 10|
| Sprache | 10 |
| Inhalt | 10|
| Einordnung in den Kontext | 10 |
| Ansprechend für Zielgruppe | 10|

# Zusammenfassung

Der Artikel informiert über funktionale Anforderungen im Projektmanagement. Hierbei werden die funktionalen Anforderungen in einem ersten Schritt von den nicht-funktionalen Anforderungen abgegrenzt. Daraufhin wird umfangreich auf Relevanz, Durchführung der Ermittlung und Änderungen der funktionalen Anforderungen eingegangen. Tiefergelegt wird zudem das Thema Durchführung der Ermittlung indem auf Basisfaktoren, Leistungsfaktoren und Begeisterungsfaktoren (gemeinsam als Kano-Modell bezeichnet) eingegangen wird.

# Positive Aspekte

Positiv hervorzuheben sind meiner Meinung nach Sprach und Wortwahl sowie Inhalt des Artikels. Es wurden einschlägige und verständliche Formulierungen gewählt. Dies macht es dem Leser leicht den Text zu lesen und sich auf den Inhalt zu konzentrieren. Inhaltlich wurden alle wichtigen Aspekte umfangreich erklärt. Auch angrenzende Themen wurden erwähnt und evtl. unbekannte Fachbegriffe erläutert. Die Tabelle ist für den Vergleich von funktionalen und nicht funktionalen Anforderungen gut geeignet. 

# Negative Aspekte

Es wurden weitere Artikel verlinkt und alle angesprochenen negativen Aspekte überarbeitet. Abgesehen von dem fehlenden Bild, was für mich hier allerdings keinen Punktabzug geben sollte da es zu diesem Thema recht schwer ist etwas geeignetes zu finden, ein sehr gelungener Beitrag.

2022-01-19 16:33 UTC, AmrouHasan reviewed
| Kriterium | Bewertung|
|-----|---|
| Front-Matter | ja |
| Umfang | ja |
| Belege | ja |
| Links | ja |
| Formatierung | ja |
| Verlinkungen vorhanden | ja |
| Abbildungen | nein |
| Strukturierung des Beitrags | 10 |
| Rechtschreibung | 10 |
| Sprache | 10 |
| Inhalt | 10 |
| Einordnung in den Kontext | 10 |
| Ansprechend für Zielgruppe | 10 |

# Zusammenfassung

Der Artikel befasst sich mit den funktionalen Anforderungen. Dabei handelt es sich um Anforderungen, die im Pflichtenheft festgehalten werden. Zunächst wird zwischen den funktionalen und nicht funktionalen Anforderungen unterschieden. Im Folgenden wird über die Wichtigkeit der Klarheit von Anforderungen berichtet. Anschließend wird über die Durchführung der Ermittlung der funktionalen Anforderungen abgehandelt, welche in drei Faktoren unterteilt werden. Schließlich wird noch erklärt, dass Änderungen von funktionalen Anforderungen kaum möglich sind. 

# Positive Aspekte

Beinahe alle notwendigen Punkte wurden erfüllt. Der Artikel lässt sich gut lesen und man versteht direkt worum es sich handelt. Es wurden auch viel im Text belegt, welche mit ausreichend vielen Quellen belegt wurden, welches auf eine gute Recherche hinweist. Die Rechtschreibung wie Wahl der Sprache ist optimal.

# Veränderungen

Der Beispieltext wurde herausgelöscht und die Überschriften wurden überarbeitet und sind nun aussagekräftiger.

Meinen Vorschlag eines Inhaltsverzeichnisses bist du nicht nachgekommen, was aber eine persönliche Entscheidung ist. Daher ist das ok.

Die Links verweisen immer noch auf die selbe Seite. Man hätte vielleicht Link z.B. zu Stakeholder oder Ähnlichem herstellen können. Außerdem fehlt eine Abbildung.

Insgesamt hat sich der Artikel sehr gut verbessert.

2022-01-25 13:59 UTC, merged