Praxisbeispiele gescheiterte Projekte
ManagingProjectsSuccessfully/ManagingProjectsSuccessfully.github.io pull request #489
Opened 2021-12-21 19:32 UTC by at33fau

Auf die Reviews bin ich eingegangen und habe den Artikel anhand der konstruktiven Kritiken überarbeitet. Das Inhaltsverzeichnis habe ich zudem aktualisiert, es aber aufgrund der vielen Unterpunkte ähnlich des Wikipedia-Stils erhalten. Die Definition des Projektmanagements ist bewusst auf zwei Sätze begrenzt und soll nur kurz zusammenfassen, was ein Projekt ist (der Kompendiumsbeitrag dazu wurde aber verlinkt). Das Beispiel der Stadtautobahn in Boston wurde bewusst gewählt, um zu zeigen, dass es auch außerhalb von Deutschland Projekte gibt, die scheitern.  
Links und Bilder habe ich abschließend erfolgreich überprüft.

2022-01-15 00:09 UTC, hatutona commented
| Kriterium | Bewertung|
|-----|---|
| Front-Matter | ja|
| Umfang | ja|
| Belege | ja |
| Links | ja|
| Formatierung | ja|
| Verlinkungen vorhanden | ja|
| Abbildungen | ja|
| Strukturierung des Beitrags | 10 |
| Rechtschreibung | 10|
| Sprache | 10 |
| Inhalt | 10|
| Einordnung in den Kontext | 10|
| Ansprechend für Zielgruppe | 10|

# Zusammenfassung
* Der Artikel beschäftigt sich mit dem Thema gescheiterte Projekte in der Praxis und besteht aus drei Teilen. Bei ersterem ist eine kleine Anleitung zum Thema dann kommen definition von Projekt bzw. die Gründe, die zum mißlungenen Projekt zurückführen.  Des Weiteren sind die vier Praxisbeispiele gescheiterter Projekte. Anschließend werden einige Zahlen, Daten und Fakten bezogen auf gescheiterte Projekte beschrieben.
# Positive Aspekte
* Kritikpunkte, die aus 1. Runde sind, wurde beachtet
# Negative Aspekte
Keine.

2022-01-15 11:16 UTC, hatutona requested changes
| Kriterium | Bewertung|
|-----|---|
| Front-Matter | ja|
| Umfang | ja|
| Belege | ja |
| Links | ja|
| Formatierung | ja|
| Verlinkungen vorhanden | ja|
| Abbildungen | ja|
| Strukturierung des Beitrags | 10 |
| Rechtschreibung | 10|
| Sprache | 10 |
| Inhalt | 10|
| Einordnung in den Kontext | 10|
| Ansprechend für Zielgruppe | 10|

# Zusammenfassung
* Der Artikel beschäftigt sich mit dem Thema gescheiterte Projekte in der Praxis und besteht aus drei Teilen. Bei ersterem ist eine kleine Anleitung zum Thema dann kommen definition von Projekt bzw. die Gründe, die zum mißlungenen Projekt zurückführen.  Des Weiteren sind die vier Praxisbeispiele gescheiterter Projekte. Anschließend werden einige Zahlen, Daten und Fakten bezogen auf gescheiterte Projekte beschrieben.
# Positive Aspekte
* Kritikpunkte, die aus 1. Runde sind, wurde beachtet
# Negative Aspekte
Keine.

2022-01-16 21:31 UTC, xyjaxy requested changes
| Kriterium | Bewertung|
|-----|---|
| Front-Matter | ja |
| Umfang | ja|
| Belege | ja |
| Links | ja|
| Formatierung | ja|
| Verlinkungen vorhanden | ja |
| Abbildungen | ja |
| Strukturierung des Beitrags | 10 |
| Rechtschreibung | 10|
| Sprache | 10 |
| Inhalt | 10|
| Einordnung in den Kontext | 10|
| Ansprechend für Zielgruppe | 10|

# Zusammenfassung

Der Artikel beschreibt zunächst sehr deutlich, ab wann ein Projekt als gescheitert gilt und rundet das Thema mit einigen ausformulierten Beispielen ab.

# Positive Aspekte

Der Artikel hat sich im Vergleich zur ersten Runde deutlich verbessert. Das Feedback wurde beachtet und der Beitrag dementsprechend angepasst. Generell liest er sich leichter und flüssiger als zuvor.

# Negative Aspekte

Keine

2022-01-19 19:40 UTC, aq07yhug reviewed
| Kriterium | Bewertung|
|-----|---|
| Front-Matter | ja |
| Umfang | ja |
| Belege | ja |
| Links | ja |
| Formatierung | ja |
| Verlinkungen vorhanden | ja |
| Abbildungen | ja |
| Strukturierung des Beitrags | 10 |
| Rechtschreibung | 10|
| Sprache | 10 |
| Inhalt | 10|
| Einordnung in den Kontext | 10|
| Ansprechend für Zielgruppe | 10|

# Zusammenfassung

Der Artikel berichtet über die gescheiterten Projekte in Deutschland und den USA. Zudem werden ausreichend die Kriterien erklärt, ab wann ein Projekt als gescheitert gilt. Alle im Artikel erwähnte gescheiterte Projekte sind mit relevanten Zahlangaben und Gründen "Warum gescheitert?" vorgestellt. Die gewählten Fakten am Ende runden den Artikel gekonnt ab und regen den Leser dazu an, sich mit dem Thema Projektmanagement weiter auseinanderzusetzen. 

# Positive Aspekte

Der Artikel hat sich wesentlich verbessert und die Kritikpunkte wurden beachtet. Der Autor hat sich die Zeit genommen, um seinen Artikel zu bearbeiten und noch bessert zu gestalten.

# Negative Aspekte

Keine

2022-01-25 14:00 UTC, merged