Xtreme Programming
ManagingProjectsSuccessfully/ManagingProjectsSuccessfully.github.io pull request #494
Opened 2021-12-21 20:18 UTC by 29834

2022-01-18 16:54 UTC, Aaron-WS reviewed
| Kriterium | Bewertung|
|-----|---|
| Front-Matter | ja|
| Umfang | ja|
| Belege | ja |
| Links | ja|
| Formatierung | ja|
| Verlinkungen vorhanden | ja |
| Abbildungen | ja|
| Strukturierung des Beitrags | 10 |
| Rechtschreibung | 10|
| Sprache |10 |
| Inhalt | 10|
| Einordnung in den Kontext | 10|
| Ansprechend für Zielgruppe | 10|

# Zusammenfassung

In diesem Beitrag wird Extreme Programming erklärt. Diese agile Methode wird in der Softwareentwicklung eingesetzt. Nach einer kurzen Einleitung mit historischen Fakten erklärt der Beitrag Rollen, Werte und die Vor- und Nachteile.

# Positive Aspekte
* Du hast viele Belege benutzt.
* Die Länge der einzelnen Absätze ist ausgewogen.
* Die Abbildung ist sehr passend.
* **Es gibt viele Verlinkungen.**

# Negative Aspekte
* ~~Du könntest auch im Text Verlinkungen einbauen. Zum Beispiel bei Scrum und Kanban in Zeile 18.~~
* Du könntest mehr Tags einfügen.

2022-01-18 21:53 UTC, niru1999 commented
| Kriterium | Bewertung|
|-----|---|
| Front-Matter | ja |
| Umfang | ja |
| Belege | nein |
| Links | ja|
| Formatierung | ja|
| Verlinkungen vorhanden | ja |
| Abbildungen | ja |
| Strukturierung des Beitrags | 10 |
| Rechtschreibung | 9 |
| Sprache | 8 |
| Inhalt | 7 |
| Einordnung in den Kontext |10|
| Ansprechend für Zielgruppe |10|

# Zusammenfassung
Der Artikel handelt von Extreme Programming. Dabei wird auf den historischen Hintergrund eingegangen. Ferner werden die einzelnen Rollen und deren Werte aufgelistet. Abschließend werden auf die Vor- und Nachteile hingewiesen. 

# Positive Aspekte

- alles gut verlinkt jeder Absatz ist mit einer Quelle vermerkt
- kurz und wichtige Aspekte werden bei den Werten hervorgehoben
- Das Bild ist treffend und beschreibt den ganzen Prozess

# Negative Aspekte
- kleine Satzbau Fehler (z.B. im 3. Absatz bei Vor- und Nachteilen)
- Das Bild hat keine Bildunterschrift und die Quelle wurde nicht vermerkt
- auf das Bild wird nicht eingegangen
- man hätte auch im Text die Verlinkungen einbauen können wie 
Leider wird der verbesserte Beitrag bei mir nicht angezeigt weswegen ich bei meiner Bewertung nichts ändern kann. Könnte es eventuell sein, dass kein Pull-Request erstellt wurde?

2022-01-19 10:38 UTC, NK0100 requested changes
| Kriterium | Bewertung|
|-----|---|
| Front-Matter | ja |
| Umfang | ja |
| Belege | ja |
| Links | ja |
| Formatierung | ja |
| Verlinkungen vorhanden | ja |
| Abbildungen | ja |
| Strukturierung des Beitrags | 8 |
| Rechtschreibung | 9 |
| Sprache | 9 |
| Inhalt | 8 |
| Einordnung in den Kontext | 10 |
| Ansprechend für Zielgruppe | 9 |

# Zusammenfassung

Der Artikel widmet sich dem sogenannten Extreme Programming. Extreme Programming ist neben Scrum und Kanban eine agile Entwicklungsmethode aus der Softwareentwicklung. Zunächst wird die Methode definiert und in einen chronologischen Zusammenhang gesetzt. Im Anschluss folgen die im Extreme Programming verankerten Rollen, Werte und Vor- und Nachteile, welche sich bei Anwendung der Methode ergeben können.

# Positive Aspekte

Ich finde Deinen Artikel durchaus gelungen und informativ! Ich mag Deine sehr kurzen und treffenden Sätze, sowie die logischen Zusammenhänge, welche sich auch in der Struktur/Aufbau widerspiegeln. Darüber hinaus finde ich Deine Belege z.B. im Buch „Beck, K. (2000): Extreme Programming explained - Embrace Chance. Massachusetts: Addison-Wesley“, welche Du mit Seitenzahlen belegt hast sehr gut gewählt. Deine Links funktionieren einwandfrei und auch der Umfang von 500 Zeichen wurde erreicht. Sprachlich kann ich keine gravierenden Fehler finden. Deine gewählte Abbildung ist auch gut gewählt und ergänzt sich super mit dem dabeistehenden Text.
Update: Du hast Dir mein vorgehendes Feedback durchaus angenommen und gut umgesetzt!

# Negative Aspekte

Du hast Dir mein vorgehendes Feedback durchaus angenommen und gut umgesetzt! (siehe neue Überschriften und einleitende Sätze nach Überschriften). Auch eine Quelle zur Abbildung ist nun vorhanden – good job!

2022-01-22 20:30 UTC, niru1999 reviewed
| Kriterium | Bewertung|
|-----|---|
| Front-Matter | ja |
| Umfang | ja |
| Belege | nein |
| Links | ja|
| Formatierung | ja|
| Verlinkungen vorhanden | ja |
| Abbildungen | ja |
| Strukturierung des Beitrags | 10 |
| Rechtschreibung | 9 |
| Sprache | 8 |
| Inhalt | 7 |
| Einordnung in den Kontext |10|
| Ansprechend für Zielgruppe |10|

# Zusammenfassung
Der Artikel handelt von Extreme Programming. Dabei wird auf den historischen Hintergrund eingegangen. Ferner werden die einzelnen Rollen und deren Werte aufgelistet. Abschließend werden auf die Vor- und Nachteile hingewiesen. 

# Positive Aspekte

- alles gut verlinkt jeder Absatz ist mit einer Quelle vermerkt
- kurz und wichtige Aspekte werden bei den Werten hervorgehoben
- Das Bild ist treffend und beschreibt den ganzen Prozess

# Negative Aspekte
- kleine Satzbau Fehler (z.B. im 3. Absatz bei Vor- und Nachteilen)
- Das Bild hat keine Bildunterschrift und die Quelle wurde nicht vermerkt
- auf das Bild wird nicht eingegangen
- man hätte auch im Text die Verlinkungen einbauen können wie 
Leider wird der verbesserte Beitrag bei mir nicht angezeigt weswegen ich bei meiner Bewertung nichts ändern kann. Könnte es eventuell sein, dass kein Pull-Request erstellt wurde?

2022-01-25 14:00 UTC, merged