Voice_of_the_Customer Beitrag
ManagingProjectsSuccessfully/ManagingProjectsSuccessfully.github.io pull request #50
Opened 2021-11-15 15:25 UTC by eddq2000

2021-11-26 12:21 UTC, ChrisBohl requested changes
| Kriterium | Bewertung|
|-----|---|
| Front-Matter | ja |
| Umfang | ja|
| Belege | ja |
| Links | ja|
| Formatierung | ja|
| Verlinkungen vorhanden | ja |
| Abbildungen | ja|
| Strukturierung des Beitrags | 10 |
| Rechtschreibung |10|
| Sprache |10 |
| Inhalt |8|
| Einordnung in den Kontext | 8|
| Ansprechend für Zielgruppe | 8|

# Zusammenfassung

Der Artikel befasst sich mit dem Thema: "Voice of the Customer (VOC)". Dies ist ein Unternehmensprozess, der auf die Analyse von Kundendaten und eine verbesserte Einbindung dieser in andere Geschäftsprozesse/ Projektmanagementprozesse abzielt. Der VOC besteht aus den drei Phasen:
Phase 1: Erfassen relevanter Kundendaten
Phase 2: Auswertung der gesammelten Daten mit Hilfe von quantitativen und qualitativen Analyseverfahren
Phase 3: Umwandlung der Analyseergebnisse in spezifische Kundenanforderungen
Die aus diesen drei Phasen gewonnene Erkenntnisse werden anschließend für diverse Unternehmensprozesse in diversen Unternehmensbereichen zur Customer Service Optimierung herangezogen. 

# Positive Aspekte

Also erstmal ist deine Sprache und Rechtschreibung top.
Ich finde den Inhalt logisch gut aufgebaut und des Weiteren auch umfangreich. 
Insgesamt würde ich sagen, dass es eine sehr schöne Arbeit ist.

# Negative Aspekte

Im Bezug zur Bewertungstabelle ist mir nur aufgefallen, dass der Bezug zum Projektmanagement irgendwann verloren geht. Das Thema wird eher allgemein gehalten, sollte aber vor allem im letzten Abschnitt den Mehrwert für das Projektmanagement nochmal unterstreichen.

2021-11-28 15:43 UTC, ChristinaHartung requested changes
| Kriterium | Bewertung|
|-----|---|
| Front-Matter | ja |
| Umfang |nein|
| Belege | ja |
| Links | ja |
| Formatierung | ja|
| Verlinkungen vorhanden | ja |
| Abbildungen | ja |
| Strukturierung des Beitrags |9 |
| Rechtschreibung | 10 |
| Sprache | 10 |
| Inhalt | 8 |
| Einordnung in den Kontext |10|
| Ansprechend für Zielgruppe |10|

# Zusammenfassung

Der Artikel befasst sich mit "Voice of the Costumer", einem Prozess in Unternehmen um mit Hilfe von Kundeninformationen für die Kunden bessere Resultate zu erzielen. Dafür werden Tools, Vorgehensweise und Beispiele aufgeführt.

# Positive Aspekte

insgesamt sehr gut gelungen --> Übersichtliche Grafik, Stichpunkte als Aufzählung sinnvoll eingesetzt, Formulierungen treffend, Einbezug bzw. Verlinkungen zu angrenzenden Themen spricht an Thema interessierten Leser sehr an, Beispiele tragen gut für Verständnis des Prozesses in der Praxis bei

# Negative Aspekte

Umfang sehr groß, eventuell könnte man einige Teile kürzen, die auf angrenzende Bereiche verweisen, die ein Leser ohne Vorwissen nicht kennt und sich deshalb für den optimalen Gesamtkontext erst belesen muss; 
Möglicherweise würde es zu einer noch besseren Übersichtlichkeit helfen, die ersten zwei Überschriften (Überblick und Hintergrund) zu einem Absatz zusammenzufassen.

2021-11-28 20:02 UTC, biancamg requested changes
| Kriterium | Bewertung|
|-----|---|
| Front-Matter | ja |
| Umfang | nein |
| Belege | ja |
| Links | ja |
| Formatierung | ja |
| Verlinkungen vorhanden | ja |
| Abbildungen | ja |
| Strukturierung des Beitrags | 10 |
| Rechtschreibung | 10|
| Sprache | 10 |
| Inhalt | 9 |
| Einordnung in den Kontext | 9 |
| Ansprechend für Zielgruppe | 10 |

# Zusammenfassung

Der Artikel "Voice of the Customer" beschreibt einen Prozess in einem Unternehmen, der dazu dienen soll Kundenbedürfnisse besser zu identifizieren um daraufhin Arbeitsprozesse anpassen zu können. In dem Artikel wird insbesondere auf die 3 Phasen des VOC eingegangen.  Am Ende wird darauf eingegangen wie Unternehmen VOC in der Praxis umsetzen können.

# Positive Aspekte

Es fällt direkt auf, dass der Artikel sehr gut strukturiert ist. Durch das Bild am Anfang und die folgenden Über- sowie Unterschriften ist es sehr angenehm den Beitrag zu lesen.
Die Sprache sowie Rechtschreibung ist ebenfalls gut. Inhaltlich ist der Beitrag, durch die anfängliche Erklärung dann die Aufteilung der Phasen und letztendlich die Umsetzung in Unternehmen, sehr gut aufgeteilt. 
Alles in allem in es ein sehr ansprechend geschriebener Artikel, der vor allem durch die Strukturierung sehr angenehmen zum lesen ist.

# Negative Aspekte

Zu Beginn muss erwähnt werden, dass der Umfang des Artikels zu viel ist. Bei Word werden fast 1000 Wörter angezeigt, wenn man den Text dort einfügt. Deshalb ist der Punkt Umfang mit "Nein" beantwortet worden. Ein Wortlimit von 500 Wörtern wurde uns als Vorgabe gegeben, 1000 Wörter sind eindeutig zu viel. Inhaltlich fallen somit nochmal ca. 50% des Textes weg.
Außerdem könnte noch etwas mehr auf den Zusammenhang zu Projektmanagement eingegangen werden und eventuell mehr Verlinkungen vorgenommen werden.
Die Links für "Siehe auch" und "Weiterführende Literatur" sind nicht vorhanden, dies könnte man noch ergänzen.

2021-11-29 11:40 UTC, eddq2000 commented
@ChrisBohl @ChristinaHartung @biancamg 

Erst einmal vielen Dank für euer Feedback! Bei fast allen negativen Aspekten stimme ich euch absolut zu.

Ich hab meinen Beitrag jetzt noch einmal überarbeitet und will euch kurz sagen, was ich gemacht habe:
* Ich habe meinen Beitrag so gut gekürzt, wie es mir möglich war: Lässt man Quellen und Formatierungen beiseite, habe ich 1000 Wörter auf ca 730 kürzen können. Mir ist bewusst, dass das die Grenze immer noch übersteigt. Mir ist es aber wichtig Leuten, die VOC lesen, ein gut genügendes Verständnis mitzugeben und das geht nicht mit noch weniger Wörtern. Sprich, hier nehme ich den Kritikpunkt in Kauf, da es sonst zu zu starkem Informationsverlust kommen würde.
* Ich habe das letzte Kapitel im Kontext auf das Kompendium komplett ausgetauscht und stelle dort noch einmal genauer die Relevanz von VOC für das PM dar.
* Ich habe die Teile "Siehe auch" und "Weiterführende Literatur" eingefügt.
* Ich habe zusätzliche Verlinkungen eingefügt, wo es mir möglich war.

Die Kapitel Übersicht und Relevanz lasse ich weiterhin getrennt, da sonst die Qualität des Kapitels Übersicht (in der man das notwendige fundamentale Verständnis bekommt) nicht mehr so gut gewährleistet wäre.

Also nochmal vielen Dank und alles Gute!

2021-12-09 19:24 UTC, merged