PRINCE2 & Impediment Backlog
ManagingProjectsSuccessfully/ManagingProjectsSuccessfully.github.io pull request #510
Opened 2021-12-21 22:31 UTC by patrick203494

@larissadiscua @Paulqe42kuno @Loris18
Hallo zusammen, hier der Vollständigkeit halber nochmal meine Antwort im neuen pull request:
danke für eure Reviews! :-)
Hat mich sehr gefreut, euer gutes Feedback zu hören. Ich hab die Verlinkungen, zu denen kein Beitrag verfasst wurde, rausgenommen. Daher sind es leider einige weniger geworden...

@Loris18
Bzgl. Impediment Backlog:
Ich habe die Reihenfolge in der Einleitung vertauscht, sodass als erstes auf das Impediment Backlog eingegangen wird und dann erst im Anschluss Impediments erklärt. Da es wie du schon meintest keinen eigenständigen Artikel dazu gibt, ist es meiner Meinung nach Sinnvoll, genauer darauf einzugehen. Ich denke das macht dann in der Reihenfolge auf jeden Fall auch mehr Sinn, danke für den Tipp!
Außerdem habe ich wie in Wikipedia üblich die Übersetzung angepasst und "englisch für..." verwendet.

Bzgl. PRINCE2:
Guter Hinweis, ich habe auf "Vorteile" und "Nachteile" abgeändert.
Bzgl. der Wortanzahl bin ich mir jedoch nicht ganz sicher, was du meinst. Ich habe nochmal nachgesehen und den Artikel in Word reinkopiert. Dann hab ich alle Überschriften, Abbildung und Abbildungsbeschriftung rausgenommen und bin trotzdem bei über 510 Wörtern (Sofern man den Tabelleninhalt mitzählt)
Aber die Überschriften zählen glaub ich ohnehin mit dazu, also sollte das eh kein Problem sein :-)

Lieben Gruß
Patrick

2022-01-15 16:53 UTC, larissadiscua commented
| Kriterium | Bewertung|
|-----|---|
| Front-Matter | ja|
| Umfang | ja|
| Belege | ja |
| Links | ja|
| Formatierung | ja|
| Verlinkungen vorhanden | ja|
| Abbildungen | ja|
| Strukturierung des Beitrags | 10 |
| Rechtschreibung | 10|
| Sprache | 10 |
| Inhalt | 10|
| Einordnung in den Kontext | 10|
| Ansprechend für Zielgruppe | 10|

# Zusammenfassung

Im Beitrag zum Impediment Backlog geht es um verschiedene Störfaktoren, die Projekte beeinflussen können. Bei diesen Störfaktoren kann es sich von zu hohen Raumtemperaturen, bis hin zu persönlichen Konflikten untereinander handeln. Im Backlog soll vermerkt werden, wer betroffen ist, wie lange die Störung schon andauert und wer eine mögliche Kontaktperson sein kann. Durch diesen Beitrag lernt man, dass ein Impediment Backlog zwar häufig unterschätzt wird, jedoch eine wichtige Rolle in jedem Scrum-Projekt spielt.

Beim Beitrag zu PRINCE2 lernt man, dass dies ein Ansatz für die Ausgestaltung, Organisation und Management von Projekten ist. Man erfährt das Wichtigste zu den vier Grundbausteinen und den sieben Grundprinzipien, die sich mit verschiedenen Fragestellungen auseinander setzen. Zum Schluss werden noch die Stärken und mögliche Schwächen besprochen.

# Positive Aspekte

Die Beiträge sind beide sprachlich und inhaltlich sehr gut gestaltet, sie sind einfach und verständlich geschrieben und geben einen guten Überblick über die beiden Themen. Man erfährt Grundlegendes und dank zahlreicher Verlinkungen besteht die Möglichkeit, sich intensiver mit den Themen auseinanderzusetzen. 

# Negative Aspekte

Da es für mich schon in der ersten Reviewrunde nichts zu bemängeln gab, habe ich nun auch keine negativen Aspekte.

2022-01-16 11:10 UTC, larissadiscua approved these changes
| Kriterium | Bewertung|
|-----|---|
| Front-Matter | ja|
| Umfang | ja|
| Belege | ja |
| Links | ja|
| Formatierung | ja|
| Verlinkungen vorhanden | ja|
| Abbildungen | ja|
| Strukturierung des Beitrags | 10 |
| Rechtschreibung | 10|
| Sprache | 10 |
| Inhalt | 10|
| Einordnung in den Kontext | 10|
| Ansprechend für Zielgruppe | 10|

# Zusammenfassung

Im Beitrag zum Impediment Backlog geht es um verschiedene Störfaktoren, die Projekte beeinflussen können. Bei diesen Störfaktoren kann es sich von zu hohen Raumtemperaturen, bis hin zu persönlichen Konflikten untereinander handeln. Im Backlog soll vermerkt werden, wer betroffen ist, wie lange die Störung schon andauert und wer eine mögliche Kontaktperson sein kann. Durch diesen Beitrag lernt man, dass ein Impediment Backlog zwar häufig unterschätzt wird, jedoch eine wichtige Rolle in jedem Scrum-Projekt spielt.

Beim Beitrag zu PRINCE2 lernt man, dass dies ein Ansatz für die Ausgestaltung, Organisation und Management von Projekten ist. Man erfährt das Wichtigste zu den vier Grundbausteinen und den sieben Grundprinzipien, die sich mit verschiedenen Fragestellungen auseinander setzen. Zum Schluss werden noch die Stärken und mögliche Schwächen besprochen.

# Positive Aspekte

Die Beiträge sind beide sprachlich und inhaltlich sehr gut gestaltet, sie sind einfach und verständlich geschrieben und geben einen guten Überblick über die beiden Themen. Man erfährt Grundlegendes und dank zahlreicher Verlinkungen besteht die Möglichkeit, sich intensiver mit den Themen auseinanderzusetzen. 

# Negative Aspekte

Da es für mich schon in der ersten Reviewrunde nichts zu bemängeln gab, habe ich nun auch keine negativen Aspekte.

2022-01-19 19:57 UTC, Paulqe42kuno requested changes
# Impediment_Backlog
| Kriterium | Bewertung|
|-----|---|
| Front-Matter | ja |
| Umfang | ja |
| Belege | ja |
| Links | ja |
| Formatierung | ja |
| Verlinkungen vorhanden | ja |
| Abbildungen | ja |
| Strukturierung des Beitrags | 10 |
| Rechtschreibung | 10 |
| Sprache | 10 |
| Inhalt | 10 |
| Einordnung in den Kontext | 10 |
| Ansprechend für Zielgruppe | 10 |

## Zusammenfassung

Kurze Zusammenfassung des/der Artikel
Der Artikel handelt von Impediment_Backlog. Impediments sind Hindernisse, die in einem Projekt auftreten. Solche sind beispielsweise zu hohe Temperatur im Büro oder das Mangel an Wissen, Fähigkeiten und Ressourcen. Ein Impediment Backlog ist die Visualisierung der Impediments mit anschließender Priorisierung. Der Artikel geht genauer auf die Darstellung von Impediment Backlogs, die Verantwortlichen für Impediments sowie dem Idealtypischen Ablauf für den Umgang mit Impediments. Verantwortlich für das Vorgehen gegen Impediments ist der Scrum Master. Der idealtypische Umgang mit Impediments wird in fünf Phasen gegliedert: Aufnehmen, Priorisieren, Veröffentlichen, Handeln, Informieren. 

## Positive Aspekte

Es sind viele Verlinkungen vorhanden, die alle funktionieren. Die angegebenen Quellen funktionieren ebenfalls noch, außer die erste weiterführende Literatur (siehe negative Aspekte). Ich finde es schön, dass du meine Tipps übernommen hast, auch wenn du diese in deinem Kommentar an Loris18 adressiert hast :D. Ansonsten bekommst du wieder volle Punktzahl von mir überall und alle ja/nein Kriterien sind erfüllt,. 
## Negative Aspekte
Deine erste weiterführende Literatur ist nicht mehr verfügbar (Youtube Video). Ansonsten habe ich eigentlich nichts mehr zu bemängeln, du hast ja bereits alle meine Tipps übernommen. Der Artikel war davor schon gut und ist jetzt noch ein Stück besser. 

# Prince 2
| Kriterium | Bewertung|
|-----|---|
| Front-Matter | ja |
| Umfang | ja |
| Belege | ja |
| Links | ja |
| Formatierung | ja |
| Verlinkungen vorhanden | ja |
| Abbildungen | ja |
| Strukturierung des Beitrags | 10 |
| Rechtschreibung | 10 |
| Sprache | 10 |
| Inhalt | 10 |
| Einordnung in den Kontext | 10 |
| Ansprechend für Zielgruppe | 10 |

## Zusammenfassung

Kurze Zusammenfassung des/der Artikel
Der Artikel handelt von einem Best-Practice-Ansatz namens PRINCE 2. Der Ansatz beschäftigt sich mit der Ausgestaltung, die Organisation und das Management von Projekten. Der Artikel beschäftigt sich zuerst mit der Geschichte von PRINCE 2 bis er dann auf die Schlüsselelemente von PRINCE2 überleitet. Die Schlüsselelemente lauten: Die 7 PRINCE2 Grundprinzipien, die 7 PRINCE2 Themen, die 7 PRINCE2 Prozesse und die Anpassung von PRINCE2 an die Projektumgebung. Die 7 Themen von PRINCE 2 werden anschließend noch tiefer thematisiert. Diese sind Business Case, Organisation, Qualität, Pläne, Risiken, Änderungen sowie Fortschritt. Abgerundet wird der Artikel mit den Vor- und Nachteilen von PRINCE 2 sowie dessen Zertifizierung. 

## Positive Aspekte
Schön, dass du meinen Punkt mit den Vor- und Nachteilen übernommen hast. Wenn die Überschriften zur Wortanzahl dazuzählen, dann dürftest du da relativ sicher sein. Ansonsten wieder volle Punktzahl. Verlinkungen stimmen alle. Guter Artikel. 
## Negative Aspekte
Alle Aspekte wurden übernommen. Nichts mehr zu bemängeln.

2022-01-19 20:49 UTC, patrick203494 commented
Ach du Schande, da hab ich eure Namen komplett vertauscht :-( Tut mir leid! @Paulqe42kuno 
Das mit dem Youtube-Video ist echt schade, du warst echt sorgfältig :D 

Danke für eure positiven Rezensionen :-)

2022-01-19 22:35 UTC, Loris18 approved these changes
| Kriterium | Bewertung|
|-----|---|
| Front-Matter | ja |
| Umfang | ja|
| Belege | ja |
| Links | ja|
| Formatierung | ja|
| Verlinkungen vorhanden | ja|
| Abbildungen | ja |
| Strukturierung des Beitrags | 10 |
| Rechtschreibung | 10|
| Sprache | 10 |
| Inhalt | 10|
| Einordnung in den Kontext | 10|
| Ansprechend für Zielgruppe | 10|

# Zusammenfassung

Der Beitrag über Impediment Backlog handelt von Störfaktoren, die während eines Projektes auftreten können und deren visuelle Darstellung durch den Backlog. Dabei werden verschiedene Störfaktoren beleuchtet, sowie der idealtypische Ablauf beschrieben, diese Störfaktoren zu beseitigen. In dem Beitrag wird vor allem die Notwendigkeit eines Backlogs für Projekte herausgearbeitet und mit einem passenden Fazit abgerundet.

Der Beitrag bzgl. PRINCE2 setzt sich mit einem Best-Practice-Ansatz für Ausgestaltung, Organisation und Management von Projekten jeglicher Art auseinander. Dabei wird zunächst auf die Entwicklung des Ansatzes eingegangen. Anschließend werden die 4 Grundbausteine genannt und die 7 Grundprinzipen des Ansatzes erläutert. Abschließend erhält man einen Überblick über die Stärken und Schwächen des Ansatzes, sowie die Zertifizierung.

# Positive Aspekte

Auf das Feedback wurde eingegangen und alle Verbesserungsvorschläge sehr gut umgesetzt.  Beide Artikel lassen sich nach wie vor sehr flüssig und verständlich lesen, ohne dabei zu stark ins Detail zu gehen. Die Schaubilder sind passend gewählt und verständlich und auch die Strukturierung ist passend gewählt. Alles in allem sind deine beiden Beträge sehr gelungen.

# Negative Aspekte

Ich kann bis auf das fehlende Video bei der weiterführenden Literatur (1. Link) über Impediment Backlog keine negativen Aspekte anmerken, da deine Beiträge bereits in der 1. Reviewrunde sehr gelungen waren. Die Umsetzung der Verbesserungsvorschläge setzten der Sahnetorte, in Form der Beiträge, noch die Kirsche auf.

2022-01-25 14:01 UTC, merged