Update VMI_Matrix.md
ManagingProjectsSuccessfully/ManagingProjectsSuccessfully.github.io pull request #528
Opened 2021-12-22 13:29 UTC by Larf4

Im Rahmen des Updates wurden folgende Änderungen implementiert: 

# up67enyq: 

* Konsistenz verbessert
* (PSP) ergänzt
* Rechtschreibung verbessert
* Quellen gefixt

## Danke für dein Review!

# Saskia1403:

* Verlinkung müsste nun funktionieren
* Wortanzahl erhöht (härter als gedacht gewesen)
* PSP ergänzt
* Literatur nicht ergänzt, da nichts mehr zum Thema gefunden wurde
* Rechtschreibung geprüft
* Auf Bild hingewiesen

## Danke für dein Review!

 # Aseuc:

* Rechtschreibung verbessert
* Format angepasst
* Literatur konnte leider nicht ergänzt werden, da nichts weiter auffindbar

## Danke für dein Review!

2022-01-12 16:20 UTC, up67enyq commented
Kriterium | Bewertung
-- | --
Front-Matter | ja
Umfang | ja
Belege | ja
Links | ja
Formatierung | ja
Verlinkungen vorhanden | ja
Abbildungen | ja
Strukturierung des Beitrags | 10
Rechtschreibung | 10
Sprache | 10
Inhalt | 10
Einordnung in den Kontext | 10
Ansprechend für Zielgruppe | 10

# Zusammenfassung
Der Beitrag fasst die wichtigsten Informationen zu der VMI-Matrix zusammen. Es wird erklärt für was die Buchstaben V,M,I stehen und wie eine solche Matrix in der Regel erstellt wird. Weiter werden Vorteile wie Transparenz und Übersichtlichkeit Herausforderungen wie, zu viele Zuweisungen für einzelne Mitarbeiter gegenübergestellt.

# Positive Aspekte
Gute Abbildung um die VMI-Matrix zu erklären und im allgemeinen gut strukturiert.
Schöne Einbeziehung und Verlinkung auf weitere Beiträge des Kompendiums.
Sehr prägnante Formulierungen die das wichtigste knackig zusammenfassen
Verbesserungsvorschläge sehr gut umgesetzt

# Negative Aspekte
In der Einleitung "I für Informieren" I vom informieren klein.
Beim Punkt "Information" steht einmal "Mitarbeiter" sonst war überall "Mitarbeitende" vielleicht kann man das angleichen
Beim Punkt "Herausforderungen" Verantwortlicher vielleicht "gendern" mit Verantwortliche Person. (zumindest wenn das "Mitarbeitende" statt Mitarbeiter aus dem Grund ist) 
Dann wäre auch "Ansprechpartner" anzupassen

2022-01-13 10:39 UTC, Saskia1403 requested changes
| Kriterium | Bewertung|
|-----|---|
| Front-Matter | ja |
| Umfang | ja |
| Belege | ja |
| Links | ja |
| Formatierung | nein|
| Verlinkungen vorhanden | ja |
| Abbildungen | ja |
| Strukturierung des Beitrags | 8 |
| Rechtschreibung | 9 |
| Sprache | 10 |
| Inhalt | 10|
| Einordnung in den Kontext | 10|
| Ansprechend für Zielgruppe | 9 |

# Zusammenfassung

Der Artikel stellt die VMI-Matrix als klassisches Projektmanagementinstrument vor. Dafür wird schrittweise erklärt, wie eine VMI-Matrix erstellt wird und wofür die Buchstaben "V", "M" und "I" überhaupt stehen. Abschließend wird noch auf die Vorteile und die möglichen Herausforderungen der VMI-Matrix eingegangen.

# Positive Aspekte

Der Großteil meiner Kritik wurde umgesetzt, danke dafür.
Weiterhin ist der Artikel:
* gut in den Kontext eingebettet
* verständlich und ansprechend geschrieben

Darüber hinaus wird der Inhalt durch eine passend gewählte Abbildung sehr gut veranschaulicht.

# Negative Aspekte

* Link auf die Projektleitung funktioniert bei mir leider nicht (Anzeige page not found)
* Die Struktur der Überschriften ist hinsichtlich der Formatierung etwas durcheinandergeraten. Sollten die Überschriften zu den Vorteilen und den Herausforderungen als Unterüberschriften der Hauptüberschrift "Vorteile und Herausforderungen" gedacht sein, so sollten diese nicht optisch größer sein, als die Hauptüberschrift.
* kleine Fehler in der Rechtschreibung: 
 a) unter der Überschrift "Erstellung der Matrix" bei Schritt 1: senkrechte Spalte statt Senkrechte Spalte
b) unter der Überschrift "Erstellung der Matrix" bei Schritt 2: beteiligten Stakeholder

2022-01-13 21:15 UTC, Aseuc commented
| Kriterium | Bewertung|
|-----|---|
| Front-Matter | ja|
| Umfang | ja|
| Belege | ja|
| Links | ja|
| Formatierung | ja|
| Verlinkungen vorhanden | ja|
| Abbildungen | ja |
| Strukturierung des Beitrags |10 |
| Rechtschreibung | 9|
| Sprache | 10 |
| Inhalt | 10|
| Einordnung in den Kontext | 10|
| Ansprechend für Zielgruppe | 10|

# Zusammenfassung
In dem Beitrag VMI-Matrix handelt es sich um ein Tool, welches im Projektmanagement verwendet wird vor allem in der Projektplanung. Die VMI-Matrix gibt auch Aufschluss über die Verantwortlichkeiten in einem Projekt. Des Weiteren wird die VMI-Matrix durch ein Schaubild visuell dargestellt, um sich ein Bild von der Matrix machen zu können, sowie die verschiedenen Bedeutungen der Buchstaben V,M und I zu beschreiben. Danach werden die 5. Schritte der Matrix auf das Wesentliche begrenzt und verschaffen dem Leser eine schnelle Möglichkeit die VMI-Matrix zu verstehen. 

# Positive Aspekte
- alle Kritikpunkte aus dem ersten Review wurden umgesetzt. 
- alle Links funktionieren bei mir einwandfrei
    
# Negative Aspekte
- Komma zwischen „Tätigkeit, sowie“ entfernen
- Bei „dadurch ist klar wer“ muss zwischen klar und wer ein Komma 
- Bei „obersten, waagrechten Zeile“ sollte glaub ich kein Komma gesetzt werden
- „Das Verfahren bringt eine Vielzahl von Vorteilen mit sich, dennoch sind bei der Nutzung gewisse Herausforderungen zu Bedenken.“ müsste bedenken klein geschrieben werden

2022-01-13 21:22 UTC, Aseuc requested changes
- zwischen Tätigkeit und sowie kein Komma setzen
- zwischen oberste und waagerechte Zeile kein Komma setzen
- „Das Verfahren bringt eine Vielzahl von Vorteilen mit sich, dennoch sind bei der Nutzung gewisse Herausforderungen zu Bedenken.“ --> Bedenken muss klein geschrieben werden also bedenken

2022-01-25 14:07 UTC, merged