Update Scrum und Projektmanagementhandbuch
ManagingProjectsSuccessfully/ManagingProjectsSuccessfully.github.io pull request #530
Opened 2021-12-22 13:57 UTC by Harthauer

2022-01-13 15:05 UTC, LaHe27 requested changes
Kriterium | Bewertung|
|-----|---|
| Front-Matter | ja |
| Umfang | ja |
| Belege | ja |
| Links | ja |
| Formatierung | ja|
| Verlinkungen vorhanden | ja |
| Abbildungen | ja |
| Strukturierung des Beitrags | 10 |
| Rechtschreibung | 10|
| Sprache | 9 |
| Inhalt | 9 |
| Einordnung in den Kontext | 10|
| Ansprechend für Zielgruppe | 10|

# Zusammenfassung

Im den beiden Beitrag geht es um das Projektmanagementhandbuch und SCRUM. Beide Beiträge bieten einen guten Überblick über die Themen. Bei SCRUM wird auf die wichtigen Begriffe, den Ablauf sowie die Rollen eines SCRUM Teams eingegangen. Der Beitrag zum Projektmanagementhandbuch befasst sich mit der Abgrenzung zum Projekthandbuch, sowie Aufbau und Inhalten und den Vorteilen.

# Positive Aspekte

Ich finde beide Beiträge sind wirklich sehr gut strukturiert und bieten den richtigen Überblick über die Themen. Auch die Rechtschreibung ist sehr gut. 
Vor allem die Abgrenzung zum Projekthandbuch finde ich sehr gut und sehr wichtig.
Die Abbildung bei SCRUM finde ich sehr gut..

# Negative Aspekte

Es wurden noch Sätze ergänzt, somit enthalten die Beiträge nun beide die erforderte Wortanzahl.
Die Quellen wurden außerdem auch mit Überschriften versehen.
Auch andere Beiträge wurden verlinkt.

Mein Feedback wurde komplett umgesetzt und es gibt keine negativen Aspekte mehr.

2022-01-17 15:08 UTC, alexandermueller296 requested changes
Thema: Projektmanagementhandbuch

| Kriterium | Bewertung|
|-----|---|
| Front-Matter | ja |
| Umfang | ja |
| Belege | ja |
| Links | ja |
| Formatierung | ja |
| Verlinkungen vorhanden | ja |
| Abbildungen | ja |
| Strukturierung des Beitrags | 10 |
| Rechtschreibung | 10 |
| Sprache | 10 |
| Inhalt | 10 |
| Einordnung in den Kontext | 10 |
| Ansprechend für Zielgruppe | 10 |

# Zusammenfassung

Der Artikel beschäftigt sich nach einer kurzen Definition mi den Themen „Abgrenzung Projektmanagementhandbuch, Projekthandbuch und Projektdokumentation“, “Aufbau und Inhalt“, „Möglichen Inhalt und Nutzen des Projektmanagementhandbuch“.

# Positive Aspekte

Schön leserlicher Artikel, gute Sprache, gute Rechtschreibung. Er ist klar strukturiert und in einer einfachen Sprache formuliert.

# Negative Aspekte

Es wurden die Mängel beseitigt und die Wörter auf über 500 erhöht.

Thema: SCRUM

| Kriterium | Bewertung|
|-----|---|
| Front-Matter | ja |
| Umfang | ja |
| Belege | ja |
| Links | ja |
| Formatierung | ja |
| Verlinkungen vorhanden | ja |
| Abbildungen | ja |
| Strukturierung des Beitrags | 10 |
| Rechtschreibung | 10 |
| Sprache | 10 |
| Inhalt | 10 |
| Einordnung in den Kontext | 10 |
| Ansprechend für Zielgruppe | 10 |

# Zusammenfassung

Der Artikel „Scrum“ erklärt zuerst in einer kurzen Übersicht das Thema im Allgemeinen mit einer Definition. Zeigt dann wichtige Begriffe in Scrum und den Ablauf mit den verschiedenen Phasen. Zuletzt wird noch das Scrum Team mit Hilfe einer Tabelle erläutert.

# Positive Aspekte

Der Artikel ist sehr gut strukturiert und man sieht den Roten Faden von Anfang an. Schön sind die Verlinkungen, welche in den Fließtext eingearbeitet sind. 7 Quellen geben ein breites Spektrum an Wissensquellen. Es wurde mit verschiedenen Mitteln gearbeitet (Stichpunkte, Tabelle). guter Beitrag.

# Negative Aspekte

Alle negativen Punkte wurden verbessert.

2022-01-18 21:43 UTC, xe28dita commented
**Projektmanagementhandbuch**

| Kriterium | Bewertung|
|-----|---|
| Front-Matter | ja|
| Umfang | ja|
| Belege | ja|
| Links | ja|
| Formatierung | ja|
| Verlinkungen vorhanden | ja|
| Abbildungen | ja|
| Strukturierung des Beitrags | 10 |
| Rechtschreibung | 10|
| Sprache | 10|
| Inhalt | 10|
| Einordnung in den Kontext | 10|
| Ansprechend für Zielgruppe | 10|

# Zusammenfassung

Der Beitrag ist gut und klar strukturiert. Zudem ist ein durchgehender roter Faden vorhanden.


# Positive Aspekte

Der Umfang passt nun, inhaltlich nach wie vor super. 

# Negative Aspekte

Nichts zu meckern

**Scrum**

| Kriterium | Bewertung|
|-----|---|
| Front-Matter | ja|
| Umfang | ja|
| Belege | ja|
| Links | ja|
| Formatierung | ja|
| Verlinkungen vorhanden | ja|
| Abbildungen | ja|
| Strukturierung des Beitrags | 10 |
| Rechtschreibung | 10|
| Sprache | 10|
| Inhalt | 10|
| Einordnung in den Kontext | 10|
| Ansprechend für Zielgruppe | 10|

# Zusammenfassung

Der Beitrag ist gut strukturiert und geht vom Allgemeinen zum Speziellen. Zunächst wird allgemein definiert, danach wichtige Begriffe genannt und im Anschluss der Ablauf des Prozesses näher geschildert.


# Positive Aspekte

Du hast meinen Vorschlag beachtet und den Satzbau im ersten Abschnitt teilweise geändert. Somit lässt sich nun der Abschnitt flüssiger und schöner lesen.

# Negative Aspekte

Auch hier nichts auszusetzen.

2022-01-22 20:57 UTC, xe28dita reviewed
**Projektmanagementhandbuch**

| Kriterium | Bewertung|
|-----|---|
| Front-Matter | ja|
| Umfang | ja|
| Belege | ja|
| Links | ja|
| Formatierung | ja|
| Verlinkungen vorhanden | ja|
| Abbildungen | ja|
| Strukturierung des Beitrags | 10 |
| Rechtschreibung | 10|
| Sprache | 10|
| Inhalt | 10|
| Einordnung in den Kontext | 10|
| Ansprechend für Zielgruppe | 10|

# Zusammenfassung

Der Beitrag ist gut und klar strukturiert. Zudem ist ein durchgehender roter Faden vorhanden.


# Positive Aspekte

Der Umfang passt nun, inhaltlich nach wie vor super. 

# Negative Aspekte

Nichts zu meckern

**Scrum**

| Kriterium | Bewertung|
|-----|---|
| Front-Matter | ja|
| Umfang | ja|
| Belege | ja|
| Links | ja|
| Formatierung | ja|
| Verlinkungen vorhanden | ja|
| Abbildungen | ja|
| Strukturierung des Beitrags | 10 |
| Rechtschreibung | 10|
| Sprache | 10|
| Inhalt | 10|
| Einordnung in den Kontext | 10|
| Ansprechend für Zielgruppe | 10|

# Zusammenfassung

Der Beitrag ist gut strukturiert und geht vom Allgemeinen zum Speziellen. Zunächst wird allgemein definiert, danach wichtige Begriffe genannt und im Anschluss der Ablauf des Prozesses näher geschildert.


# Positive Aspekte

Du hast meinen Vorschlag beachtet und den Satzbau im ersten Abschnitt teilweise geändert. Somit lässt sich nun der Abschnitt flüssiger und schöner lesen.

# Negative Aspekte

Auch hier nichts auszusetzen.

2022-01-25 14:07 UTC, merged