MarleneMeyer_Projektplanung_Offshoring-Projekte
ManagingProjectsSuccessfully/ManagingProjectsSuccessfully.github.io pull request #539
Opened 2021-12-22 14:41 UTC by MarleneMMeyer

Zu Reviews:
-Verlinkungen wurden hinzugefügt
-Umfang erweitert 
-Bild zugeschnitten
-Weitere Literatur wurde angegeben

2022-01-11 15:34 UTC, felhaag reviewed
# Projekt-Offshoring

| Kriterium | Bewertung|
|-----|---|
| Front-Matter | ja |
| Umfang | ja |
| Belege | ja |
| Links | ja |
| Formatierung | ja |
| Verlinkungen vorhanden | ja |
| Abbildungen | ja |
| Strukturierung des Beitrags | 10 |
| Rechtschreibung | 10|
| Sprache | 10 |
| Inhalt | 9 |
| Einordnung in den Kontext | 9 |
| Ansprechend für Zielgruppe | 9 |

## Zusammenfassung

Der Beitrag befasst sich mit der Definition und den Anwendungsbereichen des Projekt-Offshoring. 
Offshoring ist die Verlagerung betrieblicher Aktivitäten ins Ausland. Entsprechend hat sich das deutsche Wort "Auslandsverlagerung" herausgebildet. Unter dem Begriff "Onshoring" versteht man außerdem die Verlagerung im Inland. 
Zudem wird auf positive und kritische Aspekte des Offshoring eingegangen. 

## Positive Aspekte

Die Struktur und Rechtschreibung des Beitrags ist sehr gut. Der Beitrag wurde kompakt gehalten, aber trotzdem sehr informativ. Die Abbildung ist anschaulich und bietet einen schönen Einstieg in das Thema. Belege sind in großer Anzahl vorhanden. Gute Einbindung anderer Themenbereiche.
Kritik aus dem 1. Review wurde angenommen und umgesetzt.

## Negative Aspekte

Keine negativen Aspekte vorhanden, da die Kritik sehr gut umgesetzt wurde.

# Projektplanung

| Kriterium | Bewertung|
|-----|---|
| Front-Matter | ja |
| Umfang | ja |
| Belege | ja |
| Links | ja |
| Formatierung | ja |
| Verlinkungen vorhanden | ja |
| Abbildungen | ja |
| Strukturierung des Beitrags | 10 |
| Rechtschreibung | 10 |
| Sprache | 10 |
| Inhalt | 9 |
| Einordnung in den Kontext | 9 |
| Ansprechend für Zielgruppe | 9 |

## Zusammenfassung

Der Beitrag handelt von der Projektplanung im klassischen Projektmanagement. Hierbei wird nicht nur auf die Perspektiven und Modelle eingegangen, sondern auch Kritik an der Thematik geübt. 
Projektplanung ist der Prozess, Ablauf, Umfang, Kosten, Ressourcen, Qualität und andere Aspekte eines Projekts zu planen. Das Wasserfall- und Spiralmodell sind zwei bekannte Vorgehensmodelle des klassischen Projektmanagements.

## Positive Aspekte

Der Beitrag enthält weit über 500 Wörter. Die Struktur und Sprache ist sehr ansehnlich. Die Modelle werden durch Abbildungen veranschaulicht. Es sind viele Belege vorhanden und markiert. 
Kritik aus dem 1. Review wurde angenommen und umgesetzt.

## Negative Aspekte

Keine negativen Aspekte vorhanden, da die Kritik sehr gut umgesetzt wurde.

2022-01-11 15:40 UTC, felhaag requested changes
# Projekt-Offshoring

| Kriterium | Bewertung|
|-----|---|
| Front-Matter | ja |
| Umfang | ja |
| Belege | ja |
| Links | ja |
| Formatierung | ja |
| Verlinkungen vorhanden | ja |
| Abbildungen | ja |
| Strukturierung des Beitrags | 10 |
| Rechtschreibung | 10|
| Sprache | 10 |
| Inhalt | 9 |
| Einordnung in den Kontext | 9 |
| Ansprechend für Zielgruppe | 9 |

## Zusammenfassung

Der Beitrag befasst sich mit der Definition und den Anwendungsbereichen des Projekt-Offshoring. 
Offshoring ist die Verlagerung betrieblicher Aktivitäten ins Ausland. Entsprechend hat sich das deutsche Wort "Auslandsverlagerung" herausgebildet. Unter dem Begriff "Onshoring" versteht man außerdem die Verlagerung im Inland. 
Zudem wird auf positive und kritische Aspekte des Offshoring eingegangen. 

## Positive Aspekte

Die Struktur und Rechtschreibung des Beitrags ist sehr gut. Der Beitrag wurde kompakt gehalten, aber trotzdem sehr informativ. Die Abbildung ist anschaulich und bietet einen schönen Einstieg in das Thema. Belege sind in großer Anzahl vorhanden. Gute Einbindung anderer Themenbereiche.
Kritik aus dem 1. Review wurde angenommen und umgesetzt.

## Negative Aspekte

Keine negativen Aspekte vorhanden, da die Kritik sehr gut umgesetzt wurde.

# Projektplanung

| Kriterium | Bewertung|
|-----|---|
| Front-Matter | ja |
| Umfang | ja |
| Belege | ja |
| Links | ja |
| Formatierung | ja |
| Verlinkungen vorhanden | ja |
| Abbildungen | ja |
| Strukturierung des Beitrags | 10 |
| Rechtschreibung | 10 |
| Sprache | 10 |
| Inhalt | 9 |
| Einordnung in den Kontext | 9 |
| Ansprechend für Zielgruppe | 9 |

## Zusammenfassung

Der Beitrag handelt von der Projektplanung im klassischen Projektmanagement. Hierbei wird nicht nur auf die Perspektiven und Modelle eingegangen, sondern auch Kritik an der Thematik geübt. 
Projektplanung ist der Prozess, Ablauf, Umfang, Kosten, Ressourcen, Qualität und andere Aspekte eines Projekts zu planen. Das Wasserfall- und Spiralmodell sind zwei bekannte Vorgehensmodelle des klassischen Projektmanagements.

## Positive Aspekte

Der Beitrag enthält weit über 500 Wörter. Die Struktur und Sprache ist sehr ansehnlich. Die Modelle werden durch Abbildungen veranschaulicht. Es sind viele Belege vorhanden und markiert. 
Kritik aus dem 1. Review wurde angenommen und umgesetzt.

## Negative Aspekte

Keine negativen Aspekte vorhanden, da die Kritik sehr gut umgesetzt wurde.

2022-01-17 11:42 UTC, Polina0402 requested changes
| Kriterium | Bewertung|
|-----|---|
| Front-Matter | ja |
| Umfang | ja |
| Belege | ja |
| Links | ja |
| Formatierung | ja |
| Verlinkungen vorhanden | ja |
| Abbildungen | ja |
| Strukturierung des Beitrags | 10 |
| Rechtschreibung | 10 |
| Sprache | 10 |
| Inhalt | 10 |
| Einordnung in den Kontext | 10 |
| Ansprechend für Zielgruppe | 10 |

# Zusammenfassung

Der Artikel befasst sich mit Offshoring. Darunter versteht man die Auslagerung betrieblicher Aktivitäten ins Ausland. Man geht zuerst auf die Vorteile des Offshorings ein und rundet es zum Schluss mit Kritikpunkten ab.

# Positive Aspekte

Der Text ist sehr schön zu lesen. Die Kritik wurde wahrgenommen und man hat jetzt gut gesetzte Verlinkungen, die das Thema erweitern. Zusätzlich hat der Text jetzt den richtigen Umfang. Die erweiterte Literatur wurde angegeben und alle Quellen funktionieren. Der Text ist informativ und kompakt gestaltet, optimal für die Zielgruppe.

# Negative Aspekte

Die Kritik wurde gut umgesetzt und es gibt nichts mehr zu bemängeln.

2022-01-19 17:06 UTC, corinnaneubauer requested changes
# Projekt-Offshoring

| Kriterium | Bewertung|
|-----|---|
| Front-Matter | ja|
| Umfang | ja |
| Belege | ja|
| Links | ja|
| Formatierung | ja|
| Verlinkungen vorhanden | ja|
| Abbildungen | ja|
| Strukturierung des Beitrags | 10 |
| Rechtschreibung | 10|
| Sprache | 10 |
| Inhalt | 10|
| Einordnung in den Kontext | 10|
| Ansprechend für Zielgruppe | 10|

# Zusammenfassung

Der Beitrag befasst sich mit dem Thema Projekt-Offshoring, worunter man die Auslagerung betrieblicher Aktivitäten ins Ausland versteht. Dabei wird sowohl auf die positiven Aspekte als auch auf die mit der Thematik verbundenen Risiken eingegangen. Zudem wird Offshoring deutlich von anderen Themen wie „Onshoring“ oder „Outsourcing“ abgegrenzt.

# Positive Aspekte

Die Rechtschreibung ist fehlerfrei, der Beitrag ist gut strukturiert und informativ. Zudem ist er schön kompakt gehalten und angenehm zu lesen. 

# Negative Aspekte

Keine. Alle Kritikpunkte wurden erfolgreich umgesetzt. 






# Projektplanung

| Kriterium | Bewertung|
|-----|---|
| Front-Matter | ja|
| Umfang | ja |
| Belege | ja|
| Links | ja|
| Formatierung | ja|
| Verlinkungen vorhanden | ja|
| Abbildungen | ja|
| Strukturierung des Beitrags | 10 |
| Rechtschreibung | 10|
| Sprache | 10 |
| Inhalt | 10|
| Einordnung in den Kontext | 10|
| Ansprechend für Zielgruppe | 10|

# Zusammenfassung

Der Beitrag beschäftigt sich mit dem Thema der Projektplanung im klassischen Projektmanagement. Zudem werden in diesem Zusammenhang das Wasserfallmodell und das Spiralmodell vorgestellt sowie kritische Aspekte der Projektplanung im klassischen Projektmanagement beleuchtet.

# Positive Aspekte

Der Beitrag ist gut strukturiert, frei von Rechtschreibfehlern und schön zu lesen. Er enthält die wichtigsten Informationen und die Abbildungen sorgen für ein besseres Verständnis der Modelle. 

# Negative Aspekte

Alle Kritikpunkte wurden erfolgreich umgesetzt, von daher ist an dem Beitrag nichts auszusetzen.

2022-01-25 14:07 UTC, merged