Abschlussanalyse
ManagingProjectsSuccessfully/ManagingProjectsSuccessfully.github.io pull request #545
Opened 2021-12-22 15:24 UTC by medjeara

In meinen aktualisierten Beitrag bin ich auf die Punkte Rechtschreibung, Sprache sowie Formatierung eingegangen, die von den Reviewern bemängelt wurde. Bei den restlichen Aspekten waren die Reviewer sehr zufrieden gewesen.

2022-01-11 13:59 UTC, Juliakau commented
| Kriterium | Bewertung|
|-----|---|
| Front-Matter | ja |
| Umfang | ja |
| Belege | ja |
| Links | ja |
| Formatierung | ja |
| Verlinkungen vorhanden | nein |
| Abbildungen | ja |
| Strukturierung des Beitrags | 10 |
| Rechtschreibung | 10 |
| Sprache | 10 |
| Inhalt | 10 |
| Einordnung in den Kontext | 10 |
| Ansprechend für Zielgruppe | 10 |

# Zusammenfassung

Alles in allem ein sehr gelungener Artikel. 
Sehr gute Hinleitung zu dem Thema, tolle Untergliederung, interessant und lässt sich gut lesen. 
Alle Themen bis auf die Verlinkungen im Text wurden erfüllt. (Vielleicht gibt es keine möglichen Themen zum Verlinken)

# Positive Aspekte

- sehr ansprechend und alles logisch erklärt
- Quellenangaben und weiterführende Links
- Abbildung zeigt einen guten Überblick
- tolle Untergliederung -> sehr Übersichtlich

# Negative Aspekte

- keine Verlinkungen zu anderen Berichten in dem Text

2022-01-12 12:47 UTC, FerdinandMerbecks requested changes
| Kriterium | Bewertung|
|-----|---|
| Front-Matter | ja |
| Umfang | ja |
| Belege | ja  |
| Links | ja |
| Formatierung | ja |
| Verlinkungen vorhanden | ja |
| Abbildungen | ja |
| Strukturierung des Beitrags | 10 |
| Rechtschreibung | 10 |
| Sprache | 10 |
| Inhalt | 10 |
| Einordnung in den Kontext | 10 |
| Ansprechend für Zielgruppe | 10 |

# Zusammenfassung

Der Artikel führt zu Beginn passend zum Thema der Abschlussanalyse hin und rückt hierbei den Soll- Ist Vergleich in den Vordergrund. Anschließend erfolgen die Erläuterungen des Prozessablaufes der Abschlussanalyse. Teilweise gut von Beispielen untermauert ist jetzt die Formatierung vorhanden und trägt nun zum besseren Verständnis des Textes bei. Abgerundet wird der Artikel durch ein Fazit, welches den Plan-/ Istkostenvergleich hervorhebt.



# Positive Aspekte

- sehr gute Strukturierung des Beitrags durch die Untergliederung 
- sehr gut verständlich und nachvollziehbar
- durch Abbildung noch bessere Veranschaulichung





# Negative Aspekte

- Verlinkungen zu angrenzenden Themen vielleicht versuchen mit in den Text einzubauen

2022-01-13 19:31 UTC, Juliakau requested changes
| Kriterium | Bewertung|
|-----|---|
| Front-Matter | ja |
| Umfang | ja |
| Belege | ja |
| Links | ja |
| Formatierung | ja |
| Verlinkungen vorhanden | nein |
| Abbildungen | ja |
| Strukturierung des Beitrags | 10 |
| Rechtschreibung | 10 |
| Sprache | 10 |
| Inhalt | 10 |
| Einordnung in den Kontext | 10 |
| Ansprechend für Zielgruppe | 10 |

# Zusammenfassung

Alles in allem ein sehr gelungener Artikel. 
Sehr gute Hinleitung zu dem Thema, tolle Untergliederung, interessant und lässt sich gut lesen. 
Alle Themen bis auf die Verlinkungen im Text wurden erfüllt. (Vielleicht gibt es keine möglichen Themen zum Verlinken)

# Positive Aspekte

- sehr ansprechend und alles logisch erklärt
- Quellenangaben und weiterführende Links
- Abbildung zeigt einen guten Überblick
- tolle Untergliederung -> sehr Übersichtlich

# Negative Aspekte

- keine Verlinkungen zu anderen Berichten in dem Text

2022-01-18 11:23 UTC, ValerieGF requested changes
| Kriterium | Bewertung|
|-----|---|
| Front-Matter | ja |
| Umfang | ja|
| Belege | ja |
| Links | ja|
| Formatierung | ja|
| Verlinkungen vorhanden | nein |
| Abbildungen | ja |
| Strukturierung des Beitrags | 10 |
| Rechtschreibung | 10|
| Sprache | 10 |
| Inhalt | 10|
| Einordnung in den Kontext | 9|
| Ansprechend für Zielgruppe | 10|

# Zusammenfassung

Der Artikel beginnt mit einer Einführung ins Thema der Abschlussanalyse. Danach wird die konkrete Aufgabe der Abschlussanalyse mit dem Soll-Ist-Vergleich erläutert. Daraufhin wird genauer auf den Prozessablauf eingegangen und abschließend wird ein Fazit gezogen, wo nochmals die große Rolle des Plan-/Istkostenvergleich hervorgehoben wird. Der Text ist im Allgemeinen sehr gutgeschrieben.

# Positive Aspekte

•	Gute Struktur
•	Inhalt ist verständlich
•	Sehr ansprechend, aufgrund der Untergliederung des Themas
•	Die Beispiele und die Abbildung untermauern gut den Inhalt

# Negative Aspekte

Keine Verlinkung zu anderen Themen vorhanden.

2022-01-18 15:14 UTC, medjeara commented
@ValerieGF @Juliakau die Verlinkungen sind im Beitrag vorhanden, allerdings nach dem Fazit.

2022-01-25 14:07 UTC, merged