Update 2 Podio_PM_Tool
ManagingProjectsSuccessfully/ManagingProjectsSuccessfully.github.io pull request #562
Opened 2021-12-22 17:22 UTC by Paulqe42kuno

Hallo Zusammen,

zuerst einmal vielen Dank für das Feedback. Ich habe die Rechtschreibverbesserungen umgesetzt und den Text selbst ein paar mal durchgelesen. Ich hoffe ich habe jetzt keine Rechtschreibfehler mehr. Das war auch der Hauptkritikpunkt. Ein Vorschlag war, den letzten Satz meiner Zusammenfassung in den Abschnitt Geschichte zu packen. Ich habe das jetzt mal nicht gemacht, da ich denke dass es in den ersten Absatz besser passt. Ein weiterer Vorschlag war es, die Unterabsätze unter dem Absatz Funktionen weiter voneinander zu trennen. Dies habe ich umgesetzt. Als letztes habe ich noch das PodioLogo eingefügt, um noch ein Bild eingefügt zu haben. Ich dachte zuerst die Tabelle reicht als Abbildung. 

Vielen Dank nochmals und frohe Weihnachten

2022-01-15 16:36 UTC, larissadiscua commented
| Kriterium | Bewertung|
|-----|---|
| Front-Matter | ja |
| Umfang | ja |
| Belege | ja |
| Links | ja |
| Formatierung | ja |
| Verlinkungen vorhanden | ja |
| Abbildungen | ja |
| Strukturierung des Beitrags | 10 |
| Rechtschreibung | 10 |
| Sprache | 10 |
| Inhalt | 10 |
| Einordnung in den Kontext | 10 |
| Ansprechend für Zielgruppe | 10 |

# Zusammenfassung

Der Artikel befasst sich mit Podio, einem Projektmanagement-Tool. Zunächst wird ganz kurz die Geschichte des Tools erwähnt, daraufhin geht es weiter mit den verschiedenen Funktionen, die geboten werden. Von Apps über Workspaces, bis hin zu Online-Meetings wird hier einiges angeboten. Zum Schluss erfährt man noch Näheres zu den verschiedenen Paketen, deren Features und Kosten.

# Positive Aspekte

Der Beitrag ist trotz viele Fremdwörter und Fachbegriffe gut verständlich und leserlich. Man bekommt einen guten Überblick über das Thema, ohne zu sehr ins Detail zu gehen. 
Zudem gefällt mir die Tabelle gut, da sie einem die verschiedenen Pakete mit deren jeweiligen Features zeigt.
Die Grammatik und Rechtschreibung wurde überarbeitet, somit ist der Artikel nun auch sprachlich sehr gelungen. Zusätzlich wurde ein Bild hinzugefügt und der Artikel ist vollständig.

# Negative Aspekte

Alle negativen Aspekte wurden überarbeitet

2022-01-16 11:09 UTC, larissadiscua approved these changes
| Kriterium | Bewertung|
|-----|---|
| Front-Matter | ja |
| Umfang | ja |
| Belege | ja |
| Links | ja |
| Formatierung | ja |
| Verlinkungen vorhanden | ja |
| Abbildungen | ja |
| Strukturierung des Beitrags | 10 |
| Rechtschreibung | 10 |
| Sprache | 10 |
| Inhalt | 10 |
| Einordnung in den Kontext | 10 |
| Ansprechend für Zielgruppe | 10 |

# Zusammenfassung

Der Artikel befasst sich mit Podio, einem Projektmanagement-Tool. Zunächst wird ganz kurz die Geschichte des Tools erwähnt, daraufhin geht es weiter mit den verschiedenen Funktionen, die geboten werden. Von Apps über Workspaces, bis hin zu Online-Meetings wird hier einiges angeboten. Zum Schluss erfährt man noch Näheres zu den verschiedenen Paketen, deren Features und Kosten.

# Positive Aspekte

Der Beitrag ist trotz viele Fremdwörter und Fachbegriffe gut verständlich und leserlich. Man bekommt einen guten Überblick über das Thema, ohne zu sehr ins Detail zu gehen. 
Zudem gefällt mir die Tabelle gut, da sie einem die verschiedenen Pakete mit deren jeweiligen Features zeigt.
Die Grammatik und Rechtschreibung wurde überarbeitet, somit ist der Artikel nun auch sprachlich sehr gelungen. Zusätzlich wurde ein Bild hinzugefügt und der Artikel ist vollständig.

# Negative Aspekte

Alle negativen Aspekte wurden überarbeitet

2022-01-19 14:01 UTC, bilgesb commented
| Kriterium | Bewertung|
|-----|---|
| Front-Matter | ja|
| Umfang | ja|
| Belege | ja|
| Links | ja|
| Formatierung | ja|
| Verlinkungen vorhanden | ja|
| Abbildungen | ja|
| Strukturierung des Beitrags | 10 |
| Rechtschreibung |10|
| Sprache |10 |
| Inhalt | 10|
| Einordnung in den Kontext |10|
| Ansprechend für Zielgruppe | 10|

# Zusammenfassung
In diesem Artikel wird ein Projektmanagement-Tool namens Podio behandelt. Die Besonderheit dieses Tools ist es, dass ein CRM System integriert ist und somit den Nutzern die Anwendung durch diverse Apps, Workspaces, Kalender und Kommunikationsmöglichkeiten erleichtert.

# Positive Aspekte
Der Artikel ist sehr gut verständlich. 
Die Tabelle ist sehr anschaulich und ist somit sehr gut gelungen! 
Die Rechtschreibfehler wurden verbessert.
Ein gelungener Beitrag.
# Negative Aspekte
Es fehlt leider die Quelle zu deinem Bild.

2022-01-19 14:04 UTC, bilgesb requested changes
| Kriterium | Bewertung|
|-----|---|
| Front-Matter | ja|
| Umfang | ja|
| Belege | ja|
| Links | ja|
| Formatierung | ja|
| Verlinkungen vorhanden | ja|
| Abbildungen | ja|
| Strukturierung des Beitrags | 9 |
| Rechtschreibung |10|
| Sprache |10 |
| Inhalt | 10|
| Einordnung in den Kontext |10|
| Ansprechend für Zielgruppe | 10|

# Zusammenfassung
In diesem Artikel wird ein Projektmanagement-Tool namens Podio behandelt. Die Besonderheit dieses Tools ist es, dass ein CRM System integriert ist und somit den Nutzern die Anwendung durch diverse Apps, Workspaces, Kalender und Kommunikationsmöglichkeiten erleichtert.

# Positive Aspekte
Der Artikel ist sehr gut verständlich. 
Die Tabelle ist sehr anschaulich und ist somit sehr gut gelungen! 
Die Rechtschreibfehler wurden verbessert.
Ein gelungener Beitrag.
# Negative Aspekte
Es fehlt leider die Quelle zu deinem Bild.

2022-01-19 22:10 UTC, Loris18 approved these changes
| Kriterium | Bewertung|
|-----|---|
| Front-Matter | ja |
| Umfang | ja |
| Belege | ja |
| Links | ja|
| Formatierung | ja|
| Verlinkungen vorhanden | ja |
| Abbildungen | ja |
| Strukturierung des Beitrags | 9 |
| Rechtschreibung | 10|
| Sprache | 10 |
| Inhalt | 10|
| Einordnung in den Kontext | 10|
| Ansprechend für Zielgruppe | 10|

# Zusammenfassung

Der vorliegende Beitrag befasst sich mit Podio, einem cloudbasierten Projektmanagement Tool. Dabei wird zu Beginn auf die Besonderheiten und die Geschichte hinter dem Tool eingegangen. Danach werden die verschiedenen Funktionen des Tools sehr detailliert behandelt und erklärt. Zum einen werden die verschiedenen Apps und deren potentiellen Einsatzmöglichkeiten behandelt. Zum anderen wird das Workspace und die Kommunikationskanäle, sowie Aufgabenverteilung erläutert. Zum Abschluss erhält man eine Übersicht über die verschiedenen Versionen des Tool und deren Features.

# Positive Aspekte

Die Verbesserungsvorschläge wurden umgesetzt und vor allem die Rechtschreibung berichtigt. Der Beitrag lässt sich flüssig lesen und ist sehr interessant gestaltet, trotz der vielen Fachbegriffe. Das gewählte Schaubild bzgl. den verschiedenen Versionen gibt einen sehr guten Überblick über die features und ist sehr gelungen. Insgesamt gibt der Beitrag einen sehr guten Überblick über die Thematik mit den verschiedenen Aspekten des Tools, der sehr verständlich ist und Informationen kompakt bündelt.

# Negative Aspekte

Für das Logo von Podio (1. Bild) fehlt die Quellenangabe. Möglicherweise hätte man das Logo auch weglassen können, da es keine Informationen vermittelt.

2022-01-25 14:08 UTC, merged