Polina0402_Verantwortlichkeiten
ManagingProjectsSuccessfully/ManagingProjectsSuccessfully.github.io pull request #563
Opened 2021-12-22 17:23 UTC by Polina0402

2021-12-22 17:37 UTC, Polina0402 commented
Ich habe den Link zu den Organisationsprojekten entfernt, da es diesen Beitrag nicht mehr gibt. Stattdessen habe ich einen Link zu "Projekt" erstellt. Ich habe die Sätze „Übernahme der Verantwortung über ein Projekt“ im dritten Absatz schöner formuliert, damit sie sich nicht wiederholen. Zusätzlich habe ich Synonyme für "Verantwortlich" in meiner letzten Tabelle eingefügt. Zu beiden Abbildungen sind die Unterschriften jetzt gleich formatiert und an der selben Position (unter dem Bild). Der Satz unter der Unterschrift des zweiten Bildes ist ein Zitat, wie es von Github automatisch formatiert wird. Zuletzt habe ich noch die zwei Unterschriften unter der Überschrift "Projektbezogene Verantwortung" einmal kleiner gemacht, damit es übersichtlicher aussieht.

2022-01-11 15:43 UTC, felhaag requested changes
| Kriterium | Bewertung|
|-----|---|
| Front-Matter | ja |
| Umfang | ja |
| Belege | ja |
| Links | ja |
| Formatierung | ja |
| Verlinkungen vorhanden | ja |
| Abbildungen | ja |
| Strukturierung des Beitrags | 10 |
| Rechtschreibung | 10|
| Sprache | 10 |
| Inhalt | 10|
| Einordnung in den Kontext | 10|
| Ansprechend für Zielgruppe | 10|

# Zusammenfassung

Der Beitrag befasst sich mit der Thematik Verantwortlichkeiten im Projektmanagement. 
Hierbei wird zunächst auf grundlegende Informationen zum Thema eingegangen. Folgerichtig wird dies dann auf das Projektmanagement und deren Rollen bezogen.
Verantwortlichkeit wird als Zuständigkeit für anspruchsvolle Tätigkeitsbereiche im Projekt beschrieben. Dabei definieren diesen Begriff drei untrennbare Bestandteile:
- Aufgabe
- Befugnis
- Rechenschaftspflicht

# Positive Aspekte

Der Beitrag enthält mehr als 500 Wörter. Die Struktur und Sprache ist sehr ansehnlich. Die Abbildungen sind übersichtlich und informativ. Es werden Verweise auf angrenzende Themen gezeigt. Es wurden viele Belege benutzt. Allgemein ist der Beitrag schön lesen. 

# Negative Aspekte

Keine vorhanden, da die Kritik erfolgreich umgesetzt wurde.

2022-01-17 10:37 UTC, 29834 reviewed
| Kriterium | Bewertung|
|-----|---|
| Front-Matter | ja |
| Umfang | ja |
| Belege | ja |
| Links | ja |
| Formatierung | ja |
| Verlinkungen vorhanden | ja |
| Abbildungen | ja |
| Strukturierung des Beitrags | 10 |
| Rechtschreibung | 10|
| Sprache | 10 |
| Inhalt | 10|
| Einordnung in den Kontext | 10|
| Ansprechend für Zielgruppe | 10|

# Zusammenfassung

Der Artikel befasst sich Verantwortlichkeiten im Zusammenhang mit Projekten. Zum Thema hingeleitet wird mit einer Allgemeinen Einführung und dann wird genauer auf Rollen und Verantwortung in Projekten eingegangen. 

# Positive Aspekte

Die Anmerkungen der Reviews wurden erfolgreich umgesetzt. Es gab hauptsächlich Punkte zur Formatierung und Ansicht, wie z.B. Überschriften und Verlinkungen, der Artikel ist jetzt übersichtlich und lässt sich sehr angenehm lesen, es gibt nichts daran auszusetzen.

# Negative Aspekte

Keine, da alles umgesetzt wurde.

2022-01-19 17:01 UTC, corinnaneubauer requested changes
| Kriterium | Bewertung|
|-----|---|
| Front-Matter | ja|
| Umfang | ja |
| Belege | ja|
| Links | ja|
| Formatierung | ja|
| Verlinkungen vorhanden | ja|
| Abbildungen | ja|
| Strukturierung des Beitrags | 10 |
| Rechtschreibung | 10|
| Sprache | 10 |
| Inhalt | 10|
| Einordnung in den Kontext | 10|
| Ansprechend für Zielgruppe | 10|

# Zusammenfassung

Der Beitrag befasst sich mit dem Thema Verantwortlichkeiten. Dem Leser wird ein guter Überblick über das Thema vermittelt. Dabei wird zunächst auf Grundlegendes in Bezug auf Verantwortung eingegangen und schließlich speziell auf die Verantwortung im Projekt. 

# Positive Aspekte

Alle Kritikpunkte aus den Reviews wurden erfolgreich umgesetzt. Der Beitrag ist gut strukturiert und sprachlich einwandfrei. Die Abbildungen sind verständlich und Verlinkungen zu anderen Themen sind ebenfalls vorhanden. 

# Negative Aspekte

Ich habe keine negativen Aspekte mehr gefunden. Alle Kritikpunkte wurden erfolgreich umgesetzt.

2022-01-25 14:08 UTC, merged