Action_Points und Megatrends
ManagingProjectsSuccessfully/ManagingProjectsSuccessfully.github.io pull request #565
Opened 2021-12-22 17:46 UTC by SaskiaHe

Aktuelle Versionen mit den Anmerkungen aus den Reviews

2022-01-16 07:01 UTC, Tjara1 requested changes
| Kriterium | Bewertung|
|-----|---|
| Front-Matter | ja |
| Umfang | ja |
| Belege | ja |
| Links | ja |
| Formatierung | ja |
| Verlinkungen vorhanden | ja |
| Abbildungen | ja |
| Strukturierung des Beitrags | 10 |
| Rechtschreibung | 10|
| Sprache | 10 |
| Inhalt | 10|
| Einordnung in den Kontext | 10|
| Ansprechend für Zielgruppe | 10|

# Zusammenfassung

Der Artikel behandelt das Thema Action Points. Diese können helfen, große Projekte besser zu strukturieren. Action Points sind Arbeitspakete innerhalb des Projekts. Diese Pakete beinhalten unterschiedlichste Themen wie beispielsweise eine Erläutering, eine Übersicht über das Budget oder auch eine Zeitvorgabe. 

# Positive Aspekte

Den Umfang hast Du super erreicht. Auch die Abbildung finde ich super übersichtlich. Der Aufbau ist super übersichtlich und adressiert die Zielgruppe. Ich finde den Beitrag sehr gelungen. Schön ist, dass Du dich den letzten Änderungsvorschlägen angenommen hast. 

# Negative Aspekte

Mir gefällt der Beitrag so wie er ist. Ich habe keine weiteren Verbesserungsvorschläge.

------------------------------------

| Kriterium | Bewertung|
|-----|---|
| Front-Matter | ja |
| Umfang | ja |
| Belege | ja |
| Links | ja |
| Formatierung | ja |
| Verlinkungen vorhanden | ja |
| Abbildungen | ja |
| Strukturierung des Beitrags | 10 |
| Rechtschreibung | 10|
| Sprache | 10 |
| Inhalt | 10|
| Einordnung in den Kontext | 10|
| Ansprechend für Zielgruppe | 10|

# Zusammenfassung

Megatrends sind äußerliche Einflüsse und Veränderungen, die Projektmanager bei der Umsetzung ihres Projekts beachten müssen. Dazu zählen beispielsweise Ereignisse wie die Corona-Pandemie, Die Klimakrise oder auch gesellschaftliche Veränderungen. 

# Positive Aspekte

Ich finde es super, dass Du gleich zwei Abbildungen in den Beitrag eingepflegt hast. Sie sind passend und leicht zu verstehen. Die Quellen funktionieren alle und Verlinkungen sind gegeben. Der Beitrag ist gut und übersichtlich strukturiert.

# Negative Aspekte

Auch bei diesem Beitrag habe ich keine Verbesserungsvorschläge mehr. Ich finde der Aufbau ist sehr übersichtlich gestaltet und man erfährt in kürzester Zeit, was Megatrends im Projektmanagement bedeuten und welche Herausforderungen sie darstellen. Für mich ein guter Beitrag!

2022-01-18 12:30 UTC, jsk0lb requested changes
| Kriterium | Bewertung|
|-----|---|
| Front-Matter | ja/ nein |
| Umfang | ja/ nein|
| Belege | ja/ nein |
| Links | ja/ nein|
| Formatierung | ja/ nein|
| Verlinkungen vorhanden | ja/ nein |
| Abbildungen | ja/ nein |
| Strukturierung des Beitrags | 1-10 |
| Rechtschreibung | 1-10|
| Sprache | 1-10 |
| Inhalt | 1-10|
| Einordnung in den Kontext | 1-10|
| Ansprechend für Zielgruppe | 1-10|

# Zusammenfassung

Kurze Zusammenfassung des/der Artikel

# Positive Aspekte

Was ist gut (Bezug zur Tabelle)

# Negative Aspekte

Was geht besser (Bezug zur Tabelle)

2022-01-19 13:05 UTC, On11ybid requested changes
| Kriterium | Bewertung|
|-----|---|
| Front-Matter | ja |
| Umfang | ja |
| Belege | ja |
| Links | ja |
| Formatierung | ja |
| Verlinkungen vorhanden | ja |
| Abbildungen | ja |
| Strukturierung des Beitrags | 9 |
| Rechtschreibung | 10 |
| Sprache | 10 |
| Inhalt | 10 |
| Einordnung in den Kontext | 10 |
| Ansprechend für Zielgruppe | 10 |

# Zusammenfassung

Dieser Artikel befasst sich mit dem Thema Action Points. Dazu gehört wie Arbeitspakete in komplexen Projekten und deren verschiedenen Größen und Inhalte sind. Abhängig vom Strukturplan des Projektes, stehen die Action Points entweder schon zu Beginn fest oder werden während des Projektes festgelegt. 

# Positive Aspekte

Der Artikel gibt einen guten Einblick in das Thema Action Points. Die  Abbildungen wurden sehr passend Gewählt, was den Beitrag ansprechender für den Leser macht. Inhaltlich und sprachlich ist das ein super Beitrag und es wurden alle Aspekte aus dem vorherigen Review beachtet. 

# Negative Aspekte

Beim Projektstrukturplan würde ich wahrscheinlich die Methoden als Unterpunkte formatieren.

2022-01-19 13:15 UTC, On11ybid commented
| Kriterium | Bewertung|
|-----|---|
| Front-Matter | ja |
| Umfang | ja |
| Belege | ja |
| Links | ja |
| Formatierung | ja |
| Verlinkungen vorhanden | ja |
| Abbildungen | ja |
| Strukturierung des Beitrags | 9 |
| Rechtschreibung | 10 |
| Sprache | 10 |
| Inhalt | 10 |
| Einordnung in den Kontext | 10 |
| Ansprechend für Zielgruppe | 10 |

# Zusammenfassung

Dieser Artikel befasst sich mit dem Thema Action Points. Dazu gehört wie Arbeitspakete in komplexen Projekten und deren verschiedenen Größen und Inhalte sind. Abhängig vom Strukturplan des Projektes, stehen die Action Points entweder schon zu Beginn fest oder werden während des Projektes festgelegt. 

# Positive Aspekte

Der Artikel gibt einen guten Einblick in das Thema Action Points. Die  Abbildungen wurden sehr passend Gewählt, was den Beitrag ansprechender für den Leser macht. Inhaltlich und sprachlich ist das ein super Beitrag und es wurden alle Aspekte aus dem vorherigen Review beachtet. 

# Negative Aspekte

Beim Projektstrukturplan würde ich wahrscheinlich die Methoden als Unterpunkte formatieren.

2022-01-25 14:08 UTC, merged