Projektaufloesung
ManagingProjectsSuccessfully/ManagingProjectsSuccessfully.github.io pull request #577
Opened 2021-12-22 19:27 UTC by Quapoapo

Ich bedanke mich bei euch für euer Feedback. Ich habe den Rechtschreifehler korrigiert und den Punkt "Weiterführende Literatur" eingefügt. Noch dazu funktionieren nun alle Verlinkungen. 
Mfg
Quapoapo

2021-12-22 19:34 UTC, Quapoapo commented
Ich bedanke mich bei euch für euer Feedback. Ich habe den Rechtschreifehler korrigiert und den Punkt "Weiterführende Literatur" eingefügt. Noch dazu funktionieren nun alle Verlinkungen.
Mfg
Quapoapo

2022-01-17 15:54 UTC, tcansel requested changes
| Kriterium | Bewertung|
|-----|---|
| Front-Matter | ja |
| Umfang | ja|
| Belege | ja |
| Links | ja|
| Formatierung | ja|
| Verlinkungen vorhanden | ja |
| Abbildungen | ja |
| Strukturierung des Beitrags | 10 |
| Rechtschreibung | 10|
| Sprache | 10 |
| Inhalt | 10|
| Einordnung in den Kontext | 10|
| Ansprechend für Zielgruppe | 10|

# Zusammenfassung

Der Artikel befasst sich mit dem Thema Projektauflösung. Der Autor geht dabei auf verschiedene Aspekte ein, die während einer Projektauflösung zu berücksichtigen sind, wie z.B.: Archivierung der Unterlagen und Rückgabe der Ressourcen. Anschließend wird beschrieben, welche Schritte nach der Auflösung des Projekts zu befolgen sind, um weiterhin motiviert an neue Projekte herangehen zu gehen.

# Positive Aspekte

* leicht leserlich und verständlich
* der Artikel ist sehr gut strukuriert
* Abbildung vorhanden und passt zum Inhalt
* gute Einleitung
* Belege und Verlinkungen funktionieren
* Verbesserungsvorschläge wurden umgesetzt

# Negative Aspekte

keine

2022-01-17 22:57 UTC, YeldaUzun requested changes
| Kriterium | Bewertung|
|-----|---|
| Front-Matter | ja |
| Umfang | ja |
| Belege | ja |
| Links | ja |
| Formatierung | ja |
| Verlinkungen vorhanden | ja |
| Abbildungen | ja |
| Strukturierung des Beitrags | 10 |
| Rechtschreibung | 9 |
| Sprache | 10 |
| Inhalt | 9 |
| Einordnung in den Kontext | 10|
| Ansprechend für Zielgruppe | 10|

# Zusammenfassung
Der Artikel befasst sich mit der Projektauflösung. Hierbei wird die Auflösung eines Projekts in einige Schritten beschrieben. 

# Positive Aspekte
- Belege und Verlinkungen zu anderen Themen vorhanden. 
- Links und Verlinkungen funktionieren. 
- Umfang wurde eingehalten. 
- Abbildung vorhanden und lässt sich öffnen. 
- Verbesserungsvorschläge wurden größtenteils umgesetzt. 
- Interessanter Inhalt der einen Überblick über die Projektauflösung schafft. 

# Negative Aspekte

- Der Artikel weist einige Kommafehler auf. 
- Die Abbildung wurde unzureichend erläutert.

2022-01-18 21:25 UTC, thujavanj commented
| Kriterium | Bewertung|
|-----|---|
| Front-Matter | ja|
| Umfang | ja|
| Belege | ja|
| Links | nein|
| Formatierung | ja|
| Verlinkungen vorhanden | ja|
| Abbildungen | ja|
| Strukturierung des Beitrags | 10|
| Rechtschreibung | 10|
| Sprache | 10 |
| Inhalt | 10|
| Einordnung in den Kontext | 10|
| Ansprechend für Zielgruppe | 10|

# Zusammenfassung

Der Artikel befasst sich mit dem Thema Projektauflösung. Dabei handelt es sich um den letzten Schritt des gesamten Projekts. Der Autor erklärt am Anfang kurz, was man unter einer Projektauflösung versteht. Anschließend geht er auf die einzelnen Schritte in einer Projektauflösung ein, wie beispielsweise Archivierung der Unterlagen, Rückgabe aller Ressourcen, Abschluss der Buchhaltung und der Projektkostenstellen, Vermittlung des Personals, sowie die Organisation einer Abschlussveranstaltung und Erfahrungsaustausch.  

# Positive Aspekte
* weiterführende Literatur wurde ergänzt 
* Rechtschreibfehler wurden ausgebessert
* es wurden viele angrenzende Themen verlinkt
* dynamisches Inhaltsverzeichnis macht den Beitrag übersichtlicher und erinnert sehr stark an ein Wikipedia Artikel


# Negative Aspekte

2022-01-22 20:38 UTC, thujavanj reviewed
| Kriterium | Bewertung|
|-----|---|
| Front-Matter | ja|
| Umfang | ja|
| Belege | ja|
| Links | ja|
| Formatierung | ja|
| Verlinkungen vorhanden | ja|
| Abbildungen | ja|
| Strukturierung des Beitrags | 10|
| Rechtschreibung | 10|
| Sprache | 10 |
| Inhalt | 10|
| Einordnung in den Kontext | 10|
| Ansprechend für Zielgruppe | 10|

# Zusammenfassung

Der Artikel befasst sich mit dem Thema Projektauflösung. Dabei handelt es sich um den letzten Schritt des gesamten Projekts. Der Autor erklärt am Anfang kurz, was man unter einer Projektauflösung versteht. Anschließend geht er auf die einzelnen Schritte in einer Projektauflösung ein, wie beispielsweise Archivierung der Unterlagen, Rückgabe aller Ressourcen, Abschluss der Buchhaltung und der Projektkostenstellen, Vermittlung des Personals, sowie die Organisation einer Abschlussveranstaltung und Erfahrungsaustausch.  

# Positive Aspekte
* weiterführende Literatur wurde ergänzt 
* Rechtschreibfehler wurden ausgebessert
* es wurden viele angrenzende Themen verlinkt
* dynamisches Inhaltsverzeichnis macht den Beitrag übersichtlicher und erinnert sehr stark an ein Wikipedia Artikel


# Negative Aspekte

2022-01-25 14:08 UTC, merged