update Trello_PM_Tool
ManagingProjectsSuccessfully/ManagingProjectsSuccessfully.github.io pull request #581
Opened 2021-12-22 19:41 UTC by hatutona

2022-01-11 16:19 UTC, za22regi requested changes
| Kriterium | Bewertung|
|-----|---|
| Front-Matter | ja |
| Umfang | ja |
| Belege | ja |
| Links | ja |
| Formatierung | ja |
| Verlinkungen vorhanden | ja |
| Abbildungen | ja |
| Strukturierung des Beitrags | 10 |
| Rechtschreibung | 9 |
| Sprache | 9 |
| Inhalt | 10 |
| Einordnung in den Kontext | 10 |
| Ansprechend für Zielgruppe | 10 |

# Zusammenfassung
Der Beitrag verschafft einem zunächst einen kleinen Überblick über die Geschichte von Trello. Anschließend erfährt der Leser die Schlüsselfuktionen des Tools und darauffolgend wird das Geschäftsmodell näher erläutert. In Form einer Tabelle werden die Konkurrenten von Trollo aufgelistet und mit Trello nach einigen Kriterien verglichen.


# Positive Aspekte
Ein sehr gelungener Beitrag und die kritik wurde sehr zu herzen genommen und umgesetzt. Sehr zufrieden bin ich mit dem Aufbau und dem Inhalt des textes. Das Schaubild rundet den Beitrag noch ab und verleiht diesem noch eine höhere Qualität. 


# Negative Aspekte
Ein Rechtschreibfehler hat sich tatsächlich noch eingeschlichen. Es heißt "dieses Tool" und nicht "dieser Tool". In der Spalte Asana und der Zeile geeignet für, sollte darauf geachtet werden ein Leerzeichen zwischen dem Wort und der Klammer einzufügen.

2022-01-13 15:51 UTC, Larf4 reviewed
| Kriterium | Bewertung|
|-----|---|
| Front-Matter | ja |
| Umfang | ja |
| Belege | ja |
| Links | ja |
| Formatierung | ja |
| Verlinkungen vorhanden | ja |
| Abbildungen | ja |
| Strukturierung des Beitrags | 10 |
| Rechtschreibung | 10|
| Sprache | 10 |
| Inhalt | 10|
| Einordnung in den Kontext | 10|
| Ansprechend für Zielgruppe | 10|

# Zusammenfassung
Der Artikel gibt einen schönen, knackigen Überblick über das Tool Trello. 

# Positive Aspekte

Anmerkungen aus Runde 1 wurden beachtet


# Negative Aspekte

Ich glaube du solltest "Premium" nicht auf extern Verlinken. Ich glaube mal gehört zu haben im Text selbst solle nur auf Beiträge im Kompendium verlinkt werden. 
Mach es eventuell in "Siehe auch"
Du könntest stattdessen "Projekt" verlinken

2022-01-15 11:54 UTC, hatutona commented
> Kriterium	Bewertung
> Front-Matter	ja
> Umfang	ja
> Belege	ja
> Links	ja
> Formatierung	ja
> Verlinkungen vorhanden	ja
> Abbildungen	ja
> Strukturierung des Beitrags	10
> Rechtschreibung	10
> Sprache	10
> Inhalt	10
> Einordnung in den Kontext	10
> Ansprechend für Zielgruppe	10
> # Zusammenfassung
> Der Artikel gibt einen schönen, knackigen Überblick über das Tool Trello.
> 
> # Positive Aspekte
> Anmerkungen aus Runde 1 wurden beachtet
> 
> # Negative Aspekte
> Ich glaube du solltest "Premium" nicht auf extern Verlinken. Ich glaube mal gehört zu haben im Text selbst solle nur auf Beiträge im Kompendium verlinkt werden. Mach es eventuell in "Siehe auch" Du könntest stattdessen "Projekt" verlinken

Hallo Larf4

2022-01-19 10:30 UTC, Adaye1e requested changes
| Kriterium | Bewertung|
|-----|---|
| Front-Matter | ja |
| Umfang | ja|
| Belege | ja |
| Links | ja|
| Formatierung | ja|
| Verlinkungen vorhanden | ja |
| Abbildungen | ja |
| Strukturierung des Beitrags | 10 |
| Rechtschreibung | 9 |
| Sprache | 10 |
| Inhalt | 10|
| Einordnung in den Kontext | 10|
| Ansprechend für Zielgruppe | 10|

# Zusammenfassung
Zu Beginn schafft der Artikel einen kleinen Einblick in die Geschichte des Trello Tools.
Des Weiteren werden Schlüsselfunktionen und die Art des Geschäftsmodells, welches als Premium-Prinzip bezeichnet wird, beschrieben.
Zuletzt werden die Gemeinsamkeiten und unterschiede zwischen Trello und der Konkurrenz dargestellt.


# Positive Aspekte

Der Beitrag ist sehr gut verfasst und die Vorschläge aus dem ersten Review wurden problemlos umgesetzt.

# Negative Aspekte

Außer einem kleinen Rechtschreibfehler, welcher meinem Vorredner aufgefallen ist, gibt es keine weiteren negativen Aspekte.

2022-01-25 14:08 UTC, merged