Obeya Raum
ManagingProjectsSuccessfully/ManagingProjectsSuccessfully.github.io pull request #584
Opened 2021-12-22 19:56 UTC by xe28dita

Danke für euer Feedback. Ich habe den Front-Matter nun vollständig ausgefüllt sowie meine abschließenden Sätze unter dem Punkt "Fazit" zusammengefasst.

Schöne Grüße

2022-01-13 14:56 UTC, LaHe27 requested changes
| Kriterium | Bewertung|
|-----|---|
| Front-Matter | ja |
| Umfang | ja |
| Belege | ja |
| Links | ja |
| Formatierung | ja |
| Verlinkungen vorhanden | ja |
| Abbildungen | ja |
| Strukturierung des Beitrags | 10 |
| Rechtschreibung | 10 |
| Sprache | 10 |
| Inhalt | 10|
| Einordnung in den Kontext | 10|
| Ansprechend für Zielgruppe | 10|

# Zusammenfassung
Die Zusammenfassung ist die gleiche wie vorher auch:

Der Artikel erläutert das Konzept des Obeya-Raums. Im Artikel wird zuerst der Obey-Raum erklärt sowie auf die Hauptziele, den klassischen Verlauf und die Vorteile eingegangen.

# Positive Aspekte

Ich kannte mich zuvor noch gar nicht mit dem Thema aus und habe durch deinen Beitrag wirklich sehr gut verstanden, um was es geht. Ich finde, du hast deinen Beitrag gut gegliedert und auch die Bilder passen gut dazu. Auch die Sprache und der Stil sind sehr verständlich.

# Negative Aspekte
Das Front-Matter wurde richtig angepasst.
Zudem wurde auch die letzten 2-3 Sätze noch unter die Überschrift "Fazit" zusammengefasst. 
Ich habe keine negativen Aspekte gefunden.

2022-01-17 14:14 UTC, alexandermueller296 commented
Thema: Obeya_Raum

| Kriterium | Bewertung|
|-----|---|
| Front-Matter | ja |
| Umfang | ja |
| Belege | ja |
| Links | ja |
| Formatierung | ja |
| Verlinkungen vorhanden | ja |
| Abbildungen | ja |
| Strukturierung des Beitrags | 9 |
| Rechtschreibung | 10 |
| Sprache | 10 |
| Inhalt | 10 |
| Einordnung in den Kontext | 10 |
| Ansprechend für Zielgruppe | 10 |

# Zusammenfassung

Der Artikel besteht aus Definition, Hauptziele, Verlauf, Vorteilen und Quellen. Bei Hauptzielen und Verlauf ist jeweils eine Abbildung zum Thema gegeben. 

# Positive Aspekte

Der Artikel ist interessant geschrieben und sehr verständlich. Die Bilder sind gut verständlich gewählt.

# Negative Aspekte
 
Bei mir fehlt die Überschrift des Artikels.
Geschmackssache:
Es beginnt bei mir sofort mit „Inhalte“ Bei der Vorlage in Github war kein Inhaltsverzeichnis vorgegeben. Es ist ein schönes nice to have aber ich würde es nicht mit aufführen, da man gleich mit der Definition beginnen kann und der Artikel nicht so unübersichtlich bzw. groß ist um ein Inhaltsverzeichnis zu brauchen.

2022-01-17 14:21 UTC, alexandermueller296 requested changes
Thema: Obeya_Raum

| Kriterium | Bewertung|
|-----|---|
| Front-Matter | ja |
| Umfang | ja |
| Belege | ja |
| Links | ja |
| Formatierung | ja |
| Verlinkungen vorhanden | ja |
| Abbildungen | ja |
| Strukturierung des Beitrags | 9 |
| Rechtschreibung | 10 |
| Sprache | 10 |
| Inhalt | 10 |
| Einordnung in den Kontext | 10 |
| Ansprechend für Zielgruppe | 10 |

# Zusammenfassung

Der Artikel besteht aus Definition, Hauptziele, Verlauf, Vorteilen und Quellen. Bei Hauptzielen und Verlauf ist jeweils eine Abbildung zum Thema gegeben. 

# Positive Aspekte

Der Artikel ist interessant geschrieben und sehr verständlich. Die Bilder sind gut verständlich gewählt.

# Negative Aspekte

Die Front Matter wurde angepasst. Bei mir fehlt die Überschrift, es beginnt bei mir sofort mit „Inhalte“ Bei der Vorlage in Github war kein Inhaltsverzeichnis vorgegeben. Es ist ein schönes nice to have aber ich würde es nicht mit aufführen, da man gleich mit der Definition beginnen kann und der Artikel nicht so unübersichtlich bzw. groß ist um ein Inhaltsverzeichnis zu brauchen

2022-01-18 11:39 UTC, LeahMtmb requested changes
| Kriterium | Bewertung|
|-----|---|
| Front-Matter | ja|
| Umfang | ja|
| Belege | ja |
| Links | ja|
| Formatierung | ja|
| Verlinkungen vorhanden | ja |
| Abbildungen | ja |
| Strukturierung des Beitrags | 10 |
| Rechtschreibung | 10|
| Sprache | 10 |
| Inhalt | 10|
| Einordnung in den Kontext | 10|
| Ansprechend für Zielgruppe | 10|

# Zusammenfassung

Zuerst wurde der Begriff Obeya-Raum definiert. Anschließend wurde der Zweck mithilfe seiner Hauptziele erläutert. Des Weiteren wurde der Verlauf. Anhand dieser Aspekte wurden zum Schluss die Vorteile aufgeführt.

# Positive Aspekte

Durch deine Formatierung, ist dein Artikel sehr übersichtlich und super strukturiert. Du hast alles verständlich und prägnant wiedergegebenen, sodass ich nach einmaligem Lesen das Thema sofort verstanden habe. Was die Sprache und die Rechtschreibung betrifft, habe ich auch kaum etwas anzumerken. Aufgrund deiner Auswahl an Bilder konnte ich mir den Obeya-Raum besser vorstellen und ein besseres Verständnis entwickeln. 
Du hast die Verbesserung, der von mir negativen angemerkten Aspekten umgesetzt! 😊 
Alles in allem ist dein Artikel wirklich gelungen!

# Negative Aspekte

Die Nachteile fehlen zwar nach wie vor, aber das ist gar kein Problem, weil der Artikel zu umfangreich geworden wäre.

2022-01-25 14:11 UTC, merged