Update Gantt_Diagramme
ManagingProjectsSuccessfully/ManagingProjectsSuccessfully.github.io pull request #590
Opened 2021-12-22 20:28 UTC by xyily

2021-12-22 21:07 UTC, xyily commented
@CatrinSc vielen Dank für dein Feedback. Ich habe 1 und 2 als Überschriften genommen und die anderen Punkte jeweils als Unterpunkte. Auch den Tabellensatz habe ich entfernt.

2021-12-22 21:07 UTC, xyily commented
@uc00ekun Danke für dein Feedback, die Formatierung habe ich geändert und Kommata habe ich ebenfalls verbessert.

2021-12-22 21:07 UTC, xyily commented
@LysanderBenke Danke für dein Feedback. Ich habe die Rechtschreibfehler und Kommata verbessert.

2022-01-16 11:32 UTC, CatrinSc requested changes
| Kriterium | Bewertung|
|-----|---|
| Front-Matter | ja |
| Umfang | ja |
| Belege | ja |
| Links | ja | 
| Formatierung | ja |
| Verlinkungen vorhanden | ja |
| Abbildungen | ja |
| Strukturierung des Beitrags | 10 |
| Rechtschreibung | 10|
| Sprache | 10 |
| Inhalt | 10|
| Einordnung in den Kontext | 10|
| Ansprechend für Zielgruppe | 10|

# Zusammenfassung

Der Artikel bietet einen Einblick in das Gantt Diagramm. Man wird über die Entstehung, den Aufbau, die Erstellung sowie die Vor- und Nachteile aufgeklärt.

# Positive Aspekte

Die Verbesserungsvorschläge wurden umgesetzt. Die Tabelle wurde entfernt und die Struktur wurde sehr gut angepasst. Es ist sehr informativ, ansprechend und interessant sowie schlüssig strukturiert. 

# Negative Aspekte

keine

2022-01-16 18:04 UTC, uc00ekun requested changes
| Kriterium | Bewertung|
|-----|---|
| Front-Matter | ja |
| Umfang | ja |
| Belege | ja |
| Links | ja |
| Formatierung | ja |
| Verlinkungen vorhanden | ja |
| Abbildungen | ja |
| Strukturierung des Beitrags | 10 |
| Rechtschreibung | 10|
| Sprache | 10 |
| Inhalt | 10|
| Einordnung in den Kontext | 10|
| Ansprechend für Zielgruppe | 10|

# Zusammenfassung

Der Artikel handelt vom Gantt Diagramm. Man erhält einen Überblick über die gesamte Thematik mit Entstehung, Aufbau, Erstellung, Vor- und Nachteilen sowie mögliche Alternativen.

# Positive Aspekte

Verbesserungsvorschläge wurden umgesetzt, Artikel ist sehr gut strukturiert und enthält keine Rechtschreibfehler. Alle relevanten Informationen wurden eingefügt. Der Artikel lässt sich flüssig lesen.

# Negative Aspekte

Keine

2022-01-18 18:15 UTC, LysanderBenke reviewed
| Kriterium | Bewertung|
|-----|---|
| Front-Matter | ja|
| Umfang | ja|
| Belege | ja |
| Links | ja|
| Formatierung | ja|
| Verlinkungen vorhanden | ja|
| Abbildungen | ja|
| Strukturierung des Beitrags | 10 |
| Rechtschreibung | 10 |
| Sprache | 10 |
| Inhalt | 10|
| Einordnung in den Kontext | 10|
| Ansprechend für Zielgruppe | 10|

# Zusammenfassung

Der Artikel erklärt das Gantt Diagramm, dessen Entstehung und  seinen Aufbau sowie Vor und Nachteile davon.

# Positive Aspekte
Inhaltlich und sprachlich sehr gut. Die Verbesserungsvorschläge wurden angenommen. Der Artikel lässt sich gut lesen und ist informativ.

Was ist gut (Bezug zur Tabelle)


Keine

2022-01-25 14:11 UTC, merged