Update Crystal_Methods.md
ManagingProjectsSuccessfully/ManagingProjectsSuccessfully.github.io pull request #591
Opened 2021-12-22 20:34 UTC by creepol

2022-01-17 12:54 UTC, SaskiaHe requested changes
| Kriterium | Bewertung|
|-----|---|
| Front-Matter | nein |
| Umfang | ja |
| Belege | ja |
| Links | ja |
| Formatierung | ja |
| Verlinkungen vorhanden | ja |
| Abbildungen | ja |
| Strukturierung des Beitrags | 10 |
| Rechtschreibung | 10|
| Sprache | 9 |
| Inhalt | 9 |
| Einordnung in den Kontext | 9 |
| Ansprechend für Zielgruppe | 9 |

# Zusammenfassung

Der Artikel beschreibt die Crystal Methode, welche von Alistair Cockburn entwickelt wurde. Er teilte den einzelnen Methoden, aus welchen sich die Crystal Methode zusammensetzt, einzelne Farben zu. Außerdem werden die Prinzipien der Crystal Methode erklärt. Dadurch kann ein Projekt, bei Anwendung, erfolgreicher werden. Zuletzt werden die beteiligten Rollen aufgelistet und erläutert.

# Positive Aspekte

Die Abbildungen wurden passend zum Thema ausgewählt.
Alle Links funktionieren und es wurden Überschriften und Punktelisten gut verwendet.
Verlinkungen zu anderen Themen sind vorhanden.
Der Artikel ist gut strukturiert, er geht von einer allgemeinen Erklärung über zu spezifischeren Themen.
Anmerkungen aus dem letzten Review fast alle bearbeitet.

# Negative Aspekte

Frontmatter bei den tag "agil",bei der Anrechnung aber k?
Ansonsten nur noch ein Buchstabendreher im ersten Satz unter Punkt 2 bei dem Wort *durch*.
Aufs Ganze gesehen ein guter Beitrag.

2022-01-18 12:18 UTC, jsk0lb requested changes
| Kriterium | Bewertung|
|-----|---|
| Front-Matter | ja/ nein |
| Umfang | ja/ nein|
| Belege | ja/ nein |
| Links | ja/ nein|
| Formatierung | ja/ nein|
| Verlinkungen vorhanden | ja/ nein |
| Abbildungen | ja/ nein |
| Strukturierung des Beitrags | 1-10 |
| Rechtschreibung | 1-10|
| Sprache | 1-10 |
| Inhalt | 1-10|
| Einordnung in den Kontext | 1-10|
| Ansprechend für Zielgruppe | 1-10|

# Zusammenfassung

Kurze Zusammenfassung des/der Artikel

# Positive Aspekte

Was ist gut (Bezug zur Tabelle)

# Negative Aspekte

Was geht besser (Bezug zur Tabelle)

2022-01-19 13:30 UTC, On11ybid requested changes
| Kriterium | Bewertung|
|-----|---|
| Front-Matter | ja |
| Umfang | ja |
| Belege | ja |
| Links | ja |
| Formatierung | ja |
| Verlinkungen vorhanden | ja |
| Abbildungen | ja |
| Strukturierung des Beitrags | 9 |
| Rechtschreibung | 10 |
| Sprache | 10 |
| Inhalt | 10 |
| Einordnung in den Kontext | 10 |
| Ansprechend für Zielgruppe | 10 |

# Zusammenfassung

Der Artikel befasst sich mit der Crystal  Methode. Crystal ist eine agile Methode im Projektmanagement, und hat eine ganze Familie von einzelnen Methoden. Diese wendet man abhängig von der Größe und der Höhe der Risiken an. Der  Informatiker Alistair Cockburn entwickelte in den 90er Jahren die Crystal Familie.  Jedes Projekt und jedes Team ist einzigartig in Ihrer Zusammensetzung und es gibt keine allgemeine Vorgehensweise.

# Positive Aspekte

Der Artikel gibt einen guten Einblick in das Thema Crystal Methode. Die Abbildungen wurden dem Thema passend und sehr ansprechend für den Leser ausgewählt.  Es wurden die genannten Aspekte aus den vorherigen Reviews beachtet.

# Negative Aspekte

Abgesehen davon das der Frontmatter angepasst werden sollte, gibt es nichts zu kritisieren.

2022-01-19 13:58 UTC, creepol commented
Kommentar zu den Reviews:
Erstmal danke für euer Feedback. Ich hatte nur zwei agile Themen zugeordnet bekommen und mache noch den Scrum-Master. Deswegen muss ich das Thema als klassisch anrechnen lassen obwohl es agil ist. Darum hab ich das bei den Tags so gemacht.

2022-01-25 14:11 UTC, merged