Update SWAT_Analyse.md
ManagingProjectsSuccessfully/ManagingProjectsSuccessfully.github.io pull request #596
Opened 2021-12-22 21:11 UTC by AlperK61

2021-12-22 21:15 UTC, AlperK61 commented
der link  zu meinem alten [Beitrag](https://github.com/ManagingProjectsSuccessfully/ManagingProjectsSuccessfully.github.io/pull/169) . Ich habe Rechtschreibfehler korrigiert und ein Bild eingefügt. Habe zudem die Links richtig gesetzt, sodass sie jetzt funktionieren.

2022-01-12 13:04 UTC, FerdinandMerbecks requested changes
| Kriterium | Bewertung|
|-----|---|
| Front-Matter | ja |
| Umfang | ja |
| Belege | ja |
| Links | ja |
| Formatierung | ja |
| Verlinkungen vorhanden | ja |
| Abbildungen | ja |
| Strukturierung des Beitrags | 9 |
| Rechtschreibung | 10 |
| Sprache | 10 |
| Inhalt | 10 |
| Einordnung in den Kontext | 8 |
| Ansprechend für Zielgruppe | 9 |

# Zusammenfassung

Der Artikel beginnt mit der Erläuterung was man unter einer Stärken-Schwächen-Analyse versteht und wofür das Akronym SWOT steht. Anschließend wird in einem kurzen Absatz auf die Entstehung eingegangen, wobei es nach wie vor schön gewesen wäre diese eventuell als Einleitung zu nutzen. Daraufhin wird auf die Vorgehensweise eingegangen, welche aus einer Inter-/Externanalyse und der Strategiefindung besteht. Abschließend werden die Schritte einer Swotanalyse im klassischen Projektmanagement erläutert. Zum besseren Verständnis
wurde nun eine Abbildung hinzugefügt, welche zur besseren Veranschaulichung beiträgt.

# Positive Aspekte

- Abbildung zeigt einen guten Überblick
- Verlinkungen im text vorhanden und Funktionieren
- alle wichtigen Aspekte wurden gut herausgefiltert und kompakt dargestellt
- Quellen nun richtig angeordnet

# Negative Aspekte

- Einleitung oder Hinführung zum Thema Lieder immer noch nicht am Anfang des Beitrags 
- Daher Struktur des Beitrags nicht ganz perfekt

2022-01-18 11:32 UTC, ValerieGF requested changes
| Kriterium | Bewertung|
|-----|---|
| Front-Matter | ja |
| Umfang | ja|
| Belege | ja |
| Links | ja|
| Formatierung | ja|
| Verlinkungen vorhanden | ja |
| Abbildungen | ja |
| Strukturierung des Beitrags | 10 |
| Rechtschreibung | 10|
| Sprache | 10 |
| Inhalt | 9|
| Einordnung in den Kontext | 8|
| Ansprechend für Zielgruppe | 9|

# Zusammenfassung

Der Artikel beginnt damit, dass gleich die Aufgabe der SWOT Analyse erläutert wird. Daraufhin wird erklärt was man eigentlich unter dem Wort SWOT versteht und kurz die Entstehung erklärt. Anschließend wird die Vorgehensweise erklärt, dabei wird zuerst die Unternehmensanalyse durchgeführt und anschließend die Umweltanalyse um daraus eine Strategie abzuleiten. Am Ende des Beitrags wird speziell auf die SWOT Analyse im klassischen Projektmangement eingegangen.
# Positive Aspekte

•	Abbildung passt gut in den Kontext
•	Die Verlinkungen funktionieren jetzt
•	Das Thema wird sehr gut erklärt und ist leicht verständlich

# Negative Aspekte

Ich habe keine negativen Aspekte.

2022-01-18 13:18 UTC, medjeara requested changes
| Kriterium | Bewertung |
|-----|---|
| Front-Matter | ja |
| Umfang | ja |
| Belege | ja |
| Links | ja |
| Formatierung | ja |
| Verlinkungen vorhanden | ja |
| Abbildungen | ja |
| Strukturierung des Beitrags | 9 |
| Rechtschreibung | 10 |
| Sprache | 10 |
| Inhalt | 10 |
| Einordnung in den Kontext |  9 |
| Ansprechend für Zielgruppe | 10 |

# Zusammenfassung

Der Beitrag befasst sich mit der SWOT-Analyse. Dabei wurde auf die Entstehung, die Vorgehensweise und auf die Druchführung im klassischen Projektmanagement eingegangen. 

# Positive Aspekte

Durch die Abbildung kann man sehr gut erkennen wie sich die SWOT-Analyse zusammensetzt. Zudem wurde mit den Absätzen die Unterschiede zwischen externer und interner Analyse übersichtlicher gestaltet. 

# Negative Aspekte

Man könnte die Entstehung zu Beginn erwähnen und als nächsten Punkt wie die SWOT-Analyse sich zusammensetzt. Ansonsten habe ich keine negative Aspekte zu nennen.

2022-01-25 14:11 UTC, merged