Update internationale projektsteuerung
ManagingProjectsSuccessfully/ManagingProjectsSuccessfully.github.io pull request #598
Opened 2021-12-22 21:20 UTC by ValerieGF

2022-01-11 13:46 UTC, Juliakau commented
| Kriterium | Bewertung|
|-----|---|
| Front-Matter | ja |
| Umfang | ja |
| Belege | nein |
| Links | nein |
| Formatierung | nein |
| Verlinkungen vorhanden | nein |
| Abbildungen | nein |
| Strukturierung des Beitrags | 6 |
| Rechtschreibung | 8 |
| Sprache | 7 |
| Inhalt | 8 |
| Einordnung in den Kontext | 9 |
| Ansprechend für Zielgruppe | 9 |

# Zusammenfassung

Allgemein eine gute Einführung in den Kontext und markieren der wichtigen Tools und die Individualität der Projektsteuerung. Daher ist auf alles allgemein eingegangen, jedoch werden überall Beispiele genannt, sodass man gut verstehen kann was gemeint ist. Formatierung und Verlinkungen/Quellenangaben sowie weiterführende Links leider nicht vorhanden bzw. Links zu anderen Themen falsch angegeben und funktionieren deshalb nicht. 

# Positive Aspekte

- konkrete Beispiele
- Einordnung in den Kontext eines Projektes
- zuerst Projektsteuerung allgemein und anschließend Hinführung auf internationale Projektsteuerung

# Negative Aspekte

- Falsche Überschriften und keine Untergliederung der Themen
- keine weiterführenden Links
- keine anderen Themen verlinkt bzw. Verlinkung falsch angegeben
- keine Abbildung vorhanden
- fehlende Quellenangaben sowohl bei Absätzen als auch bei direkten Zitaten
- teilweise falsche Kommasetzung bsp "Auch hier, kann nur eine allgemeine Aussagen..."

2022-01-12 13:30 UTC, FerdinandMerbecks requested changes
| Kriterium | Bewertung|
|-----|---|
| Front-Matter | ja |
| Umfang | ja |
| Belege | ja |
| Links | nein |
| Formatierung | ja |
| Verlinkungen vorhanden | nein |
| Abbildungen | ja |
| Strukturierung des Beitrags | 10 |
| Rechtschreibung | 9 |
| Sprache | 8 |
| Inhalt | 9 |
| Einordnung in den Kontext | 10 |
| Ansprechend für Zielgruppe | 10 |

# Zusammenfassung

Der Artikel beginnt mit der Einordnung des Themas der internationalen Projektsteuerung in die Aufgaben des Projektmanagements. Zudem wurde nun eine Abbildung eingefügt, welche zur besseren Veranschaulichung dient. Anschließend erfolgt eine ausführliche Definition des Begriffs der Projektsteuerung. Daraufhin wird die Herausforderung, welche Aufgabenfelder unabhängig von einem konkreten Praxisbeispiel zur Projektsteuerung gehören, eingegangen. Dem roten Faden weiterhin sehr gut folgend werden nun zugehörige Aufgaben der Projektsteuerung und Tools vorgestellt. Abschließend wird noch auf Besonderheiten der internationalen Projektsteuerung beleuchtet.



# Positive Aspekte

- gute Struktur des Beitrag
- gute Einordnung in den Kontext
- Abbildung zum besseren Verständnis
- Belege sind nun vorhanden


# Negative Aspekte

- Verlinkungen zu angrenzenden zwar vorhanden, führen aber zu nicht existierenden Seiten
- Rechtschreibung nochmals überprüfen

2022-01-13 19:30 UTC, Juliakau requested changes
| Kriterium | Bewertung|
|-----|---|
| Front-Matter | ja |
| Umfang | ja |
| Belege | ja |
| Links | ja |
| Formatierung | ja |
| Verlinkungen vorhanden | ja |
| Abbildungen | ja |
| Strukturierung des Beitrags | 6 |
| Rechtschreibung | 8 |
| Sprache | 7 |
| Inhalt | 8 |
| Einordnung in den Kontext | 9 |
| Ansprechend für Zielgruppe | 9 |

# Zusammenfassung

Allgemein eine gute Einführung in den Kontext und markieren der wichtigen Tools und die Individualität der Projektsteuerung. Bilder, Links und andere Themen wurden eingefügt.

# Positive Aspekte

- konkrete Beispiele
- Einordnung in den Kontext eines Projektes
- zuerst Projektsteuerung allgemein und anschließend Hinführung auf internationale Projektsteuerung

# Negative Aspekte
- fehlende Quellenangaben

2022-01-15 15:27 UTC, eberto99 requested changes
| Kriterium | Bewertung|
|-----|---|
| Front-Matter | ja |
| Umfang | ja|
| Belege | ja |
| Links | nein|
| Formatierung | ja|
| Verlinkungen vorhanden | ja |
| Abbildungen | ja |
| Strukturierung des Beitrags | 8 |
| Rechtschreibung | 8|
| Sprache | 8 |
| Inhalt | 8|
| Einordnung in den Kontext | 9|
| Ansprechend für Zielgruppe | 8|

# Zusammenfassung

Zu Beginn wird die internationale Projektsteuerung in den Kontext eingeordnet. Danach folgt eine ausführliche Definition in der auf die Abbildung gut eingegangen wird. Vor der Aufgabenerläuterung wird betont, dass jede Projektsteuerung abhängig vom individuellen Projekt ist. Abschließend wird die Tool-Wahl, als auch internationale Spezifika in Beug auf die Anforderungen an Projektmanager aufgegriffen.

# Positive Aspekte

* Einordnung der Projektsteuerung, mit dem Verweis auf den Artikel des Projektmanagements
* In der Definition wird gut der Bezug zur Graphik hergestellt
* Formatierung stimmt nun und der Artikel ist somit ansprechender für die Zielgruppe
* Verlinkungen zu den Quellen wurden nun eingefügt


# Negative Aspekte

* Beim Bild würde sich ein entsprechender Quellenverweis gut machen; Vll. die Abbildung in Kursiv benennen und dann auf die bereits vorhandene Quelle unten verweisen
* Alle Verlinkungen im Text, als auch bei Siehe auch funktionieren nicht, bzw. führen nicht zu dem Beitrag; Das wird daran liegen, dass nicht die richtige Datei in dem Ordner der Themenzuordnung bearbeitet wurde, sondern die README.md
* Rechtschreibung nochmals prüfen
* Die Besonderheit der internationalen Projektsteuerung im Gegensatz zur eigentlichen Projektsteuerung wird nicht deutlich genug (Wie stark äußert sich der Einfluss, …) - Das wird bislang nur kurz im letzten Absatz aufgegriffen

2022-01-25 14:14 UTC, merged