Update Scrum_Master.md
ManagingProjectsSuccessfully/ManagingProjectsSuccessfully.github.io pull request #602
Opened 2021-12-22 21:36 UTC by Phr4nk20

2021-12-22 21:57 UTC, Phr4nk20 commented
Hallo zusammen,
vielen Dank für eure Reviews!

Ich habe versucht alle Bemerkungen und Verbesserungsvorschläge umzusetzen.
Da Rechtschreibung und Sprache die häufigsten Kritikpunkte waren, habe Ich vornehmlich Verbesserungen hinsichtlich Sprachstil und Rechtschreibung getroffen. Außerdem wurde eine Grafik und weiterführende Literatur hinzugefügt.

Schöne Weihnachten und einen guten Rutsch ins neue Jahr!

2022-01-19 04:56 UTC, jacobbocai requested changes
| Kriterium | Bewertung|
|-----|---|
| Front-Matter | ja |
| Umfang | ja |
| Belege | ja |
| Links | ja|
| Formatierung | ja|
| Verlinkungen vorhanden | ja |
| Abbildungen | ja |
| Strukturierung des Beitrags | 10 |
| Rechtschreibung | 10|
| Sprache | 10 |
| Inhalt | 10|
| Einordnung in den Kontext | 10|
| Ansprechend für Zielgruppe | 10|

# Zusammenfassung

Der Artikel wird mit einer kurzen Definition eingeleitet und die Rolle des SCRUM Masters erläutert.
Des weiteren werden die Aufgaben noch einmal näher ausgeführt und die Persönlichkeitseigenschaften dieser Rolle aufgezählt.
Die Aufgaben bestehen aus Schutz, Moderation, Coaching, Beseitigung von Impediments, Einführung, Verbesserung der Produktivität, Zielvermittlung. 
SCRUM Master sollten kommunikativ, motivierend, teamfähig und wissend sein.
Abschließend wird noch Kritik an der Bezeichnung "Master" geübt.

# Positive Aspekte

Sinnvolle und übersichtliche Gliederung.
Aussagekräftiger Inhalt
Kritik
Übersichtliche Aufzählungen
Front-Matter wurde ergänzt
Links und Literatur wurden ergänzt
Anschauliche Grafiken wurden umgesetzt
Eine schöne übersichtliche Formatierung wurde umgesetzt
Alle anderen Grammatik und Rechtschreibfehler wurden behoben


# Negative Aspekte

Die alten Fehler wurden behoben und ich habe keine weiteren negative Aspekte anzuführen.

2022-01-19 08:43 UTC, Sina5222 requested changes
| Kriterium | Bewertung|
|-----|---|
| Front-Matter | ja |
| Umfang | ja|
| Belege | ja|
| Links | nein|
| Formatierung | ja|
| Verlinkungen vorhanden | ja |
| Abbildungen | ja|
| Strukturierung des Beitrags | 10 |
| Rechtschreibung | 10|
| Sprache | 10 |
| Inhalt | 10|
| Einordnung in den Kontext | 10|
| Ansprechend für Zielgruppe | 10|

# Zusammenfassung

Der Beitrag beginnt mit einer Definition des Scrum Masters. Im Anschluss daran werden die vielfältigen Aufgaben des Scrum Masters erläutert und anhand einer Grafik veranschaulicht. Im folgenden Abschnitt werden die notwendigen Kompetenzen eines Scrum Masters aufgeführt und jeweils kurz erklärt. Abgeschlossen wird der Artikel mit möglicher Kritik an dem Begriff Scrum Master.

# Positive Aspekte

* übersichtliche Gliederung
* mögliche Kritik wurde in den Beitrag mit aufgenommen
* sehr verständlich formuliert und angenehm zu lesen
* die Abbildung veranschaulicht die vielfältigen Aufgaben eines Scrum Masters

# Negative Aspekte

* leider funktionieren bei mir die Verlinkungen zu den anderen Kompendiumsbeiträgen nicht

2022-01-19 15:58 UTC, oliPM reviewed
| Kriterium | Bewertung|
|-----|---|
| Front-Matter | ja|
| Umfang | ja|
| Belege | ja|
| Links | ja|
| Formatierung | ja|
| Verlinkungen vorhanden | nein|
| Abbildungen | ja |
| Strukturierung des Beitrags | 9 |
| Rechtschreibung |9|
| Sprache | 9 |
| Inhalt | 9|
| Einordnung in den Kontext | 9|
| Ansprechend für Zielgruppe | 9|

# Zusammenfassung

Der Artikel befasst sich mit dem Scrum Master. Im ersten Abschnitt wird der Scrum Master definiert beziehungsweise erläutert. Nachfolgend werden die Aufgaben eines Scrum Masters beleuchtet und in Form einer Abbildung untermauert. Als drittes werden die Profileigenschaften eines guten Scrum Masters genannt. Als letztes wird Kritik an der Bezeichnung des Scrum Masters ausgeübt. 

# Positive Aspekte

* Sprache
* Abbildung
* Quellen
* Inhalt
* logischer Aufbau --> roter Faden

# Negative Aspekte

* Praxisbezug --> Konkretes Beispiel, bei dem die Aufgaben eines Scrum Masters näher hervorgehoben werden
* manche Verlinkungen funktionieren nicht
* 3. Profil eines guten Scrum Masters --> Bei jeder Aufzählung sollte ein Nomen als Schlüsselbegriff stehen oder der Satz zuvor sollte dementsprechend geändert werden

2022-01-25 14:14 UTC, merged