Update Eisenhower_Matrix.md
ManagingProjectsSuccessfully/ManagingProjectsSuccessfully.github.io pull request #607
Opened 2021-12-22 21:53 UTC by Ersan42

2021-12-22 22:23 UTC, Ersan42 commented
Hey. Danke für euer Feedback. Ich habe die angesprochenen Aspekte korrigiert und umgeändert. Ich hoffe diesmal passt alles.
Liebe Grüße

2022-01-14 16:44 UTC, CatPec requested changes
| Kriterium | Bewertung|
|-----|---|
| Front-Matter | ja|
| Umfang | ja|
| Belege | ja|
| Links | ja|
| Formatierung | ja|
| Verlinkungen vorhanden | ja|
| Abbildungen | ja|
| Strukturierung des Beitrags |9|
| Rechtschreibung |8|
| Sprache |8|
| Inhalt |10|
| Einordnung in den Kontext |6|
| Ansprechend für Zielgruppe |9|

# Zusammenfassung

In dem Artikel geht es um das Prinzip der Eisenhower-Matrix.  Deren Zweck ist es, anstehende Aufgaben nach ihrer Dringlichkeit und Wichtigkeit zu überprüfen.  Je nach dem welcher A-D Aufgabentyp es ist, ergeben sich für diese unterschiedliche Handlungsmöglichkeiten.  Vorteil der Methode ist vor allem die Einfachheit des Prinzips. Nachteilig ist allerdings die begrenze Anwendbarkeit. 

# Positive Aspekte

Du hast sehr viele Dinge vom letzten Mal ausgebessert. Die Rechtschreibung und Sprache hat sich deutlich verbessert.  Die Standardanforderungen bezüglich der Formalitäten erfüllst du nun alle. Der Artikel ist ebenfalls ansprechend für die Zielgruppe (Studenten, die etwas über Projektmanagement lernen möchten), auch wenn sich die Methode an der Universität nicht gut anwenden lässt, was du ja auch als Kritik betonst. Besonders gut gefällt mir neben dem Inhalt auch die Strukturierung deines Beitrags. Ein roter Faden ist gut erkennbar.
Insgesamt wirklich gelungen :)

# Negative Aspekte

Ein paar Tipp- und Zeichensetzungsfehler befinden sich leider auch immer noch in deinem Text. Selten ist der Satzbau auch nicht ganz korrekt. Das sind aber Kleinigkeiten.
Die detaillierte Einordnung in den Kontext fehlt leider immer noch. Da hättest du noch in den Gesamtkontext des Projektmanagements einordnen können. Insgesamt ist der Artikel zwar ungefähr schon eingeordnet, das hättest du aber vielleicht nochmal mit einem Satz am Anfang deines Artikels klar machen können. 

Insgesamt gefällt mir dein Artikel aber wirklich gut!

2022-01-18 16:50 UTC, Dolunay76 reviewed
# Eisenhower-Matrix

| Kriterium | Bewertung|
|-----|---|
| Front-Matter | ja |
| Umfang | ja |
| Belege | ja |
| Links | ja |
| Formatierung | ja |
| Verlinkungen vorhanden | nein |
| Abbildungen | nein |
| Strukturierung des Beitrags | 10 |
| Rechtschreibung | 9 |
| Sprache | 10 |
| Inhalt | 10 |
| Einordnung in den Kontext | 10 |
| Ansprechend für Zielgruppe | 10 |

# Zusammenfassung

Zunächst wurde beschrieben was eine Eisenhower Matrix ist, die einem eine gute Einführung in das Thema gibt. Daraufhin wurde mit dem Inhaltsverzeichnis auf die Themen hingewiesen. Durch Wortherkunft wird erklärt das der Name sich vom ehemaligen US-Präsidenten herleitet. Bei den Aufgaben-Varianten wird auf eine Tabelle hingewiesen die gut strukturiert und übersichtlich ist. Am Ende werden die Vorteile und Nachteile des Eisenhower Prinzips erläutert und mit einem Fazit beendet

# Positive Aspekte

Der Umfang entspricht wie schon davor den geforderten Kriterien.  Sprachlich ist der Artikel einfach und verständlich zu lesen. Inhaltlich ist der Artikel informativ aufgebaut. Es sind viele Quellen gegeben.

# Negative Aspekte

Da alle negativen Aspekte korrigiert wurden, gibt es für mich keine negativen Aspekte mehr, super gelungen.

2022-01-18 17:32 UTC, Emre12345678 reviewed
# Pflichtenheft

| Kriterium | Bewertung|
|-----|---|
| Front-Matter | ja |
| Umfang | ja |
| Belege | ja |
| Links | ja |
| Formatierung | ja |
| Verlinkungen vorhanden | ja |
| Abbildungen | ja |
| Strukturierung des Beitrags | 10 |
| Rechtschreibung | 9 |
| Sprache | 9 |
| Inhalt | 10 |
| Einordnung in den Kontext | 6 |
| Ansprechend für Zielgruppe | 9 |

Eisenhower Matrix:
Der vorliegende Artikel beschreibt das Prinzip der Eisenhower-Matrix. Die Kernaufgabe der Eisenhower-Matrix ist die Überprüfung verschiedenster Aufgaben nach ihrer Wichtigkeit bzw ihrem Stellenwert. Hierbei gibt es verschiedene Aufgabetypen, die im Artikel genauer erläutert werden.


Positive Aspekte:
Dadurch, dass du die Kritik angenommen hast und sehr viele Fehler bezüglich der Grammatik, Rechtschreibung, Satzbau oder Formalitäten verbessert hast, wird dem Leser das Verfolgen deiner Gedankenschritte vereinfacht und man bekommt einen sehr guten ersten Einblick über die Eisenhower-Matrix. Des Weiteren finde ich deine persönliche Kritik sehr gut.


Negative Aspekte:
Es gibt eigentlich nicht viel zu bemängeln. Ich würde an deiner Stelle, deinen Artikel nochmal bezüglich der Zeichensetzung überarbeiten. Außerdem würde ich noch die Eisenhower-Matrix genauer im Projektmanagement einordnen. Ich glaube, dass das eine Arbeit von 15-30min ist. Ansonsten finde ich deinen Artikel top.

2022-01-25 14:14 UTC, merged