Methode_des_kritischen_Pfades_Phase1final
ManagingProjectsSuccessfully/ManagingProjectsSuccessfully.github.io pull request #61
Opened 2021-11-18 09:43 UTC by ChristinaHartung

2021-11-27 12:31 UTC, vegas1337 requested changes
| Kriterium | Bewertung|
|-----|---|
| Front-Matter | ja |
| Umfang | ja |
| Belege | ja |
| Links | ja |
| Formatierung | ja |
| Verlinkungen vorhanden | ja |
| Abbildungen | ja |
| Strukturierung des Beitrags | 9 |
| Rechtschreibung | 10 |
| Sprache | 10 |
| Inhalt | 10 |
| Einordnung in den Kontext | 8 |
| Ansprechend für Zielgruppe | 10 |

# Zusammenfassung

Der Artikel befasst sich mit der Methode des kritischen Pfades, die zur Terminplanung in einem Projekt genutzt wird.

# Positive Aspekte

- sprachlich sehr gut und verständlich
- kurz und prägnant
- sinnvolle Grafiken
- gut genutzte Tabelle für Vor- und Nachteile

# Negative Aspekte

- Verlinkungen zu anderen Artikeln in den Fließtext einbetten und damit mehr Bezug zum "Gesamten" schaffen.
- Eventuell von drei Ebenen der Überschriften auf zwei Ebenen kürzen, dass der Artikel v.a. am Anfang übersichtlicher wird

2021-12-01 16:35 UTC, AnjaKlostermeier commented
| Kriterium | Bewertung|
|-----|---|
| Front-Matter | ja|
| Umfang | ja|
| Belege | ja |
| Links | ja|
| Formatierung | ja|
| Verlinkungen vorhanden | ja|
| Abbildungen | ja|
| Strukturierung des Beitrags | 9|
| Rechtschreibung | 10|
| Sprache | 10 |
| Inhalt | 10|
| Einordnung in den Kontext |8|
| Ansprechend für Zielgruppe | 10|

# Zusammenfassung

In diesem Artikel geht es um die Methode des kritischen Pfades. Es handelt sich hierbei um ein Projektmanagementtool und wird im Englischen "Critical Path Method" genannt. Dieses Tool dient zur Terminplanung in einem Projekt und ist dem klassischen Projektmanagement zuzuordnen. 

# Positive Aspekte
* Gute Strukturierung durch die unterschiedlichen Schriftgrößen der Überschriften 
* Unterpunkte wurden durch verschiedene Schriftform (kursiv) abgehoben 
* Die Sprache wurde gut, sachlich und verständlich gewählt 
* Guter Einsatz der Tabelle für Vor- & Nachteile - gleiche Anzahl an Vor- & Nachteile 
* Quellen wurden überall durch Fußnoten hinterlegt

# Negative Aspekte
* Verlinkungen auf themenähnliche Beiträge der Kommiliton:innen im Beitrag einbauen, nicht nur unter dem Reiter "Siehe auch"
* Verlinkungen auf externe Websites im Beitrag eher unpraktisch 
* Kurzes Fazit/Zusammenfassung am Ende 
* Eventuell Verlinkung zu einem "Video" bzw. praktische Anwendung des Tools

2021-12-01 16:54 UTC, AnjaKlostermeier requested changes
| Kriterium | Bewertung|
|-----|---|
| Front-Matter | ja|
| Umfang | ja|
| Belege | ja |
| Links | ja|
| Formatierung | ja|
| Verlinkungen vorhanden | ja|
| Abbildungen | ja|
| Strukturierung des Beitrags | 9|
| Rechtschreibung | 10|
| Sprache | 10 |
| Inhalt | 10|
| Einordnung in den Kontext |8|
| Ansprechend für Zielgruppe | 10|

# Zusammenfassung

In diesem Artikel geht es um die Methode des kritischen Pfades. Es handelt sich hierbei um ein Projektmanagementtool und wird im Englischen "Critical Path Method" genannt. Dieses Tool dient zur Terminplanung in einem Projekt und ist dem klassischen Projektmanagement zuzuordnen. 

# Positive Aspekte
Der Beitrag wurde durch die unterschiedlichen Schriftgrößen der Überschriften gut strukturiert. Ebenfalls wurden die Unterpunkte durch eine andere Schriftform (kursiv) vom restlichen Beitrag abgehoben. Die Sprache des Beitrags ist sachlich und für den Leser bzw. die Leserin verständlich. Auch der Einsatz der Tabelle wurde gut umgesetzt, um die jeweiligen Vor - und Nachteile der Methode gegenüberzustellen. Gleichermaßen wurde die gleiche Anzahl von Vor- und Nachteilen angebracht. Dadurch wirkt die Tabelle geordnet. Die Quellen wurden wie vorgeschrieben durch Fußnoten hinterlegt. 

# Negative Aspekte
In diesem Beitrag wurden Verlinkungen auf externe Websites vorgenommen. Dies ist eher unpraktisch. Besser ist es, Verlinkungen zu themenähnliche Beiträge der Kommiliton:innen einzubauen. Somit kann der Gesamtbezug besser dargestellt werden und der Leser bzw. die Leserin das Thema besser in den Kontext einordnen. 
Schön wäre am Ende des Beitrags ein kurzes Fazit oder eine kurze Zusammenfassung des Themas. 
Ebenso könnte man unter dem Reiter "Siehe auch" ein Video oder eine praktische Anwendung des Tools verlinken.

2021-12-02 14:04 UTC, Phil224 requested changes
| Kriterium | Bewertung|
|-----|---|
| Front-Matter | ja|
| Umfang | ja|
| Belege | ja|
| Links | ja|
| Formatierung | ja|
| Verlinkungen vorhanden | ja|
| Abbildungen | ja|
| Strukturierung des Beitrags | 9 |
| Rechtschreibung | 10|
| Sprache | 10 |
| Inhalt | 10|
| Einordnung in den Kontext | 8|
| Ansprechend für Zielgruppe | 10|

# Zusammenfassung

Der Artikel beschäftigt sich mit der Methode des kritischen Pfades. Dabei wird das Thema zunächst im geschichtlichen Kontext betrachtet, um anschließend den Begriff kurz zu definieren. Danach werden die einzelnen Schritte im Beitrag aufgegriffen. 

# Positive Aspekte

Der Text ist sprachlich sehr gut formuliert und interessant für den Leser gestaltet. Die Informationen werden kurz und präzise formuliert und haben daher die perfekte Länge. Die Grafiken sind in den Text eingebunden und visualisieren die Thematik sehr gut. Zudem finde ich die Tabelle mit einer kurzen Gegenüberstellung der Vor-& Nachteile sehr gelungen.  


# Negative Aspekte

Die Verlinkungen im Text beziehen sich auf Wikipedia Artikel anstatt auf Kompendiums Beiträge, diese solltest du noch mit deinem Text verlinken. Zudem würde ich die Anzahl der Ebenen um eine reduzieren, dadurch wird der Text noch deutlich übersichtlicher.

2021-12-09 19:27 UTC, merged