Aenderungsmanagement
ManagingProjectsSuccessfully/ManagingProjectsSuccessfully.github.io pull request #614
Opened 2021-12-22 22:35 UTC by Sina5222

2021-12-22 22:44 UTC, Sina5222 commented
Vielen Dank für eure Reviews :)
Ich habe soweit alle Kritikpunkte in meinem Artikel angepasst. Insbesondere habe ich den Absatz mit den Rollen im Änderungsmanagement noch ausführlicher formuliert.
Der einzigen Änderungsvorschlag, den ich nicht umgesetzt habe, war der Titel meiner Abbildung, da in dem Beispieltext auch kein "Abbildung:" vor dem Titel war.

2022-01-18 18:11 UTC, mttno1 reviewed
| Kriterium | Bewertung|
|-----|---|
| Front-Matter | ja|
| Umfang | ja| 
| Belege | ja |
| Links | ja | 
| Formatierung | ja |
| Verlinkungen vorhanden | ja |
| Abbildungen | ja |
| Strukturierung des Beitrags | 10 |
| Rechtschreibung | 8|
| Sprache | 9 |
| Inhalt | 10|
| Einordnung in den Kontext | 10|
| Ansprechend für Zielgruppe | 10|

# Zusammenfassung

Der Artikel beschäftigt sich mit dem Thema Änderungsmanagement. Am Anfang wurden die Ursachen für Änderungen im Projektmanagement aufgelistet und der Begriff „Änderungsmanagement“ definiert. Danach wurde die Aufgaben des Änderungsmanagements geschildert. Darüber hinaus wurden auch sowohl die Rollen als auch die wichtigsten Faktoren in Änderungsmanagement erläutert. Letztendlich wurde in dem Artikel Vorteile des Änderungsmanagements diskutiert.

# Positive Aspekte

* Front-Matter, Quellen war gut.
* Der Artikel war visuell gut durch Überschriften strukturiert.
* Der Prozess wurde mit einem Bild visualisiert.
* Der Inhalt war ganz gut, alle wichtigen Aspekten sind vorhanden.
* Der Teil "Rollen im Änderungsmanagement" wurde ausführlicher ergänzt. 
*  Fast alle Kritikpunkte wurden umgesetzt 👍 
# Negative Aspekte
* Ein paar kleine Rechtschreibfehler müssen korrigiert werden. Ansonstens ein gut geschriebener Artikel :-)

2022-01-19 15:19 UTC, oliPM reviewed
| Kriterium | Bewertung|
|-----|---|
| Front-Matter | ja|
| Umfang | nein|
| Belege | ja|
| Links | ja|
| Formatierung | ja|
| Verlinkungen vorhanden | ja|
| Abbildungen | ja|
| Strukturierung des Beitrags | 9 |
| Rechtschreibung | 8|
| Sprache | 9 |
| Inhalt | 9|
| Einordnung in den Kontext | 9|
| Ansprechend für Zielgruppe | 8|

# Zusammenfassung

Der Artikel befasst sich mit dem Änderungsmanagement. Im ersten Abschnitt wird das Thema definiert und ein wenig erläutert. Im Anschluss werden die Aufgaben im Änderungsmanagement mit Hilfe einer Abbildung präsentiert. Mit dem dritten Abschnitt wird näher auf die Rollen eingegangen, die im Änderungsmanagement aufzufinden sind. Der vorletzte Abschnitt beleuchtet, auf welche Faktoren geachtet werden sollte.
Zum Abschluss werden die Vorteile des Änderungsmanagements hervorgehoben.

# Positive Aspekte

* Quellen 
* Abbildung
* Gliederung
* logischer Aufbau
* Inhalte

# Negative Aspekte

Sprachliche Feinheiten:

Abschnitt: Definition
* Notiz: die Veränderung äußerer Faktoren „Gesetzte“ --> Gesetze

Abschnitt: Welche Aufgaben beinhaltet das Änderungsmanagement
* 2. Zeile: Auftraggebers
* 3. Zeile: notwendige
* 6. Zeile: Kommasetzung --> Denn eine Änderung der Aufgabenstellung, …
* 9. Zeile: beinhaltet
* Das Wort Änderung, je nach Möglichkeit, durch weitere Synonyme ersetzen

Abschnitt: Welche Rollen gibt es im Änderungsmanagement
* 1. Zeile: , wie beispielsweise oder , wie beispielsweise die Projektleitung,
* 2. Zeile: , dass die festgelegte Vorgehensweise korrekt umgesetzt wird


Abschnitt: Was ist beim Änderungsmanagement zu beachten
* 2. Zeile: … in Kenntnis gesetzt werden
* 5. Zeile: Einen Überblick über alle Änderungen im Projekt ermöglicht eine Änderungstabelle
* 6. Zeile: , wie beispielsweise

Abschnitt: Welche Vorteile bietet das Änderungsmanagement
* 1. Zeile: Ein Vorteil des Änderungsmanagements

Verlinkungen zum internen Datenpool über Wörter mit gleicher Benennung
* Kostenänderung --> Kostenplanung (möglich?)

Inhaltlich:
* beispielhafter Bezug für Außenstehende

2022-01-19 21:45 UTC, seif0123 requested changes
| Kriterium | Bewertung|
|-----|---|
| Front-Matter | ja |
| Umfang | ja|
| Belege | ja |
| Links | ja|
| Formatierung | ja |
| Verlinkungen vorhanden | ja|
| Abbildungen | ja |
| Strukturierung des Beitrags |10|
| Rechtschreibung | 9|
| Sprache | 9|
| Inhalt | 10|
| Einordnung in den Kontext | 10|
| Ansprechend für Zielgruppe | 10|

# Zusammenfassung

Der Artikel handelt vom Änderungsmanagement und wie damit die erfolgreiche Realisierung eines Projekts stattfinden kann. Es sollen dabei so viele Änderungen wie nötig während des Projektvorhabens durchgeführt werden, damit ein Erfolg garantiert werden kann. 
Zuerst wird der Begriff allgemein definiert und auf mögliche Ursachen für ein Änderungsmanagement eingegangen. Daraufhin werden die verschiedenen Aufgaben des Änderungsmanagements untersucht und die verschiedenen Rollen/Positionen erwähnt. Zum Schluss werden noch die Vorteile aufgezeigt, welche somit die generelle Wichtigkeit des Änderungsmanagements unterstreichen sollen.
 
# Positive Aspekte

Der Artikel ist an sich gut und einfach strukturiert. Es werden in der Überschrift Fragen aufgeworfen, welche folglich im Text beantwortet werden. 
Die Sprache ist dabei relativ einfach gehalten und garantiert so eine hohe Verständlichkeit. 
Prozesse, wie der Ablauf des Änderungsmanagements, werden verständlich wiedergegeben und ebenfalls bildlich visualisiert. So kann man auch längere und komplexere Aufgabenschritte relativ einfach nachvollziehen.
Der Inhalt gibt dabei die wesentlichen Aspekte zum Änderungsmanagement wieder. Es wurden ebenfalls sinnvolle Verlinkungen zu angrenzenden Themenbereiche verwendet und passend in den Text integriert.

Meine erwähnten Verbesserungsvorschläge wurden berücksichtigt und korrigiert

# Negative Aspekte

Nur die paar übrig gebliebenen sprachlichen Fehler könnten verbessert werden, wie auch von dem anderen Reviewer erwähnt, sonst wurde nahezu alles beachtet.

2022-01-25 14:14 UTC, merged