Lessons Learned Jan Amend
ManagingProjectsSuccessfully/ManagingProjectsSuccessfully.github.io pull request #616
Opened 2021-12-22 22:41 UTC by JanAmend

Ich habe eure Reviews in meiner überarbeiteten Version berücksichtigt und möchte mich dafür bedanken, dass ihr mir überall 10 Punkte gegeben habt. :) 
  
Folgende Punkte habe ich verbessert:
- ein "kann" rausgenommen
- weiterführende Literatur und eine Quelle ergänzt
- Quellenangaben hinter einzelnen Absätzen ergänzt 
- eine weitere Verlinkung zu einem anderen Beitrag hinzugefügt

2022-01-15 16:29 UTC, larissadiscua commented
| Kriterium | Bewertung|
|-----|---|
| Front-Matter | ja|
| Umfang | ja|
| Belege | ja |
| Links | ja|
| Formatierung | ja|
| Verlinkungen vorhanden | ja |
| Abbildungen | ja |
| Strukturierung des Beitrags | 10 |
| Rechtschreibung | 10|
| Sprache | 10 |
| Inhalt | 10|
| Einordnung in den Kontext | 10|
| Ansprechend für Zielgruppe | 10|

# Zusammenfassung

Im Artikel handelt es sich um Lessons Learned, also gewonnene Erkenntnisse, die man bei zukünftigen  Projekten anwenden kann, wobei es sich sowohl um positive, als auch negative Erfahrungen handeln kann. Daraufhin wird der Ablauf erläutert und die Schwierigkeiten, die entstehen können.

# Positive Aspekte

Der Beitrag ist verständlich geschrieben, sowohl sprachlich auch als inhaltlich und zeigt einen klaren Aufbau. Weitere Quellenangaben und weiterführende Literatur wurden ergänzt. Insgesamt finde ich, dass der Artikel sehr gut gelungen ist.

# Negative Aspekte

Die Verbesserungsvorschläge wurden übernommen, daher gibt es für mich nichts mehr zu bemängeln.

2022-01-16 11:08 UTC, larissadiscua approved these changes
| Kriterium | Bewertung|
|-----|---|
| Front-Matter | ja|
| Umfang | ja|
| Belege | ja |
| Links | ja|
| Formatierung | ja|
| Verlinkungen vorhanden | ja |
| Abbildungen | ja |
| Strukturierung des Beitrags | 10 |
| Rechtschreibung | 10|
| Sprache | 10 |
| Inhalt | 10|
| Einordnung in den Kontext | 10|
| Ansprechend für Zielgruppe | 10|

# Zusammenfassung

Im Artikel handelt es sich um Lessons Learned, also gewonnene Erkenntnisse, die man bei zukünftigen  Projekten anwenden kann, wobei es sich sowohl um positive, als auch negative Erfahrungen handeln kann. Daraufhin wird der Ablauf erläutert und die Schwierigkeiten, die entstehen können.

# Positive Aspekte

Der Beitrag ist verständlich geschrieben, sowohl sprachlich auch als inhaltlich und zeigt einen klaren Aufbau. Weitere Quellenangaben und weiterführende Literatur wurden ergänzt. Insgesamt finde ich, dass der Artikel sehr gut gelungen ist.

# Negative Aspekte

Die Verbesserungsvorschläge wurden übernommen, daher gibt es für mich nichts mehr zu bemängeln.

2022-01-17 20:06 UTC, patrick203494 approved these changes
| Kriterium | Bewertung|
|-----|---|
| Front-Matter | ja |
| Umfang | ja |
| Belege | ja |
| Links | ja |
| Formatierung | ja |
| Verlinkungen vorhanden | ja |
| Abbildungen | ja |
| Strukturierung des Beitrags | 10 |
| Rechtschreibung | 10 |
| Sprache | 10 |
| Inhalt | 10|
| Einordnung in den Kontext | 10|
| Ansprechend für Zielgruppe | 10|

# Zusammenfassung

Der Beitrag beschreibt die „Lessons Learned“ (aus dem Projekt gewonnenes Wissen & Erkenntnisse) als wichtigen Bestandteil des Projektmanagements. Es wird auf den Zweck, den idealtypischen Ablauf der Feststellung & Analyse und mögliche Schwierigkeiten eingegangen. Am Ende findet noch eine Einordnung in den Gesamtkontext statt.


# Positive Aspekte

Der Artikel ist sprachlich sehr gut gestaltet und weist keine Rechtschreibfehler auf. Außerdem ist er klar strukturiert und besitzt einen roten Faden, wodurch der Leser sehr gut durch die herausgearbeiteten Inhalte gelenkt wird. Die eigens erstellte Grafik veranschaulicht den idealtypischen Ablauf des Umgangs mit den „Lessons Learned“ sehr gut. Inhaltlich ist der Beitrag ebenfalls gut aufgebaut und vermittelt dem Leser einen sehr guten Einblick in das Themengebiet. Sehr interessant ist auch die Auflistung der möglichen Schwierigkeiten, die die Durchführung der „Lessons Learned“ erschweren.  Auch die Einordnung in den Gesamtkontext am Ende ist sehr gut gelungen, hierdurch wird die Relevanz des Themas noch einmal herausgearbeitet & klargestellt.


# Negative Aspekte

Sowohl mehr Verlinkungen zu anderen Kompendiumsbeiträgen als auch Quellennachweise am Ende eines jeden Absatzes wurden hinzugefügt, es gibt meiner Meinung nach nichts mehr zu bemängeln. Super Beitrag!

2022-01-19 20:39 UTC, Paulqe42kuno requested changes
| Kriterium | Bewertung|
|-----|---|
| Front-Matter | ja |
| Umfang | ja |
| Belege | ja |
| Links | ja |
| Formatierung | ja |
| Verlinkungen vorhanden | ja |
| Abbildungen | ja |
| Strukturierung des Beitrags | 10 |
| Rechtschreibung | 10 |
| Sprache | 10 |
| Inhalt | 10|
| Einordnung in den Kontext | 10 |
| Ansprechend für Zielgruppe | 10 |

# Zusammenfassung

Lessons Learned befasst sich damit aus Erfahrungen zurückliegender Projekte zu lernen. Zuerst wird dabei das Problem identifiziert und dokumentiert. Anschließend wird es analysiert, gespeichert und für die Mitarbeitenden des Projekts zugänglich gemacht. Schwierigkeiten dabei können sein, dass die Mitarbeitenden sich noch an zurückliegende Probleme erinnern können sowie Stakeholder, die sich wenig bereit zeigen an dem Prozess teilzunehmen. Lessons Learned findet sowohl im agilen als auch im klassischen Projektmanagement statt. 

# Positive Aspekte
Schön finde ich, dass du eine weiterführende Literatur hinzugefügt hast. Jedoch wäre es schön, wenn du diese noch verlinken kannst falls möglich (siehe negative Aspekte). Das Fragezeichen bei Zweck der Lessons Learned hast du rausgenommen. Den Aufbau finde ich nach wie vor gut sowie die Abbildung, die du selbst erstellt hast. Nach wie vor ein guter Artikel 

# Negative Aspekte
Die Wortanzahl (inbegriffen Überschrift) ist sehr knapp über 500. Falls irgendwas nicht zählt, könntest du leicht darunter fallen. Die weiterführende Literatur sowie die Quellen sind nicht alle verlinkt. Im Abschnitt Zweck der Lessons Learned sowie Einordnung fehlt noch eine Quelle. Bis im letzten Abschnitt hast du keine Verlinkungen. Ebenso sind die Verlinkungen immer noch auf die HTML Seite. Ich glaube das ist so nicht richtig. Kann aber auch sein dass html und .md beides akzeptiert wird.

2022-01-24 15:35 UTC, JanAmend commented
> Die Wortanzahl (inbegriffen Überschrift) ist sehr knapp über 500. Falls irgendwas nicht zählt, könntest du leicht darunter fallen. Die weiterführende Literatur sowie die Quellen sind nicht alle verlinkt. Im Abschnitt Zweck der Lessons Learned sowie Einordnung fehlt noch eine Quelle. Mit Ausnahme des letzten Abschnittes hast du keine Verlinkungen. Ebenso sind die Verlinkungen immer noch auf die HTML Seite. Ich glaube das ist so nicht richtig. Kann aber auch sein dass html und .md beides akzeptiert wird.

Kurze Stellungnahme zur Kritik :): 

1. Verlinkung der Quellen:
Bei den Internetquellen ist die Website entsprechend verlinkt. Lediglich bei den Quellen, die keine "klassischen" Internetquellen sind, sondern Bücher oder Paper, ist bewusst keine Verlinkung (auf eine Internetseite) vorgenommen worden.
(siehe auch: https://www.scribbr.de/richtig-zitieren/quellenangabe-buch/)

2. Verlinkung auf HTML Seite macht aus meiner Sicht in Anbetracht des Wikipedia-Charakters mehr Sinn. 

3. Die Wortanzahl erfüllt die Anforderungen an 500 Wörter, weshalb ich den Kritikpunkt nicht nachvollziehen kann.  


Dennoch vielen Dank das Review und die Höchstpunktzahl! :)

2022-01-25 14:14 UTC, merged