Abgabe von Teammanagement
ManagingProjectsSuccessfully/ManagingProjectsSuccessfully.github.io pull request #620
Opened 2021-12-22 22:57 UTC by emir-eroglu

2022-01-14 14:29 UTC, emir-eroglu commented
Hallo ihr drei.
Es ist gut wahrscheinlich, dass ihr mein Endergebnis nicht wiedererkennt.
Das liegt daran, dass Ich kurzfristig vor der Abgabe einen sehr ähnlichen Pull Request entdeckt habe.
Aus diesem Grund musste ich mein großes Thema "Teammanagement" nun auf einen anderen Schwerpunkt aufbauen. 
Ich hoffe, dass trotz kurzzeitiger Umstellung das Artikel gelungen ist.
Danke und viel spaß..

2022-01-16 17:07 UTC, hake1110 requested changes
| Kriterium | Bewertung|
|-----|---|
| Front-Matter | ja |
| Umfang | ja |
| Belege | ja |
| Links | ja |
| Formatierung | ja |
| Verlinkungen vorhanden | ja |
| Abbildungen | ja |
| Strukturierung des Beitrags | 9 |
| Rechtschreibung | 8 |
| Sprache | 9 |
| Inhalt | 8 |
| Einordnung in den Kontext | 9 |
| Ansprechend für Zielgruppe | 10 |

Da der Beitrag grundlegend verändert wurde, sind die Änderungsvorschläge aus dem ersten Review teilweise hinfällig. Daher wird der neue Beitrag gesondert bewertet.

Nach einer kurzen Begriffserklärung wird das Synergetische Teammanagement und die Synergetische Führung genauer erklärt. Es werden die Managementaufgaben beschrieben, die bei der Synergetische Führung zu bewältigen sind. Zum Schluss wird ein kleines Fazit zum Thema Synergetisches Teammanagement gezogen. 


Anschließend wird erläutert, wie ein Team entsteht und dessen einzelne Entwicklungsphasen genauer beschrieben. Am Ende wird in einem Fazit nochmals die Notwendigkeit des Teammanagement verdeutlicht.

Kurze Zusammenfassung des/der Artikel

# Positive Aspekte
* Das Thema "Synergetisches Teammanagement" wird ausführlich und leicht verständlich erklärt.
* Abbildung 3 bietet einen inhaltlichen Mehrwert und ist übersichtlich gestaltet.
* Gute Strukturierung des Beitrags
* Die Tabelle bietet einen Mehrwert und ist stellt eine aussagekräftige Übersicht dar

# Negative Aspekte
## Punktabzug Inhalt
* Das Thema lautet "Teammanagement". Es wird gesagt, dass Synergetisches Teammanagement ein Stil des Teammanagements ist. Der restliche Beitrag bezieht sich nur auf das Synergetische Teammanagement. Entweder hätte ich das Thema "Synergetisches Teammanagement" genannt oder wäre allgemein auf verschieden Stile eingegangen, sodass ein Gesamtüberblick geschaffen wird.
*  Bilder haben keine Bildunterschriften, außer Abbildung 3. Da hätte man eine Beschriftung hinzufügen können, die das Bild beschreibt.
## Punktabzug Strukturierung
* Ein Fazit ist meines Erachtens nicht angebracht, da es sich um einen Beitrag zu einem Thema in einer Enzyklopädie handeln soll. (Das habe ich vergessen beim ersten Review zu erwähnen)

##Sonstiges

* Im Absatz "Synergetisches Teammanagement" wurden keine Belege angegeben
* Der Beleg der Abbildung 3 ist nicht richtig verlinkt

2022-01-17 12:00 UTC, Angie4321 reviewed
| Kriterium | Bewertung|
|-----|---|
| Front-Matter | ja |
| Umfang | ja |
| Belege | ja |
| Links | ja |
| Formatierung | ja |
| Verlinkungen vorhanden | ja |
| Abbildungen | ja |
| Strukturierung des Beitrags | 10 |
| Rechtschreibung | 9 |
| Sprache | 9 |
| Inhalt | 8 |
| Einordnung in den Kontext | 10 |
| Ansprechend für Zielgruppe | 10 |


# Zusammenfassung

Zu Beginn wird mit einem Zitat kurz das Thema "Teammanagement" eingeleitet. Daraufhin wird die synergetische Führung dargestellt und die verschiedenen Managementaufgaben erläutert. In einer Tabelle werden dann noch die notwendigen Schritte und Handlungen in den einzelnen Management-Aufgaben dargestellt. Am Ende erfolgt ein Fazit, welches die Wichtigkeit der Synergetischen Denkweise verdeutlicht und den Beitrag abrundet.

# Positive Aspekte

- Respekt, dass du deinen ganzen Artikel nochmal umgeschrieben hast und dir einen neuen Schwerpunkt gesucht hast.
- Die Einleitung durch das Zitat regt zum Weiterlesen des Beitrags an.
- Das "Synergetische Teammanagement" wird leicht verständlich erklärt.
- Der Inhalt ist zielgerichtet von der Einleitung bis zum Fazit am Ende.
- Es wurde im Text sinnvoll zu anderen Beiträgen des Kompendiums im Text verlinkt.
- Es wurde ein Bild hinzugefügt (Abbildung 3), welches einen inhaltlichen Mehrwert bietet.

# Negative Aspekte

- Du hast leider immernoch keine weiterführenden Quellen zu bspw. Büchern oder YouTube- Videos und mit "Siehe auch" fehlen Verweise zu anderen Beiträgen des Kompendiums.
- Die Quelle 3 hast du hinter der Überschrift verlinkt. Hier muss die Fußnote hinter den Text glaube ich.
- Sehr wenige Belege (im Absatz "synergetisches Teammanagement" gar kein Beleg)
- Fußnote 4 bei Abbildung 3 ist nicht richtig verlinkt und Bilderunterschriften fehlen
- Die Tabelle hat keine Überschrift und man weiß im ersten Moment gar nicht was sie darstellen soll.

2022-01-19 19:31 UTC, phiLippFAU requested changes
| Kriterium | Bewertung |
|-----|---|
| Front-Matter | ja |
| Umfang | ja |
| Belege | ja |
| Links | ja |
| Formatierung | ja |
| Verlinkungen vorhanden | ja |
| Abbildungen | ja |
| Strukturierung des Beitrags | 9 |
| Rechtschreibung | 8 |
| Sprache | 9 |
| Inhalt | 8 |
| Einordnung in den Kontext | 10 |
| Ansprechend für Zielgruppe | 10 |


# Zusammenfassung

Der Beitrag beschäftigt sich mit dem Thema „Teammanagement“. Zu Beginn wird der Begriff mit Hilfe eines Zitates kurz erklärt, worauf ein Einblick in den Bereich des Synergetischen Teammanagements folgt. Im Hauptteil wird der Fokus auf die Synergetische Führung und deren zu bewältigenden Managementaufgaben gelegt. Das abschließende Fazit verdeutlicht die Relevanz der Synergetischen Denkweise.


# Positive Aspekte

* übersichtliche Strukturierung
* Inhalt führt zielgerichtet zum Fazit hin
* geschickter Einbau des Zitates in der Einleitung
* inhaltlicher Mehrwert durch zusätzlich hinzugefügte Abbildung
* sinnvolle Verlinkungen zu anderen Artikeln ("Siehe auch“ fehlt jedoch)
* allgemein gute Erklärung und Verständlichkeit


# Negative Aspekte

* Inhalt:
sehr spezifischer/eingeschränkter Blick auf nur einen Teilbereich (Synergetisches Teammanagement) des Hauptthemas "Teammanagement";
wenige Quellen; keine weiterführende Literatur

* Links:
keine korrekte Verlinkung der Fußnote 4 bei Abbildung 3;
bei den Quellen: Titel der Websiten mit hinterlegtem Link ansprechender (anstatt der reinen URL)

* Rechtschreibung/Grammatik:
"...sind einige Managamentaufgaben zu bewältigen:" (Managementaufgaben);
"Gutes Teammangament ist..." (Teammanagement);
"...als Einheit begreifen denn das stärkt..." (begreifen, denn)

2022-01-25 14:15 UTC, merged