Update Spezialistenteams & Ausgangsanalyse
ManagingProjectsSuccessfully/ManagingProjectsSuccessfully.github.io pull request #624
Opened 2022-01-09 21:37 UTC by ksushaW

Wie in den Reviews aufgezeigt wurde, habe ich nun Bilder zu Veranschaulichung der Beiträge hinzugefügt und diese mit internen Links versehen.

2022-01-14 12:50 UTC, Ne88peni requested changes
# Ausgangsanalyse

| Kriterium | Bewertung|
|-----|---|
| Front-Matter | ja|
| Umfang | ja|
| Belege | ja|
| Links | ja|
| Formatierung | ja|
| Verlinkungen vorhanden | ja |
| Abbildungen | ja |
| Strukturierung des Beitrags | 10 |
| Rechtschreibung | 10 |
| Sprache | 10 |
| Inhalt | 10 |
| Einordnung in den Kontext | 10 |
| Ansprechend für Zielgruppe | 10 |

# Zusammenfassung

Der Artikel gibt einen guten Überblick über das Thema "Ausgangsanalyse". Er geht auf die verschiedenen Faktoren ein, die anhand einer Umfeldanalyse ermittelt werden. Dazu beschreibt er verständlich die Ausgangsanalyse als Basis für Stakeholder- und Risikoanalyse.

# Positive Aspekte


 * Der Artikel ist gut strukturiert und ausführlich.
 * Die Vorgabe von +/- 500 Wörtern wurde perfekt eingehalten im Rahmen der 10% Abweichung.
 * Verlinkungen zu anderen MPS-Themen und Abbildungen sind vorhanden, welche den Artikel bereichern.

# Negative Aspekte

* Weiterführende Literatur fehlt noch.

2022-01-15 10:37 UTC, Ne88peni requested changes
# Spezialistenteams

| Kriterium | Bewertung|
|-----|---|
| Front-Matter | ja |
| Umfang | ja |
| Belege | ja |
| Links | ja |
| Formatierung | ja |
| Verlinkungen vorhanden | ja |
| Abbildungen | ja |
| Strukturierung des Beitrags | 10 |
| Rechtschreibung | 10 |
| Sprache | 10 |
| Inhalt | 10 |
| Einordnung in den Kontext | 10 |
| Ansprechend für Zielgruppe | 10 |

# Zusammenfassung

Der Artikel befasst sich mit dem Thema "Spezialistenteams" in Bezug auf das klassische Projektmanagement. Er erklärt die Bedutung des Begriffs "Spezialistenteams" 
und geht auf die verschiedenen Faktoren eines Spitzenteams ein.

# Positive Aspekte

* Der Artikel ist gut strukturiert.
* Der Atrikel ist inhaltlich und sprachlich korrekt verfasst.
* Abbildung schafft einen guten Überblick über das Spitzenteam.
* Verlinkungen zu anderen Github-Themen sind vorhanden.
* Links funktionieren einwandfrei.


# Negative Aspekte

* Weiterführende Literatur fehlt.
* Mehr Quellen sind empehlenswert.

2022-01-19 19:41 UTC, Meyu23 requested changes
# Ausgangsanalyse

| Kriterium | Bewertung|
|-----|---|
| Front-Matter | ja |
| Umfang | ja |
| Belege | ja |
| Links | ja |
| Formatierung | ja |
| Verlinkungen vorhanden | ja |
| Abbildungen | ja |
| Strukturierung des Beitrags | 10 |
| Rechtschreibung | 10|
| Sprache | 10 |
| Inhalt | 10|
| Einordnung in den Kontext | 9|
| Ansprechend für Zielgruppe | 10|

# Zusammenfassung

Der Artikel gibt einen strukturierten Überblick über das Thema "Ausgangsanalyse". Es werden verschiedene Faktoren näher erklärt. Anschließend wird verständlich und zusammenhängend erklärt wie diese Informationen, welche aus der Ausgangsanalyse stammen für weitere Analysen, wie z.B. die Stakeholder- oder Risikoanalyse, verwendet werden können.

# Positive Aspekte

Das Thema wird ausführlich, zusammenhängend und gut strukturiert erläutert. Die verwendete Sprache ist sachlich und nüchtern. Die Länge des Beitrages stimmt mit den Vorgaben überein. Abbildungen, Verlinkungen und Formatierungen wurden korrekt umgesetzt.

# Negative Aspekte

Es fehlt immer noch die weiterführende Literatur.

2022-01-19 19:55 UTC, Meyu23 requested changes
# Spezialistenteams

| Kriterium | Bewertung|
|-----|---|
| Front-Matter | ja |
| Umfang | ja|
| Belege | ja |
| Links | ja |
| Formatierung | ja |
| Verlinkungen vorhanden | nein |
| Abbildungen | nein |
| Strukturierung des Beitrags | 10 |
| Rechtschreibung | 10 |
| Sprache | 10 |
| Inhalt | 10 |
| Einordnung in den Kontext | 9 |
| Ansprechend für Zielgruppe | 10 |

# Zusammenfassung

In dem Beitrag wird die Bedeutung und Merkmale von Spezialistenteams erläutert. Es handelt sich um eine Gruppe von Fachexperten, welche benötigtes Fachwissen für die Projekte mitbringen. Insgesamt bilden die Mitglieder eines solchen Teams das Spitzenteam. Dieses wird in die verschiedenen Merkmale aufgeteilt und erklärt. Schließlich wird am Ende des Artikels eine kurze schlüssige Zusammenfassung gegeben.

# Positive Aspekte

Das Thema wird ausführlich, zusammenhängend, anschaulich und gut strukturiert erläutert. Der Beitrag verwendet sachliche Sprache und korrekte Rechtschreibung. Die Länge des Beitrages stimmt mit den Vorgaben überein. Die einführende Definition des Themas ist sehr gut.

# Negative Aspekte

Zwei Quellen sind vielleicht ein bisschen zu wenig. Die weiterführende Literatur fehlt noch.

2022-01-19 20:57 UTC, BeratGuen requested changes
| Kriterium | Bewertung|
|-----|---|
| Front-Matter | ja |
| Umfang | ja |
| Belege | ja |
| Links | ja |
| Formatierung | ja |
| Verlinkungen vorhanden | ja |
| Abbildungen | ja |
| Strukturierung des Beitrags | 10 |
| Rechtschreibung | 10 |
| Sprache | 10 |
| Inhalt | 10 |
| Einordnung in den Kontext | 9|
| Ansprechend für Zielgruppe | 10 |

# Zusammenfassung
Der Beitrag handelt von der Ausgangsanalyse, die als erster Schritt der Projektdefinition beschrieben wird. Durch Erfassung des Ist-Zustands und Ermittlung von internen, externen, sozialen und sachlichen Faktoren, kann der Einfluss dieser auf den weiteren Projektverlauf gewichtet werden.


# Positive Aspekte
Der Beitrag ist sachlich, strukturiert und ausführlich gestaltet. 
Es wird durchgehend auf korrekte Rechtschreibung und Grammatik geachtet, was zu einer guten Lesbarkeit führt. Die anfängliche Definition, sowie Einordnung in den Projektablauf bieten einen guten Einstieg.

Es wurden nachträglich eine Abbildung und Verlinkungen zu angrenzenden Github-Artikeln in den Beitrag eingepflegt, die den Beitrag weiter abrunden.
 
# Negative Aspekte

Im Artikel fehlt die weiterführende Literatur zur besseren Einordnung in den Kontext.

2022-01-19 21:11 UTC, BeratGuen commented
| Kriterium | Bewertung|
|-----|---|
| Front-Matter | ja |
| Umfang | ja |
| Belege | ja |
| Links | ja |
| Formatierung | ja |
| Verlinkungen vorhanden | ja |
| Abbildungen | ja |
| Strukturierung des Beitrags | 10 |
| Rechtschreibung | 10 |
| Sprache | 10 |
| Inhalt | 10 |
| Einordnung in den Kontext | 9 |
| Ansprechend für Zielgruppe | 10 |

# Zusammenfassung
Der Beitrag stellt die Bedeutung des Spezialistenteams in Bezug auf das klassische Projektmanagement dar. Es besteht aus Mitgliedern mit hohen Fachkompetenzen, die vom Projektmanager in das Team einberufen werden. Zusammen mit den weiteren beteiligten Mitgliedern des Projektes bildet sich das Spitzenteam, welches durch die im Beitrag genannten sieben Faktoren charakterisiert wird. 


# Positive Aspekte
Der Beitrag ist inhaltlich und sprachlich korrekt verfasst und strukturiert gestaltet. Dabei wurde auf korrekte Rechtschreibung, Grammatik, Formatierung und sachliche Wortwahl im Sinne des Enzyklopädiestils, sowie auf durchgängigen Quellenbezug geachtet. Die einführende Definition bietet eine erste Einordnung in den Kontext.

Es wurden eine Abbildung und Verlinkungen zu weiteren Github Beiträgen in den Beitrag aufgenommen.

# Negative Aspekte

Durch zusätzliche Verlinkung zu weiteren Beiträgen oder weiterführender Literatur kann der Beitrag in den Kontext noch besser eingeordnet werden.

2022-01-25 14:15 UTC, merged