Zukunftswerkstatt, Soft Skills im Projektmanagement
ManagingProjectsSuccessfully/ManagingProjectsSuccessfully.github.io pull request #631
Opened 2022-01-10 17:39 UTC by ig27oqaf

2022-01-11 15:36 UTC, 5SY5 requested changes
**Softskills im Projektmanagement**
| Kriterium | Bewertung|
|-----|---|
| Front-Matter | ja|
| Umfang | ja|
| Belege | ja|
| Links | ja|
| Formatierung | ja|
| Verlinkungen vorhanden | ja |
| Abbildungen | ja |
| Strukturierung des Beitrags | 8 |
| Rechtschreibung | 9|
| Sprache | 10|
| Inhalt | 9|
| Einordnung in den Kontext | 10|
| Ansprechend für Zielgruppe | 10|

# Zusammenfassung

Zu Beginn werden die Aufgaben des Projektmanagement einfließen erläutert und dabei auf die Soft Skills eingelenkt. Daraufhin wird mit Hilfe einer kurzen Definition der Soft Skills übergeleitet in den nächsten Abschnitt, welcher die Wichtigkeit der Soft Skills im Projektmanagement beschreibt. Dabei wird auch angemerkt, dass diese Fähigkeit für eine gute Teamarbeit  erst recht in der Zeit der Pandemie eine enorme Wichtigkeit hat.
Außerdem werden die wichtigsten Punkte des Soft Skills genannt und näher erläutert, dazu zählen: Eigeninitiative, Vernetztes Denken, Kooperation und Konfliktfähigkeit, Flexibilität/Agilität. Mit der Beschreibung des letzten Punktes endet der Beitrag. 

# Positive Aspekte

Es ist eine eindeutige Verbesserung zu dem vorherigen Bericht zu sehen. Die dezente Einbindung der Abbildung find ich gut. Die Strukturierung des Beitrags ist viel Besser und verständlicher. Die Verlinkungen funktionieren alle gut und auch das einbinden von der weiterführenden Literatur ist sehr gut. 
Der Bericht erklärt den Sachverhalt anschaulich und verständlich.

# Negative Aspekte

Es gibt eigentlich nichts stark zu kritisieren, nur zwei Anmerkungen. Erstens es wäre besser die Überschrift von "wichtige Soft Skills im Projektmanagement" in die zweite Ebene zu rücken und dafür die unteren Aspekte in die dritte Ebene. Zweitens aus gründen der Einheitlichkeit würde ich raten Soft Skills immer groß und getrennt zu schreiben (in den Zwischenüberschriften war einmal "Soft" klein und einmal "Soft Skills" zusammen geschrieben).
Ansonsten ein guter solider Beitrag 👍


**Zukunftswerkstatt** 

| Kriterium | Bewertung|
|-----|---|
| Front-Matter | ja |
| Umfang | ja|
| Belege | ja |
| Links | ja|
| Formatierung | ja|
| Verlinkungen vorhanden | ja|
| Abbildungen | ja|
| Strukturierung des Beitrags | 10 |
| Rechtschreibung | 9|
| Sprache | 9 |
| Inhalt | 10|
| Einordnung in den Kontext | 10|
| Ansprechend für Zielgruppe | 10|

# Zusammenfassung

Am Anfang des Beitrags werden die Forscher vorgestellt, die die Methode der Zukunftswerkstatt begründet haben. Darauffolgend wird die Geschichte aufgezeigt und im Anschluss dazu die einzelnen Anwendungsgebiete aufgezählt. 
Weiterhin werden die drei Phasen der Zukunftswerkstatt erläutert und mit einer Abbildung verstärkt. Abschließend wird noch das Praxisbeispiel von Google aufgezeigt.

# Positive Aspekte

Sehr guter Beitrag mit einer guten Strukturierung und der Inhalt ist der sehr verständlich. 
Weiterhin ist positiv anzumerken, dass hier ein Beispiel herangezogen wurde und die Abbildung veranschaulicht nochmals die einzelnen Phasen für ein besseres Verständnis.
Des Weiteren funktionieren alle Links.

# Negative Aspekte

Es ist eine guter solider Beitrag und ich habe nichts zu kritisieren oder irgendwelche Verbesserungsvorschläge jeglicher Art.

2022-01-11 16:37 UTC, zo54hoko requested changes
Zukunftswerkstatt

Kriterium | Bewertung
-- | --
Front-Matter | ja
Umfang | ja
Belege | ja
Links | ja
Formatierung | ja
Verlinkungen vorhanden | ja
Abbildungen | ja
Strukturierung des Beitrags | 10
Rechtschreibung | 10
Sprache | 10
Inhalt | 10
Einordnung in den Kontext | 10
Ansprechend für Zielgruppe | 10


Zusammenfassung

Der Beitrag informiert zunächst über die Geschichte, der Zukunftswerkstätte und klärt im darauffolgenden über die Anwendungsbereiche derer auf, wie beispielsweise Teamentwicklung oder Projektmanagement. Im Anschluss wird auf den Aufbau von Zukunftswerkstätte eingegangen, der insgesamt aus drei Phasen besteht. Die Kritikphase, die Fantasie- & Utopiephase und zuletzt die Realisierungs- bzw. Strategiephase. Zum Schluss wird das Praxisbeispiel Google erläutert.



positive Aspekte

Die Kritierien sind immer noch alle erfüllt, es ist ein gut gelungener Beitrag mit guter Sprache und einem schönen Aufbau, sodass man Freude daran hat den Beitrag zu lesen. Schön ist auch die angegebene weiterführende Literatur und, dass im Text auf die informative Abbildung eingegangen wird. Das Praxisbeispiel Google rundet den Beitrag zum Schluss gut ab.


negative Aspekte

Es gibt keine negativen Aspekte, ein gut gelungener Beitrag.


Soft skills im Projektmanagement

Kriterium | Bewertung
-- | --
Front-Matter | ja
Umfang | ja
Belege | ja
Links | ja
Formatierung | ja
Verlinkungen vorhanden | ja
Abbildungen | ja
Strukturierung des Beitrags | 9
Rechtschreibung | 10
Sprache | 10
Inhalt | 10
Einordnung in den Kontext | 10
Ansprechend für Zielgruppe | 10


Zusammenfassung

In diesem Beitrag handelt es sich um die soft Skills im Projektmanagement. Zunächst geht es um die allgemeine Definition von soft Skills, die beschreibt, dass diese persönliche Werte (z. B. Fairness & Respekt), persönlichen Eigenschaften (z. B. Geduld), individuellen Fähigkeiten (z. B. Kritikfähigkeit) und soziale Kompetenzen (z. B. Kommunikationsfähigkeit) von Führungskräften und Mitarbeitern eines Unternehmens umfassen. Daraufhin wird die Bedeutung der soft Skills im Projektmanagement erläutert. Zuletzt wird auf besonders wichtige soft Skills im Projektmanagement näher eingegangen, dazu gehören Eigeninitiative, vernetztes Denken, Kooperation und Konfliktfähigkeit, Flexibilität bzw. Agilität.



positive Aspekte

Die Kritierien sind weiterhin erfüllt, es ist ein gut gelungener Beitrag mit einer leicht verständlichen Sprache und schönem Aufbau. Die Abbildung wurde gut gewählt und man erhält durch den neuen Aufbau einen viel besseren Überblick. Sehr informativer Beitrag, auch durch die weiterführende Literatur.

negative Aspekte

Gelungener Beitrag, ich habe nichts zu bemängeln.

2022-01-13 08:38 UTC, LKmps2021 requested changes
Softskills_im_Projektmanagement

Kriterium | Bewertung
-- | --
Front-Matter | ja |
Umfang | ja |
Belege | ja |
Links | ja |
Formatierung | ja |
Verlinkungen vorhanden | ja |
Abbildungen | ja |
Strukturierung des Beitrags | 9 |
Rechtschreibung | 9 |
Sprache | 9 |
Inhalt | 10 |
Einordnung in den Kontext | 10 |
Ansprechend für Zielgruppe | 10 |

# Zusammenfassung

Der Artikel beschäftigt sich mit dem Thema Softskills im Projektmanagement. Hierbei wird zunächst das Thema definiert. Anschließen werden die Soft Skills im Projektmanagement erläutert und es wird mit einer Grafik verdeutlich, warum diese wichtig sind. Im Anschluss geht der Autor auf die wichtigsten Kompetenzen (Eigeninitiative, Vernetztes Denken, Kooperation und Konfliktfähigkeit und Flexibilität/Agilität) im Bereich der Soft Skills ein.

# Positive Aspekte

Die Quellenangaben besitzen nun Titel. Auch wurde weiterführende Literatur verlinkt. Die Grafik wurde ordnungsgemäß verlinkt. Ihre Position ist nun stimmig und sie wurde in das Thema mit eingearbeitet. Auch die Formatierungen sind nun anschaulicher, wodurch der Artikel übersichtlicher wird. 

# Negative Aspekte

Die Überschrift "Wichtige Soft Skills im Projektmanagement" sollte als Überschrift zweiten Grades definiert werden und die Punkte Eigeninitiative, Vernetztes Denken, Kooperation und Konfliktfähigkeit und Flexibilität/Agilität sollten als Überschrift dritten Grades definiert werden. Außerdem muss der Begriff Soft Skills einheitlich geschrieben werden, am besten immer groß und getrennt.

Zukunftswerkstatt

Kriterium | Bewertung
-- | --
Front-Matter | ja |
Umfang | ja |
Belege | ja |
Links | ja |
Formatierung | ja |
Verlinkungen vorhanden | ja |
Abbildungen | ja |
Strukturierung des Beitrags | 9 |
Rechtschreibung | 9 |
Sprache | 10 |
Inhalt | 10 |
Einordnung in den Kontext | 10 |
Ansprechend für Zielgruppe | 9 |

# Zusammenfassung

Der Artikel beschreibt das Thema Zukunftswerkstatt. Im ersten Abschnitt wird das Thema definiert. Im zweiten Abschnitt wird die Geschichte der Zukunftswerkstätten erläutert. Danach werden die Anwendungsfälle kurz stichpunktartig aufgeführt. Im nächsten Absatz werden dann die drei Phasen Kritikphase - Bestandsaufnahme, Fantasie- & Utopiephase, Realisierungs- Strategiephase erläutert. Zum Abschluss wird nochmal auf die Anwendung in der Praxis von Zukunftswerkstätten am Beispiel von Google eingegangen.

# Positive Aspekte

Die Quellenangaben besitzen nun Titel. Auch wurde nun weiterführende Literatur verlinkt. Die Grafik wurde ordnungsgemäß verlinkt. Zusätzlich wurden die Verlinkungen zu anderen Themenbereichen ergänzt und erweitert.

# Negative Aspekte

In dem Kapitel „Anwendungsgebiete der Zukunftswerkstatt“ wird noch immer nicht ersichtlich auf was sich die Aufzählung bezieht. Der Satz, der zuvor geschrieben wurde, erklärt die folgende Aufzählung nicht. Es lassen sich noch Rechtschreibfehler finden (Weierführende Literatur).

2022-01-13 10:46 UTC, ig27oqaf commented
Lkmps2021,
leider verstehe ich deinen Kritikpunkt bei der Zukunftswerkstatt nicht. Die Unterpunkte beziehen sich natürlich auf die Anwendungsgebiete der Zukunftswerkstatt, sonst hätte ich die Überschrift nicht gewählt. Vielleicht erläuterst du mir, was du nicht verstehst.

2022-01-13 11:00 UTC, LKmps2021 commented
> Lkmps2021, leider verstehe ich deinen Kritikpunkt bei der Zukunftswerkstatt nicht. Die Unterpunkte beziehen sich natürlich auf die Anwendungsgebiete der Zukunftswerkstatt, sonst hätte ich die Überschrift nicht gewählt. Vielleicht erläuterst du mir, was du nicht verstehst.

Der offene Ansatz der Zukunftswerkstatt findet in vielen Bereichen, wie Start-ups, Wirtschaftsunternehmen, Schulklassen, sozialen Vereinen und Gemeinden, Anschluss.
_(Hier fehlt meiner Meinung nach eine Einleitung zu den Stichpunkten
 z.B: In folgenden Gebieten wird das Prinzip der Zukunftsforschung besonders häufig angewandt: )_ 

    Organisations- und Unternehmensentwicklung
    Leitbildentwicklung und Zukunftsprofil
    Teamentwicklung
    als Tool für Startups, Unternehmensgründer/innen und Projektentwickler/innen
    Projektmanagement
    Partizipative Gemeinde- und Regionalentwicklung
    Partizipative Raum-, Umwelt- und Stadtplanung 3.

 z.B: In folgenden Gebieten findet das Prinzip der Zukunftsforschung anwendung:

2022-01-13 16:10 UTC, ig27oqaf commented
Danke für deine konstruktive Kritik. Ich finde den Weg, den ich gewählt habe jedoch passender.

2022-01-15 14:54 UTC, LKmps2021 commented
Kein Problem war nur ein Vorschlag.
Meine Gedanken hinter dem Punkt waren: 
1.	Der Einschub macht das Kapitel übersichtlicher und verständlicher. Da man so wie es im Moment aufgebaut ist erstmal verstehen muss, dass es sich auf die Überschrift bezieht und nicht auf den Satz davor. 
2.	Du hattest nur sehr knapp 500 Wörter. Da hätte man sowas auch ohne Probleme einfügen können.

2022-01-15 15:00 UTC, ig27oqaf commented
Der Satz darunter meint die Bereiche, in denen die Zukunftswerkstatt ihre Anwendung findet. In Start ups zur Teamentwicklung beispielsweise. Ich glaube du denkst hier zu kompliziert.

2022-01-25 14:16 UTC, merged