Projektmanagement_Geographische_Unterschiede
ManagingProjectsSuccessfully/ManagingProjectsSuccessfully.github.io pull request #67
Opened 2021-11-19 10:19 UTC by Phil224

2021-11-19 10:20 UTC, Phil224 commented
New Version

2021-11-27 15:57 UTC, Lorybr requested changes
| Kriterium | Bewertung|
|-----|---|
| Front-Matter | ja |
| Umfang | ja|
| Belege | ja |
| Links | ja|
| Formatierung | ja|
| Verlinkungen vorhanden | nein |
| Abbildungen | ja |
| Strukturierung des Beitrags | 10 |
| Rechtschreibung | 10|
| Sprache | 10 |
| Inhalt | 10|
| Einordnung in den Kontext | 10|
| Ansprechend für Zielgruppe | 10|

# Zusammenfassung

Der Artikel befasst sich mit den geographischen Unterschiede des Projektmanagements, indem die Aspekte wie Führung, Kommunikation, Ich und Wir-Kulturen und Beziehungsebene der West sowie der Ost Kultur verglichen werden.

# Positive Aspekte
Alles wurde klar und genau formuliert. Es gibt eine angemessene Einführung und einen Fazit in Form einer Tabelle.

# Negative Aspekte
Die Belege deiner Quellen sind zwar vorhanden, aber:
es wurden keine andere Themen aus dem Kompendium verlinkt, zb. andere Unter- und Überthemen sowie angrenzende Themengebieten. Würde sich bei dem unterem Punkt ,,Siehe auch:" anbieten.

2021-11-29 14:45 UTC, LindaStu requested changes
| Kriterium | Bewertung|
|-----|---|
| Front-Matter | ja |
| Umfang | ja|
| Belege | ja |
| Links | ja|
| Formatierung | ja|
| Verlinkungen vorhanden | nein |
| Abbildungen | ja |
| Strukturierung des Beitrags | 10 |
| Rechtschreibung | 9|
| Sprache | 10 |
| Inhalt | 10|
| Einordnung in den Kontext | 10|
| Ansprechend für Zielgruppe | 10|

# Zusammenfassung

Im Text zu geographischen Unterschieden wird zuerst auf die kulturelle Herkunft eingegangen, dann auf Machtdistanzen, Kommunikation im Projektmanagement mit geographischen Unterschieden, auf verschiedene Kulturen und die Beziehungsebene.

# Positive Aspekte

Finde den China - DE Vergleich sehr gut, weil auch schon im Text auf die Unterschiede zwischen Asien und Europa eingegangen wurde. Insgesamt finde ich den Text gut und verständlich formuliert. Gliederung gefällt mir auch sehr gut. 

# Negative Aspekte

Nur eine Kleinigkeit, bei dem Absatz Ich und Wir - Kulturen wird "osteuropäischen" klein geschrieben. 
Würde bei den Quellen eine Überschrift herausnehmen, braucht man nicht doppelt. 
Bei Weiterführende Literatur fehlt ein Titel, nicht nur Website: und bei siehe auch fehlen Verlinkungen zu anderen Themen, nicht nur zur eigenen Seite.

2021-12-06 15:50 UTC, AnjaKlostermeier requested changes
| Kriterium | Bewertung|
|-----|---|
| Front-Matter | ja |
| Umfang | ja|
| Belege | ja|
| Links | ja|
| Formatierung | ja|
| Verlinkungen vorhanden | nein |
| Abbildungen | ja |
| Strukturierung des Beitrags | 9|
| Rechtschreibung | 10 |
| Sprache | 10 |
| Inhalt | 10|
| Einordnung in den Kontext | 8|
| Ansprechend für Zielgruppe | 10|

# Zusammenfassung

Dieser Beitrag befasst sich mit den geographischen Unterschieden im Projektmanagement. Zuerst wird der Begriff Kultur vom Project Management Institute definiert. Anschließend werden die verschiedenen geographischen Unterschiede aufgezählt und am Ende ein Vergleich zwischen China und Deutschland dargestellt.

# Positive Aspekte

Der Beitrag wurde verständlich und in einer angemessenen Länge formuliert. Ebenfalls wurden die einzelnen geographischen  Unterschiede gut erklärt. Die Tabelle, die den Vergleich zwischen China und Deutschland veranschaulicht finde ich sehr gut eingebaut. Damit bekommt der Leser bzw. die Leserin ein besseres Gespür für die Thematik. 

# Negative Aspekte

Gut wären Verlinkungen auf themenähnliche Beiträge aus dem Kompendium. Ebenfalls könnte man gleich zu Beginn des Beitrags eine Überschrift mit dem Thema "Geographische Unterschiede im Projektmanagement" anbringen. 
Bei dem Punkt "Siehe auch" fehlen Verlinkungen zu weiteren Beiträgen/Websites. Auch bei dem Reiter "Weiterführende Literatur" würde ich die Bezeichnung "Website" weglassen. 
Die Grafik könnte man durch ein paar Sätze kurz erklären, damit sie nicht so leer im Raum steht. 
Bei den Quellen würde ich den Namen der Quelle mit dem jeweiligen Link versehen, damit alles "blau" hinterlegt ist.

2021-12-09 19:27 UTC, merged