Zielbeziehungen
ManagingProjectsSuccessfully/ManagingProjectsSuccessfully.github.io pull request #71
Opened 2021-11-19 15:07 UTC by AnjaKlostermeier

2021-11-27 15:30 UTC, Kisara2426 requested changes
# Zielbeziehungen
| Kriterium | Bewertung|
|-----|---|
| Front-Matter | nein|
| Umfang | ja|
| Belege | nein |
| Links | nein|
| Formatierung | nein|
| Verlinkungen vorhanden | ja|
| Abbildungen | ja|
| Strukturierung des Beitrags |7|
| Rechtschreibung | 8|
| Sprache | 8 |
| Inhalt | 8|
| Einordnung in den Kontext | 9|
| Ansprechend für Zielgruppe | 8|

# Zusammenfassung

Der Artikel befasst sich mit dem Thema der Zielbeziehungen und beginnt mit der Definition des Begrifft und der Erklärung der unterschiedlichen Arten von Beziehungen zwischen Zielen. Anschließend folgt die Definition vom klassischen Projektmanagement und dessen wichtigsten Merkmalen. Im Weiteren werden die beiden vorher definierten Begriffe in Beziehung zueinander behandelt indem das zu erreichende priorisierte Ziel und die damit verbundenen Leistungen gegenübergestellt werden. Zum Ende wird noch auf die Zielbeziehungsmatrix, auch Präferenzmatrix eingegangen. 

# Positive Aspekte

Abbildung: Gefällt mir sehr gut, ist übersichtlich und informativ 

# Negative Aspekte

Formatierung: Thema ist nicht die größte Überschrift. 
Strukturierung: Übersichtlicher gestalten, bin mir der Struktur nicht sicher. Was sind Ober-, was Unterpunkte. Titel fehlt auch. 
Link: Quelle 1 existiert nicht, Verlinkungen aufs Kompendium sind in deinem eigenen Fork.
Belege: Erste Abbildung hat keinen oder braucht einen eigenen
Rechtschreibung: Unter Zielbeziehungen wir die Beziehung zwischen den einzelnen Ziele(N) (meist Unternehmensziele) beschrieben.
Front-Matter: muss k sein, da du das hier behandelst 


# Umgang mit Kritik 
| Kriterium | Bewertung|
|-----|---|
| Front-Matter | nein|
| Umfang | ja|
| Belege | ja|
| Links | nein|
| Formatierung | ja|
| Verlinkungen vorhanden | ja|
| Abbildungen | ja|
| Strukturierung des Beitrags |10 |
| Rechtschreibung |10|
| Sprache | 8 |
| Inhalt | 10|
| Einordnung in den Kontext | 9|
| Ansprechend für Zielgruppe | 10|

# Zusammenfassung

Der Artikel befasst sich mit dem Thema wie man mit Kritik richtig umgehen kann. Nach der Begriffserklärung und der stichpunktartigen Aufzählung verschiedener Kritikarten, folgt in Form einer Abbildung die Übersicht wie in allgemeinen Situationen mit Kritik umgegangen werden kann. Anschließend wird der Begriff des Agilen Projektmanagements erklärt, ergänzt durch den Abschnitt über den Umgang mit Kritik im agilen Projektmanagement mit tabellarisch aufgezählten Dos and Donts. 

# Positive Aspekte

Belege: sind überall vorhanden
Abbildung: Gefällt mir sehr gut, ist übersichtlich und informativ 
Strukturierung des Beitrags: Gute Aufteilung und Auswahl der Oberpunkte, sehr übersichtlich
Formatierung: Liste ist mit Punkten 


# Negative Aspekte

Link: Verlinkungen aufs Kompendium sind in deinem eigenen Fork!
Front Matter: Zuordnung muss bei a sein, da du das in deinem Text behandelst.

2021-11-27 16:02 UTC, Lorybr commented
@Kisara2426 du musst diese Tabelle ausfüllen

2021-11-27 16:02 UTC, Lorybr commented
Also entweder ja oder nein auswählen..

2021-11-27 16:27 UTC, Lorybr requested changes
| Kriterium | Bewertung|
|-----|---|
| Front-Matter | ja |
| Umfang | ja|
| Belege | ja |
| Links | ja|
| Formatierung | ja|
| Verlinkungen vorhanden | ja |
| Abbildungen | ja |
| Strukturierung des Beitrags | 10 |
| Rechtschreibung | 10|
| Sprache | 10 |
| Inhalt | 10|
| Einordnung in den Kontext | 10|
| Ansprechend für Zielgruppe | 10|

# Zusammenfassung

Der Artikel befasst sich mit der Umgang mit Kritik in einem Projektmanagement. Somit werden mehrere Lösungen beschrieben, wie man mit der Kritik umgehen kann, sowie do's und don'ts.

# Positive Aspekte
Alles wurde klar und genau Formuliert. Die angrenzende Themen aus dem Kompendium wurden auch oft verlinkt.

# Negative Aspekte
Versuche die Literatur angemessener zu verlinken (bei Quellen). Also nicht nur den Link, sondern eventuell auch den Autor, Jahr oder Titel dazuschreiben :)

2021-11-29 14:17 UTC, LindaStu commented
Zielbeziehung

| Kriterium | Bewertung|
|-----|---|
| Front-Matter | ja |
| Umfang | ja|
| Belege | ja |
| Links | ja|
| Formatierung | ja|
| Verlinkungen vorhanden | ja |
| Abbildungen | ja |
| Strukturierung des Beitrags | 10 |
| Rechtschreibung | 9|
| Sprache | 10 |
| Inhalt | 10|
| Einordnung in den Kontext | 9|
| Ansprechend für Zielgruppe | 10|

# Zusammenfassung

Zielbeziehungen im klassischen Projektmanagement. Zuerst wurden die Themen einzeln erklärt, dann zusammengeführt.
Zuerst wurden die Arten von Zielbeziehungen erklärt, dann kurz auf das klassische Projektmanagement eingegangen. Dann wurde die Wichtigkeit der Zielbeziehungen im klassischen Projektmanagement beschrieben, mit Beispielen. Am Ende wird noch auf die Zielbeziehungsmatrix eingegangen.

# Positive Aspekte

Übersichtlich gestaltet, gut erklärt, auch durch z.B. die Tabellen finde ich den Beitrag gut strukturiert und veranschaulicht dargestellt. Finde auch den Aufbau gut, zuerst auf die Themen einzeln einzugehen und diese dann zu verbinden.

# Negative Aspekte

Finde den einleitenden Satz bisschen unnötig da oben und dass dafür einen extra Absatz erstellt wurde, vielleicht entweder noch mehr als einleitenden Satz schreiben oder den Absatz weglassen.
Bei der Verlinkung des agilen Projektmanagements kommt man auf die Seite Umgang mit Kritik, nicht auf die des agilen Projektmanagements


Umgang mit Kritik

| Kriterium | Bewertung|
|-----|---|
| Front-Matter | ja |
| Umfang | ja|
| Belege | ja |
| Links | ja|
| Formatierung | ja|
| Verlinkungen vorhanden | ja |
| Abbildungen | ja |
| Strukturierung des Beitrags | 10 |
| Rechtschreibung | 10|
| Sprache | 10 |
| Inhalt | 10|
| Einordnung in den Kontext | 10|
| Ansprechend für Zielgruppe | 10|

# Zusammenfassung

Hier wird auch zuerst der Begriff Kritik erklärt, dann das agile Projektmanagement und dann wurden die Begriffe zusammengefasst. Dann gibt es noch eine Liste mit Beispielen.


# Positive Aspekte

Finde den Text gut erklärt. Man versteht schnell um was es darin geht und bekommt auch direkt Beispiele wie man mit Kritik umgehen sollte. Das Thema wurde gut eingeleitet und wurde auch sehr gut strukturiert. 

# Negative Aspekte

Hab nichts zu bemängeln.

2021-11-29 14:23 UTC, LindaStu requested changes
# Zielbeziehung

| Kriterium | Bewertung|
|-----|---|
| Front-Matter | ja |
| Umfang | ja|
| Belege | ja |
| Links | ja|
| Formatierung | ja|
| Verlinkungen vorhanden | ja |
| Abbildungen | ja |
| Strukturierung des Beitrags | 10 |
| Rechtschreibung | 9|
| Sprache | 10 |
| Inhalt | 10|
| Einordnung in den Kontext | 9|
| Ansprechend für Zielgruppe | 10|

# Zusammenfassung

Zielbeziehungen im klassischen Projektmanagement. Zuerst wurden die Themen einzeln erklärt, dann zusammengeführt.
Zuerst wurden die Arten von Zielbeziehungen erklärt, dann kurz auf das klassische Projektmanagement eingegangen. Dann wurde die Wichtigkeit der Zielbeziehungen im klassischen Projektmanagement beschrieben, mit Beispielen. Am Ende wird noch auf die Zielbeziehungsmatrix eingegangen.

# Positive Aspekte

Übersichtlich gestaltet, gut erklärt, auch durch z.B. die Tabellen finde ich den Beitrag gut strukturiert und veranschaulicht dargestellt. Finde auch den Aufbau gut, zuerst auf die Themen einzeln einzugehen und diese dann zu verbinden.

# Negative Aspekte

Finde den einleitenden Satz bisschen unnötig da oben und dass dafür einen extra Absatz erstellt wurde, vielleicht entweder noch mehr als einleitenden Satz schreiben oder den Absatz weglassen.
Bei der Verlinkung des agilen Projektmanagements kommt man auf die Seite Umgang mit Kritik, nicht auf die des agilen Projektmanagements


# Umgang mit Kritik

| Kriterium | Bewertung|
|-----|---|
| Front-Matter | ja |
| Umfang | ja|
| Belege | ja |
| Links | ja|
| Formatierung | ja|
| Verlinkungen vorhanden | ja |
| Abbildungen | ja |
| Strukturierung des Beitrags | 10 |
| Rechtschreibung | 10|
| Sprache | 10 |
| Inhalt | 10|
| Einordnung in den Kontext | 10|
| Ansprechend für Zielgruppe | 10|

# Zusammenfassung

Hier wird auch zuerst der Begriff Kritik erklärt, dann das agile Projektmanagement und dann wurden die Begriffe zusammengefasst. Dann gibt es noch eine Liste mit Beispielen.


# Positive Aspekte

Finde den Text gut erklärt. Man versteht schnell um was es darin geht und bekommt auch direkt Beispiele wie man mit Kritik umgehen sollte. Das Thema wurde gut eingeleitet und wurde auch sehr gut strukturiert. 

# Negative Aspekte

Hab nichts zu bemängeln.

2021-12-09 19:27 UTC, merged