Kanban Pull Prinzip
ManagingProjectsSuccessfully/ManagingProjectsSuccessfully.github.io pull request #73
Opened 2021-11-19 17:03 UTC by LindaStu

2021-11-23 09:32 UTC, LindaStu commented
Fertigstellung Kanban Pull Prinzip und Projektkommunikation

2021-11-27 15:21 UTC, Kisara2426 requested changes
| Kriterium | Bewertung|
|-----|---|
| Front-Matter | ja/ nein |
| Umfang | ja/ nein|
| Belege | ja/ nein |
| Links | ja/ nein|
| Formatierung | ja/ nein|
| Verlinkungen vorhanden | ja/ nein |
| Abbildungen | ja/ nein |
| Strukturierung des Beitrags | 1-10 |
| Rechtschreibung | 1-10|
| Sprache | 1-10 |
| Inhalt | 1-10|
| Einordnung in den Kontext | 1-10|
| Ansprechend für Zielgruppe | 1-10|

# Zusammenfassung

Kurze Zusammenfassung des/der Artikel

# Positive Aspekte

Was ist gut (Bezug zur Tabelle)

# Negative Aspekte

Was geht besser (Bezug zur Tabelle)

2021-11-27 17:30 UTC, Lorybr requested changes
| Kriterium | Bewertung|
|-----|---|
| Front-Matter | ja |
| Umfang | ja|
| Belege | ja |
| Links | ja|
| Formatierung | ja|
| Verlinkungen vorhanden | ja |
| Abbildungen | ja |
| Strukturierung des Beitrags | 10 |
| Rechtschreibung | 8|
| Sprache | 10 |
| Inhalt | 10|
| Einordnung in den Kontext | 10|
| Ansprechend für Zielgruppe | 10|

# Zusammenfassung

Der Artikel befasst sich mit dem Kanban Pull-Prinzip, indem erklärt wird wie das Pull-Prinzip funktioniert sowie dessen Vor-und Nachteile.

# Positive Aspekte
Alles wurde klar Formuliert. Die angrenzende Themen aus dem Kompendium wurden oft verlinkt. Der Beitrag wurde ansprechend gegliedert und weist hauptsächlich eine Formalität auf.

# Negative Aspekte
Ich würde das Bild sachlicher adressieren, z.B nicht ,, Wie Sie hier in der Graphik sehen können", sondern ,,Wie man hier in der Graphik sehen kann.."
In dem letzten Absatz fehlt bei "bedarf" ein Komma davor und der richtige Artikel "..bedarf es einer richtigen Strategie.."
Beachte auch andere Kommas ;)

2021-12-05 09:44 UTC, domirow-fau requested changes
| Kriterium | Bewertung|
|-----|---|
| Front-Matter | ja |
| Umfang | nein |
| Belege | ja |
| Links | ja |
| Formatierung | ja |
| Verlinkungen vorhanden | ja |
| Abbildungen | ja |
| Strukturierung des Beitrags | 10 |
| Rechtschreibung | 10 |
| Sprache | 10 |
| Inhalt | 10 |
| Einordnung in den Kontext | 8 |
| Ansprechend für Zielgruppe | 9 |

# Zusammenfassung

Der Artikel befasst sich mit dem Kanban-Pull-Prinzip. Hierbei wird die Methode definiert und auf Vor- sowie Nachteile eingegangen. Die Ausdrucksweise bleibt hierbei stets sachlich und klar verständlich, die sehr gute Rechtschreibung untermauert den sprachlichen Anspruch. Die Leser:innen werden mithilfe einer sehr guten Struktur durch den Beitrag geführt und können durch Querverweise am Ende des Artikels ihr Wissen noch weiter vertiefen. 

# Positive Aspekte

- alle Belege sind ausreichend gesetzt und funktionieren
- die Formatierung und Struktur des Artikels überzeugen
- eine sehr gute Abbildung zur schnellen, grafischen Übersicht der Methode wurde eingebettet
- Sprache und Rechtschreibung sind stets passend gewählt und fehlerfrei
- inhaltlich stellt der Artikel eine sehr gute Wissensvermittlung bereit
- "Siehe auch" und "Weiterführende Literatur" laden zur Wissensvertiefung ein

# Negative Aspekte

- der Artikel hat großzügig gezählt leider nur 486 Wörter; evtl. kann noch ein Fazit eingebaut werden, um die geforderte Wortanzahl zu erreichen
- die Abbildung trägt keinen Quellverweis
- in dem Artikel selbst könnte noch mit weiteren Verlinkungen zu anderen Artikeln gearbeitet werden, um die Einordnung in den Kontext zu untermauern

2021-12-09 19:27 UTC, merged