1. Version
ManagingProjectsSuccessfully/ManagingProjectsSuccessfully.github.io pull request #76
Opened 2021-11-20 10:27 UTC by Lorybr

Projektmanagement_Fallstricken und Scrum_Transparenz

2021-11-23 09:39 UTC, Lorybr commented
Paar Veränderungen.

2021-11-27 15:40 UTC, Kisara2426 requested changes
# Scrum_Transparenz 

| Kriterium | Bewertung|
|-----|---|
| Front-Matter | ja/ nein |
| Umfang | ja/ nein|
| Belege | ja/ nein |
| Links | ja/ nein|
| Formatierung | ja/ nein|
| Verlinkungen vorhanden | ja/ nein |
| Abbildungen | ja/ nein |
| Strukturierung des Beitrags | 1-10 |
| Rechtschreibung | 1-10|
| Sprache | 1-10 |
| Inhalt | 1-10|
| Einordnung in den Kontext | 1-10|
| Ansprechend für Zielgruppe | 1-10|

# Zusammenfassung

Kurze Zusammenfassung des/der Artikel

# Positive Aspekte

Was ist gut (Bezug zur Tabelle)

# Negative Aspekte

Was geht besser (Bezug zur Tabelle)

# Typische Projektmanagement Fallstricke 

| Kriterium | Bewertung|
|-----|---|
| Front-Matter | ja/ nein |
| Umfang | ja/ nein|
| Belege | ja/ nein |
| Links | ja/ nein|
| Formatierung | ja/ nein|
| Verlinkungen vorhanden | ja/ nein |
| Abbildungen | ja/ nein |
| Strukturierung des Beitrags | 1-10 |
| Rechtschreibung | 1-10|
| Sprache | 1-10 |
| Inhalt | 1-10|
| Einordnung in den Kontext | 1-10|
| Ansprechend für Zielgruppe | 1-10|

# Zusammenfassung

Kurze Zusammenfassung des/der Artikel

# Positive Aspekte

Was ist gut (Bezug zur Tabelle)

# Negative Aspekte

Was geht besser (Bezug zur Tabelle)

2021-12-01 15:43 UTC, Kisara2426 requested changes
komment

2021-12-04 15:45 UTC, domirow-fau requested changes
| Kriterium | Bewertung|
|-----|---|
| Front-Matter | ja |
| Umfang | ja |
| Belege | ja |
| Links | ja |
| Formatierung | ja |
| Verlinkungen vorhanden | ja |
| Abbildungen | ja |
| Strukturierung des Beitrags | 9 |
| Rechtschreibung | 8 |
| Sprache | 6 |
| Inhalt | 9 |
| Einordnung in den Kontext | 9 |
| Ansprechend für Zielgruppe | 9 |

# Zusammenfassung

Der Artikel befasst sich in gut strukturierter Weise mit der Scrum-Transparenz. Diese Begrifflichkeit wird ebenfalls im Gesamtkontext eingepasst und bietet den Leser:innen so einen guten Anhaltspunkt zur Wissensvertiefung. Auch die Abbildung veranschaulicht die Einordnung auf den ersten Blick.

# Positive Aspekte

- sehr gute Struktur mithilfe von Nummerierung
- sehr gute Einordnung in den SCRUM-Kontext
- alle Abschnitte und auch die Abbildung sind durch Quellen belegt
- der Inhalt ist relevant und bietet eine gute Möglichkeit zur Wissensvertiefung
- der Artikel bietet ein Inhaltsverzeichnis
- der Artikel bietet weiterführende Literatur

# Negative Aspekte

- eventuell kann das Inhaltsverzeichnis selbst noch mit den Überschriften verlinkt sein
- sprachlich gibt es stärkeres Ausbaupotenzial, was sich aber durch intensiveres Korrekturlesen schnell lösen lässt
- die Rechtschreibung ist eigentlich gut; Fehler hier sind wohl eher Folgen des sprachlichen Ausdrucks
- im Front-Matter könnten noch ein paar Tags hinzugefügt werden

2021-12-06 13:23 UTC, elainevmd requested changes
| Kriterium | Bewertung|
|-----|---|
| Front-Matter | ja |
| Umfang | ja |
| Belege | ja |
| Links | ja |
| Formatierung | ja |
| Verlinkungen vorhanden | ja |
| Abbildungen | ja |
| Strukturierung des Beitrags | 10 |
| Rechtschreibung | 8 |
| Sprache | 7 |
| Inhalt | 9 |
| Einordnung in den Kontext | 10 |
| Ansprechend für Zielgruppe |10|

# Zusammenfassung

Der Artikel behandelt die Scrum Transparenz indem zunächst die Problemstellung und anschließend die Definition und Merkmale erläutert werden. Abschließend gibt es ein Fazit. 

# Positive Aspekte

Gut finde ich die nummerierten Überschriften, da diese direkt einen Überblick über die Inhalte geben. Der Scrum Kontext ist gut eingebettet und die Abbildung gibt direkt einen Überblick über den kommenden Inhalt. 

# Negative Aspekte

Sprachlich könnte man den Artikel noch etwas überarbeiten. Bei 1.0 muss noch ein Leerzeichen zwischen die Nummer und die Überschrift. Bei der weiterführenden Literatur lassen sich die Links nicht wie bei den Quellen direkt anklicken.

2021-12-09 19:27 UTC, merged