Best_Practices
ManagingProjectsSuccessfully/ManagingProjectsSuccessfully.github.io pull request #85
Opened 2021-11-21 18:35 UTC by tobi0211

2021-11-28 19:43 UTC, BelmontR requested changes
| Kriterium | Bewertung|
|-----|---|
| Front-Matter | ja|
| Umfang | ja|
| Belege | ja|
| Links |nein|
| Formatierung | ja|
| Verlinkungen vorhanden | nein|
| Abbildungen | ja |
| Strukturierung des Beitrags | 10 |
| Rechtschreibung | 8|
| Sprache | 9 |
| Inhalt | 9|
| Einordnung in den Kontext |6|
| Ansprechend für Zielgruppe | 8|

# Zusammenfassung

Der Artikel zählt sechs "Best Practices" auf und führt sie aus.

# Positive Aspekte
Keine Rechtschreib- bzw. Tippfehler, auch sowohl sprachlich als auch inhaltlich gut ausgearbeitet. Der Artikel ist sehr übersichtlich und gut strukturiert.

# Negative Aspekte
Die Kurzbeschreibung am Anfang ist viel mehr eine Einleitung als eine Kurzbeschreibung; Die im Text eingebetteten Links funktionieren nicht; Grammatik-Fehler im ersten Satz von Überschrift 5; Quellen werden immer nach dem Punkt angegeben, sollten aber vor dem Punkt gesetzt werden (Also " blabla[^1]." statt " blabla.[^1]"); Die Doppelpunkte bei den Überschriften sind unnötig. "Siehe auch" und "Weiterführende Literatur" fehlen

2021-12-01 19:01 UTC, tobi0211 commented
@BelmontR Eine Frage zu deinem Review: Bist du dir sicher, dass man Fußnoten vor einem Punkt setzt? Ich kenne das nämlich eigentlich so, dass Fußnoten nach einem Punkt gesetzt werden und nicht vor einem Punkt. 
Sorry übrigens, dass man meine vorgenommenen Änderungen schon direkt im Pull Request sehen kann, ich wollte das eigtl. nur in meinem Repository ändern.

2021-12-01 19:35 UTC, BelmontR commented
@tobi0211 Hi, ich war mir da anfangs auch nicht ganz sicher, aber ich hab mir dann nochmal den Beispieltext angeschaut, der in der .md Datei am Anfang stand und da waren die Fußnoten auch vor dem Punkt. Ist jetzt echt keine große Sache und ich denk jetzt nicht, dass es unbedingt falsch ist, wenn du das anders machst, aber es mir nur aufgefallen. Ist eher ne kleine Formalität, I guess ^^.
![Screenshot](https://user-images.githubusercontent.com/47500226/144301426-0b155ce8-8b30-4b2f-a33c-8cf3ead239b3.PNG)
.

2021-12-01 20:47 UTC, Irishcoffee09 requested changes
| Kriterium | Bewertung|
|-----|---|
| Front-Matter | ja |
| Umfang | ja |
| Belege | ja |
| Links | ja |
| Formatierung | ja |
| Verlinkungen vorhanden | ja |
| Abbildungen | ja |
| Strukturierung des Beitrags | 10 |
| Rechtschreibung | 10|
| Sprache | 9 |
| Inhalt | 9 |
| Einordnung in den Kontext | 9 |
| Ansprechend für Zielgruppe | 10|

# Zusammenfassung

Der Artikel behandelt die Best Practices, die ein Vergessen von wichtigen Punkten in der Projektplanung verhindern sollen. Es werden sechs bewährte Vorgehensweisen genauer erläutert.

# Positive Aspekte

Positiv hervorzuheben ist die Struktur und der Aufbau des Beitrags. Die Einleitung stellt kurz das Problem einer detaillierten Projektplanung dar und somit die Notwendigkeit von Best Practices. Im Folgenden wird auf jede Methode ausführlich eingegangen. Auch die Auswahl dieser bestimmten sechs Methoden ist gut getroffen. Der Artikel ist verständlich geschrieben und weckt das Interesse an dem Thema.

Durch eine Abbildung werden Projektphasen und Arbeitspakete in einem Zeitplan visualisiert. Die Illustration ist sinnvoll im Kontext eingebettet und wird zusätzlich noch sehr gut erläutert.

Verlinkungen im Fließtext funktionieren und sind gut gewählt. Die verwendeten Quellen sind ausreichend und es liegen keine Rechtschreibfehler und Grammatikfehler vor. 


# Negative Aspekte

Es wurde zwar eine gute Einleitung verfasst, aber es handelt sich hierbei weniger um die geforderte Kurzzusammenfassung, weil man noch nicht auf Anhieb versteht, was Best Practices sind. Man könnte z.B. noch einen kleinen Einschub machen wie folgt: „Um dies zu verhindern, kann auf bestimmte/bewährte Methoden, sogenannte Best Practices zurückgegriffen werden.“, damit man als Laie gleich versteht, dass es sich um bewährte Methoden der Vorgehensweise handelt.

Leider ist am Ende des Beitrags keine weiterführende Literatur vorhanden.

2021-12-04 11:05 UTC, jnsdhr requested changes
| Kriterium | Bewertung|
|-----|---|
| Front-Matter | ja |
| Umfang | ja |
| Belege | ja |
| Links | ja |
| Formatierung | ja |
| Verlinkungen vorhanden | ja |
| Abbildungen | ja |
| Strukturierung des Beitrags | 10 |
| Rechtschreibung | 9 |
| Sprache | 9 |
| Inhalt | 9 |
| Einordnung in den Kontext | 10 |
| Ansprechend für Zielgruppe | 10 |

# Zusammenfassung

Der Artikel beschäftigt sich mit sechs Best Practices. Die Einhaltung dieser Practices soll zur Fehlervermeidung führen, sodass der maximale Projekterfolg gewährleistet werden kann. 

# Positive Aspekte

Der Artikel ist sehr gut strukturiert, sehr sachlich und ansprechend für die Zielgruppe geschrieben und gliedert sich in die sechs wichtigsten Practices. Die Graphik wurde zur Illustration passend eingebaut und passt an sich gut in den Kontext des Beitrags. Alle Links funktionieren und es gibt keine syntaktischen Fehler zu beanstanden. Man merkt, dass sich viel Mühe gegeben wurde. 

# Negative Aspekte

Bei den Quellen könnte man so zitieren, dass nicht der Link an sich, sondern sozusagen die Überschrift des Links angezeigt wird. Zum Beispiel: [10 Best Practices](https://www.wrike.com/de/blog/10-best-practices-im-projektmanagement/). Ansonsten könntest du beim 3. Punkt die Wortwiederholung "Durch das" vermeiden. Im 2. Punkt heißt es zudem "Konflikten" statt "Konflikte".  Auch könnte man die Einleitung so verändern, dass einem Laien schneller klar wird, was Best Practices sind.

2021-12-09 19:27 UTC, merged