Spotify Projektmanagement / Spotify Modell
ManagingProjectsSuccessfully/ManagingProjectsSuccessfully.github.io pull request #86
Opened 2021-11-21 19:39 UTC by BelmontR

2021-11-27 08:05 UTC, JanEhrFAU commented on kb/Spotify_Projectmanagement_Model.md
> +Das Unternehmen Spotify setzte noch zu Beginn das [SCRUM](SCRUM.md) Projektmanagement um. Nachdem Spotify mit der Zeit größer wurde, passten nicht mehr alle Prinzipien und Regeln von [[SCRUM](SCRUM.m
```suggestion
Das Unternehmen Spotify setzte zu Beginn noch das [SCRUM](SCRUM.md) Projektmanagement um. Nachdem Spotify mit der Zeit größer wurde, passten nicht mehr alle Prinzipien und Regeln von [SCRUM](SCRUM.md) zum Unternehmen und der Unternehmenskultur. Basierend auf [SCRUM](SCRUM.md) bzw. aus [SCRUM](SCRUM.md) heraus hat Spotify ein eigenes Projektmanagementmodell angefertigt[^1]. 
```

2021-11-27 08:42 UTC, JanEhrFAU requested changes
| Kriterium | Bewertung|
|-----|---|
| Front-Matter | ja |
| Umfang | ja|
| Belege | ja |
| Links | ja|
| Formatierung | ja|
| Verlinkungen vorhanden | ja |
| Abbildungen | ja |
| Strukturierung des Beitrags | 9 |
| Rechtschreibung | 6 |
| Sprache | 8 |
| Inhalt | 8 |
| Einordnung in den Kontext | 7 |
| Ansprechend für Zielgruppe | 9 |

# Zusammenfassung

Der Artikel zählt die Bausteine des Projektmanagementmodells von Spotify auf. 

# Positive Aspekte

Übersichtlichkeit, Verständlichkeit, Struktur

# Negative Aspekte

Rechtschreibung, Keine einheitliche Formatierung (Spotify Modell/ Spotify-Modell), Einzelnes Thema nur einmal verlinken, Evtl. kurz Eingehen auf Vorgehensweise in Projekten für mehr Einsicht

2021-12-01 12:44 UTC, Irishcoffee09 requested changes
| Kriterium | Bewertung|
|-----|---|
| Front-Matter | ja |
| Umfang | ja |
| Belege | ja |
| Links | ja |
| Formatierung | ja |
| Verlinkungen vorhanden | ja |
| Abbildungen | ja |
| Strukturierung des Beitrags | 8 |
| Rechtschreibung | 5 |
| Sprache | 7 |
| Inhalt | 8 |
| Einordnung in den Kontext | 10 |
| Ansprechend für Zielgruppe | 9 |

# Zusammenfassung

Der Artikel behandelt das Spotify Project Management. Die vier Hauptkomponenten (Squads, Tribes, Chapters und Guilds) sowie die Aufgabenbereiche dieser werden genau erklärt und im Anschluss wird auf die Umsetzung des Spotify Modells in klassischen Unternehmen eingegangen.

# Positive Aspekte

Positiv hervorzuheben ist die gute Einleitung, in der erläutert wird, warum es das Spotify-Modell gibt und woraus es besteht. Die erste Abbildung ist am Anfang auch gut verortet. Durch sie bekommt man gleich einen groben Überblick, wie man sich das Modell vorstellen kann. Der Artikel ist durch die Überschriften gut strukturiert und visuell ist der Beitrag durch die zwei Abbildungen gut gestaltet. Die Quellen wurden richtig zitiert und Verlinkungen zu ausgewählten Begriffen funktionieren. Ebenso ist weiterführende Literatur vorhanden.

# Negative Aspekte

Leider sind einige Rechtschreib- und Grammatikfehler vorhanden, z.B.: „…gibt es Product Owner, welche…vorgibt“ (Singular/Plural) oder „Zusätzlich haz jedes Squad…“ oder „Fachkompetnezen“. Die zweite Abbildung mit den verschiedenen Meetings, wird etwas zusammenhangslos eingebettet ohne Überschrift oder ausreichende Überleitung. Zudem könnte man noch eine weitere Überschrift einbauen, welche die Bestandteile des Models von der Umsetzung in klassischen Unternehmen optisch abgrenzt.

2021-12-03 11:07 UTC, jnsdhr requested changes
| Kriterium | Bewertung|
|-----|---|
| Front-Matter | ja |
| Umfang | ja |
| Belege | ja |
| Links | ja |
| Formatierung | ja |
| Verlinkungen vorhanden | ja |
| Abbildungen | ja |
| Strukturierung des Beitrags | 9 |
| Rechtschreibung | 4 |
| Sprache | 6 |
| Inhalt | 9 |
| Einordnung in den Kontext | 9 |
| Ansprechend für Zielgruppe | 9 |

# Zusammenfassung

Der Artikel beschäftigt sich mit Projektmanagement am Beispiel von Spotify. Nachdem zum Thema hingeführt wird, werden Squads, Tribes, Chapters und Guilds genauer erläutert. Zuletzt wird erklärt, wie das Spotify-Modell in klassischen Unternehmen umgesetzt wird. 

# Positive Aspekte

Die Einleitung führt gut zum Thema hin. Der Artikel ist allgemein gut strukturiert und unterteilt sich vor allem in die vier Hauptkomponenten. Die Graphik ist dabei sehr gut gewählt.  Der etwas komplexere Inhalt wird zumeist verständlich erklärt. Quellen sind richtig zitiert und hinsichtlich Formatierung gibt es keine Fehler. 

# Negative Aspekte

Leider gibt es einige Rechtschreibfehler wie "Umsetztung", "haz", " wo bei", "Fachkompetnezen" oder "ihrem Gebiete". Bei der Erklärung der tribes hast du dich vertippt und statt "ist" "ich" geschrieben.  Nach "crossfunktional" kommt ein "und". Bei Product Owner muss es "vorgeben" heißen, wechsle nicht zw. Singular und Plural. Wenn über "Squad" geschrieben wird, schreibst du manchmal "jeder" bzw. "jedes" Squad. Auch bei dem Begriff Spotify-Modell sollte Einheitlichkeit eingehalten werden, entweder mit oder ohne Bindestrich. Zum Teil sind die Sätze auch so verschachtelt, dass sie unverständlich sind. Den allerletzten Satz könntest du zum Beispiel wiederum in zwei Sätze aufsplitten. Eventuell hätten die Begriffe "Sprint planning Meeting" und "Retroperspektive" erklärt werden können.

2021-12-09 19:27 UTC, merged