8_Step_process_for_Leading_Change | PEST_Analyse
ManagingProjectsSuccessfully/ManagingProjectsSuccessfully.github.io pull request #95
Opened 2021-11-22 12:20 UTC by GEDA9263

2021-12-01 14:19 UTC, Steffi226 requested changes
| Kriterium | Bewertung|
|-----|---|
| Front-Matter | nein |
| Umfang | ja|
| Belege | ja|
| Links | ja|
| Formatierung | ja|
| Verlinkungen vorhanden | ja|
| Abbildungen | ja|
| Strukturierung des Beitrags |10 |
| Rechtschreibung | 9|
| Sprache | 10|
| Inhalt | 10|
| Einordnung in den Kontext | 10|
| Ansprechend für Zielgruppe | 10|

Tabelle gilt für beide Artikel.

# Zusammenfassung zu "8_Step_process_for_Leading_Change"

Das "8_Step_process_for_Leading_Change" beschreibt, wie in acht Schritten Veränderungen impliziert werden können

# Positive Aspekte "8_Step_process_for_Leading_Change"

Der Artikel ist sehr gut durchstrukturiert und die einzelnen Absätze sind treffend formuliert. Die verwendete Abbildung ist gut lesbar und verschafft einen Überblick über die acht Stufen. 
Positiv sind außerdem die vielen Verlinkungen zu angrenzenden Artikeln, sowie die Quellen, deren Links alle tadellos funktionieren.


# Negative Aspekte "8_Step_process_for_Leading_Change"

Negativ sind nur zwei kleine Rechtschreibfehler aufgefallen. Unter "1. Erzeugen eines Dringlichkeitsgefühls" im ersten Satz das sechste Wort müsste wohl "es" statt "er" lauten.
Unter "2. Aufbauen einer Führungskoalition" im dritten Satz müsste es "ein gemeinsames Ziel" heißen.
Außerdem könnte das "Front-Matter" also ein  kleiner Einführungstext ganz am Anfang ergänzt werden.

# Zusammenfassung "PEST-Analyse"

Die PEST-Analyse dient dazu, externe Einflussfaktoren, sowie Chancen und Risiken zu erkennen. 

# Positive Aspekte zu "PEST-Analyse"

Auch dieser Artikel ist gut strukturiert, besonders die kleinen Tabellen, die die einzelnen Einflussfaktoren beschreiben sind sehr gut gelungen.
Die weiteren Schritte sind  ebenfalls sehr ausführlich beschrieben.
Die Verlinkungen zu den angrenzenden Themen sind gut platziert und funktionieren, genau wie die Links zu den Quellen problemlos. 


# Negative Aspekte zu "PEST-Analyse"

Der Artikel ist insgesamt sehr gut gelungen, einzig könnte  auch hier das "Front-Matter" also ein  kleiner Einführungstext ganz am Anfang ergänzt werden.

2021-12-07 09:33 UTC, Magnus-schn reviewed
8_Step_process_for_Leading_Change

| Kriterium | Bewertung|
|-----|---|
| Front-Matter | ja|
| Umfang | ja|
| Belege | ja|
| Links | ja|
| Formatierung | ja|
| Verlinkungen vorhanden | ja|
| Abbildungen | ja |
| Strukturierung des Beitrags | 10 |
| Rechtschreibung | 10|
| Sprache | 10 |
| Inhalt | 10|
| Einordnung in den Kontext | 10|
| Ansprechend für Zielgruppe | 10|

# Zusammenfassung

Der Artikel befasst sich mit dem 8 Stufen Prozess eines Veränderungsprozesses und geht dabei auf Fehler im Change Management ein und erklärt wie man diese möglichst umgehen kann.

# Positive Aspekte

Neben einer passenden Abbildung liefert der Artikel alle benötigten Informationen und spricht gleichzeitig mit einem gelungenen Aufbau den Leser an.

# Negative Aspekte

Siehe auch: Link auf diese Seite entfernen und eine Kurzbeschreibung sind noch einzufügen. Ansonsten ist der Artikel aus meiner Sicht bereits fertig.

PEST_Analyse
| Kriterium | Bewertung|
|-----|---|
| Front-Matter | ja |
| Umfang | ja|
| Belege | ja|
| Links | ja|
| Formatierung | ja|
| Verlinkungen vorhanden | ja|
| Abbildungen | ja |
| Strukturierung des Beitrags | 10 |
| Rechtschreibung | 10|
| Sprache | 10 |
| Inhalt | 10|
| Einordnung in den Kontext | 10|
| Ansprechend für Zielgruppe | 10|

# Zusammenfassung

Der Artikel befasst sich mit der Pest Analyse und geht dabei auf die einzelnen Aspekte dieser Umfeldanalyse eine, als auch auf den Ablauf einer Durchführung.

# Positive Aspekte

Sehr gelungene Struktur, insbesondere aufgrund der Aufteilung auf einzelne und kleine Tabellen. Des Weiteren ist die Aufteilung in Organisation und Projekt aufschlussreich und passend für das Projektmanagement.

# Negative Aspekte

Es fehlt noch die Kurzbeschreibung am Anfang des Artikels. Ansonsten ist der Artikel bereits fertig.

2021-12-07 16:30 UTC, DanielLeiLei requested changes
| Kriterium | Bewertung|
|-----|---|
| Front-Matter | ja |
| Umfang | ja/ |
| Belege | ja|
| Links | ja|
| Formatierung | ja|
| Verlinkungen vorhanden | ja |
| Abbildungen | ja |
| Strukturierung des Beitrags | 10 |
| Rechtschreibung | 3|
| Sprache | 3 |
| Inhalt | 9 |
| Einordnung in den Kontext | 10|
| Ansprechend für Zielgruppe | 9 |

# Zusammenfassung
Der Beitrag befasst sich mit den in 8-Stufen aufgeteilten Prozess im Bereich des Veränderungsmanagements in Unternehmen. Da Veränderungen und das Umsetzen dieser meist mit Projekten verbunden ist, ergibt sich hier ein Berührungspunkt mit dem Projektmanagement. Zusätzlich kann das 8-Stufen Modells auch innerhalb beliebiger Projekte als ein ergänzendes und zielführendes System zum jeweiligen Projektmanagement gesehen werden.

# Positive Aspekte
Der Beitrag ist sehr gut strukturiert und inhaltlich gut dargestellt. Die 8-Phasen werden schrittweise an den Leser herangeführt. Die Grafik am Anfang ist passend platziert und schafft eine gute Übersicht --> Allerdings ist die Grafik auf Englisch, die folgenden Kapitelüberschriften jedoch auf Deutsch. Hier sollte evtl. hinter der Deutschen Überschrift die Verbindung mit der Grafik hergestellt werden indem die englische Bezeichnung in Klammern dahinter gesetzt wird.

# Negative Aspekte
Hauptsächlich Rechtschreibfehler und die gewählte Sprache (nicht wissenschaftlich an einigen Stellen) entwerten den sonst sehr gut zusammengefassten Inhalt des Beitrags. 
Am besten den Text kopieren und in Word einfügen und dort die automatische Rechtschreibprüfung durchführen - dadurch können einige Fehler direkt erkannt werden.
Zusätzlich sollten einige Wörter anders gewählt werden, um den wissenschaftlichen Anspruch gerecht zu werden sowie Adjektive in bestimmten Bereichen vermieden werden, da diese Inhalte bewerten. Die Bewertung der Inhalte war allerdings von den Dozenten ausdrücklich nicht erwünscht, sondern nur die Wiedergabe.
Beispiele: "eines Veränderungsprozesses ist eines der beliebtesten" --> Eher "ein bewährtes", zusätzlich nicht zweimal "eines" innerhalb des gleichen Satzes.
"greifbar ist führen erste erfolgreiche etablierten Veränderungen zu einem Wandel der " --> erste erfolgreiche etabliertE Veränderungen zu einem Wandel der "....
" und einfache vorstellbare Botschaften zu kreieren, welche die Mitarbeitenden dazu inspirert Großes zu vollbringe" --> dazu inspiriereN Großes zu vollbringeN". 
Zusätzlich evtl. für einige Begriffe wissenchaftlichere Synonyme suchen bzw. die Sätze generell umschreiben/kürzer und neutraler halten.

2021-12-08 18:22 UTC, DanielLeiLei requested changes
| Kriterium | Bewertung|
|-----|---|
| Front-Matter | ja/ nein |
| Umfang | ja/ nein|
| Belege | ja/ nein |
| Links | ja/ nein|
| Formatierung | ja/ nein|
| Verlinkungen vorhanden | ja/ nein |
| Abbildungen | ja/ nein |
| Strukturierung des Beitrags | 1-10 |
| Rechtschreibung | 1-10|
| Sprache | 1-10 |
| Inhalt | 1-10|
| Einordnung in den Kontext | 1-10|
| Ansprechend für Zielgruppe | 1-10|

# Zusammenfassung

Kurze Zusammenfassung des/der Artikel

# Positive Aspekte

Was ist gut (Bezug zur Tabelle)

# Negative Aspekte

Was geht besser (Bezug zur Tabelle)

2021-12-09 19:27 UTC, merged