Abgabe
ManagingProjectsSuccessfully/ManagingProjectsSuccessfully.github.io pull request #96
Opened 2021-11-22 12:27 UTC by DanielLeiLei

2021-11-29 14:43 UTC, Steffi226 requested changes
| Kriterium | Bewertung|
|-----|---|
| Front-Matter | ja |
| Umfang | ja|
| Belege | ja |
| Links | ja|
| Formatierung | ja|
| Verlinkungen vorhanden | nein |
| Abbildungen | ja|
| Strukturierung des Beitrags |10 |
| Rechtschreibung |10|
| Sprache |10 |
| Inhalt |10|
| Einordnung in den Kontext | 10|
| Ansprechend für Zielgruppe | 10|

# Zusammenfassung
Der Artikel beschäftigt sich mit der Global Project Management Survey, die bereits durchgeführte Projekte untersucht, um verschiedene Erkenntnisse über diese zu treffen.

# Positive Aspekte
Der Artikel ist äußerst ausführlich und anschaulich gestaltet und sämtliche Abbildungen wurden thematisch passend in den Artikel eingearbeitet.
Der kleine Einführungstext am Anfang des Artikels ist treffend formuliert und gibt einen guten Einstieg in das Thema. 
Der Beitrag ist ebenfalls gut strukturiert und sprachlich ansprechend gestaltet.


# Negative Aspekte
Im Absatz "Historische Entwicklung und aktueller Stand zu den Global Project Management Surveys" fehlt im letztes Satz bei dem Wort "Veröffentlichung" das "h".
Wie im Artikel bereits selbst angemerkt, müssen noch die Verlinkungen zu angrenzenden Themen erfolgen.

2021-12-07 09:26 UTC, Magnus-schn reviewed
| Kriterium | Bewertung|
|-----|---|
| Front-Matter | ja |
| Umfang | ja|
| Belege | ja|
| Links |  nein|
| Formatierung | ja|
| Verlinkungen vorhanden |  nein |
| Abbildungen | ja |
| Strukturierung des Beitrags | 8|
| Rechtschreibung | 8 |
| Sprache | 9 |
| Inhalt | 10|
| Einordnung in den Kontext | 10|
| Ansprechend für Zielgruppe | 1-10|

# Zusammenfassung

Der Artikel befasst sich mit einer Globalen Umfrage zu Projektmanagement. Diese hilft unternehmen dabei Fehler Quellen zu finden und Leitfäden für das Projektmanagement zu entwickeln.

# Positive Aspekte

Sehr umfangreicher Artikel, der mithilfe von vielen Abbildungen sehr anschaulich ist und Interesse weckt beim Leser.

# Negative Aspekte

Der Link Datenbank zur Informationsfilterung funktioniert nicht. Kurz vor Figure 3: Zugeordnet ohne Bindestrich. Es könnten noch Verlinkungen zu anderen Artikeln des Kompendiums hinzugefügt werden. Auch die Überschriften könnten noch etwas abgekürzt werden, da sie etwas überladen wirken.

2021-12-07 19:54 UTC, AbleAn requested changes
| Kriterium | Bewertung|
|-----|---|
| Front-Matter | ja |
| Umfang | ja |
| Belege | ja |
| Links |  nein|
| Formatierung | ja|
| Verlinkungen vorhanden | ja |
| Abbildungen | ja |
| Strukturierung des Beitrags | 10 |
| Rechtschreibung | 9|
| Sprache | 10 |
| Inhalt | 10|
| Einordnung in den Kontext | 9 |
| Ansprechend für Zielgruppe | 10|

# Zusammenfassung

Der Artikel befasst sich mit den Global_Project_Management_Survey. Nach einer kleinen Einführung werden Eckdaten und Erkenntnisse aus dem PMI vorgestellt.

# Positive Aspekte

Der Artikel ist anschaulich gestaltet und gibt zusammen mit den Abbildungen ein sehr gutes Bild ab. Die Struktur ist gut nachvollziehbar und man bekommt einen guten Einstieg in die Thematik. Sprachlich ist der Artikel auf einem hohen Niveau und angenehm zu lesen.

# Negative Aspekte

Es haben sich ein paar Typos eingeschlichen: 
Letzte Zeile beim Absatz historische Entwicklung -> Veröffentlichung
Bei den Eckdaten der siebte Punkt -> traditionellen
Nach figure 2 im ersten Absatz letzter Satz -> Ergebnisse
Im Satz darauf -> zugeordnet
Nach figure 4 -> technologische


Die erste Abbildung würde ich persönlich weglassen. Wie im Text bereits angesprochen, sollten noch Verlinkungen zu angrenzenden Themen eingefügt werden.

2021-12-09 19:27 UTC, merged

2021-12-20 11:31 UTC, DanielLeiLei commented
> 


Ich habe den Link nochmal geprüft - bei mir funktioniert er. Vielleicht liegt es am Browser? 
Würde das nochmal mit anderen Browsern testen.